### ISSUE TITLE
Add highlight source for recommendation links

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1007]
To support feature #935, we need to add a `type` field to the recommendation links. 

Once we add recommendations, let's start tracking what the source of an item that gets clicked on is in highlights, in addition to its position. This should be one of:

* bookmark
* history item
* recommendation
* synced tabs (once we show them)

**Comment by oyiptong** [comment]
closing because it has already been implemented

**Comment by ncloudioj** [comment]
Re-open this one to correct myself in the triage, this is not implemented yet. I think it's a P3 chore one.
