### ISSUE TITLE
Add a sorting mechanism for highlights based on weights/score

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#1010]
As a user of AS I want more than just 3 recommendations, the highlights section should expand to replace recent activity.

Deliver an initial option to score highlights and allow for more than 3 results.
Recommendations that do not fit in the top 3 positions will fall down into recent activity.
This will also help drive https://github.com/mozilla/activity-stream/issues/1006 because it will make the requirements for that module more obvious.

**Comment by oyiptong** [comment]
might need to be broken up in separate issues to fit the milestones
