### ISSUE TITLE
Intermittent failure: A coding exception was thrown and uncaught - TypeError: tabs.activeTab is null

### ISSUE THREAD

**Issue by Standard8** [mozilla/activity-stream#1013]
I'm seeing this on my Mac fairly frequently when running `npm run test:jpm`

```
JPM [error] *************************
A coding exception was thrown and uncaught in a Task.


Full message: TypeError: tabs.activeTab is null
Full stack: handlePerformanceEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/TabTracker.js:120:5
_getEnhancedLinks@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/PreviewProvider.js:226:5
getLinkMetadata@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/PreviewProvider.js:214:23
RecommendationProvider.prototype.asyncSetRecommendedContent<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/RecommendationProvider.js:90:45
TaskImpl_run@resource://gre/modules/Task.jsm:319:40

*************************
```

**Comment by Standard8** [comment]
I've been looking at this one a little, as I thought it was something I caused elsewhere.

I think what is happening is this:

- The tests are creating new `ActivityStream` objects fairly frequently.
- `ActivityStream`'s constructor is kicking off `RecommendationProvider.prototype.asyncSetRecommendedContent`
- The `asyncSetRecommendedContent` is then going off to get data from Pocket.
- In the meantime a test finishes, closes the windows/tabs associated with it.
- The result from Pocket comes back, and it attempts to get the metadata `this._previewProvider.getLinkMetadata`
- However, there's now no tabs available, so this throws.

I think changing the call in the `ActivityStream` constructor to be a yield, does actually stop this happening. However, I believe that then would wait for pocket's response before continuing, which is something we probably don't want to be doing in production.

So I'm not quite sure of the best way froward here.

**Comment by rlr** [comment]
We probably don't want to be calling pocket in tests except for in the tests for the recommendation feature. @sarracini @oyiptong thoughts?

**Comment by oyiptong** [comment]
We surely do not want to do that
