### ISSUE TITLE
Collect addon errors via Sentry?

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-stream#1016]
Would be useful to keep track of errors occurring in the addon

**Comment by oyiptong** [comment]
@edmoz could we see if we can add that to our TOS?

**Comment by pdehaan** [comment]
Ref: **Add Sentry tooling to front-end** #747

@edmoz to follow up w/ Legal today, re: adding Sentry.

**Comment by edmoz** [comment]
Ping'd legal again today.  I believe next step is to get an update PN drafted.

**Comment by jaredkerim** [comment]
Closing as a duplicate of #747
