### ISSUE TITLE
Create an experiment using local page meta data parsing

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#1017]
Let's create a MVP (basic) experiment that uses local page meta data parsing with the goal of testing and iterating over the ruleset.

**Comment by edmoz** [comment]
Nick wants to block on having a meeting about how we want to roll out local metadata parsing.

**Comment by edmoz** [comment]
this is dependent on: https://github.com/mozilla/page-metadata-service/issues/56

From my usage, we're ready to run an experiment on more users.  Do we need any other user feedback signals before we can launch this @nchapman @aaronrbenson

**Comment by pdehaan** [comment]
**Local testing:**

1. Open `about:config` and accept responsibility for your life decisions.
2. Set the `extensions.@activity-streams.embedly.endpoint` pref to `https://metadata.dev.mozaws.net/v1/metadata` (dev server)

**Comment by edmoz** [comment]
QE and UX are 👍 on releasing as an experiment.

**Comment by pdehaan** [comment]
What's the status on the prod stack?

**Comment by edmoz** [comment]
I'm using this to track that work: https://github.com/mozilla/page-metadata-service/issues/56 - no word - we'll have to ask @jaredkerim

**Comment by sarracini** [comment]
Closing this - it was split up into many different bugs:
#1409, #1410, #1417, #1418, #1430, #1431, #1432, and #1467
