### ISSUE TITLE
UX design needed for using pocket.co link for recommendations

### ISSUE THREAD

**Issue by edwinwongsf** [mozilla/activity-stream#1018]
We need UX guidance on hover state of a recommendation highlight. 

Currently if you hover, you'll see `pocket.co/sHoRtUrl` in the status bar at the bottom.  Are we OK with this? Should we consider peter's suggestion:

    Maybe we should revisit adding a site to Highlights, although we'd still need to be careful to make sure users know that we're sending them to the site via Pocket servers.

    Possibly the Twitter model where we show the site domain (ie: cnn.com), and hovering over the highlight/domain shows the unshortened URL as a tooltip/title, and we leave the status bar/href to show the shortened Pocket URL. Basically, we're sending you through a proxy, but the target site is cnn.com (so you can decide if you want to click or not).

**Comment by sarracini** [comment]
Closing this since we've disabled pocket recommendations
