### ISSUE TITLE
Clicking search engine icon searches for last highlighted suggestion

### ISSUE THREAD

**Issue by pocmo** [mozilla/activity-stream#1025]
STR:
- Enter something into the search input
- Move mouse down to a search engine icon, e.g. Twitter
- Observe how search suggestions are highlighted (blue) as you move the mouse down
- When clicking on the search engine icon (e.g. Twitter) a search for the last highlighted suggestion is started and not for the text entered.

Expected:
- A search for the entered text is started.

Actual:
- A search for the highlighted suggestion is started.

<img width="777" alt="activity_stream_search_bug" src="https://cloud.githubusercontent.com/assets/89638/17367278/b2078bf8-598f-11e6-8ddc-ad87ce117900.png">

**Comment by sarracini** [comment]
Closing this as we will use the same search bar as about:newtab and about:home and will adopt the same behaviour
