### ISSUE TITLE
Bugs in Performance Graph

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1026]
A couple of issues that Olivier pointed out here:

1. There are extra dashes at the end of the version labels on the x-axis.
2. We should sort by version.

https://sql.telemetry.mozilla.org/queries/349/source#585

**Comment by ncloudioj** [comment]
FYI, for the 1st issue, just double checked in the database, the addon version should have been truncated, `substring(addon_version, 1, 6)`. e.g. from "1.1.1-dev-1469639420" to "1.1.1-".

**Comment by emtwo** [comment]
Solved:
https://sql.telemetry.mozilla.org/queries/349#585

The versions are now ordered correctly and only showing non-dev version
