### ISSUE TITLE
jpm run/jpm test no longer work in Firefox 48.0 Release channel

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1028]
As of Firefox 48.0, `jpm run` and `jpm test` no longer work in release channel. 

We will need to update our local development and environment and CI to account for this.

**Comment by ncloudioj** [comment]
Same here. Just found out this locally.

**Comment by k88hudson** [comment]
We could use unbranded builds, but the easiest fix here (for now) might be to revert to targeting nightly with `-b nightly`.

**Comment by k88hudson** [comment]
Our CI uses `Firefox 46`, so it should be ok actually

**Comment by k88hudson** [comment]
This is now resolved. See, https://github.com/mozilla-jetpack/jpm/issues/562 for more info.

**Comment by kumar303** [comment]
Using unbranded builds should be pretty easy. They have been made available for the purpose of add-on development. Details on how to download: https://wiki.mozilla.org/Addons/Extension_Signing#Unbranded_Builds

**Comment by Standard8** [comment]
Unfortunately a wiki page isn't useful for finding them for downloading. I've raised an [issue on mozdownload](https://github.com/mozilla/mozdownload/issues/407), although that's blocked by other stuff for now.
