### ISSUE TITLE
Measuring Recommendation Success Criteria

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1048]
One way to measure discovery of recommended content is to look at the number of unique domains or URLs visited per day for a client with and without recommendations. If this increases with recommendations, we know we did a good job introducing new content to them.

This would require us to send an extra metric, unique URL count, perhaps once a day as an event ping, for example.

**Comment by sarracini** [comment]
Closing this since we've disabled recommended content for now
