### ISSUE TITLE
Update to Node v6?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1051]
Currently we're using Node 5, which is like a weird "unstable" channel (our Travis-CI uses [5.11.1](https://github.com/mozilla/activity-stream/blob/26dd2a3a960a09db2b7cfaaed0174dd85526107f/.travis.yml#L4)).

The [Node.js Download page](https://nodejs.org/en/download/current/) currently lists the following channels:

| CHANNEL | NODE | npm |
| :-- | :-- | :-- |
| Current/Stable | v6.3.1 | 3.10.3 |
| LTS ([schedule](https://github.com/nodejs/LTS#lts-schedule)) | v4.4.7 | 2.15.8 |

(See full [Previous Release](https://nodejs.org/en/download/releases/) list.)

Since we don't want to downgrade to Node v4/LTS, do we want to jump from Node 5.x to Node 6.x?

**Comment by pdehaan** [comment]
> _"You may have missed it but at the end of June, the Node.js project said a final farewell to version 5. There will be no more patches, critical or otherwise, for this branch."_

> &mdash; via https://nodejs.org/en/blog/community/v5-to-v7/

Even though we're just using Node 5 locally for development, we still may want to switch to a more stable branch.

**Comment by sarracini** [comment]
Closing this since we're going to leave this on Node 5 right now
