### ISSUE TITLE
Crash: Provider is undefined

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1053]
"TypeError: provider is undefined: _respondToPlacesRequests@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:168:9
_setupListeners/this._contentToAddonHandlers@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:365:7
emit@resource://devtools/shared/event-emitter.js:191:13
_setupPageMod/this._pagemod<.onAttach/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:483:11
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker.js:74:26
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:96:37
"event-emitter.js:195

**Comment by piatra** [comment]
Maybe worth mentioning: I am seeing this bug in DevEdition but not in Nightly. Same stack trace.

**Comment by piatra** [comment]
I had seen this issue on DevEdition & Nightly (today's latest version) but after pulling latest AS master it seems to be resolved.

**Comment by oyiptong** [comment]
This is a race condition.

Basically, we're receiving a places request from content before the memoizer was initialized.

https://github.com/mozilla/activity-stream/blob/460c8b20564499cdab39bc26412a3bf394531586/lib/ActivityStreams.js#L74
