### ISSUE TITLE
Fathom metadata debugging utility

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1054]
This is part of an effort to change our data source from embedly to our own metadata provider.

This work will help us improve the quality of the ruleset implemented with fathom, and for this we would like to have a debugging utility the add-on behind a pref in order to compare and rate the quality of results.

The debugging utility should:

- Be behind a pref
- Allow users to switch between data sources (embedly/fathom)
- Allow users to compare embedly and fathom results at the same time
- Allow users to rate the quality of embedly vs fathom results

Dependencies include:
- A fathom-based metadata service
- A way to store/transmit feedback

**Comment by k88hudson** [comment]
cc @edmoz @jaredkerim @sarracini

**Comment by jaredkerim** [comment]
#1074 is a first pass on this.

**Comment by jaredkerim** [comment]
Closing this for now as handled by #1074
