### ISSUE TITLE
Check faker usage in webpack

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1066]
Currently we [use faker](https://github.com/mozilla/activity-stream/search?utf8=%E2%9C%93&q=faker) for some "stuff".

From my laughably limited knowledge of Webpack profiling (see ["Manualling Tuning Webpack Builds"](https://medium.com/@xjamundx/manually-tuning-webpack-builds-284923f47f44)), we can do something like this to see all our modules when doing a production build:

``` sh
NODE_ENV=production ./node_modules/.bin/webpack --display-modules --sort-modules-by size
```

If I do some sloppy grep work to see how many instances of `./~/faker/` show up, it looks like a lot:

``` sh
[...] webpack --display-modules --sort-modules-by size | egrep 'faker' | wc -l # 962
```

We should probably investigate whether Faker is needed in our production builds at all, or see if we can put it somewhat on a diet, if we don't need all those locales.

**Comment by sarracini** [comment]
Closing this since it's been resolved
