### ISSUE TITLE
Do not show URL as page title

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1067]
https://github.com/mozilla/activity-stream/blob/460c8b20564499cdab39bc26412a3bf394531586/content-src/components/ActivityFeed/ActivityFeed.js#L38

Here we fall back to the sites URL if we are unable to determine a title.  We should not show URLs as titles.  If a page does not have a metadata title, it should not be shown as a highlight.

**Comment by pdehaan** [comment]
But I think the curious thing here is that often sites _DO_ have titles, but our proxies or extractors are not returning them, and then hitting the fallback case.

**Comment by jaredkerim** [comment]
Let's investigate and confirm that this happens even when we have metadata.

**Comment by ianb** [comment]
I see this when I have a page that came from Sync (that I never visited on my desktop machine)

**Comment by jaredkerim** [comment]
Closing as duplicate of #971
