### ISSUE TITLE
Perform profiling and identify performance bottlenecks

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-stream#1068]
We are looking to look at identifying bottlenecks for:

* page load latency (both addon and content side)
* on-demand CPU usage
* background CPU usage

**Comment by oyiptong** [comment]
cc @ncloudioj

**Comment by jaredkerim** [comment]
We should figure out if there's a way to track the time until the awesomebar cursor is made available because this blocks the user from interacting with the browser is pushing users away.

**Comment by sarracini** [comment]
We did this and there's some good work going into performance now
