### ISSUE TITLE
PerfMeter and TabTracker test failures on nightly

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1071]
I'm seeing the follow tests fail on nightly locally:

Personally I think we should rework these tests, they are pretty fragile right now.

The following tests failed:
  ./test/test-ActivityStreams-private-browsing.test activity stream doesn't load in private windows: failure
  ./test/test-PerfMeter.test_PerfMeter_pref: failure
  ./test/test-PerfMeter.test_PerfMeter_sample_stats: exception
  ./test/test-PerfMeter.test_PerfMeter_tab_hygiene: failure
  ./test/test-PerfMeter.test_PerfMeter_tab_restore: failure
  ./test/test-TabTracker.test_TabTracker_History_And_Bookmark_Reporting: failure
  ./test/test-TabTracker.test_TabTracker_action_pings: failure
  ./test/test-TabTracker.test_TabTracker_back_button_load: failure
  ./test/test-TabTracker.test_TabTracker_close_window_with_multitabs: failure
  ./test/test-TabTracker.test_TabTracker_disable_ping: failure
  ./test/test-TabTracker.test_TabTracker_handleRouteChange: failure
  ./test/test-TabTracker.test_TabTracker_handleRouteChange_FirstLoad: failure
  ./test/test-TabTracker.test_TabTracker_init: failure
  ./test/test-TabTracker.test_TabTracker_latency: failure
  ./test/test-TabTracker.test_TabTracker_open_close_tab: failure
  ./test/test-TabTracker.test_TabTracker_pageType: failure
  ./test/test-TabTracker.test_TabTracker_performance_action_pings: failure
  ./test/test-TabTracker.test_TabTracker_prefs: failure
  ./test/test-TabTracker.test_TabTracker_reactivating: failure
  ./test/test-TabTracker.test_TabTracker_refresh: failure
  ./test/test-TabTracker.test_TabTracker_session_reports: failure
  ./test/test-TabTracker.test_TabTracker_unfocus_unloaded_tab: failure
  ./test/test-TabTracker.test_TabTracker_unload_reason_with_user_action: failure
  ./test/test-TelemetrySender.test_TelemetrySender_init: failure
  ./test/test-TelemetrySender.test_TelemetrySender_prefs: exception

**Comment by oyiptong** [comment]
Is this issue reproducible with the latest master?

There was a race condition where PerfMeter and TabTracker was initialized potentially before other things were.

The race condition was fixed in #1065

**Comment by ncloudioj** [comment]
Dup issue of #1044 and #1046

**Comment by ncloudioj** [comment]
Those failures remain with the latest master. Let's track the progress in the original issues.
