### ISSUE TITLE
Add Rating System for Metadata

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#1074]
@k88hudson and I discussed adding a rating system for the metadata based on the source (either embedly or fathom) that it came from. You'll be able to switch between metadata sources and give each highlight a rating based on their image, title, description, etc... 

It'll be hidden behind a pref. Switching the pref on will let you pick your metadata source and then show the UI for the rating. Each rating will be sent as a ping with a payload {url, metadata_source, rating} so we can compare which urls from which source are better than others. 

ref: #1054 

⭐ ⭐ ⭐ ⭐ ⭐ 

cc @edmoz @nchapman

**Comment by ncloudioj** [comment]
cc @ncloudioj

A new ping will be added. That requires the related changes for Onyx, Splice, and Infernyx.

**Comment by sarracini** [comment]
Ping will have the following format:

```js
{
  "action": "activity_stream_metadata_rating",
  "addon_version": "1.0.12",
  "rating": 4,
  "rating_url": "https://www.example.com",
  "metadataSource": ["Embedly" | "Fathom"]
}
```

**Comment by ncloudioj** [comment]
Are we including URLs in the payload?

**Comment by sarracini** [comment]
yep, but no client ID associated with it

**Comment by ncloudioj** [comment]
Got it. That's another reason that we should exclude the client_id in this ping :)
