### ISSUE TITLE
Add test to track add-on size during CI

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1075]
Not sure where to do this, but may make sense to add it to the fabfile or in Travis-CI when merging into master so we can track or XPI installer filesize over time.

Would be pretty interesting to see if it's slowly growing as we add new features or if we're getting smaller and then getting big spikes in filesize as we update tippy-top-sites.

**Comment by jaredkerim** [comment]
Related to #1068

**Comment by k88hudson** [comment]
We might also want to include the breakdown of dependencies in Webpack, i like to use `webpack-bundle-size-analyzer`

**Comment by sarracini** [comment]
We're going to close this, since we won't need this in the system addon. Thanks @pdehaan
