### ISSUE TITLE
Cannot play YouTube Vevo videos

### ISSUE THREAD

**Issue by Coder206** [mozilla/activity-stream#1079]
When trying to, it forces a user to "Watch it on YouTube"

See below: 

![selection_001](https://cloud.githubusercontent.com/assets/7758155/17643607/24062124-613d-11e6-9cf9-c98171ffdd4d.png)

**Comment by jaredkerim** [comment]
We should find some way to detect if this is the case and indicate it to the user.

**Comment by Coder206** [comment]
@jaredkerim Yes! I think it would be better if we could use Polymer's App.route as the demo (https://elements.polymer-project.org/elements/app-route?view=demo:demo/index.html&active=app-route) shows

**Comment by ianb** [comment]
The [YouTube iframe API](https://developers.google.com/youtube/iframe_api_reference#Events) might be what we would need to detect this case (emits `onError` with an error code of 101 or 150 for this case).  Unless the intention is to do a preflight check on embeddability, then you might want to try something like `https://www.googleapis.com/youtube/v3/videos?id=6CQEZ_kas0I&key=[yourkey]&part=snippet,contentDetails,status`

**Comment by Coder206** [comment]
@ianb I would prefer being able to see all videos rather than just those that are allowed.

**Comment by sarracini** [comment]
Closing this since we've removed recent activity and timeline, therefore removing inline videos
