### ISSUE TITLE
Run an experiment with scoring/ranking system vs existing query

### ISSUE THREAD

**Issue by edwinwongsf** [mozilla/activity-stream#1085]
Goal: Understand how using the new scoring/ranking system compares to the current query measured by click through rate and qualitative surveys.

**Comment by jaredkerim** [comment]
This can be tested manually by enabling this pref:

extensions.@activity-streams.weightedHighlights

**Comment by edmoz** [comment]
waiting for initial feedback from PM/QE/UX

**Comment by edmoz** [comment]
QE/UX are 👍 on releasing this as an experiment

**Comment by k88hudson** [comment]
All you need to do for this is replace the pref with the experiment data (instead of filtering on `prefs.weightedHighlights`,  look at `experimentProvider.values.weightedHighlights`)

**Comment by piatra** [comment]
@jaredkerim this needs to run as an experiment in the main release, the goal of this bug is not complete.
