### ISSUE TITLE
Cannot Enable Activity Stream

### ISSUE THREAD

**Issue by NormG1** [mozilla/activity-stream#1095]
Trying to enable Activity Stream. It simply says Enabling . . . forever and never actually enables.

Firefox V48 on Macbook Pro and El Capitan latest.

**Comment by ncloudioj** [comment]
There is a known issue in TestPilot that makes the addon installation freeze.

Please try installing it via this link

https://moz-activity-streams.s3.amazonaws.com/dist/latest.html
