### ISSUE TITLE
Cannot remove services from Share doorhanger 

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1099]
If I go to "Remove Services" and disable a bunch of services, they're still showing in my doorhanger:

<img width="718" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/17716442/90034e42-63bd-11e6-88bf-7092998a592b.png">

So even with the majority of my services disabled, it still shows them in my dropdown:

<img width="246" alt="iphone_6s_-_apple" src="https://cloud.githubusercontent.com/assets/557895/17716403/65513088-63bd-11e6-83cd-37995dfdb90c.png">

**Comment by pdehaan** [comment]
I think this is related, so I won't file a new bug [unless somebody yells at me to], but the "Yahoo Mail" is displaying, even though it is disabled -- but if I end up selecting it above, nothing happens. I don't see anything in my Browser Console window and there is no user feedback of success or failure.

But I think this would be resolved by not displaying disabled services in the dropdown to begin with.

**Comment by rlr** [comment]
gah. I screwed up the whole listener/obsver thing when fixing something else. should be easy fix coming soon.

**Comment by pdehaan** [comment]
@rlr: Will the fix mean that adding Google+ won't add that new airplane icon to my toolbar?
This is toolbar icon overload.

**Comment by rlr** [comment]
fixord.... This doesn't fix the shareplane button getting added after adding a new provider. but we have an issue for that to track it 👍
