### ISSUE TITLE
A few errors in my local Browser Console when tweeting a page using Share panel

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1100]
<img width="579" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/17716727/c6d383fa-63be-11e6-9e90-297b2175c8fd.png">
### Steps to reproduce:
1. Go to http://www.apple.com/iphone-6s/
2. Open and clear your Browser Console (Tools > Web Developer > Browser Console).
3. Share the page to Twitter by clicking the Share icon and selecting "Twitter" from the doorhanger.
4. Witness Browser Console.
### Actual results:

I'm not sure what's happening. Not sure if it's Apple's page settings throwing exceptions or where exactly MozSocialAPI.jsm is coming into this, and why it's throwing the error (CSP?) or if it should be handling null-checks better since it's vomiting with the following error:

> "TypeError: containingBrowser is null"

<img width="719" alt="browser_console" src="https://cloud.githubusercontent.com/assets/557895/17716784/11b51b5e-63bf-11e6-9b7e-75cb1f359a14.png">

**Comment by pdehaan** [comment]
Getting similar errors w/ http://www.cnn.com/, so it isn't Apple.com specific (these are just 2 random URLs, nothing fancy).

<img width="719" alt="browser_console" src="https://cloud.githubusercontent.com/assets/557895/17717002/3dfa8996-63c0-11e6-9128-886132ce1a88.png">

**Comment by rlr** [comment]
This is from MozSocialAPI code in Firefox that is deprecated and being removed. I am pretty sure there isn't much we can do about it from our end and that it is harmless. CC @mixedpuppy

**Comment by mixedpuppy** [comment]
Is sharing not working, or is this just console output?  If the later, ignore it.

**Comment by sarracini** [comment]
Closing this since Share is gone
