### ISSUE TITLE
Debug the weights in the recommender system

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#1101]
Need: As a developer of activity stream I want to change the weights associated with the features used in scoring a URL for highlights. I want the update to be as easy as possible (no browser restarts).

Deliverable: A pref in `about:config` called `weightedHighlightsCoefficients` which allows you to change the weights in the system without having to do a browser restart to see the changes. *You still need to refresh the page* 😅 
Figuring out what the numbers mean requires [reading the comments](https://github.com/mozilla/activity-stream/blob/2a72af00acd6b13627d1f9b3c0c3f38bf3fb5cf9/common/recommender/Baseline.js#L27)

**Comment by pdehaan** [comment]
@piatra Was this resolved by #1106?

**Comment by sarracini** [comment]
^ Yes it was
