### ISSUE TITLE
Favicons are inconsistently displayed between Top Sites and Recent Activity

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1103]
Noticed that I don't get a favicon in Top Sites, but it does appear in Recent Activity. Not sure if it's because it's a super crappy 16x16 pixel mess and Top Sites is doing filtering on lower resolution images. :shrug:

<img width="753" alt="new_tab" src="https://cloud.githubusercontent.com/assets/557895/17717244/b4eb4882-63c1-11e6-84a1-cd524dc4c6c3.png">

**Comment by sarracini** [comment]
Closing this since we've removed recent activity
