### ISSUE TITLE
Launching Twitter window from Share doorhanger doesn't show entire window contents

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1108]
Possibly a losing battle trying to size popups based on 3rd party sites, but this was a bit curious:

Trying to share a page via Twitter share provider, I noticed that the page seemingly scrolls.

<img width="550" alt="share_a_link_on_twitter" src="https://cloud.githubusercontent.com/assets/557895/17717955/059fbb60-63c6-11e6-9d2a-394661e8bd4b.png">
**Before scroll**

---

<img width="550" alt="share_a_link_on_twitter" src="https://cloud.githubusercontent.com/assets/557895/17717967/1b8f3446-63c6-11e6-8610-aa1f77f1865d.png">
**After scroll**

---

Actually, mulling over this for another 0.34 seconds, this _may_ be because I'm not actually logged in to Twitter on this Firefox profile, so we're launching the window size based on us expecting the user to be already logged in.

**Comment by rlr** [comment]
yeah, all the sizes in the manifest are based on the dimensions on the page when signed in. Or that has matched my observations so far. oy

**Comment by jaredkerim** [comment]
Closing this as a wontfix.
