### ISSUE TITLE
Share window doesn't resize itself after switching between different providers

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1109]
<img width="579" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/17718013/639f9758-63c6-11e6-8dba-1c4271f7b3af.png">

### Steps to reproduce:
1. Go to a page and try sharing it to Twitter (but don't submit).
2. Try sharing the page to Gmail (but don't submit).
3. Close the sharing window.
4. Share the page to Gmail (but don't submit).

### Actual results:
<img width="550" alt="share_a_link_on_twitter" src="https://cloud.githubusercontent.com/assets/557895/17718138/22fa70be-63c7-11e6-86dd-46e02093f591.png">
**Figure 1:** Initial Twitter share page.

---

<img width="550" alt="gmail_-_free_storage_and_email_from_google" src="https://cloud.githubusercontent.com/assets/557895/17718163/3f37f68e-63c7-11e6-9855-4401aff95ee7.png">
**Figure 2:** Initial Gmail share page (after launching [unclosed] Twitter share page).

---

<img width="500" alt="gmail_-_free_storage_and_email_from_google" src="https://cloud.githubusercontent.com/assets/557895/17718188/63729608-63c7-11e6-8b56-70324ceabd1f.png">
**Figure 3:** Initial Gmail share page (if launched first).

**Comment by rlr** [comment]
I am thinking it might be better to use a different window name for each provider. That way you can share to twitter and facebook in parallel and this wouldn't be an issue. thoughts?

**Comment by pdehaan** [comment]
@rlr Sounds reasonable to me.
