### ISSUE TITLE
Add Services from Share door hanger tells me to activate already activated services

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1110]
### Steps to reproduce:
1. Make sure you have all your Share services enabled.
2. Go go "Add Services" from the door hanger (should redirect you to https://activations.cdn.mozilla.net/en-US/).

### Actual results:
Even though Facebook and Gmail are enabled in my Sharing service, they prompt me to Activate them on the activations.cdn.mozilla.net site.

<img width="1293" alt="screenshot_8_16_16__3_45_pm" src="https://cloud.githubusercontent.com/assets/557895/17718393/881d33d6-63c8-11e6-9f4a-695b76f6db61.png">

<img width="1280" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/17718411/9a8c27ac-63c8-11e6-804b-f8d43f76e8a1.png">

**Comment by rlr** [comment]
@mixedpuppy is there any way to make the activations page aware of what the user has already installed?

**Comment by mixedpuppy** [comment]
Not without exposing user information to the website.  Regular addons behave that way as well.

**Comment by jaredkerim** [comment]
Closing this as a wontfix.
