### ISSUE TITLE
Adding new Services adds new toolbar icon and doesn't seem to add new service to doorhanger

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1111]
### Steps to reproduce:
1. In the Share toolbar doorhanger, select "Add Services". It should take you to https://activations.cdn.mozilla.net/en-US/
2. Scroll down to Google+ and click Activate button.
3. Click "Enable Services" in doorhanger.
    <img width="522" alt="menubar_and_google__for_firefox" src="https://cloud.githubusercontent.com/assets/557895/17718618/b0439ab6-63c9-11e6-8c84-95b8f4a48e75.png">

### Actual results:
I see a page saying:

> Congratulations, Google+ is now activated in Firefox!

Despite that, I don't see "Google+" added to my share panel:

<img width="207" alt="screenshot_8_16_16__3_55_pm" src="https://cloud.githubusercontent.com/assets/557895/17718652/db0a14d2-63c9-11e6-80b9-286e99c5a498.png">

... But I do see yet another toolbar icon added with the same share services:

<img width="395" alt="google__for_firefox" src="https://cloud.githubusercontent.com/assets/557895/17718682/0e72295e-63ca-11e6-8452-cb101066aa3c.png">

---

I can also see Google+ added to my Services settings page:

<img width="1280" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/17718713/3a865c68-63ca-11e6-9625-bf2a3f6f41f3.png">

**Comment by rlr** [comment]
yeah, same underlying issue as #1099. PR coming in 3...2.....

**Comment by rlr** [comment]
Half of this is fixed now. Now need to figure out how to hide that reappearing shareplane.

**Comment by rlr** [comment]
Actually, scratch that... Adding/enabling still seems to be busted. As in they don't appear in the doorhanger until a disable/remove happens. weird.

**Comment by ncloudioj** [comment]
I've tried to add a new service in my AS. Looks like the new service got merged into the share toolbar after a few moments. And the shareplane was gone eventually.

**Comment by ncloudioj** [comment]
@rlr FYI, it works, amigo. I just successfully shared some links to my Chinese social networks 🎱

**Comment by rlr** [comment]
fixed via #1122
