### ISSUE TITLE
Bug 1295960 - Twitter login breaks after entering incorrect credentials while trying to share a page 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#1115]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1295960
<br>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.1-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.1-dev) was previously installed on a clean profile.
- Not logged in Twitter.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Visit any page.
3. Click the "Share" button and select Twitter.
4. Log in with an incorrect username and/or password.
5. Try to enter the correct credentials.

[Expected result]:
- You are able to log in with the correct login info.

[Actual result]:
- You cannot write in the password field and the "Login" button is active but it doesn't do anything if clicked.

[Notes]:
- Also in this screen the "Remember me" checkbox cannot be unchecked.
- The same steps work if you use the "Share this page" feature, so I don't think this is a service issue.
- Attached a screen recording of the issue https://goo.gl/MqVeDj.

**Comment by sarracini** [comment]
Closing this since Share is gone
