### ISSUE TITLE
Bug 1296247 - The latest Activity Stream version breaks the "Share this page" context menu options

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#1127]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1296247
<br>
[Notes]:
- If you install the add-on first and then add the "Share this page" feature to the browser toolbar, they both work as expected until a restart. 
- If you add the "Share this page" feature to the customization menu and then install the add-on, the Activity Stream "Share" button will overwrite the "Share this page" one, but the context menu functionality will still work (the doorhanger will appear out of the Menu)

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.1-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- "Share this page" feature is added to the toolbar through the customization menu.

[Steps to reproduce]:
1. Observe the "Share this page" button in the browser toolbar.
2. Install the latest version of the Activity Stream add-on.
3. Observe again the "Share this page" button.

[Expected result]:
- The "Share this page" button is in the same place it was and the Activity Stream "Share" button is a separate button.

[Actual result]:
- The Activity Stream "Share" button overwrites the "Share this page" button.
- The "Share this page" context menu options are unusable even if displayed.

[Additional notes]:
- If this is the intended behavior to replace the current share functionality in the future, in my opinion AS share functionality should not overwrite the default functionality until it's polished.
- Attached a screen recording of the issue https://goo.gl/K2XywB.

**Comment by sarracini** [comment]
Closing this since Share is gone
