### ISSUE TITLE
Bug 1296595 - The Activity Stream "Share" button is not available to add/remove services unless the page is share-able

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#1130]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1296595

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.2-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.2-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a new tab.
3. Observe the "Share" button. 

[Expected result]:
- The "Share" button is enabled and you should at least have the option to add/remove services.

[Actual result]:
- The "Share" button is disabled.

[Notes]:
- If you want to add/remove services you have to navigate to a share-able page where the button is enabled.
- Attached a screen recording of the issue https://goo.gl/FRwVmx.

**Comment by sarracini** [comment]
Closing this since Share is gone
