### ISSUE TITLE
Bug 1296612 - Activity Stream doesn't add it's default Share Services at installation if other Services were already installed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1131]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1296612

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.2-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- "Share this page" feature is added to the toolbar through the customization menu.
- Google plus service is added through "Share this page" feature.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Install the Activity Stream add-on.
3. Click the Activity Stream "Share" button.
4. Observe the listed services. 

[Expected result]:
- The Activity Stream default "Share" services (Facebook, Gmail, LinkedIn, Tumblr, Twitter, Yahoo Mail) are installed along the existing ones.

[Actual result]:
- Only Google+ service is displayed in the list.

[Notes]:
- Attached a screen recording of the issue https://goo.gl/oAzdeT.

**Comment by SoftVision-CiprianMuresan** [comment]
On the other hand, this could not be such a good idea if we don't want to force the installation of additional services on the user profile if he already chosen which ones he likes.

**Comment by rlr** [comment]
Yeah, this was intentional. We didn't want to mess with the settings of a user that has already used social share before. I *think* it's the best approach, but I could be convinced otherwise.

**Comment by Emboli** [comment]
There should be an option to **disable or enable** the installation of services, **I don't use them at all**, they only use memory that makes Firefox heavier. Tried to disable them or remove them without any luck. they always get installed over and over again. I really don't need them, please make them optional.
This is an add-on for **enhancing the new tab** not for sharing.

**Comment by Emboli** [comment]
well, now I met the **Share** option, I solved the above by leaving only one service enabled, the others disabled. Any way, I am not using it.

**Comment by sarracini** [comment]
Closing this since Share is gone
