### ISSUE TITLE
Share doorhanger doesn't play nicely with macOS full-screen mode

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/activity-stream#1134]
When choosing a sharing option from the doorhanger when Firefox is full-screened, a new window is opened, with all the awkward animation and accoutrements that accompanies that.

Expected: it either opens in a new tab (not terrible), in a XUL panel overlaying the window (better), or in the doorhanger itself (best).

Video here: https://vid.me/6JbS

**Comment by sarracini** [comment]
Closing this since Share is gone
