### ISSUE TITLE
Integrate FF theme background into activity stream homepage

### ISSUE THREAD

**Issue by 6a68** [mozilla/activity-stream#1137]
Relaying a user suggestion from the [Discourse forums](https://discourse.mozilla-community.org/t/nice-but-not-compelling/9218/2):

> it would be amazing if the background follow the same pattern of Firefox themes

**Comment by sarracini** [comment]
Feature requests are tracked on the trello: https://trello.com/b/KX3hV8XS/activity-stream-desktop
