### ISSUE TITLE
Activity Stream not starting on new tab

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1139]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/17825871/5486c104-6620-11e6-89d1-d859095095d8.png)

Not sure why, but my New Tab experience never seems to fully load Activity Stream:

![new_tab](https://cloud.githubusercontent.com/assets/557895/17825876/5f9130fc-6620-11e6-8c02-cdd0f6cd09d0.png)
**Figure 1:** Hang on tight!

But clicking the Activity Stream icon in the toolbar does work, and I can see "All" and "Bookmarks":

![activity_stream](https://cloud.githubusercontent.com/assets/557895/17825891/93913a28-6620-11e6-9e65-ced60d3c53cf.png)

Probably relevant, but my `extensions.@activity-streams.embedly.endpoint` points to the https://metadata.dev.mozaws.net/v1/metadata Fathom endpoint.

---

Interestingly, the Browser Console seems to point to an issue w/ ColorAnalyzer.js:53:

![browser_console](https://cloud.githubusercontent.com/assets/557895/17825940/f4b0a564-6620-11e6-87fa-00d3cbd8f77c.png)

![jar_file____applications_firefoxnightly_203_app_contents_resources_omni_ja__components_coloranalyzer_js](https://cloud.githubusercontent.com/assets/557895/17825959/0ef8b4c0-6621-11e6-9fff-0611b1f94bb8.png)

Not 100% sure what all this means yet. My guess is that I've hit a minor edge case with [maybe] Top Sites and ColorAnalyzer trying to calculate the primary colors on a non-existent favicon (perhaps with a canvas width/height of 0, which is where ColorAnalyzer.js `#onImageLoad()` seems to be puking.

**Comment by pdehaan** [comment]
This is looking _very_ suspicious in the Debug page, but not sure if it is a cause or symptom:

```js
{
  "raw": {
    "TopSites": {
      "rows": [],
      "error": {
        "name": "E_TIMEOUT"
      },
      "init": false,
      "isLoading": false,
      "canLoadMore": true
    },
    ...
}
```

![new_tab](https://cloud.githubusercontent.com/assets/557895/17826020/93121e68-6621-11e6-91da-861e69b49a20.png)

**Comment by pdehaan** [comment]
Another data point, but I can seemingly cURL the metadata server, so I don't think it's down or reaped:

```sh
$ http https://metadata.dev.mozaws.net/v1/metadata urls:='["http://motherboard.vice.com/read/smart-electrial-sockets-could-be-the-next-botnet"]' -j -v

POST /v1/metadata HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 95
Content-Type: application/json; charset=utf-8
Host: metadata.dev.mozaws.net
User-Agent: HTTPie/0.9.1

{
    "urls": [
        "http://motherboard.vice.com/read/smart-electrial-sockets-could-be-the-next-botnet"
    ]
}

HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 731
Content-Type: application/json; charset=utf-8
Date: Fri, 19 Aug 2016 22:35:14 GMT
ETag: W/"2db-zy0TGgknT9n+J7g0rsXjmA"
Server: nginx/1.9.9
Strict-Transport-Security: max-age=31536000
X-Powered-By: Express

{
    "error": "",
    "urls": {
        "http://motherboard.vice.com/read/smart-electrial-sockets-could-be-the-next-botnet": {
            "description": "Researchers found a vulnerability that poses both physical and online security risks for the user.",
            "favicon_url": "http://motherboard.vice.com/assets/favicons/motherboard/apple-touch-icon-57x57.png?v20160720101513",
            "images": [
                {
                    "entropy": 1,
                    "height": 500,
                    "url": "http://motherboard-images.vice.com/content-images/article/no-id/1471555589921449.jpg",
                    "width": 500
                }
            ],
            "original_url": "http://motherboard.vice.com/read/smart-electrial-sockets-could-be-the-next-botnet",
            "title": "Smart Electrial Sockets Could Be the Next Botnet",
            "url": "http://motherboard.vice.com/read/smart-electrial-sockets-could-be-the-next-botnet"
        }
    }
}
```

**Comment by rlr** [comment]
Is this still happening? It seems to be working on my end today.

**Comment by k88hudson** [comment]
Looks like `ColorAnalyzer` is throwing a fatal error inside a callback.... :'(
