### ISSUE TITLE
Bug 1297059 - The Activity Stream "Share" button is disabled after being placed back in the toolbar from the customization menu

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1142]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1297059

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.2-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.2-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open the browser "Menu" button.
3. Enter the customization mode and place the Activity Stream "Share" button in "Additional Tools and Features".
4. Exit customization and enter it again.
5. Place the "Share" button back in the browser toolbar. 

[Expected result]:
- The "Share" button is clickable and if clicked the dropdown menu appears.

[Actual result]:
- The "Share" button is greyed out and is not clickable.

[Notes]:
- The "Share" button will be disabled for all opened tabs, but if you navigate to the "New Tab" page and back, it will become active.
- Attached a screen recording of the issue https://goo.gl/PQ3uxC.

**Comment by sarracini** [comment]
Closing this since Share is gone
