### ISSUE TITLE
"Share" button's popup window can't be closed by CMD+W keyboard shortcut on Mac

### ISSUE THREAD

**Issue by cpeterso** [mozilla/activity-stream#1144]
STR:
1. Click the Share toolbar button.
2. Select some sharing service like Facebook.
3. See the Facebook popup window open.
4. Try to close the window using the CMD+W keyboard shortcut on Mac.

RESULT:
Nothing happens. The popup window can't be closed by the normal keyboard shortcut, though you can still close the window by clicking the red X close button.

**Comment by sarracini** [comment]
Closing this since Share is gone
