### ISSUE TITLE
disable then enable activity stream results in Tiles displaying in new tab

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#1145]
1. install dev channel:
https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html
2. browse around, disable, then enable
3. open new tab

actual: activity stream doesn't display in new tab, you see tiles.
if you go to about:addons you'll still see it as installed and enabled.

i've tried restarting browser on nightly and beta but it's not working

**Comment by jaredkerim** [comment]
#747 is related.

**Comment by pdehaan** [comment]
Ref: #1016

**Comment by edmoz** [comment]
after updating Nightly to today, I'm not able to install and see activity stream in new tab.

**Comment by edmoz** [comment]
the easiest way to repro is in step 2, goto about:addons disable, then enable - and now i'm stuck in tiles.   Here's the only obvious exception

    10:42:16.408 NS_ERROR_DOM_BAD_URI: Component returned failure code: 0x805303f4 [nsIScriptSecurityManager.checkLoadURIStrWithPrincipal]1(unknown)LinkChecker_doCheckLoadURIresource://gre/modules/commonjs/toolkit/loader.js%20-%3E%20resource://activity-streams/lib/PlacesProvider.js:154:7LinkChecker_checkLoadURIresource://gre/modules/commonjs/toolkit/loader.js%20-%3E%20resource://activity-streams/lib/PlacesProvider.js:141:29Links.prototype._getHistoryLinks</<resource://gre/modules/commonjs/toolkit/loader.js%20-%3E%20resource://activity-streams/lib/PlacesProvider.js:396:33filterself-hostedLinks.prototype._getHistoryLinks<resource://gre/modules/commonjs/toolkit/loader.js%20-%3E%20resource://activity-streams/lib/PlacesProvider.js:396:12InterpretGeneratorResumeself-hostednextself-hostedTaskImpl_runresource://gre/modules/Task.jsm:319:40bound TaskImpl_runself-hostedHandler.prototype.processresource://gre/modules/Promise.jsm%20-%3E%20resource://gre/modules/Promise-backend.js:937:23this.PromiseWalker.walkerLoopresource://gre/modules/Promise.jsm%20-%3E%20resource://gre/modules/Promise-backend.js:816:7bound self-hostedbound bound self-hosted

**Comment by edmoz** [comment]
this could be a related bug - but i'll put it here.
1. at some point my dev chan instance self updates
2. I see a "hang on spinner" forever
3. at some point, launching a new tab results in Tiles (but i see AS is still on and share button exists)

**Comment by edmoz** [comment]
From the prod mtg - lot of people running into this, we should push a hot fix ASAP.

**Comment by edmoz** [comment]
any updates on understand why we're seeing this?

**Comment by edmoz** [comment]
more data - I can't repro in a new profile. Only my main 4yrs old one.  It could be a collision of another addon or something, previous installs of share addon.

**Comment by pdehaan** [comment]
I can't repro either with: macOS 10.11.6, Firefox Nightly 51.0a1 (2016-09-02) with a fresh profile.
Was also unable to repro in an older profile w/ a few months of browsing history.

Closing for now, and we'll see if we get any new user reports or if it was fixed in a previous commit.

**Comment by pdehaan** [comment]
Reopening... @ncloudioj said he "can repro it with a fresh profile" in IRC:

>9:52 AM `<edwong>` you u using a new profile
> 9:52 AM `<edwong>` or one with other addons etc...
> 9:56 AM `<nanj>` edwong: i don't think that issue was due to the addon collision 
> 9:56 AM `<edwong>` any ideas why?
> 9:56 AM `<nanj>` i can repo it with a fresh profile
> 9:56 AM `<edwong>` the error seems to be in customizableUI with a promise resolution issue
> 9:56 AM `<edwong>` oh great
> 9:57 AM `<edwong>` but i don't think it's share button as i can repro with old builds
> 9:57 AM `<nanj>` we have seen the similar issue if the user keeps clicking on the disable/enable button

**Current status:**
![](https://cdn-images-1.medium.com/max/600/1*snTXFElFuQLSFDnvZKJ6IA.png)

**Comment by edmoz** [comment]
Nan and I spoke: 
* disable then quickly enable can cause addon to crash. Time seems to be related to size of profile.
* It's possibly on large profiles, updating addon could cause this but we don't really know.  We should watch Sentry to see how many users are hitting this.

There was an issue with social API with Nightly that was causing crashes which has been fixed.  This could cause similar symptoms which confuses the user.

Downgrading priority of bug

**Comment by ncloudioj** [comment]
@edmoz can we close this one? I personally prefer to do so as it's a known issue, and I don't think there is too much we can do for now.

**Comment by jaredkerim** [comment]
We're closing this for now unless it begins to become more of an issue again.

**Comment by edmoz** [comment]
we're not seeing this very often and it will recovery if you do see tiles.  Let's close this till we get data that tells us it's a bigger issue.
