### ISSUE TITLE
Need better UI when user has no bookmarks

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1150]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/17871054/c2f461f0-686e-11e6-8a6d-7b5b3fb4980d.png)

I built the add-on locally using `$ npm run once` which creates an empty profile.

For giggles, I deleted all the 5 default bookmarks, but now the page feels very barren. Not sure if we want to have some "empty state" which prompts the person to start browsing or bookmarking some content.

![activity_stream](https://cloud.githubusercontent.com/assets/557895/17871089/ea96c8a6-686e-11e6-8256-99204cd1fce9.png)
**Figure 1:** Empty bookmarks page (note I manually deleted all my bookmarks to get into this state).

**Comment by pdehaan** [comment]
![activity_stream](https://cloud.githubusercontent.com/assets/557895/17871202/6eaa504a-686f-11e6-932c-708cd2d4b101.png)
**Figure 2:** "All" page with no browsing history.

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/17871235/88d534b2-686f-11e6-8303-1a1841fba17c.png)
**Figure 3:** "New Tab" page with no browsing history, using default "Top Sites" and "Highlights".

**Comment by sarracini** [comment]
closing this since we've removed timeline
