### ISSUE TITLE
Only getting two highlights

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1152]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/17875653/9065ae8c-6888-11e6-9323-ecf56a53ecca.png)

Set up locally using `npm run once` using 5930a7de89ea415ceb7fca02ca053a942adada87

![menubar_and_about_config_and_new_issue_ _mozilla_activity-stream](https://cloud.githubusercontent.com/assets/557895/17875667/bb58b9f4-6888-11e6-8e79-db1edf55d5ca.png)

![new_tab](https://cloud.githubusercontent.com/assets/557895/17875675/c82de4c4-6888-11e6-85b8-f0aeae689044.png)

I can't see anything of interest anywhere, so I'm not sure why I'm only being served up 2 recommendations (although I don't seem to be getting Pocket recommendations, so maybe I'm not in that A/B experiment.

I did see this error in my Browser Console, but I'm not sure if it's related:

![browser_console](https://cloud.githubusercontent.com/assets/557895/17875699/2565e4ca-6889-11e6-83ab-eb9eb5d9d645.png)

**TypeError: `this.controller` is undefined`**

via chrome://browser/content/places/browserPlacesViews.js:263:1

**Comment by k88hudson** [comment]
@pdehaan any chance you got a look at the console for the page?

**Comment by k88hudson** [comment]
I was unable to reproduce this. If we see it again, let's re-open. Having sentry data here would be really helpful
