### ISSUE TITLE
Bug 1297388 - The Top Sites tile loses its highlight if you mouseover the context menu button

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1154]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1297388

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.2-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.2-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Hover one of the tiles from Top Sites.
3. Hover the tile's context menu button.

[Expected result]:
- The Top Sites tile is still highlighted.

[Actual result]:
- The Top Sites tile loses its highlight.

[Notes]:
- The issue is not reproducible for Highlights tiles and Recent Activity items.
- Attached a screenshot of the issue.

![top sites tile not visually focused](https://cloud.githubusercontent.com/assets/18304511/17895717/aa2ae02a-6956-11e6-82e4-32c3bdb07a1b.png)

**Comment by sarracini** [comment]
Video (provided by @aaronrbenson: https://cl.ly/2l2B171T0i45)

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Activity Stream 1.3.0-pre-release-1485545108-d43cc0c.
