### ISSUE TITLE
Bug 1297389 - [Enhancement] A confirmation message should be displayed after clicking "Copy Address" from the "Share" dropdown

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1155]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1297389

<hr>

[Notes]:
- This should be treated as an enhancement.
- Attached a screen recording of the issue http://goo.gl/eUefXB.

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.2-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.2-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Visit any share-able page.
3. Click the "Share" button.
4. Click the "Copy Address" option. 

[Expected result]:
- A confirmation message should be displayed informing the user that the link was copied to the clipboard.

[Actual result]:
- The link is copied, but no confirmation message is displayed.

**Comment by sarracini** [comment]
Closing this since Share is gone
