### ISSUE TITLE
Odd error when installing Test Pilot experiment

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1161]
Possibly not the right repo for this bug, but oddly the stack points to resource://activity-streams/\* so buckle up!

I enabled http://testpilot.dev.mozaws.net/experiments/no-more-404s in FF Nightly, and happened to have my Browser Console open, and it displayed this error. Thinking it was unrelated, I cleared my console then disabled and reenabled the experiment and the error returned.

If you have a better place for me to file this bug, let me know and I can move it.

![browser_console](https://cloud.githubusercontent.com/assets/557895/17907454/e86e20e8-6930-11e6-88bb-afab9cd16b3f.png)

![firefox_test_pilot_-_no_more_404s](https://cloud.githubusercontent.com/assets/557895/17907422/d592a980-6930-11e6-846f-8c7c86ee0a9f.png)

**Comment by jaredkerim** [comment]
Requires verification from @pdehaan

**Comment by edmoz** [comment]
also does this happen on Prod Test Pilot?

**Comment by sarracini** [comment]
This was fixed with #1943
