### ISSUE TITLE
Initial evaluation of local MetadataParser performance and stability

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#1162]
Need to qualitative and perf profile compare of  #1157 (was #904)

I think you just set this pref: MetadataParser = true?  not sure how to do this.

**Comment by pdehaan** [comment]
Well, I don't think the performance of the metadata proxy will be "great" until we can do https://github.com/mozilla/page-metadata-service/issues/48; _"Add redis caching"_ (and possibly https://github.com/mozilla/page-metadata-service/issues/41; _"Use a queue/worker/cache system"_).

IIRC, currently we fetch the remote resource each time you request a URL with no caching whatsoever, which will complicate load testing or anything at scale.

/cc @jaredkerim

**Comment by edmoz** [comment]
@pdehaan this is just for local page metadata parsing... this does NOT use the metadata proxy server at all.  

The plan is to test fathom ruleset on the server for rapid iteration and test performance and stability of local parsing pref'd off so we can evaluate how good or bad it feels local only.  When you fire up with local page scraping on, there was assumptions your browser will lock up as it parses 10 pages at startup.

**Comment by edmoz** [comment]
pdehaan pointed out that this hasn't merged and #904 was abandoned and replaced with #1157   no action for now.

**Comment by sarracini** [comment]
If some preliminary work wanted to be done for this, you would have to not only turn the pref 'pageScraper' on but also enable the experiment too (change the control variable of localMetadata in experiments.json to ```true```)

**Comment by jaredkerim** [comment]
Please move all discussion related to local metadata processing experiment into #1157.
