### ISSUE TITLE
highlight cards don't display lead image if proxy server return empty value

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#1169]
If the server for whatever reasons (low bandwidth, not cached, server slow) returns empty string for metadata, often the lead image fails to load. I'm seeing this happen at a 50% rate. We should shoot for zero.  Maybe we should try again if we know an image is not displayed?

<img width="987" alt="screen shot 2016-08-25 at 8 57 46 am" src="https://cloud.githubusercontent.com/assets/3698618/17976441/5ecbf61c-6aa2-11e6-9e55-98e3bb700c15.png">

**Comment by edmoz** [comment]
example of what happens on the server api: https://edwong.pastebin.mozilla.org/8904564

**Comment by aaronrbenson** [comment]
Not sure if related, lately almost none of my trending highlights are showing image/title/description
![trending_no_images](https://cloud.githubusercontent.com/assets/139451/18028936/9082c362-6c4f-11e6-9590-5ffbaae0cddc.png)

**Comment by pdehaan** [comment]
Fwiw, I think the metadata server got reaped on Friday. Not sure if we got
it back up or not. I'm not seeing the version endpoint responding, but hard
to debug from iPhone https://metadata.dev.mozaws.net/__version__

**Comment by jaredkerim** [comment]
New highlight behaviour should not show highlights without images.  File a new ticket if that behaviour is observed.

**Comment by pdehaan** [comment]
@jaredkerim Doesn't that mean we'd have zero highlights if the proxy server went down again?
