### ISSUE TITLE
Add a pref for users that are testing

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1170]
Right now the only way we can know whether one of us is testing or we have actual user interaction in the pings is by looking for a `dev` addon version. There are a couple of problems with this:
1. Querying a boolean column is likely faster than a substring search to find `dev` in the addon version
2. Sometimes we are testing using a release version but there's no way for us to know that.

What do we think of having a pref that we can set to say we're testing? We can set it to `True` by default in the dev versions.

**Comment by emtwo** [comment]
Note: this also includes adding a field in the pings for the value of the pref.

**Comment by emtwo** [comment]
Un-assigning myself as this is low priority for now.

**Comment by sarracini** [comment]
Closing this since we did this
