### ISSUE TITLE
Installation broken on Nightly

### ISSUE THREAD

**Issue by 6a68** [mozilla/activity-stream#1173]
MacOS 10.11.6
Nightly 51.0a1 (2016-08-25)
Bug does _not_ occur on Dev Edition

Steps to reproduce:
- with a fresh profile, go to testpilot.firefox.com
- install test pilot
- try to install activity stream from the test pilot site
- you'll see two error traces in the browser console/toolbox, both point to the same error.

The first error trace, [gisted here](https://gist.github.com/6a68/538ba3f23fb62f79ed84520a31c2971c), points to an incorrect `Cu.import` call at [line 8 in ShareProvider.js](https://github.com/mozilla/activity-stream/blob/master/addon/ShareProvider.js#L8):

```js
// ShareProvider.js, line 8
const SocialService = Cu.import("resource://gre/modules/SocialService.jsm", {}).SocialService;
```

This line should actually be

```js
const SocialService = Cu.import("resource:///modules/SocialService.jsm", {}).SocialService;
```

TBH I'm not sure what the difference is, but looking at how SocialService.jsm is imported [elsewhere in dxr](https://dxr.mozilla.org/mozilla-central/search?q=SocialService.jsm&redirect=false), it seems the latter is always used. Should be a quick fix.

**Comment by rlr** [comment]
I updated my nightly and started getting this error when running `npm run test:jpm`. I'll try your suggestred fix. Thanks!

**Comment by rlr** [comment]
Actually, the change that broke this just landed: http://searchfox.org/mozilla-central/diff/1bb3fcb541982a7176dbeb407a239bae87c038af/browser/modules/test/unit/social/head.js#119

I'm trying to figure out how to write the code to handle both version. Any ideas?

**Comment by dmose** [comment]
Execute the new path first, wrapped in a try statement, and if it explodes, try again with a catch clauses that uses the old path?

**Comment by dmose** [comment]
Actually, if you held off on dereferencing the imported thing, you could just test the return from import for null and not even bother with a try catch.

**Comment by dmose** [comment]
Er, undefined, I meant.

**Comment by rlr** [comment]
@dmose Thank you!

**Comment by rlr** [comment]
@dmose Thank you!

**Comment by rlr** [comment]
Fix landed. Should be in our dev channel shortly.
