### ISSUE TITLE
wikipedia doesn't have a lead image with current fathom ruleset

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#1178]
use httpie to do this:

    http POST https://metadata.dev.mozaws.net/v1/metadata urls:='["https://en.wikipedia.org/wiki/Katie_Ledecky"]' content-type:application/json -v
    POST /v1/metadata HTTP/1.1
    Accept: application/json
    Accept-Encoding: gzip, deflate
    Connection: keep-alive
    Content-Length: 57
    Host: metadata.dev.mozaws.net
    User-Agent: HTTPie/0.9.3
    content-type: application/json

    {
        "urls": [
            "https://en.wikipedia.org/wiki/Katie_Ledecky"
        ]
    }

    HTTP/1.1 200 OK
    Connection: keep-alive
    Content-Length: 351
    Content-Type: application/json; charset=utf-8
    Date: Fri, 26 Aug 2016 00:02:46 GMT
    ETag: W/"15f-yq7jMGNJTHESb0Xw52QPlg"
    Server: nginx/1.9.9
    Strict-Transport-Security: max-age=31536000

    {
        "request_error": "",
        "url_errors": {},
        "urls": {
            "https://en.wikipedia.org/wiki/Katie_Ledecky": {
                "favicon_url": "https://en.wikipedia.org/static/apple-touch/wikipedia.png",
                "images": [],
                "original_url": "https://en.wikipedia.org/wiki/Katie_Ledecky",
                "title": "Katie Ledecky - Wikipedia, the free encyclopedia",
                "url": "https://en.wikipedia.org/wiki/Katie_Ledecky"
            }
        }
    }

notice images:[]

results in this:
<img width="245" alt="screen shot 2016-08-25 at 5 00 48 pm" src="https://cloud.githubusercontent.com/assets/3698618/17989922/df430cf2-6ae5-11e6-9df1-87882c511c59.png">

expected: embedly does have an img

**Comment by pdehaan** [comment]
Not _too_ surprising, they have very sparse `<meta>` tags (none of them seemingly Twitter or Open Graph):

```html
<meta charset="UTF-8" />
<meta name="ResourceLoaderDynamicStyles" content="" />
<meta name="generator" content="MediaWiki 1.28.0-wmf.15" />
<meta name="referrer" content="origin-when-cross-origin" />
```

**Comment by pdehaan** [comment]
I [poorly] wrote https://github.com/pdehaan/meta-scraper which grabs all `<link/>`, `<meta/>`, and `<title/>` tags, for easier debugging:

```js
const { areWeMetaYet } = require('meta-scraper');

areWeMetaYet('http://reddit.com/r/gaming')
  .then(({link, meta, title}) => [].concat(link, meta, title))
  .then((tags) => tags.sort().join('\n'))
  .then(console.log) // eslint-disable-line no-console
  .catch(console.error); // eslint-disable-line no-console
```

Or if you have it installed locally/globally, you can add it to an npm script:

```js
  "scripts": {
    "api": "node index",
    "cli": "meta-scraper -u https://reddit.com/r/funny"
  }
```

... Then you can just run `npm run cli`:

```html
<link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.reddit.com/r/funny/">
<link rel="alternate" type="application/atom+xml" title="RSS" href="https://www.reddit.com/r/funny/.rss">
<link rel="apple-touch-icon-precomposed" href="//www.redditstatic.com/icon-touch.png">
<link rel="canonical" href="https:///r/funny/">
<link rel="dns-prefetch" href="//out.reddit.com">
<link rel="icon" href="//www.redditstatic.com/icon.png" sizes="256x256" type="image/png">
<link rel="preconnect" href="//out.reddit.com">
<link rel="shortcut icon" href="//www.redditstatic.com/favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="https://b.thumbs.redditmedia.com/Ju1zzvx7kG2OcrYqcS8k5W40yOSjlCYl5XV8KEcRpkE.css" title="applied_subreddit_stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="//www.redditstatic.com/reddit.DZIb11y75Do.css" media="all">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="description" content="reddit: the front page of the internet">
<meta name="keywords" content=" reddit, reddit.com, vote, comment, submit ">
<meta name="referrer" content="always">
<meta name="viewport" content="width=1024">
<meta property="og:description" content="Welcome to r/Funny: reddit&apos;s largest humour depository">
<meta property="og:image" content="https://www.redditstatic.com/icon.png">
<meta property="og:site_name" content="reddit">
<meta property="og:title" content="funny &#x2022; /r/funny">
<meta property="twitter:card" content="summary">
<meta property="twitter:site" content="reddit">
<meta property="twitter:title" content="funny &#x2022; /r/funny">
<title>funny</title>
```

**Comment by edmoz** [comment]
moved here: https://github.com/mozilla/page-metadata-service/issues/85
