### ISSUE TITLE
Option to Disable Trending

### ISSUE THREAD

**Issue by sleepypikachu** [mozilla/activity-stream#1179]
I find the trending news really irrelevant (mainly US politics after I dismissed the CS articles I'd already read from HN). Additionally I just feel like I should be able to control the content that's on my screen.

Can we add an option to disable the trending news?

**Comment by sarracini** [comment]
@sleepypikachu There is an option! At the bottom of your newtab page there's a settings button (looks like a gear and when you hover over it, a button with a label ```settings``` appears). If you click on the button you'll see an option to ```Show Trending Highlights``` where you can toggle it on or off

**Comment by sleepypikachu** [comment]
D'oh! :smile::palm_tree:

Since this is the only option on the gear maybe it should be merged with the about:addons settings? That's where I went looking first, anyway.
