### ISSUE TITLE
implement top 20 highlights UI

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#1181]
This is the eng task for implementing this:

https://trello.com/c/XGRmjDGR/63-i-want-to-see-more-highly-relevant-content-on-my-new-tab

![177705068](https://cloud.githubusercontent.com/assets/3698618/18012777/d0682750-6b6f-11e6-8b98-32def4b1f14a.png)

**Comment by edmoz** [comment]
Triage: we want to run this as an experiment

**Comment by bryanbell** [comment]
let's do straight to this. 

https://mozilla.invisionapp.com/share/E78LSLGQH#/177705068_NewTab_-_More_Highlights

https://mozilla.invisionapp.com/static-signed/live-embed/22240415/177705068/5/latest/hwRBAB4lEfnJi8lDy1lEeLQizReEa9mTBfDlEgvN9xnKPjy9WQiTznMSgQszrrByduOlEeYii7RGCPHtchm1yjSxdwlE/NewTab---More-Highlights-2x.png
