### ISSUE TITLE
New tab reverted to tiles after enabling and disabling e10s

### ISSUE THREAD

**Issue by ckarlof** [mozilla/activity-stream#1182]
I accidentally enabled e10s, and after disabling I still see old "tiles" on my new tab page. I've tried restarting and disabling and re-enabling AS. I'm in Nightly 51.0a1 (2016-08-26).

<img width="1141" alt="screenshot 2016-08-26 10 10 14" src="https://cloud.githubusercontent.com/assets/2365255/18013930/60f8f31c-6b75-11e6-89f7-2e7c953feded.png">

**Comment by ckarlof** [comment]
Removing and re-installing didn't fix it either.

**Comment by rlr** [comment]
This is *probably* due to issue #1173 which is fixed but we haven't cut a release yet. Want to try the dev channel and see if that fixes it? https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html

**Comment by ckarlof** [comment]
Awesome, that fixed it. Thanks @rlr!
