### ISSUE TITLE
Load Latency by Addon Version + OS + FX version

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1187]
We need some more detailed graphs to see if the most recent load latency issues are different on different platforms.

**Comment by k88hudson** [comment]
Just some notes here:

- For both Firefox version and OS, I think it might be more useful to have load latency statistics for each add-on version separately, or perhaps for just the latest few releases; this will help us detect changes or regressions introduced by specific changes we made.
- We might want to consider using the median for each statistic, to account for outliers

Also: I think we should work on the definition/implementation for First Load Latency to make sure it’s more accurate; right now we’re using an unreliable timer on the add-on side, and we should probably we’re not accounting for message latency at the end of the event. This can be adressed in a separate issue though

**Comment by emtwo** [comment]
@k88hudson I've added a few more graphs here: https://sql.telemetry.mozilla.org/dashboard/activity-stream-performance

Let me know if you'd like to see anything more or differently. Thanks!

**Comment by emtwo** [comment]
Incorporated additional feedback from @k88hudson into the performance dashboard here: https://sql.telemetry.mozilla.org/dashboard/activity-stream-performance

Closing this issue as complete
