### ISSUE TITLE
Investigate Homu - a tool for automating github merges

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1191]
Some background on this tool here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1291901

basically it could help automate our review process by checking for r[?+] annotations, tracking reviewers and handling the merge by integrating through Travis.  The Rust team is using Homu:

http://huonw.github.io/blog/2015/03/rust-infrastructure-can-be-your-infrastructure/

**Comment by jaredkerim** [comment]
Closing this based on feedback from the team that merging is not a bottleneck.
