### ISSUE TITLE
Ability to render Trending results in /debug UI tester

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1200]
Re: resource://activity-streams/data/content/activity-streams.html#/debug

It'd be kind of cool if we could select "Trending" from the Data Source dropdown, to render the 20 URLs from the recommendation engine: https://embedly-proxy.services.mozilla.com/v2/recommendations

**Comment by sarracini** [comment]
Closing this since we removed all the trending content stuff
