### ISSUE TITLE
Highlight age changes after being bookmarked

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#1201]
Bookmark any article that shows up in highlights and is older than 1hr.
After page refresh highlight age is listed as 1hr although metadata behind the article still holds correct age.
<img width="240" alt="screen shot 2016-08-31 at 11 09 36 pm" src="https://cloud.githubusercontent.com/assets/810040/18157100/26783018-6fd0-11e6-9ac0-1ca040afb5df.png">

Is this intentional?

**Comment by jaredkerim** [comment]
Highlights are going away and so I will close this.
