### ISSUE TITLE
provide assets for test pilot's social card previews

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#1211]
Test pilot has a feature where we an define the preview image for FB and Twtr, please create assets so that links to:
https://testpilot.firefox.com/experiments/activity-stream

display with the correct image preview

<img width="444" alt="screen shot 2016-09-02 at 10 32 11 am" src="https://cloud.githubusercontent.com/assets/3698618/18213919/52817144-70ff-11e6-99dc-7d856193191b.png">

**Comment by aaronrbenson** [comment]
Using consistent images from the landing site but cropped out the search bar to show more of the top sites and highlight cards.

![facebook_preview](https://cloud.githubusercontent.com/assets/139451/18275535/00167a24-740d-11e6-8657-1b39a9804e25.png)
![twitter_preview](https://cloud.githubusercontent.com/assets/139451/18275536/002cde54-740d-11e6-9803-fac9b71090e4.png)

**Comment by edmoz** [comment]
I've updated test pilot

**Comment by edmoz** [comment]
i see this when i curl:
         <meta property="og:image" content="https://testpilot-prod.s3.amazonaws.com/experiments_experiment/e/1/e19739ea25188c866b654d3aa2616b27_image_1473186642_0826.png" />
        <meta name="twitter:image" content="https://testpilot-prod.s3.amazonaws.com/experiments_experiment/e/1/e19739ea25188c866b654d3aa2616b27_image_1473186642_0579.png" />

But my previews look cached - prob need to wait a few hrs

**Comment by lmorchard** [comment]
FWIW, [the thumbnails show up on Facebook's OpenGraph debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftestpilot.firefox.com%2Fexperiments%2Factivity-stream). Might take a long, long while for Facebook & Twitter to get around to re-crawling

**Comment by lmorchard** [comment]
Also checked [Twitter's card validator](https://cards-dev.twitter.com/validator), and the preview showed up.
