### ISSUE TITLE
Activity stream UI should go 100% width

### ISSUE THREAD

**Issue by edwinwongsf** [mozilla/activity-stream#1212]
currently A-S only displays at 50% width or 1200px of screen.  We should consider going 80-100%.

**Comment by pdehaan** [comment]
![new_tab](https://cloud.githubusercontent.com/assets/557895/18218494/df557666-7117-11e6-805f-ff2447b003f3.png)
**Figure 1:** Full screen on my 15" rMBP (~1440x880px)

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/18218524/061dcb9a-7118-11e6-8cfe-5d832820b85b.png)
**Figure 2:** Full screen on my external 30" Dell monitor (2560x1413px)

**Comment by Emboli** [comment]
There should be an _**option to customize**_ the _**number of rows and columns**_ individually of _Top Sites, Highlights_ and _Recent Activity_. If we have more space in our screen, or if you need more Top Sites to be shown, you can adjust it to your needs.
