### ISSUE TITLE
Error "IndexSizeError: Index or size is negative or greater than the allowed amount" @ ColorAnalyzer.js:53

### ISSUE THREAD

**Issue by marco-c** [mozilla/activity-stream#1225]
I'm seeing this error in the browser console when opening a new tab page.

The page isn't populated with thumbnails, but there's the message "Hang on tight! We are analyzing your history to personalize your experience".

The line in question is: `this.startJob(ctx.getImageData(0, 0, canvas.width, canvas.height),`.

**Comment by jaredkerim** [comment]
#1014 will fix and close this.  If it recurs, please file again.
