### ISSUE TITLE
Bring back "Restore Previous Session" button on the new page

### ISSUE THREAD

**Issue by ericawright** [mozilla/activity-stream#1229]
Opening for @MrJustMe 

"A link with the same funcionality could be a good replacement if you do no want to bring back the restore button.
I mean this button:
http://i.imgur.com/3qFOh4M.png
In this page:
resource://activity-streams/data/content/activity-streams.html#/

Thanks for reading."

**Comment by alex-mayorga** [comment]
¡Hola!

This just bite me a moment ago.

What would need to happen for this to become "P1"?

¡Gracias!

**Comment by MrJustMe** [comment]
dunno, more people comenting here perhaps?

**Comment by alex-mayorga** [comment]
Actually if this bit of about:home could be brought back somehow that'd be neat IMHO.

![imagen](https://cloud.githubusercontent.com/assets/649262/19091446/41b6af84-8a48-11e6-98a5-267053418a74.png)

**Comment by Emboli** [comment]
I agree, that button saves a lot of trouble, without it I need to go to _Session Manager > Load Session >_ select _Previous Session_ and click _Load_
[New Tab Tools](https://addons.mozilla.org/en-US/firefox/addon/new-tab-tools/) have an option to put the whole row down top or left, but doesn't have the classification of site that you have.

**Comment by trlkly** [comment]
+1 this bug.

As a temporary workaround, I change my start page back to about:home. This is a bit tricky to do, but it can be done. You can always click the Activity Stream button or the New Tab button to open the activity stream again. 

Go to Options, and find the Home Page option on the General tab. Type in `about:hom`. Do not type the `e` yet. Now type a space. Then click behind the space and type the `e`. So your home page is actually "about:home "

If you don't do this, about:home will be replaced with "Mozilla Firefox Start Page," and that will be changed back to Activity Stream the next time you start Firefox.

**Comment by sarracini** [comment]
Closing this in favour of tracking in #2003
