### ISSUE TITLE
Docs for experiments to enable discovery and summarize insights

### ISSUE THREAD

**Issue by edwinwongsf** [mozilla/activity-stream#1232]
Doc should help users discover:
- How to enable an experiment
- Goals and hypothosis
- Results and what insights we can draw
- Links to dashboards in support of experiment

**Comment by jaredkerim** [comment]
Let's see if we can find a way to auto generate an experiments.md from experiments.json

**Comment by jaredkerim** [comment]
This will be handled by https://github.com/mozilla/experimenter
