### ISSUE TITLE
deploy SHIELD study comparing activity stream vs tiles

### ISSUE THREAD

**Issue by edwinwongsf** [mozilla/activity-stream#1235]
step 1: identify the questions we want to answer with the study

**Comment by edmoz** [comment]
@nchapman we need user stories of what specific questions we want to answer with the study.

**Comment by emtwo** [comment]
Just thought I'd drop a relevant link here: https://bugzilla.mozilla.org/show_bug.cgi?id=1301188

We also need a decision on thresholds of differences we'd like to see in order to consider Activity Stream a "success"

**Comment by emtwo** [comment]
Note: issue #1331 includes the initial analysis for this.

**Comment by jaredkerim** [comment]
This will be managed by https://github.com/mozilla/activity-stream/projects/4
