### ISSUE TITLE
Opening a bookmark causes blank address bar

### ISSUE THREAD

**Issue by plieblang** [mozilla/activity-stream#1240]
Platform:  Windows 10, Firefox 48.0.2 Stable
Steps to reproduce:
1.  Have Activity Stream enabled
2.  Open Firefox and go to a website
3.  Open a new tab and keep it on the new tab page
4.  Close the website
5.  Reopen by right-clicking on the current tab
6.  There is no URL in the address bar.

I do have Tab Mix Plus installed, but the issue occurs with both the default Undo Close Tab and also the Tab Mix Plus implementation.

Edit:  This issue actually appears when any bookmark is opened while Activity Stream is enabled.

**Comment by jaredkerim** [comment]
Hi thanks for this, good find!  We're going to attempt to recreate this locally and then investigate a fix!

**Comment by jaredkerim** [comment]
This will be addressed by the new system addon implementation, and so we will not be fixing this for the test pilot implementation.  Closing this as a won't fix.
