### ISSUE TITLE
Highlights are broken for an empty profile on the Timeline page

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1252]
This is with weighted highlights turned on.

**Comment by k88hudson** [comment]
STR: run `npm start`, `npm run firefox`

Screenshot: https://irccloud.mozilla.com/file/tvYVRYgW/Screen+Shot+2016-09-09+at+2.39.23+PM.png

**Comment by piatra** [comment]
Pull request in progress.
