### ISSUE TITLE
Improve responsiveness when clearing timeline search

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1261]
As noted in #1199, when clearing a search, all items that were filtered out try to immediately appear. There could be many items that are showing up at the same time causing a pause in responsiveness when rendering all that content.

<img width="1004" alt="screen shot 2016-09-15 at 10 21 05 am" src="https://cloud.githubusercontent.com/assets/3095/18559961/6c79a24a-7b2e-11e6-9e9c-6bb428a2cbb4.png">

**Comment by nchapman** [comment]
Yes this is critical. It locks up my browser when I clear the search #1303.
