### ISSUE TITLE
Inappropriate 'Hang on tight'

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1264]
here's the traceback:

Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.(unknown)
TypeError: can't access dead object(unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src resource://activity-streams”).activity-streams.html:1
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Fri Sep 09 2016 16:50:39 GMT-0400 (EDT)
Full Message: Error: Could not compute feature score
Full Stack: decay@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/common/recommender/Baseline.js:263:13
scoreEntry@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/common/recommender/Baseline.js:73:17
score/results<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/common/recommender/Baseline.js:168:35
score@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/common/recommender/Baseline.js:166:19
scoreEntries@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/common/recommender/Recommender.js:13:12
_respondToPlacesRequests/</<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/addon/ActivityStreams.js:233:43
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:937:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:816:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:750:11

**Comment by piatra** [comment]
Likely related to https://github.com/mozilla/activity-stream/pull/1242 which that pull request will fix.
Keeping this open until that pull request lands.

**Comment by piatra** [comment]
Pull request for #1241 landed and closed the bug, this should also be fixed. Closing this unless it's reproduced.

**Comment by tspurway** [comment]
Re-opening, this is still happening with the same console output.  I can verify that if I set

`extensions.@activity-streams.weightedHighlights = false`

then restart, the page renders normally.

Let me know what I can do to help reproduce.

**Comment by piatra** [comment]
Found the source of the bug.

```
<andreio> Andrei Oprea [:andreio] is it guaranteed that the image returned has a `size` field?
1:46 PM if it exists of course.
1:46 PM J<jkerim> No
1:46 PM You're talking about size in bytes
1:47 PM We won't provide that
```
