### ISSUE TITLE
Add tests for checking expected PerfMeter tests

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1289]
#1255 replaced the old `PerfMeter` tests with new unit tests in mocha, but we ideally need some tests to make sure the right events are actually being sent on load. We could probably do this with mocha.

We also might want a couple of integration-ish tests in jpm to make sure a `PerfMeter`is correctly initialized and torn down (see https://github.com/mozilla/activity-stream/blob/master/test/test-ExperimentProvider.js as an example)

**Comment by sarracini** [comment]
closing this as won't fix for system addon
