### ISSUE TITLE
No bookmark status for default Top Sites

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1290]
STR: Bookmark a default Top Site from the context menu
Expected: should now show unbookmark option in context menu, as well as on a refresh
Actual: still shows "Bookmark" immediately and on refresh

**Comment by aaronrbenson** [comment]
Default Top Sites should have the same behavior as anything else. Bookmarking a default Top Site should result in showing the "Remove Bookmark" option immediately after bookmarking.

**Comment by sarracini** [comment]
according to aaron in the new specs, we don't have the option to bookmark a default top site, so let's close this:
> aaron
[3:53 PM] 
top sites can have bookmarks
there’s just not a bookmark item in the context menu

> ursula
[3:53 PM] 
oh ok ok
so no bookmark option in context menu for top sites

**Comment by Tobias-B-Besemer** [comment]
So why not?

**Comment by aaronrbenson** [comment]
My perspective here was that the Top Sites section is providing a very specific use in that it acts as a launch pad for getting back to your most frequently visited sites -- which is similar to a bookmark but different enough that having the bookmarks option in the context menu felt a little redundant or unnecessary. I'm not entirely married to this idea, though, and am willing to admit it might have been a bad call. We will revisit this in our UX triage this week and decide on whether or not to update the context menu for Top Sites.

**Comment by Mardak** [comment]
@bryanbell says "sure why not" (as in sure allow default top sites be bookmarkable)

**Comment by k88hudson** [comment]
We've decided to remove bookmarking entirely from all Top Sites as of the latest nightly since they are already pinnable. It's definitely a good idea for defaults have consistent behaviour 👍
