### ISSUE TITLE
Duplicate top site with www. and no-www. domains

### ISSUE THREAD

**Issue by ckarlof** [mozilla/activity-stream#1300]
I'm seeing a site repeated in my "Top Sites". Is that expected?

<img width="292" alt="screenshot 2016-09-15 09 11 15" src="https://cloud.githubusercontent.com/assets/2365255/18557631/82ea86f2-7b24-11e6-94bf-71da1af8ba14.png">

**Comment by pdehaan** [comment]
# ¯\\\_(ツ)\_/¯ 

What are the URLs that they point to?
I think you _can_ get into that point when one is www. and the other isn't, or if one is HTTP and the other is HTTPS.

**Comment by ckarlof** [comment]
Both appear to be http, and one indeed is www. and the other one isn't.

**Comment by piatra** [comment]
I don't think this should happen. Dedupe key is `return host + pathname + query` doesn't look at protocol or www.

**Comment by ckarlof** [comment]
The URLs I see are:

1) yucata.de
2) www.yucata.de/en/CurrentGames

These are the same site, of course.

**Comment by pdehaan** [comment]
Those are different pages.
I think we're just seeing https://github.com/mozilla/activity-stream/issues/405 where "Top Sites" label is misleading.

**Comment by tspurway** [comment]
This is actually working as intended, though we need some design work to make distinction clearer.

**Comment by k88hudson** [comment]
that's a pretty cool/nerdy top site btw

**Comment by pdehaan** [comment]
> that's a pretty cool/nerdy top site btw

![](https://media.giphy.com/media/3Mm6HZud4m2oU/giphy.gif)

**Comment by ckarlof** [comment]
> that's a pretty cool/nerdy top site btw

I'm there every day. :)

**Comment by Mardak** [comment]
@ckarlof do you have either page bookmarked? I can only seem to reproduce if I first create a bookmark to http://yucata.de/

**Comment by ckarlof** [comment]
Yes I have http://www.yucata.de/en/CurrentGames bookmarked.

**Comment by piatra** [comment]
my 2c here. The problem is not that the topsites return both www. and nonwww but actually it does not differentiate between different urls from the same domain. Therefore:
1) yucata.de
2) www.yucata.de/en/CurrentGames
Are actually parsed and the keys are
1) yucata.de
2) yucata.de/en/CurrentGames
Which make them different and valid to take into consideration. So the question is how should we collapse them.
