### ISSUE TITLE
Deleting text from the search box locks up Firefox

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#1303]
When I tried to delete the text that I typed into the search box, it didn't delete and Firefox locked up. 

<img width="1004" alt="screen shot 2016-09-15 at 10 21 05 am" src="https://cloud.githubusercontent.com/assets/3095/18559961/6c79a24a-7b2e-11e6-9e9c-6bb428a2cbb4.png">

It's worth noting that I have a rather large profile.

**Comment by Mardak** [comment]
Duped to #1261
