### ISSUE TITLE
Better UI when no search results found

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1304]
<img width="587" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/18560671/7c8f6464-7b31-11e6-8507-ddbd5ddb7bf2.png">

If I don't have any matching results, we should display some sort of user message so they know that they can stop expecting content.

<img width="718" alt="activity_stream" src="https://cloud.githubusercontent.com/assets/557895/18560659/6b3bbca8-7b31-11e6-9d32-cc1fcf5da29b.png">

Here's an example of Gmail's search results page, if you have no results found:

<img width="569" alt="search_results_-_peterdehaan_gmail_com_-_gmail" src="https://cloud.githubusercontent.com/assets/557895/18560748/cc298496-7b31-11e6-980b-0f956ee4bb5f.png">

**Comment by pdehaan** [comment]
Likewise, a rogue Google.com search:

<img width="720" alt="asdfasdfasdfasdfasdfzxfsada9sd88hfkdsfuapsdfasdf_-_google_search" src="https://cloud.githubusercontent.com/assets/557895/18560833/285c2610-7b32-11e6-83bf-873aa673aa67.png">

**Comment by pdehaan** [comment]
@nchapman suggests that it'd be cool if we offered to do a web search here.

**Comment by sarracini** [comment]
we're removing the filter functionality here so i'll close this as a wont fix
