### ISSUE TITLE
How useful are sessions?

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1309]
I'm just wondering if we are using data related to sessions, or if they've turned out to be not so useful. If the latter is true could we considering removing the code/logic associated with them?

cc @nchapman @sarracini

**Comment by jaredkerim** [comment]
Requires feedback from @emtwo to determine whether this is doable.

**Comment by emtwo** [comment]
The most common use case I have for session data is to look at users who are opening Activity Stream regardless of whether they interact with anything and trigger events. It's also been useful to Nick to see how many sessions have no interactions and end with navigation-only. I imagine we'll make more use of session durations and load/unload reasons in the future as well.

That said, it **might** be possible to implement session pings as 2 events: 1 at the start and 1 at the end of the session. However, my guess is this won't help you get rid of much code and may just be more unnecessary work.

**Comment by sarracini** [comment]
Closing this since we know how useful they are
