### ISSUE TITLE
Race condition in ShareProvider

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1314]
There is a race condition in `ShareProvider.js` I noticed while working on performance improvements that is revealed by the page loading much quicker.

If you access the property `.socialProviders`, there is a chance it will return `undefined`. This will in turn cause the `providers` property on the reducer to be `undefined`, which will cause a fatal error.

**Comment by jaredkerim** [comment]
Requires feedback from @rlr

**Comment by rlr** [comment]
I looked into this a bit but I can't really find any code path that would cause `_shareProvider.socialProviders` to be undefined. @k88hudson do you remember how you triggered this? Unless I am missing something, it will always be an array as long as `_shareProviders` has been created (`new ShareProvider()`). And `_refreshAppState()` is always called after the share provider is created. What am I missing?

**Comment by rlr** [comment]
fixed via pull #1492
