### ISSUE TITLE
Race condition in TabTracker

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1315]
Right now we are initializing most tab data in the  tabs/`"ready"` event, but  there is actually a chance we could receive the Time to First Load event from content _before_ `"ready"` fires. There is a quick fix for this implemented so that at least we will have the tab `id`, but we should probably do what `PerfMeter` does and initialize in the`"open"` event, and just delete the tab if necessary in the `"ready"` event

**Comment by k88hudson** [comment]
Would love to know abt https://github.com/mozilla/activity-stream/issues/1309 before deciding on a course of action for this

**Comment by ncloudioj** [comment]
This is already fixed in 5b972f05e6b644af5e312738837a0e50d83f33e1
