### ISSUE TITLE
Bookmarking is slow

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1316]
Not sure if this is just my machine, but I'm sometimes seeing a considerable delay between bookmarking the item and the UI updating (i.e. receiving the message back with the bookmark data).

I've seen this for both highlights and recent activity

**Comment by jaredkerim** [comment]
Requires verification

**Comment by sarracini** [comment]
So after some investigation, I've found the reason why bookmarking is slow.
The culprit seems to be here https://github.com/mozilla/activity-stream/blob/master/common/reducers/SetRowsOrError.js#L41 where we're iterating over all the history entries and finding which one was the one we bookmarked and then update it. The bigger the history size, the slower it'll be.
On top of doing this loop many times, we're also receiving as many as 5 'RECEIVE_BOOKMARK_ADDED' actions every time we bookmark, which means we're also doing the looping 5 times.
That's a lot. Will look into solutions for this

cc @k88hudson

**Comment by Mardak** [comment]
I would think there are the 5 instances because there's 5 reducers using `SetRowsOrError`: https://github.com/mozilla/activity-stream/blob/master/common/reducers/reducers.js#L11-L15 but I would think each of these's `prevState.rows` has 20 or fewer items. Iterating over 100 items shouldn't take a couple seconds. I'm guessing the delay is more from when the `NOTIFY_BOOKMARK_ADD` and before a `RECEIVE_BOOKMARK_ADDED` happens.

**Comment by sarracini** [comment]
Though there is some delay between modifying places and actually sending down the message, the actual operation of inserting the bookmark is async, so I tried to add a fake bookmarkGuid attribute to the original link and send that down immediately without waiting for the notification to fire from places and it's still slow to show the actual star on larger history. Leads me to believe the unnecessary looping contributes to the delay.
I also don't know that we can necessarily get away from the delay between inserting the bookmark and then getting a notification from places, whereas we can definitely improve the content side speedyness to draw the star. Ideally you would bookmark something, draw the star immediately for that link and then let the bookmarking stuff on addon side take the time it needs

**Comment by Mardak** [comment]
I agree that having the UI update immediately from the local event would be better for responsiveness.

I tried digging into the delay, and at least for me, the `gLinks.getBookmark` seems to be slow. Do you also see this similar over 1-second time delay when bookmarking?

```
console.log: activity-streams: getBookmark time 1344
console.log: activity-streams: getBookmark time 1346
console.log: activity-streams: getBookmark time 1347
```
```diff
diff --git a/addon/PlacesProvider.js b/addon/PlacesProvider.js
index e8eb878..869e454 100644
--- a/addon/PlacesProvider.js
+++ b/addon/PlacesProvider.js
@@ -220,17 +220,19 @@ Links.prototype = {
 
   /**
    * A set of functions called by @mozilla.org/browser/nav-bookmarks-service
    * All bookmark events are emitted from this object.
    */
   bookmarksObserver: {
     onItemAdded(id, folderId, index, type) {
       if (type === Bookmarks.TYPE_BOOKMARK) {
+        let added = new Date();
         gLinks.getBookmark({id}).then(bookmark => {
+          console.log("getBookmark time", new Date() - added);
           gLinks.emit("bookmarkAdded", bookmark);
         });
       }
     },
 
     onItemRemoved(id, folderId, index, type, uri) {
       if (type === Bookmarks.TYPE_BOOKMARK) {
         gLinks.emit("bookmarkRemoved", {bookmarkId: id, url: uri.spec});
```

**Comment by sarracini** [comment]
I don't get quite one second, but my history size is probably smaller.
What I did was:
```diff
diff --git a/addon/ActivityStreams.js b/addon/ActivityStreams.js
index ea65e58..ef080f6 100644
--- a/addon/ActivityStreams.js
+++ b/addon/ActivityStreams.js
@@ -326,7 +326,9 @@ ActivityStreams.prototype = {
         });
         break;
       case am.type("NOTIFY_BOOKMARK_ADD"):
-        PlacesProvider.links.asyncAddBookmark(msg.data);
+        //PlacesProvider.links.asyncAddBookmark(msg.data.url);
+        let bookmark = Object.assign({}, msg.data, {bookmarkGuid: "mA3e7N6M8B23"});
+        this.broadcast(am.actions.Response("RECEIVE_BOOKMARK_ADDED", bookmark));
         break;
       case am.type("NOTIFY_BOOKMARK_DELETE"):
         PlacesProvider.links.asyncDeleteBookmark(msg.data);
@@ -439,7 +441,7 @@ ActivityStreams.prototype = {

     switch (eventName) {
       case "bookmarkAdded":
-        this.broadcast(am.actions.Response("RECEIVE_BOOKMARK_ADDED", data));
+        // this.broadcast(am.actions.Response("RECEIVE_BOOKMARK_ADDED", data));
         break;
       case "bookmarkRemoved":
         this.broadcast(am.actions.Response("RECEIVE_BOOKMARK_REMOVED", data));
```

Just make a fake bookmarkGuid and don't go to places at all, send down a 'bookmark' immediately after you receive the request (just to test out how long the content side is taking). 
Though it's faster, there's still a delay and the looping seems to be happening ~150 times.

I don't think there's anything we can do about ```gLinks.getBookmark``` to speed it up, so i'm going to try to just draw the star on the local item and let the bookmark come back whenever it gets added

**Comment by Mardak** [comment]
Can you check what's the delay from `LinkMenu.js` calling `actions.NotifyBookmarkAdd` to `ActivityStreams.js` handling `case am.type("NOTIFY_BOOKMARK_ADD"):`? That seems to be a couple hundred milliseconds already. If so, we can probably make things more responsive by having `LinkMenu.js` directly dispatch a fake `bookmarkGuid` with `RECEIVE_BOOKMARK_ADDED` to speed things up even more.

**Comment by sarracini** [comment]
Takes ~ 120ms from dispatching to receiving, is what I got. 
I'm worried faking the bookmarkGuid on content side might lead to some race conditions when we get the actual bookmarkGuid back from the addon at some point. Is there another way we can trick the content side to just draw the star? Something along the lines of:

```diff
diff --git a/addon/ActivityStreams.js b/addon/ActivityStreams.js
index ea65e58..b3c517b 100644
--- a/addon/ActivityStreams.js
+++ b/addon/ActivityStreams.js
@@ -327,6 +327,7 @@ ActivityStreams.prototype = {
         break;
       case am.type("NOTIFY_BOOKMARK_ADD"):
         PlacesProvider.links.asyncAddBookmark(msg.data);
+        this.broadcast(am.actions.Response("RECEIVE_BOOKMARK_ADDED", msg.data));
         break;
       case am.type("NOTIFY_BOOKMARK_DELETE"):
         PlacesProvider.links.asyncDeleteBookmark(msg.data);
diff --git a/common/reducers/SetRowsOrError.js b/common/reducers/SetRowsOrError.js
index fd0e4f1..5c2e2a3 100644
--- a/common/reducers/SetRowsOrError.js
+++ b/common/reducers/SetRowsOrError.js
@@ -38,10 +38,10 @@ module.exports = function setRowsOrError(requestType, responseType, querySize) {
         break;
       case am.type("RECEIVE_BOOKMARK_ADDED"):
         state.rows = prevState.rows.map(site => {
           if (site.type === "history" && site.url === action.data.url) {
             const {bookmarkGuid, bookmarkTitle, lastModified} = action.data;
             const frecency = typeof action.data.frecency !== "undefined" ? action.data.frecency : site.frecency;
-            return Object.assign({}, site, {bookmarkGuid, bookmarkTitle, frecency, bookmarkDateCreated: lastModified});
+            return Object.assign({}, site, {bookmarkGuid, bookmarkTitle, frecency, bookmarkDateCreated: lastModified, showBookmark: true});
           }
           return site;
         });
diff --git a/content-src/components/ActivityFeed/ActivityFeed.js b/content-src/components/ActivityFeed/ActivityFeed.js
index 458102d..3061ffb 100644
--- a/content-src/components/ActivityFeed/ActivityFeed.js
+++ b/content-src/components/ActivityFeed/ActivityFeed.js
@@ -63,7 +63,7 @@ const ActivityFeedItem = React.createClass({

     return (<li className={classNames("feed-item", {bookmark: site.bookmarkGuid, active: this.state.showContextMenu})}>
       <a onClick={this.props.onClick} href={site.url} ref="link">
-        <span className="star" hidden={!site.bookmarkGuid} />
+        <span className="star" hidden={!site.bookmarkGuid || !site.showBookmark} />
         {icon}
         <div className="feed-details">
           <div className="feed-description">
```

**Comment by sarracini** [comment]
That way the site will still recieve it's real bookmarkGuid whenever the addon finishes and we don't block on it, and there's no race.
And then on top of that we could also reduce the number of times it loops, and also the fact that it gets caught in the reducer 5 times. I think a combination of these 3 things should really speed it up

**Comment by Mardak** [comment]
> Takes ~ 120ms from dispatching to receiving

Okay, so we can save on that overhead by dispatching directly from content instead of waiting for the add-on to receive it.

> I'm worried faking the bookmarkGuid on content side might lead to some race conditions when we get the actual bookmarkGuid back from the addon at some point

I would assume the local content fake guid dispatch would always be faster than content -> add-on -> places -> add-on -> content. Could you try measuring the time from local content event -> fake guid -> star render?

> Is there another way we can trick the content side to just draw the star?

Your extra `showBookmark` seems like a fine fix for this issue, and that by itself could be good enough. It would seem unlikely that someone bookmarking immediately will want to unbookmark before the real guid arrives.

**Comment by Mardak** [comment]
I just tried testing again as per https://github.com/mozilla/activity-stream/issues/1316#issuecomment-250381667 and instead of getting times over 1 second, they're all in the range of 10-20ms on `master`.

If I go back to `v1.1.5`, running the same timing tests, I now get ~2 second delays. `v1.1.7` has delays ~130ms. `v1.1.9` ~105ms. `v1.2.0` ~15ms.

Resolving as fixed.
