### ISSUE TITLE
Activity Stream hangs on Fx 45

### ISSUE THREAD

**Issue by smiddy** [mozilla/activity-stream#1327]
My activity is broken: Whenever I open a new tab, the stream is not able to collect the data (see screenshot). The activity stream is not usable at all.

I am running
Firefox 45.3.0
Scientific Linux 7.2 64-bit
The user profile is on a network server (client system)

**Comment by smiddy** [comment]
![screenshot from 2016-09-19 15-36-45](https://cloud.githubusercontent.com/assets/4051014/18634321/bd0bcf26-7e80-11e6-8025-a99514f206b7.png)
Here the screenshot

**Comment by ncloudioj** [comment]
Thanks for reporting this! @smiddy 

Did you just install this addon for the first time? Or it just break after the recent update?

**Comment by smiddy** [comment]
When did you issue the update? It worked before on the SL mashine and is up and running on my ubuntu mashine.

**Comment by smiddy** [comment]
I am on Test Pilot.

This is what I get out of the web console:

17:39:48.706 Content Security Policy: Directive 'frame-src' has been
deprecated. Please use directive 'child-src' instead.1 <unknown>

17:39:48.875 mutating the [[Prototype]] of an object will cause your
code to run very slowly; instead create the object with the correct
initial [[Prototype]] value using Object.create1 bundle.js:67546:416

17:39:48.915 TypeError: arguments is not iterable
defineActions/</composed() bundle.js:7081
componentDidMount() bundle.js:7141
[228]/<.notifyAll() vendor.bundle.js:21
[1339]/m.close() vendor.bundle.js:24
[42]/r<.closeAll() vendor.bundle.js:3
[42]/r<.perform() vendor.bundle.js:3
s() vendor.bundle.js:21
[42]/r<.perform() vendor.bundle.js:3
[1330]/_.batchedUpdates() vendor.bundle.js:23
o() vendor.bundle.js:2
[238]/I._renderNewRootComponent() vendor.bundle.js:22
[238]/I._renderSubtreeIntoContainer() vendor.bundle.js:22
[238]/I.render() vendor.bundle.js:22
renderRootWhenAddonIsReady() bundle.js:36
<anonymous> bundle.js:43
t() vendor.bundle.js:1
window.webpackJsonp() vendor.bundle.js:1
<anonymous> bundle.js:1
1 bundle.js:7081:67

**Comment by ncloudioj** [comment]
Thanks a lot! @smiddy This is very helpful.

**Comment by k88hudson** [comment]
This is related to a bug in the Firefox implementation of `arguments`, which I thought was fixed in `45`, but it was possibly fixed in `46`

**Comment by emtwo** [comment]
Just to confirm priority on this, we have about 30-80 unique daily users on Firefox 45 at the moment:
https://sql.telemetry.mozilla.org/queries/1241#2150

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
I cannot even write something in the search bar. Using Firefox ESR 45.4.0 and installed your add-on today.

**Comment by alex-mayorga** [comment]
¡Hola!

I sometimes get and info bar at the bottom of the browser that reads: "Activity Stream might be making Nightly run slowly"

Is this the same bug or a different one?

¡Gracias!

**Comment by davidhedlund** [comment]
@smiddy Why did you close the issue without comment?

**Comment by davidhedlund** [comment]
[mylabel:open](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aopen%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by smiddy** [comment]
I believe there is no need to fix this bug, since it is a problem solved in fx46. And fx45 is going to be retired in a couple of weeks.
So I would label as wontfix.

**Comment by davidhedlund** [comment]
@smiddy IceCat is based on Firefox ESR 45. Will Firefox ESR 45 be retired in a couple of weeks as well?

**Comment by davidhedlund** [comment]
@smiddy Can you please document that  Activity Stream require Firefox 46 or higher?
