### ISSUE TITLE
Add  contributing.md

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1329]

**Comment by pdehaan** [comment]
If we need inspiration, I vaguely recall we have them for the following projects:

- [mozilla/testpilot](https://github.com/mozilla/testpilot/blob/master/CONTRIBUTING.md)
- [mozilla/web-ext](https://github.com/mozilla/web-ext/blob/master/CONTRIBUTING.md)
- [mozilla/addons-linter](https://github.com/mozilla/addons-linter/blob/master/CONTRIBUTING.md)
- [mozilla/fxa-content-server](https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md)
- [mozilla/fxa](https://github.com/mozilla/fxa/blob/master/CONTRIBUTING.md)

**Comment by Standard8** [comment]
Loop also had one: https://github.com/mozilla/loop/blob/master/CONTRIBUTING.md

Note we had a separate "Developing" doc  as well: https://github.com/mozilla/loop/blob/master/docs/Developing.md
