### ISSUE TITLE
Coverage fails when running karma tests

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#1330]
All tests pass. Exit code is 0. Istanbul karma coverage fails.
From what I have experienced this happens when doing require overrides `require("inject!addon/AvocadoProvider");`

![screen shot 2016-09-19 at 9 48 28 am](https://cloud.githubusercontent.com/assets/810040/18640742/4b6c0f02-7e4e-11e6-9ac1-08e5f032424f.png)

**Comment by dmose** [comment]
I'm seeing this just running 'npm run tdd' on master.

**Comment by sarracini** [comment]
Fixed with #1374
