### ISSUE TITLE
Refreshing Timeline view loads Main AS page

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#1333]
As spotted by @sarracini.

**Comment by sarracini** [comment]
**STR** (on latest master):
Visit a page 
Open new tab 
Click 'see more activity'
Refresh the page

**Expected Results**:
Refresh the Timeline Activity Stream page

**Actual Results**:
Refresh the New Tab Activity Stream page

**Comment by jaredkerim** [comment]
Related to shared redux state.

**Comment by sarracini** [comment]
Closing this as timeline is now gone
