### ISSUE TITLE
Move experimentProvider init into constructor

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1343]
Presently we initialize the experiment provider outside of its constructor which could theoretically lead to the case where we attempt to access its member variables before it is initialized we could lead to destructive behaviour in our experiments.  We should initialize it in its constructor.

**Comment by k88hudson** [comment]
Personally I don't agree with having side effects such as adding listeners, setting prefs, etc. in constructors for the following reasons:

- you can accidentally initialize them and forget to tear them down, causing memory leaks or failures in a non-obvious way. If you forget to initialize, your code fails very quickly very obviously. 
- if your initialization work has to include async stuff in the future, refactoring is harder
- it makes testing more difficult, if you need to stub things out or spy on methods

That said,  `init` is not a particularly descriptive and could be named better

**Comment by k88hudson** [comment]
That said, most of my reservations here are pretty theoretical. If you want to do this, just also remove this line and the tests should pass: https://github.com/mozilla/activity-stream/blob/master/content-test/addon/ExperimentProvider.test.js#L34

**Comment by jaredkerim** [comment]
Closing this after discussion with @k88hudson
