### ISSUE TITLE
First time use data from Firefox

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#1348]
For fresh profiles you get a couple of default values in your history and bookmarks which (in my opinion) don't go great with activity stream.
**Default bookmarks (5 of them)**: these will overtake your highlights because.. they are bookmarks, these have invalid dates because they have not really been visited.
![screen shot 2016-09-20 at 3 19 15 pm](https://cloud.githubusercontent.com/assets/810040/18691025/36f3d16a-7f46-11e6-904f-c1a0a85273a9.png)
![screen shot 2016-09-20 at 3 19 28 pm](https://cloud.githubusercontent.com/assets/810040/18691039/45d072e2-7f46-11e6-9579-4c33f58a4f9b.png)

These are separate from our regular first time use data.
What should be the action here? Drop them? Keep them and try to merge them with others?

**Comment by pdehaan** [comment]
I think originally we were showing a few dummy/filler items for Highlights if the user had no browsing data. Here's what they look like in the debug page:

![new_tab](https://cloud.githubusercontent.com/assets/557895/18691998/0fcc84f0-7f4c-11e6-8751-1ebdd5faec66.png)

You can also see that we override the "Bookmarked" labels and hide the timestamps for these special cases.

Not sure if we still want to do that for "new" profiles, but I agree that the current UI doesn't look that great with 5 default bookmarks.

**Comment by piatra** [comment]
@pdehaan it's not by choice we show those extra websites, they are default bookmarks in Firefox. They are more obvious now when we don't have rules such as "Display exactly one bookmark in the first position".

**Comment by pdehaan** [comment]
Are those 5 default bookmarks always the same, or are they locale specific?

**Comment by pdehaan** [comment]
For example, I just created a new profile in Aurora/DevEd and I seem to have the following URLs:

- https://www.mozilla.org/en-US/firefox/help/ "Help and Tutorials"
- https://www.mozilla.org/en-US/firefox/customize/ "Customize Firefox"
- https://www.mozilla.org/en-US/contribute/ "Get Involved"
- https://www.mozilla.org/en-US/about/ "About Us"
- https://www.mozilla.org/en-US/firefox/central/ "Getting Started"

Not sure if other versions of Firefox would include the "en-US" or have other locale-specific URLs.

**Comment by sarracini** [comment]
Closing this since default cards were removed
