### ISSUE TITLE
Color Analyzer still throwing 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1356]
Just received a report from @jbuck that `ColorAnalyzer` is still throwing, on line `53`. This is on version `1.1.3`, which does include the latest fix.

**Comment by k88hudson** [comment]
This is the site and the image that causes the error:

https://compat.spec.whatwg.org/
https://resources.whatwg.org/logo-compat.svg

**Comment by k88hudson** [comment]
Also, it looks like the error happens in an asynchronous context (i.e. image `onLoad` event) so the try-catch block wont catch the error 😢

**Comment by k88hudson** [comment]
I looked into whether it was possibly failing on svgs, and I found this was not the case. For example, https://css-tricks.com/wp-content/uploads/2015/05/kiwi.svg loads fine

**Comment by ncloudioj** [comment]
😡 ColorAnalyzer, I hate you.

K, will take a look what we can do.
