### ISSUE TITLE
Add l10n (or i18n, or whatever it is)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#136]
Currently we only have a small handful of localizable strings.

https://github.com/MozillaFoundation/mofo-example-app/issues/13 and https://github.com/mozilla/donate.mozilla.org/blob/master/docs/Localization.md may have a few pointers.

We've used http://l20n.org/ in other projects, but not sure how well that'll play w/ React and add-ons.

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/13128364/2111591e-d58a-11e5-884a-733317b59f96.png)

**Comment by pdehaan** [comment]
![new_tab](https://cloud.githubusercontent.com/assets/557895/13128520/174b1496-d58b-11e5-917f-1ddff98677ac.png)
**Figure 2:** The "Timeline/Activity Stream" page also has a few different strings which could be localized.

**Comment by k88hudson** [comment]
Personally I like to use `react-intl`

**Comment by oyiptong** [comment]
We'll need to get the strings localized. The first release is en-US only.

**Comment by gasolin** [comment]
In my previous usage l20n works pretty good. 
@zbraniecki do you have experience to have l20n work with React or add-ons?

**Comment by zbraniecki** [comment]
If activity-streams are going to be plugged into our l10n toolchain, `react-intl` will not work because it uses MessageFormat which is not supported by our toolchain.

l20n.js would be a better option, but I'm not sure if we already have react bindings. If we don't, we should add them and activity-stream may be a good project to make it happen :) @stasm ?

**Comment by oyiptong** [comment]
We don't have any plans at the moment for a language other than en-US. The experiment is set to only run for that locale. We can think about longer term commitments when it comes the time to think about for a gecko implementation.

**Comment by stasm** [comment]
I'm planning on adding experimental support for React to L20n and I'm looking for a project to test it :)  I'd love to take this opportunity and use activity-streams in my research!

**Comment by oyiptong** [comment]
excellent and great to hear :-)

**Comment by pdehaan** [comment]
Ref: #429

**Comment by k88hudson** [comment]
This is on hold for now, but linking to PR by @stasm for some ideas/prior work when we do get to this
