### ISSUE TITLE
Selecting "Open in a new Window" or "Open in a Private Window" opens the specified URL in two new windows

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1363]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18725999/63f6c760-7ff7-11e6-905a-8f58f5ae157d.png)

### Steps to reproduce:

1. Hover over an item in Highlights or Recent Activity.
2. In the context menu, select "Open in a New Window" or "Open in a Private Window".

### Actual results:
TWO windows are opened.

![activity-stream-extravagance](https://cloud.githubusercontent.com/assets/557895/18726154/faf1f586-7ff7-11e6-8893-582f94f692bb.gif)

### Expected results:
ONE window is sufficient. Two is just being extravagant.

**Comment by rlr** [comment]
@pdehaan Can you still reproduce this? And, if so, can you provide more details (addon and browser versions, etc)?

I'm unable to reproduce on dev edition with my full profile or on nightly with a fresh profile.

**Comment by rlr** [comment]
(Just saw you did provide the addon version.) I tested the latest dev release.

**Comment by pdehaan** [comment]
Unable to repro in today's Nightly with official 1.1.4 add-on and 1.1.4-dev-1475178038 dev add-on.

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18970272/76a55bd4-8645-11e6-8d24-605ad611cb6c.png)

**Comment by rlr** [comment]
cant repro either so far. please reopen if it happens again.
