### ISSUE TITLE
Loading message is always displayed in AS Timeline History page after a refresh

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#1368]
**[Affected versions]:**
-Nightly 52.0a1 (Build ID: 20160921030221)
-Activity Stream 1.1.4-dev

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a fresh profile.

**[Steps to reproduce]:**
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Wait until AS Timeline History page has loaded.
4. Click on Refresh button.

**[Expected results]:**
-After the refresh has been made, the loading animation and text is dismissed.

**[Actual results]:**
-The loading animation and text is forever displayed.

**[Notes]:**
- Below is a recording of the issue:
  ![forever loading](https://cloud.githubusercontent.com/assets/9248513/18749397/5ee4e32c-80df-11e6-926c-a6791f906fb5.gif)

**Comment by sarracini** [comment]
Closing this as Timeline is now gone
