### ISSUE TITLE
Timestamp is not updated for revisited websites from AS Timeline History

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#1371]
**[Affected versions]:**
-Nightly 52.0a1 (Build ID: 20160921030221)
-Activity Stream 1.1.4-dev

**[Affected Platforms]:**
-All Windows

**[Prerequisites]:**
-Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a profile.
-Multiple pages were previously visited in order to have items displayed in all areas of both “Timeline” and “New Tab” pages. 

**[Steps to reproduce]:**
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on a website displayed in AS Timeline History.
4. Click on "Activity Stream" button from browser toolbar.
5. Observe the timestamp for the visited website.

**[Expected results]:**
-Timestamp has been correctly updated.

**[Actual results]:**
-The visited website is moved to the first position in AS Timeline History but it has the old timestamp.

[Notes]:
- This issue is also reproducible in AS New Tab.
- Below is a recording of the issue:

![timestamp is not updated](https://cloud.githubusercontent.com/assets/9248513/18752519/55ff4688-80eb-11e6-94fc-9ed3facb46be.gif)

**Comment by sarracini** [comment]
We're removing timeline so closing this
