### ISSUE TITLE
Revert weighted highlights override

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#1381]
Dev channel currently has weighted highlights on by default for everyone. Make sure to revert this and only keep it as an experiment when cutting the next release.
[Key line is here](https://github.com/mozilla/activity-stream/commit/64330436dd020285d34f457b7e59c107a7e34895#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R218).

**Comment by jaredkerim** [comment]
This must be reverted before we release.
