### ISSUE TITLE
Use larger icons when available for top sites (apple-touch-icons)

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1383]
Split from #1311. Fixed in [**page-metadata-parser**](https://github.com/mozilla/page-metadata-parser)

**Comment by jaredkerim** [comment]
This will be handled when #904 lands.  Closing as a duplicate.

**Comment by Mardak** [comment]
#904 is already closed but potentially references a new PR #1157 which references issue #1017.
