### ISSUE TITLE
Collapse redirected top sites and combine their frecency

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1388]
Split from #1311. moz_placeshistory has referrer information that could be used.

**Comment by Mardak** [comment]
The top frecent sites query already includes `hidden = 0` which should prevent a page that is only redirected to from showing up.

**Comment by jaredkerim** [comment]
This is blocked on being able to confidently reproduce it.

**Comment by sarracini** [comment]
Closing this since we can't reproduce this, and we will re-open if we find an issue with redirects
