### ISSUE TITLE
Opening a new Container tab with activity stream active remains on "Hang tight" permanently

### ISSUE THREAD

**Issue by Standard8** [mozilla/activity-stream#1389]
STR
1. On a profile you've been using for a while, go to File -> New Container Tab

=> New Tab opens with a spinner "Hang on tight! We are analyzing your history to personalize your experience" but never returns with anything.

Since containers are only on nightly, this probably isn't super high priority at the moment, but worth watching.

**Comment by jaredkerim** [comment]
Containers are being pulled out of Nightly, closing this.

**Comment by pdehaan** [comment]
Containers are still in Nightly, and I'm seeing a constant refresh issue. Also, from my understanding, we're adding Spaces/Containers as a Test Pilot experiment, so we may need to reopen and investigate this...
In fact, I'll _boldly_ reopen this so we can discuss in a future triage. /cc @nchapman @johngruen

![activity-stream-containers](https://cloud.githubusercontent.com/assets/557895/20191705/9081fda2-a73b-11e6-84a1-b0947087c43b.gif)

**Comment by TanviHacks** [comment]
History isn't tagged with container ids yet.  So I'm not sure why there would be a problem analyzing user history within a container.

Containers is going to be a Test Pilot experiment in late Q4 / early Q1.  So if a user installs it and Activity Stream, then it sounds like they will not have a good experience.

**Comment by sarracini** [comment]
The issue has to do with localStorage... when opening a new tab in a container and opening up the console, you can see there is no ```ACTIVITY_STREAM_STATE``` key on local storage - so we end up spinning forever

**Comment by cpeterso** [comment]
With the [Containers Test Pilot experiment](https://github.com/mozilla/testpilot-containers), new tabs in a container open Firefox's default about:newtab page instead of the Activity Stream page.

**Comment by jaredkerim** [comment]
Compatibility between the test pilot addon and container tabs is out of scope, this can be handled more effectively in the new system addon, closing as a won't fix.
