### ISSUE TITLE
The Share doorhanger is not dismissed when switching tabs with the keyboard shortcut (Ctrl+Tab)

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1406]
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.4-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a new tab and navigate to a website.
3. Click the "Share" button from the browser toolbar.
4. Press Ctrl+Tab and observe the Share doorhanger.

[Expected result]:
- The doorhanger is dismissed.

[Actual result]:
- The doorhanger is still active.

[Additional Notes]:
- Copy Address and Email Link work and the rest of the Share options are actionable but nothing happens when clicked.
- The issue is not reproducible if you navigate to a different tab with the mouse.
- Attached a screen recording of the issue https://goo.gl/OVvg4t.

**Comment by rlr** [comment]
share doorhanger is gone.
