### ISSUE TITLE
Seeing integer overflow in the "performance" ping

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1416]
We've captured some integer overflow errors in the "performance" ping, this affected the database persistence of table `activity_stream_performance_daily`. 

```
colname         | value
type            | int4
raw_field_value | 3113554838
err_reason      | Overflow (Integer valid range -2147483648 to 2147483647)
```

Looks like the `value` field had this issue, as this field is of type "int4". Is it a expected value for this field? @sarracini

**Comment by jaredkerim** [comment]
@ncloudioj What is the `event` field for that row?  That will tell us whether this is a valid value.

**Comment by ncloudioj** [comment]
Redshift only logs the invalid value of that column. I can try getting that whole payload from the logs on DDFS.

**Comment by ncloudioj** [comment]
```JSON
{
"addon_version":"1.1.1",
"date":"2016-09-26",
"event_id":"{ea0f57fb-0929-40ca-86fd-29eadd412235}",
"ip":"74.193.49.144",
"value":3113554838,
"page":"NEW_TAB",
"source":"BUILD_PREVIEW_CACHE",
"timestamp":1474919423632,
"action":"activity_stream_performance",
"tab_id":"-3-9",
"locale":"en-US",
"ua":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko\/20100101 Firefox\/46.0",
"event":"embedlyProxyRequestTime"
}
```

**Comment by dmose** [comment]
Since we're looking at APIs (eg performance.now) that express things with
fractional milliseconds (down to 5 microsecond granularity), if we do end
up wanting to change this now, perhaps it makes sense to change it to a
float for forward compatibility?

2016-09-29 8:57 GMT-07:00 Nan Jiang <notifications@github.com>:

**Comment by ncloudioj** [comment]
@dmose Yes, we need to change the table schema if this is a valid value.

In this case, the `(event, value)` is being used as a generic pair, which multiplexes a couple of different events for the performance monitoring of metadata processing. I think we need to investigate this "value" first. It looks quite suspicious as the value of "BUILD_PREVIEW_CACHE" event.

**Comment by jaredkerim** [comment]
This looks like an invalid value to me.  I doubt that a client waited 36 days to connect to the Embedly Proxy.  If this only happened once then I'll chalk it up to client randomness and we should throw records which overflow like this out.  If there are many records like this, then I think that indicates a reporting bug on the client side.  @ncloudioj how many records that overflow like this are there?

**Comment by ncloudioj** [comment]
@jaredkerim I can poke around the raw logs to see how often this happens in general. Will keep you posted.

If this is related to attacks or similar, we can also add some data cleaning in Infernyx to filter them out.

**Comment by ncloudioj** [comment]
@jaredkerim I couldn't find the similar issue for the "activity-stream-performance-daily" on that day. But this error also happened for the "activity-stream-stats-daily" table. `session_duration = 496126050956`, it could be due to a long-lived tab session or a wrong timing. Anyway, will add a filter to the data pipeline for now.

Let's also make sure the timing in the addon is working as expected.

**Comment by ncloudioj** [comment]
Actually, this particular session_duration looks fairly unreal, 496126050956 in milliseconds is almost 5742 days.

**Comment by tspurway** [comment]
That session is older than the internet!

**Comment by ncloudioj** [comment]
Having added a hotfix for Infernyx to filter out those invalid data points, it's already out in prod. However, it's worth investigating the timing of addon to ensure the accuracy of performance monitoring. Will file a separate issue to track that.
