### ISSUE TITLE
Refactoring of Preview Provider for adding links with metadata to DB

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#1418]
Expose a way in preview provider to 
1) process the links (add a cache_key, places_url....)
2) insert in DB
3) save it in metadataStore Cache

**Comment by sarracini** [comment]
cc @jaredkerim

**Comment by jaredkerim** [comment]
This will allow us to write to preview provider from the new local metadata parser in a way which transparently masks the interfaces to MetadataStore and MetadataCache.
