### ISSUE TITLE
Add former interns to contributors list on Test Pilot

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1425]
Re: https://testpilot.firefox.com/experiments/activity-stream

We should add @piatra and @rittme to the contributors list as "Engineering Intern" or something, that's the label we used for a contributor on Min Vid experiment.

I think all we'll need is photos for them. We can pull their GitHub profile pictures, but not sure if we want a higher quality or if they want a different photo.

Current avatars are in the Test Pilot repo at https://github.com/mozilla/testpilot/blob/master/frontend/src/images/experiments/activity-stream/avatar/0a68a9039e9ddfcc53515773bf307c79.jpg

![](https://github.com/mozilla/testpilot/blob/master/frontend/src/images/experiments/activity-stream/avatar/0a68a9039e9ddfcc53515773bf307c79.jpg?raw=true)
And seems to be 64px &times; 64px.

---

![piatra](https://avatars2.githubusercontent.com/u/810040?v=3&s=64)
![rittme](https://avatars3.githubusercontent.com/u/201125?v=3&s=64)

**Comment by pdehaan** [comment]
And before I close my tab, I should mention that the YAML config file for Activity Stream is at https://github.com/mozilla/testpilot/blob/master/content-src/experiments/activity-stream.yaml

I can do the Test Pilot PR, I just wanted to give @piatra and @rittme a chance to post a different photo if they don't want to be forever immortalized by their GitHub avatars.

**Comment by pdehaan** [comment]
Fixed in pending [mozilla/testpilot#1497](https://github.com/mozilla/testpilot/pull/1497/files#diff-e7230c13af64694b4b1ab20dee54d7c0R73) PR (using their GitHub avatars).

**Comment by sarracini** [comment]
Done with PR mentioned above
