### ISSUE TITLE
Shield Study Data Pipeline Engineering

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1440]
The study will generate pings from both the control and AS `about:newtab` pages.  We will need to differentiate these data from the data we collect from our Test Pilot page.  

- determine if new endpoints, tables etc. need to be developed or if we could leverage existing data assets to handle this (and future) Shield experiments

- build out and document and changes to server side AS infrastructure to support 

see https://bugzilla.mozilla.org/show_bug.cgi?id=1301188
see #1235

**Comment by jaredkerim** [comment]
See #1516

**Comment by sarracini** [comment]
Let's track the ping work in #1522, and use this ticket to just update the ```data_dictionary.md``` which will reflect the addition of ```shield_variant``` field in all pings
