### ISSUE TITLE
Shield Study Deployment Issues

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1441]
This bug covers work and administration required to sign and deliver the add-on and ensure the study starts.
- resolve any signing and AMO issues for activating a Shield study
- follow up with Shield team and negotiate start date
- verify the deployment is successful

see #1235

**Comment by sarracini** [comment]
From the meeting we have the following things left to do before deploying:

- [ ] Generate an xpi of the shield_study addon and submit it to AMO for review and approval
- [ ] Write a static page which will describe our addon, and has the download link to the addon (provided by AMO)
- [ ] Update shield pings to have another field which has the version of the AS addon that was snapshotted at the time of releasing the study

**Comment by tspurway** [comment]
The static page landed: https://github.com/mozilla/addons-server/pull/3950#event-851257135

**Comment by sarracini** [comment]
Closing this as we've deployed SHIELD
