### ISSUE TITLE
Editable history chunks?

### ISSUE THREAD

**Issue by flurick** [mozilla/activity-stream#1449]
I don't know if this is out of scope but this is what I thought activity-stream
would be, is it or will it? Splitting up the history per "research task" and moving items between them as questions raises questions. 

"...enabling individuals to develop and read a large self-contained research library, create and follow associative trails of links and personal annotations, and recall these trails at any time to share them with other researchers."
https://en.wikipedia.org/wiki/Memex

**Comment by jaredkerim** [comment]
@flurick Thanks for the feedback!  We have definitely thought about this kind of history clustering, and it's being scoped out in our design process, so look out for this kind of feature in future releases!
