### ISSUE TITLE
Issues with awesomebar autocomplete

### ISSUE THREAD

**Issue by marco-c** [mozilla/activity-stream#1458]
When I open a new tab and write the first characters of a history entry, the history entry is highlighted at first, but then quickly unhighlighted (so when I press enter I get redirected to a search instead of the history entry that I wanted).
This only happens if I do it quickly, not if I wait a couple of seconds after opening a new tab (probably because the activity stream page is loaded in the meantime).

I can reproduce this issue with the addon enabled, I can't with the addon disabled.

P.S.: I have noticed a similar issue (when opening URLs that I directly typed) with private windows. I'm hoping it's the same underlying bug, so I'm not going to open a new issue.

**Comment by jaredkerim** [comment]
There was a fix applied some time ago to remove redundant awesomebar URL masking which was causing this issue.
