### ISSUE TITLE
Downloading error

### ISSUE THREAD

**Issue by Liam1011011** [mozilla/activity-stream#1459]
every time i try downloading activity stream and any other test pilot add-on (excluding Min Vid)  i get this error: Uh oh. ⁨Activity Stream⁩ could not be enabled. Try again later. And i have been waiting a few hours in between trying to download the test pilot add-ons. 
![capture](https://cloud.githubusercontent.com/assets/22650556/19138272/30c5cb12-8b40-11e6-98ef-44d574bb5112.PNG)

**Comment by k88hudson** [comment]
@Liam1011011 would you mind telling us what version of Firefox are you currently running?

**Comment by Liam1011011** [comment]
49.0.1

**Comment by Liam1011011** [comment]
49.0.1

**Comment by ncloudioj** [comment]
That's a known issue that some users couldn't install AS from Test Pilot.

@Liam1011011 You can try installing it from [here](https://moz-activity-streams.s3.amazonaws.com/dist/latest.html)
