### ISSUE TITLE
clean up/document metadata used for the site "name"

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#1473]
As of this writing, in different parts of the code, I've found various combinations and relationships of

site.provider_display
site.provider_name
site.parsedUrl.hostname

perhaps based on the (under)-documentation at http://docs.embed.ly/docs/extract

We should figure out what attributes we want to use and document them better in metadata_schema.md (or somewhere).  We should also figure out in what order we want to fallback, in general, a stick a utility function somewhere that does that fallback so that each piece of code doesn't do its own thing.

**Comment by dmose** [comment]
OK, it looks like things are good here.  The only metadata-related use of provider that I still see is (presumably) related to Embedly, and is in MetadataParser._formatData and the accompanying test here.  It may be worth adding a couple of XXX comments that once Embedly is gone, this bit of code and test should disappear.  Up to you...

**Comment by sarracini** [comment]
so actually all the code in MetadaParser is not related to Embedly. The ```provider``` field that comes from ```data``` here actually comes from the metadata service itself, which we then map to a field on the site called ```provider_name``` which is used for the highlights

**Comment by dmose** [comment]
So should the service change too, just to minimize confusion?

**Comment by sarracini** [comment]
Meh, I don't think we care that the page scraper calls it provider. As long as within activity stream it's always referenced as provider_name

**Comment by dmose** [comment]
It's less about generic caring, and more about the use case that if they have the same name if different places, it's easy for new folks to the code to (correctly) intuit that those two things are the same, as opposed to having to go figure out that mapping code exists and read it.

But yeah, it's not a huge deal.

**Comment by sarracini** [comment]
Closing this in favour of tracking it in #1624
