### ISSUE TITLE
Page is blank

### ISSUE THREAD

**Issue by mele113** [mozilla/activity-stream#1484]
With private browsing disabled, activity-stream doesn't remember anything, page is blank with exception of headers
![screen shot 2016-10-07 at 7 08 44 pm](https://cloud.githubusercontent.com/assets/10197742/19207778/aa583190-8cc1-11e6-8fa0-df4426303e39.png)

**Comment by Softvision-VladBacia** [comment]
@mele113, thank you for reporting this. Can you give me a little more info?

- Operating system
- Firefox version
- Any further steps to reproduce
- This is happening right after Activity Stream was installed?

**Comment by jaredkerim** [comment]
We are removing this feature altogether, so this will not be an issue in the future!
