### ISSUE TITLE
The last Highlight tile is displayed under the first one on Activity Stream Timeline page

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#1496]
[Affected versions]:
-Nightly 52.0a1 (Build ID: 20161010030204)
-Activity Stream 1.1.4-dev

[Affected Platforms]:
-All Windows

[Prerequisites]:
-Multiple pages were previously visited in order to have items displayed in all areas of both “Timeline” and “New Tab” pages.
-Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a profile.
- Set `extensions.@activity-streams.weightedHighlights` pref from about:config is set to true.

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on the "Activity Stream Timeline" button from the browser toolbar.
3. Observe the Highlights.

[Expected results]:
-There are displayed 3 Highlights tiles in line.

[Actual results]:
-The 3rd Highlights tile is displayed under the 1st one.

[Notes]:
-Below is a screenshot of the issue:

![timeline highlights](https://cloud.githubusercontent.com/assets/9248513/19271142/e86c801e-8fcb-11e6-82a0-9678bf5ce12f.jpg)

**Comment by dmose** [comment]
This is a regression from #1190.  I'll have a look today.

**Comment by k88hudson** [comment]
Since the Timeline Page is being removed this week, I would recommend wont-fixing this

**Comment by dmose** [comment]
Sounds good to me.

**Comment by ncloudioj** [comment]
@k88hudson The Timeline pages still exists in 1.1.5 though, can we take a quick look at this one to assess how much work it needs?

**Comment by dmose** [comment]
I'll have a look, though it may be Tuesday morning before I can report back.

**Comment by dmose** [comment]
Landed on the release branch, @ncloudioj reviewed post-factor.

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on A-S 1.14.0-dev-1497551877-9d19af4 and I cannot reproduce is. Thus, marking this as Verified-Fixed.
