### ISSUE TITLE
Remove Timeline Component

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1499]
Remove the Timeline page React component and its tests, as well as related smaller components that only exist on the Timeline. Note that some things will be blocked on the Highlights experiment landing .

[edit @k88hudson for clarity]

**Comment by pdehaan** [comment]
I'm a bit confused, if we remove the timeline view, will we still have this button in the toolbar?
![conventional-changelog-cli_and_investigate_webpack_ _issue__1463_ _mozilla_testpilot_and_1__pdehaan_pdehaan____dev_tmp_del_testpilot-webpack_frontend__zsh_](https://cloud.githubusercontent.com/assets/557895/19287014/eaf89208-8fb4-11e6-89ae-239c3f0edeaf.png)
