### ISSUE TITLE
Can't install activity stream when internet security suites are enabled

### ISSUE THREAD

**Issue by wresuolc** [mozilla/activity-stream#1509]
Firefox does some special checks when updating add-ons to make sure the new version is the right one.  One of these is checking the update against a whitelist of certs.  Many internet security suites inject their own root certs so they can MITM SSL traffic which breaks this update check.

Until this gets addressed further up the chain, our best bet is to bypass the cert check by passing a sha hash of the .xpi through a redirect to install.  (The reason this check exists is the idea that you want to host the redirect on a secure site, but the .xpi itself on an insecure CDN).

So, long story short, to fix this:

1) Change your update.rdf to point to a 302 redirect which then points to https://moz-activity-streams.s3.amazonaws.com/dist/activity-streams-latest.xpi
2) Change any install button links which point to https://moz-activity-streams.s3.amazonaws.com/dist/activity-streams-latest.xpi to point to your redirect (if this is only on test pilot, we can do that, but need the new URL)
3) On the 302 redirect add a header `X-Target-Digest: sha256:<hash>`.  The hash should match whatever the .xpi is, so it'll need to change as -latest changes.

Some background:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1308251
* https://github.com/mozilla/testpilot/issues/1474
* https://github.com/mozilla/testpilot/issues/1537

**Comment by ncloudioj** [comment]
I've tried the solution @wresuolc mentioned above. Turns out it's not that easy to set the redirect as we're not hosting those s3 buckets as website, thus, `x-amz-website-redirect-location` and `x-amz-meta-x-target-digest` won't work without further configuration such as header rewrite. Also I've spoken to relud, and both we thought setting up ngnix/cloudfront seemed to be an overkill.
  
I wonder if we can host the A-S add-on directly in Test Pilot, just like most of other experiments do. What do you think? @wresuolc

**Comment by wresuolc** [comment]
That would be fine, the caveat being, we don't have an automated-upload system yet.  When an experiment does a release now, they email me the xpi and I upload it

**Comment by ncloudioj** [comment]
@wresuolc ah, i see. So, basically, all the experiment teams just sign the add-on and send it to you, right? I think we can also take that way. At the very least, T-P has already set up the proper configuration (Nginx, CloudFront, etc.) to mitigate this issue.

For A-S, we use `fab` for both `dev` and `release` to sign the add-on, then upload it to S3. But it needs some extra effort to support the redirect style installation. Also, IMO let us ship A-S directly to the T-P S3 bucket isn't preferred for the security concern.
