### ISSUE TITLE
Persist active experiments in prefs

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1511]
This will include the following steps:

1. Experiment provider starts up and loads experiments.json
2. It looks at each experiment and sees if a pref exists for that experiment. If not, create a pref, and this means we have new experiments
3. If there are experiments that a user is assigned to that are no longer active, unassign them.
4. If there are new experiments and the user is not assigned to an experiment, randomly decide if they should be assigned to an experiment

**Comment by jaredkerim** [comment]
We need to verify that machine generated prefs are not wiped at update time if they're not defined in package.json

**Comment by sarracini** [comment]
Closed with #1560
