### ISSUE TITLE
Add Feedback/modal component

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1513]
This ticket adds a component to display a feedback form. For the initial work, let's just make the component without hooking up any data source.

This could be multiple components (maybe one modal, one specific to Feedback), or not. It should include tests and a storybook.

Trello card for reference: https://trello.com/c/EiQkbFh4/81-i-want-to-be-able-to-send-feedback-about-my-new-tab-experience

![](https://trello-attachments.s3.amazonaws.com/57bde7ce9ec6607538040b82/2840x1394/d48007fb1b919e8ad6af9f8b0f3c2ba2/Trello_Cover_Shot%402x.png)

**Comment by Mardak** [comment]
Dupe of #1811
