### ISSUE TITLE
Add a 'shield_variant' field to pings

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1516]
Split from #1438. We'll use ClientID to track groups within a shield study, e.g., shield1A-<clientId> vs shield1B-<clientId>

**Comment by Mardak** [comment]
It was suggested that we might want to keep clientId opaque and instead add an additional field to the ping to track shield experiment groups.

**Comment by sarracini** [comment]
the shield addon utils guys said there's a way to access which variation you're in using a ```study.variations``` attribute that you get when you set up the study. we can add a 'shield_ variation' field to the pings which we can populate with that attribute and will give us a way to distinguish which group a user was in. 
@Mardak @jaredkerim sounds good?

**Comment by Mardak** [comment]
Does it make sense to put that variation value as the `experimentId`?

**Comment by jaredkerim** [comment]
@Mardak We could potentially reuse the experimentId field but then it might not be clear whether a given ping belongs to someone in one of our activity stream experiments vs a shield study variation.  @ncloudioj We can add a `shield_variant` field to event pings in Onyx/Redshift without too much trouble right?

**Comment by ncloudioj** [comment]
Yes, adding a `shield_variant` field to the ping is better. Let's leave the `experimentID` alone, as it's being used by various ongoing experiments.

**Comment by sarracini** [comment]
Re-opening this since we're going to add shield_variant to the common properties for the ping instead of just for user events
