### ISSUE TITLE
Verify shield pings

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1522]
Split from #1438. We'll be sending custom shield client ids in #1516. We want to make sure these are being received. @sarracini suggests @ncloudioj can probably help once we get the pings updated.

**Comment by ncloudioj** [comment]
Schema changes are required:
* add a new field `shield_variant`, ref #1516

**Comment by ncloudioj** [comment]
We've decided to create a separate set of tables for the shield study so that all the existing analytics queries could work without any change.

**Comment by ncloudioj** [comment]
Landed in both Splice and Infernyx.
