### ISSUE TITLE
Add Feedback data endpoint and implement in addon

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1524]
This could be in our own endpoint or just an email address, whatever is easiest. This ticket should add the endpoint to the Feedback form implemented in #1513.

See project https://github.com/mozilla/activity-stream/projects/8 for Trello details.

**Comment by jaredkerim** [comment]
Closing this in favour of the new work in https://github.com/mozilla/activity-stream/projects/8
