### ISSUE TITLE
Cache dataURIs for various images in the add-on

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1525]
Right now we are passing around images for search, share, and favicons multiple times via data uris. These start to add up, so it would be great if we could cache them somwhere

**Comment by dmose** [comment]
Some code Kate found doing something similar in Firefox: https://reviewboard.mozilla.org/r/67474/diff/1#index_header

Some

**Comment by sarracini** [comment]
After much discussion with jared, nan, mike conley and jeff muizelaar, we can't actually use blobs between processes in a way that will increase performance. Instead we're going to try to reduce the size of localstorage by other means (like not storing places and tippytop and metadata favicons, for starters). Closing this in favour of tracking that work in #1658
