### ISSUE TITLE
Description text is cut off on some highlight cards

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1526]
On some of the highlight cards, the description text is not properly truncated or is overflowing it's container making the text cut off. Examples attached:

![screen shot 2016-10-11 at 12 53 29 pm](https://cloud.githubusercontent.com/assets/139451/19282046/42f77c1a-8fb2-11e6-905c-47198b4bba41.png)
![screen shot 2016-10-11 at 12 57 56 pm](https://cloud.githubusercontent.com/assets/139451/19282077/5d35a160-8fb2-11e6-8060-7de770a0fe9d.png)

**Comment by dmose** [comment]
Some examples of what I've currently got for @bryanbell:

https://monosnap.com/file/s8hDyut63Kg8qSwbp3LDkuGdkPW2Ip#
https://monosnap.com/file/WqbEneJ9lQfXMmx08r4K5mFTNINs90#
https://monosnap.com/file/QPry2REDcXyZ3kirjvgIW8ezFm7yig#

This is with line-height in all of the text area of 18px, padding around all sides of the text area of 10px, and a max-height of the text are of 90px.

**Comment by dmose** [comment]
@bryanbell I think we should spin off "line clamping" a.k.a. multi-line ellipses to another issue.  There are lots of hacky, edge-casey "solutions" to this floating around, all the CSS ones I've seen are unlikely to work in a right-to-left context, which we're likely to need to land in m-c.  There are Javascript ones as well, but I don't want the tradeoffs involved in figuring out what to do to block this bug.

**Comment by Softvision-VladBacia** [comment]
This issue is related to #502 that was reported a long time ago. The issue was initially found on Windows XP but from what I can see it has migrated to other OSs.

**Comment by dmose** [comment]
@Softvision-VladBacia thanks for pointing to that bug!

**Comment by dmose** [comment]
Weighted highlights:

![image](https://cloud.githubusercontent.com/assets/425657/19368710/3c77e564-9156-11e6-8d27-eba05f860f01.png)

Item with all properties:

![image](https://cloud.githubusercontent.com/assets/425657/19368750/61967c84-9156-11e6-9416-7d29f0cd489e.png)

Item with title overflowing text area:

![image](https://cloud.githubusercontent.com/assets/425657/19368757/708dccb0-9156-11e6-820b-8e967359a685.png)

Item with title + desc overflowing text area:

![image](https://cloud.githubusercontent.com/assets/425657/19368801/9ba22f40-9156-11e6-9bb2-97bcab718350.png)

Item missing feed name (like (eg) first 3 default tiles for first run experience):

![image](https://cloud.githubusercontent.com/assets/425657/19368816/b8b2adb2-9156-11e6-95fc-6e71510061aa.png)
