### ISSUE TITLE
Can't enable

### ISSUE THREAD

**Issue by StanTheManMcCan** [mozilla/activity-stream#1539]
Just loads ad infinitum

**Comment by jaredkerim** [comment]
Hi @StanTheManMcCan!  I think this is related to the issue tracked here:

https://github.com/mozilla/activity-stream/issues/1509

which is itself related to a larger issue with test pilot tracked here:

https://github.com/mozilla/testpilot/issues/1474

I'm marking this as a duplicate.  If there's any additional information you can provide or believe it's not related to those issues, please reopen with additional information!  

One thing that would be helpful is if you experience this and open the 'Browser Console' by going to Tools -> Web Developer -> Browser Console and copy and paste what's in there into the ticket in case there are meaningful errors that could help us debug it.  Thanks!
