### ISSUE TITLE
Error: UNIQUE constraint failed by page_metadata.cache_key

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1543]
With PageScraper enabled, this entered my browser console:

MetadataStore failed to insert metadata: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key  MetadataStore.js:284
	MetadataStore.prototype.asyncInsert</< resource://activity-streams/addon/MetadataStore.js:284:11
	throw self-hosted
	TaskImpl_run resource://gre/modules/Task.jsm:323:42
	bound TaskImpl_run self-hosted
Error: Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key
Stack trace:
ConnectionData.prototype<._executeStatement/pending<.handleCompletion@resource://gre/modules/Sqlite.jsm:807:25
  Sqlite.jsm:648
Error(s) encountered during statement execution: UNIQUE constraint failed: page_metadata.cache_key  Sqlite.jsm:807
	ConnectionData.prototype<._executeStatement/pending<.handleCompletion resource://gre/modules/Sqlite.jsm:807:25

**Comment by Mardak** [comment]
Might be the same as #1451?

**Comment by jaredkerim** [comment]
Marking as a duplicate of #1451
