### ISSUE TITLE
Make sure Test Pilot site is still accurate

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1544]
We should do this before we deploy the next XPI since the screenshots and descriptions may be out of date with all the ✂️ we've been doing lately.

https://testpilot.firefox.com/experiments/activity-stream/

/cc @johngruen

**Comment by pdehaan** [comment]
We'll also want to make sure we bump the version on https://testpilot.dev.mozaws.net/experiments/activity-stream via [**mozilla/testpilot** /content-src/experiments/activity-stream.yaml:14](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/activity-stream.yaml#L14).

**Comment by sarracini** [comment]
the test pilot version will soon die, so there's no point doing this anymore
