### ISSUE TITLE
The Top Sites context menu button is misalligned

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1547]
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.4-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and open a new tab. 
2. Hover any of the Top Sites tiles and observe the Context Menu button position.

[Expected result]:
- The Context Menu button appears in the upper right corner of the tile.

[Actual result]:
- The Context Menu button appears over its normal position.

[Additional Notes]:
- The issue is not reproducible for Highlights tiles.
- Attached a screenshot of the issue.
![top sites context menu is misalligned](https://cloud.githubusercontent.com/assets/18304511/19344035/50476f2a-9141-11e6-9411-89f467dcdd3e.png)

**Comment by rlr** [comment]
I'm not seeing this issue at all on the 1.5 pre-release build.

With an existing profile:
<img width="734" alt="screen shot 2016-10-18 at 4 45 51 pm" src="https://cloud.githubusercontent.com/assets/36629/19495801/ea4f64be-9552-11e6-8cb0-fcf3d788e774.png">

With a brand new profile:
<img width="739" alt="screen shot 2016-10-18 at 4 47 46 pm" src="https://cloud.githubusercontent.com/assets/36629/19495807/f0aa22ae-9552-11e6-9680-007ac16d7ba8.png">

And running the master branch on nightly is good too:
<img width="732" alt="screen shot 2016-10-18 at 4 48 49 pm" src="https://cloud.githubusercontent.com/assets/36629/19495828/fbc90f1a-9552-11e6-91f5-0bc68958f8ba.png">

Closing for now. Please re-open if you are still seeing the issue.

In the screenshot it appears that something was actually pushing the Top Sites tiles down and the context menu button is where it's supposed to be. But I'm not sure what may have caused that and I can't repro.

**Comment by SoftVision-CiprianMuresan** [comment]
I can still reproduce this on the latest Nightly (Build ID 20161018030211) regardless of where I install AS from, so something changed in the browser which caused this "regression". Aurora and Beta are not affected (yet).

I did a regression range and got the following [pushlog](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=bb8fca801fc8a71e975ce5afce317e0694827475&tochange=570c8ad43113da52517b48d68982deb96f072c7f). 
Looks like the following bug has the changes which introduced the regression:
[Bug 1306894](https://bugzilla.mozilla.org/show_bug.cgi?id=1306894)

**Comment by rlr** [comment]
@SoftVision-CiprianMuresan ah, I didn't have the latest nightly. Now I can repro. Thanks!

**Comment by rlr** [comment]
^ fixed. @ncloudioj will cherry pick onto the release

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest version (1.1.5).
