### ISSUE TITLE
Limit highlights to one item per domain (weighted highlights)

### ISSUE THREAD

**Issue by hmcgaw** [mozilla/activity-stream#1553]
I get duplicate highlights often on the new highlights view. 

Using version Activity Stream Dev 1.1.4-dev-1476371709

<img width="665" alt="screen shot 2016-10-13 at 2 03 10 pm" src="https://cloud.githubusercontent.com/assets/21317131/19360804/0b60bd00-914e-11e6-9601-c3bf6029b304.png">

**Comment by jaredkerim** [comment]
Let's investigate ways to improve this before we send out the SHIELD study.  Perhaps we can simply modify some weights to reduce the number of duplicates.

**Comment by k88hudson** [comment]
As per our discussions in the for the shield MVP, let's **only show one item per domain**. We can do this at the query level.

In the future, we can work on something more nuanced.

**Comment by piatra** [comment]
@k88hudson I disagree with doing this at query level. It bypasses scoring and could hide useful results.

**Comment by k88hudson** [comment]
OK, @piatra is gonna give this a shot with tweaking the scoring

**Comment by piatra** [comment]
Some thoughts here.
* I've [made a pull request](https://github.com/mozilla/activity-stream/compare/master...piatra:similar-items) to lower the score of similar items
* We could also consider increasing the [LINKS_QUERY_LIMIT](https://github.com/mozilla/activity-stream/blob/8830040528ca0bf83980cd301e33ff535eea65e7/addon/PlacesProvider.js#L768)
* or (maybe even better) replace [that same check](https://github.com/mozilla/activity-stream/blob/8830040528ca0bf83980cd301e33ff535eea65e7/addon/PlacesProvider.js#L768) with one that counts the number of unique domains we are about to return and if it falls under __X__ get more (presumably older) links.

**Comment by sarracini** [comment]
Notes: 
The logic here https://github.com/mozilla/activity-stream/blob/master/common/recommender/Baseline.js#L42 seems to be a bit broken - the ```idf``` is always returning the same number for a domain which has multiple occurrences and a domain which has just a single occurrence. Not sure if that directly influences the score to a degree that matters, but it's worth noting that since ```this.domainCounts``` only gets computed once (on creation time here https://github.com/mozilla/activity-stream/blob/master/common/recommender/Baseline.js#L16), that the number will always remain the same

**Comment by sarracini** [comment]
Also, I've tested out the patch which lowers the score from 0.8 to 0.3 for duped items and that doesn't work when you have a small history and only a small number of tiles to choose from - they're still going to show up. So if we want to actually dedupe, or limit to one item per domain, we have to just remove duplicate items altogether, not necessarily just lower their score

**Comment by sarracini** [comment]
Here's the difference with the same set of websites with just lowering score (first) vs deduping method in pr #1653 (second)
<img width="1440" alt="screen shot 2016-10-28 at 9 54 57 am" src="https://cloud.githubusercontent.com/assets/7219526/19809028/629017c6-9cf5-11e6-90de-9e9c47857f2e.png">
<img width="1440" alt="screen shot 2016-10-28 at 9 57 28 am" src="https://cloud.githubusercontent.com/assets/7219526/19809036/67ff7468-9cf5-11e6-912c-e25e26695b08.png">

**Comment by sarracini** [comment]
we could also consider doing something smarter like, if we have less than 9 highlights if we remove dupes then it's ok to show the dupes?
