### ISSUE TITLE
Instrument tiles page for session and search/click-related events

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1570]
From learnings from #1514, #1519, and #1520; we'll want to use both new tab page mod and directory links module monkey patching to get the desired user events. We'll use the existing tab tracking page mod to send session pings.

**Comment by sarracini** [comment]
@Mardak do we want to close this and track it in the work from #1579?

**Comment by Mardak** [comment]
Are you wanting to close this as this is fixed on a shield branch? Maybe we should just make an official activity-stream repository shield branch and get the current PR reviewed and merged onto that branch?

**Comment by sarracini** [comment]
Yeah - I'll make an official branch for the shield commit to live once we sort out the last bit of the shield parameters from #1523 but I think we can closed this as fixed since it'll all be part of one commit which is in #1579 now
What do you think?

**Comment by Mardak** [comment]
Usually issues are closed when the associated PR is reviewed and merged, but github won't autoclose this anyway as the merge isn't to master. So that's fine. Closed!
