### ISSUE TITLE
Recent Activity section is displayed under the default Highlights

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1576]
[Affected versions]:
- Nightly 45 and up
- Activity Stream 1.1.4-dev

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.4-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Open a new tab and observe the bottom part of the New Tab page.

[Expected results]:
- Default Highlights tiles are displayed.

[Actual results]:
- Recent Activity section is displayed on the New Tab.

[Notes]:
- I can reproduce this issue on all Firefox channels.
- I installed AS from [here](https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html) and also from a custom build.
- Attached a screenshot & screen recording of the issue of the issue https://goo.gl/NKpgbW.
![recent activity is still being shown](https://cloud.githubusercontent.com/assets/18304511/19474028/8bed947a-9536-11e6-92ed-1224e229df2b.png)

**Comment by jaredkerim** [comment]
This is an expected behaviour.  Recent activity will be deprecated when Weighted Highlights is landed.
