### ISSUE TITLE
Decide on "filter" list for some components

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#159]
Some URLs should never be shown on the new tab page (e.g. searches, images). Let's add filtering for things we know won't look good/won't be very useful.

This should not be done for `Recent`, only `FrecentLinks` and `TopSites`.

**Comment by oyiptong** [comment]
How about we make a list of those and track them here rather than implementing the filter immediately?

**Comment by pdehaan** [comment]
Ref: #187

**Comment by jaredkerim** [comment]
We currently filter history and highlights based on various properties about each page, if this requires more decisioning it can be revisited, however there is a currently deployed strategy around content filtering and any additional modifications can be opened as new tickets.
