### ISSUE TITLE
The New Tab search bar does not receive focus after dragging a link in it

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#1604]
[Affected versions]:
- Nightly 52.0a1, Build ID  20161020030211
- Activity Stream 1.1.6-dev

[Affected Platforms]:
- Windows 10 x64
- Mac OS 10.11

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Open a new tab and drag one of the Top Sites or Highlights tiles in the Search bar.
3. Observe the Search bar.

[Expected results]:
- The Search bar is focused.

[Actual results]:
- The Search bar is not focused.

[Notes]:
- After dragging one of the Top Sites or Highlights tiles in the browser toolbar search bar, the latter is focused.  
  ![search bar is unfocused](https://cloud.githubusercontent.com/assets/18304511/19592124/048c9ba8-9783-11e6-8b9d-ea2a39016b8a.gif)

**Comment by sarracini** [comment]
No longer doing work on test pilot version of the addon. closing this
