### ISSUE TITLE
Differentiate about:home vs about:newtab in pings

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#1606]
**Here's the deal:** 
Activity Stream sets about:home to be Activity Stream, but we don't have any way of knowing which interactions came from about:home and which ones came from about:newtab. That being said, in the SHIELD study we need to deal with that. We want to get the SHIELD study out as soon as possible so let's do the minimum amount of work while still pleasing everyone. Here are the options:

**Option a)** Do engineering work in Activity Stream to differentiate between clicks from about:home and about:newtab. Throw away about:home clicks for SHIELD study users in the Activity Stream variant. No data on about:home clicks 

**Option b)** Do engineering work in Activity Stream to differentiate between clicks from about:home and about:newtab. Monkey patch about:home for Tiles variant to collect the search clicks on about:home and compare ONLY search data from about:home in Tiles vs search data from about:home in Activity Stream

**Option c)** Turn off setting about:home to Activity Stream for SHIELD users in that variant. No data collected on about:home in either Tiles or Activity Stream

**Option d)** Ship it as is and get the first SHIELD study out as is and we'll get a proper fix in for the next SHIELD study

**Option e)** Set about:home to about:newtab for SHIELD study users in the Tiles variant. We don't need to differentiate between pages and we just group the data together as just 'Tiles' vs 'Activity Stream'

Let's decide which one of these we want to do.
cc @Mardak @emtwo @tspurway @nchapman @ncloudioj @jaredkerim @k88hudson @dmose

**Comment by nchapman** [comment]
> Option c) Turn off setting about:home to Activity Stream for SHIELD users in that variant. No data collected on about:home in either Tiles or Activity Stream

Let's do this for the Shield study.

> Option a) Do engineering work in Activity Stream to differentiate between clicks from about:home and about:newtab. Throw away about:home clicks for SHIELD study users in the Activity Stream variant. No data on about:home clicks

Let's do this for the future, but not block the Shield study on it.

**Comment by sarracini** [comment]
Sounds good Nick, thanks! I'll put this ticket in the next iteration and we'll do option a) then

**Comment by Mardak** [comment]
@emtwo how should the pings be differentiated? Is this good enough where `url` in the session ping includes "home" and event ping is unchanged. I suppose we could restore the `resolvePageType` logic to use the default "NEW_TAB" or a new "HOME" (where the code was removed in 8952233d1480a4500e3d658226fb84c2cdc93740 for #1502).
```
console.log: activity-streams: TELEMETRY PING: {
    "action": "activity_stream_event",
    "action_position": 2,
    "addon_version": "1.1.6",
    "client_id": "d6e77289-4d2b-5745-acfa-43c6d472d8cd",
    "event": "CLICK",
    "locale": "en-US",
    "metadata_source": "TippyTopProvider",
    "page": "NEW_TAB",
    "session_id": "{ca565285-0b7a-9849-ae6f-b43f9956c3eb}",
    "source": "TOP_SITES",
    "tab_id": "-27-2"
}
console.log: activity-streams: TELEMETRY PING: {
    "action": "activity_stream_session",
    "addon_version": "1.1.6",
    "client_id": "d6e77289-4d2b-5745-acfa-43c6d472d8cd",
    "load_latency": 803,
    "load_reason": "newtab",
    "locale": "en-US",
    "page": "NEW_TAB",
    "session_duration": 3713,
    "session_id": "{ca565285-0b7a-9849-ae6f-b43f9956c3eb}",
    "tab_id": "-27-2",
    "total_bookmarks": 21,
    "total_history_size": 100055,
    "unload_reason": "click",
    "url": "resource://activity-streams/data/content/activity-streams.html#/home"
}
```

**Comment by ncloudioj** [comment]
@Mardak I think restoring the `page` field is preferred than using the `url` filed in the session ping.

What do you think? @emtwo
