### ISSUE TITLE
Explicitly unpack metadata fields on to site object

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1609]
Rather than flattening the metadata object on to the site object in its entirety, let's explicitly transfer each field by name.  For example:

https://github.com/mozilla/activity-stream/blob/master/addon/PreviewProvider.js#L220

const cachedMetadata = existingLinks.get(site.cache_key);
enhancedSite.title = cachedMetadata.title;
enhancedSite.description = cachedMetadata.description;

etc

This accomplishes two things

1) It forces us to be explicit about which metadata fields we're using, and where they're being populated
2) If we want to add new fields or remove them it becomes more explicit
3) We can do additional post processing or validation here as well

**Comment by dmose** [comment]
If there is a point at which the metadata on the object should no longer be updated, we may want to consider using Object.freeze there to prevent other code from stomping on the fields.
