### ISSUE TITLE
The "active" property in experiments has an unclear meaning

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1610]
Right now it's unclear what we are using the `"active"` field on experiments for -- this came in a with a discussion with @emtwo. In practice we use it for "archiving" old experiments that may not even be referenced in the code, whereas for experiments that are not yet running, we tend to just set the `"threshold"` value to `0`.

We should clarify this distinction.

**Comment by sarracini** [comment]
We're redoing the experiment json definition anyways, so i'll close this
