### ISSUE TITLE
Graduate Weighted Highlights?

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#1611]
Once we have enough data, lets change weighted highlights from an experiment to a stable feature. We would need to do this in order to ship it for shield.

**Comment by jaredkerim** [comment]
This depends on #1617

**Comment by dmose** [comment]
If we make this a completely unflagged feature, and we discover a severe problem during post-Shield rollout, it'll be notably more work to temporarily roll this feature back.

It seems like it might be wiser to simply turn this into a flagged feature defaulted to "on" for a while.

Thoughts?

**Comment by dmose** [comment]
#1666 has fixed the basic thing, so it no longer needs to be in La Mauricie, and I've moved it to Mount Revelstoke.

**Comment by dmose** [comment]
What remains to be done is to go tear out all the old code paths for unweighted highlights, including the various XXX comments I left pointing to #1611.

**Comment by Mardak** [comment]
Taking the remaining cleanup of this issue at the same time as #1518.
