### ISSUE TITLE
Weighted highlights analysis

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1617]
engagement of weighted highlights participants vs. control group

**Comment by dmose** [comment]
Last week in the product meeting, it was decided that the current data was enough to warrant switching to weighted highlights, which I suspect means this can be closed.  @emtwo ?

**Comment by emtwo** [comment]
Yes, here's the link to the analysis, so I'll close this.
https://sql.telemetry.mozilla.org/dashboard/activity-stream-a-b-testing-weighted-highlights
