### ISSUE TITLE
Local metadata analysis

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1618]
Ensure no drop in engagement and a decrease in cache misses for experiment vs. control group

**Comment by jaredkerim** [comment]
The success criteria are as follows:

1) We reduce the number of cache misses
2) We do not worsen performance
3) We do not worsen stability
4) We do not worsen engagement
5) We do not worsen retention

**Comment by emtwo** [comment]
We've been running this experiment for ~1 month and the results can be found on re:dash here:
https://sql.telemetry.mozilla.org/dashboard/activity-stream-a-b-testing-local-metadata

And on a plotly dashboard here:
https://dashboards.ly/ua-uLSxixt6QAchZy2dTGy7DY

These results show no significant difference between both experiment and control groups except for 1:
There are significantly more deletes in the control group than the experiment group.

We speculate that this may be due to the higher quality metadata associated with the experiment and it's likely a positive indicator.
