### ISSUE TITLE
Add ability to bookmark/unbookmark from star

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#162]
It would be nice to be able to bookmark/unbookmark things from the `ActivityFeed`:

<img width="756" alt="screen shot 2016-02-22 at 11 17 52 am" src="https://cloud.githubusercontent.com/assets/1455535/13224214/7ae96e6c-d955-11e5-96eb-9baa848115c8.png">

**Comment by sarracini** [comment]
Closing this since we've removed Timeline and all bookmarking stuff
