### ISSUE TITLE
Consolidate weightedHighlights prefs

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1623]
There are now two prefs for weighted highlights:

extensions.@activity-streams.experiments.weightedHighlights;false

and

extensions.@activity-streams.weightedHighlights;true

The first one is introduced by the new experiment pref changes.  We need to consolidate this into a single pref, ideally the experiment pref.  So let's change all references to the second one to the first one and update our package.json.

**Comment by dmose** [comment]
So developers who want to work on the forward-looking code path should force their dev profiles into the experiment?  Or is the intent to have that done in github for everyone who checks out master?

**Comment by jaredkerim** [comment]
@dmose I don't understand what you mean.  What this is talking about is that recently @emtwo landed a change which dynamically creates a pref for each experiment.  Previously there was no individual, automatically generated pref which stored the state of each individual experiment, and so some experiment implementers would create a pref which made it easier to modify the state of experiments.  Now that the new patch is in, there is both the automatically generated pref as well as the one created by the experiment developer, which is confusing and not clear what the expected behaviour is, so we need to modify references to the manually created one to refer to the automatically created one, and in the future all experiments should refer to the automatically created pref.

This does not change how experiments behave with regards to how users are assigned to experiments.  But it allows devs to more easily interact with and test and debug experiments.

**Comment by dmose** [comment]
I was mostly concerned that developers would end up polluting the collected-data pool while they were working (eg using "npm run firefox").  But if that doesn't happen, or the numbers there are certain to be statistically uninteresting, then it doesn't matter.

**Comment by jaredkerim** [comment]
@dmose if a developer messes with the experiment prefs then they are automatically excluded from all experiments metrics.

**Comment by dmose** [comment]
Got it; thanks!

**Comment by dmose** [comment]
Although, actually, wouldn't that mean that developers who don't mess with those prefs will be reporting telemetry?  And presumably those usage patterns would be polluting the overall dataset, though perhaps not in a way that's significant enough to matter...

**Comment by k88hudson** [comment]
The `weightedHighights` pref was removed from package.json in a previous patch, and the last reference (in dev-prefs) was removed in https://github.com/mozilla/activity-stream/commit/6ac6f57b32d9660b2e04455f023c71661eb8e47f. Is there anywhere else where it hasn't been removed?

**Comment by dmose** [comment]
https://github.com/mozilla/activity-stream/blob/1940dea1807708b3194b79684bb7c63de428eb18/addon/ActivityStreams.js#L573 is one usage of the old pref; there may be more.

**Comment by k88hudson** [comment]
@dmose Ah, that looks like a bug, since that pref no longer exists

My patch does remove that line, so we could just wait for it to land

**Comment by k88hudson** [comment]
If there are any references to `prefs.weightedHighlights`, those should have been changed

**Comment by dmose** [comment]
#1666 closed this.
