### ISSUE TITLE
No tiles other than the 3 default tiles show up in the highlights

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1627]
This happened after I updated the add-on(dev) today on my box. After surfing around a bit, it still only gave me those 3 default tiles. This is my regular Ffx profile, and there were 9 tiles in there before the update. No error/warning messages in the console.

My add-on is currently running two experiments("weightedHighlights" and "metadataService").

<img width="734" alt="screen shot 2016-10-25 at 10 59 51 am" src="https://cloud.githubusercontent.com/assets/1455254/19691903/f4fa789e-9aa3-11e6-89d2-cdcfb84fcd0d.png">

<img width="1069" alt="screen shot 2016-10-25 at 10 59 22 am" src="https://cloud.githubusercontent.com/assets/1455254/19691911/fbd0e2f2-9aa3-11e6-9b99-78b7adf2d229.png">

**Comment by ncloudioj** [comment]
Update: running with the patch for #1577 , this issue remains. As the `weightedHighlight` experiment is about to graduate as the de facto feature. We can de-prioritize this issue for now.

**Comment by k88hudson** [comment]
@ncloudioj are you still seeing this?

**Comment by ncloudioj** [comment]
@k88hudson Couldn't reproduce this issue in the dev build. Let's close this issue as the "weightedHighlight" has already graduated.
