### ISSUE TITLE
Use of nsIFile in content process is deprecated

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1628]
I think I'm also seeing #1627 and I noticed that if I open the Browser Console, I see the following debug log:

> "Use of nsIFile in content process is deprecated"

There is no mention of _where_ we're using that exactly, but a GitHub search shows 3 possible results:
https://github.com/mozilla/activity-stream/search?utf8=%E2%9C%93&q=nsifile

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/19697550/a3f16082-9aa0-11e6-931f-b73fa7375b12.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19697567/b169923e-9aa0-11e6-9a04-577f0381f29b.png)

![browser_console_and_new_tab_and_slack_-_dog_chat](https://cloud.githubusercontent.com/assets/557895/19697542/9adb0d2c-9aa0-11e6-85b7-f8a4079c14b8.png)

![about_config](https://cloud.githubusercontent.com/assets/557895/19697588/cb7ecb6c-9aa0-11e6-932e-d5e402569b95.png)

**Comment by tspurway** [comment]
wontfix - it's an SDK thang
