### ISSUE TITLE
Regression: Showing default bookmarks

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1634]
During a first run of activity stream, we should show the 3 default tiles like so:

![screenshot 2016-10-25 17 02 59](https://cloud.githubusercontent.com/assets/119884/19704225/ea769d04-9ad4-11e6-86c5-7022ca1c3d54.png)

But right now what we're getting is this:

![screenshot 2016-10-24 17 22 00](https://cloud.githubusercontent.com/assets/119884/19704235/f13ef9a6-9ad4-11e6-8d6c-fa0fa7d23012.png)

I believe that the default bookmarked highlights are being processed by preview provider rather than using the built in metadata which is why they're behaving this way.

**Comment by k88hudson** [comment]
I'm pretty sure this only happens for the old highlights, not the new ones

**Comment by sarracini** [comment]
If that's the case, this is a won't fix?

**Comment by sarracini** [comment]
Kate's right, I can only reproduce this without weighted highlights....i wonder why.....

**Comment by jaredkerim** [comment]
Closing this as old highlights will be deprecated shortly.
