### ISSUE TITLE
Bookmarks should show on the New Tab immediately 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#1638]
Bookmarks should be shown immediately on New Tab. Currently they’re kept off for 45(ish) minutes, which ruins hope that the user might begin to learn that bookmarks are a good way to get things on your New Tab.

**Comment by Mardak** [comment]
There's a visited check threshold of 30 minutes:

https://github.com/mozilla/activity-stream/search?utf8=%E2%9C%93&q=HIGHLIGHTS_THRESHOLDS

**Comment by Mardak** [comment]
![screen shot 2016-10-28 at 2 46 54 am](https://cloud.githubusercontent.com/assets/438537/19802515/f13b25e8-9cb8-11e6-9d73-a4e5acb88be9.png)

It doesn't look like there's a 45 minute threshold. The bookmark threshold does only look for those that were created within the last 3 days.

There could be some caching issues that require the page to be refreshed/loaded a second time to show the newly added bookmark.

**Comment by Mardak** [comment]
With the proposed fix for #1493, updates will happen every 15 minutes instead of after each new tab load, so potentially a bookmark will show right away if the timer is just right or some minutes later. Filed followup #1670.
