### ISSUE TITLE
Audit Test Pilot contributors

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1645]
Re: https://testpilot.firefox.com/experiments/activity-stream,

We currently have 13 contributors listed, but are probably missing a few (notably @Mardak and @dmose and @aaronrbenson, possibly others -- per https://github.com/mozilla/activity-stream/graphs/contributors).

The config file in question is at [**mozilla/testpilot** content-src/experiments/activity-stream.yaml](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/activity-stream.yaml) if anybody wants to add anybody to the list.

**Comment by emtwo** [comment]
looks like we need to add @pdehaan there too ;)

**Comment by pdehaan** [comment]
> looks like we need to add @pdehaan there too ;)

No. I opted out.
