### ISSUE TITLE
Feature request: Top Tiles should each point to a unique domain.

### ISSUE THREAD

**Issue by mhoye** [mozilla/activity-stream#1650]
Right now it looks like Top Tiles points to the most frequently visited URLs, but there is often (in my experience) a lot of site redundancy. e.g. Twitter, twitter notifications, mobile.twitter brought over frm sync, most of which I can get to via the first link. 

I'd like to propose that each of the top-tiles point to different domains, by default, to provide the widest "utility coverage" possible, and emphasize breadth of utility rather than pure frequency.

**Comment by jaredkerim** [comment]
@mhoye This will be handled by our efforts to improve top sites overall, which includes reducing duplicates.  Thanks for reporting this!

**Comment by jaredkerim** [comment]
Oops forgot to link: https://github.com/mozilla/activity-stream/projects/6
