### ISSUE TITLE
Consolidate favicon metadata fields

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1658]
Presently we refer to `.favicons` and `.favicon_url` when we access favicon data from site objects.  We should consolidate this to a single field, ie `.favicon_url`

**Comment by sarracini** [comment]
also, the favicon colours that go with it. there's 
```favicons.color```, ```favicon_color```, ```favicon_colors``` and ```background_color```

**Comment by sarracini** [comment]
By storing only the favicon that we intend on using we will also reduce the size of localstorage and improve performance (ever so slightly but still counts)

**Comment by sarracini** [comment]
Closed with #1821
