### ISSUE TITLE
Audit webpack bundles

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1692]
Recently found [**webpack-bundle-analyzer**](https://github.com/th0r/webpack-bundle-analyzer) and it's a bit interesting.

I opted for the following:

1. `npm install webpack-bundle-analyzer -D`
1. `NODE_ENV=production ./node_modules/.bin/webpack --profile --json > stats.json` (then edit the file to remove the 5-6 non-JSON lines at the top)
1. `NODE_ENV=production ./node_modules/.bin/webpack-bundle-analyzer stats.json`

If all went well, you should see a big grid like this at localhost:8888:

![webpack_bundle_visualizer](https://cloud.githubusercontent.com/assets/557895/19907571/b330afb6-a03c-11e6-8765-9e36c7265d3d.png)

From the looks of it, **faker** takes up a huge portion of the _bundle.js_ (1.02 of 1.53MB -- 67%), and **moment** takes up a large portion of the _vendor.bundle.js_ (467KB of 1.1MB -- 43%).

---

top_sites.json takes up a smaller portion of the bundle.js than I expected, but I guess it isn't including all the images in tippy-top-sites in the bundle (which, according to `du -sh ./node_modules/tippy-top-sites/images` is about 716KB of logo-goodness).
I'm not sure if `du -sh` is an accurate representation of file sizes, but if I run the same `du -sh images` command in the tippy-top-sites repo, I get about 912KB, so I'm guessing we'll be adding ~200KB of logos after we migrate to the latest version of tippy-top).

**Comment by pdehaan** [comment]
Now that @k88hudson landed #1814, here's the current graph:

![webpack_bundle_analyzer](https://cloud.githubusercontent.com/assets/557895/20545833/3c097cc0-b0c6-11e6-9c34-8ea971034999.png)

**Comment by pdehaan** [comment]
@k88hudson: Can we close this too? Or is there anything else we need to do?

**Comment by k88hudson** [comment]
All done!
