### ISSUE TITLE
Change add-on updateURL and updateLink for shield study

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1707]
Once AMO assigns a link to this shield study, we need to change the `updateURL` and `updateLink` in the `package.json` before building the Shield Study A-S.

I came across this issue while playing with the shield study version of A-S, which automatically updated itself to the latest version on Test Pilot.

**Comment by tspurway** [comment]
this is what we are putting in the AMO template for the xpi URL:

https://addons.mozilla.org/firefox/downloads/latest/activity-stream-shield-study/?src=shield-study-7

**Comment by sarracini** [comment]
this has been updated on latest shield_study branch
