### ISSUE TITLE
unload_reason not being set on session end pings

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1710]
Using the latest activity stream on master, at commit: https://github.com/mozilla/activity-stream/commit/f6ecc5e1b9683806f6b5a48ffc7828ee383e3fc8

If I dump all telemetry pings to the console, I can see session end pings being fired, but they do not seem to include 'unload_reason'.  I believe this is a bug.

**Comment by sarracini** [comment]
Closing this as it's been fixed now 🎉
