### ISSUE TITLE
Missing search pings in Shield Study Tiles variant

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1712]
We've noticed that the add-on only sends the first "search" ping in the shield study tiles variant. @sarracini has found that it had to do with the prefs option`browser.newtab.preload`, and she is making a bugfix for this.

**Comment by Mardak** [comment]
If it is a `preload` issue, a simple fix is to set `preload` pref to `false`.

**Comment by sarracini** [comment]
@Mardak yup! I can close this now, I updated the shield_study branch's commit to do that - and also reset the pref to the user's default when the shield study shuts itself down
