### ISSUE TITLE
Performance ping: embedlyProxyRequestReceivedCount not sending value correctly

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1713]
The performance ping for:

embedlyProxyRequestReceivedCount

found here:

https://github.com/mozilla/activity-stream/blob/df98f1de7731a55547edc6d147c1d1a2f3f65e62/addon/PreviewProvider.js#L332

is not being sent correctly because it assumes urls is an array, which it's not it's an object so we need to do Object.keys(responseJson.urls).length instead

**Comment by Mardak** [comment]
Requested by @jaredkerim to block #1654
