### ISSUE TITLE
Do not refresh highlights feed on every places change (first run, empty profile)

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1714]
Presently, we refresh the highlights feed on every places change.  

https://github.com/mozilla/activity-stream/blob/master/addon/Feeds/HighlightsFeed.js#L76-L85

However this causes an unnecessary amount of work to be performed by the users browser, ie multiple database queries for urls, metadata, triggering network requests for metadata for every single url that the user browses to.  We do not want to perform this much work in the users browser as this will reduce the overall performance of the browser.  We should find a more periodic way to regenerate the highlights for a user that does not consume so many resources.

**Comment by k88hudson** [comment]
Keep in mind this only happens for users who have an empty profile and have just started to use the browser, so we should consider what to do for that use case specifically.

**Comment by jaredkerim** [comment]
First step is to track background processes here #1732 and then we can attempt to reduce the number of background processing events.
