### ISSUE TITLE
Validate telemetry pings before sending

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1715]
Presently it is possible to use TelemetrySender to attempt to send a ping to Onyx which will fail validation on the Onyx side and thus never be processed or make its way into Redshift.  There have been a significant number of cases where we launch code changes with new telemetry pings and only find out after the fact that they have not made it into Redshift because they failed Onyx validation.  We should extend telemetry sender to include this kind of validation on the client side so that it becomes immediately obvious that a ping has been misconfigured.

**Comment by ncloudioj** [comment]
Good idea!

I'd recommend to do this validation offline, for example, in the unit test. So the most frequent issue we've seen so far is that missing required field in the payload. We can improve this at least by:

* reference the `data_dictionary.md` when you're changing anything in the telemetry. It has all the specs for each field of the payload. Also, when you add new fields to the payload, don't forget to update the doc there
* add unit test for your change, particularly, checking the required fields, invalidating the value etc. based on the `data_dictionary.md`

**Comment by sarracini** [comment]
Closing this and we'll file it on ping center
