### ISSUE TITLE
Would like to be able to view and modify which experiments I'm enrolled in

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1721]
It would be nice to have a setting in the debug view to see and modify which experiments I'm enrolled in. This would be especially helpful when testing on fresh profiles.

**Comment by ncloudioj** [comment]
Yes, that would be pretty handy. For the time being, you can do this through the `about:config` page, just search for `activity`, then you should be able to see your experiment setup like this.

<img width="1008" alt="screen shot 2016-11-03 at 2 41 33 pm" src="https://cloud.githubusercontent.com/assets/1455254/19980281/ce1b950a-a1d3-11e6-9724-1fe11d5892f3.png">
