### ISSUE TITLE
Activity Stream disabled but no option to enable it.

### ISSUE THREAD

**Issue by markrcote** [mozilla/activity-stream#1749]
When I click on the Test Pilot button, it shows no green checkmark beside Activity Stream. However when I go to the Activity Stream page, it gives me a button to disable it and no button to enable it, implying that it's already active. However, it doesn't appear to be active, as I don't see any of its UI on the new-tab page.

Disabling then re-enabling it fixed the problem, but I figured I'd report it anyway.

**Comment by pdehaan** [comment]
@markrcote What does your about:addons page look like?

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/20111800/7bb72ff8-a59e-11e6-903a-9b584f6f52b9.png)

**Comment by markrcote** [comment]
At the moment it looks fine (as yours), but as I say I fixed the problem by disabling & re-enabling it. So I don't know if there's anything I can really investigate, unfortunately. Although if it helps, I *think* I originally disabled it via the "This addon is slowing down Firefox" warning at the bottom.

**Comment by pdehaan** [comment]
Ah, some fine QE skills you have! 🍻 
Thanks, I'll keep an eye on it and see if I can trigger the "The addon is slowing down Firefox" warning for that add-on. I haven't seen it lately (which is great news... unless you're trying to repro the bug).

**Comment by markrcote** [comment]
Aha, I just got the slowing-down warning and clicked "disable". Sure enough, it appears disabled in the Test Pilot dropdown now, but selecting it shows a "Disable" button as before. So seems totally reproducible. Anything you'd like me to do to investigate further?

**Comment by pdehaan** [comment]
Reported upstream in Test Pilot as https://github.com/mozilla/testpilot/issues/1810. Closing in favor of upstream bug.
