### ISSUE TITLE
Batch telemetry pings before sending

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1752]
Presently we make a network request for every individual telemetry ping.  We should create a TelemetryFeed which listens for all pings, batches them, and sends them in bulk to Onyx.

**Comment by emtwo** [comment]
I believe the reason we send pings immediately is to use the received timestamp on the server to represent the time the event occurred. If we do batching, we should make sure we only batch things that happen in close time proximity.

**Comment by jaredkerim** [comment]
We discussed and decided this was no an effective strategy.
