### ISSUE TITLE
Create Ping Centre client library

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1755]
Create an npm package for brokering all calls to onyx called Ping Centre, which is easy to drop into any project and allow them to send metrics to the Onyx data ingestion endpoint.  This will replace our current use of Telemetry Sender.

**Comment by emtwo** [comment]
Ping Centre exists now: https://github.com/mozilla/ping-centre

Will file a separate bug for replacing telemetry sender with Ping Centre.
