### ISSUE TITLE
Dismissing a tile only works once.

### ISSUE THREAD

**Issue by mhoye** [mozilla/activity-stream#1762]
In a new tab, click the three-dots menu in the upper right corner of any tile and dismiss that tile. If you attempt to do the same to a second tile, you can hover over the tile and cause the three-dots menu to appear, but clicking it will not bring up the menu. 

Refreshing the page will bring up the menu, and it works again until you dismiss another tile.

I'm using Nightly, current as of today, on OSX. I've got Activity Stream, No More 404s, Pageshot and Tracking protection in stalled as Firefox addons.

**Comment by k88hudson** [comment]
This is a known issue and will be fixed in the next release (fx landed https://github.com/mozilla/activity-stream/commit/534b8b773ce45572f60a4dd2014e0aeb13ac8b84).

Thanks for reporting!
