### ISSUE TITLE
Attach telemetry to the new tool tip hints

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1765]
We have added helpful new 'What's this?' popups to educate users about Activity Stream.  We should attach telemetry to interactions with these tool tips so we can assess whether users are engaging with them.

**Comment by dmose** [comment]
Note to self: should just be trackable like any other click event; no new backend work needed.

**Comment by jaredkerim** [comment]
We're removing the "What's this?" tooltips so this goes away.
