### ISSUE TITLE
Dismissing a tile is (very) temporary

### ISSUE THREAD

**Issue by mhoye** [mozilla/activity-stream#1766]
OSX and current nightly: if I dismiss a tile without deleting that tile's history, it will reappear if I wait a few moments.

**Comment by sarracini** [comment]
Some notes: This is also a problem with _bookmarking_ things...
**STR:** 
1. With a highlight, bookmark a site on AS through the context menu
2. Very very quickly refresh the page

**Expected results:**
The highlight shows the 'bookmarked' context label on the refreshed page

**Actual results:**
The highlight doesn't show the 'bookmarked' context until a couple refreshes later

**What's going on?**
Internally the site is bookmarked, just like internally the site dismissed is added/persisted to the blockedurls list in prefs (and gets filtered out in ```getRecentlyVisited```). However between the time the state is set in the reducers with the blocked site, if you refresh the page, the selectors get the outdated version of the state so it temporarily shows up until you refresh the page again and the selectors get the new state.
