### ISSUE TITLE
Check Embedly results for "safe" attribute (safe browsing api)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#178]
Ref: #177 

We may also want to filter on the Boolean [`safe`](http://docs.embed.ly/docs/extract#response-attributes) property in the Embedly response, so we aren't highlighting potentially unsafe sites.

> `safe`: Safe is an attribute that tells you if the url is on a phishing or malware list. Embedly uses Google's Safe Browsing API to obtain a list of malicious urls. By using this API through our service, you agree to its terms of service.

**Comment by oyiptong** [comment]
:+1: i like that idea

**Comment by pdehaan** [comment]
@nchapman says to wait on this and maybe use the built-in Firefox list of bad URLs/sites.

**Comment by tspurway** [comment]
check if this is taken care of by 'shavar' db

**Comment by oyiptong** [comment]
I will find out if the urls we have are already safe, and if they are, will close that bug

**Comment by nchapman** [comment]
We should use the built-in safe list, but we can do this post v1.

**Comment by oyiptong** [comment]
To check within our safe url list, one could obtain an instance of `nsIUrlClassifierDBService.idl`

One can then call the `lookup` function.

This is illustrated at: https://dxr.mozilla.org/mozilla-central/source/toolkit/components/url-classifier/tests/unit/test_dbservice.js#239

**Comment by jaredkerim** [comment]
We will be deprecating embedly soon and so any efforts involving safe browsing should lean on the internal safety and blacklisting facilities of Firefox.
