### ISSUE TITLE
Collect 'May be making your browser slow' from AddonWatcher

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1782]
Newer versions of Firefox will monitor addons for performance interruptions in the main thread and show a yellow bar indicating that an addon may be slowing down your browser.  We should see if this data is captured by Unified Telemetry and if we can access it anywhere.  This would be useful for monitoring performance improvements we make to Activity Stream.

**Comment by emtwo** [comment]
So the cool thing is there is a module called `AddonWatcher` that we can use to be notified of this. Specifically, we would want to listen to https://dxr.mozilla.org/mozilla-central/source/toolkit/components/perfmonitoring/AddonWatcher.jsm#45

This is already stored in UT so we can analyze it, but I think it's also a good idea to add this to our "bad states" table.

I've removed the priority and I'm going to unassign myself so we can decide on the next steps for this.

**Comment by rlr** [comment]
landed 2988d54588fbb174ed0b27ac6e722a0b51f90830
