### ISSUE TITLE
Highlights should be recalculated after a sync

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#1785]
I returned to a computer that I hadn't used in a couple of days, and here's what I saw in my Highlights:

<img width="731" alt="screen shot 2016-11-11 at 7 54 54 am" src="https://cloud.githubusercontent.com/assets/3095/20220911/3009279e-a7e4-11e6-841e-fa243ad728b2.png">

Notice that they're all 2 or 3 days old. I have been actively using Firefox on other devices so I should see newer content. I checked the sync settings, and the browser had synced this morning. I reloaded a few times for good measure but got the same result.

I think we should probably recalculate Highlights after a successful sync of data we care about (tabs, bookmarks, history).

**Comment by rlr** [comment]
landed fix ^
