### ISSUE TITLE
Users are kicked out of their experiment cohort on version update

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1789]
We can find these users with a couple of queries. The first query shows clients who were in the local metadata experiment prior to the Nov 7th release and were no longer in it for the Nov 7th release:
```
SELECT client_id, experiment_id, COUNT(*)
FROM activity_stream_stats_daily
WHERE client_id IN
  (SELECT DISTINCT client_id
  FROM activity_stream_stats_daily
  WHERE experiment_id = 'exp-004-local-metadata'
  AND date >= '10/19/16'
  AND date < '11/7/16')
AND date > '11/7/16'
AND addon_version IN ('1.1.5', '1.1.6')
GROUP BY client_id, experiment_id
```

We can confirm the results of this query with another query on one of the client IDs that show up in the first query:

```
SELECT date, experiment_id, COUNT(*)
FROM activity_stream_stats_daily
WHERE client_id = 'a61f639c-f568-4931-97e4-a46e6dccba5d'
AND date >= '10/19/16'
GROUP BY date, experiment_id
ORDER BY date, experiment_id
```

**Comment by k88hudson** [comment]
Hm, I've tested a number of updating scenarios and I'm not able to reproduce this. I thought maybe it was that we were removing prefs on an `upgrade` reason but it looks like the code is correct for that case 😕 

I wonder if it could be related to https://github.com/mozilla/activity-stream/issues/1620 possibly?

**Comment by jaredkerim** [comment]
Let's verify whether this is still happening?

**Comment by emtwo** [comment]
I'll take this to verify if it's still happening recently and @k88hudson if you don't mind listing what attempts you've tried that'd be great! Thank you!

**Comment by k88hudson** [comment]
I tried the following situations and could not reproduce the bug:

- When the  add-on is upgraded, when the user is already in an experiment cohort
- When a new experiment is added
- When the browser is restarted
- When Firefox is upgraded

**Comment by emtwo** [comment]
I looked at the most recent data again and it's still happening but it looks like this issue isn't actually triggered by upgrades.

I had three hypotheses:
1. These users are people messing about with experiment settings in about:config so their `experiment_id` switches from an experiment to `n/a`
2. These users are us, which we can verify if we are on the `dev` addon versions
3. These are users doing a lot of uninstalling/disabling which clears their experiment_id each time.

After filtering out these 3 conditions (https://sql.telemetry.mozilla.org/queries/2146#table), the percentage of people in an experiment that experience this issue is very small, under 1%.

One example we can see with this client in this query:
```
SELECT date, experiment_id, COUNT(*)
FROM activity_stream_stats_daily
WHERE client_id = '087b835e-aa5a-794a-9e94-afb12b7ab295'
AND date >= '01/01/17'
GROUP BY date, experiment_id
ORDER BY date, experiment_id
```

This is a small enough percentage that I'm not too concerned about it skewing the data, though it would still be nice to get a better idea of why this is happening. I will file a separate issue though.
