### ISSUE TITLE
Investigate Xvfb XRANDR extension missing problem

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-stream#179]
Travis builds occasionally fail because Xvfb sometimes start without the XRANDR extension.

We need to see if we can ensure Xvfb is launched with the extension.

**Comment by k88hudson** [comment]
I haven't been seeing this error come up lately :pray:

**Comment by oyiptong** [comment]
I've seen it happen occasionally. I just retriggered builds manually. Unfortunately, travis does not keep track of errors if you rebuild.

**Comment by oyiptong** [comment]
This error seems to have be gone now.

Let's close for now
