### ISSUE TITLE
Breakdown work for feedback form on New Tab

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1790]
Trello Card: https://trello.com/c/EiQkbFh4/81-i-want-to-be-able-to-send-feedback-about-my-new-tab-experience

Design Spec: https://mozilla.invisionapp.com/share/6U9AX0C8F

**Comment by Mardak** [comment]
Issues filed and tracked in the project: https://github.com/mozilla/activity-stream/projects/8
