### ISSUE TITLE
Strip out potential username:password in prettyUrl()?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#1792]
Per https://github.com/mozilla/activity-stream/pull/1791#discussion_r87905770,

I was playing around and noticed that the [_./content-src/lib/utils.js_'s `prettyUrl()`](https://github.com/mozilla/activity-stream/blob/c9286d83db030fa7a99e8b0c9de6643d34589a52/content-src/lib/utils.js#L36-L41) method doesn't remove any username/password values that may be present in the URL.

```js
getDomain('https://user:pass@www.gmail.com/1/somepath') // gmail.com
prettyUrl('https://user:pass@www.gmail.com/1/somepath') // user:pass@www.gmail.com/1/somepath
```

**Comment by jaredkerim** [comment]
Closing this as a won't fix for the test pilot addon, if we need this for the system addon we can file a new ticket.
