### ISSUE TITLE
add commit-hash to build somewhere

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#1799]
It's very handy to be able to tell exactly what build of the add-on someone is running.  We should expose the git commit-hash of the build somewhere in the UI (the debug page, perhaps?) so that we can get it when we need it...

Dan

**Comment by pdehaan** [comment]
Related: #1203

**Comment by ncloudioj** [comment]
As @pdehaan suggested, we could append the commit hash to the version string for each build in dev and pre-release.

**Comment by ncloudioj** [comment]
@emtwo If we change the version string from "x.y.z-dev-timestamp" to "x.y.z-dev-timestamp-commit-hash", do you need to change anything on re:dash? I recall that you've got some tricks to extract the versions for the dev channel there.
