### ISSUE TITLE
My history Disappeared

### ISSUE THREAD

**Issue by SherylBratcher** [mozilla/activity-stream#1802]
Please make it come back I don't need 9 hi-lite boxes I need my history...

[test pilot screen.docx](https://github.com/mozilla/activity-stream/files/595033/test.pilot.screen.docx)

Thank You!

Sheryl Bratcher
sherylamericancreative@gmail.com

**Comment by pdehaan** [comment]
Here's a screenshot of the attached DOCX file:

![screenshot_11_16_16__9_35_am](https://cloud.githubusercontent.com/assets/557895/20358293/22800750-abe0-11e6-91ae-70694b53156c.png)

**Comment by jaredkerim** [comment]
Hi Sheryl!  Thanks for your feedback, we have removed the 'Recent Activity' feature for now, but stay tuned in the future as we plan on revisiting this idea!
