### ISSUE TITLE
Reduce content js bundle size

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1805]
Presently, when we start a new tab we pass in two js bundles:

bundle.js: 1.63mb
vendor.bundle.js: 365kb

Together these two files are ~2mb.  According to the gecko profiler, given that it takes ~500ms to start an activity stream tab on my 15" quad i7 MBP, ~250ms of that is loading the 2mb of js we pass in these two bundles.  If we can reduce the amount of js in those bundles to just the js necessary for our page to start, we can improve start up time.

**Comment by pdehaan** [comment]
Ref: Audit webpack bundles #1692
I did a quick audit earlier with **webpack-bundle-analyzer** and it looks like **faker** and **moment** were the biggest contributors to bundle size. If we're not too concerned with localization yet, there may be a way we could not include all moment.js's locales.

**Comment by dmose** [comment]
We should be able to avoid bundling faker with production builds entirely,
I would think.

2016-11-18 11:09 GMT-08:00 Peter deHaan <notifications@github.com>:

**Comment by k88hudson** [comment]
Weird, faker should be excluded from prod builds. I'll take a look
