### ISSUE TITLE
Allow zooming on full page feedback screenshot

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1806]
For just the full page and not the contextual item screenshot, the user should be able to see a zoomed view of the page of where the cursor is on the smaller screenshot. The zoomed view is shown instead of the labels.

https://mozilla.invisionapp.com/share/6U9AX0C8F

**Comment by sarracini** [comment]
We're not doing the feedback form right now, and if we do the specs will change and we will re-open this issue
