### ISSUE TITLE
Show a item-specific screenshot for TopSite and Highlight feedback

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1807]
Similar to the full page screenshot being initially disabled, this will allow showing of the specific item screenshot for that feedback. The "screenshot" item is not interactable.

https://mozilla.invisionapp.com/share/6U9AX0C8F

**Comment by sarracini** [comment]
We're not doing the feedback form right now, and if we do the specs will change and we will re-open this issue
