### ISSUE TITLE
Add item contextual menu to show item-specific feedback form

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1808]
TopSites and Highlights context menus have a last new item (and a separator) to open up the feedback form. This form differs from the full page feedback with different screenshot and different label text. The size of the screenshot matches that of a Highlight. Whitespace is added around a TopSite.

Screenshot handled in #1807

https://mozilla.invisionapp.com/share/6U9AX0C8F

**Comment by sarracini** [comment]
We're not doing the feedback form right now, and if we do the specs will change and we will re-open this issue
