### ISSUE TITLE
Show a page screenshot for a full page feedback

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1809]
The initial implementation has screenshot disabled, but this will allow for the user to by default see the screenshot and optionally disable the screenshot.

Zooming is handled #1806

https://mozilla.invisionapp.com/share/6U9AX0C8F

**Comment by sarracini** [comment]
We're not doing the feedback form right now, and if we do the specs will change and we will re-open this issue

**Comment by rlr** [comment]
so rude.

**Comment by sarracini** [comment]
@rlr deal with it

**Comment by rlr** [comment]
you win
