### ISSUE TITLE
Polish edges/transitions/error-handling of feedback form

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1810]
Not explicitly shown in the invisionapp yet. There will be fade transitions to show/hide the form. Additionally there will be a brief success/submitted state as well as error handling if the submission failed.

@aaronrbenson will provide more details of what needs to be done.

https://mozilla.invisionapp.com/share/6U9AX0C8F

**Comment by sarracini** [comment]
We're not doing the feedback form right now, and if we do the specs will change and we will re-open this issue
