### ISSUE TITLE
Add feedback button to show modal feedback form

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1811]
This is the initial bug for the feedback form focusing on the full page feedback experience. The text labels for radio buttons for full page differ from the item contextual labels. We'll split off the screenshot logic, but we should show the space and checkbox control (default unchecked and disabled for now).

The form will be modal and @aaronrbenson will add screens showing how that should appear over the rest of the content.

Item contextual form handled in #1808
Full page screenshot handled in #1809 
Transitions and other edge cases handled in #1810
Surveygizmo endpoint handled in #1812 

Sizes and texts available here:
https://mozilla.invisionapp.com/share/6U9AX0C8F

**Comment by Mardak** [comment]
@aaronrbenson can you provide a text format of the full page labels in this bug? In particular the unicode emoji?

**Comment by aaronrbenson** [comment]
Absolutely. Getting a final 👍 on the copy and then I'll post it here!

**Comment by jaredkerim** [comment]
Closing this metabug and all future information should be added to individual tickets and tracked in the project.
