### ISSUE TITLE
Highlight provider name should be top level domain only (or at least don't wrap the title)

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1816]
![screen shot 2016-11-21 at 5 02 23 pm](https://cloud.githubusercontent.com/assets/139451/20504295/4d521006-b00c-11e6-808a-2d25fd18fcd7.png)

Don't wrap the provider name and consider not showing this at all if we can't get a top level domain. It appears to have fallen back to the website <title>.

**Comment by aaronrbenson** [comment]
Another one spotted in the wild.
![screen shot 2016-11-23 at 11 16 25 am](https://cloud.githubusercontent.com/assets/139451/20571787/81117996-b16e-11e6-8821-afc998ccc3b8.png)

**Comment by tspurway** [comment]
Use domain name instead
