### ISSUE TITLE
Missing TOP_SITES pings

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1831]
It looks like our top sites pings have dropped significantly since our last release on Nov. 24th. We can see it in this graph: https://sql.telemetry.mozilla.org/queries/1800#3196 with this query:
```
SELECT date, COUNT(*)
FROM activity_stream_events_daily
WHERE source = 'TOP_SITES'
GROUP BY date
ORDER BY date
```
This is likely a reporting bug since all other numbers are looking consistent (mau/dau/highlights clicks/searchs etc)

**Comment by pdehaan** [comment]
Could this possibly be because we've removed the Timeline page so now the only thing which sends TOP_SITES pings is the New Tab page?
