### ISSUE TITLE
Search bar on the default activity stream screen should also search time line streams

### ISSUE THREAD

**Issue by nunocastro** [mozilla/activity-stream#1839]
By default, the only way we have to search the stream, is to enter the detailed stream screen and search there.
This is an annoyance because we can only either search the web or search our streams.

Search on the default screen should list, on the auto-suggestions, entries from the stream and the web.

**Comment by jaredkerim** [comment]
This will be handled by a separate effort and not by activity stream.  Closing this for now, but stay tuned!
