### ISSUE TITLE
Certain favicon icons look blurry

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#184]
A bunch of my icons look blurry because it seems like we're upscaling 16x16px icons up to 32x32px.

![new_tab](https://cloud.githubusercontent.com/assets/557895/13267447/21e17b2e-da32-11e5-8bc0-dd852560ca30.png)

![fullscreen_2_23_16__1_35_pm](https://cloud.githubusercontent.com/assets/557895/13267498/698643f6-da32-11e5-8c80-d77e594e62d9.png)

Not sure how to solve that, since IIRC we're getting the favicon data back from embedly based on what the site defined. But one solution may be to write our own clearbit proxy or something ([related](https://github.com/mozilla/activity-streams/issues/132))

![](http://logo.clearbit.com/youtube.com?size=32)
http://logo.clearbit.com/youtube.com?size=32

**Comment by jaredkerim** [comment]
Future implementations of metadata extraction will allow for the parsing and storage of high res icons, and so this will be covered by that implementation.
