### ISSUE TITLE
Page Scraper failing to parse

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1843]
Version: 1.1.9-dev-a11675b

Page scraper is complaining:

<img width="1111" alt="screenshot 2016-11-30 13 52 12" src="https://cloud.githubusercontent.com/assets/119884/20772895/463df204-b704-11e6-9df2-291b2475d64d.png">

**Comment by sarracini** [comment]
any STR this @jaredkerim ?

**Comment by jaredkerim** [comment]
This was fixed in https://github.com/mozilla/activity-stream/issues/1859
