### ISSUE TITLE
Enhance the WeightedHighlight scoring algorithm 

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1845]
As a follow up for #1311, we might want to revisit the current weighted highlight strategy, in particular, for the following cases:

* Recently bookmarked links, weight adjusting may not be sufficient in some cases. See #1794 and #1844 
* Links with different signals, such as:
   - metadata, see #1189 
   - proximity and deduping, see #1311, #1788
   - synced links, see #411, #1785

**Comment by Mardak** [comment]
The algorithm currently highly prefers sites that you tend not to visit, so if you normally visit amazon.com, even if you bookmarked it, it would tend to get a lower score.

**Comment by ncloudioj** [comment]
@Mardak So the current image-less bookmark score boost won't work in some cases.

For example, I bookmarked a site, then opened a new tab, it just took the last spot of the highlight grid. Had to scroll down to see it. This is opposite to the fact that we want to show the recent bookmarks in the front of the line.

**Comment by jaredkerim** [comment]
This should be refiled as a project for Improving Highlights, and will probably need to take place after we land in MC.

**Comment by jaredkerim** [comment]
Closing this and replacing it with:

https://github.com/mozilla/activity-stream/projects/12
