### ISSUE TITLE
Activity Stream should not animate animated GIFs

### ISSUE THREAD

**Issue by cpeterso** [mozilla/activity-stream#1853]
The top image on the following Medium article is an animated GIF. When it shows up on my Activity Stream home page, it is animated, which is very distracting.

https://medium.com/@eluciano11/from-ember-to-react-5c2faa0e8d10#.h4iswe2l4

**Comment by tspurway** [comment]
The user has the ability to dismiss tiles that contain animated GIFs.  If however, we find performance issues with animated GIFs, then let's revisit.  Closing.
