### ISSUE TITLE
Can not drag and drop one favourie site's priority

### ISSUE THREAD

**Issue by mMARUF** [mozilla/activity-stream#1856]
In the activity-stream , where there are list of my often visited websites, if I try to change to priority of a site y jut simply  drag and drop the the site to change its position , it does not work. But, users should have the right to change he priority of their favorite sites. 

This issue is tested in latest Nightly 53

Attachment 1 : https://drive.google.com/open?id=0B75_JfziYeofclBVTGNEdUZsUGc
Attachment 2 : https://drive.google.com/open?id=0B75_JfziYeofVkppd2VQS2tXZUk

**Comment by jaredkerim** [comment]
We are working on designs for customizing top sites and higlights, but it has not been finalized yet.
