### ISSUE TITLE
Tuning the schema of Metadata Store

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1858]
During the workweek, we had Mak to have a thorough review on the schema of Metadata Store. Here is a list of the feedback that we want to dive deeper.

* The "title" column is redundant if it's already stored in places
* Consider adding a size cap to the "description" column to avoid bloated database
* Encode the "type" column in the "page_metadata" table to speed up the query performance
* Consider using timestamp for the "created_at" column
* Consider moving the long fields to the end of the schema

**Comment by dmose** [comment]
Interesting; does moving long fields to the end of the schema improve
performance somehow?

2016-12-09 13:58 GMT-08:00 Nan Jiang <notifications@github.com>:
