### ISSUE TITLE
Flashing banner on first install for Ubuntu

### ISSUE THREAD

**Issue by edadoko** [mozilla/activity-stream#1861]
When first installing activity stream, immediately opening a new tab causes a flashing 'Welcome to new tab' page. This flashing continues even on opening other new tabs. Quitting the browser then relaunching fixes the problem. 

![flashing_welcome](https://cloud.githubusercontent.com/assets/7792311/21126492/881307ea-c0ba-11e6-8df9-cbd35a96e4fc.gif)

**Comment by jaredkerim** [comment]
This is fixed in an upcoming release.
