### ISSUE TITLE
URL Bar displaying unexpected content Ubuntu

### ISSUE THREAD

**Issue by edadoko** [mozilla/activity-stream#1863]
When opening a new window or tab the URL bar displays: `resource://activity-streams/data/content/activity-streams.html#/`. (This does not happen on Mac OS)

![url_bar](https://cloud.githubusercontent.com/assets/7792311/21128315/da5211a6-c0c7-11e6-97b0-4963dd94952a.png)

**Comment by jaredkerim** [comment]
We should investigate if there's a simple way to fix this otherwise push it back until we land in MC.

**Comment by jaredkerim** [comment]
Closing this for now becuase this will be solved in the new system addon.
