### ISSUE TITLE
Everywhere/Extend Firefox/Complete Your Install cards displayed under highlights despite having browser history

### ISSUE THREAD

**Issue by hmcgaw** [mozilla/activity-stream#1864]
Save Everywhere/Extend Firefox/Complete Your Install cards are displayed under highlights even when the user has lots of browser history.

<img width="494" alt="screen shot 2016-12-12 at 6 51 56 pm" src="https://cloud.githubusercontent.com/assets/21317131/21145873/caac73c6-c11d-11e6-9191-5ded2741ad78.png">

**Comment by dmose** [comment]
I believe that once #1670 is closed, these cards will disappear entirely
for everyone, but I may be misremembering.  @bryanbell, can you confirm or
deny?

2016-12-13 7:21 GMT-08:00 hmcgaw <notifications@github.com>:

**Comment by dmose** [comment]
Er, I should have said "will be able to disappear entirely for everyone", as that work won't be part of #1670.

**Comment by tspurway** [comment]
Destroy default cards!

**Comment by Mardak** [comment]
Did we decide on whether there should never be any default cards or only show them if there's no history? Where I suppose in the latter case, it's only helpful on a completely new profile and once the user goes anywhere, the defaults disappear. If that's the case, I would think we'll want to just remove the defaults always. Yeah?

**Comment by dmose** [comment]
My understanding from the triage meeting yesterday was that these current default cards should be completely killed.
