### ISSUE TITLE
Experiment cohorts not unassigning themselves from disabled experiments

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1866]
In 1.1.8 we set to the local metadata experiment to inactive:

https://github.com/mozilla/activity-stream/blob/release-1.1.8/experiments.json#L49

However we can see that there are still users actively assigned to the experiment in 1.1.8 by querying the data.  There must be a bug in experiment provider which is failing to unassign users from a disabled experiment.

**Comment by emtwo** [comment]
There is actually some confusion here where 1.1.8 was simply a chemspill release and in fact the "graduate local metadata" commit will be available in 1.1.9. So this should be resolved once we actually release the graduation.
