### ISSUE TITLE
Experiment Provider unhandled exceptions

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1867]
Version: 1.1.9-dev-a2a18d5

Experiment Provider is causing the following unhandled exceptions at install time:

<img width="1124" alt="screenshot 2016-12-13 15 00 31" src="https://cloud.githubusercontent.com/assets/119884/21156847/539ac986-c145-11e6-8017-252f0c8f7d51.png">

**Comment by jaredkerim** [comment]
This is probably what is causing #1864

**Comment by emtwo** [comment]
Note: this bug is to just add exception handling and it's not necessary to reproduce

**Comment by hmcgaw** [comment]
Recreated by uninstalling and reinstalling Activity Stream via Test Pilot 

![screen shot 2016-12-19 at 2 31 05 pm](https://cloud.githubusercontent.com/assets/21317131/21327114/a0a00984-c5fb-11e6-85a9-a46c40a5394c.png)

**Comment by hmcgaw** [comment]
Recreated by uninstalling and then reinstalling Activity Stream from Test Pilot 

![screen shot 2016-12-19 at 2 31 05 pm](https://cloud.githubusercontent.com/assets/21317131/21327269/4c01ff9e-c5fc-11e6-9796-66184a154a6a.png)
