### ISSUE TITLE
Determine which Embedly result types to include in results

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#187]
The [Embed.ly extract API docs](http://docs.embed.ly/docs/extract#response-attributes) lists the ~12 different types of results that that they handle

(Spoiler alert)

1.    `html`: The most common response. The resource is an `html` document.
2.    `text`: The response is a plain `text` document.
3.    `image`: This is a static viewable `image`.
4.    `video`: This is a playable `video`.
5.    `audio`: This is a playable `audio`.
6.    `rss`: The resource is an `rss` feed.
7.    `xml`: The resource is an `xml` document.
8.    `atom`: The resource is an `atom` feed.
9.    `json`: The resource is a `json` document.
10.    `ppt`: The resource is a PowerPoint document.
11.    `link`: This is a general embed that may not contain HTML.
12.    `error`: When accessing multiple urls at once Embedly will not throw HTTP errors as normal. Instead, it will return an `error` type response that includes the `url`, `error_message` and `error_code`.

Here's what my results currently look like with a few random images in my activity feed:

![new_tab](https://cloud.githubusercontent.com/assets/557895/13268151/b6c43cc4-da35-11e5-8df1-952db0facdb8.png)

As you can see, since it's just an image on a page, there is no title or any viable data that we can show (apart from a fallback site icon with the first letter of the provider name (ie "Tumblr" and "Clearbit"):

![new_tab_and_new_tab](https://cloud.githubusercontent.com/assets/557895/13268234/353bd152-da36-11e5-987a-b2c2cd8f25b8.png)
"type": "image"

I don't know what the optimal user experience is here. Do we just omit image (and maybe: "audio", "rss", "xml", "atom", "json", "ppt", "link", and "error") types, or if users would expect to see a list of sweet-sweet GIFs (and Powerpoint presentations that they were browsing earlier).

Or maybe if we can't find a `title` from the embedly results, we just display the `provider_name`, which may be marginally more friendly.

**Comment by pdehaan** [comment]
Actually, looking deeper "YouTube.com" link in the first screenshot is an "html" result, but has no title information, so this isn't truly specific to image types.

Here's what using the `provider_name` fallback would look like (compliments of DevTools hackery):

![new_tab](https://cloud.githubusercontent.com/assets/557895/13268412/363ab91e-da37-11e5-8832-79b0cb031fcd.png)

Better than nothing, but may be a bit awkward if you have 20 Tumblr results in your Activity Feed and they all just say "Tumblr" (not that no text and a long mashed URL are great identifiers anyways).

![new_tab](https://cloud.githubusercontent.com/assets/557895/13268494/a792fbbc-da37-11e5-875a-5473dda629ca.png)

**Comment by pdehaan** [comment]
Actually, possibly a dupe of #159

**Comment by jaredkerim** [comment]
The minimum schema required to satisfy the Activity Stream use case is as follows:

{ type: 'website',
  url: 'http://www.eetimes.com/document.asp?doc_id=1329941',
  title: 'China Tops U.S. in Supercomputers | EE Times',
  description: 'China built the world\'s most powerful supercomputer with chips it designed itself and topped the U.S. for the first time in the number and performance of installed systems.',
  favicon_url: 'http://img.deusm.com/eetimes/favicon.ico',
  image: 'http://img.deusm.com/eetimes/2016/06/1329941/Sunway-computer-room-x-366.png',
  original_url: 'http://www.eetimes.com/document.asp?doc_id=1329941',
  provider_url: 'http://www.eetimes.com/document.asp?doc_id=1329941',
  favicon_colors: [ { color: [1, 2, 3], weight: 0 } ],
  images:
   [ { url: 'http://img.deusm.com/eetimes/2016/06/1329941/Sunway-computer-room-x-366.png',
       width: 500,
       height: 500,
       colors: [1, 2, 3] } ] }


This will be satisfied by the Fathom based metadata processor.

**Comment by jaredkerim** [comment]
Embedly will be deprecated and so these particular page type classifications will no longer be accessible or relevant. We will have access to a 'type' field which will be populated by open graph data, which will allow for rich content filtering based on metadata selectors, however this will not be based on embedly formatted data.  See #770 for details.
