### ISSUE TITLE
recent activities timeline disappeared!

### ISSUE THREAD

**Issue by ashokaditya** [mozilla/activity-stream#1872]
I do not see recent activity timeline anymore! It suddenly disappeared.
I used to be able to see activity stream and recent activities timeline upon creating or opening a new tab!
<img width="1312" alt="screen shot 2016-12-15 at 14 39 47" src="https://cloud.githubusercontent.com/assets/1849116/21226107/6002daac-c2d4-11e6-8ba8-ceb6e885f7d4.png">

**Comment by Softvision-VladBacia** [comment]
@ashokaditya thank you for reporting this. 

Unfortunately AS Tineline has been removed in #1499  and Recent Activity from New Tab page was replaced by Weighted Highlights. Instead of the Recent Activity section, now there are 9 Weighted Highlights.

**Comment by tspurway** [comment]
Thank you for the feedback @ashokaditya !  We miss the timeline view, too and will be bringing it back in a future release, better than ever.  We removed it to focus on the core functionality.
