### ISSUE TITLE
Remove Tooltip Helper (What's this?) on both Top Sites and Highlights

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1873]
![screen shot 2016-12-19 at 9 32 13 am](https://cloud.githubusercontent.com/assets/139451/21318258/0bde33fc-c5ce-11e6-93a3-8ad97f898891.png)

Currently the tooltip helper remains in the UI unless you click on the "Okay, got it" button inside the tooltip. We don't want these helpers to linger forever, so lets institute a hard limit on the number of times they show up on new tab at 50x. This is a bit of an arbitrary number so it's open for discussion.

**Comment by tspurway** [comment]
Qualitative research indicates users already know what top sites and highlights are.

**Comment by jaredkerim** [comment]
We should remove `What's this` altogether
