### ISSUE TITLE
Recently bookmarked pages should show on newtab no mater what, older ones shouldn't

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#1887]
@bryanbell suggests bookmarks made within 3 days get a boost so that just bookmarked pages show up for sure:
```
give a bookmark that’s 0-120minutes old a Plus 100 points
then a bookmark that’s 120-500mins old gets a +40
a bookmark that’s older than 3 days gets no point boost
```

**Comment by bryanbell** [comment]
BTW I made those number up.

The point is that bookmarks that are newly minted should get enough of a point boost to guarantee their inclusion on the new tab instantaneously.  As they age their boost should fade, and after say 3 days their boost should be eliminated.

**Comment by Mardak** [comment]
Maybe we can do something like.. `boost = 3 / age`, so a bookmark that is 3 days old gets a boost of 1, 1.5 days old gets boost of 2, 6 days old gets boost of 0.5.

We can skew this even more by adding an exponent, e.g., `boost = (3 / age)³ ` so a 3 day old bookmark still gets a boost of 1, 1.5 day old get boost of 8, 6 day old get boost of 0.125.

In general, dividing by the age makes it so that a just created (1 second ago) gets a near-infinitely large boost.

**Comment by bryanbell** [comment]
YAY!
