### ISSUE TITLE
Please make my RSS feed of websites come back

### ISSUE THREAD

**Issue by SherylBratcher** [mozilla/activity-stream#1889]
I have tried uninstallinig/re-installing and all I get are the small focus boxes with the larger ones below.

Also I rarely use the gmail address this is showing you so please cc sbratcher@americancreative.com so that I see the reply on how to fix this!

I attached a screen print. Believe me when I say below that there's just more focus boxes
[activity stream.docx](https://github.com/mozilla/activity-stream/files/664592/activity.stream.docx)

Thank you!

**Comment by jaredkerim** [comment]
See https://github.com/mozilla/activity-stream/issues/1802
