### ISSUE TITLE
Top Site and Highlights cards need a line separator between the icon/image and text sections

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1892]
There should be a separator on Top Site and Highlight tiles, as described in the attached picture. 
![tile-seperator](https://cloud.githubusercontent.com/assets/139451/21400774/51a32168-c777-11e6-9da7-11d6528a2046.png)

**Comment by Mardak** [comment]
@dmose was this something you added to the topsites placeholder and removed later in the PR because the actual site didn't have the line?

@aaronrbenson should there be a line in the highlights placeholder? There isn't one here: https://mozilla.invisionapp.com/share/D995GXJVC

**Comment by aaronrbenson** [comment]
@Mardak no, not on the highlights placeholder card since we use the darker BG color to show the image section. 

Though, I think I could be persuaded to have it in both places if it were easier to build.

**Comment by dmose** [comment]
@Mardak I ended up putting it back before landing after talking to Aaron.

2016-12-21 10:42 GMT-08:00 aaronrbenson <notifications@github.com>:

**Comment by Mardak** [comment]
Here's some after pictures:
![screen shot 2016-12-21 at 11 15 06 am](https://cloud.githubusercontent.com/assets/438537/21403480/c8561a0a-c771-11e6-87d8-5bb89e756f53.png)
![screen shot 2016-12-21 at 11 29 22 am](https://cloud.githubusercontent.com/assets/438537/21403487/cb3f7108-c771-11e6-9078-595ee2f05989.png)

And for reference from before/now:
![screen shot 2016-12-21 at 11 16 20 am](https://cloud.githubusercontent.com/assets/438537/21403495/d3098a36-c771-11e6-8a9f-d6f753cc6b99.png)
![screen shot 2016-12-21 at 11 16 57 am](https://cloud.githubusercontent.com/assets/438537/21403496/d4d4786c-c771-11e6-97d9-9cd91721eddb.png)

**Comment by aaronrbenson** [comment]
![i-like-it-alot](https://cloud.githubusercontent.com/assets/139451/21405728/539881e6-c78d-11e6-91f2-d02e040b693c.gif)
