### ISSUE TITLE
Top sites and Highlights tiles are still populated after deleting all Firefox history

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/activity-stream#1901]
[Affected versions]:
- Nightly 53.0a1
- Activity Stream 1.1.8-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.8-dev) was previously installed on a clean profile.
- Have enough history so that Top Sites and Highlights tiles are populated.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Open a new tab and observe the Activity Stream history.
3. Clear all history (Ctrl+Shift+Delete shortcut) and refresh the page.
4. Observe the Activity Stream Top Sites and Highlights tiles.

[Expected results]:
- The default Activity Stream new tab page is displayed.

[Actual results]:
- Activity Stream Top Sites and Highlights tiles are still populated.

[Notes]:
- If you visit a new website, the Highlights tiles will disappear but the Top Sites remain populated.
- The default Activity Stream new tab page is displayed if the browser is restarted.
- Here is a screen recording with the issue: https://goo.gl/UYUURm.

**Comment by jaredkerim** [comment]
We probably need to listen to the 'ManyLinksChanged' event?

**Comment by sarracini** [comment]
@SoftVision-CosminMuntean can you confirm this issue is fixed?

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Activity Stream version 1.2.0-dev.
