### ISSUE TITLE
Some users are in Shield for more than 14 days

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#1908]
We can see that using this query:

```
SELECT * FROM
    (SELECT client_id, shield_variant, DATEDIFF(day, MIN(date), MAX(date)) AS day_count
    FROM ss_session
    GROUP BY client_id, shield_variant)
WHERE day_count > 14
```

I verified that at least one user exists that had the experiment for more than 14 days while still using the browser every day, so this isn't caused by a user who leaves for a few days:

```
SELECT client_id, shield_variant, date, COUNT(*)
FROM ss_session
WHERE client_id = 'c1a95725-dc60-4308-8338-2a4a613efec0'
GROUP BY client_id, shield_variant, date
ORDER BY client_id, shield_variant, date
```

The other possibility is that the `shield_variant` attribute is only updated when you restart the browser, for example. We should try to verify this somehow or ask Matt G.

**Comment by emtwo** [comment]
There are only roughly 0.4% of users experiencing this, and this is an expected amount according to Gregg Lind

**Comment by Mardak** [comment]
Do we know if these users installed the add-on from AMO directly instead of via Shield? Should we be doing something about the AMO listing? https://addons.mozilla.org/en-US/firefox/addon/activity-stream-shield-study/

**Comment by emtwo** [comment]
@Mardak - that listing link is actually something the Shield people told us about and said it may bring other users to us. However, they also said that even if they installed the addon from that link it will still automatically deactivate on time. The only issue with that link is that the people who found it may bring in some bias to the results (e.g. these people might be tinkerers or devs who do not represent the general population)
