### ISSUE TITLE
Incorrect "total_history_size" and "total_bookmarks" in the session ping

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1914]
Using A-S with a new profile, the payload of the session ping always has following values
```json
{
  "total_history_size": 0,
  "total_bookmarks": 10
}
```
Looks like those two fields didn't get updated properly.

**Comment by emtwo** [comment]
There are usually some default bookmarks that come with a new profile. Perhaps that's where the 10 is coming from?

**Comment by sarracini** [comment]
This is working as intended - the PlacesStatsFeed updates every 24h so although it looks wrong a bunch, it'll eventually correct itself. Closing this
