### ISSUE TITLE
Duplicate tiles in the Topsites

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#1916]
Having two exact same tiles (with the same urls) in the Topsites. You can reproduce this by clicking on the  default tiles in the Topsites, and then open another new tab page.

<img width="712" alt="screen shot 2017-01-04 at 10 46 04 am" src="https://cloud.githubusercontent.com/assets/1455254/21648185/0cc9d27c-d26b-11e6-85ea-5ed082f797a5.png">

**Comment by Mardak** [comment]
Looks like `selectAndDedupe` just appends the defaults:

https://github.com/mozilla/activity-stream/blob/05fcc35a6a06edf025be87ad4e844e7dd6dd2f99/common/selectors/selectAndDedupe.js#L22-L23
