### ISSUE TITLE
Limit number of URLs returned by TopFrecentSites

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1918]
AS Version: 1.1.9-dev-a9b100f

When we query Places for top sites, we should cap it at a small number rather than returning a very large number including full data uri's for the favicons as this increases the size of the JSON payload from 100kb to 1.5mb for my profile.

**Comment by Mardak** [comment]
How many items should it return? One number is 6, which matches the visible top sites, but if the user dismisses any, it'll go straight to the defaults, e.g., Facebook. Another number could be double the number, so 12.

@emtwo, perhaps being smarter, we could figure out how many top sites a user dismisses in one go. Do we have any insights here? Or maybe find the average of dismisses and double that number?
