### ISSUE TITLE
Places Provider Unhandled Exception

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1919]
AS Version: 1.1.9-dev-a9b100f

On startup of activity stream, we see this:

![screenshot 2017-01-04 13 45 29](https://cloud.githubusercontent.com/assets/119884/21654573/12bc3f3a-d284-11e6-8bf6-3b643931b2ff.png)

**Comment by sarracini** [comment]
Can we get some STR?

**Comment by Mardak** [comment]
I can trigger a similar error if I bookmark `resource://gre/modules/Services.jsm`
```
NS_ERROR_DOM_BAD_URI: Component returned failure code: 0x805303f4 [nsIScriptSecurityManager.checkLoadURIStrWithPrincipal]  (unknown)
	LinkChecker_doCheckLoadURI resource://activity-streams/addon/PlacesProvider.js:151:7
	LinkChecker_checkLoadURI resource://activity-streams/addon/PlacesProvider.js:138:29
	Links.prototype.getBookmark</< resource://activity-streams/addon/PlacesProvider.js:461:26
```

The original code looks to be from `NewTabUtils` and the way `checkLoadURIStrWithPrincipal` indicates if the load request should be denied is with an exception.
https://dxr.mozilla.org/mozilla-central/source/caps/nsIScriptSecurityManager.idl#102-127

We should be able to just remove the `reportError` as it's an expected control flow.

@jaredkerim do you know what URI is triggering this? If you want to debug:
https://github.com/mozilla/activity-stream/blob/49833d3ebf9c8c9a4896be4dac25aa8a8e4404ec/addon/PlacesProvider.js#L157
```diff
diff --git a/addon/PlacesProvider.js b/addon/PlacesProvider.js
index 0aadd1c..c8f2e68 100644
--- a/addon/PlacesProvider.js
+++ b/addon/PlacesProvider.js
@@ -147,17 +147,17 @@ let LinkChecker = {
     if (aURI.startsWith("place:")) {
       return false;
     }
     try {
       Services.scriptSecurityManager.checkLoadURIStrWithPrincipal(gPrincipal, aURI, this.flags);
       result = true;
     } catch (e) {
       // We got a weird URI or one that would inherit the caller's principal.
-      Cu.reportError(e);
+      Cu.reportError(aURI);
     }
     return result;
   }
 };
 
 /* Queries history to retrieve the most visited sites. Emits events when the
  * history changes.
  * Implements the EventEmitter interface.
```
