### ISSUE TITLE
Typo in ActivityStream.js

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1921]
"initializePreviewProvier" should be "initializePreviewProvider" 

https://github.com/mozilla/activity-stream/blob/master/addon/ActivityStreams.js#L118

https://github.com/mozilla/activity-stream/blob/master/addon/ActivityStreams.js#L189

**Comment by sarracini** [comment]
I'm gonna fix this in the PR for #1940 while I'm there, so I'll close this
