### ISSUE TITLE
Top Site: Google tile goes to my calendar

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#1934]
![screen shot 2017-01-09 at 2 12 30 pm](https://cloud.githubusercontent.com/assets/139451/21781581/aefaa87e-d675-11e6-8892-5c6e4c46c373.png)

I have a Google Top site tile and it currently points to my google calendar: https://calendar.google.com/calendar/

**Comment by ncloudioj** [comment]
Dup of #1898. Closing this.
