### ISSUE TITLE
New Tab prompts to install add-on visited in the past

### ISSUE THREAD

**Issue by kewisch** [mozilla/activity-stream#1945]
It seems I visited the install URL of an add-on in the past, which activity streams picked up and presented to me on the new tab page. The result was, that I got an add-on install dialog from the activity streams page.

I suspect the URL that was used is https://addons.mozilla.org/firefox/downloads/latest/375008/addon-375008-latest.xpi?src=dp-btn-primary

**Comment by sarracini** [comment]
@kewisch can you still reproduce this? and if so, can you reproduce it in the system-addon version too?

**Comment by kewisch** [comment]
I'm not currently using activity stream, but I'll see if I can reproduce this. Might take a bit before I reply.

**Comment by sarracini** [comment]
I can't seem to reproduce this on the system-addon version of activity stream. if no one else can reproduce this then let's close this

**Comment by kewisch** [comment]
I've been using Activity Stream since and haven't experienced this again, good to close. Thanks for following up!
