### ISSUE TITLE
turn on jsx-no-bind eslint rule to avoid unnecessary perf lossage

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#1949]
Turns out that using arrow functions or binding functions in render() is a non-trivial performance hit, because it causes a function allocation and associated GC in every single call to render, even if render doesn't end up changing anything in the layout.

See <https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md> and 
<https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.2bk1pstfj>.

We've got a bunch of instances of it in our codebase, though they shouldn't be terribly hard to fix.  The possible fixes are detailed in the above links, as well as (if we start using ES6 classes for our components) <https://babeljs.io/blog/2015/06/07/react-on-es6-plus>.

**Comment by sarracini** [comment]
No longer doing work on test pilot version of the addon. closing this

**Comment by Mardak** [comment]
This was fixed for system-addon via #2928.
