### ISSUE TITLE
Error: "tab is undefined" in PerfMeter

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1951]
Saw this in latest dev version:

console.error:
  TypeError: tab is undefined: log@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/addon/PerfMeter.js:133:1
_logPerfMeter@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/addon/ActivityStreams.js:349:5
_setupListeners/this._contentToAddonHandlers@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/addon/ActivityStreams.js:372:7
emit@resource://devtools/shared/event-emitter.js:191:13
onMessage@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/addon/ActivityStreams.js:406:29
onAttach/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/addon/PageModProvider.js:60:13
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker.js:74:26
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/parent.js:96:37

**Comment by dmose** [comment]
I just saw this too.

**Comment by sarracini** [comment]
closing this since we won't be using this in system addon
