### ISSUE TITLE
Use the original tiles algorithm to get the top sites

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#1952]
So in the SHIELD study we saw that our top sites were not as successful as the original tiles in terms of click through rates. An easy experiment we can run is the use the original new tab sites' algorithm to power our top sites (the first 6, anyways). That way we can see if our click through rates improve at all. If they don't, it's a good indication that there's something else contributing to the low click through rate for top sites compared to tiles.

cc @emtwo

**Comment by emtwo** [comment]
let's do it. we'll probably be diving more into what to do about topsites next week too.
