### ISSUE TITLE
New Tab Preferences Pane

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1984]
https://trello.com/c/ByHqlXfd/17-i-want-to-customize-my-new-tab-page-so-that-the-things-i-care-about-are-where-i-want-them

This is the preference pane that allows users to choose which sections of activity stream (Top Sites, Highlights, Search) are available on the about:newtab page

- [ ] Establish default prefs for Top Sites, Highlights and Search visibility
- [ ] Tool existing newtab page to check for and render the sections according to prefs
- [ ] Build UI to display and modify prefs according to specs

**Comment by aaronrbenson** [comment]
The prefs modal was updated to include an option for snippets: https://mozilla.invisionapp.com/share/3JA587BBE#/screens/215824028_Preferences_Newtab_Modal
