### ISSUE TITLE
Top Sites icon improvement

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1988]
https://trello.com/c/JzwG7YNu/126-make-top-sites-more-special

The feature will improve the Top Site presentation/visualization.  The Top Site rendering will choose the best quality (high res, min 128px) icon available for the site.  Failing the availability of this quality, fall back on a screenshot of the site, plus any available favicon, which will be overlayed on the top left corner as per spec.

**Comment by jaredkerim** [comment]
TabCenter captures screenshots of tabs using this method:

https://github.com/bwinton/TabCenter/blob/master/vertical-tabbrowser.xml#L791-L831

**Comment by nchapman** [comment]
Icon rules:

1. Top site visuals should fit inside a 96x96px square
2. Large icons with white or transparent borders should add a border
3. Small icons should follow the same rule as small icons in Highlights

**Root Domains**

1. Use a Tippy Top icon centered on the provided background
2. Else use the display icon (apple touch icon) full width and height (96px)
3. Else use high res favicon (96px minimum) full width and full height (96px)
4. Else use screenshot with small favicon in the corner (32px)
5. Else use screenshot with letter + color in the corner

**Non Root Domains**

1. Use screenshot with favicon in the corner (32px)
2. Else use screenshot with letter + color in the corner
