### ISSUE TITLE
Audit and Optimize Weighted Highlights algorithm

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#1989]
Create an experiment investigating changing co-efficients for the weighted highlights algorithm.  Run experiment with the goal of improving overall user engagement for the highlights section.  Pay particular attention to improving engagement for the low usage cohort.

**Comment by jaredkerim** [comment]
This could benefit from some further insight from user research, as well as quantitative analysis on low engagement users to figure out how we can improve their user experience.

**Comment by jaredkerim** [comment]
Highlights will be deprecated altogether in test pilot and system addon and so the algorithm will go away.
