### ISSUE TITLE
'Hang Tight' still hangs and does not resolve

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1995]
AS Version: 1.3.0-dev-1484695187

I updated my activity stream to the latest version, opened a new tab, and saw 'hang tight'.  It spins forever and does not resolve itself.  Opening a new tab will show activity stream, but the 'hang tight' tab will spin forever.

<img width="800" alt="screenshot 2017-01-18 10 14 36" src="https://cloud.githubusercontent.com/assets/119884/22076934/03830fce-dd67-11e6-83bf-aa1e5399bac7.png">

**Comment by jaredkerim** [comment]
The problem is that it's not properly reloading the store from localstorage and so it's just re checking the init flags in memory.

**Comment by rlr** [comment]
So far I've been unable to reproduce. I get the hang tight for a sec or two and then the tiles and highlights show up as expected. I've tried on release, dev edition, nightly, with e10s on and off. The addon version I have is `Build: 1.3.0-dev-1485541569-7dacdd1`.

Any other ways to force the condition?

**Comment by rlr** [comment]
After discussing more with @jaredkerim, we realized the issue only happens when you enable multiple content processes (set `dom.ipc.processCount` to 100, for example).

**Comment by jaredkerim** [comment]
This is related to the fact that localstorage is isolated to each content process, so we need to find some way to address that.

**Comment by jaredkerim** [comment]
This is blocked on fixes to localStorage in Nightly

https://bugzilla.mozilla.org/show_bug.cgi?id=1285898

**Comment by jaredkerim** [comment]
The test pilot addon uses localstorage for its state but the system addon does not, so I don't think we'll fix this for the test pilot addon and it shouldn't be an issue in the system addon.
