### ISSUE TITLE
'Can't access dead object' in PageScraper

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#1996]
AS Version: 1.3.0-dev-1484695187

Browser console error:

TypeError: can't access dead object PageScraper.js:114:15
TypeError: can't access dead object  PageScraper.js:167:13

https://github.com/mozilla/activity-stream/blob/master/addon/PageScraper.js#L167

**Comment by rlr** [comment]
I already have a fix for this from looking into the #2102
