### ISSUE TITLE
Mozilla Central replace addon-sdk 

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#1999]
Split from #1990. Addon sdk is a significant amount of overhead and we should get rid of it. Also we can make better use of the things that central gives to us that we would normally access through the sdk (for example ```sdk/windows```). 

- [ ] #2187 Bundle addon code with webpack
- [ ] #2188 Custom bootstrap.js for add-on

**Comment by Mardak** [comment]
Discussion with @mythmon https://public.etherpad-mozilla.org/p/as-sdk of experiences of rewriting shield/normandy
