### ISSUE TITLE
Migrate jpm tests to Firefox testing

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2000]
Split from #1975. It seems unlikely that we'll be able to continue using jpm/jetpack style testing, so the existing unit tests will need some test runner perhaps to mocha/karma/xpcshell?

- [x] #2145 private browsing 
- [x] #2146 places provider
- [x] #2147 search provider
- [x] #2151 about:home page

**Comment by sarracini** [comment]
https://public.etherpad-mozilla.org/p/as-mochitests

**Comment by sarracini** [comment]
This looks done!
