### ISSUE TITLE
Mozilla Central about:home Session Restore Button

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2003]
Split from #1974. The about:home tab has a launcher with the following features: Downloads, Bookmarks, History, Add-ons, Sync, Preferences and Session Restore. Needs UX specs

<img width="663" alt="image" src="https://user-images.githubusercontent.com/438537/29232838-a43daa00-7ea2-11e7-8ece-a4888375e12d.png">

Strings (with plural form):
- Restore {num} tab(s) from your last session

**Comment by AmyYLee** [comment]
There is a bug filed for the session restore button in New Tab https://bugzilla.mozilla.org/show_bug.cgi?id=1352068 along with attached UX specs.

**Comment by andreicristianpetcu** [comment]
so just restore session, no Preferences :( I really like the preferences link in about:home

**Comment by sarracini** [comment]
After chatting with @bryanbell, we're no longer doing the "launcher" that has all those options at the bottom of about:home. We are still doing session restore, so let's repurpose this bug for just the session restore implementation. Bryan said he'll drop some specs in this bug

**Comment by sarracini** [comment]
blocked on us actually taking over about:home - we don't want to show this on about:newtab pages

**Comment by AmyYLee** [comment]
After talking to the rest of the UX team, we decided to omit the restore session button from the New Tab page and instead have it in a more permanent location inside the hamburger menu.

**Comment by Mardak** [comment]
Just making sure, you also meant not having it on about:home? (The session restore button currently only shows up on about:home and not about:newtab).

**Comment by Mardak** [comment]
@bryanbell confirmed that the session restore button won't be on about:home or about:newtab and will be in hamburger.

**Comment by xsistema** [comment]
Is it possible to copy "Restore Previous Session" button to navigation tab?
