### ISSUE TITLE
Mozilla Central about:home search is autofocused

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2007]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1382891
Split from #1974. When opening about:home it auto focuses to the search bar

**Comment by Mardak** [comment]
Blocked on #2598

**Comment by Mardak** [comment]
@bryanbell says the location bar should be focused when opening about:home. Or effectively there should be no difference between opening about:newtab and opening about:home.

**Comment by Mardak** [comment]
So we will be doing this to avoid impacting any existing search metrics.

**Comment by Mardak** [comment]
Looks like we can't use `autofocus` https://github.com/facebook/react/issues/3066

So we'll want to detect visibility to focus but only the first visibility after the latest mount to avoid stealing focus. There's existing `lib` and `components` that individually check visibility, so potentially that can be shared and exported from https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/lib/detect-user-session-start.js

**Comment by Mardak** [comment]
We will be conservative and keep the existing focus-search-in-content behavior. But we will put this behind a pref so that we can experiment via Shield study during Beta 57 to keep focus in location bar.

**Comment by Mardak** [comment]
We will be conservative and keep the existing focus-search-in-content behavior. But we will put this behind a pref so that we can experiment via Shield study during Beta 57 to keep focus in location bar.

The experiment will want to measure total search volume (from location bar, content, etc.) and probably go with the one that has most search.

**Comment by Mardak** [comment]
I suppose we can use this pref name: `browser.newtabpage.activity-stream.aboutHome.autoFocus`

**Comment by rlr** [comment]
0c188ea2a98aeca6e1abe113daa707c066940915
