### ISSUE TITLE
Mozilla Central about:home brand logo

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2008]
Split from #1974. Currently on about:home there is a brand logo of either Firefox / Dev Edition / Nightly. This needs UX specs

**Comment by tspurway** [comment]
let's not do this

**Comment by andreicristianpetcu** [comment]
:( why? @tspurway

**Comment by tspurway** [comment]
@andreicristianpetcu We don't absolutely need this for MVP.  Also,  about:home is becoming an Activity Stream, which is currently unbranded.  This may change in the future, but for now, it seems like a rational decision.

**Comment by andreicristianpetcu** [comment]
I really like the about:home page :(
