### ISSUE TITLE
Mozilla Central about:home tab title

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2010]
Split from #1974. The about:home has a tab title of  "<Brand> Start Page".

**Comment by Mardak** [comment]
Noted in the PR adding strings:
> We'll want to get {build} somehow into some store(?) with the value from https://searchfox.org/mozilla-central/source/browser/extensions/onboarding/content/onboarding.js#19-21

**Comment by Mardak** [comment]
Needs #2598 to load in about:home

**Comment by Mardak** [comment]
@aaronrbenson says it would be fine to just have the about:home title be "New Tab" as there should be no difference from about:newtab.

**Comment by Mardak** [comment]
@bryanbell says there should be no difference.

**Comment by Mardak** [comment]
Strings reverted with https://github.com/mozilla/activity-stream/commit/f1ad570ef5df2cf2434e7e6f01c8bb0c63b621e6
