### ISSUE TITLE
Mozilla Central Snippet blocking

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2017]
Split from #1985. The closed/dismissed snippet needs to be persisted so it won't show up again. There is also logic for some snippets which are not allowed to be dismissed or closed at all

**Comment by glogiotatidis** [comment]
> There is also logic for some snippets which are not allowed to be dismissed or closed at all

Hey Jean (@jkt230) do we need to have snippets that are not allowed to be blocked?

**Comment by jkt230** [comment]
@glogiotatidis For the current about:home, we don't have snippets that are not allowed to be blocked. But in the future with the new Activity Stream look and feel, we may use snippets for rare occasions like security alerts, etc. But even then, we should give users the option to block it. So to answer your question - we do not have snippets that are not allowed to be blocked.

**Comment by glogiotatidis** [comment]
> For the current about:home, we don't have snippets that are not allowed to be blocked.

Yes we do. If you don't check the "Blockable" checkbox people cannot block the snippet. I don't want to hijack this thread which is about AS, so lets get this to email if it's still unclear.

> But even then, we should give users the option to block it

So all snippets will be blockable on AS and therefore we don't need to support unblockable snippets on AS. Correct @jkt230 ?

**Comment by jkt230** [comment]
@glogiotatidis Correct!
