### ISSUE TITLE
RTL CSS

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2023]
Split from #1981. Make sure our CSS works with right-to-left languages. Check label positions, context menus, icon directions, etc.

**Comment by dmose** [comment]
https://github.com/joscha/storybook-addon-i18n-tools might or might not turn out to be worthwhile here.

**Comment by dmose** [comment]
Looks like devtools uses a PostCSS-based tool to make this happen all automagically: https://github.com/devtools-html/debugger.html/blob/master/docs/local-development.md#rtl
