### ISSUE TITLE
Implement restore all for blocked sites

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2026]
Split from #1982. If you block a site in about:newtab you have the option to 'restore all' which unblocks all your blocked sites

**Comment by k88hudson** [comment]
@aaronrbenson do we have designs for this?

**Comment by Mardak** [comment]
@aaronrbenson says there are plans for putting the restore button in the preference pane and not like the tiles' "popup". I suppose keeping design feedback needed for actual design.

**Comment by Mardak** [comment]
Design says "restore all" is less likely a need but "undo" is probably more common. Not for 57.

**Comment by Mardak** [comment]
Not for 57 per design.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432306
