### ISSUE TITLE
Adjust contrast ratio especially for high contrast mode

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2028]
Split from #1978. We need to make sure there's enough contrast between foreground/background text/images/etc. This is especially critical for high contrast mode where sometimes things just disappear because they were too similar and the item becomes the same white or black color.

**Comment by Mardak** [comment]
@yzen, did you consider contrast issue when providing your feedback in https://github.com/mozilla/activity-stream/issues/2874#issuecomment-318425638 ?

**Comment by sarracini** [comment]
I believe this is a dupe #1562
