### ISSUE TITLE
Mozilla Central Newtab Parity keep prefs

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2033]
Split #1982. When updating from about:newtab to activity stream we should keep all the custom prefs from their original about:newtab (like their pinned sites, their blocked sites, etc...)

**Comment by rlr** [comment]
We are using the same pref for pinning so that part is done. Still need to figure out blocking, etc.

**Comment by sarracini** [comment]
Blocking in the system-addon has the same pref as original about:newtab so when we port over the pinning stuff this should be done!

**Comment by sarracini** [comment]
The only thing we have left is rows and that's got it's own ticket #2592. So let's close this one
