### ISSUE TITLE
Create Top Site card based on screenshot + icon 

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2045]
This type of Top Site card is required when we don't have a properly sized high res icon.  The icon is composed of a screenshot of the site with the favicon on the top left corner

**Comment by k88hudson** [comment]
Started PR here: https://github.com/k88hudson/activity-stream/tree/gh2045 needs image sizes to complete

**Comment by rlr** [comment]
landed in 385da1a72e7fd4aa78773be3dda04501ea3b9d19 and 4ce49827566f537f406a5d72d3fc0730cc15ddb5
