### ISSUE TITLE
Decide what to do about history entry / back button

### ISSUE THREAD

**Issue by Mathnerd314** [mozilla/activity-stream#2057]
The [default](https://bugzilla.mozilla.org/show_bug.cgi?id=724239) behavior for about:newtab is to not show up in the browsing history at all, although Alexander Limi [suggested](https://bugzilla.mozilla.org/show_bug.cgi?id=724239#c8) that it should in fact show up for consistency. The history-munging used to be activated by [setting NewTabURL](https://bugzilla.mozilla.org/show_bug.cgi?id=1118285) (as implemented in Activity Stream), but got [hardcoded](https://hg.mozilla.org/mozilla-central/rev/ea4f4e3b0090#l2.6) to about:newtab after e10s as [a short term fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1179058#c5).

Seeing as it's been the subject of multiple discussions and bugs (#812, #2042), I thought somebody might want to consider the behavior afresh for Activity Stream: should it show up in the browsing history?

Reproducing: Windows 10.0 x64; Firefox/52.0a2 20170116004021, Activity Stream 1.2.0: about:newtab doesn't show up in history while Activity Stream does

**Comment by sarracini** [comment]
When we take over about:newtab we won't be able to go back, so we'll just adopt the default behaviour
