### ISSUE TITLE
Tiles from AS New Tab page can be dragged outside the browser window

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2061]
[Affected versions]:
-Firefox 45.0 and up
-Activity Stream Dev 1.3.0-dev-1484867588

[Affected Platforms]:
-All Windows
-All Mac OS X
-All Linux

[Prerequisites]:
-Latest Activity Stream add-on version (1.3.0-dev) was previously installed on a profile.
-Have more history so that the "Highlights" area is populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites, the browser is not on the whole screen.
2. Open a New Tab so that Activity Stream page is displayed.
3. Drag&Drop one of the Highlights tiles outside the browser window.

[Expected result]:
-Tiles cannot be dragged outside the browser window. The tiles can be dragged&dropped only in Firefox browser windows.

[Actual result]:
-The tiles can be dragged outside the browser window and a shortcut will be created where it will be dropped. The name of the shortcut will be the whole text from that tile.

[Notes]:
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiVjVmRmtUYkRFUW8) is a video of the issue.
- In about:newtab, the tiles cannot be dragged&dropped outside the browser window. They can be dragged only in the same or another browser window.

**Comment by sarracini** [comment]
No longer doing work on test pilot version of the addon. closing this

**Comment by Mardak** [comment]
Looks like this still exists on system-addon version

**Comment by Mardak** [comment]
Design says this is standard link dragging behavior from browsers. Tiles was breaking that.
