### ISSUE TITLE
Remove highlight/topsite deduping

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2064]
Presently we remove highlights that come from sites that appear in your top sites.  However this can cause a lot of confusion about behaviours (I bookmarked something, but now it doesn't appear) as well as hiding content that users might find more engaging.  We should experiment with removing this logic and see if it improves engagement in highlights.

**Comment by ncloudioj** [comment]
Prioritize this one as we're looking to implement pinning, drag&drop for Top Sites.

**Comment by jaredkerim** [comment]
Highlights are being deprecated and so this logic will just vanish.
