### ISSUE TITLE
Use screenshots for highlights with no metadata

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2065]
There are times when we may show a highlight without metadata (for instance if it's a bookmark that we want to show because it's a bookmark but it does not have a suitable preview image) should we consider using a screenshot for that image rather than showing no image (ie a big block of colour)

**Comment by bryanbell** [comment]
<img width="870" alt="image" src="https://cloud.githubusercontent.com/assets/228979/23318201/5108278e-fa86-11e6-8729-a0a23b993fa6.png">

**Comment by jaredkerim** [comment]
Here we receive URLs from weighted highlights:

https://github.com/mozilla/activity-stream/blob/master/addon/Feeds/HighlightsFeed.js#L63

We need to slice this array to max 18 elements, then loop over it and look for ones where link.images.length === 0 and for those ones find screenshots the way we do with topsites like this:

 https://github.com/mozilla/activity-stream/blob/master/addon/Feeds/TopSitesFeed.js#L27-L46

**Comment by jaredkerim** [comment]
We also need to make this an experiment so we need to add a new entry to experiments.json, and then only find the screenshots if we're in that experiment.

Call it: `bookmarkScreenshots`

And make this line in the Baseline recommender only occur if we're in that experiment:

https://github.com/mozilla/activity-stream/blob/master/common/recommender/Baseline.js#L112-L114

**Comment by jaredkerim** [comment]
To get the experiment flag in the recommender, you can pull it out of the store in the feed like this:

https://github.com/mozilla/activity-stream/blob/master/addon/Feeds/TopSitesFeed.js#L17


And then pass it into the recommender here:

https://github.com/mozilla/activity-stream/blob/master/addon/Feeds/HighlightsFeed.js#L47

**Comment by bryanbell** [comment]
<img width="862" alt="image" src="https://cloud.githubusercontent.com/assets/228979/24114482/a6dd08de-0d5d-11e7-80b8-4db13cbee506.png">

Still seeing this type of thing.
