### ISSUE TITLE
Long Website URL is not truncated and overlaps with other websites URL and Highlights section title

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2071]
**[Affected versions]:**
-Firefox 45.0 and up
-Activity Stream Pre-release 1.3.0-pre-release-1485308519-0fda037

**[Affected Platforms]:**
-All Windows
-All Mac OS X
-All Linux

**[Prerequisites]:**
-Latest Activity Stream Pre-release add-on version (1.3.0-pre-release) was previously installed on a profile.
-Have more history so that the "Highlights" area is populated with visited websites.
-From about:config, only the "extensions.@activity-streams.experiments.screenshots" experiment is set to true.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Visit a website that has a long URL. (e.g.: https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html , https://moz-activity-streams-prerelease.s3.amazonaws.com/dist/latest.html)
3. Visit the website multiple times so it will reach Top Sites area.
4. Open a New Tab so that Activity Stream page is displayed.
5. Observe the Top Sites area where the visited website is displayed.

**[Expected result]:**
-The website URL is properly truncated and there is no overlapping.

**[Actual result]:**
-The whole URL is displayed, it is not truncated. If there will be another website with a long URL next to it they will overlap each other and also will overlap the Highlights section title.

**[Notes]:**
- On Dev branch we didn't see this behavior.
- Here is a screenshot of the issue.
![long title overlaps highlights](https://cloud.githubusercontent.com/assets/9248513/22291929/8c84ef2c-e311-11e6-91ae-c6618e4d84e3.jpg)

**Comment by rlr** [comment]
oops. should be easy fix.

**Comment by rlr** [comment]
landed fix on master. need to cherry pick onto release branch

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Activity Stream 1.3.0-pre-release-1485356001-8b433f9.
