### ISSUE TITLE
Top Sites screenshots are just a section from the initial screenshot

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2075]
**[Affected versions]:**
-Firefox 45.0 and up
-Activity Stream Pre-release 1.3.0-pre-release-1485308519-0fda037

**[Affected Platforms]:**
-All Windows
-All Mac OS X
-All Linux

**[Prerequisites]:**
-Latest Activity Stream Pre-release add-on version (1.3.0-pre-release) was previously installed on a profile.
-Have more history so that the "Highlights" area is populated with visited websites.
-From about:config, only the "extensions.@activity-streams.experiments.screenshots" experiment is set to true.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Visit multiple website for which there are no high res icons so they will reach Top Sites area.
3. Open a New Tab and observe the screenshots for Top Sites.

**[Expected result]:**
-Screenshots are clearly visible and relevant to the visited website.

**[Actual result]:**
-Initial screenshots are 280x190 px but are truncated to fit the Top Sites screenshot area which is 96x96px. Top Sites images are just a section from the 280x190 px screenshot.

**[Notes]:**
- Here is a screenshot of the issue.
![screenshot truncated](https://cloud.githubusercontent.com/assets/9248513/22296059/cb999572-e321-11e6-96f7-becb2eecaa0f.jpg)

**Comment by sarracini** [comment]
@Softvision-VladBacia I believe this is by design, there's a follow up ticket filed to center it (#2084). Can I close this?

**Comment by Softvision-VladBacia** [comment]
@sarracini , I will close this in favor of #2084
