### ISSUE TITLE
After refreshing the AS New Tab page, "Bookmark" option is available for a previously bookmarked item from "Highlights"

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2077]
**[Affected versions]:**
-Firefox 45.0 and up
-Activity Stream Pre-release 1.3.0-pre-release-1485308519-0fda037

**[Affected Platforms]:**
-All Windows
-All Linux

**[Prerequisites]:**
-Latest Activity Stream Pre-release add-on version (1.3.0-pre-release) was previously installed on a profile.
-Have more history so that the "Highlights" area is populated with visited websites.
-From about:config, only the "extensions.@activity-streams.experiments.screenshots" experiment is set to true.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Hover on a Highlights tile and click on the "..." button. 
3. Click on Bookmark option.
4. Refresh the AS New Tab page.
5. Hover on the previously bookmarked Highlights tile and click on the "..." button. 
6. Click on "Remove Bookmark" option.

[Expected result]:
-Highlights tile is removed from bookmarks. Status is changed to Visited.

**[Actual result]:**
-"Remove Bookmark" option is replace by "Bookmark" after AS New Tab page refresh. Also, the status from Bookmarked is changed into Visited after page refresh.

**[Notes]:**
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiQkh5Rjl4Z0w5eGM) is a video of the issue.

**Comment by rlr** [comment]
I can't seem to reproduce this one either. I bookmark, then I get the "Remove Bookmark" option even after refreshing.

**Comment by emtwo** [comment]
Our unload reason being "refresh" occurs less for less than 4% of sessions:

https://sql.telemetry.mozilla.org/queries/2449/source#4552

**Comment by jaredkerim** [comment]
This is a bug fix for the test pilot version, but is an edge case so I am going to close this as a won't fix.
