### ISSUE TITLE
Top site labels are aligned incorrectly (v 1.3.0-dev-1485385120)

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2080]
![screen shot 2017-01-26 at 9 45 02 am](https://cloud.githubusercontent.com/assets/139451/22339548/f7b478dc-e3af-11e6-866c-853a8fe87fea.png)

**Comment by aaronrbenson** [comment]
Possibly fixed in https://github.com/mozilla/activity-stream/pull/2072

**Comment by Softvision-VladBacia** [comment]
This seems to be similar with #2076 .

**Comment by jaredkerim** [comment]
Closing as a duplicate.
