### ISSUE TITLE
Top Sites don't have existing pinned tiles

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#2081]
We were hoping that by using the Tile's function for fetching Top Sites that we would get pinned tiles for free. So far that doesn't seem to be happening:

Activity Stream with `screenshot` experiment enabled

![image](https://cloud.githubusercontent.com/assets/3095/22339592/58fbb152-e39f-11e6-9aec-451d6370bb50.png)

Tiles

![image](https://cloud.githubusercontent.com/assets/3095/22339609/6d4166ac-e39f-11e6-8e1f-5267bfbd1603.png)

**Comment by nchapman** [comment]
I did get this to work by enabling the `originalNewTabSites` experiment:
<img width="783" alt="image" src="https://cloud.githubusercontent.com/assets/3095/22340200/70340c5a-e3a1-11e6-83f5-7abd38496f5d.png">

It took restarted and reloads which isn't good, but it does work and includes pinned tiles! We need to use this same function in the `screenshots` experiment.

**Comment by rlr** [comment]
Per @nchapman on IRC, we are going to use the tiles used in the `originalNewTabSites` experiment for the `screenshots` experiment too.

On it.
