### ISSUE TITLE
Large icons in Top Sites should fill the box entirely

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#2083]
Sites that have large icons should go edge to edge rather than having a gutter and background. Right now they appear to be treated like Tippy Top Sites (which look great and are using the right behavior).

<img width="489" alt="image" src="https://cloud.githubusercontent.com/assets/3095/22341678/94652b90-e3a6-11e6-8220-fdefd74185b7.png">

<img width="495" alt="image" src="https://cloud.githubusercontent.com/assets/3095/22341683/9c0c9662-e3a6-11e6-8e87-c81e337d7acc.png">

**Comment by rlr** [comment]
pull #2089 makes it look like this (for my small sampling of sites):

<img width="754" alt="screen shot 2017-01-26 at 3 01 28 pm" src="https://cloud.githubusercontent.com/assets/36629/22348159/b35fe51c-e3d8-11e6-8163-be03101bbba1.png">

**Comment by pdehaan** [comment]
Curious, why doesn't the HackerNews (ycombinator) icon look full sized?

**Comment by nchapman** [comment]
@pdehaan I think that Hacker News icon is coming from Tippy Top which are centered like that. I hear they have a large icon now so we can probably remove that from the list. It would be a bad idea for us to audit the tippy top list and kick out all the icons where the site returns a good apple touch icon now that we're using those.

**Comment by bryanbell** [comment]
ycombinator is a tippy top icon... maybe we should remove that.

**Comment by rlr** [comment]
After a vidyo chat with @bryanbell and @k88hudson, we decided that tippy tops are the only icons that will have the background/border. All other icons will be stretched or shrinked to 96x96 unless they have a screenshot.
