### ISSUE TITLE
Top sites grey border should remain when context menu is open

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2092]
When clicking the context menu of any item, the grey border should persist.

I made a video: https://cl.ly/2l2B171T0i45

**Comment by Softvision-VladBacia** [comment]
This issue is also reproducible in Activity Stream Pre-release v1.3.0-pre-release-1485468410-8683703

**Comment by Softvision-VladBacia** [comment]
This is a duplicate of #1154 .

**Comment by sarracini** [comment]
Closing this in favour of tracking it in #1154
