### ISSUE TITLE
Low res images are displayed for Top Sites if AS was installed on a profile with existing history

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2093]
**[Affected versions]:**
-Firefox 45.0 and up
-Activity Stream Pre-release 1.3.0-pre-release-1485468410-8683703

**[Affected Platforms]:**
-All Windows
-All Mac OS X
-All Linux

**[Prerequisites]:**
-Have more history so that the "Top Sites" area is populated with visited websites.
-Latest Activity Stream Pre-release add-on version (1.3.0-pre-release) was previously installed on a profile.
-From about:config, only the "extensions.@activity-streams.experiments.screenshots" experiment is set to true.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open AS New Tab page.
3. Observe Top Sites cards.

**[Expected result]:**
-Top Sites cards have a high res image and are displayed inside the tile.

**[Actual result]:**
-Top Sites cards have a low res image and for the ones that have site-icon-fallback the image is bigger than the tile.
 
**[Notes]:**
- Here is a screenshot with the issue:
![low res icons and favicon is bigger than the top sites card](https://cloud.githubusercontent.com/assets/9248513/22368411/062b9f50-e48f-11e6-8877-63d80c948861.jpg)

**Comment by jaredkerim** [comment]
This is behaving as designed for now.  Backlogging.

**Comment by sarracini** [comment]
Let's close this, as this is a test pilot issue, and we're going to re-evaluate our method for collecting and storing rich icons for the system addon version
