### ISSUE TITLE
Bookmarks are missing metadata for what seems like a very long time

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#2094]
STR

1. Create bookmarks on my iMac
2. See nice metadata. Yay!
3. Use Windows machine
4. See synced bookmarks but no metadata
5. Wait for time to pass... (15 minutes) ... still no images.

Screenshot from Windows

![image](https://cloud.githubusercontent.com/assets/3095/22376322/64f2b9e2-e462-11e6-9660-b62d2638d4af.png)

Screenshot from iMac (not exactly the same but close)

![image](https://cloud.githubusercontent.com/assets/3095/22376398/a12c59d6-e462-11e6-92f6-e6528658b585.png)

**Comment by nchapman** [comment]
Seeing the same thing on my Macbook which is also synced: 

<img width="774" alt="image" src="https://cloud.githubusercontent.com/assets/3095/22382411/706f268a-e47a-11e6-9110-9af2d1a9acfc.png">

**Comment by jaredkerim** [comment]
This is a duplicate of #1969
