### ISSUE TITLE
Top Sites are a wreck in narrow windows

### ISSUE THREAD

**Issue by nchapman** [mozilla/activity-stream#2095]
![image](https://cloud.githubusercontent.com/assets/3095/22377970/a2db92b4-e468-11e6-8f0c-4def4af1e852.png)

**STR**

1. Resize the window so that it's narrower than the width of the 6 top sites.

**Expected Result**

Icons should stay aligned in a grid.

**Comment by Softvision-VladBacia** [comment]
I've noticed that this issue is happening with Top Sites cards that do not have a screenshot. The Top Sites cards that have screenshots stay aligned and the others don't.

**Comment by pdehaan** [comment]
Unrelated, but that favicon action for "smile.amazon.com" looks pretty poor.
We may need to try [tweaking that in tippy-top-sites](https://github.com/mozilla/tippy-top-sites/blob/b5d290159ad43cf1f7db0bdd95d66cef952c2f3e/top_sites.json#L60) for the "smile." subdomain.

**Comment by Softvision-VladBacia** [comment]
The issue is no longer reproducible on the latest Activity Stream 1.4.0-pre-release-1486067840-083a326 .
