### ISSUE TITLE
Add the bookmarks toolbar to the page when the bookmark toolbar is disabled

### ISSUE THREAD

**Issue by samueljun** [mozilla/activity-stream#2111]
I would love to see the bookmark toolbar in the new tab page (a la Chrome) to save on vertical space. If you disable the bookmark toolbar on chrome, the bookmark toolbar is displayed on the new tab page instead.

![screenshot from 2017-02-01 01-32-19](https://cloud.githubusercontent.com/assets/1808588/22501658/9a56ca3c-e81e-11e6-98fc-d8d896c959fa.png)
![screenshot from 2017-02-01 01-32-21](https://cloud.githubusercontent.com/assets/1808588/22501657/9a55cc90-e81e-11e6-88bd-c90ac24578da.png)

Vertical real estate is at a premium and I along with many other keep the bookmark toolbar disabled. I went so far as to create [a Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/new-tab-bookmarks/) to pseudo-display my bookmarks on the new tab page. Since the activity stream is meant to be the new tab page in FF 56, I would love to this feature included on the roadmap!

Also here is a filed bugzilla report from 2012: https://bugzilla.mozilla.org/show_bug.cgi?id=727668

**Comment by tspurway** [comment]
We are adding a Recent Bookmarks section, which should address some of this.  Thanks for commenting @samueljun

**Comment by samueljun** [comment]
I would still like to see the feature that is on parity because of the fact that I organize and group my bookmarks on the bar in a specific fashion, especially with folders as well. 

From the name it sounds like I would not be able to manually organize a Recent Bookmarks section nor see/open my folders. One of the main draws for bookmarks is being able to organize, group, and sort them however you like. The Recent Bookmarks section sounds like it'll be organized based on most-recently-used or most-recently-added. Neither of those sounds like the Recent Bookmarks section will be organized predictably between session or even between visits to the new tab page. 

That being said, I realize this is just a feature request and not everything can make the cut. I can simply keep my bookmark bar enabled (at the loss of vertical real estate) or continue to use the extension I created. I just want to throw my case out there in the hopes that this feature would eventually picked up.
