### ISSUE TITLE
Explicitly assign control groups to experiments in ExperimentProvider

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2118]
Right now control groups are not assigned to be the 'control' group of any given experiment, which means that there is no group of users which stays in control for the duration of any given experiment.  This makes it difficult to test things like retention because a given control user could be assigned to an experiment at any time, particularly when an addon update is pushed out.  It makes it very difficult to analyze the success of certain experiments.

**Comment by emtwo** [comment]
We can still carry on experiments without this for now, so lowering priority

**Comment by sarracini** [comment]
@emtwo says we can close this since the way we're doing experiments no longer requires this :D
