### ISSUE TITLE
Get Mochitests running for each a-s github commit/PR/merge

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2126]
This could be as simple as doing a push-to-try for each commit that shows up on a relevant PR, or else having a named branch off of mozilla-central and pushing to that.  I'll be talking to a-team folks to see what the preferred solution is.

**Comment by Mardak** [comment]
Some notes of manual steps from running the script on my own account:

* first run build artifact build confirming yes
* add mk_add_options AUTOCLOBBER=1 in mozconfig
* add pine as a hg remote in hgrc
* add ui email/username in hgrc
* add user/StrictHostKeyChecking no for hg.mozilla.org in .ssh/config
* edit +const OLDEST_PR_DATE = "2017-02-20";

Other than actually setting up a cronjob, the changes at https://github.com/dmose/activity-stream/tree/export-merges seem to be working as per https://github.com/mozilla/activity-stream/pull/2195#issuecomment-282814242

**Comment by dmose** [comment]
Resolved by #2198.
