### ISSUE TITLE
List and break down key functional tests to write before landing.

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2127]
We want to have a minimal set of mochitests running when we land in tree so that if/when key toolkit/platform APIs change out from under us, the tree breaks if the A-S code is not patched at the same time.

**Comment by sarracini** [comment]
https://public.etherpad-mozilla.org/p/as-mc-failures

**Comment by Mardak** [comment]
These tests will be implemented as part of #2880:

test search box appears
test top sites section appears when that section is on
test top sites section doesn't appear when that section is off

Other tests probably useful:
click interaction on various elements including pref pane
sections gets populated with dummy data including top sites, recommendations
