### ISSUE TITLE
Determine dir of html

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2136]
Firefox probably has a way to check if the locale being used is an RTL or LTR language

**Comment by Mardak** [comment]
Loop used a vendor `l10n.js` that came from `pdf.js` that provided a `language.direction` "rtl" vs 'ltr" value:
https://github.com/mozilla/loop/blob/616b1e9c2dd844a6068cd194ac6d17d771241981/add-on/panels/vendor/l10n.js#L239-L243

At least initially, we might be able to just copy the function above.
