### ISSUE TITLE
Proxy bandwidth friendly assets?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#214]
I'm noticing that even with my local version and the embedly proxy, sometimes my new tab page takes 5-8 seconds to load.

Currently it seems like we make 3 requests to the embedly-proxy which (in my case) have 7, 7, and 9 results each. The responses are 16KB, 16KB, and 28KB (~60KB total -- but we should already have 1-2 issues on returning a subset of keys or whatever).

I also notice that a lot of the returned favicons are ridiculously large file sizes (or small, blurry images). For example,

### favicon.ico

| SITE | WxH | SIZE |
|----|----:|----:|
| twitter.com | 32px | 6.37KB
| hbo.com | 32px | 1.54KB
| netflix.com | 256px | 23.74KB
| bing.com | 16px | 1.12KB
| people.mozilla.org | 16px | 2.49KB
| sho.com | 64px | 21.86KB
| **TOTAL** | | ~56KB

Things start going sideways really quickly when we blindly load the "optimal" images for the Spotlight sites though. I'm surfing some pretty high-brow sites, but their assets are HUUUGE (and then scaled to thumbnails client side).

### `images[0].url`

| SITE | WxH | SIZE |
|----|----:|----:|
| sho.com | 1536x960px | 850KB
| hbo.com | 1920x1080px | 640KB
| netflix.com | 2000x1125px | 93KB
| **TOTAL** | | ~1583KB

So even though the images are all super-high-res, we scale them down to ~212x124px. Not sure if it's worth trying to write our own proxy and image processor which grabs the optimal image from Embed.ly proxy and resizes it down to something closer to 212x124px and stores it in S3 or something.

I can imagine trying to load all these assets over slow wifi where bandwidth is a bit more expensive could be terribly annoying if loading each New Tab page takes 20s and costs you $0.11 in bandwidth.

**Comment by jaredkerim** [comment]
Performance issues around the embedly proxy are not related to the sizing of content but rather to the intricacies of distributed system design and have now been remedied been improved.  Rescaling high res images in the proxy will not be implemented.  It is possible we may rescale high res images for storage and display in activity stream when we implement the locally processed version, however that remains to be seen.
