### ISSUE TITLE
Handle multiple content processes

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2157]
in Firefox 54, multiple content processes (N > 1) will roll out to all users.  In this scenario, there may be consistency issues between the content of localstorage in each content process, as described in this bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1285898

In that scenario, we need to make sure that we handle the case gracefully rather than winding up in an inconsistent state.

**Comment by jaredkerim** [comment]
In which case we will remove the following:

https://github.com/mozilla/activity-stream/blob/master/dev-prefs.json#L2

**Comment by k88hudson** [comment]
This is resolved in the system add-on with the Message Channel (landing in nightly in https://bugzilla.mozilla.org/show_bug.cgi?id=1350411)
