### ISSUE TITLE
Non-en-US strings show up as ids (except first time after first load)

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2158]
Testing with latest `master` https://github.com/mozilla/activity-stream/commit/cc373b92103f3fe0047759a31514c0e8139070da  with a nightly "it" build: https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/firefox-54.0a1.it.mac.dmg

On first load, string ids are shown for about a second before they switch to the Italian version. All subsequent openings of new tab show the string id.

![screen shot 2017-02-09 at 9 26 34 pm](https://cloud.githubusercontent.com/assets/438537/22815265/28292ca0-ef0f-11e6-8265-6cc4fd625529.png)

This seems to be the same behavior when setting `general.useragent.locale` to "it" from about:config in an en-US build. (Where all strings show up as the id as "first load" happened already with english strings.)

@k88hudson @sarracini

**Comment by sarracini** [comment]
Hmm I can reproduce this too and my console throws these errors
![errors](https://cloud.githubusercontent.com/assets/7219526/22829701/da142746-ef71-11e6-8b8c-76b92cb3e190.png)
:

**Comment by k88hudson** [comment]
Ok, this should be fixed now! Test incoming

**Comment by Mardak** [comment]
Fixed by #2159. @flodolo Verified with screenshot (testing "it" Firefox then switched to "zh-TW" `useragent.locale`):
![localized](https://cloud.githubusercontent.com/assets/438537/22838017/f8b0de50-ef77-11e6-908f-eec9c790ffe4.png)

**Comment by flodolo** [comment]
Confirmed, it works fine now.

**Comment by Mardak** [comment]
Also tested en-US fallback with a partially translated localization (Serbian sr 68%):
![partial-localized](https://cloud.githubusercontent.com/assets/438537/22838780/7f8636b6-ef7b-11e6-8aab-6a47a788221c.png)
