### ISSUE TITLE
Land Metadata Parser in Mozilla Central

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2163]
We should open a PR to have the Fathom Metadata parser 

https://github.com/mozilla/page-metadata-parser

land in Mozilla Central.  The reason to do this now, outside of the effort to land the entire addon are 

1) Leverage additional support from outside our team to help with the review landing process for just this code

2) Leverage external efforts to integrate rich metadata into the places db which are currently taking place

The ultimate goal of this is to deal with passing the parser through review so that when the addon is up for review, the parser component will have already passed review.  

This does not block us from using a more recent version of the parser inside the addon when it lands as a system addon.

This may afford us the opportunity in the future to deprecate certain metadata processing and storage responsibilities inside the addon and fall back to browser provided mechanisms, but there is no requirement for this to be the case.

**Comment by jaredkerim** [comment]
Bugzilla reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1343991

**Comment by sarracini** [comment]
#2354 Will be used to track what parts of the parser land in central
