### ISSUE TITLE
Invalid "value" in the performance ping

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2166]
Infernyx was reporting an invalid performance ping for event "countMetadataURLs". See attached payload for more details.

```
{
  "addon_version":"1.4.0",
  "date":"2017-02-10",
  "experiment_id":"foo_01",
  "event_id":"{f520de98-fb9e-45bc-944a-06cbefb503dd}",
  "value":[0],
  "page":"NEW_TAB",
  "source":"PLACES_STATS_FEED",
  "session_id":"{c2cabd42-6aea-47b1-aafa-160821b59a8c}",
  "client_id":"e921a4e5-ff36-40fa-a37d-2831d63ff978",
  "timestamp":1486705101364,
  "action":"activity_stream_performance",
  "tab_id":"-3-37",
  "locale":"en-US",
  "ua":"Mozilla\/5.0 (X11; Linux x86_64; rv:46.0) Gecko\/20100101 Firefox\/46.0",
  "event":"countMetadataURLs"
}
```

**Comment by jaredkerim** [comment]
@ncloudioj How many of these are we seeing?

**Comment by ncloudioj** [comment]
This happens quite often, I've talked to @sarracini about this, I think she has some ideas about what's going on behind.

**Comment by jaredkerim** [comment]
@ncloudioj What percent of all pings with events:

countMetadataURLs
countHistoryURLs

are invalid on each date?  How many valid ones did we receive yesterday and how many invalid ones did we receive yesterday?

**Comment by ncloudioj** [comment]
@jaredkerim This issue appears to be happening in the stage only, take yesterday's data for example (2017-02-16),

There are 77 pings of the event `countMetadataURLs`, 76 of them have the `value: [0]`. I suspect that those pings might be generated by the old version of the addon, like running in the test env.

Feel free to close this issue if you couldn't find anything suspicious.

**Comment by jaredkerim** [comment]
We had this issue in a much earlier build of the addon and fixed it, I can see valid data in the production db so my inclination is that this issue no longer exists in dev.
