### ISSUE TITLE
Top Sites: iCloud doesn't have a border 

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2168]
![screen shot 2017-02-13 at 2 23 45 pm](https://cloud.githubusercontent.com/assets/139451/22901679/183b2438-f1f8-11e6-9ec1-c163b183b212.png)

There should be a border around the iCloud top site, much like the Amazon tile.

**Comment by rlr** [comment]
There is a difference in that the amazon is a tippy top image+background color (white) so we know to put a border around it given the light ("almost white") background color. The icloud one is just an image and we don't really know about it's colors. So we could put a border around all image icons or none, and we decided on none for now. We can revisit that decision though. cc: @bryanbell

**Comment by aaronrbenson** [comment]
Conferred with @bryanbell and decided it would be better to put a tinted border on all the icons. Otherwise it looks like a bug if some icons get a border and others don't (in this case iCloud vs. Amazon).

Following this rule: 
![screen shot 2017-02-14 at 9 57 36 am](https://cloud.githubusercontent.com/assets/139451/22936770/1b166a1a-f29c-11e6-9ba0-0c86ba851937.png)

**Comment by aaronrbenson** [comment]
Oops, @rlr can we do the opposite and remove the border on all icons instead?

**Comment by rlr** [comment]
@aaronrbenson sure. either way :smile:

**Comment by aaronrbenson** [comment]
Okay cool, lets remove it then. @bryanbell and I gave it another pass and it looks cleaner without especially in the case where favicons stretch to the edges of the container.

**Comment by aaronrbenson** [comment]
I think we need to revisit this ... Bryan found a case where a favicon is a square and doesn't fill the available space which makes the top sites appear they are different sizes. 

@bryanbell will you chime in on what the rule should be? Borders for all top sites? Borders for only Tippy Top sites?

  
![screen shot 2017-02-21 at 1 01 40 pm](https://cloud.githubusercontent.com/assets/139451/23180119/e8abe8d0-f835-11e6-9ebc-fdd93219d00f.png)

**Comment by rlr** [comment]
After chat with @bryanbell, we decided to make tippy top icons 80x80px and we'll give them (and only them) a border.
