### ISSUE TITLE
Properly disable experiments for SHIELD variants

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2181]
we should set all the control values for active experiments to their control value for shield study, similar to how we do it for the disable active experiment pref ```activateExperiments```. We should pass in a ```disable``` parameter into experiment provider's init and then call the ```disableAllExperiments``` if that parameter is true.

**Comment by jaredkerim** [comment]
If this gets pushed out then we need to only use 'false' default control values in our experiments.

**Comment by jaredkerim** [comment]
I'm going to promote this to P1 to figure out if we need it for the upcoming shield study or if it's just a nice to have in which case I think we will close it.
