### ISSUE TITLE
tie our telemetry pref into the main firefox pref

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2183]
Right now, if someone goes into the Firefox preferences page, Advanced -> Data Choices, and sets "Share Additional Data" (tied to the toolkit.telemetry.enabled pref) to off, A-S will continue to send telemetry.  

Our code should respect toolkit.telemetry.enabled, possibly even getting rid of our own local telemetry pref, though I'm not sure about that.

**Comment by Mardak** [comment]
Maybe fixed by #3095 ?
