### ISSUE TITLE
Missing glyph-showmore-16.svg

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2189]
https://github.com/mozilla/activity-stream/commit/e30f699 removed the file with some CSS cleanup but there was another CSS style `.icon-arrow` using the file:

https://github.com/mozilla/activity-stream/blob/f3200da627b89e780f8de7ad09f392218dba3cde/content-src/styles/icons.scss#L18-L19

This showed up in a mozilla-central mochitest:
 TEST-UNEXPECTED-FAIL | browser/base/content/test/general/browser_parsable_css.js | missing jar:file:///home/worker/workspace/build/application/firefox/browser/features/@activity-streams.xpi!/data/content/img/glyph-showmore-16.svg referenced from jar:file:///home/worker/workspace/build/application/firefox/browser/features/@activity-streams.xpi!/data/content/main.css - 

Can this style rule be removed?

@sarracini

**Comment by sarracini** [comment]
@Mardak yep it doesn't look like it's being used anywhere so we can remove it
