### ISSUE TITLE
Activity Stream home is broken in Container tabs

### ISSUE THREAD

**Issue by groovecoder** [mozilla/activity-stream#2193]
Couple of issues ...

[When a user installs Containers and Activity Stream experiments together, and then opens a new container tab, we were showing the regular `about:newtab` page instead of activity stream page](https://github.com/mozilla/testpilot-containers/issues/246)

But when [we fixed the container tab home to be the activity stream page](https://github.com/mozilla/testpilot-containers/pull/254), the activity stream page is very broken.

<img width="1440" alt="txp-container-tab-activity-stream" src="https://cloud.githubusercontent.com/assets/71928/23311227/355ae57e-fa6a-11e6-8dd4-ac1ed2df10c3.png">

For now, [we are warning users that activity stream doesn't work inside container tabs](https://github.com/mozilla/testpilot/pull/2227), but we need to collaborate on a longer-term fix.

**Comment by sarracini** [comment]
This is an issue with local storage as mentioned in here: https://github.com/mozilla/activity-stream/issues/1389#issuecomment-273936286

**Comment by jaredkerim** [comment]
Closing this as a duplicate.
