### ISSUE TITLE
The Search Suggestions for the second written word in A-S Search bar are wrongly displayed

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2200]
**[Affected versions]:**
-Firefox 51.0.1
-Activity Stream 1.6.0-pre-release-1487703855-3df7287

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Activity Stream pre-release add-on version (1.6.0-pre-release) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and write something in the AS search bar.
3. Observe the Search Suggestions drop-down.
4. Click on "->" Search button.
5. After the Search is performed, click on "Back' button from the browser.
6. Write another word in the A-S search bar and observe the  Search Suggestions drop-down.

**[Expected results]:**
- Search suggestions are displayed according to the last word written.

**[Actual results]:**
- Search suggestions are kept from the first searched word.

![search suggestions](https://cloud.githubusercontent.com/assets/9248513/23517650/aa288fd2-ff79-11e6-97f3-8c52ebc6fe78.gif)

**Comment by sarracini** [comment]
Closing this since we won't be able to navigate back to about:newtab shortly
