### ISSUE TITLE
Disable Feeds when section pref'd off

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#2203]
This is a followup from #1984 

Now we allow users to turn off Top Sites and Highlights. But the Feeds for them keep on doing background work regardless. We should have Feeds stop refreshing if their corresponding section is disabled by the user.

One thing we should make sure works is when a user has Highlights, for example, disabled. Goes to the New Tab page, enables Highlights on the Preferences Pane. Hopefully, we show something in Highlights section when they close the pane even if it isn't the latest. Or maybe we need to show the loader and wait?

**Comment by nchapman** [comment]
I think there are probably quite a few design decisions that will come out of this. Can we hold off on this for now and come back to it?

**Comment by rlr** [comment]
@nchapman yep. I don't think I was going to get to it this round anyway. I'll push to next sprint and unassign to make sure we bring it up next time.

**Comment by jaredkerim** [comment]
This is an optimization for the test pilot version that I think we can live without, and when we implement sections for the system addon we can revisit this from a new approach and probably file a new ticket for it, I'm going to close this for now.
