### ISSUE TITLE
Search textbox is not autofilled with the clicked word from the Search drop-down menu

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2206]
**[Affected versions]:**
-Firefox 51.0.1
-Activity Stream 1.6.0-pre-release-1487703855-3df7287

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Activity Stream pre-release add-on version (1.6.0-pre-release) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and write something in the AS search bar.
3. Click on a suggestion from the Search Suggestions drop-down.
4. Observe the word/s from the Search bar.
5. After the Search is performed, click on "Back' button from the browser.
6. Observe the word/s from the Search bar.

**[Expected results]:**
4. Search textbox is autofilled with the clicked word from the Search drop-down menu and a search is automatically performed.
6. The clicked word/s from the Search Suggestions drop-down list is displayed in Search textbox.

**[Actual results]:**
6. The manually written text is displayed in the Search textbox and not the selected one.

**[Notes]:**
- If the word is selected from the keyboard then the Search textbox is autofilled with the selected word.

![search autofill](https://cloud.githubusercontent.com/assets/9248513/23553813/0e808776-002b-11e7-9cad-fcc7046d1e7b.gif)

**Comment by sarracini** [comment]
Closing this as a won't fix for test pilot - the system addon version doesn't let you go back from a newtab
