### ISSUE TITLE
Inconsisten behaviour when clicking on "Change Search Settings" button from the Search Suggestions drop-down

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2207]
**[Affected versions]:**
-Firefox 51.0.1
-Activity Stream 1.6.0-pre-release-1487703855-3df7287

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Activity Stream pre-release add-on version (1.6.0-pre-release) was previously installed on a clean profile.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and write something in the AS search bar.
3. Click on "Change Search Settings" button from the Search Suggestions drop-down.
4. Click on "Back' button from the browser.
5. Write something in the A-S Search bar and click again on "Change Search Settings" button.

**[Expected results]:**
- The behavior should be consistent. `about:preferences#search` page should be opened in the same tab as A-S New Tab page or in a new tab.

**[Actual results]:**
- After opening a new A-S New Tab and navigating the 1st time to `about:preferences#search` from the Search Suggestions drop-down, the  `about:preferences#search` page is opened in the same tab. After clicking on "Back" browser button and performing the same steps the `about:preferences#search` page is opened in a new tab.

**[Notes]:**
- don't know what is the best behavior but if changes are made to  `about:preferences#search` page, they will be available in A-S New Tab page after opening a new tab.

![search settings](https://cloud.githubusercontent.com/assets/9248513/23555150/74bef914-0030-11e7-940c-c5019b624405.gif)

**Comment by sarracini** [comment]
This is not reproducible in the system addon version, closing this as a won't fix in the test pilot version
