### ISSUE TITLE
Collect screenshots experiment data

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#2210]
Including:
* Number of screenshots shown in a session
* Whether a clicked topsite had a screenshot (I believe we have this already, but need to confirm)

**Comment by jaredkerim** [comment]
We also need to add metrics to show which things we're showing during a session

    number of tippy top sites
    number of high res icons
    number of low res icons
    number of screenshots
    number of TLD top sites
    number of non-TLD top sites
