### ISSUE TITLE
(Bugzilla 1344372): Add ability to customize RemotePageManager for AboutNewTab if Activity Stream is enabled

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2215]
Because we will need to add our own listeners / logic for handling messages from the new tab in Activity Stream, we will need to instantiate our own RemotePageManager or override the existing one.

This blocks replacing PageMod

See https://bugzilla.mozilla.org/show_bug.cgi?id=1344372

**Comment by jaredkerim** [comment]
'This is done!' - Ursula
