### ISSUE TITLE
Links in the Top Sites portion of Activity Stream sometimes are not correctly calculated

### ISSUE THREAD

**Issue by weaversam8** [mozilla/activity-stream#2228]
Running Firefox Developer Edition (Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0)

On the Activity Stream new tab page, the Top Sites section lists some sites I visit regularly. That includes Hacker News (https://news.ycombinator.com). This might be a bit of a difficult bug to reproduce, but the link on the Activity Stream page is listed as **https://www.news.ycombinator.com**. The www portion seems to be added erroneously.

Would this happen to be because HN is my home page?

**Comment by Softvision-VladBacia** [comment]
@weaversam8, thank you for reporting this. Please, can you give me a little more info?

A-S version and from where it was installed
Screenshot of the issue

**Comment by weaversam8** [comment]
I've been away from my machine today, but I can at least confirm that it was installed officially from the test pilot extension/website, not through a custom build. 

Where can I check the version?

**Comment by nchapman** [comment]
I have this same issue on `1.7.0-dev-1489161278-f46f8b9`:

<img width="356" alt="image" src="https://cloud.githubusercontent.com/assets/3095/23869256/8764592c-07df-11e7-837b-28aeaa791820.png">

These are technically not the same URL as `www.news.ycombinator.com` doesn't redirect to the correct page.

I'm guessing that this is related to how we're deduping and combining frecency. We're likely combining them by using a substring match and ignoring `www`. We should either do something more sophisticated (like make sure they're the same URL) or at the very least use the combined item with the highest visit count (don't know if it's SQL but something like... `GROUP BY MAX(visit_count)`).

**Comment by weaversam8** [comment]
@nchapman thanks for that screenshot. It had slipped my mind to reply to this ticket. 

Is the site in question your homepage as well? I've seen sub domains work properly on this page before.
