### ISSUE TITLE
Enable eslint for system-addon/

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2229]
Right now we don't have eslint targeting `.jsm`s. There are a few issues we would need to sort out (like `no-unused-vars` conflicting with jsm-style exports, for example) to get this to work

**Comment by k88hudson** [comment]
This is one possible solution: https://github.com/mozilla/activity-stream/compare/master...k88hudson:gh2229

**Comment by dmose** [comment]
In general seems like a reasonable start.

I'd suggest bootstrapping the magic globals instead of allowing them arbitarily, like Hello did: https://github.com/mozilla/loop/blob/master/add-on/chrome/.eslintrc .

Other interesting things to read could include the master eslintrc from dxr: https://github.com/mozilla/loop/blob/master/add-on/chrome/.eslintrc as well as the various devtools ones.

**Comment by k88hudson** [comment]
@rhelmer mentioned he was about to land a patch for some specific rules for `browser/extensions/`, so we'll want to make sure we're compatible with those as well

**Comment by rhelmer** [comment]
@k88hudson`./browser/.eslintrc.js` extends `./toolkit/.eslintrc.js` which already has some generic JSM-specific rules, you could probably steal from that or maybe automatically import https://hg.mozilla.org/mozilla-central/raw-file/tip/toolkit/.eslintrc.js into your repo somehow and use `"extends"` in the Activity Stream `.eslintrc.js`.

I was thinking about starting to ratchet up the rules in `./browser/extensions` although ideally I'd like to just keep making `./toolkit/.eslintrc.js` better which will improve all the front-end code in Firefox.

@Standard8 has been pushing this stone up the hill for a while and make have some thoughts on how to keep things like eslint rules in sync for projects developed out-of-the-tree like Activity Stream.

**Comment by Standard8** [comment]
The best way to do this is probably via [eslint-plugin-mozilla](https://www.npmjs.com/package/eslint-plugin-mozilla), however there's some issues with being able to include that currently, as it relies on files directly in m-c locations.

I've got some thoughts on how to fix that, that I'll hopefully be starting on this week. How soon do you need this?

It'll also be likely that we'll use it to publish a recommended set of rules.

**Comment by Standard8** [comment]
FYI, I filed [bug 1347645](https://bugzilla.mozilla.org/show_bug.cgi?id=1347645) to deal with the improvements to eslint-plugin-mozilla.

**Comment by Mardak** [comment]
I'll merge #2297 first and create a followup PR that switches to new fancy `extends: "plugin:mozilla/recommended"` and removing duplicate rules.

**Comment by Mardak** [comment]
@Standard8 is there a good way for me to develop against `eslint-plugin-mozilla@0.2.32` before it's available via `npm`? I suppose I can at least just look at the list of `recommended` rules and start culling our list.

**Comment by Mardak** [comment]
With #2384, eslint is passing, so let's close this for now and track #2304 separately.
