### ISSUE TITLE
Close ActivityStream:Newtab component and ActivityStream:Timeline component in bugzilla

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2230]
We no longer need these components since ActivityStream:General is the only bugzilla component needed.

**Comment by k88hudson** [comment]
@tspurway could you help get those components closed/removed?

**Comment by Mardak** [comment]
We chose to keep Newtab and Application Servers https://bugzilla.mozilla.org/show_bug.cgi?id=1383153
