### ISSUE TITLE
Monitor new tab preferences interactions with telemetry events

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2233]
We need to make sure that interactions with the new tab Prefs pane is monitored with telemetry so we can understand how users are interacting with it:

https://github.com/mozilla/activity-stream/issues/1984

**Comment by rlr** [comment]
When a user changes a pref, we fire a user event. Not sure if this is telemetry or just or own ping centre, but I thought I'd point that out: https://github.com/mozilla/activity-stream/blob/master/addon/PrefsProvider.js#L34

**Comment by jaredkerim** [comment]
Let's add click events for

1) Clicking on the pref gear
2) Clicking on the 'done' button
