### ISSUE TITLE
Document use cases for addon (for QA signoffs)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#224]
We need to come up with a solid list of manual tests that we perform when signing off on an addon.
For example:

1. A new user with an empty profile. (also a user who has browsing history and deletes it regularly.)
2. A weekend warrior that uses a browser 1-2x a week and has very sparse browsing data (with long gaps).
3. A power user with a vast history and hundreds of results (stress testing pagination).

Not sure the best way to test these. Usually I just run `$ npm run once` and then click on a dozen or so links, but that doesn't cover a lot of cases.
I don't know if we can have various different stub data scripts which populate different browsing scenarios so we can manually test without each needing to maintain several different profiles.

**Comment by jaredkerim** [comment]
Outside of the scope of activity stream github issues.
