### ISSUE TITLE
New tab never gets past "Welcome to new tab" dialog

### ISSUE THREAD

**Issue by nicklan** [mozilla/activity-stream#2272]
After installing activity-stream, I opened a new tab, and it just sits with the "Welcome to new tab" dialog up and spinning circle saying "Identifying your Highlights" forever (well, it's been about an hour now).  Each new tab does the same thing.  No errors in JS console.

**Comment by ncloudioj** [comment]
Thanks for reporting this issue! @nicklan 

Could you provide more details for us to investigate the issue? For instance, the Firefox version, the addon version (you can get it from "about:addons"), and OS etc.

**Comment by nicklan** [comment]
Sure:

- Firefox 52.0 (64-bit)
- Activity Stream 1.6.0 (installed from test pilot)
- OS: Linux 4.10.3

Let me know if you need any other info

**Comment by ncloudioj** [comment]
@nicklan Thanks for your input!

This might relate to #1995 , but we'll investigate it again.

Also, we've already released a new version 1.7.0, you can try installing it via Testpilot again to see whether or not the issue gets fixed on your machine.

**Comment by nicklan** [comment]
Ahh, updating to 1.7.0 seems to have fixed it.  Feel free to close, or let me know if you want any more info.

Thanks!

**Comment by ncloudioj** [comment]
@nicklan You're welcome! Good to hear that it's working now.
