### ISSUE TITLE
green up treeherder for bootstrapped add-on on pine

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2276]
This is actually probably several different issues.  https://treeherder.mozilla.org/#/jobs?repo=pine is an example of the bootstrapped add-on test results on pine.  A few of these are actually "normal" intermittent mozilla-central failures.  Other classes include:

* a bunch of identical-looking failures related to the localization set-up on pine
* a set of failures due to the fact that a bunch of tests in the tree are expecting old-school new tab semantics, even though the push to pine is only building and testing the bootstrapped add-on.  We may need to do some things to make both sets of preferences work in the tests, since presumably we're going to be feature-flagged in the tree for a while.
* eslint failure (there's already a github issue open for this

Next steps here are to go through all the failing test (classes) and break them down into separate tickets.

**Comment by Mardak** [comment]
Looks like just #2371 left.
