### ISSUE TITLE
figure out perfherder strategy for bootstrapped add-on

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2277]
We probably want alerts for this, so that we actually notice the difference.  It may also be that we're going to need to change our strategy for how we use pine (i.e. make it follow a single linear head), because Perfherder appears to be written assuming it can gather data from the last bunch of (presumably linear) commits in order to figure out whether there is noise in the data.

**Comment by dmose** [comment]
On the upside, the bootstrapped add-on is off to a good start w.r.t. perf: https://treeherder.mozilla.org/perf.html#/compare?originalProject=mozilla-central&originalRevision=3945f2297b99&newProject=pine&newRevision=bc5fff53646952aad7049f86e0340f919a8b5719&framework=1

**Comment by Mardak** [comment]
After discussing with wlach and digging around, it looks like perfherder doesn't really care about the commit / branching structure. It's just tracking performance results by push id and time. Here's a graph of e10s tp5o and tsvg summary results on the 3 platforms: https://mzl.la/2o84AAS (Some reason linux tp5o isn't being run consistently or maybe just stopped after 24th.)

Alerts (in the interface -- there's no more emails) use 12 data points (including retriggers) based on nearby pushes. Given how we're pushing to pine, these nearby pushes are generally sequential outside of the batch of pushes if there was a backlog of pushes to pine. Assuming each push-to-pine has one commit at a time, we can treat the previous pushes as reference performance points, so if a new push results in regressions, the interface will show the change. Even with multiple nearby pushes, future pushes will still show the regression as `master` is sequential, and newer PRs will include older commits, so it's no different from tracking down which commit actually regressed when builds are busy and drop some talos runs.

Given our relatively low volume of pushes/commits compared to m-c, we might want to look into retriggering talos jobs on each commit.

**Comment by dmose** [comment]
Wow, that's really interesting. Thanks for the digging, Ed.

It seems like, at some level, we're actually more interested in the regressions compared to mozilla-central, rather than in the regressions on pine, no?  Admittedly, both are interesting.

From your last sentence, do I understand correctly, that Talos jobs aren't automatically triggered after every hg push?

**Comment by Mardak** [comment]
We do want regressions vs mozilla-central, and pine is mostly mozilla-central right now, so any major regression will still be caught, e.g., when we implement rendering of the activity stream new tab page. I could see there being a potential sneaking in of regression, e.g., a series of say 0.5% regressions each from 10 separate commits, but we can just check periodically the performance relative to m-c.

Talos jobs should be running on every push (although I think some pushes are skipped if there's too much backlog). The `windows tsvg` results seem to have about 12 runs from the past 2 weeks: https://mzl.la/2o84AAS with a probably single run each. The main mozilla-central repository probably easily reaches 12 runs in an hour, so to reduce noise, we can retrigger to get more runs in to trigger alerts sooner.

**Comment by Mardak** [comment]
Here's the perfherder graphs for mac / windows talos e10s of tp5o / tsvg_static / tart:
https://mzl.la/2oD891a

Those were the most regressed from previous analysis in issue #2006.

These don't include linux as they aren't being run per [bug 1355812](https://bugzilla.mozilla.org/show_bug.cgi?id=1355812) and [bug 1355939](https://bugzilla.mozilla.org/show_bug.cgi?id=1355939).

Here's how things look in the past month:

![screen shot 2017-04-13 at 7 43 59 am](https://cloud.githubusercontent.com/assets/438537/25009963/587acf64-201d-11e7-8c19-f5231411edd7.png)

Note there's a clumping of dots in the last day from my explicit triggering of talos runs. Although looking at this 30 day picture, the triggers might not be necessary unless we're tracking down an exact push causing a regression. But just to track the script that I run from treeherder:

```js
// open treeherder with talos e10s expanded: https://treeherder.mozilla.org/#/jobs?repo=pine&filter-searchStr=talos%20e10s&group_state=expanded

// use this next line to show jobs to add
Array.slice(document.querySelectorAll("a[title^=Add][title$=push]")).forEach(a => a.click())

// use this to select jobs that aren't running or didn't succeed; skip linux for now
Array.slice(document.querySelectorAll("button[title~=Talos][title~=runnable][title~=e10s]:not([data-buildername~=Ubuntu])")).forEach(b => {
  p = b.previousSibling
  while (p !== null && (p.textContent.search(/^\s*$/) === 0 || p.title.split(" - ")[1] === "coalesced")) {
    p = p.previousSibling;
  }
  if (p !== null) {
    bt = b.title.split(" - ")[0];
    pt = p.title.split(" - ");
    if (pt[0] === bt && pt[1].search(/^(pending|success)/) === 0) return;
  }
  b.click();
});

// after above, click the "Trigger" button for desired pushes
```
