### ISSUE TITLE
Highlights with missing images 

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2279]
Dev build running on OSX: 1.7.0-dev-1490005055-13fd993

My experiment setup:

<img width="1027" alt="screen shot 2017-03-20 at 1 46 51 pm" src="https://cloud.githubusercontent.com/assets/1455254/24113649/d7454da4-0d73-11e7-98d8-2dbafebbdd91.png">

Seeing some blank tiles in the Highlighs occasionally:

<img width="244" alt="screen shot 2017-03-20 at 1 42 51 pm" src="https://cloud.githubusercontent.com/assets/1455254/24113510/67843944-0d73-11e7-96f2-68221445043d.png">
<img width="248" alt="screen shot 2017-03-20 at 1 43 01 pm" src="https://cloud.githubusercontent.com/assets/1455254/24113518/6d22af98-0d73-11e7-8c69-394c0d33739a.png">

**Comment by jaredkerim** [comment]
Closing this for now, my strongest suspicion is that this is a result of the network being spotty while opening a new tab page.  The system addon version will likely aggressively locally cache images and so should prevent this from happening.
