### ISSUE TITLE
Collect about:home vs. about:newtab

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#2280]
It would be good to know how frequently each of these sessions are happening so we can observe the relationship with click rate - specifically in the shield study when we need to make a 1:1 comparison.

**Comment by jaredkerim** [comment]
It's possible we already have this in the URL field.

Ursula says: 'it should include /home at the end of the URL'

**Comment by rlr** [comment]
Take a look at the page column. There should be a NEW_TAB vs HOME value?

**Comment by emtwo** [comment]
@rlr that's right, thanks!
