### ISSUE TITLE
review licenses of all dependent libraries we'll be shipping; figure out what to do with them

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2286]
We need to figure out approximately how many dependent libraries that we'll be shipping (eg not devDependencies) for the bootstrapped add-on.  After that we should then figure out what our strategy for getting them in the tree is.  My guess is that we'll have enough that we'll want to somehow deal with them en-masse, the way the devtools folks have (@k88hudson has a link for this, I believe).  And we'll need to talk to legal about that.

That said, we will also need to do some of this work incrementally as we land patches now which include these dependencies (eg Redux).

**Comment by k88hudson** [comment]
The only libraries I can see that we likely to want to include are `classnames` and possibly `lodash.debounce` (although there might be a Firefox equivalent for the latter we could replace it with). There also might be some dependencies getting added for `rlr`'s drag-drop stuff.

**Comment by k88hudson** [comment]
This is done
