### ISSUE TITLE
Icon quality drifting over time. 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#2296]
I have noticed that my icons have been loosing resolution throughout my day. 

![icons-looking-tired](https://cloud.githubusercontent.com/assets/228979/24171221/c6d650e4-0e40-11e7-97bb-59c4a722785f.gif)

**Comment by pdehaan** [comment]
That daringfireball icon just looks like a completely different icon.
kottke definitely looks fuzzier.
macrumors looks slightly different and almost zooms in, making me think it's also a different icon.

**Comment by sarracini** [comment]
Activity stream is alive, clearly

**Comment by ncloudioj** [comment]
This is fixed by 2f25fb5ff4c584ff8e7a0c89530e1d8944dcc8e4
