### ISSUE TITLE
This feature is leaking private URLs to external servers

### ISSUE THREAD

**Issue by Frogging101** [mozilla/activity-stream#2306]
A few days ago, I was looking at my server logs when I noticed odd requests for files that were only shared privately with a small number of people. The requests came with a non-descriptive "node-fetch" user agent, from AWS IP addresses with generic EC2 PTR records. No identification whatsoever.

Understandably, this was very concerning to me. The URLs they were requesting are not publicly searchable; they were only posted in private chat rooms, in some cases as far back as October 2015. And yet, somehow, they are being downloaded years later by unidentified bots that couldn't possibly know about them.

I began to investigate how the URLs could have been obtained. Other members of the community reported similarly odd requests from the same IP addresses and the same user agent. Eventually, I discovered that a member of our community (in which most of us are Firefox users) had enabled the Activity Stream feature.

I briefly installed Activity Stream (and I note that Firefox didn't ask for a confirmation before installing, as it usually does with Add-ons) to see what would happen. The node-fetch bots immediately hit my servers after doing so. That answers that. Now, what to do about it?

In my opinion, the browser should **not** be using external servers to query URLs from the user's history. I consider this an invasion of my privacy both as a Firefox user, and as an Internet user who shares content privately among his friends in the expectation that it will not be viewed by anyone else.

And as a server administrator, I expect that any legitimate service properly identifies itself when making requests. Questionable automated queries from a generic user agent with a generic EC2 PTR record frankly looks malicious.

The user agent in question is `node-fetch/1.0 (+https://github.com/bitinn/node-fetch)`
And these are the IP addresses I observed:

> 34.208.116.58
34.208.145.186
34.208.189.48
34.208.205.177
35.160.36.119
35.162.12.21
35.162.69.232
35.163.110.98
35.164.86.234
52.25.175.133
52.27.19.41
52.27.248.59
52.33.67.85
52.33.93.150
52.35.88.44

**Comment by jaredkerim** [comment]
@Frogging101 Thanks for the feedback!  Let me just explain the background on this:

Activity Stream takes a user's history and makes nice little preview cards of frequently and recently visited sites on your new tab page.  In the early stages of prototyping this, we used a service called http://embed.ly/ to generate these preview cards, which means that for each URL we wanted to show, we had to send that URL to the embedly servers to generate the preview.  Eventually we replaced our dependency on embedly with a smaller service we made to replace it:

https://github.com/mozilla/page-metadata-service

Which is the service you can see pinging your servers.

This service is a temporary stand in for parsing page metadata for generating preview cards while we move all metadata processing directly into the addon.  We obviously do not want to leak private URLs for our users, so we are migrating all metadata processing and storage into the addon itself as a background task.  In fact the current version does this for the majority of history items, but it still makes some queries to the service.  We have several code changes and experiments in flight now which will disable all calls to this service and measure its success.  When these experiments are complete we will be able to deprecate all calls to any remote service and no private URLs will be sent  out of the browser.  Let me know if you have any other questions!

Jared

**Comment by asppsa** [comment]
I second the call for a clear User-Agent string that identifies this service.  I was similarly alarmed by the 'node-fetch' requests showing up in my server logs.
