### ISSUE TITLE
Green up our JS dependencies

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2321]

**Comment by dmose** [comment]
https://dependencyci.com/ might be useful here

**Comment by Mardak** [comment]
I tried out https://www.npmjs.com/package/next-update and it seems to get some of what we want. Per-dependency update with unit testing. Although I didn't configure it at all and just ran `next-update`, so there's most likely various false positives that @dmose probably noticed in #3632 as well as those that didn't get touched as part of `npm test` (e.g., `buildmc` or `tippymc`).

It also reports the failed updates, and an initial glance shows some stuff like chai 4.0 renaming `propertyNotVal` to `notPropertyVal` https://github.com/chaijs/chai/releases/tag/4.0.0

So hopefully most are indeed actually green and updatable, and some requiring easy fixes to then be able to update.

next updates green:
moment 2.15.2 -> 2.19.2
object-sizeof 1.1.1 -> 1.2.0
page-metadata-parser 0.6.0 -> 1.1.0
react-json-inspector 7.0.0 -> 7.1.1
react-redux 4.4.5 -> 5.0.6
redux 3.6.0 -> 3.7.2
redux-logger 2.7.4 -> 3.0.6
redux-thunk 2.1.0 -> 2.2.0
reselect 2.5.4 -> 3.0.1
tippy-top-sites 1.3.1 -> 1.3.2
babel-core 6.25.0 -> 6.26.0
babel-loader 7.1.1 -> 7.1.2
babel-plugin-transform-es2015-destructuring 6.18.0 -> 6.23.0
babel-plugin-transform-es2015-modules-commonjs 6.24.1 -> 6.26.0
babel-plugin-transform-es2015-parameters 6.18.0 -> 6.24.1
babel-plugin-transform-strict-mode 6.18.0 -> 6.24.1
babel-preset-react 6.16.0 -> 6.24.1
conventional-changelog-cli 1.2.0 -> 1.3.5
eslint 4.9.0 -> 4.11.0
eslint-plugin-promise 3.5.0 -> 3.6.0
eslint-plugin-react 7.1.0 -> 7.4.0
eslint-watch 3.1.2 -> 3.1.3
eventemitter2 2.1.3 -> 4.1.2
faker 3.1.0 -> 4.1.0
github 8.1.1 -> 12.0.3
husky 0.11.9 -> 0.14.3
joi-browser 10.0.6 -> 13.0.1
karma 1.7.0 -> 1.7.1
karma-chrome-launcher 2.0.0 -> 2.2.0
karma-mocha 1.2.0 -> 1.3.0
karma-mocha-reporter 2.2.0 -> 2.2.5
karma-webpack 2.0.4 -> 2.0.6
mocha 3.5.0 -> 4.0.1
node-sass 4.5.3 -> 4.6.1
npm-run-all 3.1.1 -> 4.1.2
react-intl 2.2.3 -> 2.4.0
requirejs 2.3.2 -> 2.3.5
rimraf 2.5.4 -> 2.6.2
sass-lint 1.10.1 -> 1.12.1
shelljs 0.7.6 -> 0.7.8
simple-git 1.65.0 -> 1.82.0
sinon 3.2.0 -> 4.1.2
webpack 3.5.3 -> 3.8.1


red:
react 15.3.2 -> 16.1.1
react-dom 15.3.2 -> 16.1.1
chai 3.5.0 -> 4.1.2
enzyme 2.7.0 -> 3.2.0
eslint-plugin-mozilla 0.4.0 -> 0.4.8
istanbul-instrumenter-loader 0.2.0 -> 3.0.0
karma-sinon 1.0.5 -> 1.8.0
loader-utils 0.2.16 -> 1.1.0
react-addons-test-utils 15.3.2 -> 15.6.2

Although we probably want to clean up some dependencies first in #3537. And other types of cleanup, e.g., moving `tippy-top-sites` as a dependency to something more like external? Or does it actually need to be there given that we separately updated the icons and manifest?

**Comment by Mardak** [comment]
Saving the resulting package.json diff from my initial run:
```diff
diff --git a/package.json b/package.json
index 99daff22..43ca915b 100644
--- a/package.json
+++ b/package.json
@@ -5,87 +5,87 @@
   "author": "Mozilla (https://mozilla.org/)",
   "bugs": {
     "url": "https://github.com/mozilla/activity-stream/issues"
   },
   "dependencies": {
     "classnames": "2.2.5",
     "fancy-dedupe": "0.1.0",
     "lodash.debounce": "4.0.8",
-    "moment": "2.15.2",
-    "object-sizeof": "1.1.1",
-    "page-metadata-parser": "0.6.0",
+    "moment": "2.19.2",
+    "object-sizeof": "1.2.0",
+    "page-metadata-parser": "1.1.0",
     "react": "15.3.2",
     "react-dom": "15.3.2",
-    "react-json-inspector": "7.0.0",
-    "react-redux": "4.4.5",
-    "redux": "3.6.0",
-    "redux-logger": "2.7.4",
-    "redux-thunk": "2.1.0",
+    "react-json-inspector": "7.1.1",
+    "react-redux": "5.0.6",
+    "redux": "3.7.2",
+    "redux-logger": "3.0.6",
+    "redux-thunk": "2.2.0",
     "redux-watch": "1.1.1",
-    "reselect": "2.5.4",
-    "tippy-top-sites": "1.3.1"
+    "reselect": "3.0.1",
+    "tippy-top-sites": "1.3.2"
   },
   "devDependencies": {
     "babel": "6.23.0",
-    "babel-core": "6.25.0",
-    "babel-loader": "7.1.1",
+    "babel-core": "6.26.0",
+    "babel-loader": "7.1.2",
     "babel-plugin-jsm-to-commonjs": "0.2.0",
     "babel-plugin-transform-async-to-module-method": "6.24.1",
-    "babel-plugin-transform-es2015-destructuring": "6.18.0",
-    "babel-plugin-transform-es2015-modules-commonjs": "6.24.1",
-    "babel-plugin-transform-es2015-parameters": "6.18.0",
-    "babel-plugin-transform-strict-mode": "6.18.0",
-    "babel-preset-react": "6.16.0",
+    "babel-plugin-transform-es2015-destructuring": "6.23.0",
+    "babel-plugin-transform-es2015-modules-commonjs": "6.26.0",
+    "babel-plugin-transform-es2015-parameters": "6.24.1",
+    "babel-plugin-transform-strict-mode": "6.24.1",
+    "babel-preset-react": "6.24.1",
     "chai": "3.5.0",
     "co-task": "1.0.0",
-    "conventional-changelog-cli": "1.2.0",
+    "conventional-changelog-cli": "1.3.5",
     "cpx": "1.5.0",
     "decompress-cli": "2.0.0",
     "enzyme": "2.7.0",
-    "eslint": "4.9.0",
+    "eslint": "4.11.0",
     "eslint-plugin-json": "1.2.0",
     "eslint-plugin-mozilla": "0.4.0",
-    "eslint-plugin-promise": "3.5.0",
-    "eslint-plugin-react": "7.1.0",
-    "eslint-watch": "3.1.2",
-    "eventemitter2": "2.1.3",
-    "faker": "3.1.0",
-    "github": "8.1.1",
-    "husky": "0.11.9",
+    "eslint-plugin-promise": "3.6.0",
+    "eslint-plugin-react": "7.4.0",
+    "eslint-watch": "3.1.3",
+    "eventemitter2": "4.1.2",
+    "faker": "4.1.0",
+    "github": "12.0.3",
+    "husky": "0.14.3",
     "istanbul-instrumenter-loader": "0.2.0",
-    "joi-browser": "10.0.6",
-    "karma": "1.7.0",
+    "joi-browser": "13.0.1",
+    "karma": "1.7.1",
     "karma-chai": "0.1.0",
-    "karma-chrome-launcher": "2.0.0",
+    "karma-chrome-launcher": "2.2.0",
     "karma-coverage": "1.1.1",
     "karma-coveralls": "1.1.2",
     "karma-firefox-launcher": "1.0.1",
     "karma-html2js-preprocessor": "1.1.0",
-    "karma-mocha": "1.2.0",
-    "karma-mocha-reporter": "2.2.0",
+    "karma-mocha": "1.3.0",
+    "karma-mocha-reporter": "2.2.5",
     "karma-requirejs": "1.1.0",
     "karma-sinon": "1.0.5",
     "karma-sourcemap-loader": "0.3.7",
-    "karma-webpack": "2.0.4",
+    "karma-webpack": "2.0.6",
     "loader-utils": "0.2.16",
-    "mocha": "3.5.0",
+    "mocha": "4.0.1",
     "mock-raf": "1.0.0",
-    "node-sass": "4.5.3",
-    "npm-run-all": "3.1.1",
+    "node-sass": "4.6.1",
+    "npm-run-all": "4.1.2",
     "pontoon-to-json": "2.0.0",
     "react-addons-test-utils": "15.3.2",
-    "react-intl": "2.2.3",
-    "requirejs": "2.3.2",
-    "rimraf": "2.5.4",
-    "sass-lint": "1.10.1",
-    "shelljs": "0.7.6",
-    "simple-git": "1.65.0",
-    "sinon": "3.2.0",
-    "webpack": "3.5.3",
+    "react-intl": "2.4.0",
+    "requirejs": "2.3.5",
+    "rimraf": "2.6.2",
+    "sass-lint": "1.12.1",
+    "shelljs": "0.7.8",
+    "simple-git": "1.82.0",
+    "sinon": "4.1.2",
+    "webpack": "3.8.1",
     "yamscripts": "0.0.3"
   },
   "engines": {
     "firefox": ">=45.0 <=*",
     "//": "when changing node versions, also edit .travis.yml and .nvmrc",
     "node": "7.*"
   },
   "homepage": "https://github.com/mozilla/activity-stream",
```

**Comment by dmose** [comment]
I can't tell whether the proposal is to upgrade everything that's green, but I suspect we want to do most of these things in separate PRs so that any regressions not caught by integration/functional tests are findable via bisection.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421823
