### ISSUE TITLE
Update top sites queries to reflect new metadata fields

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2323]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1396104

**Comment by sarracini** [comment]
This is done via newtabutils's _addFavicons function - passing in a 0 to here: https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm?q=file%3Anewtabutils.jsm&redirect_type=single#877 to pull out largest favicon available

**Comment by Mardak** [comment]
@ncloudioj should this just be part of the patch for #3113 https://bugzilla.mozilla.org/show_bug.cgi?id=1352459

**Comment by ncloudioj** [comment]
@Mardak I prefer to do this change in a separate bug (although it could be an one-line-change), since #3113 is really only for *collecting* the rich favicons.

**Comment by Mardak** [comment]
The code change for this can happen now, and it can function correctly even before #3113. And it will get the better icon when that other issue is fixed.

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/d923714255be
