### ISSUE TITLE
Optimize icon message passing

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2324]
Currently we are passing  data URIs which is inefficient.  Can we pass a hash or some other id instead?

**Comment by Mardak** [comment]
Firefox has a `moz-anno:favicon:` URI that's generated with this bit of code:
https://dxr.mozilla.org/mozilla-central/source/browser/base/content/browser.js#4055-4058

The result looks like:
```js
Cu.import("resource://gre/modules/PlacesUtils.jsm");
PlacesUtils.favicons.getFaviconURLForPage(Services.io.newURI("https://github.com/"), icon =>
  icon && console.log(PlacesUtils.favicons.getFaviconLinkForIcon(icon).spec));

"moz-anno:favicon:https://assets-cdn.github.com/favicon.ico"
```

Although I'm not entirely sure when things get cached or not.

**Comment by sarracini** [comment]
Bugzilla ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1354248

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1436615
