### ISSUE TITLE
string is a link `What's this?`  is not visible

### ISSUE THREAD

**Issue by HasibulShanto** [mozilla/activity-stream#2329]
build id : 20170323090023
user agent : Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

Steps to reproduce :

1. install the testpilot add-on
2. install Activity Stream feature
3.  In the right side of the `Top Sites` string is a link `What's this?` should be there

Actual Result : the string is not visible
Expected Result : The string should have been there

![screenshot_6](https://cloud.githubusercontent.com/assets/26650229/24293070/323ec4a8-10ba-11e7-97a3-952ba7608c3e.jpg)

**Comment by tspurway** [comment]
Thanks @HasibulShanto for the bug report!

This is intentional as explained in #1873
