### ISSUE TITLE
Cookies and local storage fail when Activity Stream Add-on is enabled.

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#2336]
For a couple of weeks, I've been having trouble login into Mozilla.invision, and Pocket. 

Example: 
<img width="2560" alt="image" src="https://cloud.githubusercontent.com/assets/228979/24334715/683c23e6-1224-11e7-8ada-bbead093edd1.png">

Recently while trying to remedy this problem, I ran into this bug on the internet. https://github.com/mozilla/fxa-content-server/issues/4796 and decided to restart the browser in safe mode, which solved my login issues. Great!

However after enabling the Activity Stream add-on (dev/Master) version the login issue returned.

**Comment by bryanbell** [comment]
`GET 
https://getpocket.com/ff_signin [HTTP/1.1 302 Found 93ms]
GET 
https://oauth.accounts.firefox.com/v1/authorization [HTTP/1.1 302 Found 298ms]
GET 
https://accounts.firefox.com/oauth/signin [HTTP/1.1 200 OK 206ms]
GET 
https://accounts.cdn.mozilla.net/styles/adb16cbb.en.css [HTTP/2.0 200 OK 0ms]
GET 
https://accounts.cdn.mozilla.net/scripts/ced3da5c.head.js [HTTP/2.0 200 OK 0ms]
GET 
https://accounts.cdn.mozilla.net/scripts/698c9d90.main.en.js [HTTP/2.0 200 OK 0ms]
GET 
https://accounts.firefox.com/experiments.bundle.js [HTTP/1.1 200 OK 50ms]
POST 
https://accounts.firefox.com/_/csp-violation [HTTP/1.1 200 OK 166ms]
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://accounts.firefox.com 'sha256-9n6ek6ecEYlqel7uDyKLy6fdGNo3vw/uScXSq9ooQlk=' https://accounts.cdn.mozilla.net”). Source: 
		@font-face {

		font-family: 'Comic-S....  signin:1
POST 
https://accounts.firefox.com/_/csp-violation [HTTP/1.1 200 OK 190ms]
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://accounts.firefox.com https://accounts.cdn.mozilla.net”). Source: onfocusin attribute on DIV element.  signin
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.  adb16cbb.en.css:1:621
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.  adb16cbb.en.css:1:1733
Unknown property ‘speak’.  Declaration dropped.  adb16cbb.en.css:1:2508
Unknown property ‘appearance’.  Declaration dropped.  adb16cbb.en.css:1:5171
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.  adb16cbb.en.css:1:5939
Unknown property ‘appearance’.  Declaration dropped.  adb16cbb.en.css:1:17353
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:20426
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:20463
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:21619
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:21656
Unknown property ‘user-select’.  Declaration dropped.  adb16cbb.en.css:1:22363
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.  adb16cbb.en.css:1:25136
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:28464
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:28501
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:29187
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:29224
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:29855
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:29892
Unknown property ‘appearance’.  Declaration dropped.  adb16cbb.en.css:1:30158
Unknown property ‘user-select’.  Declaration dropped.  adb16cbb.en.css:1:30361
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:30910
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:30947
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector.  adb16cbb.en.css:1:31198
Unknown pseudo-class or pseudo-element ‘-ms-value’.  Ruleset ignored due to bad selector.  adb16cbb.en.css:1:31249
Unknown property ‘user-select’.  Declaration dropped.  adb16cbb.en.css:1:33543
Error in parsing value for ‘width’.  Declaration dropped.  adb16cbb.en.css:1:35548
Error in parsing value for ‘width’.  Declaration dropped.  adb16cbb.en.css:1:35597
Error in parsing value for ‘width’.  Declaration dropped.  adb16cbb.en.css:1:37158
Error in parsing value for ‘width’.  Declaration dropped.  adb16cbb.en.css:1:37207
Error in parsing value for ‘height’.  Declaration dropped.  adb16cbb.en.css:1:37869
Error in parsing value for ‘height’.  Declaration dropped.  adb16cbb.en.css:1:37920
Error in parsing value for ‘display’.  Declaration dropped.  adb16cbb.en.css:1:38372
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:39619
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:39656
Error in parsing value for ‘color’.  Declaration dropped.  adb16cbb.en.css:1:43627
Unknown property ‘text-wrap’.  Declaration dropped.  adb16cbb.en.css:1:44409
Unknown property ‘text-wrap’.  Declaration dropped.  adb16cbb.en.css:1:46786
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:49978
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:50015
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:50526
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:50563
Unknown property ‘user-select’.  Declaration dropped.  adb16cbb.en.css:1:57598
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:58195
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:58232
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:58743
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:58780
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:59246
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:59283
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  adb16cbb.en.css:1:59790
Expected media feature name but found ‘min-device-pixel-ratio’.  adb16cbb.en.css:1:59827
Use of Mutation Events is deprecated. Use MutationObserver instead.  ContentVeil.js:2:4726
GET 
https://accounts.cdn.mozilla.net/images/7c34ff65.firefox@2x.png [HTTP/2.0 304 Not Modified 64ms]
GET 
https://accounts.cdn.mozilla.net/images/396e2200.spinnerlight@2x.png [HTTP/2.0 304 Not Modified 64ms]
GET 
https://accounts.cdn.mozilla.net/images/542fcd95.mozilla.svg [HTTP/2.0 200 OK 0ms]
GET 
XHR 
https://oauth.accounts.firefox.com/v1/client/749818d3f2e7857f [HTTP/1.1 200 OK 288ms]
POST 
https://accounts.firefox.com/_/csp-violation [HTTP/1.1 200 OK 48ms]
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://accounts.firefox.com 'sha256-9n6ek6ecEYlqel7uDyKLy6fdGNo3vw/uScXSq9ooQlk=' https://accounts.cdn.mozilla.net”).  signin:1
POST 
https://accounts.firefox.com/_/csp-violation [HTTP/1.1 200 OK 64ms]
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://accounts.firefox.com 'sha256-9n6ek6ecEYlqel7uDyKLy6fdGNo3vw/uScXSq9ooQlk=' https://accounts.cdn.mozilla.net”). Source: /* Copyright 2014 Evernote Corporation. ....  signin:1
POST 
XHR 
https://accounts.firefox.com/metrics-errors [HTTP/1.1 200 OK 52ms]
POST 
https://accounts.firefox.com/metrics [HTTP/1.1 200 OK 138ms]
GET 
https://accounts.cdn.mozilla.net/bower_components/fxa-js-client/a09b461b.fxa-client.js [HTTP/2.0 200 OK 0ms]
`

**Comment by bryanbell** [comment]
I get this console readout when trying to log into Pocket with my Firefox Accouunt <img width="995" alt="image" src="https://cloud.githubusercontent.com/assets/228979/24371322/4afb4120-12df-11e7-9d6b-f25564e2a4cb.png">

**Comment by bryanbell** [comment]
[Invision-Console-Readout.txt](https://github.com/mozilla/activity-stream/files/873405/Invision-Console-Readout.txt)

[Pocket-Console-Readout.txt](https://github.com/mozilla/activity-stream/files/873411/Pocket-Console-Readout.txt)

**Comment by bryanbell** [comment]
This problem also happens for me on https://mozilla.service-now.com/

**Comment by bryanbell** [comment]
and Trello 
<img width="1391" alt="image" src="https://cloud.githubusercontent.com/assets/228979/24668504/fa004d54-191b-11e7-8b14-dc7e0ee9e309.png">

[trello-console.txt](https://github.com/mozilla/activity-stream/files/893853/trello-console.txt)

**Comment by ncloudioj** [comment]
Using a new profile seemed to solve this issue. Close this one.
