### ISSUE TITLE
Correct text strings don't load with new browser session

### ISSUE THREAD

**Issue by mattcoxonline** [mozilla/activity-stream#2337]
I don't see the correct strings when I first load the browser / activity view for a new session. I thought this was something to do with my language setting of the browser or OS _(which is probably British English instead of American "English")_...

...but maybe it's because after every session, my browser clears the history / cookies / etc, and there's no content to show when I start the browser back up again.

<img width="1097" alt="capture-strings" src="https://cloud.githubusercontent.com/assets/673542/24356426/3492fbec-12fa-11e7-9303-cdced18a6c77.PNG">

I see **newtab_page_title** instead of **New Tab**, and **header_top_sites** instead of **Top Sites**, etc.

**Comment by ncloudioj** [comment]
@mattcoxonline Thank you for reporting this issue!

Close this one in favor of issue #2316 to track the Localization issue.
