### ISSUE TITLE
Re-enable/fix tightly-coupled search tests

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2340]
Over in #2339, we disabled some of the browser search tests that were tightly coupled to the existing tiles implementation.

As we land search in the bootstrapped add-on (probably around the time #2314 lands), we need to figure out what to do about that.  Assuming we're planning on a gradual roll-out of A-S (meaning that the search tests need to function with A-S preffed on or off), we'd ideally run the tests once under each setting.

We might be able to just assert that pine should stay alive to keep this coverage until we're done with the rollout.

We could also write some utility for running any given test with both pref settings (assuming such a thing doesn't already exist), and wrap the tightly coupled tests with that as we turn them back on...

**Comment by Mardak** [comment]
Looks like this will need some test changes as well as actual code changes to fix actual bugs!

**Comment by Mardak** [comment]
We'll need a `mozilla-central` change first before we can land `activity-stream` changes:
https://bugzilla.mozilla.org/show_bug.cgi?id=1371479
