### ISSUE TITLE
decide how to handle existing tiles tests 

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2344]
Over in #2342, we temporarily disabled tiles tests, since it seems premature to try and figure out what to do with them until we have something stood up that is closer to replacing them.  Assuming we're doing incremental roll-out, any solution needs to ensure that both tiles and activity-stream are tested while the roll-out is going on.

**Comment by k88hudson** [comment]
Ok I talked to some ateam people, they suggested setting the pref in `head.js` or taking advantage of `pushPrefEnv`. I'm going to push some stuff to pine to see how it works out
