### ISSUE TITLE
Opening sites in wrong containers

### ISSUE THREAD

**Issue by jjdelc** [mozilla/activity-stream#2349]
This is a tricky one, I don't know what to suggest, but I use the default tab containers heavily, Social/Shopping/News/Banking and my "No container" as well.

Opening a site from activity stream in "No container" sends me to an unlogged Facebook page, or will open my news reading site in "No container", leaking cookies there where I don't want them, or opening Amazon without my account signed in. 

I sometimes, accidentally, have Facebook links, or Amazon links open in the wrong container, but when that happens, it's OK because usually that meant that they were opened outside of my main intention to use those sites, but following other places' links. So there will be history of facebook.com in several containers.

**Comment by sarracini** [comment]
Let's close this, since we won't be fixing this in the test pilot version, and the new system addon version doesn't have this feature spec'ed out yet. Thanks for reporting!
