### ISSUE TITLE
Topsites are misaligned

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2351]
AS Version: 1.7.0-98c65f009ad58ffbf3ad44f1e15554be3f8eedee

![screenshot 2017-03-30 14 10 02](https://cloud.githubusercontent.com/assets/119884/24519324/bf9d7bc2-1552-11e7-94f9-5cad905fd5a5.png)

**Comment by rlr** [comment]
oy. well hopefully we can graduate the new top sites/screenshots experiment and not worry about this. Assuming it only happens with experiment off.

**Comment by jaredkerim** [comment]
Closing this as a wontfix.
