### ISSUE TITLE
Collect DOMMetaAdded event in ContentMetaHandler.jsm

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2354]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1393924
We're going to land a framescript in browser/extensions/activitystream which listens to DOMMetaAdded events, and collects:
- description
- preview images

For now, it'll just log the metadata it gets, but eventually when the places schema changes lands, it will store the found metadata for every url in places.

Rich icons will be added to firefox in ```ContentLinkHandler.jsm``` where DOMLinkAdded events get handled. We're doing this because 1. we told mak we would and 2. it's already being handled there and all we have to do is add a couple extra fields to listen on

The "rules" for which meta tags and which link tags we'll be collecting will be following our current rules from page-metadata-parser (https://github.com/mozilla/page-metadata-parser/blob/0.6.1/parser.js)

**Comment by Mardak** [comment]
When adding to places, will this just store the latest entry for a given page, i.e., `INSERT OR REPLACE`? Related is there value in adding an empty value to mark that we tried to get these items from the page but there weren't any?

**Comment by sarracini** [comment]
Currently blocked on landing schema changes and a js api for inserting description and preview image. Also, this will be code that lands in firefox and not system addon. Taking a similar approach to ```ContentLinkHandler.jsm``` but probably something like ```ContentMetaHandler.jsm```

**Comment by sarracini** [comment]
Tracking: https://bugzilla.mozilla.org/show_bug.cgi?id=1393924 
The work will be done in m-c and this ticket can be closed when that bug is closed

**Comment by sarracini** [comment]
woohoo! this is on autoland now: https://hg.mozilla.org/integration/autoland/rev/60cb967ca47f
fingers crossed it sticks

**Comment by sarracini** [comment]
take 2: https://hg.mozilla.org/integration/autoland/rev/1b2b3bc1d47b27d02c7187c818a7f5f5808ddc1f

**Comment by sarracini** [comment]
Closing this as it landed in mc: https://hg.mozilla.org/mozilla-central/rev/1b2b3bc1d47b
