### ISSUE TITLE
Collect number of low-res and high-res icons shown

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#2355]
There are 4 possible types of topsites images that might be shown:

1) Low-res places icon
2) High-res tippy top icon
3) High-res metadata icon
4) Screenshot

We now collect the number of screenshots and tippy-top sites people see. Additionally, it would be nice to collect cases when we show low-res icons. In fact, this could be a "bad state" since, with the addition of screenshots, we should very rarely see low-res icons.

**Comment by jaredkerim** [comment]
Okay so I added some boolean fields that should help with this in #2392 

So now you can determine those with the following logical statements after the link has been emitted from the TopSites feed (ie you should be able to do this anywhere in the redux store and onwards):

 Low Res:  !(link.hasHighResIcon || link.screenshot))
 High Res: link.hasMetadata && link.hasHighResIcon
 Screenshot: link.hasMetadata && !!link.screenshot


Only one of those three should ever be true at a given time, and typically it'll go: First 'low res' is true until we either compute the metadata and find a high res icon or compute the metadata and compute a screenshot.

There's not a good way right now to distinguish between a tippy top or metadata high res icon but @emtwo suggested that it wasn't strictly necessary, just to know whether it's high res or not.

Let me know if this makes sense.
