### ISSUE TITLE
Perma-orange: browser_undo_notification.js Test timed out

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2365]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1378478

Over in #2362, we disabled a couple of tightly coupled automigration-undo tests, where about:home and about:newtab are expected to handle certain messages from the migration code.  Here's a partial list:

https://dxr.mozilla.org/mozilla-central/search?q=MaybeShowAutoMigration&redirect=false

**Comment by Mardak** [comment]
Looks like the test is failing on try on multiple platforms:

linux: https://treeherder.mozilla.org/logviewer.html#?job_id=110569076&repo=try&lineNumber=3335
win7: https://treeherder.mozilla.org/logviewer.html#?job_id=110575004&repo=try&lineNumber=5090

```
FAIL | browser/components/migration/tests/browser/browser_undo_notification.js | Test timed out FAIL | browser/components/migration/tests/browser/browser_undo_notification.js | Found a tab after previous test timed out: about:newtab
```

**Comment by Mardak** [comment]
@dmose, any notes for @sarracini to take this issue?

**Comment by Mardak** [comment]
@sarracini is blocked on @gasolin responding to if these failing tests can be removed

**Comment by Mardak** [comment]
Maybe this test should only run with activity-stream.enabled=false or skip if enabled=true?

**Comment by Mardak** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1378478 for only running on about:home and tiles about:newtab

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/517fb326c6fe
https://bugzilla.mozilla.org/show_bug.cgi?id=1378478
