### ISSUE TITLE
Fix pine failure browser_google_codes.js

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2366]
https://treeherder.mozilla.org/logviewer.html#?job_id=87925091&repo=pine&lineNumber=2408

**Comment by dmose** [comment]
As it turns out, this was previously seen in https://bugzilla.mozilla.org/show_bug.cgi?id=1315953, so it's actually not us.  Going to disable.

**Comment by dmose** [comment]
There's some reasonable chance that this won't show up when we do things with the try servers to test landing / turning, so I don't think it's worth filing a reminder bug for re-enabling.  If it's a problem when we use the try servers before turning on by default, we'll hit it then, and can re-open this.
