### ISSUE TITLE
fixing single_locale pine issue

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2368]
A bunch of the pine builds (mostly l10n related, including L10N) are failing with this message:

IOError: Can't find single_locale/pine.py in ['.', '/home/worker/workspace/build/src/testing/mozharness/scripts/../configs',  '/home/worker/workspace/build/src/testing/mozharness/scripts/../../configs']!

It rather looks like a pine configuration issue.  We should ask around in #ateam and/or poke at the code to see what to do.

**Comment by k88hudson** [comment]
This issue will be fixed by https://hg.mozilla.org/integration/mozilla-inbound/rev/8a3519624432cad53d657ab0452f3ca11aafd936, but we may need to re-open if we want to enable l10n-specific tests for activity stream.

**Comment by Mardak** [comment]
💚 greeeen! (well… lack of red) https://treeherder.mozilla.org/#/jobs?repo=pine&revision=838c5174dfab6ca4fe1a0e70f43ba7aa929746c6&selectedJob=89723792&filter-searchStr=l10n
