### ISSUE TITLE
Fix pine Gecko Decision Task

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2370]
https://treeherder.mozilla.org/logviewer.html#?job_id=87631096&repo=pine&lineNumber=3684
HTTPError: 403 Client Error: Forbidden for url: http://taskcluster/queue/v1/task/KIY1vNrgR_6upTOUduQc6A

part of #2276

**Comment by dmose** [comment]
Talking to aki about this; he's going to tweak the pine config to fix and then push to m-c once it's verified to work on pine.

**Comment by dmose** [comment]
This is being tracked over in https://bugzilla.mozilla.org/show_bug.cgi?id=1339179.  Aki's patch will also get rid of a whole bunch of unnecessary, duplicate builds, which will mean less starring work for us when there are problems.

**Comment by Mardak** [comment]
💚 greeeen! https://treeherder.mozilla.org/#/jobs?repo=pine&revision=838c5174dfab6ca4fe1a0e70f43ba7aa929746c6&filter-searchStr=decision
