### ISSUE TITLE
Turn off artifact builds for pine

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2371]
Linux x64 opt - AB Artifact builds are failing with

Exception: Could not find any candidate pushheads in the last 50 revisions.

part of #2276

**Comment by dmose** [comment]
> <dmose> jmaher: how do we turn off artifact builds on the pine branch?  do we need to file a bug somewhere?  (those builds will always fail because of how we're using pine, so they're just wasting cycles)
> <jmaher|afk> dmose: I suspect we just need to adjust some taskcluster configs to not use pine
> <jmaher|afk> dmose: file a bug and cc :chmanchester 
>

**Comment by dmose** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1354247 filed.

**Comment by sarracini** [comment]
@dmose says close it, so it's closed!
