### ISSUE TITLE
Create an event for inserting favicons

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2379]
Currently we have a race between when the history entry is inserted and when the favicon is inserted in that sometimes the favicon data isn't ready when we need it. This is highlighted more prominently in the patch for #2376 when we get rid of the ```LEFT JOIN moz_favicons``` and replace it with the favicon service API ```getFaviconDataForPage```. Adding an event that we can listen to for when the favicons are done inserting would be better

**Comment by k88hudson** [comment]
This works if added to NewTabUtils, but it only returns the remote URL (not the data URI):
```
onPageChanged(uri, propertyChanged, value) {
      if (propertyChanged === Ci.nsINavHistoryObserver.ATTRIBUTE_FAVICON) {
        Services.obs.notifyObservers(null, "newtab-faviconChanged", {
          url: uri.spec,
          faviconUrl: value
        });
      }
    },
```

**Comment by sarracini** [comment]
Closing this an re-opening if we need it again
