### ISSUE TITLE
Unhandled exception in Preview Provider

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2397]
AS Version: 1.9.0-dev-1491861998
![screenshot 2017-04-11 13 05 54](https://cloud.githubusercontent.com/assets/119884/24921106/b287c05a-1eb7-11e7-92a8-52248e157f96.png)

**Comment by rlr** [comment]
This was because the new pinning code was sending in some empty slots (nulls) in the link array. This has been fixed on master. Do we still want to fix the Preview Provider to handle nulls?

Pretty sure same goes for #2398

**Comment by ncloudioj** [comment]
This is fixed in 46106ce21c9e80457c625258933fb632cc034280
