### ISSUE TITLE
Uncaught promise in Metadata Feed

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2398]
AS Version: 1.9.0-dev-1491861998

![screenshot 2017-04-11 13 05 33](https://cloud.githubusercontent.com/assets/119884/24921141/cccc0ca0-1eb7-11e7-8bec-7817673e52ff.png)

**Comment by ncloudioj** [comment]
This is fixed in 46106ce21c9e80457c625258933fb632cc034280
