### ISSUE TITLE
enable es2017/es8 for async/await (enables perf win; readable code)

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2407]
For performance reasons, [Firefox is switching away from Task.jsm to async/await](https://bugzilla.mozilla.org/show_bug.cgi?id=1353542).  Our infrastructure is almost set to do this, except that right now, we've got eslint using the default ES5 parser, rather than the ES8/ES2017 parser.  

I'm not so sure that we want to accept all the ES2017 features in our code base, but I don't see a way to turn async/await on selectively.  Additionally, the [Firefox codebase is already set to use ES8](https://dxr.mozilla.org/mozilla-central/source/.eslintrc.js#26).

An additional big bonus is that it makes it possible to [write more readable tests of Promise-based stuff, and ones that more robust against becoming "evergreen"](https://wietse.loves.engineering/testing-promises-with-mocha-90df8b7d2e35).

**Comment by Mardak** [comment]
@k88hudson you mentioned potentially running into CI issues because of old Firefox? `async` got added in 52 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Browser_compatibility

@dmose says CI should be using 53 already?

**Comment by Mardak** [comment]
Looking at a recent push, the logs seem to confirm 53:
Running tests on Firefox 53.0/Gecko 53.0 (Build 20170411024320) ({ec8030f7-c20a-464f-9b0e-13a3a9e97384}) under linux/x86_64.
