### ISSUE TITLE
Graduate screenshotsLongCache, bookmarkScreenshots and newtabPrefs experiments in 1.9.0 

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2410]
Note that for newtabPrefs, let's just graduate the sidebar part, and leave the Top Sites editing feature (pin/drag&drop/edit) as it is.

**Comment by ncloudioj** [comment]
@jaredkerim Could you take care of the screenshot one?
Of course, the newtabPrefs one belongs to @rlr :)

**Comment by rlr** [comment]
The sidebar part has been done in pull #2416

**Comment by tspurway** [comment]
@ncloudioj, @jaredkerim is on PTO, if we want this done by monday, we need another volunteer :-)

**Comment by emtwo** [comment]
Are we graduating bookmark screenshots as well? This one is doing well so far so I think we can.

**Comment by tspurway** [comment]
good idea, @emtwo - updated title

**Comment by ncloudioj** [comment]
Just knocked down the screenshots one. @rlr Your turn 👉🎸
