### ISSUE TITLE
Highlights cards are missing when Top Sites are displayed on two rows

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2413]
**[Affected versions]:**
-Firefox 55.0a1 & 52.0.2
-Activity Stream 1.9.0-dev-1491949221-463e213

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Activity Stream dev add-on version was previously installed on a profile with Highlights.
-The `extensions.@activity-streams.experiments.newTabPrefs` pref from about:config is set to **true**.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and click on the gear wheel (Customize your New Tab page) button from the top right corner of the page.
3. Select to show Top Sites on two rows.
4. Observe Highlights tiles.
 
**[Expected results]:**
- Top Sites tiles are displayed on two rows and all other sections are are untouched by this change.

**[Actual results]:**
- Highlights cards are no longer displayed after Top Sites are displayed on two rows.

**[Notes]:**
- Recording of the issue:
![missing highlights](https://cloud.githubusercontent.com/assets/9248513/24956637/2e802d3a-1f91-11e7-866f-ed5df7205674.gif)

**Comment by ncloudioj** [comment]
I think this is due to "selectAndDedupe", with two rows of Top Sites, the current logic of "selectAndDedupe" won't show those two cards in Highlights as they're already in the Top Sites. But yes, it looks like an odd behavior that all of a sudden, the Highlights area disappears.

**Comment by ncloudioj** [comment]
Closing this one to favor #2064

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on A-S 1.14.0-dev-1497551877-9d19af4 and I cannot reproduce is. Thus marking this as Verified-Fixed.
