### ISSUE TITLE
[Enhancement] Default Top Sites should have the Pin option available

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2414]
**[Affected versions]:**
-Firefox 55.0a1 & 52.0.2
-Activity Stream 1.9.0-dev-1491949221-463e213

**[Affected Platforms]:**
-All Windows
-All Mac
-All Linux

**[Prerequisites]:**
-Latest Activity Stream dev add-on version was previously installed on a profile with history.
-The `extensions.@activity-streams.experiments.newTabPrefs` pref from about:config is set to **true**.
-One or two default tiles are present in Top Sites.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and click on "Edit" button for Top Sites.
3. Hover the mouse cursor over a default tile.
4. Observe the behavior.
 
**[Expected results]:**
- Default Top Sites tiles have the pin option available.

**[Actual results]:**
- Default Top Sites tiles cannot be pinned.

**[Notes]:**
- Recording of the issue:

![pin default top sites tiles](https://cloud.githubusercontent.com/assets/9248513/24959180/96ab5e4e-1f9a-11e7-86e0-8070e52381c7.gif)

**Comment by aaronrbenson** [comment]
Yes, default Top Sites should have the same behavior.

**Comment by jaredkerim** [comment]
We will build this in the system addon version but we will not fix this for the test pilot addon because it requires too much architectural change.

**Comment by k88hudson** [comment]
This is blocked on pinning landing in nightly

**Comment by Mardak** [comment]
Do we have an issue tracking pinning in nightly? I would guess as a bigger part of porting edit?
