### ISSUE TITLE
Consider refactoring into larger modules for performance 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2419]
This issue was raised in a review from mconley on [Bug 1350411](https://bugzilla.mozilla.org/show_bug.cgi?id=1350411):

> Is it necessary to have so many JSM's? One of the things that Quantum Flow has identified is that accessing JSM's results in a non-zero overhead cost because of something called "cross-compartment wrappers". The more things can be contained within a single JSM, the better, because we avoid that overhead entirely.

> I see you're adding some new JSM's here, and I'm just a little worried that we're adding to that problem for Activity Stream. This doesn't have to happen in this patch, but I want your opinion: would it be possible to combine many of these JSM's into a single JSM? That way, you could at least avoid the overhead of them talking amongst each other.

This will obviously need some discussion, but perhaps we can find a middle ground / do some profiling to determine the extent to which we need to refactor into larger modules.

**Comment by Mardak** [comment]
It's not easy for us to combine into fewer large modules for testing, etc reasons.
