### ISSUE TITLE
Design changes to pinning

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2421]
<img width="387" alt="image" src="https://cloud.githubusercontent.com/assets/25276/25014660/aaeb3350-2046-11e7-9409-ab072466fdc0.png">

I would expect it to 'unpin'?

**Comment by bryanbell** [comment]
<img width="650" alt="image" src="https://cloud.githubusercontent.com/assets/228979/25195355/3617e73e-24f2-11e7-9af6-05ff44511dd0.png">

**Comment by aaronrbenson** [comment]
![screen shot 2017-05-01 at 1 38 21 pm](https://cloud.githubusercontent.com/assets/139451/25589764/7c99c62a-2e73-11e7-8a20-857ff0e86942.png)
