### ISSUE TITLE
Context menu button wrongly stays visible after you click it twice

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#2442]
[Affected versions]:
- Firefox 55.0a1 & 52.0.2
- Activity Stream Build: 1.10.0-dev-1492554719-a2769d0

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- The "extensions.@activity-streams.experiments.newTabPrefs" pref from about:config is set to true.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the context menu button for one of the tiles twice.
3. Hover away and observe the behavior.
 
[Expected results]:
- Context menu button is no longer visible.

[Actual results]:
- Context menu button stays visible. 

[Notes]:
- The issue is not reproducible on Mac OS.
- Attached a screen recording of the issue:
![context menu button stays visible](https://cloud.githubusercontent.com/assets/18304511/25180794/144612a4-2518-11e7-9dcd-f9d9ef0740af.gif)

**Comment by SoftVision-CiprianMuresan** [comment]
I've noticed that the same thing occurs in the Nightly version of Activity Stream.
@tspurway, what should be done in these kind of cases? File a new bug in bugzilla?

**Comment by Mardak** [comment]
Not sure if this is actually the wrong behavior. The context menu button is shown because it has focus. After closing the menu, you can hit space to reopen the menu. Or if you hit tab, focus moves to the next top site/article.

I do see that the behavior is different on mac vs linux, with mac seemingly moving focus to the top of the page?

**Comment by dmose** [comment]
On Mac, one needs to go into the system Preferences -> Keyboard ->
Shortcuts and change the "Full Keyboard Access" to get full accessibility.

2017-08-24 14:41 GMT-07:00 Ed Lee <notifications@github.com>:

**Comment by Mardak** [comment]
Basically it looks like windows/linux moves focus to clicked buttons while mac does not. This happens on regular web pages with `<button>`s.

For example, at the top of the github on this page, there's the right-most "Insights" button:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/438537/29690295-4bd50834-88db-11e7-9723-d8b4637350e2.png">

Clicking it on mac then hitting tab results in focus being not immediately after the Insights button. Whereas on Linux, clicking Insights button then hitting tab moves focus from the button to Pulse link.
