### ISSUE TITLE
Pinned tiles from Top Sites 2nd row are not visible if Top Sites tiles are displayed on only one row

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2445]
**[Affected versions]:**
- Firefox 55.0a1 & 52.0.2
- Activity Stream Build: 1.10.0-dev-1492554719-a2769d0

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- The "extensions.@activity-streams.experiments.newTabPrefs" pref from about:config is set to true.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and click on "Edit" button for Top Sites.
3. Click the "Show more" button.
4. Hover one of the Top Sites tile from the 2nd row and pin it.
5. Click the "Show less" button.
6. Click "Done" button.
 
**[Expected results]:**
- The pinned tab has priority over the others and it is displayed.

**[Actual results]:**
- The pinned tab is hidden and the user will not see that tab unless the Top Sites tiles are displayed on two rows.

**[Notes]:**
- When pinning tabs from the browser, the pinned tabs are displayed in front of the normal ones and are in chronological order.
- Attached a screen recording of the issue:
![pin](https://cloud.githubusercontent.com/assets/9248513/25187465/c38436ca-252b-11e7-8621-d74b9aaaec6e.gif)

**Comment by rlr** [comment]
From what I can tell, this is the same behavior in the existing `about:newtab`. For example, I pinned a site at slot #9. Then I resized my window so only 6 tiles would show, and that pinned site doesn't show up anymore.

So, I think this is working as designed. But UX should probably chime in here.

**Comment by tspurway** [comment]
this is intended.  it would be too jarring if we reordered the tiles when adjusting the number of rows
