### ISSUE TITLE
CSS is a bit off in 2 rows of topsites

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#2447]
It looks like this for me:

<img width="765" alt="screen shot 2017-04-19 at 1 39 34 pm" src="https://cloud.githubusercontent.com/assets/784781/25193669/dfd74d7e-2505-11e7-80b8-d1ca42e51006.png">

**Comment by emtwo** [comment]
<img width="128" alt="screen shot 2017-04-19 at 1 46 54 pm" src="https://cloud.githubusercontent.com/assets/784781/25194049/22da30cc-2507-11e7-89fc-3a0663947053.png">

Additionally, this shifted outline on hover appears

**Comment by jaredkerim** [comment]
Requires verification, found in release 1.9.0

**Comment by emtwo** [comment]
This was an issue in Firefox 52 but is fixed in Firefox 53
