### ISSUE TITLE
zh-CN localization displayed in zh-TW Firefox

### ISSUE THREAD

**Issue by petercpg** [mozilla/activity-stream#2452]
Steps to reproduce:
1. Install latest Activity Stream add-on
2. Change Firefox's `general.useragent.locale` preference to `zh-TW`
3. Open a new tab, and observe the placeholder text for search box ('Search the Web')

Expected: 
Proper zh-TW localization '搜尋 Web' is shown. 

Actual:
zh-CN text '在网络上搜索' is shown. 

Looks like a locale fallback problem?

**Comment by Mardak** [comment]
Turns out there's a bug in the SDK locale matching, which we'll be switching away from, but fixing it will allow localizers to correctly test.

**Comment by Mardak** [comment]
Screenshot of fix from the PR:
![screen shot 2017-04-21 at 12 15 07 am](https://cloud.githubusercontent.com/assets/438537/25267254/e197bf1c-2628-11e7-9302-835a15e837cc.png)
