### ISSUE TITLE
Move all the Places queries off the main thread

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2460]
Currently, all the Places queries for highlights and top sites are executed on the main thread. This could become a major performance concern as running too many time consuming tasks on the main thread is usually not a good idea.

Since each Places connection also provides another thread to support the async style query execution, we should consider migrating those queries for A-S to there as well. Actually, most of history/favicon/bookmarks services are already implemented as async APIs running on that worker thread.

Technically, this needs to be done at the lower level in order to dispatch queries to the worker thread, i.e. wrapping those queries by various C++ XPCom APIs.

**Comment by ncloudioj** [comment]
Split from #1510

**Comment by dmose** [comment]
Using XPCOM isn't sufficient -- i.e. why does this need to be in C++?

**Comment by ncloudioj** [comment]
In order to access the database worker thread, AFAIK, all those async APIs for Places are implemented in this way.

**Comment by Mardak** [comment]
Was this issue being handled by https://bugzilla.mozilla.org/show_bug.cgi?id=1352502 or is there a different issue that should be resolved with the landing of that bug?

**Comment by ncloudioj** [comment]
Yup, I think that's the only bug by far I'd have to consider.

Close it via https://bugzilla.mozilla.org/show_bug.cgi?id=1352502.
