### ISSUE TITLE
Fix string or add comment for "Trending Stories by [pocket]"

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2463]
@csadilek added a string in #2449
```
header_stories=Trending Stories by
```
https://github.com/mozilla/activity-stream/pull/2449/files#diff-906742e1af7418eb557312dc9217f2f1R6

The string is used in a context where an image is placed after it, specifically right now the pocket logo.

We might be able to fix this by making the string be something like "Trending Stories by {trending_logo}" although that might need a dangerously_set_html thing?

At minimum we should probably have a LOCALIZATION_NOTE explaining how the string is being used, so some locales can work around the issue with something like "Trending Stories by:" (note the colon) if grammar rules allow…

@flodolo suggestions?

**Comment by flodolo** [comment]
We definitely need a localization note. 

As you said, we could use a placeholder and replace it with the proper HTML code, but would layout support that, e.g. image at the beginning or in the middle?

**Comment by Mardak** [comment]
Sounds like the experiment will be en-US only, so I guess when we export strings to localize, I'll explicitly ignore the pocket commits for now.

**Comment by jaredkerim** [comment]
@k88hudson and @Mardak need to discuss an effective strategy for this

**Comment by Mardak** [comment]
Here's the list of recently added pocket-related strings:
```ini
header_stories=Trending Stories by 
type_label_recommended=Recommended
menu_action_save_to_pocket=Save to Pocket
settings_pane_pocketstories_header=Trending Stories
settings_pane_pocketstories_body=Pocket™, a part of the Mozilla family, will help connect you to high-quality content that you may not have found otherwise.
pocket_read_more=Read More
pocket_read_even_more=View More Stories
```

Which of these will users see even if the experiment/feature is turned off? And which should only be available to en-US?

**Comment by csadilek** [comment]
@Mardak The new plan is that the experiment will be active for everyone but only prefed on for 20% of the users. So, everyone will see the preference pane and everyone might see the remaining strings if they decide to turn on the feature. If possible, I would like to keep the remaining localization strings if the don't cause any concerns (these will be useful in other locales later.)

**Comment by csadilek** [comment]
@Mardak we've added a localization note now. Can this be closed?

**Comment by Mardak** [comment]
Let's wait for the sign off in https://github.com/mozilla/activity-stream-l10n/pull/1

**Comment by Mardak** [comment]
There was just one issue noted: "This sounds more like a developer note. Can you explain what "PocketStories component" is?"

**Comment by Mardak** [comment]
Actually, looking more closely at how those strings are used, we'll probably need to fix it. @flodolo 

https://github.com/mozilla/activity-stream/blob/2a8a93e8113438bd1906bbd70c65458c8fc109c9/content-src/components/PocketStories/PocketStories.js#L45
adds a ":" after `pocket_read_more`

https://github.com/mozilla/activity-stream/blob/2a8a93e8113438bd1906bbd70c65458c8fc109c9/content-src/components/PocketStories/PocketStories.js#L48
adds a ">" after `pocket_read_even_more`

See screenshot:
<img width="816" alt="image" src="https://cloud.githubusercontent.com/assets/438537/25448231/a4a71362-2a6c-11e7-8dd1-f7e6e20b1fd8.png">

**Comment by flodolo** [comment]
Yes, we need that to be part of the string (also, the > might would need to be RTL aware if not).

**Comment by csadilek** [comment]
@flodolo @Mardak you mean the ":" and "<" should be part of the translation string or explained in the note? It was part of the string in the original PR and then moved out based on review...

**Comment by flodolo** [comment]
The colon should be definitely part of the string exposed for localization.

If the ">" is just a decoration and we don't want to risk any locales changing it, we need to make sure it has the right direction on RTL.

**Comment by csadilek** [comment]
OK, I've update the linked PR to improve on the localization notes and move the colon to the string.

@flodolo @Mardak

**Comment by flodolo** [comment]
You need to update the comment, since colon is part of the string now.

Also need to fix this, probably in a followup
https://github.com/mozilla/activity-stream/blob/2a8a93e8113438bd1906bbd70c65458c8fc109c9/content-src/components/PocketStories/PocketStories.js#L48

Can we use CSS?

**Comment by csadilek** [comment]
@flodolo OK, comment updated.

I am not sure I get the concern about the ">". Can you elaborate?

**Comment by flodolo** [comment]
English vs Persian. By using `&gt;`you're hard-coding the direction

<img width="836" alt="schermata 2017-04-26 alle 20 20 21" src="https://cloud.githubusercontent.com/assets/3644868/25450022/e6e4563a-2abd-11e7-9400-097e30a156f9.png">

![Uploading Schermata 2017-04-26 alle 20.20.41.png…]()

**Comment by csadilek** [comment]
@flodolo never mind about the last question, you had already answered that above.

**Comment by Mardak** [comment]
For the ">", depending on LTR and how the page is composed, it might end up looking like "Read more <"

**Comment by Mardak** [comment]
@k88hudson I see your comment of "This shouldn't contain the >, since that's more of a UI element"
https://github.com/mozilla/activity-stream/pull/2449#discussion_r112474078

We can leave it out, and it should be RTL-able via css content

**Comment by Mardak** [comment]
I suppose an alternative is a common practice is to use ellipsis: …

E.g., View More Stories…

**Comment by csadilek** [comment]
@Mardak @flodolo @k88hudson I took the ">" out now. It's not relevant to this experiment and the UI is likely gonna chance for the final version.

All requested changes should now be covered by: https://github.com/mozilla/activity-stream/pull/2495

**Comment by flodolo** [comment]
> All requested changes should now be covered by: #2495

It looks good to me, both by fixing the > or using a …
