### ISSUE TITLE
Add telemetry to capture assistive technology

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2470]
We should include in telemetry information about which assistive technology users are employing to help us understand how we should address accessibility in our designs.

**Comment by sorin-davidoi** [comment]
I don't think capturing this sort of information makes much sense - see http://adrianroselli.com/2014/03/on-screen-reader-detection.html. Effort would be better spend fixing issues like https://github.com/mozilla/activity-stream/issues/2998.

**Comment by sarracini** [comment]
This doesn't make much sense
