### ISSUE TITLE
Improve the Screenshots mechanism in the system addon

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2475]
Currently the implementation of screenshots involves creating a whole new browser object in the main thread, however this is highly resource intensive and as we request more screenshots it seems to leak memory and then implode, so we should find a way to request screenshots in a way that doesn't interfere with main process performance and is also more stable.

**Comment by sarracini** [comment]
After doing some profiling with the background page thumbs mechanism, we saw that it's actually pretty fast and efficient - loads into it's own content process, doesn't jank the browser etc. The main reason it looks like it's slow to load in, is that we're limited to how long it takes for the page to load up in a browser and be ready for a screenshot. There's not a whole lot we can do there. However, there is a mechanism in place in here: https://dxr.mozilla.org/mozilla-central/source/browser/base/content/browser-thumbnails.js#171 which preemptively determines the links that are going to be shown on about:newtab, and captures a screenshot of that page if it will be a top site when it's already open so we don't have to open up a browser later and reload the page. 

We can optimize the screenshot mechanism by also doing this with activity stream's top sites. We would run the query, check if the currently open page is going to be a top site, and if so, capture the screenshot right then and there, so it's ready to be displayed the next time you open a new tab

**Comment by sarracini** [comment]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1367462

**Comment by sarracini** [comment]
Fixed in central; see bug above
