### ISSUE TITLE
Customize checkboxes not working after navigating back to Activity Stream

### ISSUE THREAD

**Issue by vladikoff** [mozilla/activity-stream#2476]
FF: 55.0a1 (2017-04-24) (64-bit)
Activity Stream : 1.9.0 ( April 24 )

## STR

* Install AS
* Open Activity stream, click on one of the top site icons
* Hit back, try to customize AS

## Expected 

Checkboxes should work

## Actual

Click the checkboxes does nothing.

## Details

See GIF below, I'm trying to click on checkboxes but they are not functioning: 

![as](https://cloud.githubusercontent.com/assets/128755/25353814/9553307c-28fe-11e7-85e9-07e6129d0f95.gif)

**Comment by tspurway** [comment]
Thanks for reporting this, @vladikoff! We aren't going to fix this, as there is a bunch of wonky behaviour with the back button that "goes away" when this lands in Nightly.
