### ISSUE TITLE
Track impressions on pocket items

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2486]
In addition to interactions, we also need to track impressions and unique ids of individual pocket items. This requires changes on our data processing and in the UI/the ping being sent.

**Comment by k88hudson** [comment]
cc @ncloudioj

**Comment by ncloudioj** [comment]
Yep, the Pocket team has updated the API to include an integer id for each recommended article. @csadilek and I will be working together on implementing the other changes for the add-on and data pipeline.

**Comment by ncloudioj** [comment]
This has landed.
