### ISSUE TITLE
Pocket v1 UX Improvements

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2496]
- [x] <strike>The icon in the Title logo (by Pocket) should be more transparent.</strike>
- [x] <strike>remove all Read More links: (Tech, Finance, Health etc)</strike>
- [x] <strike>move the View More Stories to the top right of the section</strike>
- [x] <strike>Remove the star, which represents a bookmark - replace with trending arrow</strike>
- [x] <strike>Rather than 'Recommended' put the topic (Travel, Health etc) for that card</strike>
- [x] <strike>In Preferences Pane, there is a ™ symbol that seems unnecessary</strike>

**Comment by bryanbell** [comment]
![newtab - 57 2x](https://cloud.githubusercontent.com/assets/228979/25451119/eed3922c-2a75-11e7-9993-ab9b17340f6e.png)

**Comment by nchapman** [comment]
Okay updated this issue to match various conversations that we had to day. @bryanbell is going to provide a new icon to put next to "Recommended".

**Comment by bryanbell** [comment]
Here's the New Trending icon. 
[Pocket Trending.svg.zip](https://github.com/mozilla/activity-stream/files/963418/Pocket.Trending.svg.zip)

**Comment by bryanbell** [comment]
Mockup

<img width="988" alt="image" src="https://cloud.githubusercontent.com/assets/228979/25513779/ccd17b36-2b8c-11e7-8c74-d0076a5c4509.png">

**Comment by bryanbell** [comment]
Specs

<img width="952" alt="image" src="https://cloud.githubusercontent.com/assets/228979/25513935/badecd4c-2b8d-11e7-8615-ea1fe92fd32d.png">

**Comment by Mardak** [comment]
As per #2463, would an ellipsis for "View More Stories…" be acceptable?

**Comment by csadilek** [comment]
@Mardak I've added a comment [1] to address this localization issue (">" LTR/RTL) when we're porting this to a system-addon. The topic came up in meetings yesterday and the agreement was to postpone working on some of the localization concerns so we can get the experiment started.

[1] https://github.com/mozilla/activity-stream/issues/2512
