### ISSUE TITLE
Can we remove animation on checkboxes inside New Tab Preferences

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2499]
There's a small delay when turning on/off sections from New Tab Preferences and it appears to be a result of a transition to the checkmark in the checkbox. Can we remove the transition/animation/effect thingy so that the page feels more responsive when turning sections on/off?

**Comment by rlr** [comment]
for sure! easy peasy. not sure how that got in there in the first place :eyes:
