### ISSUE TITLE
Add task to package system add-on as a stand-alone add-on

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2506]
It would be nice to be able to bundle a build of the system-addon to send to someone for testing (e.g. to UX, QA)

**Comment by Mardak** [comment]
Just making sure, this should just be a `npm run buildmc; pushd system-addon/; zip -r ../as-sa.xpi *; popd` (`buildmc` for webpack and css then zip it up)?

**Comment by Mardak** [comment]
Oh actually, there's some `install.rdf.in` processing.

**Comment by Mardak** [comment]
Well.. this might not be as useful as we think as the system-addon has some dependencies on Firefox 55 (e.g., `NewTabUtils`), so whoever is going to install the `.xpi` will need to be running on Nightly anyway, which will then just need a toggling of the pref to get the system-addon activity-stream.

**Comment by Mardak** [comment]
Also, looks like there might be some non-trivial issues of installing the add-on over the system-addon resulting in broken `resource://activity-stream` etc

**Comment by dmose** [comment]
This would (immediately) get us a developer channel that is up-to-date after every check in.  In the slightly longer term, 55 will be riding the trains...

As the resource: stuff, are you aware of specific problems?

**Comment by Mardak** [comment]
I got things mostly working after tweaking bootstrap to load/unload correctly on separate install of the xpi.
