### ISSUE TITLE
Set the right page property for telemetry from about:home

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2510]
Right now the `page` property for all events in `TelemetryFeed.jsm` is hardcoded to `NEW_TAB`. When we support taking over `about:home`, we should implement logic to detect the right page. This should also update the search box telemetry.

**Comment by Mardak** [comment]
Generalizing this to include other telemetry such as those from the search box.

**Comment by dmose** [comment]
@Mardak, I'm not sure what the "include other telemetry" means here.  Can you be more explicit?

**Comment by Mardak** [comment]
ursula already fixed the other stuff in #3321

**Comment by dmose** [comment]
@Mardak, I'm not sure what the "include other telemetry" means here.  Can you be more explicit?

**Comment by dmose** [comment]
Landing this is blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1398955 landing and merging to mozilla-central.
