### ISSUE TITLE
Implement search suggestions in Search

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2517]
We need to implement suggestions and related UI for graduation. Let's work with Bryan on this one to make sure the UI matches up with the style of the new about:newtab search input.

I also noticed there were some changes recently to the search box to the right of the awesomebar in nightly... perhaps we should take that into account?

**Comment by jaredkerim** [comment]
Let's remember to include 'ESC key dismisses suggestion' as part of our accessibility compliance and backwards compatbility/feature parity on about:home, see: https://github.com/mozilla/activity-stream/issues/2553

**Comment by k88hudson** [comment]
Ok, @bryanbell said he is cool with using the contentSearchUI stuff, can you just line up the suggestions to the input like this?:

![image](https://cloud.githubusercontent.com/assets/1455535/26213154/f7a7b480-3bc5-11e7-92f5-a4a1263e6fde.png)

**Comment by Mardak** [comment]
I believe I can!

<img width="765" alt="image" src="https://cloud.githubusercontent.com/assets/438537/26214293/b270ecb6-3bb0-11e7-9d96-5f73f57a599e.png">
