### ISSUE TITLE
Implement Places-related APIs for system addon

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2518]
This includes:
- relaying events (including history changes, clearing history, etc.)
- bookmarking API
- deleting API
- blocking API

These can be split into separate tickets if necessary.

**Comment by k88hudson** [comment]
I'm going to grab the relaying events part if that's cool

**Comment by sarracini** [comment]
The events are prefixed with "newtab-": https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#949

To call into the actions use this API: https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#1214
So it would be ```NewTabUtils.activityStreamLinks.deleteHistoryEntry(url);```
