### ISSUE TITLE
test-merges fails in hard-to-understand way when code is rebased rather than merged in

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2519]
When github returns no merge events for a PR that has actually merged, test-merges emits a confusing message.  I have a simple patch that makes the problem clear and suggests a workaround.

**Comment by k88hudson** [comment]
I changed the settings to use rebase/merges recently – we could also change this back if it's a problem

**Comment by dmose** [comment]
I'd suggest changing it back for now, and landing this patch also, as even before this change, people would occasionally rebase of their own volition.
