### ISSUE TITLE
Activity Stream fails to initialize

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2522]
AS Version: Build: 1.10.0-dev-1493658140-01d2c93

Just updated to latest dev version and my activity stream is stuck on the hang tight screen.

<img width="1440" alt="screenshot 2017-05-01 13 21 23" src="https://cloud.githubusercontent.com/assets/119884/25587292/6255df08-2e71-11e7-8511-dec80b98a8ea.png">

Browser console:

TypeError: can't access dead object  NewTabUtils.jsm:935:9
Attempt to set a forbidden header was denied: Connection  50175121-lcs_client_bin.js:93:385
TypeError: this.transport is null[Learn More]  main.js:1491:5
Use of nsIFile in content process is deprecated.  loader.js:244:15
TypeError: can't access dead object NewTabUtils.jsm:935:9
can't access dead object  NewTabUtils.jsm:463
TypeError: can't access dead object  NewTabUtils.jsm:935:9
can't access dead object  NewTabUtils.jsm:463
Empty string passed to getElementById().  github-8f30c4122a2e20872d9c1f277c02176c552d4488cf69e537b7a785a655cd1559.js:6:18088
TypeError: NetworkError when attempting to fetch resource.  (unknown)
TypeError: can't access dead object NewTabUtils.jsm:935:9
can't access dead object  NewTabUtils.jsm:463
TypeError: NetworkError when attempting to fetch resource.  (unknown)
TypeError: can't access dead object NewTabUtils.jsm:935:9
can't access dead object  NewTabUtils.jsm:463
TypeError: can't access dead object  NewTabUtils.jsm:935:9
TypeError: NetworkError when attempting to fetch resource.  (unknown)
can't access dead object  NewTabUtils.jsm:463
TypeError: can't access dead object NewTabUtils.jsm:935:9
OpenGL compositor Initialized Succesfully.
Version: 2.1 ATI-1.50.38
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M370X OpenGL Engine
FBO Texture Target: TEXTURE_2D

**Comment by jaredkerim** [comment]
I tried disabling and re-enabling and it hasn't fixed itself.

**Comment by jaredkerim** [comment]
I think this is probably the issue:

<img width="1014" alt="screenshot 2017-05-01 13 27 15" src="https://cloud.githubusercontent.com/assets/119884/25587410/f28bcbaa-2e71-11e7-8e93-a2a25780fe20.png">

**Comment by jaredkerim** [comment]
Now I'm just getting an endless stream of this:

<img width="1026" alt="screenshot 2017-05-01 13 33 56" src="https://cloud.githubusercontent.com/assets/119884/25587637/e405bd56-2e72-11e7-8731-df7d8d455944.png">

**Comment by tspurway** [comment]
I am getting this occasionally as well.  For me, it's after a few days of not opening a profile, so it leads me to believe there is some cache issue?

**Comment by jaredkerim** [comment]
My browser.newtabpage.pinned looks like:

﻿[{"url":"http://reddit.com/"},{"url":"http://www.youtube.com/"},{"url":"http://news.ycombinator.com/"},{"url":"https://www.netflix.com/"},{"url":"https://facebook.com/"},{"url":"http://instagram.com/"}]

**Comment by jaredkerim** [comment]
It's definitely related to accessing pinned links in metadata feed, these are the two errors I see at startup:

<img width="1023" alt="screenshot 2017-05-01 13 39 36" src="https://cloud.githubusercontent.com/assets/119884/25587836/aeed022c-2e73-11e7-92a0-e1a8f4af4190.png">

**Comment by jaredkerim** [comment]
Okay steps to reproduce are

1) Start Nightly with a fresh build of master on an empty profile
2) Navigate to a bunch of urls to fill your profile and populate some topsites and highlights
3) Enable the edit top sites experiment
4) Pin all your top sites
5) Disable the addon
6) Re enable the addon
7) See the trace above

**Comment by rlr** [comment]
e3b508ffc749c8f33269dc4470fae34194777f44
