### ISSUE TITLE
Main Thread Performance Tracking / Reporting

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2526]
Let's bookend main thread tasks in the system add-on and report in appropriate telemetry pings.  Includes:

- screenshots
- redux/reducer calculations
- metadata

**Comment by k88hudson** [comment]
Can we do/support some local profiling on a windows machine for this ticket as well?

**Comment by dmose** [comment]
As of this writing, no schema has yet been proposed for tracking this data, and the schema work is still in progress, and is happening in #2653 and https://github.com/mozilla/activity-stream/pull/2660/files

**Comment by dmose** [comment]
I suspect that we'll want to use some similar techniques to those described by @digitarald in #2669.

**Comment by dmose** [comment]
See also https://github.com/mozilla/activity-stream/issues/2005#issuecomment-298095620

**Comment by Mardak** [comment]
Main page including react and redux are on content page and screenshots are done in content too.
