### ISSUE TITLE
The Pocket watermark/logo should link to Pocket

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2536]
![screen shot 2017-05-02 at 4 19 03 pm](https://cloud.githubusercontent.com/assets/139451/25639867/21c4142c-2f53-11e7-9e85-91b76367f834.png)

**Comment by csadilek** [comment]
This will be covered in the next iteration. Link should go to: http://getpocket.com/firefox_learnmore?src=ff_newtab

We should also bring in the question mark / information panel from chrome (minus options):

<img width="413" alt="screen shot 2017-05-04 at 3 25 11 pm" src="https://cloud.githubusercontent.com/assets/472523/25721417/639f8a20-30de-11e7-85d3-06154719c00e.png">

**Comment by csadilek** [comment]
On master now.
