### ISSUE TITLE
"Top Sites" and "Trending Stories" appear after being disabled if a tab is pinned and certain steps are made

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla/activity-stream#2542]
[Notes]:
- The issue is intermittently reproducible without a pinned tab.
- The issue is also reproducible the other way around, "Top Sites" or "Trending Stories" elements won't appear after being enabled if the following steps are made.
- Disabling "Top Sites" or "Trending Stories" from the Activity Stream "about:addons" page has the same effect.
- The issue is still reproducible after browser restart.
- After disabling/enabling "Highlights" or "Search bar", the issue is no longer reproducible in that session.
- When disabling "Top Sites" and "Trending Stories", both may re-appear on certain new tabs.
- The issue is also reproducible with Activity Stream installed from Test Pilot.

[Affected versions]:
- Firefox 55.0a1
- Activity Stream Build: 1.11.0-dev-1493757617-571c80e

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream dev add-on version was previously installed on a profile with history.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and navigate to any website.
2. Pin the current tab and open a new tab.
3. Click on the "Customize your New Tab page" button.
4. Uncheck the "Top Sites" checkbox and click the "Done" button.
5. Open three new tabs and observe the contents of the new tab page.
 
[Expected results]:
- All elements except the disabled one appear.

[Actual results]:
- Every 3rd or 4th new tab, "Top Sites" section is displayed despite it being disabled.

[Additional Notes]:
- Attached a screen recording of the issue:
![as_issue_topsites](https://cloud.githubusercontent.com/assets/20083658/25666822/4f602682-302a-11e7-9757-a5db73b471e3.gif)

**Comment by jaredkerim** [comment]
This could be related to issues we've seen surrounding localstorage and content processes in nightly, which are somewhat outside of our control.  We probably won't fix this for the test pilot addon because it's going away, and shouldn't apply to the new system addon.  I'm closing this for now and we can revisit it if it re-occurs in the system addon.
