### ISSUE TITLE
1px hairline gap under the search button in active state

### ISSUE THREAD

**Issue by AmyYLee** [mozilla/activity-stream#2543]
When you click on the search box there is a 1px gap between the search box and the arrow icon. When you hover over the arrow icon, the gap disappears.

<img width="501" alt="screen shot 2017-05-03 at 15 02 03" src="https://cloud.githubusercontent.com/assets/5992746/25678081/800aa488-3016-11e7-9f42-9bdaeb93b8cc.png">

**Comment by k88hudson** [comment]
I am seeing some blurring happening on non-retina screens as well ata  `36px` height -- setting it to `37px` fixes it
