### ISSUE TITLE
ContentSearch not initialized

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2548]
Full message: TypeError: this._stringBundle is undefined
Full stack: this.ContentSearch._currentEngineObj<@resource:///modules/ContentSearch.jsm:508:9

@sarracini This was broken today by https://hg.mozilla.org/mozilla-central/rev/84909c2a4dbb
https://bugzilla.mozilla.org/show_bug.cgi?id=1358921

Instead of `init`ing in `_finalUIStartup`, it only gets loaded when it receives a message.

**Comment by Mardak** [comment]
Looks like it's lazily loaded only after receiving a ContentSearch message which is triggered from about:home or about:newtab loading. I wonder if we'll need to rework how `SearchFeed` works to be similar. I suppose technically it could be delayed even past page load as the actual search is only needed when the user starts typing in the search box?

**Comment by dmose** [comment]
We might want to wait and see if we actually have a perf issue that needs
help here, since it could introduce extra input latency.

2017-05-03 22:43 GMT-07:00 Ed Lee <notifications@github.com>:

**Comment by sarracini** [comment]
ugggghhhhhhhh

**Comment by sarracini** [comment]
We could also just explicitly initialize it ourselves

**Comment by Mardak** [comment]
The problem with initializing ourselves is that nsBrowserGlue will also initialize on its first message. And we can't rely on waiting for that init as it might never happen if the user doesn't load about:newtab or about:home.
