### ISSUE TITLE
Opening a new browser window will lose focus in A-S

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2554]
Reported by @st3fan,

> I have a desktop bug: When I create a new window, neither location field or Activity Stream search field have focus, so I have to click or hit Command-L. New tabs do focus on the location field.

**Comment by k88hudson** [comment]
This is for the test pilot add-on, right?

**Comment by ncloudioj** [comment]
Yep, it's reproducible there.

**Comment by jaredkerim** [comment]
Because this may impact the SHIELD study let's fix this if it's quick and easy.

**Comment by sarracini** [comment]
Dupe of #2007
