### ISSUE TITLE
404 not found for '… about the data collection for ⁨Activity Stream …'

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/activity-stream#2560]
At https://testpilot.firefox.com/experiments/activity-stream: 

> [You can learn more about the data collection for ⁨Activity Stream⁩ here.](https://github.com/mozilla/activity-stream/blob/master/docs/data_dictionary.md)

I can not learn from that `;-)` – it's 404, not found.

**Comment by Mardak** [comment]
Looks like the link is outdated. Should point to this:

https://github.com/mozilla/activity-stream/blob/master/docs/v1-test-pilot/data_dictionary.md

**Comment by k88hudson** [comment]
I updated the link here https://github.com/mozilla/testpilot/commit/3ab612c9adec6077b086f60d70f39b2bebffb697, that commit might not be in production yet though

**Comment by k88hudson** [comment]
Ok, this commit is now in production. Thanks for reporting the broken link!
