### ISSUE TITLE
Context Menu ordering/UX

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2563]
The Context Menu should be:
```
------
Bookmark
Pin
Save to Pocket
------
Open in New Window
Open in Private Window
-------
Dismiss
Delete From History
-------
```

**Comment by jaredkerim** [comment]
Added pin.

**Comment by aaronrbenson** [comment]
**Top Sites Context Menu**
```
------
Pin
Edit
------
Open in a New Window
Open in a New Private Window
-------
Dismiss
Delete From History
-------
```

**Pocket Stories Context Menu**
```
------
Bookmark / Remove Bookmark
Save to Pocket
------
Open in a New Window
Open in a New Private Window
-------
Dismiss
-------
```

**Recent Bookmarks**
```
------
Remove Bookmark
Save to Pocket
------
Open in a New Window
Open in a New Private Window
-------
Dismiss
Delete from History
-------
```

**Visit Again**
This section should never contain a bookmark
```
------
Bookmark
Save to Pocket
------
Open in a New Window
Open in a New Private Window
-------
Dismiss
Delete from History
-------
```

**Comment by Tobias-B-Besemer** [comment]
Can you always add"Open in a New Tab", too?

**Comment by Tobias-B-Besemer** [comment]
And if "Top Sites Context Menu" can contain pages that are not bookmarked, a "Bookmark / Remove Bookmark"...

**Comment by aaronrbenson** [comment]
Re: "Open in a New Tab" .. this is already a New Tab page, so I don't think it makes sense to add it to the context menus. 

Re: "Save to Pocket" in Top Sites ... Pocket is _usually_ used for things to read later while Top Sites operate more as bookmark/favorites for repeated use

**Comment by Mardak** [comment]
One of the user studies had a comment of being able to open multiple pages into separate tabs was nice.

On a separate note, I just noticed that one can right-click a top site to get the traditional link context menu in addition to clicking the corner "…" menu.

**Comment by Tobias-B-Besemer** [comment]
Re: "Save to Pocket" in Top Sites ... Pocket is usually used for things to read later while Top Sites operate more as bookmark/favorites for repeated use
And what's about a new, clean profile? The first opened tabs will be in "Top Sites", right?
