### ISSUE TITLE
Search suggestions are not displayed for an old profile

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2566]
**[Affected versions]:**
- Firefox 55.0a1 & 53.0.2
- Activity Stream Build: 1.11.0-dev-1494274961-dc23841

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and click into the Search bar.
3. Write a word.
4. Observe the Search Suggestions.
 
**[Expected results]:**
- Search suggestions are displayed for the written word.

**[Actual results]:**
- There are no search suggestions.

**[Notes]:**
- For a new profile, the search suggestions are displayed but the errors from the browser console remain.
- Attached a printscreen of the issue:
![no search suggestions old profile](https://cloud.githubusercontent.com/assets/9248513/25853186/94e03ee6-34d4-11e7-9031-d2eeadf61304.jpg)

**Comment by jaredkerim** [comment]
This is caused by core logic in the search provider mechanism which is outside of our ability to fix or control for the time being.
