### ISSUE TITLE
Cannot set "Top Sites" on two rows if the "Back" button was clicked after accessing a link from A-S page

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2567]
**[Affected versions]:**
- Firefox 55.0a1 & 53.0.2
- Activity Stream Build: 1.11.0-dev-1494274961-dc23841

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- "Top Sites" tiles are set to be on a single row.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and click on a tile from any section.
3. After the page has loaded click on the "Back" button.
4. Set the "Top Sites" tiles
 
**[Expected results]:**
- The user can set the "Top Sites" to be displayed on two rows.

**[Actual results]:**
- When clicking the "Show more" button nothing happens. The behavior is the same when trying the do the same action from New Tab Preferences menu.

**[Notes]:**
- This issue is encountered also after a search is performed and the user uses the "Back" button.
- This issue is reproducible also when trying to display less "Top Sites" tiles.
- Attached a screen recording of the issue:
![cannot set top sites on 2 rows](https://cloud.githubusercontent.com/assets/9248513/25856522/e9c6329e-34de-11e7-9e2f-b0dd11326abb.gif)
of the issue:

**Comment by jaredkerim** [comment]
Because 'navigating back' will not be supported in the system addon this will not be fixed in the system addon.
