### ISSUE TITLE
User friendly message is not displayed for empty sections

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2568]
**[Affected versions]:**
- Firefox 55.0a1 & 53.0.2
- Activity Stream Build: 1.11.0-dev-1494274961-dc23841

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- "Trending Stories" are activated from New Tab Preferences.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a new tab and dismiss all the "Trending Stories" tiles.
3. Observe the "Trending Stories" section.
 
**[Expected results]:**
- An user friendly message is displayed. The user is informed that if he will return later there will be more Trending Stories. 

**[Actual results]:**
- After all "Trending Stories" tiles are removed, the section is hidden.

**Comment by aaronrbenson** [comment]
Empty state added here for Pocket and other sections. Might need to make issues for these other ones?

https://mozilla.invisionapp.com/share/VHBRBK5SJ#/234243578_NewTab_-_Empty_States
