### ISSUE TITLE
[Enhancement] Add option to have the Activity Stream New Tab in "Dark Mode" 

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#2577]
[Affected versions]:
- Firefox 53.0.2 and up
- Activity Stream Build: 1.11.0-dev

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Latest Activity Stream dev add-on version is installed on a profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the New Tab settings button.
3. Observe the list of options.
 
[Expected results]:
- An option to switch to "Dark Mode" exists.

[Actual results]:
- No such option exists. 

[Notes]:
- Ideally instead of just a dark mode, the user could have the option to select a background color and text color of their choosing.
- Attached a screen shot (background color is switched with the text one; browser theme is compact dark):
![image](https://cloud.githubusercontent.com/assets/18304511/25896616/9e649af2-358d-11e7-9db6-aa50812beedd.png)

**Comment by StefanoCecere** [comment]
we would just need a simple light/dark theme selector.

i see that just by setting:
```
body {
  background-color: #2b2b3b;
}

.top-sites .tile-outer .tile .label {
color: #aaa;
}
```

a dark theme works nice!

**Comment by Tobias-B-Besemer** [comment]
What's about adding two prefs for it to Fx? It's part of the browser...

**Comment by sarracini** [comment]
No longer doing work on test pilot version of the addon. closing this
