### ISSUE TITLE
The Activity Stream resource is wrongly displayed in the Address Bar after a browser restart

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#2578]
[Affected versions]:
- Nightly 55.0a1
- Activity Stream Build: 1.11.0-dev

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- "When Firefox starts: Show my homepage" is set in about:preferences.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Observe the Address Bar.
 
[Expected results]:
- Address Bar is empty.

[Actual results]:
- "resource://activity-streams/data/content/activity-streams.html#/HOME" is displayed in the Address Bar.

[Notes]:
- The issue is also reproducible if the "When Firefox starts: Show my windows and tabs from last time" is set in about:preferences. But in this case you need to focus a New Tab before restarting the browser.
- The issue is also reproducible if you use the "restart" console command while on a New Tab page.
- If you navigate away from the New Tab page and then back to it, the URL bar is cleared.
- Attached a screen recording of the issue:
![activity stream resource shown after restart](https://cloud.githubusercontent.com/assets/18304511/25901403/658323ae-359f-11e7-897d-927dfc4ff91b.gif)

**Comment by jaredkerim** [comment]
This is not fixable in the test pilot addon and will not apply to the system addon so this is a wont fix.
