### ISSUE TITLE
"..." dots from Tops Sites context menu are displayed in the lower part of the button

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2579]
**[Affected versions]:**
- Nightly 55.0a1
- Activity Stream Build: 1.11.0-dev-1494371204-ffe9abc

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites.
2. Open a New Tab.
3. Move the mouse cursor over Top Sites tiles.
4. Observe the context menu button.
 
**[Expected results]:**
- The dots from the context menu icon are displayed in the middle of the button. 

**[Actual results]:**
- The dots from the context menu icon are displayed in the lower part of the button. 

**[Notes]:**
- The issue is only reproducible on Windows.
- Attached a screen recording of the issue:

![top sites context menu are wrongly displayed](https://cloud.githubusercontent.com/assets/9248513/25903013/e5aac9ac-35a3-11e7-99a5-625de33fc666.gif)

**Comment by sarracini** [comment]
I think we're going to close this as a won't fix since it's test pilot. Thanks!
