### ISSUE TITLE
Implement confirm dialog for deleting items in system add-on

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2584]
Implement a dialog for asking users to confirm when items are deleted.

This should be implemented in the system add-on (there is not currently a confirmation of any kind ) and can re-use existing localized strings.

**Comment by Mardak** [comment]
Alternatively have an undo button like the current new tab page.

**Comment by tspurway** [comment]
What we actually need for this is a better design for the dialog.  Right now it's implemented as an alert, which blocks the content process.  @aaronrbenson do you have a design already done for deleting a site?

**Comment by aaronrbenson** [comment]
Here's a new confirmation dialog: https://mozilla.invisionapp.com/share/49C81C6Z7#/238928525_Photon_-_Confirm_Dialog

**Comment by piatra** [comment]
Checklist:
- Create a new component that is added to the newtabpage, hidden most of the time.
    - this would allow us to reuse it for other confirmations
- Reuse the overlay implemented for Topsites editing (and whatever else is possible).
- Would react to `NotifyHistoryDelete` actions and become visible.
- Action buttons emit `NOTIFY_HISTORY_DELETE` and `NOTIFY_HISTORY_DELETE_CANCELLED` just as current behavior.

Nothing else significant comes to mind. @rlr does this look ok to you?

**Comment by piatra** [comment]
This issue mentions system add-on in the title but system add-on doesn't have a confirmation dialog. What is the scope? Test pilot or addon? @k88hudson

**Comment by rlr** [comment]
@piatra checklist 👍

**Comment by k88hudson** [comment]
The event you'll need to look for in the system add-on is `DELETE_HISTORY_URL`. 

If you're planning on implementing the confirmation dialog as a separate component, I'd recommend creating a new action specifically for opening/closing the dialog (e.g. `OPEN_DELETE_CONFIRMATION`) and have the buttons in the dialog actually trigger `DELETE_HISTORY_URL` and `CANCEL_DELETE_HISTORY_URL`.
