### ISSUE TITLE
[l10n] Untranslated strings in Activity Stream (Pocket)

### ISSUE THREAD

**Issue by flodolo** [mozilla/activity-stream#2589]
It was just reported by a localizer that we have unlocalizable strings in the Gear menu related to Pocket.

I see them in master here, can someone clarify what's the plan?
https://github.com/mozilla/activity-stream/blob/master/locales/en-US/strings.properties

Side reminder: if you update an existing string, remember to update the string ID too, otherwise translations will never be updated. I've seen a few of these changes in the latest commits, not sure if they're relevant, i.e. if we already exposed those strings for localization.

**Comment by k88hudson** [comment]
Product was thinking about only shipping that feature to our `en-US` audience, so we haven't actually uploaded the pocket strings to `mozilla/activity-stream-l10n` yet. We may in fact end up taking them out (depending on what the decision is)

**Comment by flodolo** [comment]
One issue is that we're currently exposing it for all locale, not just en-US. Not sure how easy it would be to hide it for all other languages while a final decision is taken.

**Comment by Mardak** [comment]
Could at least hide the preference pane showing the option:
```diff
diff --git a/content-src/components/PreferencesPane/PreferencesPane.js b/content-src/components/PreferencesPane/PreferencesPane.js
index 5bd9e47..fefa463 100644
--- a/content-src/components/PreferencesPane/PreferencesPane.js
+++ b/content-src/components/PreferencesPane/PreferencesPane.js
@@ -73,3 +73,3 @@ const PreferencesPane = React.createClass({
               </section>
-              <section>
+              <section hidden={props.intl.locale !== "en-US"}>
                 <input ref="showPocketCheckbox" type="checkbox" id="showPocket" name="showPocket" checked={showPocket} onChange={this.handleChange} />
```

But would need to figure out what to do with the experiment?

**Comment by Mardak** [comment]
There's also the context menu:
<img width="201" alt="image" src="https://cloud.githubusercontent.com/assets/438537/26005872/49dedca0-36ef-11e7-85fa-57591c8df710.png">

**Comment by tspurway** [comment]
Is pocket available in non-english locales?  if so, we should at least localize the "Save to Pocket" menu item.

**Comment by flodolo** [comment]
> Is pocket available in non-english locales? if so, we should at least localize the "Save to Pocket" menu item.

https://l10n.mozilla-community.org/webstatus/?product=pocket

**Comment by tspurway** [comment]
Let's make sure to have a chat with the Pocket folks to figure out what the params are around this.

**Comment by tspurway** [comment]
Let's go ahead and get these strings translated

**Comment by Mardak** [comment]
Opened up https://github.com/mozilla/activity-stream-l10n/pull/2
