### ISSUE TITLE
Tiles pref parity: browser.newtabpage.rows

### ISSUE THREAD

**Issue by Mathnerd314** [mozilla/activity-stream#2592]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1383004
I'd really like a pref similar to [``browser.newtabpage.rows``](https://dxr.mozilla.org/mozilla-central/rev/73b3fc64525b6816842c737e104ef2ac5482d217/toolkit/modules/NewTabUtils.jsm#42); #2218 is a good start with the ``showMoreTopSites`` pref, but 2 rows just isn't enough.

**Comment by tspurway** [comment]
Thanks for the feedback @Mathnerd314, we are working on more customization features in about:newtab and about:home, and will consider your input.

**Comment by Mathnerd314** [comment]
@tspurway any news on this? I've looked but it doesn't seem like there's actually been any work. I'm willing to do it, but I don't know what the goals are...

**Comment by piatra** [comment]
@Mathnerd314 Activity Stream graduated from a Test Pilot experiment and made it in Firefox Nightly. Right now our efforts are concerned with having feature parity (which means having to port a lot of functionality in the version being shipped with Nightly). Although customization is important it's not currently our focus. More customization will be coming in the future.

**Comment by Mathnerd314** [comment]
So you're saying that existing prefs aren't a part of feature parity? It looked like it was from #2033, when it said "all the custom prefs".

**Comment by Mardak** [comment]
Reopening for design feedback as it's a common request in bugzilla. @bryanbell Do we want to at least silently support multiple rows? I could see us not wanting to do columns as it impacts other sections.

**Comment by Mardak** [comment]
#3214 added a `browser.newtabpage.activity-stream.topSitesCount` pref that could potentially be reused to allow for more than 12. The 12 cap is still limited by `TopSitesFeed.jsm`:
https://github.com/mozilla/activity-stream/blob/2563425a870a9aa7952175b36fa73d78a0ccb454/system-addon/lib/TopSitesFeed.jsm#L81

**Comment by Mathnerd314** [comment]
@Mardak What does this need to move forward? A pull request?

**Comment by Mardak** [comment]
Sure, a PR would be good. The team is currently focused on getting in P1s for Firefox 57 and then to fx 57 P2s. This bug is not triaged as either, so it's unlikely we'll get it in for 57 unless someone volunteers.

**Comment by Mardak** [comment]
Well, I've thought about this for a while. Maybe I'll try to volunteer some time this weekend.

**Comment by Mathnerd314** [comment]
I'd rather you review; I've got most of a patch, just have to test it

**Comment by Mardak** [comment]
Ah sorry about that. I also worked on a patch with a PR now. But I would still like to see how you approached it!

**Comment by Mathnerd314** [comment]
My approach: https://github.com/Mathnerd314/activity-stream/commit/6ef069505f4f4270264b17908007573528361171

**Comment by Mardak** [comment]
Ah yup. Pretty similar to what I did for #3507. There's no need to stash the `topSitesCount` as it would be available via `getState()`. Seems like you might have more extensive testing updates though.

**Comment by Mardak** [comment]
@Mathnerd314 thanks for putting together the commit. As you did cover some things I didn't, I think it could make sense to have a separate followup to fix various things if you want `topSitesCount` to be more dynamically updated. There's at least a couple things that don't work until restarting Firefox, e.g., increasing that pref value manually or pinning/unpinning excess-over-12 sites.

**Comment by Mathnerd314** [comment]
Restartless would nice, but honestly it's not much of an issue anymore since Firefox startup got so speedy.

**Comment by Mathnerd314** [comment]
Here's what my new about:newtab looks like now, with topSitesCount=66 and some userContent.css [styling](https://userstyles.org/styles/95775/new-tab-full-screen):

![image](https://user-images.githubusercontent.com/322214/30660285-9613d862-9dfd-11e7-851a-53e6d2f8f955.png)

Compared to [the old version](https://camo.githubusercontent.com/00f880e7c4edc96189a6d94814c775b833b610e4/687474703a2f2f692e696d6775722e636f6d2f646568335769732e706e67), it adds favicons and 16 extra pages. Still not as good as [Auto Dial](https://addons.mozilla.org/en-US/firefox/addon/auto-dial/) though 😄

**Comment by Mardak** [comment]
Glad it works for you. Just checking, did those screenshots eventually load?

**Comment by Mathnerd314** [comment]
Yep, after I disabled a noscript pref that was blocking them...
