### ISSUE TITLE
Please use bookmark names if they are available on Android

### ISSUE THREAD

**Issue by andreicristianpetcu** [mozilla/activity-stream#2593]
Hi,

I use different bookmarks to the same site and I differentiate them by name. For example I have `refi` which points to [Reddit Firefox](https://www.reddit.com/r/firefox/new), `remo` which points to [Reddit Mozilla](https://www.reddit.com/r/mozilla/new) and `mdd` which points to [Mozilla Discourse](https://discourse.mozilla-community.org/new). They all appear by their bookmark name in the current new tab page.

![screenshot_20170514-151951](https://cloud.githubusercontent.com/assets/922368/26033683/c185fae8-389f-11e7-9e0c-410368725854.png)

But they all appear as `new` in the new Activity Stream.
![screenshot_20170514-150859](https://cloud.githubusercontent.com/assets/922368/26033651/406552a6-389f-11e7-8b5f-95b1f7494009.png)

This is how my bookmarks look in de desktop bookmark edit window.
![screenshot from 2017-05-14 15-11-24](https://cloud.githubusercontent.com/assets/922368/26033657/5aa971ba-389f-11e7-8caf-cf4b347029ef.png)
![screenshot from 2017-05-14 15-13-55](https://cloud.githubusercontent.com/assets/922368/26033655/5aa7a916-389f-11e7-99c9-12096c38537e.png)
![screenshot from 2017-05-14 15-15-09](https://cloud.githubusercontent.com/assets/922368/26033656/5aa7f060-389f-11e7-9a3c-686e809c498d.png)

Please keep the old behavior. 
Thank you for building the new Activity Stream! It looks really nice so far :D

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @andreicristianpetcu, thanks for the report. However, this repo only represents the work that is being done on the Desktop version of [Activity Stream](https://testpilot.firefox.com/experiments/activity-stream) and not the Mobile one.

Please report your issue in Bugzilla (https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20Android).

**Comment by andreicristianpetcu** [comment]
I reported the bug in Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1370066
