### ISSUE TITLE
Add Pin option to context menu...

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#2596]
...only for Top Sites.

Should it go right below Bookmark? Or?

<img width="263" alt="screen shot 2017-05-15 at 12 30 20 pm" src="https://cloud.githubusercontent.com/assets/36629/26068095/5334cbfc-396a-11e7-93db-9f58cc1415e6.png">

**Comment by tspurway** [comment]
It should go right under 'Bookmark' in the same section

**Comment by jaredkerim** [comment]
Closing this as a duplicate of https://github.com/mozilla/activity-stream/issues/2563
