### ISSUE TITLE
Add telemetry on the "Read More" links for Pocket

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#2600]

**Comment by emtwo** [comment]
This is for any clicks on the links shown in the screenshot here
<img width="783" alt="screen shot 2017-05-15 at 2 09 29 pm" src="https://cloud.githubusercontent.com/assets/784781/26072042/2c46c56e-3978-11e7-9973-2c65eaa69dcd.png">

**Comment by csadilek** [comment]
Fixed with https://github.com/mozilla/activity-stream/commit/6f8f52cde358d9bae6061071f02c452d85aad3ae
