### ISSUE TITLE
Highlights keep sites which I've "Forgotten" 

### ISSUE THREAD

**Issue by fenimore** [mozilla/activity-stream#2604]
Mozilla Firefox 53.0.2
OS: Archlinux

When I use Firefox's feature `Forget` (in the action button spill over menu), website will be deleted from my history, but **Highlights** in the activity stream panel will continue showing those sites.

Steps:
1. Visit site
2. Forget the last 5 minutes
3. Go to Activity Stream

Where does activity streams keep track of the sites I've visited? I assume it doesn't just access my history.

**Comment by piatra** [comment]
I tried to reproduce this issue but the Forget feature seems to work and highlights are not kept around. Can you please confirm if this is still reproducible? Possibly things changed since May.

**Comment by fenimore** [comment]
Hi! I'm trying to reproduce this, but having trouble, namely because I don't know how the highlights section is populated... so it's hard to force it to register a site I've visited.

**Comment by piatra** [comment]
@fenimore Try visiting some article like:
    - https://blog.mozilla.org/blog/2017/06/13/faster-better-firefox/
    - https://blog.mozilla.org/blog/2017/06/14/mozilla-launches-campaign-raise-awareness-internet-health/

They should be picked up by highlights (maybe try a few refreshes). Did the trick for me.

**Comment by jaredkerim** [comment]
Highlights is being deprecated from the Test Pilot addon, which itself is being deprecated in favour of the new System Addon, and as a result this will never be fixed.
