### ISSUE TITLE
Top Sites Editor: Change "Show less" to "Show Fewer"

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2613]
![screen shot 2017-05-18 at 1 38 40 pm](https://cloud.githubusercontent.com/assets/139451/26218115/67484a4e-3bcf-11e7-8a98-b64edadcbed5.png)

Change the button in the Top Sites editor to read “Show Fewer” (note the caps case because it’s a button)

**Comment by morrme** [comment]
I'd like to help with this. I'm guessing both the en-US and en-GB strings should be changed.
