### ISSUE TITLE
Show automigration (datamigration) description on the activity stream page

### ISSUE THREAD

**Issue by gasolin** [mozilla/activity-stream#2616]
Interact with automigrate module to show the migration description on activity stream page

(Correspondent to [bug 1361287](https://bugzilla.mozilla.org/show_bug.cgi?id=1361287))

The flow (defined in [bug 1361286](https://bugzilla.mozilla.org/show_bug.cgi?id=1361286)) (need convert to the redux structure) includes
- Send message in `page.js` to remotepage `aboutNewTab.jsm`(`NewTab:MaybeShowUndoMessage`)
- `page.js` show the migrated description while receive `NewTab:Automigrated` message from `aboutNewTab.jsm`
  - trigger `keep` action (`NewTab:MigrationIsDone`) when user select `Keep It` button
    - hide all messages while receive `NewTab:HideMigrationMessage` message from `aboutNewTab.jsm`
 - show `manual import message` while receive `NewTab:MigrationIsReverted` message
  - trigger `undo` action (`NewTab:UndoAutoMigration`) when user select `undo` button
 - trigger `manual import` action ("NewTab:ManualMigration") when user select `manual import` link

Here's the workflow-correct screencast [bug 1361286](https://bugzilla.mozilla.org/show_bug.cgi?id=1361286)
![](http://g.recordit.co/DdA6RDBlrF.gif)

**Comment by gasolin** [comment]
The flow includes
* async get data from Automate.jsm -> Main -> show on Content, and 
* UI action from Content -> Main -> call Automate.jsm/MigrationUtil.jsm

**Comment by Mardak** [comment]
These are from the [Firefox Desktop May 23 meeting notes](https://wiki.mozilla.org/Firefox/Meeting):

The Automation workflow-correct screencast http://g.recordit.co/DdA6RDBlrF.gif  http://bugzil.la/1361286

- UX spec for Activity Stream is in progress
  - The UI part will be done separately in Activity Stream
  - Skeleton of onboarding overlay system add-on is under review with Mossop. http://bugzil.la/1357005
  - This is a skeleton without tours. Tours will be landed in follow-up bugs.
  - Workflow-correct screencast  : http://g.recordit.co/hzMSeS5EoE.gif
- Under discussion about onboarding tour’s update between different versions.

**Comment by gasolin** [comment]
Here is the more concrete plan after tracing the activity stream code (the rough approach was discussed in photon workweek at toronto):

create `lib/AutoMigrateFeed.jsm`, which
* listen `NEW_TAB_VISIBLE` action in `onAction` method, call `automigrate` module to decide if we need to show the undo message (correspondent to sendAsyncMessage `NewTab:MaybeShowUndoMessage` from page.js in newtab)
* use `dispatch(ac.BroadcastToContent({type: at.AUTOMIGRATE_OOO, data: {}})`; to send action from main to content
* update the reducer accordingly

Default state in `common/Reducers.jsm` will be
```
AutoMigrate: {
    display: false, // control display automigrate message or not
    stage: 0, // show 0: migrated Message or 1: migrationIsReverted Message
    msg: "", // show the message from `automigrate` module if its stage 1
}
```

create `content-src/components/AutoMigrationPrompt/AutoMigratePrompt.jsx` and `AutoMigratePrompt.scss`, which
* display messages based on state
* send click event via `dispatch(ac.SendToMain({type: at.AUTOMIGRATE_XXX}));`
* catch actions and do the job in `lib/AutoMigrateFeed.jsm::onAction` method

@k88hudson does that plan looks like in the right direction?
