### ISSUE TITLE
Pocket Card changes: date, saves

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2620]
Let's add the link date, the number of saves and add the Pocket chevron button to save to your pocket account.  

<img width="246" alt="pocket card" src="https://cloud.githubusercontent.com/assets/25276/26357344/fbd69654-3f9c-11e7-87de-7193b7aa5674.png">

**Comment by pdehaan** [comment]
Friendly reminder, I think in the past w/ Pocket, we'd see some items without a date.
I was trying to browse the returned data from https://getpocket.com/v3/firefox/global-recs?consumer_key=xyz and I only saw one suspicious looking result:

```js
{
  id: 569,
  url: "https://pocket.co/sMTKmt",
  dedupe_url: "http://www.nytimes.com/2017/05/19/business/washington-post-digital-news.html",
  title: "Cookies are Not Accepted",
  excerpt: "We're sorry, we are not able to log you in Terms of Service | Privacy Policy",
  domain: "nytimes.com",
  image_src: false,
  published_timestamp: "0",
  sort_id: 11
},
```

So we may want to try checking for non-zero `published_timestamp` values before converting them to timestamps and displaying them.

**Comment by pdehaan** [comment]
Took a bit of scrolling, but managed to find one example on https://getpocket.com/explore/technology?src=ff_new_tab where the entry doesn't have a displayed date:

<img width="1194" alt="top_articles_and_videos_about_tech_on_pocket" src="https://cloud.githubusercontent.com/assets/557895/26374492/5df205e0-3fba-11e7-954e-36ee9f732c89.png">

**Comment by aaronrbenson** [comment]
Working on a couple more revisions here based on our meeting with Pocket this morning. We discussed running the date label as an experiment, and need the "Trending" label needs to come back. Adding the "Save to Pocket" button is a nice-to-have based on the amount of work needed.

**Comment by mariappopova** [comment]
@emtwo @ncloudioj We want to launch an experiment with the date in the pocket story tile.

**Comment by csadilek** [comment]
@aaronrbenson Hi, there seems to be a new feature in the tiles to differentiate between "New" and "Trending". Can you share some background on this? We're wondering how we'd know what's "New"? Thanks.

**Comment by aaronrbenson** [comment]
@csadilek Yeah, the "new" context label would show trending items that are dated within the last 24 hours. This might help to clue people into more "breaking" stories vs. trending topics.

**Comment by csadilek** [comment]
Based on the discussion on Monday, the only planned task is adding the differentiation between "new" (< 24hrs) and "trending" tiles. Given we can get the "new" icon from @aaronrbenson, I think we can schedule this for the next release (Bridge of the River Kwai).

Note that some tiles don't have a publication date set when retrieved from Pocket's backend. Therefore these tiles will show up as "trending" and never as "new".

**Comment by csadilek** [comment]
If this feature is still desired and when the icon is ready the functionality is ready in this branch: https://github.com/csadilek/activity-stream/tree/2620

**Comment by aaronrbenson** [comment]
We're not doing this in the foreseeable future. Closing.
