### ISSUE TITLE
Sections A/B Test

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2624]
Let's start an experiment to test the engagement of the new Sections UI.  The control should be Highlights, and the variant should be the new Bookmarks and Visit Again Sections

**Comment by piatra** [comment]
Is this in any way related to https://github.com/mozilla/activity-stream/issues/2649?

**Comment by rlr** [comment]
This was going to be an A/B test with the test pilot population. But as discussed in the product meeting on Monday, we won't be doing it anymore.
