### ISSUE TITLE
Implement "Card" component (formerly known as Spotlight) in system add-on

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#2625]
This refresh affects card titles (domain names, uppercase), timestamps, and overall height change of Recent Bookmark and Visit Again cards.

<img width="548" alt="image" src="https://cloud.githubusercontent.com/assets/25276/26376418/6970ecd6-3fda-11e7-9dc7-c99d79c6d0f9.png">

**Comment by piatra** [comment]
Talked to @aaronrbenson, a new spec for this is in progress.

**Comment by aaronrbenson** [comment]
This was part of a design path that removed the context clues from the cards. Since we're not removing the context clues after all, I'm closing this.
