### ISSUE TITLE
"Save to Pocket" option in context menu does nothing because pocket icon is unavailable on about:newtab

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#2626]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1385418

[Affected versions]:
- Firefox 53 and up
- Activity Stream Build: 1.12.0-dev-1495540530-3c17cad

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- The "extensions.@activity-streams.showPocket" pref from about:config is set to true.
- The Pocket button has been removed from the browser toolbar. 

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the context menu button for one of the Highlights or Top Stories tiles.
3. Observe the "Save to Pocket" option.
 
[Expected results]:
- The option is greyed out.

[Actual results]:
- The option is not greyed out and nothing happens if it is clicked.

[Notes]:
- Attached a screen recording of the issue:
![save to pocket should be greyed out](https://cloud.githubusercontent.com/assets/18304511/26406744/da753898-40a1-11e7-8858-1007cbc35827.gif)

**Comment by tspurway** [comment]
If Pocket is disabled in the browser, we should also disable (grey out) all "Save to Pocket" controls in AS

**Comment by Mardak** [comment]
I believe this `Pocket.savePage` is what's called:
https://dxr.mozilla.org/mozilla-central/source/browser/extensions/pocket/content/Pocket.jsm#74

**Comment by Mardak** [comment]
There was some discussion that the Photon work is moving Pocket into the page action menu:
https://bugzilla.mozilla.org/show_bug.cgi?id=1363188
https://mozilla.invisionapp.com/share/ENBBK0F9U#/screens/230998673

So perhaps it won't be fully removable anyway as it'll be in the menu or in the location bar.

**Comment by sarracini** [comment]
See conversation in #3107

**Comment by sarracini** [comment]
After chatting with @bryanbell about this, the meatball menu will always be available in pages (right now it's been removed from about:newtab but that looks like a bug), so there will always be the option to save to pocket that way. Currently because the meatball menu is missing from about:newtab the context menu action for saving to pocket does nothing (as reported in #3107) so let's re-purpose this bug to be fixing the bug addressed in #3107

**Comment by sarracini** [comment]
Bug reference for adding the meatball menu (it has a real name: Page Action Menu) back into about:newtab and about:home : https://bugzilla.mozilla.org/show_bug.cgi?id=1388528

**Comment by Mardak** [comment]
gijs/adw APIs need to be rewritten to work whether visible or not.

**Comment by Mardak** [comment]
Work will be done in https://bugzilla.mozilla.org/show_bug.cgi?id=1385418 with "The Pocket panel/doorhanger should open on the site identity icon in that case."

**Comment by sarracini** [comment]
https://hg.mozilla.org/integration/autoland/rev/397fe94c67f1

**Comment by sarracini** [comment]
Closing this as this should now be fixed with: https://hg.mozilla.org/mozilla-central/rev/397fe94c67f1 

we can re-open if there are any other issues
