### ISSUE TITLE
The context menu is not dismissed when a tile is dragged

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#2633]
[Affected versions]:
- Firefox 53 and up
- Activity Stream Build: 1.12.0-dev-1495651999-23f96c2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream dev add-on version was previously installed on a profile with history.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the context menu button for one of the tiles.
3. Drag a different tile and observe the context menu.
 
[Expected results]:
- The context menu is dismissed.

[Actual results]:
- The context menu stays in it's place.

[Notes]:
- Attached a screen recording of the issue:
![context menu is not dismissed when a tile is dragged](https://cloud.githubusercontent.com/assets/18304511/26453495/a1fd7ca2-416c-11e7-9071-17e97b90e22c.gif)

**Comment by rlr** [comment]
fix just landed

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is still reproducible on the latest version (installed from https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html).
If you drag a different Top Sites, Highlights or Top Stories tile than the one with the context menu, the menu remains open.
If you drag the same Top Site which has the context menu open, then the menu is correctly dismissed. However in the case of Highlights and Top Stories the menu is not dismissed.

**Comment by tspurway** [comment]
let's close this and re-test when implemented on the system add-on
