### ISSUE TITLE
Links dragged and dropped over a Top Site tile breaks that tile

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#2634]
[Affected versions]:
- Firefox 53 and up
- Activity Stream Build: 1.12.0-dev-1495651999-23f96c2

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- The "extensions.@activity-streams.showPocket" pref from about:config is set to true.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Drag a Highlight tile over a Top Sites one and release the mouse.
3. Observe the tile.
 
[Expected results]:
- The Top Site is not replaced by anything.

[Actual results]:
- The Top Sites tile is replaced with a random background color and no other text.

[Notes]:
- The issue is also reproducible if you drag a link over a Top Sites tile or a file from desktop.
- If a broken tile is dragged in a different position, after a few seconds (~20) the page is refreshed and only the default Top Sites are displayed.
- Attached a screen recording of the issue:
![links break top sites tiles if they are dragged over them](https://cloud.githubusercontent.com/assets/18304511/26452871/441ad924-416a-11e7-8d75-4c2a52bbc0d2.gif)

**Comment by rlr** [comment]
oh wow. fixing.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest Activity Stream build. (installed from https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html)
