### ISSUE TITLE
Pocket info modal needs a faster fade-in-out

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#2637]
<img width="661" alt="blank_skitch_document" src="https://cloud.githubusercontent.com/assets/557895/26472574/97fd2ec0-415b-11e7-8ff5-13161ec817c8.png">

<img width="612" alt="add-ons_manager" src="https://cloud.githubusercontent.com/assets/557895/26472597/b8379504-415b-11e7-9724-8b58d440b2a4.png">

---

I was trying to bookmark one of the Pocket recommendations then decided to unbookmark it, but overshot the (&hellip;) button and accidentally hovered over the Pocket (?) icon.
After mousing off the (?) I tried again to hover over the Pocket card and select Unbookmark from the (&hellip;) menu, but the Pocket menu keeps popping up as soon as I hover over the card's image. It seems like I need to mouse off the card for a good 1+ seconds in order to have that Pocket info modal fully disappear.

<img width="393" alt="new_tab" src="https://cloud.githubusercontent.com/assets/557895/26472769/6032d3b8-415c-11e7-81bb-187fc667a009.png">

**Comment by csadilek** [comment]
Agreed. I've send a PR to speed up the animation: https://github.com/mozilla/activity-stream/pull/2642

![take7 mov](https://cloud.githubusercontent.com/assets/472523/26511385/caafcace-422f-11e7-83ea-a23744a438c7.gif)

**Comment by csadilek** [comment]
Fixed with 6ef1b3c9df066829e7388aeb6e660ec0379007b5
