### ISSUE TITLE
switch test-merges.js to use child_process.execFile

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2643]
Right now, there are some uses of ShellJs.exec(), which allows shell-interpolation in incoming data which can lead to injection attacks.  The amount of dirty data we currently have is small, and corrupting it would be non-trivial (eg getting GitHub to return a bogus commitID with shell crud in it).  Fixing this should be straightforward.

**Comment by dmose** [comment]
(An example of this was already fixed in #2638, the small number of remaining fixes should be very similar.)

**Comment by Mardak** [comment]
This is only running on dmose's machine and he says it shouldn't matter
