### ISSUE TITLE
Figure out pref-on infrastructure for Fx56

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2644]
We need to figure out how we're going to do a staged pref on rollout in nightly.  Shield may be able to make this as simple as logging into Normandy and clicking a few buttons, in which case we can just use that.  If that is not ready, then we will write code to implement this ourselves.

**Comment by jaredkerim** [comment]
It looks like there is a Shield pref flipping mechanism that we can use.  The process is documented here:

https://docs.google.com/document/d/16bpDZGCPKrOIgkkIo5mWKHPTlYXOatyg_-CUi-3-e54/edit#

**Comment by k88hudson** [comment]
Changing this to refer to Fx56 (release) since we're just going to pref on normally in nightly

**Comment by sarracini** [comment]
@jaredkerim how can we prioritize this? will this be done this week?

**Comment by jaredkerim** [comment]
We know we are using Shield to do this and how to do it so I'm closing this.
