### ISSUE TITLE
switch AboutRedirector to URI_SAFE_FOR_UNTRUSTED_CONTENT for about:newtab

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2646]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1021667
This came up at the security review, and will drop any unnecessary privs we have.  We may need to punch a few smaller holes back in, the way about:home currently does.

**Comment by dmose** [comment]
(This will need to (at least partly) happen in a bugzilla bug, since it's mozilla-central code).

**Comment by k88hudson** [comment]
This is done, right?

**Comment by Mardak** [comment]
Maybe you're thinking of `URI_MUST_LOAD_IN_CHILD` https://bugzilla.mozilla.org/show_bug.cgi?id=1365643

The only other flag right now is `ALLOW_SCRIPT`
https://hg.mozilla.org/mozilla-central/file/tip/browser/components/about/AboutRedirector.cpp#l92

**Comment by sarracini** [comment]
Bug ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1021667

**Comment by sarracini** [comment]
This is in the process of landing with: https://hg.mozilla.org/integration/autoland/rev/6726399b5bbb

Closing this :D

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/6726399b5bbb

**Comment by Mardak** [comment]
Filed #3013 and #3014 followups
