### ISSUE TITLE
Revive Shield Study addon wrapper code

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2649]
We need to blow the dust off of the shield study code which wraps the addon in the shield study layer for:

- starting the addon
- selecting variants (the exact variants right now are unclear, so to start just have two variants: control (tiles with monkeypatched telemetry) and activity stream
- uninstalling it after the study is complete
- monkey patching tiles for rich telemetry

The commit that has all the relevant code is here:

https://github.com/mozilla/activity-stream/commit/1258e6c9b292a0e4b22985fb5a543cf797e193b2

So this needs to be rebased onto master, updated, and then tested in the following versions of Firefox: 54, 55.

We also need to make sure that this study can survive an update from 54 to 55, so figure out if there's any way to get 54, install the shield study addon on it, then force it to update to 55 somehow, and make sure the study continues to function as expected.  

The tiles telemetry monkey patching will only work in 54 and not 55, so we need to make sure that if someone has the study addon installed in 54 and the tiles telemetry is monkey patched, and then their browser updates, that the telemetry just quietly goes away but that the study continues to exist and not crash horribly.

@sarracini is available for mentorship on this because she wrote most of this code, but her time is precious so be sparing in your requests.

**Comment by jaredkerim** [comment]
There have been some changes in MC to the Tiles infrastructure which might preclude attaching monkey patched telemetry (at least in the way we did for the last shield study) in ffox55+.  See if there's any way to rework that telemetry patching so that it works in 55+ so that we can still track telemetry after users update.

**Comment by sarracini** [comment]
This is done!
