### ISSUE TITLE
send perceived about:home load_trigger="first_window_opened" telemetry

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2658]
Whenever possible, an about:home load should set the session ```load_trigger``` timestamp, and should also set the ```load_trigger_type```.    As of this writing, the exact data format is still under discussion, and https://github.com/mozilla/activity-stream/pull/2660/files is the current draft.

**Comment by Mardak** [comment]
To actually measure the load, we need to load about:home with #2598

**Comment by dmose** [comment]
mozilla/ping-centre#84 is the related dashboarding bug for this.

**Comment by dmose** [comment]
This has a PR that's ready for data review, but not yet for code review, and I'm too fried to finish it tonight.

**Comment by dmose** [comment]
Fixed by #3552
