### ISSUE TITLE
send Hero Element (TopSites) painted telemetry

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2661]
This will (approximately) be adding ```top_sites_painted_ts``` to the session telemetry.  

Note that doing it will be a bit fun.  My suspicion is that the right way to do it is to look at the technique described in http://stackoverflow.com/a/34999925, but to use two requestAnimationFrame's as suggested by https://github.com/mozilla/activity-stream/issues/2005#issuecomment-298095620 since rAF is less likely to jank than setTimeout.

**Comment by dmose** [comment]
As of this writing, the exact data schema is still being sorted out in https://github.com/mozilla/activity-stream/pull/2660/files.

**Comment by tspurway** [comment]
This is a measure of the time to when TopSites are available for interaction

**Comment by dmose** [comment]
There's a user story for the dashboarding of this in #2838.

**Comment by dmose** [comment]
I've filed #2965 to track the performance of filling in the screenshots for the times when a tab needs that.
