### ISSUE TITLE
send search box input latency telemetry

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2663]
Which is to say, the time between keystroke and character visibility.

As of this writing, the data format has yet to be proposed; https://github.com/mozilla/activity-stream/pull/2660/files should have an up-to-date schema.  Maybe we want the latency distribution for all characters typed?  Maybe something less comprehensive than that.  

@digitarald Do you have any suggestions here?

**Comment by digitarald** [comment]
Measuring the frequency of outliers would probably be a good start for this. As an easy threshold, for typing you want to stay under 100ms to have it feel instant. The metric to be reported back to your analytics would be `% of inputs that took over 100ms`.

After understanding the data, you could report on top of this an aggregate as "% of sessions with 20% of inputs taking longer than 100ms" as trend-able metric. Examples can be found in the [Android monitoring dashboard](https://support.google.com/googleplay/android-developer/answer/7385505).

**Comment by dmose** [comment]
@digitarald The Android dashboard is super interesting & helpful; thanks for the link!  When you say "inputs" above, is that a synonym for "keystrokes", or do you mean something else?

**Comment by digitarald** [comment]
>  When you say "inputs" above, is that a synonym for "keystrokes", or do you mean something else?

For this case inputs would be keystrokes, yes. Just wanted to keep it more general. In other cases of frequent inputs, like scrolling, the same aggregation might be applied though.

**Comment by sarracini** [comment]
We no longer want to collect this

**Comment by Mardak** [comment]
input boxes are plain html no special stuff we're doing here
