### ISSUE TITLE
send telemetry for latency between keystroke and autocomplete dropdown

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2664]
Which is to say, I think, the time between a single keystroke and the autocomplete drop-down 
having finished painting.  Note that #2663 is related to this.

https://ux.stackexchange.com/a/36235 has some interesting reading about implementation itself.

As of this writing, the data format has yet to be proposed; https://github.com/mozilla/activity-stream/pull/2660/files should have an up-to-date schema. Maybe we want the latency distribution for all characters typed? Maybe something less comprehensive than that.

Perhaps @phlsa or @digitarald have thoughts here?

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448353
