### ISSUE TITLE
telemetry data for bad states

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2672]
We need to notice if topsites or highlights data is ready too late (i.e. later than the (first?) call to that component's render method).

Schema work is still in progress, and is happening in #2653 and https://github.com/mozilla/activity-stream/pull/2660/files

My guess is that we'll want to only report top_sites_data_ready_ts and highlight_data_ready_ts if they happen too late.

**Comment by k88hudson** [comment]
I feel like the bad app state telemetry might be little over-verbose in the test pilot add-on (for missing images, for example) let's look at auditing that for the nightly version

**Comment by piatra** [comment]
Topsites seems to have [a component](https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/components/TopSites/TopSitesPerfTimer.jsx) for handling performance events. Do we want to make a similar component for Sections? (Building a higher level component to handle both seems out of scope).

**Comment by dmose** [comment]
@piatra at this point, whatever is easiest, given the time.  You're totally right that the slightly longer term solution is to build a higher-order component.  I guess one advantage to building a separate such component for Sections would be that, when the time comes to build the higher-order component, we'd have two components to look at so we'd be able to see the requirements more clearly.
