### ISSUE TITLE
[meta] make plans for synthetic performance tests

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2675]
The intent here is stuff to run both in CI as well as locally for desktops for faster, better feedback loops than just using Real User Measurement data from telemetry.  There's a fair bit of discussion of the various options in #2005.

**Comment by dmose** [comment]
Ideally, these would just be identical to the data collected remotely, but run in a benchmarking harness, perhaps even talos.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448355
