### ISSUE TITLE
Last Pocket card overlaps with the first history card

### ISSUE THREAD

**Issue by FLamparski** [mozilla/activity-stream#2677]
See attached:

![image](https://cloud.githubusercontent.com/assets/912935/26820884/62f72236-4a9c-11e7-923a-c64e4143796f.png)

This change seems to fix the overlapping cards, but the third Pocket card is now in its own row with space in the first row:

```diff
/* .pocket-stories ul.spotlight-list */
-height: 320px;
+min-height: 320px;
```

![image](https://cloud.githubusercontent.com/assets/912935/26820974/add97ede-4a9c-11e7-981c-90f90535f964.png)

Additionally giving `width: 100%` to `.pocket-stories > .spotlight-list` fixes that.

**Comment by csadilek** [comment]
Thanks for reporting this!
