### ISSUE TITLE
Add a "show blank page" equivalent preference for activity stream

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2683]
Right now, we don't have an equivalent of the "Show blank page" preference on New Tab – the only way to replicate this is to turn each section off one-by-one. We might want to consider a more straight-forward way for users to express that they never want to see content on the new tab page:

- With sections, turning every preference off could require 8+ clicks (that's a lot to ask)
- new sections that are added in future releases will keep showing up, and users will have to turn them off
- users might want to keep their certain set of preferences but temporarily hide activity stream for a short time (e.g. during a presentation)

**Comment by aaronrbenson** [comment]
Some thoughts around this are attached so we can discuss a) if this is a feature we want to include and b) which design works best. 

![show_blank_page](https://user-images.githubusercontent.com/139451/27043160-d46dee2e-4f5e-11e7-8058-c20a582bb984.png)

**Comment by aaronrbenson** [comment]
Per a discussion in the UX call, the product team is going to hold off on adding this feature for a few reasons:

- In our latest diary studies we didn't find that anyone wanted to customize their new tab to be a blank page. 
- Firefox already has the ability to set a blank page in Preferences
- We'd like to monitor telemetry data about whether a significant number of the population actually turns off all the sections before adding a setting in the prefs panel.

**Comment by jenniferdavidson** [comment]
To add to @aaronrbenson's comment, we had 9 participants in a daily diary study in May - June 2017. After using Firefox as their main browser for 4 days with Activity Stream New Tab installed, we asked them to customize the New Tab how they wished. No participants wanted a blank page, and in fact one participant said "I don't want it to be completely dead." - P9. The most 'minimalist' customization we saw was a participant who just wanted the Search and Top Sites. 

Here's a trello card with a link with more inforamtion and a link to the full report: https://trello.com/c/nU66nkN6.
