### ISSUE TITLE
implement rest of load_trigger_type telemetry for newtab

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2685]
After #2539 lands, there will still be a bunch of other ways to trigger newtab loads that we need to send telemetry for.  Until we do this, we won't be able to compute most of the interesting data we need for other telemetry for a fair number of new tabs, as these bits of data are the starting point that we need to subtract out.

I don't think this needs a dashboard user story, as it's really just plumbing for most of the rest of the perf telemetry.

As of this writing, those look likely to be:

```
    "session_restore" | // home or newtab
    "url_bar" | // home or newtab
    "refresh"  // home or newtab
```

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448356
