### ISSUE TITLE
Scrollbar placeholders are displayed when there is no scrollable content in "New Tab Preferences" menu

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2690]
**[Affected versions]:**
- Firefox 53 and up
- Activity Stream Build: 1.13.0-dev-1496953578-4e27f4b

**[Affected Platforms]:**
- All Windows
- All Linux

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Maximize the browser window.
3. Click the "Customize your New Tab page" gear wheel button from top-right corner of the page.
4. Observe the "New Tab Preferences" menu.
 
**[Expected results]:**
- When there is no scrollable content the scrollbars are not displayed. 

**[Actual results]:**
- The scrollbar placeholder is displayed even if there is no scrollable content.

**[Notes]:**
- This issue is not reproducible on Mac OS.
- Attached a screenshot of the issue:
![scroll bars](https://user-images.githubusercontent.com/9248513/26966339-4e3f47e8-4d02-11e7-84b3-a3245f9e48cc.jpg)

**Comment by rlr** [comment]
gah. need to do `overflow-y: auto;` instead of `overflow: scroll;` fixing

**Comment by rlr** [comment]
this already landed. 41f5d69ced3bb2cdaf6263066047dfed9bf273b3

**Comment by Softvision-VladBacia** [comment]
This issue has been verified on A-S 1.14.0-dev-1497551877-9d19af4 and I cannot reproduce is. Thus marking this as Verified-Fixed.
