### ISSUE TITLE
Switch over Telemetry endpoint in system add-on and turn on telemetry by default

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2694]
When we get the new endpoint for the system add-on, we should change it in the prefs config and set telemetry to be on my default.

**Comment by ncloudioj** [comment]
@k88hudson @dmose 

FYI, the new endpoint for system addon is up and running in stage, feel free to enable telemetry and hammer it. Next we'll deploy the database change as well as ETL jobs, so that we can test it as a whole in stage.

https://onyx_tiles.stage.mozaws.net/v4/links/activity-stream

**Comment by ncloudioj** [comment]
A quick update:

We're deploying the database schema as well as the ETL jobs to stage now, should be available shortly. Do you want to do an end-to-end telemetry test in stage at any point? @k88hudson @dmose
