### ISSUE TITLE
Perma-orange: browser_ext_tabs_onUpdated.js Check changeInfo.url Expected: about:blank

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2696]
Since treeherder started up again May 25, these (related?) tests have been consistently failing:

```
 FAIL | browser/components/extensions/test/browser/browser_ext_tabs_onUpdated.js | Check changeInfo.url - Expected: about:blank, Actual: about:newtab
Stack trace: onUpdated@moz-extension://76a1f775-a2ba-48be-9b0e-f4a2ca63744d/%7Bfcfe82ca-8e3a-478a-8861-15c3e8156f69%7D.js:9:11
```
https://treeherder.mozilla.org/logviewer.html#?job_id=106084414&repo=pine&lineNumber=3414

```
FAIL | browser/components/extensions/test/browser/test-oop-extensions/browser_ext_tabs_onUpdated.js | Check changeInfo.url - Expected: about:blank, Actual: about:newtab
Stack trace: onUpdated@moz-extension://c6f783e9-1140-423d-a1ce-96719b075793/%7B42fa115d-aef0-4ece-ab30-49212d5f3b52%7D.js:9:11
```
https://treeherder.mozilla.org/logviewer.html#?job_id=106084384&repo=pine&lineNumber=3555

**Comment by Mardak** [comment]
@dmose I bisected this to the MUST_LOAD_IN_CHILD https://bugzilla.mozilla.org/show_bug.cgi?id=1365643

That specific test line was last touched by https://bugzilla.mozilla.org/show_bug.cgi?id=1227462

**Comment by dmose** [comment]
Oh, the irony.  :-)

**Comment by Mardak** [comment]
Looks like about:newtab is being preloaded and triggering an update, so if I modify the test to not immediately remove the listener, it actually does get the about:blank update next.

**Comment by sarracini** [comment]
@k88hudson and I found out that these sort of test failures are going to happen a lot now since we're preloading in a content process. This is something we should look at as a general case, it may fix a whole whack of tests at a time

**Comment by dmose** [comment]
I'm not so sure it's being preloaded, although it's possible.  Some debugging seems to show that we don't get above two tabs (the first one in the new window, and the one created by the test).  Although I guess it's possible that the webextension browser.tabs.query API isn't exposing the preloaded thing, but the browser.tabs.onUpdated callback is.  More as it sorts.

**Comment by dmose** [comment]
After further investigation, from what I can tell, none of these tabs are preloaded.  So my next suspicion for the source of the problem is that about:newtab is running in a content process rather than the main process.  That said, another possibility is some semantic difference between tiles and activity stream.

**Comment by Mardak** [comment]
The test started failing from `MUST_LOAD_IN_CHILD` so it was passing before even with the differences between tiles and activity stream. Maybe something to check is if somehow tiles is loaded in child as well? Although not entirely sure how that will help…?

**Comment by dmose** [comment]
My assumption is that there is probably some race condition that we're losing when whatever impl of newtab is loaded in the child.  But we'll see...

**Comment by dmose** [comment]
This is definitely a race.  Excitingly, running with --jsdebugger causes it to be hit much less often.  And when it is hit, also excitingly, the `debugger` statement in the appropriate spot doesn't actually cause the code to break in the debugger.  :-/

**Comment by Mardak** [comment]
Will need to be addressed later now that content process is being backed out in #2756 but will need to be fixed to turn it back on for #2777.

**Comment by sarracini** [comment]
Tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1377358

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/39754f1db01c
https://hg.mozilla.org/mozilla-central/rev/8ecee4458990
