### ISSUE TITLE
Perma-orange: browser_background_tab_crash.js

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2697]
```
TEST-UNEXPECTED-FAIL | browser/components/sessionstore/test/browser_background_tab_crash.js | uncaught exception - TypeError: aTab is undefined at _insertBrowser@chrome://browser/content/tabbrowser.xml:2244:1
```
https://treeherder.mozilla.org/logviewer.html#?job_id=106084424&repo=pine&lineNumber=2902

**Comment by k88hudson** [comment]
Ok, so far I have tracked this down to the following line failing to find a tab for a particular browser and returning `undefined`:

https://dxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#1805

**Comment by k88hudson** [comment]
The fix for this bug will close this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1373271

**Comment by Mardak** [comment]
Fixed https://hg.mozilla.org/mozilla-central/rev/761383b60ca2
