### ISSUE TITLE
Display bookmark title instead of places title for Recent Bookmarks section

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#2702]
Update places provider query for `getBookmarks` (maybe other places as well?) to return `moz_bookmarks.title` instead of `moz_places.title` because the two can be different.

**Comment by piatra** [comment]
@aaronrbenson Any design concerns here? Using the original page title vs the title the user gave to the bookmark?

**Comment by aaronrbenson** [comment]
No concerns here. Great fix!

**Comment by piatra** [comment]
Closing this because priorities have shifted to the system addon, going to be implemented there.
