### ISSUE TITLE
Topsite Drag and Drop produces unpredictable results

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2704]
AS Version:

Build: 1.13.0-dev-1497278874-89a6711

Steps to reproduce:

<img width="831" alt="screenshot 2017-06-12 12 02 48" src="https://user-images.githubusercontent.com/119884/27043111-1986b358-4f67-11e7-85a0-2df7d7fe397d.png">

Drag rightmost topsite over the one to its left

Expected result: Those two swap, nothing else changes.

Actual result: ¯\_(ツ)_/¯

<img width="853" alt="screenshot 2017-06-12 12 02 58" src="https://user-images.githubusercontent.com/119884/27043205-54e3e95c-4f67-11e7-86c6-1f297a75360b.png">

Where did Netflix go?  Why is there two Githubs?

**Comment by rlr** [comment]
Hmm, there must be something else going on. It doesn't make sense that apparently your fourth slot got unpinned when you dragged from 6 to 5. Can you reproduce at will or was it a one time thing?

Look at me swap all day 😄 

<img src="https://d2ppvlu71ri8gs.cloudfront.net/items/2h3w330H1A062o2r2a1P/Screen%20Recording%202017-06-12%20at%2012.38%20PM.gif" />

**Comment by jaredkerim** [comment]
Closing this as a wont fix for the testpilot addon.
