### ISSUE TITLE
Adjust click targets for headers and editing Top Sites

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2712]
https://cl.ly/2739251T072y

Problem: The click target for the header runs wide. If you click just outside of the "Edit" link it collapses the section and is disorienting.

The click target for headers should be around the header text and collapse arrow only.

**Comment by piatra** [comment]
Opportunity to combine bug https://github.com/mozilla/activity-stream/issues/2709 with this one.
