### ISSUE TITLE
Layout glitch for Pocket/Highlights/Bookmarks

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2717]
Addon version: 1.14.0-dev-1497380233-50935e3
Firefox version: 54 release on OSX

<img width="807" alt="screen shot 2017-06-13 at 9 11 57 pm" src="https://user-images.githubusercontent.com/1455254/27111313-529cce72-507d-11e7-904b-c37a2584f850.png">

**Comment by csadilek** [comment]
This affects Highlights as well: PR and details here: https://github.com/mozilla/activity-stream/pull/2716
