### ISSUE TITLE
dashboard for load_trigger_ts - visibility_event_rcvd_ts for load_trigger_type of menu_plus_or_keyboard

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2725]
### User Story
_As a developer, I see dashboards for both new_tab_preloaded=false and newtab_preloaded=true with the distribution (or percentiles?) of the time taken between the perceived trigger of loading a new tab and when the visibility event for that tab is received, for when the load was trigger by the menu entry, the plus button, or the keyboard shortcut, so that I have a sense of how long it takes for the user to be shown something, both on preloaded and non-preloaded tabs._

This is a first cut at a description of what I suspect we want.  This probably wants some thoughts (or maybe a vidyo chat) with @emtwo to dig into whether these are the visualizations that we really want.

Note that this depends on #2539 and #2726 for some of the telemetry.

**Comment by emtwo** [comment]
@dmose - could you link the dashboards that you're referring to with new_tab_preloaded?

These visualizations do sound like something we want. It might take some exploration/fiddling with the data before confirming.

**Comment by dmose** [comment]
Sorry for the confusion: I tend to write user stories in the present tense; I'll mark it up to be more clear.

No dashboards exist; the idea is that we probably want two, since the data is likely to be very different depending on whether the tab is preloaded or not.

**Comment by Mardak** [comment]
https://sql.telemetry.mozilla.org/dashboard/activity-stream-system-addon-performance
