### ISSUE TITLE
Perma-orange: assertNoUncaughtRejections "session is undefined" - add error-handling & test for mark underflows in TelemetryFeed.jsm

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2728]
It's possible (particularly in cases that we haven't implemented yet, but also potentially otherwise), for TelemetryFeed.addSession to try and execute  

```js
absBrowserOpenTabStart =
      perfService.getMostRecentAbsMarkStartByName("browser-open-newtab-start");
```

And find that there are no recent marks with that name.  Right now, it explodes; it should detect this and handle it gracefully.

**Comment by Mardak** [comment]
This seems to be causing perma-orange on `browser/components/search` tests:

https://treeherder.mozilla.org/logviewer.html#?job_id=110254801&repo=pine&lineNumber=12567

```
02:54:26     INFO -  539 INFO Console message: [JavaScript Error: "TypeError: session is undefined" {file: "resource://activity-stream/lib/TelemetryFeed.jsm" line: 138}]
02:54:26     INFO -  Buffered messages finished
02:54:26    ERROR -  540 INFO TEST-UNEXPECTED-FAIL | browser/components/search/test/browser_amazon_behavior.js | A promise chain failed to handle a rejection: session is undefined
```

**Comment by Mardak** [comment]
Fixing this perma-orange might reveal some intermittent failures, e.g.:

```
LOG ERROR | TEST-UNEXPECTED-FAIL | browser/components/sessionstore/test/browser_394759_purge.js | application terminated with exit code 1 [log…]
CRASH | browser/components/sessionstore/test/browser_394759_purge.js | application crashed [@ PLDHashTable::Iterator::Iterator(PLDHashTable *)] [log…] 
```
https://treeherder.mozilla.org/logviewer.html#?job_id=110250858&repo=pine&lineNumber=3539
https://treeherder.mozilla.org/logviewer.html#?job_id=110250858&repo=pine&lineNumber=3550

**Comment by Mardak** [comment]
This type of test failure is happening on a lot of `browser-chrome` runs, so fixing this is probably relatively higher priority as it might uncover other tests that happen to not run correctly in the rest of the set.

**Comment by Mardak** [comment]
Chatted with @emtwo and @ncloudioj about what to do with these unexpected pings without sessions, and they agreed that the ping should still be sent in a way that can be identified as missing the usual session start. We can then track if this is happening more than we expect and fix things.
