### ISSUE TITLE
Reduce impact / extra memory overhead of new tab preloading

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2730]
Gabor mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1372664 that it might be problematic to always consume an extra content process when we preload a new tab. We might want to consider taking advantage of the existing preloaded content process / merge the strategy for preloading new tab and preloading content processes.

Related/relevant code here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1341008
http://searchfox.org/mozilla-central/source/dom/ipc/PreallocatedProcessManager.cpp

**Comment by Mardak** [comment]
The regression appeared as https://bugzilla.mozilla.org/show_bug.cgi?id=1381804 and is acceptable. Also see #2894
