### ISSUE TITLE
Make activity-stream to be a webextension for Nightly 57 (and earlier)

### ISSUE THREAD

**Issue by TerraX-net** [mozilla/activity-stream#2731]
What are your plans on this?

I was surprised that
https://moz-activity-streams.s3.amazonaws.com/dist/latest.html and
https://s3.amazonaws.com/moz-activity-streams-dev/dist/latest.html
do not work with
extensions.legacy.enabled;false
extensions.interposition.enabled;false
although that prefs are important to test OOP addons effectively etc.
https://developer.mozilla.org/en-US/Add-ons/Overlay_Extensions

And how is it possible that browser.newtabpage.activity-stream.enabled works with that flags: Is this already a webextension? Thank you.

**Comment by jaredkerim** [comment]
@TerraX-net Thanks for bringing this up I know it's confusing, to clarify:  The existing version of Activity Stream is a jetpack addon in test pilot, or a 'legacy addon' in this context, and will no longer function after legacy addons are disabled in ffox57.  We are in the process right now of rewriting all of activity stream as a privileged system addon:

https://github.com/mozilla/activity-stream/tree/master/system-addon

Which will function post ffox57, and the SDK legacy addon that lives in Test Pilot right now will be completely deprecated.  The UI and functionality will be the same (and most of the frontend will just be ported right over) but all the backend stuff is being rewritten.  I hope this helps answer your question, let me know if you need any other information!
