### ISSUE TITLE
Collect Tiles Metrics

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#2736]
While the upcoming shield study will be easily comparable to the last study, there is one big disadvantage still: we know for a fact that the **Test Pilot Activity Stream is less performent than Tiles** and that this has a **significant impact on its engagement**. We can only make estimates about how likely we are to close the gap with performance improvements in the system addon.

To make more accurate claims about Activity Stream vs. Tiles engagement, we need to collect engagement metrics for Tiles and directly compare them to the system addon when we turn it on by default.

**Comment by sarracini** [comment]
Closing this since we decided not to do this.
