### ISSUE TITLE
Decrease the spacing in search/topsites/pocket so two rows can fit with pocket on a small screen

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#2738]
This is to mitigate lost clicks on Pocket

**Comment by tspurway** [comment]
1344 x 768 = "small screen"

**Comment by aaronrbenson** [comment]
The attached design tightens up the space between the sections and uses a different thumbnail image (closer to a 16:9) to bring the Pocket story headlines above the 768px "fold". I tried experimenting with alternate card designs for the Pocket stories but I fear making them different than the other cards makes them look even more like paid advertisements; of which they are not and we are expressly trying to avoid that impression.

![screen shot 2017-07-12 at 11 35 24 am](https://user-images.githubusercontent.com/139451/28128767-7fdb2e1c-66f6-11e7-89aa-85535669afc5.png)

**Comment by Mardak** [comment]
Looks like the latest specs are here with 40px between sections:
https://mozilla.invisionapp.com/share/QBD5BOJMJ#/screens/249812144_New_Tab_-_Section_Measures
