### ISSUE TITLE
Filter out top sites below a certain frecency threshold

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#2739]
This is to handle issues when user history is too minimal to determine good top sites.

**Comment by Mardak** [comment]
Sounds like we want to filter out sites that the user only visited once or just a couple times. The experiment can test with multiple values.

A visited page gets a frecency of 100 while a page that the user typed from the location bar gets a much higher score as if the user visited 10+ times.

So one threshold can be "more than 100" to have at least 2 visits. And if we want to prefer typed pages, a threshold of at least 2000 (inclusive) to see how this behaves, but to be clear, for those who don't type in urls/domains, it can be slow to get to 20 visits depending on browsing behavior.

**Comment by piatra** [comment]
This became relevant for system addon as well and I doubt we'll try this in Test Pilot.
