### ISSUE TITLE
Recent Bookmarks section showing incorrect/old bookmarks

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2748]
My recent bookmarks currently looks like: 

![screen shot 2017-06-21 at 2 03 18 pm](https://user-images.githubusercontent.com/139451/27406373-3eb76502-569a-11e7-8ba2-c88044032a88.png)

When I would expect to see the top three out of this list instead:

![screen shot 2017-06-21 at 2 35 14 pm](https://user-images.githubusercontent.com/139451/27406391-4ada5fe2-569a-11e7-8e8c-549c6237f813.png)

**Comment by piatra** [comment]
I'm looking into this.
