### ISSUE TITLE
Talos sessionrestore and sessionrestore_no_auto_restore 4%+ regression

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2750]
The regression seems like it can be entirely attributed to activity-stream getting initialized after "browser-delayed-startup-finished" which happens after `SessionStore.init` during "final-ui-startup" but before it reads the sessionstore file and finishes with "sessionstore-windows-restored"

Here's a profile: http://bit.ly/2stCFwh

This profile is 34ms of init after receiving the browser event. There's ~15 activity stream modules to load taking at least 1ms each, and 5 feeds to construct as well as potentially handle the `INIT` dispatch. So at quick glance, that's 15ms + 5ms + 5ms for 25ms of initing. Some modules take more time to load as they load other Firefox modules, e.g., `PlacesUtils`, or do some work at the top level (reading prefs).

**Comment by dmose** [comment]
All the timings in that profile end (implausibly) in .0, which is to say that every single timing is supposedly an exact number of ms.  Which makes me wonder what 0.1 would be rendered as.  And 0.5.  Perhaps @gregtatum can offer some insight?

**Comment by dmose** [comment]
If the JSM loads really do take 1ms each, perhaps the patch in [bug 1186408](https://bugzilla.mozilla.org/show_bug.cgi?id=1186409) would help.
