### ISSUE TITLE
New tab "Highlights" feature causing unintended side-effects

### ISSUE THREAD

**Issue by danielcoconnor** [mozilla/activity-stream#2751]
I have observed that the "Highlights" feature seems to re-issue the URLs that have been recently accessed. 

This can cause unintended side-effects if recent URLs cause changes to the state of the server that was recently accessed.

For example, we use a webservice to stop, start and restart services running on a server. The URL for this looks something like http://<<server>>:<<port>>/ServiceName?command=stop

After that URL has been issued and a subsequent new tab is opened, that URL gets re-issued which causes the Service to stop again -- which is not desired and has, in many cases, very bad effects.

I've been told this feature will be included in FF v.57, If so, there needs to be some way of preventing the re-issue of URLs that have side-effects.

If you need further information, please contact me at doconnor@acquiremedia.com.

**Comment by sarracini** [comment]
Thanks for the feedback! We no longer have Highlights as a section in newer versions. Closing this as a won't fix
