### ISSUE TITLE
temporarily back out running AS in content processes

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2756]
After discussion around [bug 1372664](https://bugzilla.mozilla.org/show_bug.cgi?id=1372664), we've decided to back out the move to the content process until bug 1372644 is fixed in a satisfactory way (which will happen after we pref on).

The backout is happening in the same bug we originally landed in: [bug 1365643] (https://bugzilla.mozilla.org/show_bug.cgi?id=1365643), and the relanding will happen there too.

**Comment by dmose** [comment]
It's on autoland now.

**Comment by Mardak** [comment]
We won't do this and flip dom.ipc.processPrelaunch.enabled false at the same time as preffing on.
