### ISSUE TITLE
Code tab describes this project as "MVP prototype add-on for activity streams"

### ISSUE THREAD

**Issue by Hillside502** [mozilla/activity-stream#2758]
Please expand on "MVP", as this acronym is not at all obvious to the world at large.

I assume it to be [Minimum viable product - Wikipedia
](https://en.wikipedia.org/wiki/Minimum_viable_product)

If not, [MVP (disambiguation) - Wikipedia
](https://en.wikipedia.org/wiki/MVP_(disambiguation)) expands

If the former, suggest "MVP (Minimum viable product) prototype add-on for activity streams"

**Comment by tspurway** [comment]
Thanks for your feedback!  We updated the code page!
