### ISSUE TITLE
Orphaned @activity-streams-{version}.update.rdf left in root dir after npm run package

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#276]
Saw this the other day and lazily forgot to file it...
### Steps to reproduce:
1. `$ git status` (should be clean)
2. `$ npm run package`
3. `$ git status`
### Actual results:

A new file, `@activity-streams-1.0.2.update.rdf` is left in my root directory (adjacent to /package.json):

``` sh
$ git status
On branch master
Your branch is ahead of 'origin/master' by 193 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean


$ npm run package
...
JPM [info] Starting jpm xpi on activity-streams-experiment
JPM [info] updateRDF created at /Users/pdehaan/dev/github/activity-streams/@activity-streams-1.0.2.update.rdf
JPM [info] Successfully created XPI at /Users/pdehaan/dev/github/activity-streams/@activity-streams-1.0.2.xpi (4735ms)


$ git status
On branch master
Your branch is ahead of 'origin/master' by 193 commits.
  (use "git push" to publish your local commits)
Untracked files:
  (use "git add <file>..." to include in what will be committed)

    @activity-streams-1.0.2.update.rdf
```
### Expected results:

We should add that pattern to to the /.gitignore, or maybe move the file into /dist/ which is already ignored by our current .gitignore rules.

I imagine it's easiest to just move it into /dist/ at the same time as we move the @activity-streams-{version}.xpi` file (in package.json):

``` js
"package": "npm run bundle && jpm xpi && mv @activity-streams-$npm_package_version.xpi dist/activity-streams-$npm_package_version.xpi"
```

Maybe just do something like append this to the previous "package" script:

``` sh
.. && mv @activity-streams-$npm_package_version.update.rdf dist/update.rdf
```

**Comment by sarracini** [comment]
@pdehaan can you still reproduce this?

**Comment by k88hudson** [comment]
I fixed this at some point
