### ISSUE TITLE
Activity-Stream use to much resources on Windows

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/activity-stream#2760]
Activity-Stream use to much resources (some hundred MB mem and a lot of CPU) on Windows (older machine) and makes FF unusable with this extension.
Testes with FF56.0a1, 64-bit with E10s on Win7 and with the latest Activity-Stream-Dev-Extension (v1.14.0-dev).

**Comment by Tobias-B-Besemer** [comment]
Is it possible that this happens just at the first start and comes due to conversation of the db?
Does a process have to much rights/use to much resources?

**Comment by Spitfire1900** [comment]
I have seen Firefox 55.0b3 (64-bit) be4a0ad5d6cab12fb89495d020532040b91be1f4 goes from 5-7% CPU usage idle to 35-40% cpu utilization when idle with this add-on enabled.

**Comment by Tobias-B-Besemer** [comment]
My memory was going up overnight from <1GB for FF to >4GB!

**Comment by sarracini** [comment]
Thanks for the feedback! We're not making any changes to the test pilot version since it will be deprecated soon. Closing this as a won't fix

**Comment by Tobias-B-Besemer** [comment]
I talk about the version from AMO.

**Comment by Spitfire1900** [comment]
@sarracini ; curious, is this add-on going to become a full-fledged add-on or integrated with FF?

**Comment by sarracini** [comment]
@Spitfire1900 it's going to be integrated with Firefox - so it won't be using the addon sdk, and soon it will be phased out of test pilot altogether

**Comment by Tobias-B-Besemer** [comment]
@sarracini, the AMO-Version will also be no more maintained, right?
Does it get auto-deinstalled?

**Comment by sarracini** [comment]
Yes
