### ISSUE TITLE
Create and use a icon for deactivated AS in Addon-Mgr

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/activity-stream#2761]
Create and use a icon (grayed-out) for deactivated AS in Addon-Manager of FF.
![2017-06-25 19_10_20-add-ons manager - nightly build 20170625030210](https://user-images.githubusercontent.com/11881073/27519199-0f5a4d3a-59ef-11e7-8342-0bcea828c8ff.png)

**Comment by sarracini** [comment]
Thanks for the feedback! We're not making any changes to the test pilot version since it will be deprecated soon. Closing this as a won't fix

**Comment by Tobias-B-Besemer** [comment]
I'm talking about the version from AMO.
