### ISSUE TITLE
A space to much in extension name

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/activity-stream#2762]
Seems there is a space to much in the extension name (after the "Dev").

**Comment by Tobias-B-Besemer** [comment]
![2017-06-25 19_10_20-add-ons manager - nightly build 20170625030210](https://user-images.githubusercontent.com/11881073/27519227-74ff74f8-59ef-11e7-8df0-4b416502176b.png)

**Comment by sarracini** [comment]
Thanks for the feedback! We're not making any changes to the test pilot version since it will be deprecated soon. Closing this as a won't fix

**Comment by Tobias-B-Besemer** [comment]
I'm talking about the version from AMO.
