### ISSUE TITLE
Page previews of Top Sites to small

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/activity-stream#2764]
The page previews of the Top Sites seems to be to small. I can see just a part of the page.
![2017-06-25 21_17_22-new tab - nightly build 20170625030210](https://user-images.githubusercontent.com/11881073/27519261-0de2d660-59f0-11e7-8462-61282c17f548.png)

**Comment by sarracini** [comment]
Thanks for the feedback! We're currently not taking feature requests for top sites. Closing this as a won't fix

**Comment by Tobias-B-Besemer** [comment]
I request no feature! It just looks wrong!
