### ISSUE TITLE
Allow more rows for Top Sites

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/activity-stream#2765]
Please allow more then two rows for Top Sites.
A counter with arrows for set the rows in the options would be IMHO fine.
Just the option to set 3 rows would be also fine to me.

**Comment by sarracini** [comment]
Thanks for the feedback! We're currently not taking feature requests for top sites. Closing this as a won't fix

**Comment by Tobias-B-Besemer** [comment]
You don't like me feedback, right? You closed all my bugs as "won't fix"... :-/
Why not let the feature requests open for the future?

**Comment by piatra** [comment]
@Tobias-B-Besemer This version of Activity Stream (currently in Test Pilot) will not be supported anymore. We will not be adding any new features. We are transitioning to a new version that is a part of Firefox. This can be enabled in `about:config` by changing `browser.newtabpage.activity-stream.enabled` to true. Currently the two versions do not have feature parity but this will happen in the following months.

**Comment by Tobias-B-Besemer** [comment]
I always wrote about the version from AMO. Isn't it the same code as in FF?

**Comment by Tobias-B-Besemer** [comment]
Is the AMO-Version a preview of what will land in Fx?
Makes it sense to write bug-reports for the AMO-Version?
Is there a chance that `browser.newtabpage.rows` will be used?

**Comment by Mathnerd314** [comment]
If you just want a pref then see #2592, it is (slowly) being worked on
