### ISSUE TITLE
Resource-URL looks "ugly"

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/activity-stream#2766]
I have the following Resource-URL for AS in my Bookmarks:
resource://activity-streams/data/content/activity-streams.html#/
I think the URL looks "ugly" and should be something like:
resource://activity-streams/data/content/activity-streams/
Or:
resource://activity-streams/data/content/activity-streams.html

**Comment by k88hudson** [comment]
We definitely agree! In the Firefox port of activity-stream we will make sure we always hide the URL (it just becomes `about:newtab`) 👍
