### ISSUE TITLE
Bookmarks of GitHub-Issues show user-pics

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [mozilla/activity-stream#2768]
My AS-Bookmarks of GitHub-Issues show user-pics of the users filled the issue.
What I expected was, that it shows the GitHub-Logo, or a preview of the page.
![2017-06-26 01_03_51-new tab - nightly build 20170625030210](https://user-images.githubusercontent.com/11881073/27563213-9ed8af38-5ad0-11e7-9118-fe2d75a43c23.png)

**Comment by Tobias-B-Besemer** [comment]
"Visit Again" have the same problem then "Recent Bookmarks"...

**Comment by sarracini** [comment]
Thanks for the feedback, activity stream doesn't decide what the preview image is, so we don't have much control over this. Closing this as a won't fix
