### ISSUE TITLE
Activity Stream is hoging all my bandwidth

### ISSUE THREAD

**Issue by dannyhajj** [mozilla/activity-stream#2769]
This may be related to #2760, but I've noticed that Firefox has been draining my bandwidth resources since yesterday. But only today I've managed to find out it's due to Activity Stream.
When I start Firefox and load a couple or more tabs while Activity Stream is enabled, Firefox hogs my download bandwidth. If I disable activity stream, the download stops.
I've noticed that after I re-enable activity stream without restarting Firefox, this issue doesn't occur again.

I don't mind adding logs or more info, but I'm not sure what kind of info is needed.

I'm on Firefox 55.0b4 on Ubuntu 17.04 (Using Gnome desktop).

**Comment by k88hudson** [comment]
Is this for this Test Pilot experiment or the one build into nightly?

**Comment by tspurway** [comment]
This is a known issue in Test Pilot.  Luckily AS for Firefox in Nightly doesn't have these issues!  Thanks for filing the bug.
