### ISSUE TITLE
Make Preferences pane accessible by keyboard

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2772]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1399428
Right now I don't think the Preferences Pane (triggered by the gear in the top right corner) is accessible without a mouse

**Comment by Mardak** [comment]
Is this still blocked? If so on what?

**Comment by k88hudson** [comment]
Nope, we did get review on this

**Comment by dmose** [comment]
I think this is a "good first bug" only if someone already has substantive accessibility experience, so I'm going to remove that tag.

**Comment by tspurway** [comment]
Ideally, we would have the gear icon in the tab-order, and it should have a highlight/selected state.  Within the panel, tabs (arrows?) should navigate, and return should select/deselect checkboxes.  Esc should close the panel (?)

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1399428
