### ISSUE TITLE
Land localized default top sites

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2776]
See https://docs.google.com/spreadsheets/d/15yLsFBkic5DFUSdbvSFlR3Rzjxqwmizq9EmksK28l6I

We need to figure out the mechanism for using default top sites depending on the locale

…or geo? https://github.com/mozilla/activity-stream/issues/2776#issuecomment-318877317

**Comment by tspurway** [comment]
- default top sites themselves broken  down by locale
- actual assets/icons for all topsites
- json doc mapped by locale, code for localized selection

**Comment by zbraniecki** [comment]
L10n-Drivers team can help you get the list of most popular sites per locale if you'd like to use that to influence the defaults.

**Comment by Mardak** [comment]
I believe according to mpopova (activity-stream PM), for the initial release, we'll just do US/China/rest; but having a better way than looking at top sites lists to get these 6 for each locale might be better going forwards.

**Comment by AdamHillier** [comment]
Amazon is listed under "Global" but amazon.com won't automatically redirect to the correct local version amazon.{fr, it, co.uk, jp} so will we (maybe not for 56) have to localise the top sites in a more granular way?

**Comment by Mardak** [comment]
depends on what's needed for shield beta 56

**Comment by Mardak** [comment]
Initial verbal example was en-US and de. Blocked on product decision of which exact locales for shield study.

**Comment by Mardak** [comment]
Development can start to support just en-US and de. Adding more locales or changing sites should be straightforward once the logic is there to support 2.

**Comment by mariappopova** [comment]
The top sites for 56 will include Tier 1 and Tier 2 countries + default (rest of the world):  https://docs.google.com/spreadsheets/d/15yLsFBkic5DFUSdbvSFlR3Rzjxqwmizq9EmksK28l6I/edit#gid=170333837

UX is currently reviewing and coming up with tippytop/icons for those default sites

**Comment by Mardak** [comment]
So it sounds like Canada doesn't actually get its own locale (i.e., en-CA doesn't actually exist). This means canadian users who are using en-US will just get the en-US. mconnor has mentioned how search engines get selected based on geo, but that's not something activity stream is doing currently (but could potentially reuse what search has done ??)

**Comment by Mardak** [comment]
Approach for 56 can probably just grab the locale from Services.locale and later clean up in #2999. 

Use that locale to key into an updated "default.sites" that is an object with keys of locales falling back to a "default"
https://github.com/mozilla/activity-stream/blob/master/system-addon/lib/ActivityStream.jsm#L52
E.g., {"en-US":"https://...","de":"https://","default":"https://"}

**Comment by zbraniecki** [comment]
Note that we're moving away from thinking about any single `locale` and in the direction of `locale fallback lists`. For example, mentioned `Services.locale` has `getAppLocales`, `getRequestedLocales` etc. This is primarily for fallback reasons, but I can imagine how it could be used to fine-tune content selection in the future - ["en-GB", "fr-CA", "fr"] vs. ["en-US", "de"] for example.

**Comment by Mardak** [comment]
So in #3004, we're doing Pocket selection by geo and locale. The list of sites have been provided with countries, so that would seem to want to pick things by geo. This would actually make more sense than relying on a non-existent en-CA.

In terms of UI, by default just the hostname is shown, which doesn't really depend on the UI locale, e.g., "amazon.ca" will show up as that for English and French Canadian users.

**Comment by Mardak** [comment]
I've updated the spreadsheet to be the redirected (`https`) page https://docs.google.com/spreadsheets/d/15yLsFBkic5DFUSdbvSFlR3Rzjxqwmizq9EmksK28l6I

Instead of "[youtube.com](http://youtube.com)" it's "https://www.youtube.com/". Basically whatever is loaded after just typing in the domain.

I also added a code section that is copy/paste-able directly into `ActivityStream.jsm` as used in PR #3022.
