### ISSUE TITLE
Checkbox style in Preferences sidepanel have gone astray 

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#2781]
<img width="392" alt="screen shot 2017-06-27 at 3 58 32 pm" src="https://user-images.githubusercontent.com/139451/27613747-39697e3e-5b52-11e7-99dd-a4b13b82e8f8.png">

The checkmarks inside the checkboxes have gone black instead of being blue (as seen in Firefox Prefs).

**Comment by k88hudson** [comment]
Ok, this has been resolved in the system add-on!
