### ISSUE TITLE
Flip dom.ipc.processPrelaunch.enabled to false when enabling activity-stream

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2785]
Instead of backing out with #2756, we will do this instead:

flip `dom.ipc.processPrelaunch.enabled` to `false`

This will probably be done as part of https://github.com/mozilla/activity-stream/blob/master/mozilla-central-patches/enable-mc-as.diff

**Comment by Mardak** [comment]
@mikeconley, @krizsa: we flipped prelaunch to false, but that didn't seem to fix our issues, so should we back out this change and leave it as true even when activity-stream enabled?

**Comment by dmose** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1373773 might be related to the decision here.  @krizsa, do you have a sense of which prelaunch setting is likely to have what effect on that bug?

**Comment by krizsa** [comment]
@dmose @Mardak I don't see how turning off process prelaunch would help the situation described in bug 1373773. We needed to turn it off for other reason (memory overhead from having two or more inactive cached process in the bg).

Currently if there is a preloaded browser loaded in the bg then opening a new tab should not suffer from that issue. (which is not the case for example when you quickly add two or more new tabs, but that should not be the most interesting use case). I'm not sure how aggressive we are currently about preloading an about:newtab page in the bg, maybe @mikeconley knows more about the details.

After https://bugzilla.mozilla.org/show_bug.cgi?id=1376895 the preloaded browser will not start up a new process (that will happen during the first navigation away from it if there is no preallocated process to be used and we have not reached the max process count).

After that we can further generalize that machinery to work for other about:newtabs too (so the non-preloaded browser case).

Does that make sense?
