### ISSUE TITLE
Integrate manual migration UI and functionality into Activity Stream

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2787]
[Bug 1361294 - show "import from other browser" link on Activity Stream](https://bugzilla.mozilla.org/show_bug.cgi?id=1361294)

We will need to add some UI for manual migration with a "Import Now" button, as well as the API to trigger the import wizard. This will replace the work that was done in #2616.

@gasolin feel free to add more details here

Manual import design:
![manual_import](https://user-images.githubusercontent.com/438537/27658812-1fdf9f7a-5c06-11e7-83f1-c65bfc998246.png)

Hover (adds `[x]` on right side):
![manual_import_hover](https://user-images.githubusercontent.com/438537/27658815-23033fb8-5c06-11e7-9dd4-6b5fc55356ab.png)

**Comment by Mardak** [comment]
There's some logic from the AutoMigrate PR:

```js
+XPCOMUtils.defineLazyModuleGetter(this, "MigrationUtils",
+  "resource:///modules/MigrationUtils.jsm");
+
+this.AutoMigrateFeed = class AutoMigrateFeed {
+  onAction(action) {
+    switch (action.type) {
+      case at.AUTOMIGRATE_MANUAL_IMPORT:
+        // We pass in the type of source we're using for use in telemetry
+        MigrationUtils.showMigrationWizard(action._target.browser.ownerGlobal,
+          [MigrationUtils.MIGRATION_ENTRYPOINT_NEWTAB]);
```
https://github.com/mozilla/activity-stream/pull/2650/files#diff-43cb90fc3065e94a29974775e0f22749R20

**Comment by gasolin** [comment]
can use `Automigrate.isMigratePromptExpired` or `profileAge.created` to check the remain days
http://searchfox.org/mozilla-central/source/toolkit/modules/ProfileAge.jsm#43

**Comment by Mardak** [comment]
From discussing with @gasolin, it'll be safer to just check the `profileAge.created` given the note in https://github.com/mozilla/activity-stream/issues/2787#issuecomment-311779167 about the unexpected external callers of `isMigratePromptExpired`.

**Comment by bryantmao** [comment]
Update UX spec for manual import
![manual import_v1_0711](https://user-images.githubusercontent.com/15391951/28056397-68e8a448-664f-11e7-9a58-5ffba2f29962.png)

**Comment by piatra** [comment]
Does this work supersede #2616 ? I see the bug is closed but the pull request for it #2650 is still open which makes it confusing. UX is done so I want to pick this up.

**Comment by piatra** [comment]
@bryantmao can you give more information about what "After 3 active days" means? Is it more than a profile that is 3 days old?

**Comment by bryantmao** [comment]
@piatra Whenever the user opens a new tab and sees the message during a day (00:00-23:59) we count the day as an "active day." The active day will expire after 23:59. If the user opens a new tab again, we recount the day. We will count it for three times then the message will be dismissed. If that makes sense, I'll update the spec again. 

For the icon, we don't intend to provide extra information on hover, but I'll check with the design system team to see if there are similar behaviors for the [i] icon (are there a similar icon on the activity stream page?)

**Comment by Mardak** [comment]
The "active day" behavior looks like it's the same that was implemented for AutoMigrate's `isMigratePromptExpired` linked earlier: https://github.com/mozilla/activity-stream/issues/2787#issuecomment-311779167

**Comment by piatra** [comment]
One limitation that I'm currently seeing is that there is no way to tell how many browsers the users has. Once the first import has finished the message will go away. But I'm confident that anyone wanting to import more than one profile is savvy enough to trigger manual import himself.

**Comment by piatra** [comment]
@bryantmao Could you provide the font sizes & paddings for the component? Thanks

**Comment by bryantmao** [comment]
Of course! Also, the string is currently under copy review. Once it's finished, I'll upload the spec altogether.

**Comment by piatra** [comment]
We can't rely on the AutoMigrate logic and we will have to compute the active days ourselves.

**Comment by bryantmao** [comment]
![pasted image at 2017_07_17 10_08 am](https://user-images.githubusercontent.com/15391951/28347839-1d79ee7c-6c6c-11e7-8b66-125da19855c8.png)
@piatra I heard Aaron already deliver the visual spec to you, have you got it?

**Comment by bryantmao** [comment]
The message copy has been reviewed: Try Firefox with your favorite sites, bookmarks, and passwords from another browser.

**Comment by bryantmao** [comment]
Spec update (copy reviewed)
![manual import_spec_v1 1](https://user-images.githubusercontent.com/15391951/28446565-2d4d59ae-6dfe-11e7-91b3-4033a5bbb1b8.png)

**Comment by Mardak** [comment]
How important are each of the "dismissing" conditions? In the image, they're listed as:

- User clicks "No Thanks"
- User clicks "Cancel" on the import wizard
- User completed the data import
- After 3 active days

I believe the current patch in the PR does not handle the "Cancel" from wizard. Also, what should be done about existing profiles that have been used for more than 3 days, e.g., long time Firefox users?

**Comment by bryantmao** [comment]
I think the "cancel" button is the least important one since the user can click "No thanks" to give up the import and dismiss the message. The "After 3 days" rule is kind of must have because we don't want the message hanging there forever if the user doesn't take any action on that. Other 2 conditions are considered essential. So the importance ranking will be:

1. User clicks "No Thanks"
2. User completed the data import
3. After 3 active days
4. User clicks "Cancel" on the import wizard

I wonder how the current migration message work on the existing profile? Will it show up after they update Firefox?

**Comment by Mardak** [comment]
I suppose if there's an assumption that there will be returning-to-Firefox users, showing the migrate prompt even if there had been Firefox activity in the past would actually be beneficial. And if the user has been actively using Firefox, the "No Thanks" is easy enough to dismiss.

**Comment by bryantmao** [comment]
If the users (either active or inactive) with existing profile update Firefox through stab installer, I assume they would expect the prompt. For people who were actively using Firefox and directly update to 57, I think it's okay to see the message since it's a major update with the activity stream taking over the home page. (The import prompt and activity stream will land together in 57 right?) So without over complicate the rules, I'll say it's fine for everyone to see the prompt in 57. 

And for your question, do you think it's possible to mark the update/install timestamp (ex. first session after the last update) as the start point for counting the active days?

**Comment by bryantmao** [comment]
Message string update: **Try Firefox with your favorite sites and bookmarks from another browser.**
