### ISSUE TITLE
"Customize your New Tab page" button overlaps other buttons from A-S New Tab page if Zoom is set to 300%

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2792]
**[Affected versions]:**
- Firefox 53 and up
- Activity Stream Build: 1.15.0-dev-1498669904-155a8b9

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- Set Zoom to 300%.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Scroll through the New Tab page and observe the "Customize your New Tab page" button.

**[Expected results]:**
- "Customize your New Tab page" button does not obstruct the user in using other buttons from the page.

**[Actual results]:**
- "Customize your New Tab page" button overlaps with other buttons. 

**[Notes]**:
- Attached a screen recording of the issue:
![overlap](https://user-images.githubusercontent.com/9248513/27661642-e711b6ba-5c0f-11e7-8ffc-c4d8ab69aba6.gif)

**Comment by aagandhi1** [comment]
I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by sarracini** [comment]
no longer reproducible 
<img width="1085" alt="screen shot 2018-03-23 at 11 30 43 am" src="https://user-images.githubusercontent.com/7219526/37838206-a95de004-2e8d-11e8-940d-0cc3683c78d4.png">
