### ISSUE TITLE
Multiple issues with A-S New Tab page and "New Tab Preferences" menu if the text is zoomed at maximum

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#2795]
**[Affected versions]:**
- Firefox 53 and up
- Activity Stream Build: 1.15.0-dev-1498669904-155a8b9

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Latest Activity Stream dev add-on version was previously installed on a profile with history.
- From browser menu "View -> Zoom" select the Zoom Text Only option.

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Zoom text to maximum.
3. Observe the New Tab page.
4. Observe also the "New Tab Preferences" menu.
5. Click on "Show two rows" button from the "New Tab Preferences" menu.

**[Expected results]:**
3. site-icon-fallback is no longer centered.
4. If the text is too big there should be a horizontal scroll bar.
5. Top Sites are displayed on 2 rows/1 row. No UI issues in "New Tab Preferences" menu.

**[Actual results]:**
3.  site-icon-fallback is displayed in center of the tile and fav-icon even if it is zoomed +/- .
4. Horizontal scroll bar is missing when the text is too big and is out of view but the vertical scroll can be done selecting the text.
5. Clicking the "Show two rows" button while the text is zoomed in, the UI of the New Tab Preferences menu is broken.

**[Notes]**:
- Attached a screen recording of the issue:
![issue text zoomed](https://user-images.githubusercontent.com/9248513/27663485-661eea66-5c17-11e7-8d3b-db0a641e97d3.gif)

**Comment by sarracini** [comment]
This is fixed since we no longer have the customize menu

**Comment by Mardak** [comment]
Fixed in #4041
