### ISSUE TITLE
Lin32 opt Perma-red: sessionstore/browser_window{Restore_perwindowpb,StateContainer}.js CRASH [@ RunWatchdog]

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2805]
This looks to have been happening for a little bit only on "Linux opt" for a couple tests:

```
 LOG ERROR | TEST-UNEXPECTED-FAIL | browser/components/sessionstore/test/browser_windowRestore_perwindowpb.js | application terminated with exit code 11 [log…] 
 LOG ERROR | TEST-UNEXPECTED-FAIL | browser/components/sessionstore/test/browser_windowStateContainer.js | application terminated with exit code 11 [log…] 
```

Restore_perwindowpb: https://treeherder.mozilla.org/logviewer.html#?job_id=110250146&repo=pine&lineNumber=3504
StateContainer: https://treeherder.mozilla.org/logviewer.html#?job_id=108959559&repo=pine&lineNumber=3039

Might be related to the filed intermittent bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1244904
https://bugzilla.mozilla.org/show_bug.cgi?id=1361528

**Comment by Mardak** [comment]
The StateContainer blamed crash was recently turned off for debug builds: https://bugzilla.mozilla.org/show_bug.cgi?id=1373116

**Comment by sarracini** [comment]
@Mardak try and see if this can be caught by running it multiple times

**Comment by Mardak** [comment]
I tried running the whole sessionstore directory with repeat but didn't get it to crash. I suppose it's because my VM is "Ubuntu; Linux x86_64" so not quite the Linux32 opt. And the pine runs do seem to only crash on 32bit not 64.

**Comment by piatra** [comment]
@Mardak Same failures on mozilla-central with activity-stream turned off in profile.js [see here](https://treeherder.mozilla.org/#/jobs?repo=mozilla-central&selectedJob=112113253) Shouldn't this be enough to ignore this failure?

**Comment by Mardak** [comment]
It is indeed quite frequent per the reports in https://bugzilla.mozilla.org/show_bug.cgi?id=1244904 ranging up to 0.4 failures per push. However on pine, that test seems to be failing on 100% of pushes, hence the perma-orange label. If we tried to turn on with 100% consistent test failure, the commit will be backed out.

On the other hand, because the failure rate is so high, it seems likely that something will be done on the mozilla-central side to address the test. The usual steps are to turn off the test, except as described in various related `RunWatchdog` intermittent test failure bugs, the blamed test is not too accurate, so there will need to be some more work done to "fix" things.

**Comment by piatra** [comment]
@Mardak thank you for explaining, it makes more sense now. I tried a try run just on linux32 with [latest AS but with the pref turned off](https://treeherder.mozilla.org/#/jobs?repo=try&revision=ab2dbd8ae3e10a4d8903ecdada8121b7de516a9c&selectedJob=112330139).
Even though we might influence the test with AS turned on these bugs are getting a lot of attention I would put off doing something about them because they have high priority and might get fixed/changed/disabled soon.

**Comment by Mardak** [comment]
I'm currently looking at finding a set of tests that can be disabled. The set of 20 that gbrown found is not sufficient when activity-stream is enabled.

https://bugzilla.mozilla.org/show_bug.cgi?id=1244904#c7

**Comment by piatra** [comment]
There's now a patch in bugzilla to disable the tests and it has r+.

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/82f7afb4f46b
https://bugzilla.mozilla.org/show_bug.cgi?id=1244904

**Comment by piatra** [comment]
It looks like this bug is making a comeback? https://bugzilla.mozilla.org/show_bug.cgi?id=1244904#c51 but if I'm wrong please disregard and close again.

**Comment by Mardak** [comment]
That comment is the summary of the last 7 days, and the patch only landed 3 days ago.
