### ISSUE TITLE
The "Back" button is not disabled after you are redirected to "about:preferences" page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#2807]
[Affected versions]:
- Firefox 56.0a1 (Build ID 20170628030206)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Write a keyword in the search bar and click the "Change Search Settings" button.
3. Observe the behavior.
 
[Expected results]:
- The "about:preferences" page is opened in the same tab and the "Back" button is disabled.

[Actual results]:
- The "about:preferences" page is opened in the same tab and the "Back" button is active. 

[Notes]:
- If you go back to the about:newtab page, the URL is "about:newtab?" and the search bar no longer works.
- The issue is not reproducible on about:home and (the old) about:newtab.
- Attached a screen recording of the issue:
![changesearchsettingsbug](https://user-images.githubusercontent.com/18304511/27687085-1cbf79f4-5cde-11e7-87f5-61d81d0bc50c.gif)

**Comment by sarracini** [comment]
This is the current behaviour from about:newtab that exists in mozilla central, so i'll close this as a won't fix

**Comment by SoftVision-CiprianMuresan** [comment]
@sarracini, okay, but the second part of this issue is not addressed. 
If you open about:preferences from about:newtab (the old one) you can't go back the the new tab page. This however is possible with the Activity Stream new tab page. 
Changing the title to better reflect this.

**Comment by Mardak** [comment]
The bugs related to ending up on `about:newtab?` seem to be gone?
