### ISSUE TITLE
Malformed payload for the activity_stream_performance_event ping

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2810]
Have seen some performance pings in the stage as follows:

```js
{
    "addon_version":"0.0.0",
    "date":"2017-06-28",
    "locale":"en-US",
    "action":"activity_stream_performance_event",
    "client_id":"ceff4adf-51ef-294a-89b6-6e927f2144ab",
    "timestamp":1498687466816,
    "visability_duration":71274.9836425781,
    "ua":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko\/20100101 Firefox\/56.0"
}
```

Having your event, i.e. `visability`, defined as a key in the payload makes it hard to extend. Rather, we can use a generic key called `event` as well as a `value` for its value if needed.

```js
{
    "addon_version":"0.0.0",
    "date":"2017-06-28",
    "locale":"en-US",
    "action":"activity_stream_performance_event",
    "client_id":"ceff4adf-51ef-294a-89b6-6e927f2144ab",
    "timestamp":1498687466816,
    "event": "visability_duration",
    "value": ...,
    "ua":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko\/20100101 Firefox\/56.0"
}
```

Although not required, adding more contextual fields such as `session_id`, `page`, and `source` to the payload is highly recommended, since you might want to associate it with its corresponding session in the analysis.

**Comment by ncloudioj** [comment]
Note that the `value` field is currently of the type `int32` in the database, if you want to store floating point numerics, you will have to do the conversion if necessary. Otherwise, the ETL job will do that conversion for you, which may introduce the unexpected precision loss.

**Comment by Mardak** [comment]
This was removed https://github.com/mozilla/activity-stream/pull/2811/files#diff-c5c105b24f51b0ff8628a32504faae1aL95
