### ISSUE TITLE
Misalligned tile in the top sites

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2814]
Firefox Nightly 56.0a1 on OS X

<img width="973" alt="screen shot 2017-06-30 at 9 57 01 am" src="https://user-images.githubusercontent.com/1455254/27746092-b5773352-5d7a-11e7-8167-bcf8cb30ad98.png">

**Comment by Mardak** [comment]
Looks like there's no label. What's the url for the top right site?

**Comment by ncloudioj** [comment]
the url is `localhost:8989` without `title`.

**Comment by piatra** [comment]
@aaronrbenson is it ok to show the URL in this case?

**Comment by aaronrbenson** [comment]
Yeah. Something is better than nothing.

**Comment by Mardak** [comment]
@ncloudioj did point out that `localhost` was being filtered out somewhere so perhaps it's just not being skipped because of the `:8989` port. If we do show `localhost:8989` should we make sure that `localhost` shows up as well?

**Comment by ncloudioj** [comment]
Looks like we only exclude the `localhost` in the Test Pilot version [here](https://github.com/mozilla/activity-stream/blob/master/addon/PreviewProvider.js#L15). The system addon only excludes those user-blocked URLs.

Anyway, using URL as the fallback for the title-less site seems to be a reasonable plan.

**Comment by aaronrbenson** [comment]
@ncloudioj If it's user-blocked, does the item show without a title or not show at all?

**Comment by piatra** [comment]
@aaronrbenson user blocked should prevent it from showing up at all.
