### ISSUE TITLE
Pinning a default top site in the sytem addon adds all the other context menu items

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2825]
It's weird.....
before:
<img width="1263" alt="screen shot 2017-07-06 at 5 31 20 pm" src="https://user-images.githubusercontent.com/7219526/27933787-d750ae4a-6270-11e7-84dc-71786407522b.png">

after: 
<img width="1279" alt="screen shot 2017-07-06 at 5 31 31 pm" src="https://user-images.githubusercontent.com/7219526/27933800-df269d50-6270-11e7-93fb-1539de6ec0f9.png">

**Comment by piatra** [comment]
I looked into it, we use`NewTabUtils.pinnedLinks.pin` to store pin information. This takes just url and position as arguments and `isDefault` is completely lost. Here is a tentative fix, let me know if you r+ the solution and I could write tests and have a pull req ready. It checks the DEFAULT_SITES and there is another fix where we would return `isDefault: false` although the correct information was already available in the state.

https://github.com/mozilla/activity-stream/compare/master...piatra:bug-2825-pinned-sites?expand=1
