### ISSUE TITLE
measure memory of tiles and about:newtab by hand, regularly

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2831]
After meeting with the product integrity folks, it sounds like current memory measurement abilities are still fairly manual.  It sounds like we want to do something like this:

* start the browser
* use about:memory to measure (presumably using Measure and Save) the current memory usage and save it
* open a new tab
* use about:memory to measure the current memory usage and save it

For the first time, we should do this for activity stream preffed off (i.e. tiles), and then preffed on (system addon).

Subsequently, we should probably do the same thing, about once a week, and compare the numbers with the previous week, filing any regressions as we see them.  Perhaps this is something SoftVision could handle?

CC @bsmedberg does this sound about right?

**Comment by dmose** [comment]
I suspect we'll want to collect several data points for each measurement to try and at least eliminate some of the effects of an intrinsically noisy process.  @emtwo, thoughts here?

**Comment by jaredkerim** [comment]
The actionable outcome of this ticket is for this memory testing process is to add this to the activity stream test plan.

**Comment by jaredkerim** [comment]
https://wiki.mozilla.org/QA/Activity_Stream

**Comment by SoftVision-PaulOiegas** [comment]
@jaredkerim Just a correction. I think you guys were searching for the Activity Stream system add-on Test Plan, not for the Test Pilot experiment one.  The right link for that is https://wiki.mozilla.org/QA/Activity_Stream_(system_add-on).

**Comment by Softvision-VladBacia** [comment]
@dmose , I've created a folder in drive ( https://goo.gl/DMzXDx ) in which I will upload twice a week the performance profiles. I was thinking of doing this on Monday and Thursday. Is this ok for you? And another question is what should we look for when comparing the memory profiles? Is there something particular?

**Comment by dmose** [comment]
@Softvision-VladBacia this is great; thanks!  What platform and OS are these traces from?  In an ideal world, these would be from one of the "reference machines", but as a start, a (low-end, if possible) Windows machine running Windows 10 should do, since that's what our reference machines are...

**Comment by Softvision-VladBacia** [comment]
@dmose the traces are from an Windows 8.1 x64 machine but it's a high end machine (SSD, 16 GB RAM, proc AMD FX-8320 eight core processor). I will try to provide some logs from low end machines. I will create a separate folder in gdrive. I'll post here when the profiles are ready.

**Comment by Softvision-VladBacia** [comment]
Updated the gdrive folder with the mem profile from a low end machine. I'll put new mem reports also on Friday.

**Comment by Mardak** [comment]
Given that AWSY does something similar and more, do we need this manual measuring of memory?
