### ISSUE TITLE
dashboard for the Hero Element paint time

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2838]
This is the dashboard side of #2661.

User Story:

> As a developer or (product/eng) manager, I can see real user monitoring of the length of the time it takes to paint the Hero Element (TopSites currently, although do we know whether adding Pocket changes what the Hero Element is?), and can notice regressions in that time, so that I can keep perceived rendering speed fast.

I'm not sure what visualization(s) we want here.  I can imagine a percentile, but I could also imagine a trendline over time of some single number to help in noticing regressions.  

@emtwo, what are your thoughts?

**Comment by dmose** [comment]
@digitarald do you have any experience with / suggestions for what dashboarding is likely to be most useful for this RUM data?

**Comment by digitarald** [comment]
On top of the median the typical starting point for tracking  performance numbers is tracking the 90, 95 or 99th percentile (depending on amount of generated data and shape of distribution; test what provides stable numbers). Improvements then can be tracked as addressing the worst cases (only visible in higher percentiles) or improving performance for all cases.

**Comment by emtwo** [comment]
Blocked on #2661

**Comment by emtwo** [comment]
https://sql.telemetry.mozilla.org/dashboard/activity-stream-system-addon-performance
