### ISSUE TITLE
separate preloaded and non-preloaded new tab hero reporting in dashboards

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2839]
This is the dashboard piece of #2726.

User Story: 

> As a developer or (product/eng) manager, I should be able to see different Hero Element data for newtabs which have been preloaded and those that haven't, so that I can view separate data for each case, rather than confusing data for the combined case. 

This probably wants to be implemented after (or maybe as part of) #2838.

@emtwo would love your thoughts on how to fit this together (happy to discuss with you and/or others together over Vidyo if that helps)

**Comment by emtwo** [comment]
Blocked on #2726

**Comment by dmose** [comment]
The simplest (not sure how reliable yet, though) way may just be to start sending performance.timing.navigationStart and assuming that when it happens before things are visible, the tab must be preloaded.

**Comment by Mardak** [comment]
Could use #3144 instead of #2726

**Comment by emtwo** [comment]
Tracking here now: https://github.com/mozilla/ping-centre/issues/90
