### ISSUE TITLE
Separate remaining load_trigger_types data from the existing one in dashboard visualization

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2840]
This is the dashboard piece of #2685.

User Story: 
> As a developer or product/eng manager, I can see when the Hero Element loads for all different types of new tab loads, not just those started by the initially implemented user affordances, so that I have an overall sense of how our hero element paint times (and others) are performing.  

The simplest thing here is just to make sure that all load_trigger_types are handled.  In an ideal world, we want to be able to drill down into all the various different types to be able to see which ones are slowest.  I suspect that can be spun off to a future issue, though.

@emtwo, thoughts are, as usual, appreciated.  :-)

**Comment by dmose** [comment]
Blocked on #2685

**Comment by emtwo** [comment]
Tracked here now: https://github.com/mozilla/ping-centre/issues/89
