### ISSUE TITLE
visualize telemetry data for bad states

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2841]
This is the dashboard piece of #2672.

User Story:
> As a developer or product/eng manager, I should be able to see how often activity stream gets into a bad state in the field, as well as how those ratios (bad states / client, I suspect) change, so that regressions and improvements can be spotted.

@emtwo, your thoughts on dashboard design here would be most welcome

**Comment by emtwo** [comment]
Tracked here now: https://github.com/mozilla/ping-centre/issues/88
