### ISSUE TITLE
visualize slow (ie content-proc jank inducing) event handlers

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2842]
This is the dashboard piece for #2669.

User Story:
> As  developer or product/eng manager, I can tell if event handlers in the field are taking too long so that I can work to speed them up.

Note in particular the subsampling suggestions toward the end of the bug, which may have some impact on the dashboards as well.

**Comment by emtwo** [comment]
Blocked on #2669

**Comment by emtwo** [comment]
Tracked here now https://github.com/mozilla/ping-centre/issues/87
