### ISSUE TITLE
visual display done telemetry

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2843]
This is the dashboard side of seeing how long things take to finish painting in the field.

User Story: 
> As a developer or eng/product manager, I can see how long it takes for about:newtab to finish painting in the field so that I can both ensure that it is quick enough and notice if it regresses.

This has lots in common with #2838, as well as the follow on work to help understand the data in a more granular fashion (#2839, #2840).  Note that it may well make sense to spin this follow-on work out into separate bugs.

**Comment by dmose** [comment]
I think our hero element captures the most important piece of this, so I'm demoting it to P2.

**Comment by emtwo** [comment]
Tracked here now: https://github.com/mozilla/ping-centre/issues/86
