### ISSUE TITLE
visualize when we're janking the main thread

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2844]
This is the dashboard work for #2526.  

User Story: 
> As a developer or eng/product manager, I can see how often we're running code on the main thread that takes longer than 50ms.

See also https://github.com/mozilla/activity-stream/issues/2005#issuecomment-298095620

This should be very similar to #2842.  As with that bug, it may make sense to do some subsampling here.

**Comment by emtwo** [comment]
This is blocked on #2526

**Comment by emtwo** [comment]
Tracked here now: https://github.com/mozilla/ping-centre/issues/85
