### ISSUE TITLE
visualize search box input latency telemetry

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2845]
This is the dashboard piece of #2663.

User Story:
> As a developer or eng/product manager, I can see how often is takes > 100ms to see the result of a keystroke, so that I can have a sense of whether typing in the search box feels responsive.

https://github.com/mozilla/activity-stream/issues/2663#issuecomment-306262318 has some thoughts on measurement.

**Comment by Mardak** [comment]
Not doing #2663
