### ISSUE TITLE
incorporate about:home telemetry into the various dashboards

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2846]
This is the dashboard piece of #2658.

User Story:
> As a developer or eng/product manager, the various dashboards also have about:home broken out into their own statistics.

I don't think it's going to be clear until we've implemented some dashboards exactly how much work this is likely to be and what the best strategy for it is.  But perhaps @emtwo disagrees...

**Comment by emtwo** [comment]
Tracked here now: https://github.com/mozilla/ping-centre/issues/84
