### ISSUE TITLE
Perma-orange: browser_all_files_referenced.js | unreferenced file PreviewProvider.jsm

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2849]
Looks like #2824 removed the last reference to `PreviewProvider` so we'll need to remove it from m-c and the related tests.

```
FAIL | browser/base/content/test/static/browser_all_files_referenced.js | there should be no unreferenced files
Got 1, expected 0
```

Linux64: https://treeherder.mozilla.org/logviewer.html#?job_id=113157434&repo=pine&lineNumber=2230
Windows10: https://treeherder.mozilla.org/logviewer.html#?job_id=113171828&repo=pine&lineNumber=2631

**Comment by piatra** [comment]
The fix for #2824 doesn't seem to have landed in m-c yet and all the PreviewProvider code is still there.

**Comment by sarracini** [comment]
Do we care that the test pilot addon still uses it as a reference?

**Comment by Mardak** [comment]
Sorry nanj, I ended up grabbing this.
