### ISSUE TITLE
Intermittent: browser_getScreenshots.js Test timed out

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2851]
I would guess it's the same test failure situation from https://bugzilla.mozilla.org/show_bug.cgi?id=1343150 that #2824 was trying to avoid.

```
 FAIL | browser/extensions/activity-stream/test/functional/mochitest/browser_getScreenshots.js | Test timed out [log…] 
```

Linux64: https://treeherder.mozilla.org/logviewer.html#?job_id=113155669&repo=pine&lineNumber=3538

**Comment by sarracini** [comment]
i hate screenshots

**Comment by tspurway** [comment]
Let's turn this test off

**Comment by Mardak** [comment]
Sorry nanj, I ended up grabbing this.
