### ISSUE TITLE
Win8 intermittent: browser_urlbarRaceWithTabs.js | New tab still has about:newtab

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2860]
https://treeherder.mozilla.org/#/jobs?repo=pine&selectedJob=114078450

Got about:blank, expected about:newtab
Stack trace:
chrome://mochikit/content/browser-test.js:test_is:967
chrome://mochitests/content/browser/browser/base/content/test/urlbar/browser_urlbarRaceWithTabs.js:hitEnterLoadInRightTab:50

**Comment by dmose** [comment]
So far, we've only seen this happen once.

**Comment by Mardak** [comment]
Pushed onboarding try with latest patches: https://treeherder.mozilla.org/#/jobs?repo=try&revision=583d77d718566376cd43c969b786ca23ade0ebdf

**Comment by Mardak** [comment]
Pushed urlbar try with latest patches: https://treeherder.mozilla.org/#/jobs?repo=try&revision=827feac377f21aa8100c63ba3fb4ff53bb47d764

**Comment by Mardak** [comment]
Only 1 out of 40 Windows 8 x64 opt M-e10s tests failed with the above `try` push. I also retriggered on the latest `pine` and there was 1 out of 30.

Probably won't need to fix this for preffing on.
