### ISSUE TITLE
pagescraper causes massive downloads

### ISSUE THREAD

**Issue by russetrob** [mozilla/activity-stream#2865]
Was seeing massive network load over past week from Firefox:
Every time I started Firefox, it would download a massive file.
Page was a vm image, in zip format from download.microsoft.com.

I managed to track it to "pagescaper.js", after enabling browser toolbox, switching to offline mode in Firefox, and looking for timeout error messages that matched download.microsoft.com.

Unforunately browser console seems to be choking on volume of messages (or discarded old logs), so can't report exact message.

**Comment by russetrob** [comment]
Update:
I can confirm that problem goes away if activity stream is disabled.
And I have the error from browser console:  
PageScraper failed to get page content for http://download.microsoft.com/download/E/2/8/E289FC3B-124C-425A-9675-97CDF22E0881/WinDev1612Sys.VirtualBox.zip. AbortError: The operation was aborted.

**Comment by jaredkerim** [comment]
Ah yes I understand, the scraper is attempting to fetch that bundle to parse it for preview metadata without understanding that it is a non HTML content type.  

Unfortunately, the Test Pilot Activity Stream addon has now been End of Lifed and no further maintenance will be made to that addon.  I would suggest permanently disabling the addon until it is finished being ported into Firefox over the next couple of months, at which time it will come back as the default new tab page.  

If you want to keep using the Test Pilot addon without this problem repeating itself, you can manually remove that URL from your history by opening up the History panel, finding that URL, and removing it, but it may recur in the future for other large binary blobs.

Thank you for trying Activity Stream and giving us feedback!
