### ISSUE TITLE
Replace Embedly

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#288]
I was investigating a bug yesterday (where we were mishandling sites with query params), but it brought up an interesting point of what exactly we need/use Embedly for.

It looks like without Embedly, we get about 9 keys back from our queries:
- `bookmarkDateCreated`
- `bookmarkGuid`
- `favicon` (base64 encoded data uri)
- `frecency`
- `lastVisitDate`
- `parsedUrl{}`
- `title`
- `type`
- `url`

Results injected with the Embedly middleware add the following ~22 keys (see [Embedly `extract` API docs](http://docs.embed.ly/docs/extract#response-attributes)):
- `app_links[]`
- `authors[]`
- `cache_age`
- `content`
- **`description`**
- `embeds[]`
- `entities[]`
- **`favicon_colors[]`**
- **`favicon_url[]`**
- **`images[]`**
- `keywords[]`
- `language`
- `lead`
- `media{}`
- `offset`
- `original_url` (ie: "https://news.ycombinator.com")
- **`provider_display`** (ie: "news.ycombinator.com")
- **`provider_name`** (ie: "Ycombinator")
- `provider_url` (ie: "https://news.ycombinator.com")
- `published`
- `related[]`
- `safe`

So I think the only keys we use above are:
- `description` &mdash; used for the spotlight results.
- `favicon_colors[0]` &mdash; for the background color on "Top Sites" and fallback icons for "Top Activity"
- `favicon_url` &mdash; kind of redundant since we have a base64 encoded version already which would save us a network request.
- `images[0]` &mdash; only used for the 3 "Spotlight" results.
- `provider_display` and `provider_name` &mdash; only used for the fallback icon letter and possibly "Top Sites" friendly name. Probably easily extracted from the `parsedUrl` object.

Not sure if I'm missing anything, but it seems like we're barely using any of the features from Embedly, and it may be pretty easy to build our own version. The big features being:

1. How can we get the primary favicon colors from our existing base64 encoded `favicon` data uri?
2. How can we get the primary article image for "Spotlight" results?
3. How can we get the site description for "Spotlight" results?

But if we can live without `favicon_colors`, I think we'd only to use the Embedly middleware for the 3 spotlight URLs so we can get the spotlight `description` and `images[0]`.

----

```json
"FrecentHistory": {
  "rows": [
    {
      "bookmarkDateCreated": null,
      "bookmarkGuid": null,
      "favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABj0lEQVQ4jZWTP0gCURzHXf0DDaKoyZ06CTVHc3NLU1CrFpipd+dgTeXUFCFETbXU0pJr0SQotLS5VN69d2hpIaaWJIbfhtPr0tNsePDe7/H7/L6/fwbKMV3KsaAc06U8i4mOxseg/SAc07t71LeeTetjGFRAYm6QTYc2muIYcYDE3H8oiLkhJ/woJucVUN8enUZxdw5ywv8DURVoAVEX5K0ZdJqvKB+vQgxZIYXteNpfRKdWgrw9CxJ1jQBwDKjgQyFgQu3qAJ/FPMSQFeL6FFoPWbxdp1AImEAFn5rWsIJ+DXgWX80qnlNLKO0toFOvgAieX2npA3oqxDULqpc7aN1n8ZG/QTWdhBi0gAo+nS4MEAmngKSIE+3KI9ovIqSIc6ClYwEMaNyHQsCIRu4M9cwpCgEjaHw4ui6A8iyI4IUYNKORO0c9cwIxaAYRvLpTqQvoK3i/S6N5e6EqmBzAeyCF7SgfraB8uAwpbFdHeRigt0wco0A2bJDCNsVZm/+oUR5uqRdU8OoWb7yCf6zzN96LhjqimbbsAAAAAElFTkSuQmCC",
      "frecency": 2000,
      "lastVisitDate": 1457634541144,
      "parsedUrl": {
        "auth": "",
        "hash": "",
        "host": "news.ycombinator.com",
        "hostname": "news.ycombinator.com",
        "href": "https://news.ycombinator.com/item",
        "password": "",
        "pathname": "/item",
        "port": "",
        "protocol": "https:",
        "query": {},
        "username": ""
      },
      "title": "PyPy 5.0 Released | Hacker News",
      "type": "history",
      "url": "https://news.ycombinator.com/item?id=11260377"
    },
    {
      "app_links": [],
      "authors": [],
      "bookmarkDateCreated": null,
      "bookmarkGuid": null,
      "cache_age": 86400,
      "content": null,
      "description": "AlphaGo beats Lee Sedol again in match 2 of 5",
      "embeds": [],
      "entities": [...],
      "favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABj0lEQVQ4jZWTP0gCURzHXf0DDaKoyZ06CTVHc3NLU1CrFpipd+dgTeXUFCFETbXU0pJr0SQotLS5VN69d2hpIaaWJIbfhtPr0tNsePDe7/H7/L6/fwbKMV3KsaAc06U8i4mOxseg/SAc07t71LeeTetjGFRAYm6QTYc2muIYcYDE3H8oiLkhJ/woJucVUN8enUZxdw5ywv8DURVoAVEX5K0ZdJqvKB+vQgxZIYXteNpfRKdWgrw9CxJ1jQBwDKjgQyFgQu3qAJ/FPMSQFeL6FFoPWbxdp1AImEAFn5rWsIJ+DXgWX80qnlNLKO0toFOvgAieX2npA3oqxDULqpc7aN1n8ZG/QTWdhBi0gAo+nS4MEAmngKSIE+3KI9ovIqSIc6ClYwEMaNyHQsCIRu4M9cwpCgEjaHw4ui6A8iyI4IUYNKORO0c9cwIxaAYRvLpTqQvoK3i/S6N5e6EqmBzAeyCF7SgfraB8uAwpbFdHeRigt0wco0A2bJDCNsVZm/+oUR5uqRdU8OoWb7yCf6zzN96LhjqimbbsAAAAAElFTkSuQmCC",
      "favicon_colors": null,
      "favicon_url": null,
      "frecency": 100,
      "images": [],
      "keywords": [...],
      "language": "English",
      "lastVisitDate": 1457634543196,
      "lead": null,
      "media": {},
      "offset": null,
      "original_url": "https://news.ycombinator.com/news",
      "parsedUrl": {...},
      "provider_display": "news.ycombinator.com",
      "provider_name": "Ycombinator",
      "provider_url": "https://news.ycombinator.com",
      "published": null,
      "related": [],
      "safe": true,
      "title": "Hacker News",
      "type": "history",
      "url": "https://news.ycombinator.com/news"
    }
  ],
  "error": false
}
```

**Comment by jaredkerim** [comment]
Progress is being made on this front by @erikrose and myself in the https://github.com/mozilla/fathom/ project which we hope to use to replace embedly eventually.

**Comment by jaredkerim** [comment]
This will be implemented by combining https://github.com/mozilla/fathom/ with #25 to extract metadata and store it locally.

**Comment by erikrose** [comment]
Exciting! And fathom 1.0 is up, so you can depend on it nicely: https://www.npmjs.com/package/fathom-web.

**Comment by pdehaan** [comment]
> Exciting! And fathom 1.0 is up, so you can depend on it nicely

This is great news indeed! Now that we've hit 1.0 (:tada:), it's almost time to add a Fathom code reviewer and person to reduce self-merging. I nominate @jaredkerim.

**Comment by erikrose** [comment]
Ask and ye shall receive. You and jkerim are now fathom reviewers.
