### ISSUE TITLE
Add mochitest to ensure correct behavior enabled/disabled on all channels

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2880]
There's some complexity here in that for initial rollout, activity-stream is enabled on nightly 56 and disabled beta 56. And beta 56 doesn't even build the extension.

This is to make sure tests don't start failing because of a nightly -> beta transition where build/default prefs change.

**Comment by dmose** [comment]
I assume that the only reason it's not build on 56 is because we haven't been greenlighted to uplift yet, correct?
