### ISSUE TITLE
address AWSY memory regressions from landing 

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2894]
[Turning on AS in mozilla-central ](https://bugzilla.mozilla.org/show_bug.cgi?id=1381569) has resulted in a [memory usage regression](https://bugzilla.mozilla.org/show_bug.cgi?id=1381804).

After reading through the AWSY docs and FAQ, it's not obvious to me why we didn't end up with AWSY on pine.  In an ideal world, we'd still try to get it there, but I don't think that's the top prio at the moment, since more specific tests will be more useful in figuring out what's going on.

Fortunately, thanks to @Softvision-VladBacia, we have [some data that we can start analyzing](https://github.com/mozilla/activity-stream/issues/2831#issuecomment-314414892) for both AS off and AS on.  I've started poking at the "load and diff" functionality of [about:memory](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/about:memory).

It should also be easier to generate the data by hand using steps described in #2831; we don't yet have a sense of how noisy the data is.

Reading the "diff" was a bit confusing at first, it's formatted exactly like the non-diff versions.  After some playing around, it appears that all positive numbers in the diff are the differences where the second log had a larger number than the first, and all negative numbers are where the second log had a smaller number than the first.  To contextualize this, it can be useful to open three about:memory tabs: the as-OFF trace, the as-ON trace, and the diff trace.

**Comment by Mardak** [comment]
@dmose do you know how to run AWSY on try? I pushed a patch to flip prelaunch https://reviewboard.mozilla.org/r/158390/diff/1

**Comment by Mardak** [comment]
Some reason mozreview wouldn't let me trigger try, so I manually ran `./mach try -b o -p linux64,macosx64,win64 -u awsy-e10s -t none`
https://treeherder.mozilla.org/#/jobs?repo=try&revision=b3636c388a2cd3d6029ee8d99637c71c98c9a69a

**Comment by dmose** [comment]
https://areweslimyet.com/faq.htm#how-can-i-request-additional-awsy-tests-on-specific-changesets-or-try-pushes

**Comment by EricRahm** [comment]
AWSY has moved in tree, `-u awsy-e10s` should do what you want. It will show up as an `sy` job. If you're going to compare in perfherder, I'd suggest doing a few retriggers (similar to talos) so you get stable numbers.

**Comment by Mardak** [comment]
Aha! Thanks. I retriggered the try run. Perfherder has a dropdown to switch from talos to awsy:
https://treeherder.mozilla.org/perf.html#/compare?originalProject=autoland&originalRevision=87e8ccdd8aa6f6b549922b4debc19a4126b7d940&newProject=try&newRevision=b3636c388a2cd3d6029ee8d99637c71c98c9a69a&framework=4

**Comment by EricRahm** [comment]
I took a look at the memory reports, the main regression comes from having an additional content process after closing all tabs. This is probably pretty easy to repro outside of AWSY, something like:

1. Launch Firefox
2. Open 4 tabs to actual websites
3. Close 3 tabs
4. Navigate to about:blank in the final tab

You can automate this locally by using `./mach awsy-test --entities 4 --iterations 1`

**Comment by Mardak** [comment]
I tried just doing a plain `./mach awsy-test` (as the `--entities 4 --iterations 1` didn't run), and I'm guessing I might need to start up some local server?

```
$ ./mach awsy-test 
 0:00.53 /usr/local/opt/python/bin/python2.7 /Users/Ed/Development/mozilla-central/mach artifact toolchain -v --tooltool-manifest=/Users/Ed/Development/mozilla-central/testing/awsy/tp5n-pageset.manifest --cache-dir=/Users/Ed/Development/mozilla-central/tooltool-cache
 0:00.00 LOG: MainThread INFO Using workspace for temporary data: "/Users/Ed/Development/mozilla-central"
 0:00.00 LOG: MainThread mozversion INFO application_buildid: 20170718150952
 0:00.00 LOG: MainThread mozversion INFO application_display_name: Nightly
 0:00.00 LOG: MainThread mozversion INFO application_id: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
 0:00.00 LOG: MainThread mozversion INFO application_name: Firefox
 0:00.00 LOG: MainThread mozversion INFO application_remotingname: firefox
 0:00.01 LOG: MainThread mozversion INFO application_vendor: Mozilla
 0:00.01 LOG: MainThread mozversion INFO application_version: 56.0a1
 0:00.01 LOG: MainThread mozversion INFO platform_buildid: 20170718150952
 0:00.01 LOG: MainThread mozversion INFO platform_version: 56.0a1
 0:00.01 LOG: MainThread INFO Application command: /Users/Ed/Development/mozilla-central/obj/dist/Nightly.app/Contents/MacOS/firefox -no-remote -marionette -foreground -profile /var/folders/y2/mv1933z15px1stfzf43sl15c0000gr/T/tmpoRZTUs.mozrunner
 1:00.03 CRASH: MainThread pid:72931. Test:marionette.py. Minidump anaylsed:False. Signature:[None]
Crash dump filename: /var/folders/y2/mv1933z15px1stfzf43sl15c0000gr/T/tmpoRZTUs.mozrunner/minidumps/BE8896FB-317E-45B9-AFBE-554D16E8CF45.dmp
MINIDUMP_STACKWALK not set, can't process dump.

Error running mach:

    ['awsy-test']

The error occurred in code that was called by the mach command. This is either
a bug in the called code itself or in the way that mach is calling it.

You should consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

IOError: Content process crashed (Reason: Timed out waiting for connection on localhost:2828!)

  File "/Users/Ed/Development/mozilla-central/testing/awsy/mach_commands.py", line 220, in run_awsy_test
    return self.run_awsy(tests, **kwargs)
  File "/Users/Ed/Development/mozilla-central/testing/awsy/mach_commands.py", line 131, in run_awsy
    failed = MarionetteHarness(MarionetteTestRunner, args=vars(args)).run()
  File "/Users/Ed/Development/mozilla-central/testing/marionette/harness/marionette_harness/runtests.py", line 72, in run
    runner.run_tests(tests)
  File "/Users/Ed/Development/mozilla-central/testing/marionette/harness/marionette_harness/runner/base.py", line 842, in run_tests
    self.marionette = self.driverclass(**self._build_kwargs())
  File "/Users/Ed/Development/mozilla-central/testing/marionette/client/marionette_driver/marionette.py", line 615, in __init__
    self.raise_for_port(timeout=self.startup_timeout)
  File "/Users/Ed/Development/mozilla-central/testing/marionette/client/marionette_driver/decorators.py", line 28, in _
    m._handle_socket_failure()
  File "/Users/Ed/Development/mozilla-central/testing/marionette/client/marionette_driver/decorators.py", line 23, in _
    return func(*args, **kwargs)
  File "/Users/Ed/Development/mozilla-central/testing/marionette/client/marionette_driver/marionette.py", line 701, in raise_for_port
    self.host, self.port))
```

**Comment by Mardak** [comment]
Sounds like it's broken on mac right now. Works on my linux vm, so testing things there now.

**Comment by Mardak** [comment]
For those not following the bugzilla version of this issue, short summary of initial findings is that moving back to main process completely avoids the awsy regression as the regression is completely from having the extra web content process. https://bugzilla.mozilla.org/show_bug.cgi?id=1381804#c11

There are open bugs to just reuse existing content processes for about:newtab, and this should hopefully fix the regression. https://bugzilla.mozilla.org/show_bug.cgi?id=1376895

**Comment by Mardak** [comment]
This is accepted and has an AWSY followup to remove the preloaded.
