### ISSUE TITLE
Enable telemetry for Pocket in system addon

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2898]
This requires,

* telemetry tracking on the client side  
* data processing and persistence on the data pipeline side

Depends on the progress of #2512, we'll try to land it in Fx56.

**Comment by ncloudioj** [comment]
This needs a full review as mentioned [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1382735).

For Firefox 56, let's just collect category 1&2 data for top stories (like regular clicks/blocks etc.). 

/cc @csadilek

**Comment by k88hudson** [comment]
We already collect clicks on pocket, so that will cover the category 1/2 data we need for fx56.

**Comment by ncloudioj** [comment]
Reopen it as we haven't enabled the impression pings for Top stories yet.

We are waiting for the final call from data steward.

**Comment by Mardak** [comment]
Uplifted the first part to firefox-56 branch https://github.com/mozilla/activity-stream/commit/c41110189b7a5d39db701ca8f09924c496594b0f

The actual turning on will need to be separately uplifted if it's okayed.

**Comment by ncloudioj** [comment]
This is closed via #3170 #3171 #3165

**Comment by Mardak** [comment]
@k88hudson the PR for #3165 is #3174 if you need to rebase/cherry-pick those to the beta branch (assuming we got approval that data on beta)

**Comment by ncloudioj** [comment]
@Mardak Thanks for pointing it out! I've updated the comment.

@k88hudson Let's uplifts those three commits for the Top stories telemetry.
