### ISSUE TITLE
tile for a file:// URL top site has no caption and is misaligned

### ISSUE THREAD

**Issue by heycam** [mozilla/activity-stream#2915]
[I'm not sure if I should be filing issues here or filing bugs in Bugzilla.  Please let me know if this should go elsewhere.]

In my about:newtab top sites tiles, there is an entry for a file:// URL.  It doesn't have a caption (maybe because that file doesn't have a <title>?  I'm not sure) and as a result it gets misaligned.

![about-newtab](https://user-images.githubusercontent.com/1484434/28411728-4a44f83a-6d74-11e7-869f-0aa9478fc801.png)

**Comment by piatra** [comment]
A fix for this landed https://github.com/mozilla/activity-stream/commit/e628aa2297ba1210a10e1274a3ac96268bc1f995 3 days ago. It might be that it was not included in the release.

**Comment by heycam** [comment]
OK, thanks!

**Comment by piatra** [comment]
@ncloudioj can you please confirm?

**Comment by ncloudioj** [comment]
No, this patch has not landed in m-c yet.
