### ISSUE TITLE
Delay loading of content search until necessary

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2917]
From mconley's joy of coding 106 notes:

https://www.evernote.com/shard/s434/sh/4cc743c4-933f-4917-af1e-343acf32a096/eb0c9f60ac08f6f0
> Leaking Blob URI:
contentSearchUI probably leaks Blob URIs if the favicons for the one-off buttons are never shown (like, if the defaultEngine is set, but the user never tries to do a search in about:newtab).

**Comment by k88hudson** [comment]
Do you mean loading the file at all or initializing `ContentSearchUIController`

**Comment by Mardak** [comment]
> Do you mean loading the file at all or initializing ContentSearchUIController

Whatever is causing the URL blob object to exist. I would think it's from constructing as you've done in #2921.

**Comment by Mardak** [comment]
Backed out by #2926

**Comment by jaredkerim** [comment]
Closing this until it is confirmed that we need this.
