### ISSUE TITLE
Dup tiles in the Top sites

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#2933]
Nightly 56.0a1 (Linux)

![screenshot from 2017-07-21 14-40-00](https://user-images.githubusercontent.com/1455254/28477686-3450b2ee-6e23-11e7-9290-fafdbd2a5614.png)

We fixed the same issue in the Test Pilot version by deduping the default top sites against the user's top sites.

**Comment by piatra** [comment]
@k88hudson could we also make use of `fancy-dedupe` and use `selectAndDedupe` in this case?

**Comment by k88hudson** [comment]
Depending on where you're doing the deduping, you might not be able to. I think it might be worth trying to do it in the TopSites feed, in which case I don't think you'll be able to use them – however, you can pull out bits of code as necessary.
