### ISSUE TITLE
Address l10n review comments

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2934]
https://github.com/mozilla/activity-stream-l10n/pull/4

@AdamHillier the localization note for `section_info_option` needs some more context to be useful

@csadilek is `empty_state_topstories` meant to be generic for top stories because it includes "Pocket" in the string. Or should it use `{provider}` to insert Pocket? A localization note would be useful too. A simple fix might be to just rename it `pocket_empty_state` if we expect other top stories to have different empty messages.

**Comment by csadilek** [comment]
@Mardak Sorry, I missed this. Yes, it should use ```{provider}``` to insert Pocket.
