### ISSUE TITLE
New Tab Preferences pane should not have selectable text

### ISSUE THREAD

**Issue by heycam** [mozilla/activity-stream#2935]
I don't think we should allow the user to select the text in the New Tab Preferences pane, since it should feel like Firefox UI.  If teels a little more acceptable to be able to select text in the main about:newtab page.

**Comment by Mardak** [comment]
I suppose a related issue is that both parts of…

**Search**
Search the Web from your new tab.

Should be clickable and have the hover state to toggle the checkbox.

**Comment by Mardak** [comment]
@aaronrbenson says it can be useful to have that text selectable. Wontfixing.
