### ISSUE TITLE
Can't open local file: top site

### ISSUE THREAD

**Issue by nchevobbe** [mozilla/activity-stream#2937]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1383720
One of my top site is a local file.
On latest Nightly (56.0a1 (2017-07-23) (64-bit)), when I click on the tile, nothing happens, and I have the following in the browser console : 

```
TELEMETRY PING: {"client_id":"5e7be74f-7d3a-4446-a40d-56f64aeaa4ae","addon_version":"0.0.0","locale":"en-US","session_id":"{ec3a9a2e-de8f-2e4a-9517-9d6e228506cf}","page":"about:newtab","event":"CLICK","source":"TOP_SITES","action_position":2,"action":"activity_stream_user_event"}
  TelemetrySender.jsm:79
Security Error: Content at about:newtab may not load or link to file:///Users/nchevobbe/Desktop/console-test-app.html.
```

**Comment by piatra** [comment]
@nchevobbe Thanks for reporting. I can reproduce it but I'm not seeing the Security Error message. Is there an extra pref for it?

**Comment by piatra** [comment]
@aaronrbenson Can we make a decision now on whether to filter out local uris from Topsites before we actually try to fix this bug?

**Comment by nchevobbe** [comment]
> Thanks for reporting. I can reproduce it but I'm not seeing the Security Error message. Is there an extra pref for it?

I don't think so. Note that it appears in the browser console (Tools -> Web Developer -> Browse Console), not in the Web Console.

**Comment by Mardak** [comment]
Don't include file:// until we figure out the underlying issue.

**Comment by sarracini** [comment]
fixed with: https://hg.mozilla.org/integration/autoland/rev/4e92ebe6256d 

closing this (we can re-open if for some reason this gets backed out)

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/4e92ebe6256d
