### ISSUE TITLE
short-url.js needs extra fallback in case of missing title

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#2938]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1383859
In case link title is empty [short url](https://github.com/mozilla/activity-stream/blob/75e5bec66d83924b3979925bc1e1fc4cee559999/system-addon/content-src/lib/short-url.js#L26) will return null and crash Activity Stream. This only happens for local uris, depends on [the answer in this bug](https://github.com/mozilla/activity-stream/issues/2937#issuecomment-317418324) if we actually need to fix/handle this. An extra `|| link.url` should fix it.

<img width="1713" alt="screen shot 2017-07-24 at 15 14 59" src="https://user-images.githubusercontent.com/810040/28524994-03aa01ba-7083-11e7-8609-b05f6e1f1f0f.png">

**Comment by Mardak** [comment]
Also see #2937

**Comment by Mardak** [comment]
Just making sure we want to make sure this handles the "letter-fallback" trying to grab the first letter of something with no title.

**Comment by Mardak** [comment]
This should be reproducible by opening a local (non-image) file: `$ touch blank` and opening that file in Firefox.
