### ISSUE TITLE
Inconsistent section titles in system-addon

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2942]
In the test pilot addon, each section has a title which matches its name in the configuration section, such as Top Sites and Top Stories:

<img width="852" alt="screenshot 2017-07-24 13 38 06" src="https://user-images.githubusercontent.com/119884/28536446-99dc0d30-7075-11e7-94a1-89929969f1fa.png">

However in the system addon, instead of 'Top Stories' for the Pocket section, it says 'Recommended by Pocket' in a different font and weight:

<img width="832" alt="screenshot 2017-07-24 13 38 18" src="https://user-images.githubusercontent.com/119884/28536462-ae073816-7075-11e7-97bf-36a1a8c1428b.png">

Is this the desired design or should it match the older design?

**Comment by csadilek** [comment]
Link to latest designs: https://mozilla.invisionapp.com/share/UWCKPZTBY#/screens/243608608_New_Tab_-_All

Looks like top sites header needs to be updated.
