### ISSUE TITLE
Add TippyTop sites to the System Addon

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2944]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1382703
Import the Tippy Top sites list and icons into the System Addon and use them for matching URLs.

**Comment by jaredkerim** [comment]
We need to figure out whether we will bundle the icons directly with the browser or fetch them from a remote CDN.

**Comment by jaredkerim** [comment]
1) pull the npm package (already defined in package.json)

 2) in yamlscripts.yml define a script to copy it from node_modules into a static asset path inside the system addon like data/tippytopicons
 3) then buildmc kicks in and copies the whole system addon into the mc checkout, so now you can find the json manifest and all the pngs locally
 4) load the manifest json at activity stream init into memory inside a tippy top helper
 5) in TopSitesFeed when looping over topsite links, check if they appear in the TippyTop provider and have an icon
 6) if it has it, attach it, and now you don’t need to fetch a screenshot
 7) in content, check for tippy top icon and render that otherwise check for screenshot and render that

**Comment by jaredkerim** [comment]
I think we'll proceed with the assumption that we can do it the same way that we did in Test Pilot and if we have to change this to fetch from a remote resource we can do that.

**Comment by Mardak** [comment]
For 56 shield study, we need to just have tippy top for the default sites. Locale list is unsure yet but it will be at least en-US. Maybe de?

**Comment by Mardak** [comment]
The tippy top sites should match those in https://github.com/mozilla/activity-stream/issues/2776#issuecomment-318460997

So the related US, Canada, Germany, Poland, UK, France, Russia sites.
