### ISSUE TITLE
My top sites are tripping out .......

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#2945]
So I had no pinned top sites, and then I pinned a top site and all of a sudden: 
<img width="1440" alt="screen shot 2017-07-24 at 2 58 01 pm" src="https://user-images.githubusercontent.com/7219526/28539760-d70bfc64-7080-11e7-8938-e4672d996f06.png">

And then the extra 3 wouldn't go away no matter how many times I opened a new tab......

cc @dmose @k88hudson @Mardak @rlr any idea what could be going on here?

**Comment by Mardak** [comment]
Did you pin just one? There was an issue filed at some point where multiple top sites were pinned? Notice the "extra" ones after 12 are also pinned. Perhaps there's some logic making sure pinned sites are always visible?

**Comment by sarracini** [comment]
yeah I had pinned the first one in the second row and then my top sites updated to that. I'm guessing the three that are pinned at the bottom were perhaps pinned from tiles, but didn't show up in activity stream until I kicked it with pinning one that showed up in top sites

**Comment by piatra** [comment]
My thought: On pinning the website we hit this [case statement](https://github.com/mozilla/activity-stream/blob/master/system-addon/common/Reducers.jsm#L140) which does not call `slice`. If you previously had pinned sites (not one of the 12 already presented) in `NewTabUtils.pinnedLinks.links` they will all be added resulting in more than 12 topsites.

**Comment by piatra** [comment]
I managed to reproduce the issue and confirm it's the problem described in the previous comment.
<img width="782" alt="screen shot 2017-08-02 at 21 29 17" src="https://user-images.githubusercontent.com/810040/28891173-defb5f32-77c9-11e7-8a5a-6a79fe6c1c1a.png">
