### ISSUE TITLE
Allow removing default sites

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2947]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1382967

Some users clear history regularly and end up seeing the defaults more often than others. Some of those users don't want to see the default sites but want to see their own history and/or pinned items.

Should users be allowed to block / remove the default sites?

**Comment by Flore-mozfr** [comment]
Thanks Mardak. I am the one who reported the issue on bugzilla. I'd be happy to discuss here too, if needed.

**Comment by Mardak** [comment]
Not for 56. Design feedback will investigate. For now, you can just pin the pages you do want to push out the default sites.

**Comment by Flore-mozfr** [comment]
OK, noted. I'm following the issue and the bug and of course, I will keep the newtab as is and maybe one day, I will notice a change ;)
Thanks for your help

**Comment by Mardak** [comment]
Design says not for Firefox 57. But I just realized that you can set an `about:config` preference `browser.newtabpage.activity-stream.default.sites` to override the default sites:

browser.newtabpage.activity-stream.default.sites;https://a.mozilla.org/,https://b.mozilla.org/,https://c.mozilla.org/,https://d.mozilla.org/,https://e.mozilla.org/,https://f.mozilla.org/,https://g.mozilla.org/,https://h.mozilla.org/
Results in this:
![screen shot 2017-08-02 at 11 53 15 am](https://user-images.githubusercontent.com/438537/28889635-773962d6-7779-11e7-9bfa-b79917d0de7a.png)


Or you can just make it an empty string:
browser.newtabpage.activity-stream.default.sites;
Results in this:
![screen shot 2017-08-02 at 11 53 29 am](https://user-images.githubusercontent.com/438537/28889618-6a177d9a-7779-11e7-9580-1605928946f3.png)

**Comment by Flore-mozfr** [comment]
![capture d ecran 2017-08-03 a 10 54 59-fullpage](https://user-images.githubusercontent.com/6987429/28914036-77310ee4-783a-11e7-9d6b-f5eb8ed3ecfd.png)
@Mardak , I think I got it right...

Anyway, I hope the sites can be changed later by when the product is localized. As a french person, using a french localized version of nightly, I expect ebay**.fr**, amazon**.fr**, yahoo**.fr** and not the american sites.
If it's not planned, let me know, it would be important to create a bug / issue to see that it's localizable when 57 is lauched. FYI, the default search engines and bookmarks are also localized.

**Comment by Mardak** [comment]
Are you *in* France? The latest update has default sites set by region for #2776 in

The PR #3022 set this for users in France.
 +  ["FR", "https://www.youtube.com/,https://www.facebook.com/,https://www.wikipedia.org/,https://www.amazon.fr/,https://www.leboncoin.fr/,https://twitter.com/"] 

Although you need to clear the `browser.newtabpage.activity-stream.default.sites` if you changed it to get the defaults.

**Comment by Flore-mozfr** [comment]
I am in France and using a FR Nighty and if I reset the value, it is still: `https://www.facebook.com/,https://www.youtube.com/,https://www.amazon.com/,https://www.yahoo.com/,https://www.ebay.com/,https://twitter.com/`

I'm using 57.0a1 (2017-08-02) (32 bits) (Identifiant de compilation 	20170802100302) the latest update available. Maybe the patch will land in the next days. Or maybe I messed up something by changing the value before updating Nightly and it reverts to the default value before updating instead of the default value of the build (don't even know if it's possible).

Anyway, I will check this value on my home computer, on which I did not change this value (because I don't clear my history every day there).

**Comment by Mardak** [comment]
Fixed by #3191 for #3188
