### ISSUE TITLE
Backport Bug 1381460 - Add telemetry search event for Activity Stream. f=florian, r=Dexter, data-r=bsmedberg

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2954]
This is landing:
https://bugzilla.mozilla.org/show_bug.cgi?id=1381460
https://hg.mozilla.org/integration/mozilla-inbound/rev/839d8a60a2ea

In particular the "newtab" -> "activitystream"

**Comment by piatra** [comment]
This already has PR https://github.com/mozilla/activity-stream/pull/2904

**Comment by Mardak** [comment]
Will be handled in #2729
