### ISSUE TITLE
Manual migration buttons should expand to fit longer strings

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2955]
Some locales might need more space.

dmose shared this:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/438537/28555244-60b90fd8-70b3-11e7-8c8a-f919d68e64e5.png">
<img width="761" alt="image" src="https://user-images.githubusercontent.com/438537/28578543-f0367424-710e-11e7-80a2-44e39503aec4.png">

@piatra

**Comment by piatra** [comment]
Dropping the height requirements the text will overflow to the second row.
@aaronrbenson What do you think?
<img width="753" alt="screen shot 2017-07-25 at 16 40 09" src="https://user-images.githubusercontent.com/810040/28577788-05af2744-7158-11e7-82ec-03ad0737445d.png">

**Comment by piatra** [comment]
Same for the copy text.
<img width="748" alt="screen shot 2017-07-25 at 16 41 56" src="https://user-images.githubusercontent.com/810040/28577877-4347ef32-7158-11e7-9248-a1aff4bde9a6.png">

**Comment by Mardak** [comment]
I would think it would be preferable to have the buttons expand in width while allowing the description wrap ?

**Comment by Mardak** [comment]
Here's an actual screenshot of localized issue for `fr`:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/438537/28578543-f0367424-710e-11e7-80a2-44e39503aec4.png">

Increasing min-width:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/438537/28578733-6ff10aee-710f-11e7-8e59-73fbc4d74aec.png">

**Comment by Mardak** [comment]
Might have long buttons for de. Don't wrap button text says @aaronrbenson
