### ISSUE TITLE
Increase size of top sites

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2956]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1377317

"The new tab tiles got really small, they are not as useful as before (I can't distinguish the thumbnails as well as before)."

"The tile labels significantly undercut OS default font sizes. This is problematic especially for visually impaired users."

@bryanbell ?

**Comment by Mardak** [comment]
Design says the plan is for top sites to have the large icons not screenshots/thumbnails in the common case. Defer feedback until there are issues raised with the icons design.

**Comment by sarracini** [comment]
the tiles are going to stay 96x96. @bryanbell has spoken. we can close this
