### ISSUE TITLE
Section titles are vertically misaligned

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#2958]
According to the mockups the section title should be vertically centered with respect to the height of its icon, example:

![mockup](https://trello-attachments.s3.amazonaws.com/56f56a284ae0796984e3ca8e/59667156102ccbe243496f55/38515ce1d1a02d9516b8f5c123fbcc74/Screen_Shot_2017-07-12_at_2.43.18_PM.png)

Right now it's aligned with the top:

![screenshot 2017-07-25 13 30 38](https://user-images.githubusercontent.com/119884/28585377-1c41ea06-713e-11e7-8272-f108df36caa3.png)

**Comment by sarracini** [comment]
according to the css it's aligned in the middle: 
https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/styles/_icons.scss#L8

aligning it to the bottom might look better though
