### ISSUE TITLE
get dashboard view on when topsites renders & has rendered all updated screenshots 

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2965]
Proposed user story: 

> As a developer or (product/eng) manager, I can see (possibly overlaid) graphs of when the render completes and when the screenshots are done rendering for a page, so that I can see how long it takes for topsites to become stable.

Over in #2661, we added telemetry for topsites_first_painted_ts.  

One exciting nuance is that in the case where we don't have screenshots for topsites yet, we render placeholders with just the letter of the alphabet.

This happens particularly in the first new tab page after startup, (which is currently never pre-rendered).  After that rendering completes, we'll get 12 (or less) separate messages with screenshot updates from the add-on code, each of which will cause one image to paint.  

In (I believe) most other paints, it doesn't happen at all: when topsites is rendered, it has all the screenshots, so there are no temporary placeholders or subsequent messages filling them in.

Once we figure out what we want here, we'll want to spin off a client-side implementation bug.

**Comment by emtwo** [comment]
Closing as tracked in ping-centre: https://github.com/mozilla/ping-centre/issues/83
