### ISSUE TITLE
Activity Streams breaks my new tab page now ("Access to the file was denied" " The file at resource://activity-streams/data/content/activity-streams.html#/ is not readable.")

### ISSUE THREAD

**Issue by dholbert** [mozilla/activity-stream#2966]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1384240
As of recently, when I open a new tab, I'm now greeted with this as my New-Tab Page:

> Access to the file was denied
> 
> The file at resource://activity-streams/data/content/activity-streams.html#/ is not readable.
> 
>     It may have been removed, moved, or file permissions may be preventing access.

This is in a profile with Test Pilot installed, and the Activity Stream experiment enabled. I was not prompted to disable it.

The problem goes away if I manually disable activity stream at about:addons -- but users shouldn't have to do that (or figure that out).

EXPECTED RESULTS:
If Activity Stream is going to break, we should actively disable it in users' profiles (or remove it, or at the very least "upgrade it" to a stub which no longer replaces the homepage if it's gonna be non-functional going forward, so that at least it's unobtrusively non-functional).

**Comment by dholbert** [comment]
Here's a screenshot of what this issue looks like on my new-tab page:
![screenshot of my new tab page now](https://user-images.githubusercontent.com/426803/28598935-c88d5ea4-715b-11e7-9bee-dcb66b7f4984.png)

**Comment by Mardak** [comment]
Are you on linux? The report on [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1384240) is on linux64 and @jaredkerim believes this might be a file permission issue. "my guess is that wahtever process wrote that to disk and the process that’s currently running firefox are on different accounts and it can’t read from that file path"

**Comment by dholbert** [comment]
I am on Linux64, yeah. I don't run with multiple user accounts, so I don't know why there'd be a file ownership issue, though...

**Comment by alejandrodnm** [comment]
Same here, I'm on fedora 26 - x86 I've been using activity stream on nightly for some time now. But yesterday it started displaying the access denied page.

**Comment by piatra** [comment]
I've received multiple reports of this bug on Linux. One suggestions was that we could trigger the test pilot version uninstall or disable if we see that `browser.newtabpage.activity-stream.enabled = true` that way we only target nightly population.

**Comment by jaredkerim** [comment]
We have responded in the bugzilla ticket with recommendations to disable the test pilot version and switch to the system addon using the pref, so we are closing this.
