### ISSUE TITLE
Don't show manual migration offer on existing profiles

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2967]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1384392

"This is a little weird, because this is the Firefox profile that I've been using for 6+ years now. Why suddenly offer to import data? … seems like this should only be triggering for recently created profiles.

**Comment by piatra** [comment]
@aaronrbenson @bryantmao There was a discussion at one point about this where 57 being such a big release we might get a lot of old users back and still want to present them with the option of importing their profiles.

**Comment by bryantmao** [comment]
We now have the auto refresh option in the stab installer for existing user whose Firefox are 2 version behind (55 or earlier). If they check that option, we'll treat them as a new user which they'll get the New user UI tour and notification, and I think that can apply to migration as well. 

For an active user who directly updates from the browser, that seems a bit weird even if there are significant changes in 57, since they might already be using Firefox, save a lot of stuff and even set it as their default browser.

**Comment by piatra** [comment]
Related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1369255

**Comment by Mardak** [comment]
In a bug related to the related bug..

Bug 1376558 - Should not migrate session for Firefox auto-refresh, r=MattN
```js
let env = Cc["@mozilla.org/process/environment;1"].getService(Ci.nsIEnvironment);
if (env.get("MOZ_RESET_PROFILE_MIGRATE_SESSION")) {
```

Not sure if that's what we'll need to use or if Firefox will be setting a pref on startup after detecting the environment variable.. Or we'll need some other way to detect that it was autorefreshed.

The assumption is that the first time Activity Stream logic is running, there should be some pref/env that is already set on autorefresh. If it doesn't exist, we should then set expired to true.

Probably can do that inline from https://github.com/mozilla/activity-stream/blob/7dde26f2bff166c7612bda1cad2898ec67cba4a1/system-addon/lib/ActivityStream.jsm#L90-L92

Set the default for expired to false if the auto refresh happened. However, if it's an env, subsequent starting of Firefox might not have it set, so we might need to persist that information differently. Or have Firefox persist it in a way that Activity Stream can reference it consistently.

**Comment by Mardak** [comment]
Design says this would be not ideal for the existing beta 56 users during the shield study as most likely they're ongoing Firefox users. Not sure what the interim solution would be before the stub installer.

**Comment by Mardak** [comment]
A simple fix for 56 might be to set expired by default...

@bryantmao is there a particular need to have manual migration shown to 56 beta users (that are selected in the shield study)?

**Comment by Mardak** [comment]
Summarizing: For 56, figure out or estimate when profile creation was and don't show manual migration if creation is older than 3 days ago
