### ISSUE TITLE
Don't error when snippets service returns no snippets.

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/activity-stream#2968]
Activity stream shows an empty, all white, `#snippets-container` and returns to the console `
```
NS_ERROR_NOT_AVAILABLE
showDefaultSnippets about:newtab:109:13 <anonymous> about:newtab:174:9 <anonymous> about:newtab:103:2 _showRemoteSnippets resource://activity-stream/data/content/activity-stream.bundle.js:874:7 init resource://activity-stream/data/content/activity-stream.bundle.js:915:7 next self-hosted:1183:9
```

if the server returns no snippets. [Example response with no snippets](https://pastebin.mozilla.org/9028001)

Expected behavior:

AS should not display `#snippets-container` at all and produce no errors. It should normally cache the response. It's totally valid to not serve snippets for some locales.

/cc @k88hudson

**Comment by glogiotatidis** [comment]
Actually that was related to `showDefaultSnippets` function that the snippet payload called if there were no snippets to display. That said it's very difficult to debug injected JS code with those cryptic messages. Do you have any suggestions on how to debug better @k88hudson ?

I fixed it:
 - by removing the call to that non-existent function and
 - by altering the logic in the snippet's service payload to [handle the display of `#snippets-container`](https://github.com/mozmeao/snippets-service/pull/254/files#diff-050fa7fbdf0fa60913c8fc36985fa302R26) there. I'll followup with related a PR for activity stream. Since we're deciding which snippet to display in the snippets-payload it feels like we should control the display of the container there as well.  

See also https://github.com/mozmeao/snippets-service/pull/254/

**Comment by k88hudson** [comment]
Ah ok I understand now. I have some placeholder CSS there right now, but I think maybe I should just remove it and let the template / payload handle it completely. What do you think?

**Comment by k88hudson** [comment]
Also, I was thinking we shouldn't actually show default snippets at all if no remote ones exist, since the new design is a lot more intrusive than the old design.

**Comment by glogiotatidis** [comment]
> Also, I was thinking we shouldn't actually show default snippets at all if no remote ones exist, since the new design is a lot more intrusive than the old design.

Agree. We have no default snippets for AS now anyway

**Comment by glogiotatidis** [comment]
> Ah ok I understand now. I have some placeholder CSS there right now for #snippets-container, but I think maybe I should just remove it and let the template / payload handle it completely. What do you think?

Yes! I filed a PR https://github.com/mozilla/activity-stream/pull/3005
