### ISSUE TITLE
Perma-orange EVERYWHERE a connection attempt to getpocket.com (54.87.88.43) was made.

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2971]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1384721
```
 GECKO(1659) | FATAL ERROR: Non-local network connections are disabled and a connection attempt to getpocket.com (54.87.88.43) was made. [log…] 
```

Most likely caused by https://github.com/mozilla/activity-stream/pull/2960

Probably just need to set the appropriate pref in
```
testing/profiles/prefs_general.js
testing/talos/talos/config.py
```

See example:
https://bugzilla.mozilla.org/show_bug.cgi?id=1382719
https://hg.mozilla.org/mozilla-central/rev/7d2e89fb92331d7e4296391213c1e63db628e046

**Comment by k88hudson** [comment]
Should we maybe implement a test value (similar to `value_local_dev`) in our configuration to prevent this from happening in the future

**Comment by Mardak** [comment]
The specific bug https://bugzilla.mozilla.org/show_bug.cgi?id=1382719 was caused by us using `value_local_dev` instead of setting `prefs_general`-related files.

**Comment by dmose** [comment]
I've landed a temporary patch in github while the patch from the above bug works its way through autoland to mozilla-central.  Once that has happened, i'll back the temporary patch out here.

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/8798108d6ad4
