### ISSUE TITLE
Follow photon color schemes

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2979]
http://design.firefox.com/photon/visual/color.html

Some things are already following the guide, e.g., 
```
$info-option-text-color: #0C0C0D;
$info-option-link-color: #0A84FF;
```

We might want to rename and update references to match those of photon, e.g., `$grey-90` and `$blue-50`. Might also want to alias them to friendlier names, e.g., `$link-color`

This will probably lead to some shifting around of colors in the existing interface to match photon.

**Comment by aaronrbenson** [comment]
We need to update the new tab background color to match the toolbar. Should be Grey 10 (#f9f9fa) in the design system.

**Comment by AmyYLee** [comment]
Hi, 

I've attached a spec for the New Tab page with the Photon color palette applied. Please use this as reference.
https://mozilla.invisionapp.com/share/8KCY4I0QU

**Comment by Mardak** [comment]
@AmyYLee there's some colors with opacities, e.g., search text is Grey-90 60% opacity. Is it intended to have it slightly transparent to blend with the background? Or should the color be the closest thing to Grey-90*60% = Grey-54 -> Grey-50, i.e., #737373, to actually match Photon color scheme?

@aaronrbenson other than the question of opacity above, anything else before someone should implement this?

For whoever implements, I believe we want to rename our variables to match the photon names, so future designs would just include the photon color name instead of the hex.

**Comment by AmyYLee** [comment]
Hi, 

The opacity should be set in the alpha channel. I've also updated the spec to include card hover colour, search box color, drop-shadows, etc. Thanks!

**Comment by Mardak** [comment]
All text should be 100% opacity, so calculate the closest Gray-photon-acceptable number.
Search box is special and be 60% opacity.

**Comment by Mardak** [comment]
@AmyYLee do any of the secondary icons need to become 80% opacity on hover:

- info icon for pocket section (maybe?)
- trending / now story icons (probably no as not separately interactable?)
- pinned icon for top sites (probably not as clicking it doesn't toggle the icon?)
- search stuff ? do these want to go from 60% to 80% on hover
-- related, when it's active, the text color should be grey-90 100%?

**Comment by AmyYLee** [comment]
do any of the secondary icons need to become 80% opacity on hover:

    info icon for pocket section (maybe?) - This can match the rollover effect in the icons in the URL bar. Also it looks like the door-hanger overlaps onto the icon. It should appear just below it.
    trending / now story icons (probably no as not separately interactable?) - No hover style needed
    pinned icon for top sites (probably not as clicking it doesn't toggle the icon?) - No hover style needed
    search stuff ? do these want to go from 60% to 80% on hover - Not really sure what you mean by "search stuff" No hover style needed
        related, when it's active, the text color should be grey-90 100%? - Yes

**Comment by Mardak** [comment]
@AmyYLee says links should be using a different blue than the teal for topics. We'll need two blue colors: one for static link and one for hovered link. Currently there's 3 links and the articles specially show gray-90 instead of static link color:

old:
![image](https://user-images.githubusercontent.com/438537/29796245-f04b02a2-8c04-11e7-98eb-0943a96918b5.png)

photon teal-70:
![image](https://user-images.githubusercontent.com/438537/29796238-e9eb579a-8c04-11e7-91b9-f2b6642ce83a.png)

**Comment by Mardak** [comment]
Looks like we'll cover additional photon color changes with #3281

**Comment by Mardak** [comment]
Amy says link should be Blue-60 #0060DF with no hover color difference. Topics keeps the teal-70.

**Comment by AmyYLee** [comment]
The spec has been updated with some styling changes (coloured in green). I've also added Aaron's spec for Import Message. Attaching the import icon as well. 
[import-16.svg.zip](https://github.com/mozilla/activity-stream/files/1261243/import-16.svg.zip)
Updated Spec: https://mozilla.invisionapp.com/share/MHD92KAYR
