### ISSUE TITLE
Remove PreviewProvider from mozilla-central

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2984]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1384977

Found when investigating #2893. This will start failing when the 56 code moves to beta: `  {file: "resource://app/modules/PreviewProvider.jsm", skipNightly: true},`
https://searchfox.org/mozilla-central/source/browser/base/content/test/static/browser_all_files_referenced.js#88

```
 FAIL | browser/base/content/test/static/browser_all_files_referenced.js | unused whitelist entry: resource://app/modules/PreviewProvider.jsm
```
https://treeherder.mozilla.org/logviewer.html#?job_id=118249381&repo=pine&lineNumber=2426

@sarracini can this file be removed from mozilla-central and remove the `all_files_referenced` entry? I believe it was kept around for test pilot? We shouldn't have the test pilot version running on 56 anyway?

**Comment by sarracini** [comment]
@Mardak yes! Remove it!!!

**Comment by dmose** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1384977

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/cfd698429f63
