### ISSUE TITLE
Should we block https://www.mozilla.org/en-US/privacy/firefox/ from topsites?

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#2993]
For new users, it kind of sucks that https://www.mozilla.org/en-US/privacy/firefox/ ends up as their top site. I wonder if there's a better way to prevent privacy/update related-pages from getting added?

**Comment by Mardak** [comment]
Other first-run pages include things like https://www.mozilla.org/en-US/firefox/56.0/firstrun/

**Comment by pdehaan** [comment]
Can we block based on RegExps? (since I see locales in both URLs and a version number in the latter URL).
