### ISSUE TITLE
Detect "blank" behavior to hide any new sections

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2996]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1385064

"When we start shipping the 'Recommended by Pocket' section, we should hide it if the user has 'Search' and 'Top Sites' disabled. It's highly likely that these users don't want to be distracted and want a blank new tab."

Basically if pocket weren't available to a user/locale before, and the user had already turned off search and top sites (and anything else), it would be a good guess that the user didn't want anything visible, so when pocket is turned on by default, it should actually be turned off to keep the page blank.

There was some discussion designs around having a completely separate pref checkbox to set to blank at some point, but that was decided against in #2683 specifically https://github.com/mozilla/activity-stream/issues/2683#issuecomment-308547074

**Comment by piatra** [comment]
Where are we turning pocket on by default?

**Comment by Mardak** [comment]
We shouldn't work on this bug until design feedback. I could see the argument for both sides of wanting to keep blank vs wanting to show off the new stuff. And to get both, the "better" approach could be to reopen #2683.

**Comment by Mardak** [comment]
#3020 would probably remove the need for this as one would just turn off the whole page.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1385064
