### ISSUE TITLE
Use smarter locale fallbacks if there's no exact match

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3003]
@csadilek noted that the strings fallback uses "en-US" when there's no exact match, e.g., the user set `general.useragent.locale` to "de-DE" but Activity Stream/Firefox/Pontoon only expects "de". Similarly if someone sets "es", we could somehow choose one of es-{AR,CL,ES,MX}.

Use something like
```js
Services.locale.negotiateLanguages(
  Services.locale.getAppLocalesAsLangTags(),
  Array.from(locales.keys()),
  this.defaultLocale);
```

-------

Old issue stuff:
Not sure if there's existing logic already but probably something along the lines of..

1. check exact match
2. check first-part match, e.g., "de" of "de-DE" or "de-FOO"
3. check for first-duplicated+uppercase, e.g., "es-ES" from "es"
4. pick first of first-part prefix match, e.g., "zh-CN" for "zh" (from zh-{CN,TW})
5. use en-US

**Comment by Mardak** [comment]
@flodolo just making sure, Firefox list of built locales will have a `general.useragent.locale` that matches those of Pontoon? So we shouldn't really need to handle this situation unless the user is manually entering in a value?

**Comment by flodolo** [comment]
CC @pike and @zbraniecki to make sure I don't say anything wrong, and for some code expertize

`general.useragent.locale` is the UI language. You can set it to whatever you want in your en-US build, but it will keep showing English UI. It can be manually flipped to change language if you install a language pack.

I confess don't remember what technology Activity Stream's add-on is using? For example, I'm aware of at least a [bug in the work](https://bugzilla.mozilla.org/show_bug.cgi?id=1357902) on for WebExtensions, I have no clue what an SDK add-on does.

Having said that, a user manually setting that pref to de-DE is an edge case.

**Comment by zbraniecki** [comment]
so, you should not use the pref for UI locale. We have LocaleService::GetAppLocales, and LocaleService::{Set|Get}RequestedLocales for that.

There's also negotiateLanguages API which given requested "de-DE" and available ["en-US", "de"] will return ["de"] for you.

There's a patch in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1357902 that is aiming to turn it on for WebExtensions and @kmaglione is supposed to land it any day now.

**Comment by Mardak** [comment]
Oh nice. Thanks for that bug reference. Activity stream is not a webextension -- just a plain old bootstrapped extension, so we should be able to call in to whatever webextensions would have done.

**Comment by Mardak** [comment]
It sounds like "de-DE" and other "de-*" locales, e.g., "de-AT", are being used. Currently activity stream only supports "de" and we'll be turning on shield study for german locales. We need this fix so that those de-DE locales don't get english for the study.

**Comment by zbraniecki** [comment]
yep, that's exactly the API you want to use :) I'm also switching a couple more uses of that here: https://bugzilla.mozilla.org/show_bug.cgi?id=1385416

You may be interested in the `lookup` strategy as used in the patch and using `this.default_locale || Services.locale.defualtLocale` here because lookup requires a default locale, and App's default locale is a good fallback.

**Comment by Mardak** [comment]
I believe `negotiateLanguages` will return an array, so potentially we can do a cascading fallback on a per-string basis instead of whole locale. E.g., if missing string "foo" in "es-AR", it can use "foo" of "es-ES" and if not there, "en-US".

@dmose At minimum, we should fix it so "de-*" uses "de" strings instead of "en-US"

**Comment by zbraniecki** [comment]
@Mardak if you're using Fluent, it'll do it automatically (the fallbacking), but yes, you definitely can and we'd recommend to do fallbacks :)

If you want a fallback list, the strategy for language negotiation to use is called `filtering`.
