### ISSUE TITLE
Check desired geo and locales list for turning on Pocket in 56

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3004]
See https://docs.google.com/spreadsheets/d/1hyI166PJFAFkBVaNqIz7MkFApdpo2C_dUwO0-GwnSxA

We need logic to check the geo pref "browser.search.region" It should be a 2 letter uppercase value or blank if search hasn't set it yet (but that should happen pretty soon after first start). If it doesn't exist, we need to observe when it does change so that the appropriate showTopStoriesByDefault default pref gets set. https://github.com/mozilla/activity-stream/blob/0675a44abd1b3954565501df7b71f8f5e9fb32e5/system-addon/lib/ActivityStream.jsm#L28

The logic to turn on is that the geo AND locale need to match the "desired" list.

**Comment by Mardak** [comment]
Blocked on confirmation of which locales

**Comment by Mardak** [comment]
Here's the geo and locales from the doc:


US | en-US
-- | --
US  | en-GB
US  | en-ZA
CA | en-US
CA  | en-GB
CA  | en-ZA
DE | de
DE  | de-DE
DE  | de-AT
DE  | de-CH

**Comment by k88hudson** [comment]
I'm pretty sure someone mentioned `en-GB` was not supposed to be included for Pocket, isn't it North America only? Or did something change recently?

**Comment by Mardak** [comment]
US + en-GB means it's a US person that prefers en-GB as their favourite Firefox.

**Comment by k88hudson** [comment]
Ahhh I see

**Comment by Mardak** [comment]
On initial testing, `Services.prefs.getStringPref("browser.search.region")` will throw on a clean profile from the top level of `ActivityStream.jsm`

**Comment by Mardak** [comment]
I updated the spreadsheet to generate code that can be used in PR #3021:
https://docs.google.com/spreadsheets/d/1hyI166PJFAFkBVaNqIz7MkFApdpo2C_dUwO0-GwnSxA
