### ISSUE TITLE
Snippets: Read telemetryEnabled from Services.telemetry.canRecordBase.

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/activity-stream#3007]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1384843
Based on suggestion given by  :gfritzsche in [Bug 1384843](https://bugzilla.mozilla.org/show_bug.cgi?id=1384843) we should get `ervices.telemetry.canRecordBase` instead of directly reading prefs.

/cc @k88hudson

**Comment by dmose** [comment]
We're going to want this for the rest of our telemetry too, I think.  We should grep the code base for other users of telemetry-related prefs.

**Comment by k88hudson** [comment]
Ok thanks!
