### ISSUE TITLE
Content tab hangs content process after going to an invalid page

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3011]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1384168

1. Try going to "about:pref" (invalid page)
2. Switch to another tab
3. Try switching back to the invalid page tab and can't
4. Firefox now won't be able to quit either

Looks like this only happens when activity-stream.enabled pref is turned on. Maybe something to do with forcing content process? @dmose ?

**Comment by dmose** [comment]
It looks to me like this already fixed in the bugzilla bug and autolanded.  Or am I missing something?

**Comment by Mardak** [comment]
This bug "has PR" for the mozreview

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/e2c06426fc2e
