### ISSUE TITLE
FirstPartyDomain should be properly set for about:newtab

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3014]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1385308

"We should figure out how to properly set the firstPartyDomain for about:newtab, or at least figure why the test is failing when we set the URI_SAFE_FOR_UNTRUSTED_CONTENT flag in the first place."

**Comment by sarracini** [comment]
Yoshi took this and there's a PR in circulation, I think we can close this since we won't have to do this and it won't contribute to our tracking numbers

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/2cc320aac603
