### ISSUE TITLE
Make Pocket thumbnail's settings button permanently visible, and remove article once it's clicked or added to Pocket or Bookmarked.

### ISSUE THREAD

**Issue by smartfonreddit** [mozilla/activity-stream#3019]
To make Pocket stream more touch-friendly, please make the "..." setting button on top-right corner of each thumbnail permanently visible and bigger, so there will be no need to hover a mouse to see it. Perhaps you could tie this to Firefox's "browser.uidensity" configuration. If it's set to 2 that means the user is using touch screen and needs big icons. It's hard to use the button with high accuracy even with a mouse.

Once the article is bookmarked or added to Pocket, ideally it should be automatically removed from the list.

**Comment by Mardak** [comment]
#3020 would probably remove the need for this as one would just turn off the whole page.

**Comment by Mardak** [comment]
The "..." issue is tracked in #3280 now https://bugzilla.mozilla.org/show_bug.cgi?id=1432299

Hiding the story when bookmarked was handled in #3675. And the deduping against pocketed items will probably naturally happen when pocket items show up in "weighted" highlights.
