### ISSUE TITLE
Initial brief white flash when opening new tabs

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3025]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1382373

Seems to happen even with prerendered browser.

Might be something with content process?

**Comment by Mardak** [comment]
dao suggests it's probably not worth optimizing for the "opening many tabs" case https://bugzilla.mozilla.org/show_bug.cgi?id=1382373#c7

**Comment by aibaraiduas** [comment]
The title of this bug should read "Initial brief white flash when opening new tabs," since it occurs every time a new tab is opened, not just when opening many tabs in quick succession.

**Comment by sarracini** [comment]
tracking in bugzilla now
