### ISSUE TITLE
Card domain does not cut off all TLDs 

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3029]
Reported via slack by Nate:
![pasted image at 2017_07_28 03_03 pm](https://user-images.githubusercontent.com/7219526/28782848-70a4e786-75dc-11e7-9d5c-9c2c61b336a4.png)

> Looks like we have logic on these cards that cuts off ".com" from domains (see Wired above), but looks like we may be missing other TLDs (ex .org, see HBR's card)

**Comment by sarracini** [comment]
So digging into this a little deeper, since it actually should work with things like "org" or "net" at TLDs, the issue is this:
For top sites, in NewTabUtils.jsm we've got a function called _addETLD which every top site runs through, which means down in short-url.js it's got a TLD that it can remove. However with pocket, we don't run through that function, so we don't have a TLD for that link, and so we fall back on a match with ".com", which of course, doesn't work with "hbr.org".

So we could either 1. extend our match to have other TLDs like "org", "net", "ca" etc... or 2. run the pocket links through an _addETLD type function to add a TLD in the feed before passing it down to get rendered.

**Comment by dmose** [comment]
Usee _addETLD or something like it.  We don't want to write our own matching function, because that stuff gets complicated in international domains and it's easy to miss stuff (eg the UK equivalent of .com is .co.uk, and most countries have similar "top-level" domains).  We want to take advantage of existing logic if we can.

**Comment by dmose** [comment]
Seems fine to me.  @sarracini can you file a bug for us to use a real ETLD list for short-url.js too?
