### ISSUE TITLE
Empty Pocket stories message is hard to read

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3032]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1385894

![image](https://user-images.githubusercontent.com/438537/28789402-29a534a0-75da-11e7-8e3e-5ffdaef24e21.png)

**Comment by apoorvasingh17** [comment]
I'm a beginner and would like to work on this bug. How should I get started?

**Comment by dmose** [comment]
@apoorvasingh17 thanks for your interest!  Right now, everyone on our team is up against a deadline, so you may not get much feedback right away.  However, with luck, we'll have some more cycles on Wednesday, and, also with luck, the design folks will have provided design feedback (ie what they're specifically hoping to have implemented by mid-day Pacific time on Wednesday as well). 

In the meantime, here's something that should help you get started: https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/1.GETTING_STARTED.md

**Comment by dmose** [comment]
@bryanbell any update on the design here?

**Comment by Mardak** [comment]
To be fixed with #2979. Basically there's 2 colors for everything -- either primary or secondary. This text and icon would fall under secondary.
