### ISSUE TITLE
Allow loading more news stories than the 3 to use more available space

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3043]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1385944

"load more news item on it there is only 3 item on screen utilize full screen because both side too much space is left blank."

**Comment by AdamHillier** [comment]
Showing more cards would be easy, it's just a parameter passed by TopStoriesFeed, but they would end up in a new row and not use additional horizontal space.

**Comment by aaronrbenson** [comment]
We're tracking this in a Trello card. We'll address this post 57 as we triage new feature work.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1385944
