### ISSUE TITLE
Get review on our CSP

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3045]
We added a CSP via meta tag in activity-stream.html, but right now it's set to Report-Only. It would be nice to get someone from security to review our current CSP

**Comment by dmose** [comment]
It would also be helpful to know if there's a way to prevent us from being iframed from a <meta> tag CSP.  frame-ancestors didn't appear to work when tried.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448359
