### ISSUE TITLE
addMessageListener not defined

### ISSUE THREAD

**Issue by Pike** [mozilla/activity-stream#3054]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1386445
Every now and then, I get an empty homepage. Found the following message in the console:
```
ReferenceError: addMessageListener is not defined[Weitere Informationen] activity-stream.bundle.js:772:3
	initStore resource://activity-stream/data/content/activity-stream.bundle.js:772:3
	<anonym> resource://activity-stream/data/content/activity-stream.bundle.js:2705:15
	__webpack_require__ resource://activity-stream/data/content/activity-stream.bundle.js:20:12
	<anonym> resource://activity-stream/data/content/activity-stream.bundle.js:66:18
	<anonym> resource://activity-stream/data/content/activity-stream.bundle.js:1:11
```
This is on Nightly.

**Comment by Mardak** [comment]
That line is `  addMessageListener(INCOMING_MESSAGE_NAME, msg => {` which would probably indicate that the page isn't set up to be remote yet which is being fixed in #2819. Duping to that.

**Comment by Mardak** [comment]
Actually this seems to be separate. Did you set about:newtab to be your start/home page?

**Comment by Mardak** [comment]
Not quite fixed yet. This needs a m-c change to get `AboutNewTab` initialized earlier.

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/b48486fff521
