### ISSUE TITLE
Pocket Suggestions are enabled by default in fresh Nightly profiles 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/activity-stream#3072]
I checked on Slack and Pocket should be an `opt-in` feature. However on fresh Nightly profiles I get Pocket Suggestions "on" enabled by default.

See GIF below:

![](https://user-images.githubusercontent.com/128755/28880693-d59fb9de-7773-11e7-8f3b-b001bf6ccba2.gif)

### STR

* New Nightly Profile
* Open new tab page

### Expected

* Pocket should be hidden

### Actual

* Pocket recommended stories are visible

Build: 57.0a1 (2017-08-02) (64-bit)

**Comment by Mardak** [comment]
Pocket was turned on by default for en-US builds with #2943 then more correctly turned on by country (currently US, Canada, Germany) by #3004

**Comment by vladikoff** [comment]
Thanks @Mardak !!
