### ISSUE TITLE
Better handling of missing or poor quality Pocket/Highlights images

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3074]
@ideashower @csadilek

Right now there's these 3 stories from pocket:
![screen shot 2017-08-02 at 10 23 13 am](https://user-images.githubusercontent.com/438537/28886321-ee0dffb8-776d-11e7-9343-f0bf5cb48958.png)

The first image is poorly cropped:
https://d33ypg4xwx0n86.cloudfront.net/direct?url=https%3A%2F%2Fassets.bwbx.io%2Fimages%2Fusers%2FiqjWHBFdfxIU%2FiHawO9rQZ5Fw%2Fv0%2F150x-1.jpg&resize=w450
![image](https://user-images.githubusercontent.com/438537/28886419-4c0cd170-776e-11e7-88fa-c6e85006f269.png)

The second image is a single pixel high white line?
https://d33ypg4xwx0n86.cloudfront.net/direct?url=https%3A%2F%2Fstatic01.nyt.com%2Fimages%2F2017%2F07%2F30%2Fmagazine%2Ffullbleed-spacer%2F30whitemarble-fullbleed-articleLarge-v6.gif&resize=w450
image -- > ![direct](https://user-images.githubusercontent.com/438537/28886443-605221e4-776e-11e7-833c-1428be79f055.gif) < -- here

The third image is almost illegible text:
https://d33ypg4xwx0n86.cloudfront.net/direct?url=https%3A%2F%2F25iq.files.wordpress.com%2F2017%2F07%2Fpoker.png%3Fw%3D440&resize=w450
![image](https://user-images.githubusercontent.com/438537/28886446-66773460-776e-11e7-8eec-c2284b655a63.png)

**Comment by Mardak** [comment]
Positioning the image at the top/left instead of center/center:
![screen shot 2017-08-02 at 11 21 18 am](https://user-images.githubusercontent.com/438537/28888293-e42c5600-7774-11e7-9490-56afe6ce17f4.png)

**Comment by Mardak** [comment]
Looks like Chrome extension for the second item with effectively no image just shows more space for the text/title/description and show no image.

**Comment by Mardak** [comment]
Here's a quick css hack to `display: none` image, increase height of `.card-text`, adjust negative margin of `.card-host-name` (so it's higher than usual but text at bottom of description fits better):

![screen shot 2017-08-02 at 11 30 14 am](https://user-images.githubusercontent.com/438537/28888670-4ed74d06-7776-11e7-8d98-802eceaea590.png)

Or maybe have one fewer line of description so there's more whitespace at top and before "Trending".

**Comment by Mardak** [comment]
@bryanbell says put a little more space under the title

**Comment by Mardak** [comment]
Here's some of the recent articles with larger thumbnails than can be shown:
![screen shot 2017-08-27 at 4 22 45 pm](https://user-images.githubusercontent.com/438537/29754934-667d2a34-8b44-11e7-99b9-b3ca47dd7426.png)

and when they're positioned to the top instead of center:
![screen shot 2017-08-27 at 4 23 14 pm](https://user-images.githubusercontent.com/438537/29754935-6ff7e496-8b44-11e7-9dbd-4efc93a2db9a.png)

**Comment by Mardak** [comment]
Retriaging as highlights are much more likely to have no images for bookmarks

**Comment by Mardak** [comment]
@nchapman noted:

Here is an example of the "Recommended by Pocket" row with a portrait image in the third position. I imagine this applies to Highlights as well but it could be specific to this type:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/3095/31782083-cf33a36c-b4ae-11e7-8a08-e25d25701b12.png">

That third image is this one:

<img src="https://img-getpocket.cdn.mozilla.net/direct?url=https%3A%2F%2Fstatic01.nyt.com%2Fimages%2F2017%2F10%2F16%2Ft-magazine%2Fnicki-minaj-slide-O7D6%2Fnicki-minaj-slide-O7D6-articleLarge.jpg&resize=w200">

We should try to show the person's face instead of their torso. I've had good luck with aligning portrait images to the top instead of middle. This requires that we know the dimensions of images ahead of time. There are fancier solutions (face detection 😁), but I think combining width to height ratio with alignment should get us pretty far.

**Comment by aaronrbenson** [comment]
Oddly enough I got a duped story from Pocket an Highlights with different treatment of the thumbnail.

![screen shot 2017-10-23 at 5 04 19 pm](https://user-images.githubusercontent.com/139451/31915575-8fdf37a8-b814-11e7-9088-a66e3941e7bb.png)

**Comment by Mardak** [comment]
The bottom image is for Highlights that uses the page's og:image https://static01.nyt.com/images/2017/10/22/fashion/22WITH/22WITH-facebookJumbo.jpg

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448360
