### ISSUE TITLE
Card layout when missing preview image

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3079]
I can't elaborate something more complex than just: it looks broken.
Personally I would hide all stories that don't have an image. Any other attempts just break the nice layout top stories has.
<img width="246" alt="screen shot 2017-08-03 at 11 58 35" src="https://user-images.githubusercontent.com/810040/28916680-56c53de8-7843-11e7-9d70-4a1a20bff3e0.png">

<img width="760" alt="screen shot 2017-08-03 at 12 00 02" src="https://user-images.githubusercontent.com/810040/28916705-6e0bffe6-7843-11e7-8e2f-328e1d7007df.png">

**Comment by Mardak** [comment]
There's also a related #3074 where it would make a story with a poor image just only show the text.

**Comment by Mardak** [comment]
@aaronrbenson says at minimum adjust the bottom cropping to not be bad.

@bryanbell says "do math". We want to have pictureless stories.

**Comment by Mardak** [comment]
Duping to #3074 which has the same desired behavior for small/bad images as no images.
