### ISSUE TITLE
Open about:accounts from snippets in activity stream

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/activity-stream#3083]
Hi folks,

Our snippets system used to be able to open `about:accounts` when a user clicked on relevant snippet. E.g. we have snippets like `Hey Firefox Accounts are great, _click here_ to get one` and we would open `about:accounts` for the user.

The thing is that `about:accounts` being a special page you cannot directly link to it. You can however trigger a UITour custom event to get UITour open the page. ([See code from about:home snippets](https://github.com/mozmeao/snippets-service/blob/master/snippets/base/templates/base/includes/snippet.js#L628-L640))

This using UITour still a possibility or should we look into other ways to implement this?

/cc @k88hudson

**Comment by k88hudson** [comment]
@glogiotatidis do you need the rest of the functionality for adding params to the url (defined here http://searchfox.org/mozilla-central/source/browser/components/uitour/UITour.jsm#540) or just to simply open the URL?

**Comment by glogiotatidis** [comment]
Ideally we want to open in the signup form as the UITour does so we'll have to add `action=signup` to the URL. Also if you can hardcode `entrypoint=snippets` instead of `uitour` would be perfect. Thanks!
