### ISSUE TITLE
Update tippy top icons for youtube and facebook.

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3087]
See https://github.com/mozilla/tippy-top-sites/pull/75

I'll merge that, create a release and update package.json. This needs to be uplifted for 56.

**Comment by Mardak** [comment]
It sounds like this might not be needed for 56 shield studies.

**Comment by rlr** [comment]
Cool. It also sounds like there is more work to be done on tippy tops to make legal happy.

**Comment by rlr** [comment]
I'll file a new bug when it's clear what we need to do.
