### ISSUE TITLE
Collect 'user_prefs' on session and event pings

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#3089]
I noticed we didn't collect this when I wanted to look at users with pocket enabled in the system addon.

**Comment by piatra** [comment]
@emtwo which user prefs are you referring to? what sections are currently displayed? or others as well.

**Comment by emtwo** [comment]
@piatra I just mean what sections are currently displayed. which is how we defined the `user_prefs` value in Test Pilot.

We were collecting this field in Test Pilot but I guess we haven't transferred it over yet.

**Comment by Mardak** [comment]
Uplifted to firefox-56 branch https://github.com/mozilla/activity-stream/commit/fdffb523298f8ddd1bc64f7b573429096b07a622
