### ISSUE TITLE
Remove Send Feedback link just before 57 moves to Beta

### ISSUE THREAD

**Issue by ideashower** [mozilla/activity-stream#3106]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/188963/29037039-c2a35ec6-7b56-11e7-90a3-9a6423a3005e.png">

We should remove the "Send Feedback" link before Top Stories goes into the broader 56 shield study. Otherwise the volume on that form is going to be too high.

//cc @csadilek

**Comment by Mardak** [comment]
The code for 56 is already on mozilla-beta past the code freeze for 56. If we do make this change, it'll need special approval by release drivers

**Comment by ideashower** [comment]
Good to know - Let me confirm with the team as to what the impact would be if that link is left in there. Should have an answer by tomorrow.

**Comment by Mardak** [comment]
On a related note, we do want to keep this in for Nightly 57, but definitely remove it before Beta 57 where activity stream should be on by default?

**Comment by ideashower** [comment]
Synced with the team - This will be fine for 56 but should be removed for beta57, thanks!

**Comment by Mardak** [comment]
Okay. We'll remove this before 57 moves from Nightly to Beta so that we can still get feedback

**Comment by Mardak** [comment]
This won't be necessary as #3265 will be replacing it with the privacy notice text and link.
