### ISSUE TITLE
A-S Home page resource is available when switching from Nightly 56 with A-S Dev installed to Nightly 57 with A-S system add-on

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#3109]
**[Affected versions]:**
- Firefox Nightly 56 and up
- Activity Stream Build: 1.15.0-dev-1501872077-54a5392

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have Nightly 56 and create a new profile with updates disabled.
- Install latest Activity Stream Dev from GitHub.
- Update Nightly to latest version (Nightly 57) .

**[Steps to reproduce]:**
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Open a New Tab.
3. Open a New Window.
4. Go to `about:preferences` and observe the Home page.
 
**[Expected results]:**
- A-S Home page resource is removed when switching to the Nightly system add-on. 

**[Actual results]:**
- In Nightly 57 the Activity Stream Dev add-on from GitHub is not working. It is installed but when opening a New Tab the Activity Stream from the system add-on is displayed. In `about:preferences` page, the Home page has the old Activity Stream resource and when opening a new tab a blank page is displayed. 

**[Notes]**:
- When switching to the A-S system add-on, the resource from about:preferences should be deleted. This can create confusion between the users.
- A-S has graduated from Test Pilot but there are still users on Nightly 56 that are using the A-S Dev branch and when they will update to Nightly 57 they will encounter this issue. If the resource remains in `about:preferences -> Home page` then it should work  
- [Here](https://drive.google.com/open?id=0B6QogV2AJFKiYW5fNVlGZHVmRkk) is a screen recording of the issue.

**Comment by Mardak** [comment]
We'll do #3112 instead to migrate users away from test pilot version.
