### ISSUE TITLE
Break down issues for remaining 57 required features

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3114]
We want to break down the OKR before the next triage:
https://github.com/mozilla/activity-stream-okrs/projects/4

1.0 Release Activity Stream
- performance
- engagement and retention
- Fx 57
- feature parity 
- feature completeness (parity w/ Test Pilot add-on)
- about:home
1.1 Metadata
1.2 Tippytop
1.3 Customization UI
1.4 Perf Measurement and Optimization
1.5 Highlights
1.6 about:home
1.7 Perceptual Perf Optimization
1.8 Telemetry, Dashboarding, Alerts

**Comment by Mardak** [comment]
feature completeness includes highlights section

**Comment by Mardak** [comment]
string considerations: at least the highlights header. maybe something only used by about:home. edit top sites should have all strings already localized for test pilot

**Comment by Mardak** [comment]
Also clean up the project to have "theme" or "feature" as the column instead of milestone:
https://github.com/mozilla/activity-stream/projects/11

**Comment by rlr** [comment]
I've filed a bunch issues related to Top Sites customization (they fall in feature parity and/or feature completeness buckets):

#3130 Port the Edit Top Sites modal to system-addon
#3132 Port the Show More/Less (2 rows vs 1 row) pref for topsites
#3133 Port the Top Sites pin and dismiss button (edit mode)
#3134 Port the Add Top Site feature
#3136 Port the Edit Top Site feature
#3137 Top Sites drag and drop

**Comment by Mardak** [comment]
Thanks. I created a new project "Release Activity Stream in Firefox 57" and moved all those under "Customization UI"
https://github.com/mozilla/activity-stream/projects/16

**Comment by Mardak** [comment]
I created 15 columns in the project  https://github.com/mozilla/activity-stream/projects/16
Currently there's 89 Fx57 issues that are m-c changes https://github.com/mozilla/activity-stream/labels/Fx57
And 11 MVP issues that are non-m-c https://github.com/mozilla/activity-stream/labels/MVP

Total of 100 issues open right now that need to be done before Beta 57 merge / code freeze September 20th

Just 2 issues right now that need strings, so maybe we can enforce our own string freeze relatively soon https://github.com/mozilla/activity-stream/labels/Strings

@jennchaulk
