### ISSUE TITLE
Improve first run / import / update experience by having screenshots ready

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3115]
During some user studies, many users had a poor experience seeing "big letters" for a long time because there were no screenshots. Some of this might be fixed by #3100 and #3101 and other fixes to make sure screenshots get created.

This issue is more to preload screenshots to be ready for the first new tab.

This might actually be (partially?) fixed by #3088 where it happens to call `refresh` closer to `INIT` than waiting for `NEW_TAB_LOAD`

**Comment by sarracini** [comment]
blocked on getting metadata

**Comment by Mardak** [comment]
This does seem to be fixed by @rlr's change in #3088. If I create a delete the profile and run
```
./mach run --setpref browser.newtabpage.pinned='[{"url":"https://www.mozilla.org/?1"},{"url":"https://www.mozilla.org/?2"},{"url":"https://www.mozilla.org/?3"},{"url":"https://www.mozilla.org/?4"},{"url":"https://www.mozilla.org/?5"},{"url":"https://www.mozilla.org/?6"}]'
```

Waiting a minute or so before opening a new tab shows a screenshot for each of those pinned sites:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/438537/29582423-7f108288-8731-11e7-97bb-752b5b90dc43.png">

**Comment by rlr** [comment]
\o/ 💃

**Comment by Mardak** [comment]
I suppose just to additionally confirm, if I..

```
$ git revert 835317a0
    Revert "fix(topsites): Refresh TopSitesFeed when TippyTopProvider init is complete (#3088)"
    This reverts commit 835317a06aa1f0f91822339319ac9c06e9be2f98.
```

I get this after waiting a minute before opening new tab:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/438537/29582836-04ae88f8-8733-11e7-9164-34d0a05d0f92.png">
