### ISSUE TITLE
Pocket stories should respect "extensions.pocket.enabled"

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/activity-stream#3116]
Nightly 57, Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0, build ID 20170808114032

STR:
1) Open about:config.
2) Change `browser.newtabpage.activity-stream.feeds.section.topstories.options` to unhide Pocket stories.
3) Change `extensions.pocket.enabled` to `false`.
4) Open activity stream new tab.
5) The pocket stories are still there.

I would expect the new tab to respect the preference too.

**Comment by sarracini** [comment]
Thanks for your feedback! The product team has decided that these two are pretty independent of one another. We're still working on a way to best integrate Pocket with Activity Stream. Let's close this for now, and we can re-open if the product team decides to tie these two features together in the future
