### ISSUE TITLE
Show the Firefox (or Nightly) favicon

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3123]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1389587

Currently (in Nightly) New Tab has no favicon. We should be showing the Firefox favicon.

Ignore the logo in the top left. Focus on the favicon in the tab.
![image](https://user-images.githubusercontent.com/438537/29196132-604c1acc-7de7-11e7-8452-55b899e9bddf.png)

https://mozilla.invisionapp.com/share/UWCKPZTBY#/243608608_New_Tab_-_All
https://trello.com/c/hRhvmlYN/149-include-firefox-logo-in-new-tab

**Comment by Mardak** [comment]
The trello card says if only search is shown, a large logo should be shown above search. @aaronrbenson are we doing that?

**Comment by aaronrbenson** [comment]
No

**Comment by aaronrbenson** [comment]
This is mostly about the favicon on the tab. Showing the FF logo in-content should be handled separately (and probably by onboarding?). The reason for showing the Firefox logo is to give more opportunities for Firefox branding. We considered using a "home" icon but that's not entirely accurate since you can set a different homepage in Firefox prefs.

**Comment by Mardak** [comment]
Verified fixed? ;)

<img width="453" alt="image" src="https://user-images.githubusercontent.com/438537/29243395-e357bc20-7f52-11e7-8af0-9f1365db732e.png">
