### ISSUE TITLE
Bookmarking a link via Activity Stream context menu should give feedback

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3126]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1388863

**Comment by sarracini** [comment]
note to self: we'll need to backport some stuff here

**Comment by sarracini** [comment]
pushed by: https://hg.mozilla.org/integration/autoland/rev/44b5074b9c65 

once this lands in m-c we can backport changes from #3154

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/44b5074b9c65
