### ISSUE TITLE
Pocket story bookmark status is not persisted in context menu

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3131]
STR:
1 .Open nightly (ensure Pocket is showing some recommended stories)
2. Bookmark a card via the context menu
3. Open the context menu of that same card and observe that it now says "Remove Bookmark". Open Bookmarks panel and confirm bookmark has been added
4. Quit nightly
5. Open nightly and open the context menu of the card you previously bookmarked

Expected results:
The context menu says "Remove Bookmark" and it should not allow you to bookmark the same card again

Actual results:
The context menu says "Bookmark" and gives you the option to bookmark the same site again. Actually clicking the context menu option to bookmark the card actually puts a new entry in the bookmarks library, so now you have duplicate bookmarks.

**Comment by piatra** [comment]
I've looked into this and what happens is that the story feed is subscribed to bookmark events through the `Sections` reducer `case at.PLACES_BOOKMARK_ADDED:`. When you bookmark a story it will update the state of the story (isBookmarked = true), but the information is lost on restart.
I don't think we have any mechanism to persist that. My proposed solution is to use the urls and `executePlacesQuery` to fetch bookmarkGuids from PlacesProvider, if they exist. Whatever we use as `guid` for the top stories now is not actually a valid guid (it's just the story id) for querying using `getBookmark` from `NewTabUtils`.

**Comment by Mardak** [comment]
As noted in https://github.com/mozilla/activity-stream/pull/3381#issuecomment-328110448
> Design says reflecting "bookmarked" for pocket stories makes sense. And the behavior is that top stories show "Bookmarked" immediately without moving. On refresh, that card no longer shows up in Top Stories and appears in Highlights (with image and description and Bookmarked).

**Comment by piatra** [comment]
@Mardak right now the query for fetching recent bookmarks is [filtering out](https://searchfox.org/mozilla-central/rev/00fa5dacedb925022f53d025121f1a919508e7ce/toolkit/modules/NewTabUtils.jsm#866) bookmarks with no visits. Do we want to remove this constrain?

**Comment by Mardak** [comment]
Ahhh.. doh. Well the query explicitly looks for visited pages. I think we'll need to do what you ended up doing for the test pilot version of filtering out `min(profile creation date + buffer, 5 day recent)`

Not sure if it'll be any better to use `await new (resource://gre/modules/ProfileAge.jsm).created` vs doing a places query…

**Comment by Mardak** [comment]
I had to revert this for very odd test failures. See https://bugzilla.mozilla.org/show_bug.cgi?id=1405539#c8

win64 debug test_chrome_ext_downloads_saveAs.html
linux/64 debug browser_webpagePerformanceAlerts.js

**Comment by Mardak** [comment]
Just documenting some findings from @piatra:

Removing the profile age file loading from #3623 seems to avoid the test failures, so we'll have a new PR that has that removed so that the other issues can be resolved: #3573 #3629 #3587 while we investigate how to avoid the test failures for this issue.

**Comment by piatra** [comment]
Pull request here: https://github.com/mozilla/activity-stream/pull/3675
