### ISSUE TITLE
Port the Show More/Less (2 rows vs 1 row) pref for topsites

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3132]
The default will be 1 row.

We need to add the pref and use it to truncate Top Sites to 6 or 12 depending on the value.

There are two places in the UI where the pref can be toggled.

1) From the Top Sites edit modal (Show More/Less button):

<img width="857" alt="screen shot 2017-08-10 at 10 38 06 am" src="https://user-images.githubusercontent.com/36629/29176124-f5a11a20-7db8-11e7-9648-8ae1cdf430a8.png">

2) From the customization sidebar:

<img width="345" alt="screen shot 2017-08-10 at 10 44 35 am" src="https://user-images.githubusercontent.com/36629/29176134-fbde52b8-7db8-11e7-988a-f542f46a2313.png">

**Comment by Mathnerd314** [comment]
I think #2592 is relevant here; ideally it would replace that two with a textbox, "show _N_ rows", but I guess there's internationalization issues with that so it probably won't happen. But the underlying pref should actually store a 6 or a 12, not just a boolean.
