### ISSUE TITLE
Top Sites drag and drop

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3137]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1402192
A user should be able to drag and drop their Top Sites to reorder them. The dropped site gets pinned in the new location causing sort of reflow of the rest of the sites.

This was mostly implemented in the Test Pilot addon but it was missing some UX. When dragging a site over a new slot, a preview of the new ordering of all the Top Sites should appear without the user having to drop on the slot and see the result.

Also, drag and drop was only available when in edit mode. We want to always allow drag and drop (I think?).

**Comment by ernstki** [comment]
For the benefit of anyone who found themselves here trying to find a way to reorder the tiles on the "new" New Tab page, there's a solution [here, in the Mozilla support forum](https://support.mozilla.org/en-US/questions/1178312#answer-1030416).

Basically, toggle `browser.newtabpage.activity-stream.enabled` to **false**, rearrange the tiles, then toggle back to **true**.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1402192
