### ISSUE TITLE
Use mapping from user events to browsers to set load info

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3138]
Split from #3118 that was worked around by #3128. @dmose and I discussed with mconley about having `BrowserOpenTab@browser.js` notify with a `Promise` that resolves with the browser that is used to open the about:newtab page.

**Comment by Mardak** [comment]
The other load trigger types are #2685. The fix here could help clean up the implementation.

**Comment by dmose** [comment]
Once this lands in m-c, we need to check our Nightly data and see if there  the various high-percentile outliers in our performance dashboards go away.  If they don't there's more investigation to do, as one possible cause might be https://bugzilla.mozilla.org/show_bug.cgi?id=1413352

**Comment by tspurway** [comment]
See also: https://github.com/mozilla/ping-centre/issues/124

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1425494
