### ISSUE TITLE
Fewer than 12 top sites shown when there should be 12

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3141]
Maria says there should be more top sites when I asked if without pinned sites there would be fewer than 12.

<img width="940" alt="screen shot 2017-08-10 at 9 17 45 am" src="https://user-images.githubusercontent.com/438537/29186528-a3d7e10c-7dc1-11e7-92d1-64cfe7add694.png">

**Comment by Mardak** [comment]
Can reproduce by setting `browser.newtabpage.pinned;[null,null,null,null,null,null,null,null,null,null,null,{"url":"https://www.youtube.com/","title":"youtube"},{"url":"https://twitter.com/","title":"twitter"}]`

Where twitter is the 13th pinned item.
![screen shot 2017-08-10 at 12 20 38 pm](https://user-images.githubusercontent.com/438537/29188083-d194acf6-7dc6-11e7-9ba3-7beb1fee9ef4.png)

**Comment by piatra** [comment]
Sorry could you please explain a bit more about what is the desired behavior here? @Mardak

**Comment by Mardak** [comment]
It should probably show 12 top sites where currently it looks like it's picking out 12 top sites but then truncates and the 12th position is a hole in the array. Probably just filter out holes before truncating?

**Comment by Mardak** [comment]
Maybe might be a related fix with #3220 where maybe we should have more than 12 available in case of holes or blocking ?

**Comment by Mardak** [comment]
Noted in #3358, maybe an alternative to filtering out holes is to only look at the first `topSitesCount` pinned sites (including holes) as the ones that can't be seen probably shouldn't affect deduping of the ones that could be seen.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1422867
