### ISSUE TITLE
Record in perf object if the browser started preloaded

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3144]
Split from #3118. We can provide some additional insight by remembering whether a browser started as a preloaded browser. This can be detected on handling `RemotePage:Init`:

This piece of code for `ActivityStreamMessageChannel` seems to detect preloaded-ness:
```diff
   onNewTabInit(msg) {
-    this.onActionFromContent({type: at.NEW_TAB_INIT}, msg.target.portID);
+    this.onActionFromContent({
+      type: at.NEW_TAB_INIT,
+      preloaded: msg.target.browser === msg.target.browser.ownerGlobal.gBrowser._preloadedBrowser
+    }, msg.target.portID);
   }
```

Without this, we can mostly infer when a page is preloaded by checking the `topsites_first_painted_ts` being before `visibility_event_rcvd_ts` but in the slight case of a preloaded browser started and soon became visible before painting, that could be confused with the case where a non-preloaded about:newtab is opened.

**Comment by dmose** [comment]
https://github.com/mozilla/activity-stream/pull/2660/files#diff-f9d20d6688eef2754298456e5d5b836bR261 is the straw-man schema.

**Comment by Mardak** [comment]
Would be needed for #2839.

**Comment by dmose** [comment]
@Mardak while that's true if we want to capture the "starts preloaded & then is made visible mid-load case", for now, I'd suspect that the visibility > topsites_first_painted_ts would be a good-enough heuristic.  What do you think?  CC /@emtwo
