### ISSUE TITLE
Snippets needs a section in prefs panel so that snippets can be turned off completely

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3146]
As seen here: https://mozilla.invisionapp.com/share/4CCZSU2BU#/248174509_New_Tab_Prefs

<img width="359" alt="image" src="https://user-images.githubusercontent.com/438537/29232638-8c81ce60-7ea1-11e7-97bb-1dfb0a70d1e5.png">

Adds a `<hr />` above the Snippets pref. Also turns off onboarding snippets.

Strings:
- settings_pane_snippets_header=Snippets
- settings_pane_snippets_body=Read short and sweet updates from Mozilla about Firefox, internet culture, and the occasional random meme.

**Comment by Mardak** [comment]
The string seems to be:

"Snippets"
"Snippets are small messages that Mozilla uses to delight and inform."

**Comment by tspurway** [comment]
@aaronrbenson I really think we need this to turn off Onboarding "snippets" as well.  We can still give access to onboarding from the top-left Firefox icon, but we need to turn off the snippet if the user chooses to turn off the snippet.

**Comment by aaronrbenson** [comment]
I'm hesitant only because it's not clear to users what a snippet is and they could 'accidentally' shut down onboarding messages. The onboarding tour will have a clear call-to-action button to "Skip Tour" which effectively turns off those messages. Thoughts?

**Comment by Mardak** [comment]
I would assume if we have a pref for user to toggle, it would be something like "Tips from Mozilla" as opposed to "Snippets"

**Comment by Mardak** [comment]
Design says the strings are good. Behavior is to also turn off onboarding snippets.
