### ISSUE TITLE
Add section called "Highlights"

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3147]
Fill as many cards on Highlights with visited bookmarks up to 5 days old: "Bookmarked"
Fill the rest with most recent history item (can be bookmarked): "Visited"
Looks like the total is 9 cards with no timestamp but "Bookmarked" or "Visited" with matching icon. If a card's url is actually bookmarked, its context menu should have "Remove Bookmark".
None of the highlights should exactly match the url of a recently bookmarked or recently visited top site. But pages/articles visited from the top site should appear as Highlights.
The prefs from #3155 section allows for turning off of bookmarks and/or history.

![image](https://user-images.githubusercontent.com/438537/29196173-98a97888-7de7-11e7-81bd-4d7695c8607a.png)

https://trello.com/c/kijapFZ2/156-i-want-to-see-a-highlights-section-on-new-tab

Strings:
- header_highlights=Highlights
- highlights_empty_state=Start browsing, and we’ll show some of the great articles, videos, and other pages you’ve recently visited or bookmarked here.

https://mozilla.invisionapp.com/share/FUD0ADOYE#/screens/248319677_NewTab_-_Empty_States

**Comment by sarracini** [comment]
Blocked on metadata

**Comment by Mardak** [comment]
"This should work the same way as Pocket" so use section manager and reuse telemetry provided by section manager.

**Comment by Mardak** [comment]
Bookmarks should be always be shown even without metadata "because it’s a bookmark it’s more likely to feel familiar even if it’s missing thumbnails." Whereas a history page should only be shown if there's an image

**Comment by Mardak** [comment]
Updated initial comment to note some additional behaviors from UX:
- old bookmarks can appear as "Visited" but context menu will show "Remove Bookmark"
- top site urls should not appear in Highlights (but their pages/articles should appear)
