### ISSUE TITLE
Update Tippy Top with scraped icons

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3149]
When tippy top has allowed icons, we'll want to use those

**Comment by tspurway** [comment]
@bryanbell  We need to take another pass at the Tippytop icons for default Top Sites.  We need to make two changes:

1) use hi-res icons where available.  Let's figure out which sites actually have decent icons (from the list of default top sites) and use them where available

2) when we have to use screenshots, let's make sure that the favicon for that site is also put in the top-left hand corner of the screenshot icon
