### ISSUE TITLE
Add section in prefs to turn off parts of Highlights

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3155]
At minimum the whole section can be turned off but the full feature is to be able to individually turn off bookmarks and visited sites.

https://mozilla.invisionapp.com/share/4CCZSU2BU#/screens/248174509_New_Tab_Prefs

<img width="357" alt="image" src="https://user-images.githubusercontent.com/438537/29232281-b1370696-7e9f-11e7-90f4-b4c30b8c38eb.png">

Pref pane behavior:
- If the user unchecks both Bookmarks and Visited Sites, the Highlights section is also unchecked.
- If Highlights section is unchecked, the sub option box is disabled at 50% opacity not allowing clicks but maintains whatever the user has checked for Bookmarks and Visited Sites.
- If all sub options are unchecked and the user is turning on Highlights section, all options are now checked.

Highlight section behavior (from https://github.com/mozilla/activity-stream/issues/3378#issuecomment-327960680):
- If the user is excluding Bookmarks, all items should appear as Visited but context menu allows removing a bookmarked page. They keep the Visited type even when bookmarked and without shifting around cards, but the context menu will update to allow Remove Bookmark.
- If the user is excluding Visited Sites, only bookmarks should appear, and these show Bookmarked. If the user then Remove Bookmark from context menu, that card is dismissed immediately.

Strings:
- settings_pane_highlights_header=Highlights
- settings_pane_highlights_body2=Find your way back to interesting things you’ve recently visited or bookmarked.
- settings_pane_highlights_options_bookmarks=Bookmarks
- settings_pane_highlights_options_visited=Visited Sites

**Comment by Mardak** [comment]
The strings for the pref pane were removed when the Highlights header was removed.

**Comment by sarracini** [comment]
Blocked on actually implementing highlights

**Comment by Mardak** [comment]
Added a note that there's more complex behavior of excluding bookmarks or excluding history https://github.com/mozilla/activity-stream/issues/3378#issuecomment-327960680

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432595
