### ISSUE TITLE
Pocket privacy notice feature [placeholder]

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3168]
Adding this for the benefit of triage. The scope of work is still unknown until we get go-ahead from Product/Pocket/Legal. 

At this point it could be as small as a copy change to the "?" in the Pocket Stories section or as big as message displayed over the entire section after a delayed hover that indicates intent to click on a story.

**Comment by tspurway** [comment]
Also note that this work includes:
- lazily create a pref containing a unique ID (GUID) 
- pass this along with the Pocket ping-centre 'click' ping as 'pocket_id'

**Comment by Mardak** [comment]
The switch from "send feedback" to "privacy notice" happened with #3265.

**Comment by csadilek** [comment]
This was covered in #3770 and can be closed now.
