### ISSUE TITLE
Event handlers in Sections.jsx are causing too many re-renders

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3180]
Due to a major bug we found (multiple renders being caused by `setState` being called on `mouseMove` events) we need to back out this commit and uplift.

**Comment by k88hudson** [comment]
Ok, so I did some investigation and it looks like `onInfoLeave` and `onInfoEnter` are being triggered continuously in succession as the mouse moves over the element, so unfortunately just setting a conditional isn't going to work – we'll have to do some more investigation tomorrow to see what is causing these events to fire unexpectedly

**Comment by Mardak** [comment]
Which element are you moving over? I see many events as you move the mouse over `info-option` but it's always setting a truthy value. And the events are only happening when the cursor is over the `section-info-option` `icon`/`span` and the child `div`.
