### ISSUE TITLE
Refactor edit mode to avoid rendering Top Sites twice

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3189]
Right now when in edit mode, there is a set of Top Sites rendered under the modal overlay which are part of the normal page and an extra set of the same Top Sites rendered inside of the modal.

From @sarracini (https://github.com/mozilla/activity-stream/pull/3182#discussion_r133554617):
> This is out of scope for this ticket, but maybe we can file a follow up ticket to factor our the modal and some of the edit logic into it's own component so the top sites component doesn't get too gnarly. It would be nice if we only had one set of top sites being rendered at a time, and they could either be in edit mode or not, rather than rendering the default top sites and then rendering the editable top sites on top. Can you file a ticket for that?

**Comment by Mardak** [comment]
This was fixed in #3951
