### ISSUE TITLE
Abnormally high CPU usage under e10s

### ISSUE THREAD

**Issue by professionaltart** [mozilla/activity-stream#3190]
System: Win10, Firefox 55.0.2 64-bit, release branch

Upgraded from v54 today.  Manually disabled extensions incompatible with multiprocess to enable e10s.
With Activity Stream enabled, Firefox regularly sits at 40%+ CPU usage, often high enough to boost to ~4.2GHz (i4-4690k)

Restart with all extensions disabled, no issue.  Manually re-enable one at a time, and a small spike from AS.  Restarted browser, then AS resumed unacceptably high CPU usage again.  Disable AS, CPU usage dives.

Unsure if reproducable on any other system: may be the combination of hardware I am on, detritus in user profile, or the fact I have over 100 tabs open (~10 loaded into memory and active).

Tried enabling AS as the first extension to confirm it wasn't interacting poorly with other extensions.  Made no difference, CPU spiked hard.

Tried variations of how many processes e10s allowed, from 1 through 7: no difference (16GB RAM)

**Comment by k88hudson** [comment]
Is the version of Activity Stream available as an add-on through Test Pilot? If so, this is a known issue and will be resolved in the built-in version of Activity Stream shipping with Firefox. You can preview it right now in Firefox Nightly or Beta 56 by enabling the `browser.newtabpage.activity-stream.enabled` in about:config. Thanks for reporting!

**Comment by professionaltart** [comment]
Ah, yep, it's the one that came with test pilot a while back.  Thanks!
