### ISSUE TITLE
Sections should have an order

### ISSUE THREAD

**Issue by AdamHillier** [mozilla/activity-stream#3194]
Allow users to be able to reorder sections instead of whatever they're registered in by code. In particular, it would be nice to reorder web extensions where they might by default be at the top but not necessarily especially with multiple extensions.

**Comment by Mardak** [comment]
Adam will keep working on this separate from the 57 work.

**Comment by sarracini** [comment]
This is done!!!!

**Comment by Mardak** [comment]
Fixed in #4022.
