### ISSUE TITLE
preload newtab on addon startup

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-stream#320]
We want to preload the newtab page on addon startup to diminish the DOM population latency.

That will shave ~100ms on my computer for the first load.

This bug is the final part of #274 and will close it

**Comment by rlr** [comment]
Preload it where? How does this work? The preloaded DOM would be invalid as soon as the user visits a new page. Or I probably just don't get what/how you would do this.

**Comment by oyiptong** [comment]
It would work the same way our local page summarizer would work:

We create a hidden DOM window, create a document inside and load the page.
In the case of our own page, we can load the document as we would a regular tab.

Later, in the case of web pages we want summaries of, we'll need to load with a lot of things turned off.
You'll find some examples for the newtab page preloader and for the page thumbnailer:

* https://dxr.mozilla.org/mozilla-central/source/browser/base/content/tabbrowser.xml#1705
* https://dxr.mozilla.org/mozilla-central/source/toolkit/components/thumbnails/BackgroundPageThumbs.jsm#167

**Comment by rlr** [comment]
ah. neat :+1:

**Comment by sarracini** [comment]
Closing this in favour of the new caching mechanisms in place for AS
