### ISSUE TITLE
Bump version on export to either mc or a standalone XPI for better telemetry/diagnotics

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#3202]
We haven't set the version yet, and currently all the telemetry pings have `addon_version: '0.0.0'`. This field will be useful for the telemetry analysis to track different releases as well as different user groups.

**Comment by emtwo** [comment]
This came up because I was unable to identify whether users had updated with the telemetry hero element paint bug fixes.

**Comment by Mardak** [comment]
Is there a firefox/nightly version and is that usable? I believe there's some fuzzy useragent versioning to not actually expose daily build numbers.. ?

**Comment by ncloudioj** [comment]
We do have Firefox version available, but, unfortunately, the underlying ua parsing library doesn't parse out minor version of Firefox.

**Comment by emtwo** [comment]
This likely needs a separate issue (I'll file now), but I think we don't collect the firefox channel either? Can't tell between whether a ping came from 56 nightly or 56 beta...

**Comment by ncloudioj** [comment]
@emtwo No, we are not collecting channel info either. Go ahead file a bug for it plz.

**Comment by dmose** [comment]
OK, after discussion with @Mardak and @ncloudioj, and a bit more pondering, the current theory is to have buildmc replace the 0.0.0 in install.rdf.in with a string that looks like:
`YYMMDD.minute-of-the-day.git-hash`, eg `20170824.57643.11abcdef`.

This use of minute of the day will allow us to someday have an add-on built every time there is a merge, and we'll still end up with strictly ascending version numbers (which is important for use by telemetry to discard old results), assuming we don't build more frequently than once per minute, and modulo builds happening on different branches, which will likely require some more thought.

I will say that I'm somewhat tempted to put dots in between YYYY.MM.DD for readability.  It would give us a five-part version number, but it's not clear to me that that's a problem.

**Comment by dmose** [comment]
The nice thing about using it as the version string in install.rdf.in is that it will be visible in Firefox about:support, as well as in telemetry pings.

**Comment by dmose** [comment]
@Mardak pointed out that nsIVersionComparator only wants 4 part version numbers.  So I'll leave the dots out.

**Comment by dmose** [comment]
After more discussion with Mardak, what would appear to be the most human-readable version looks like this:

2017.08.24.1234-deadbeef
