### ISSUE TITLE
Send Firefox channel with telemetry ping

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#3205]
We need to know, for example, whether a user is on Firefox 56 beta or nightly.  Right now we cannot tell how big our actual beta population is which is important for the upcoming shield study

**Comment by ncloudioj** [comment]
Okay, we can add "app.update.channel" to the payload. Did you want to add this field to all the pings? @emtwo

**Comment by emtwo** [comment]
@ncloudioj yes to all pings. Thanks!

**Comment by emtwo** [comment]
Complete:
https://github.com/mozilla/activity-stream/commit/11c5de58aefe25c40dbd2491e000a2bae2a9a15b
