### ISSUE TITLE
visualize ongoing time-to-interactive data

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3217]
User Story: 

> As someone working on activity-stream, I see a dashboard showing how long it took for time-to-interactive (by percentile?), so that I can get a sense of existent delay for the majority of users, and notice if something has changed over time.

Good definitions of time-to-interactive are very much [still evolving](https://docs.google.com/document/d/1GGiI9-7KeY3TPqS3YT271upUVimo-XiL5mwWorDUD4c/preview#).  For the medium term, we'll want to look at switching to [Google's TTI polyfill](https://github.com/GoogleChrome/tti-polyfill), or [Firefox's implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1299118), both of which can't happen until various platform work gets done.

In the meantime, after reviewing [Nic Jansma's `Reliably Measuring Responsiveness` slides](https://www.slideshare.net/nicjansma/reliably-measuring-responsiveness/31), discussing with @k88hudson, and looking at the code, it seems like the simple thing that's practical to implement is the timestamp at the beginning of the first 500ms block after the Hero element paints where "Page Busy" is less than 10%.  This misses a bunch of a stuff (eg long tasks), but it's what seems most practical.  More details about how we'll calculate this in the implementation bug (#3219).

@digitarald, @emtwo would love any thoughts you guys have one this...

**Comment by dmose** [comment]
After doing some prototyping, it's looking much less clear that this metric is going to be useful to us at all, at least at the current time.  See https://github.com/mozilla/activity-stream/issues/3219#issuecomment-324706886 for details...

**Comment by Mardak** [comment]
Going to measure with video
