### ISSUE TITLE
Host Tippy Top in S3 - fetch it periodically from AS

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#3218]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1386767
To allow 'off-train' improvements to our site summary metadata, let's host a static Tippy Top with scraped data on S3 and fetch this once-a-day in the system addon.  Note that we have a similar fetch in current Tiles implementation for default tiles.

**Comment by sarracini** [comment]
Fixed with #3787

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/6ff9a23d3212
