### ISSUE TITLE
report TTI data telemetry for page loads

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3219]
This is the client-side reporting implementation bug for #3217; be sure to review the context and links there to help understand what we need to do.

Once the hero element paints (which is when we're visually ready), we want to start an interval timer that fires every 50ms or so to collect CPU page busy data.   We want to find the first ~500ms timestamp where cpu page busy is < 10% the whole time.

This means essentially implementing the stuff [here](https://github.com/nicjansma/talks/blob/master/measuring-continuity/examples/cpu-page-busy.js).

A variant with more context: https://github.com/nicjansma/talks/blob/master/measuring-continuity/perf-timeline.js#L280

However, we'll want to account for visibility changes which can throttle timer callbacks as well.

**Comment by dmose** [comment]
Note that the code linked to above is MIT-licensed, so we can fork and reuse if desired, though I'm not sure whether it's worth it.

**Comment by dmose** [comment]
Worth noting, possibly even in the dashboard itself is that we're using visually ready of after the hero element has painted, but for the non-preloaded case, it's likely that it will just have big letters displayed for each site rather than screenshots.

**Comment by dmose** [comment]
So doing some cut-n-paste prototyping with the above code turns out to give substantially less useful information than one might expect.  On a macbook air, one sees bunches of numbers over 10% right after the load.  However, the page is completely easy to interact with during that time.  This is probably in part because the primary interaction we're expecting is just "clicking a link" and doesn't likely really require much JavaScript to run.   

I could imagine a more sophisticated algorithm that doesn't just count late callbacks, but actually accumulates how late they were to compute a perhaps-more-accurate count.  

I've fooled around with it on the reference machine some, and I'll do some more of that tomorrow.  
If I'm able to actually reproduce the case where there is interaction lag when clicking immediately after I see the hero element on a loaded ref machine, maybe there will be something useful to measure here.  Otherwise, I think we should just close this.

**Comment by digitarald** [comment]
+1 on that finding. TTI is interesting for JS-driven interactions, but only if those are core interactions on the critical path. As the search and links on top sites are the core interactions; TTI is not meaningful here.

**Comment by Mardak** [comment]
Going to measure with video
