### ISSUE TITLE
Dismissing a Top Site will permanently reduce the number of Top Sites displayed

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#3220]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/25276/29631518-e1a64d74-880d-11e7-842f-64a09210c76e.png">

- select 'Dismiss' from (...) menu on a Top Site
- you get one less Top Site

**Comment by tspurway** [comment]
restarting Firefox 'fixes' this situation

**Comment by piatra** [comment]
It's permanent due to the 15 minute timeout in the feed.
