### ISSUE TITLE
IDN/non-punycode eTLD are shown

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3221]
Regressed by #3215. For `https://xn--c1asce.xn--90a3ac/` now shows "гном.срб" but should probably show "гном" given that we strip off eTLD elsewhere.

After:
![screen shot 2017-08-23 at 11 31 14 am](https://user-images.githubusercontent.com/438537/29632311-7c47ed22-87f7-11e7-8ffa-ea4e48b21de3.png)

Before:
<img width="132" alt="image" src="https://user-images.githubusercontent.com/438537/29489588-719d930c-84d9-11e7-9faa-11c6569efb88.png">

@piatra

**Comment by mkaply** [comment]
Can we really handle every IDN top level domain? is срб a common TLD?

**Comment by Mardak** [comment]
It was correctly handled (punycode version) before:
```js
Services.eTLD.getPublicSuffixFromHost("xn--c1asce.xn--90a3ac")
"xn--90a3ac"
```

**Comment by mkaply** [comment]
Mardak: You are 100% correct. Should have looked at the TLD list. That's quite a list when you include IDN.

**Comment by piatra** [comment]
On that note
<img width="257" alt="image" src="https://user-images.githubusercontent.com/810040/29659934-1470ffbc-88c0-11e7-8930-0dc9041b49f8.png">

**Comment by pdehaan** [comment]
I'm confused. I'm using today's Nightly build, but it isn't showing my domain name:

<img width="783" alt="nightly" src="https://user-images.githubusercontent.com/557895/29681297-208da236-88bc-11e7-901c-672883e6c242.png">

Note that the super-rad site in question is http://🇨🇦🍕.ws

**Comment by Mardak** [comment]
It needs to be exported to mozilla-central in https://bugzilla.mozilla.org/show_bug.cgi?id=1392384
