### ISSUE TITLE
Top stories pref never gets reparsed/updated in the Preferences Panel

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3222]
I'm not seeing Top Stories in the Preferences Panel on master right now, however the section is showing up. Bug?

**Comment by Mardak** [comment]
Do you have any custom values for either `browser.newtabpage.activity-stream.feeds.section.topstories.options` or `browser.newtabpage.activity-stream.feeds.section.topstories` ?

**Comment by k88hudson** [comment]
Ah, I found out what the issue is. On my branch I am adding an extra update for the purposes of preloading, but the `topStoriesOptions` are calculated only once in the constructor (which results in updates never getting processed).

For now this isn't an issue, but it could (will) cause bugs in the future, so we should fix this.

**Comment by csadilek** [comment]
This is fixed now with the latest enhancements to SectionManger.

**Comment by Mardak** [comment]
Which change/PR?

**Comment by csadilek** [comment]
It was fixed as part of this PR: https://github.com/mozilla/activity-stream/pull/3216
