### ISSUE TITLE
Use page title instead of domain for top sites

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3223]
Noted from https://bugzilla.mozilla.org/show_bug.cgi?id=1391667

> Honestly, we should be using titles. Top level domains are too diverse to try to standardize these for new tab.
> A very simple example is the fact that yahoo.co.jp and yahoo.com are both presented as yahoo on the new tab (if you manage to get them both on there). Or Firefox chooses which one is more important and only shows one. But the other problem is it assumes that domain names are always a good representation of a site.
> http://speedofart.com/ would much rather you use the title :)
> I also think it is a very US centric view of the world. Domain names have been traditionally English (before IDN), even when titles and content are in other languages.

**Comment by Mardak** [comment]
Design says not for 57. There might be better ways than domain but just using the title is not good, e.g., mozilla.org would show

<img width="134" alt="image" src="https://user-images.githubusercontent.com/438537/29727249-ed1e7d86-8987-11e7-9eef-27654202419b.png">

**Comment by Mardak** [comment]
From nchapman:
> all solutions are kind of terrible, but i’m pretty sure we can do better than what we have now
> i would imagine it’s a post 57 thing
> i believe that readability has code in it to try to handle this problem. could be some good inspiration.
> https://github.com/mozilla/readability/blob/master/Readability.js#L308

**Comment by mkaply** [comment]
> Design says not for 57. There might be better ways than domain but just using the title is not good, e.g., mozilla.org would show

That's a bad design of the Mozilla website. It looks bad as a tab title too. Most sites start with the name of the site to avoid that exact problem.

**Comment by bryanbell** [comment]
I blame Search Engine Optimization for all the bad titles in the world. Verbose titles that lead with what a site is about, followed by the title, is sadly very common.

**Comment by jenn-chaulk** [comment]
Note from Tim - could put the title in a tool tip?

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1433530
