### ISSUE TITLE
The "Back" button is not disabled after a search is made

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3248]
[Affected versions]:
- Firefox 57.0a1 Build ID 	20170827100428

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Write a keyword in the search bar and press enter.
3. Observe the Back button.
 
[Expected results]:
- Button is disabled.

[Actual results]:
- Button is enabled and clickable.

[Notes]:
- The issue is not reproducible on the old about:newtab.
- Attached a screen recording of the issue:
![back button enabled after a search is made](https://user-images.githubusercontent.com/18304511/29774269-95724822-8c09-11e7-9805-4aa34af0bea4.gif)

**Comment by sarracini** [comment]
Bug https://bugzilla.mozilla.org/show_bug.cgi?id=776167 has made it possible to go back to the newtab page now, so i think this is working as intended
