### ISSUE TITLE
Clicking the "Change search settings" button from search suggestions menu on a new tab wrongly refreshes the page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3249]
[Affected versions]:
- Firefox 57.0a1 Build ID 	20170827100428

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Write a keyword in the search bar and press the "Change search settings".
3. Observe the behavior.
 
[Expected results]:
- The "about:preferences#search" page is opened. 

[Actual results]:
- The page is refreshed.

[Notes]:
- The issue is reproducible only the first time you do this on a new tab.
- The issue is reproducible on each new tab you open.
- The issue is not reproducible on the old about:newtab.
- Attached a screen recording of the issue:
![page refresh after clicking the change search settings](https://user-images.githubusercontent.com/18304511/29774940-04cd90e4-8c0c-11e7-88c7-43b84cfc08f8.gif)

**Comment by Mardak** [comment]
This seems to have the same odd behavior as #3255 where the first click reloads and second click goes to preferences.
