### ISSUE TITLE
Top Sites are no longer populated after Clearing all History, until the browser is restarted

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3250]
[Affected versions]:
- Firefox 57.0a1 Build ID 	20170827100428

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Clear recent history (cmd/ctrl+shift+del) and choose to clear everything.
3. Visit a few websites and open a new tab.
4. Observe the page.
 
[Expected results]:
- The previously visited websites appear as Top Sites.

[Actual results]:
- Only the default top sites are displayed.

[Notes]:
- The issue is not reproducible on the old about:newtab.
- Attached a screen recording of the issue:
![top sites not populated after clearing history](https://user-images.githubusercontent.com/18304511/29776033-05558ec8-8c10-11e7-9d48-cb7618e5f15f.gif)

**Comment by Mardak** [comment]
This sounds like it's by design similar to a new profile experience. Have the default sites show longer until there's enough visits for this session. It should update after 15 minutes I believe.

**Comment by tspurway** [comment]
We think this is intended behaviour

**Comment by Mardak** [comment]
Design says the 15 minutes is expected. And if the user does want to add things sooner, there's the edit menu.
