### ISSUE TITLE
Clicking context menu separator wrongly dismisses the menu

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3251]
[Affected versions]:
- Firefox 57.0a1 Build ID 	20170827100428

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the "..." button for a Top Site.
3. Click the line between two options and observe the behavior.
 
[Expected results]:
- Nothing happens.

[Actual results]:
- The menu is dismissed.

[Notes]:
- The issue is not reproducible with any other context menu.
- Attached a screen recording of the issue:
![top sites context menu dismissed](https://user-images.githubusercontent.com/18304511/29776665-09b06766-8c12-11e7-9c71-89f08724f5a8.gif)

**Comment by Mardak** [comment]
For for 57

**Comment by rlr** [comment]
fixed over here -> https://github.com/mozilla/activity-stream/commit/cd2d5031f7cf6212480a6026b8418253d519b902#diff-a4808e9780f515ecae36d2b3ace17ed4R28
