### ISSUE TITLE
Disable test for Pressing any key should focus the search box in the page, and send the key to it

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3252]
```
Open about:home (with AS).
Press any key. 
Search input should be focused.
```
At least that is the expected behavior of a test in `browser_aboutHome.js`

**Comment by Mardak** [comment]
We will disable this test as #2007 will capture most of the keyboard presses. This is more of a corner case to handle focus moving away from search box and user starts typing.

P2 for reenabling and getting feature parity

**Comment by piatra** [comment]
Will be fixed as part of https://github.com/mozilla/activity-stream/issues/3302.

**Comment by Mardak** [comment]
Duping this to #3302
