### ISSUE TITLE
New Tab Preferences menu is not scrollable if the browser is resized and the menu is not fully displayed

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3256]
Mirror of bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1394409

> User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20170828100127
>
> [Prerequisites]:
> - From about:config make the following changes:
> browser.newtabpage.activity-stream.enabled = true
>
> [Steps]:
> 1. Open Nightly browser and open a new tab.
> 2. Click on the "Customize your New Tab page" setting button.
> 3. Resize the browser window so that the settings are not fully displayed.
> 4. Scroll to see all the settings available.
>
> [Expected results]:
> - When there are more settings than the ones displayed in viewport, a scroll bar is displayed for > "New Tab Preferences" menu.
>
> [Actual results]:
> - Scroll bar for settings menu is not available

**Comment by Mardak** [comment]
Probably can just add scroll bars to the pref pane

**Comment by rlr** [comment]
The test pilot one already had these. We just need to port over some styles. I'll grab

**Comment by Mardak** [comment]
This will be especially important as highlights #3155 and snippets #3146 get prefs making that pane even taller.
