### ISSUE TITLE
Experiment:  turn off all snippets and onboarding tour notifications for a % of users

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#3257]
Let's test how the snippets and onboarding notifications affect retention and engagement.  Let's make sure we have the ability to turn off snippets and onboarding behind a single pref, so that this can be flipped with a Shield study.

**Comment by Mardak** [comment]
Might need some telemetry on when snippets are actually shown

**Comment by Mardak** [comment]
Could potentially do this from the snippets server side

**Comment by Mardak** [comment]
This was recommended closed. Perhaps onboarding has done some experiments?
