### ISSUE TITLE
Make all sections collapsible

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3261]
We need to port over the `CollapsibleSection` component from test pilot addon. It probably needs some changes to handle the new custom sections.

**Comment by Mardak** [comment]
P2 as there's an alternative to completely turn off sections.

**Comment by sarracini** [comment]
This is actually a dupe of #3148

**Comment by rlr** [comment]
gah I searched for "collapsible" instead of "collapsed". github should have smarter search 😃
