### ISSUE TITLE
Port the placeholders for Top Sites, Sections

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3262]
In the test pilot addon, we would pad the Top Sites with placeholders when the user didn't have enough to fill the 1 or 2 rows. This is noticeable on fresh profiles with the top sites pref set to 2 rows:

<img width="1026" alt="screen shot 2017-08-28 at 1 48 36 pm" src="https://user-images.githubusercontent.com/36629/29786028-9f7e6c4a-8bf7-11e7-9a82-f7d56b93cd7c.png">

**Comment by Mardak** [comment]
This might be handled as part of prerendering to avoid jumping around.

**Comment by Mardak** [comment]
Fixed top sites #3323 and sections #3337.
