### ISSUE TITLE
Add API to give Snippets in Activity Stream control over when to show onboarding

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3263]
https://bugzilla.mozilla.org/show_bug.cgi?id=1393489

**Comment by k88hudson** [comment]
I have a working patch for this, just writing some tests now

**Comment by tspurway** [comment]
@k88hudson, does this have a PR?

**Comment by Mardak** [comment]
Just attached to mozreview https://bugzilla.mozilla.org/attachment.cgi?id=8907692

**Comment by Mardak** [comment]
Fixed by #3542

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/79375774e4fe
