### ISSUE TITLE
Replace "Send Feedback" link in TopStories info section with link to privacy notice

### ISSUE THREAD

**Issue by csadilek** [mozilla/activity-stream#3265]
If we can't get an alternative link and text by the end of this week, let's just remove the link altogether.

<img width="431" alt="screen shot 2017-08-28 at 2 51 00 pm" src="https://user-images.githubusercontent.com/472523/29788414-7d6000a2-8c00-11e7-9622-360b8f1285ac.png">

**Comment by Mardak** [comment]
Theres #3106 for removing the link completely.

**Comment by mariappopova** [comment]
Maria to check with Elvin and update the string

**Comment by Mardak** [comment]
For now, I've put "Privacy Policy" in the in-progress PR #3274.
