### ISSUE TITLE
Move line separators in preferences and differently style confirmation

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3273]
See https://mozilla.invisionapp.com/share/NYDAMWECB#/251367746_Preferences_Spec

Between search / top sites
<img width="353" alt="image" src="https://user-images.githubusercontent.com/438537/29804191-df695c64-8c35-11e7-8b5e-6be6c9121152.png">

and between highlights / snippets
<img width="364" alt="image" src="https://user-images.githubusercontent.com/438537/29804199-e3a647b0-8c35-11e7-8fbc-9c17be3fc796.png">

and background of "Done"
<img width="423" alt="image" src="https://user-images.githubusercontent.com/438537/29806019-c44eef1e-8c41-11e7-8801-72fd9f4a8345.png">

and lighter intro text:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/438537/29884682-09f22b76-8d69-11e7-959b-71f2140947f0.png">

**Comment by aaronrbenson** [comment]
More details for updated styles to the prefs panel: https://mozilla.invisionapp.com/share/NYDAMWECB#/251367746_Preferences_Spec

**Comment by Mardak** [comment]
@aaronrbenson is the done button area anchored to the bottom or just under the last item? And if the window is too small, what is scrolling?

**Comment by aaronrbenson** [comment]
My mistake, left that part and the spacing out! Updated the spec above.
