### ISSUE TITLE
 PERMA-FAIL | browser/base/content/test/about/browser_aboutHome_wrapsCorrectly.js | narrow mode - null == "true" 

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3277]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1395281
Browser is resized to 300x300 and then a special "narrow" attribute is checked on the document body. Do we want to support this size? @aaronrbenson @bryanbell 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/810040/29819397-ed20af48-8cc0-11e7-9b20-439682241216.png">

**Comment by tspurway** [comment]
let's disable this test

**Comment by Mardak** [comment]
Design says we already support narrow screens. @k88hudson do you know if snippets is relying on this "narrow" `body` attribute?

**Comment by Mardak** [comment]
Sounds like snippets doesn't need it, so if it's only used by snippets, we can skip the test.

**Comment by Mardak** [comment]
Looks like this test was originally added so that session restore button wrapped correctly

https://hg.mozilla.org/mozilla-central/rev/8602949a29dc

the "narrow" attribute was how they were determining when it should be styled differently. We do that directly through css.

**Comment by sarracini** [comment]
Turning AS about:home off for this test:  https://bugzilla.mozilla.org/show_bug.cgi?id=1395281

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/da46b9690d97
