### ISSUE TITLE
 PERMA-FAIL | browser/components/privatebrowsing/test/browser/browser_privatebrowsing_aboutHomeButtonAfterWindowClose.js | Uncaught exception 

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3278]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1395319

```
FAIL | browser/components/privatebrowsing/test/browser/browser_privatebrowsing_aboutHomeButtonAfterWindowClose.js | Uncaught exception
TypeError: Argument 1 of Window.getComputedStyle is not an object.
```
https://treeherder.mozilla.org/#/jobs?repo=try&revision=4e323761c128b40621ffdff46c0e92dc6463df34&group_state=expanded&selectedJob=127119664

```
let button = content.document.getElementById("restorePreviousSession");
```
Is tested to be disabled.

**Comment by piatra** [comment]
Fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1395319.

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/13c1ef2b9859
