### ISSUE TITLE
Background color should be #F9F9FA (Grey 10) including migration

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3281]
![screen shot 2017-08-29 at 10 21 15 am](https://user-images.githubusercontent.com/139451/29828973-d39e60be-8ca3-11e7-8a64-1a3373146b90.png)

**Comment by aaronrbenson** [comment]
We also need to update the drop shadows and style of the search bar to as follows:

**Search Field:**
background: #FFFFFF ;
border: 1px solid rgba(9,6,13,0.10);
box-shadow: 0 1px 4px 0 rgba(9,6,13,0.10);
border-radius: 3px;

**Top Sites:**
box-shadow: 0 1px 4px 0 rgba(9,6,13,0.10);
border-radius: 6px;

**Highlights:**
box-shadow: 0 1px 4px 0 rgba(9,6,13,0.10);
border-radius: 3px;

**Comment by Mardak** [comment]
@aaronrbenson what should the background be for various other items:

manual migration (here grey-20):
<img width="774" alt="image" src="https://user-images.githubusercontent.com/438537/29829121-717e78ac-8c93-11e7-8a8b-7b9a12c757bd.png">

link menu (here grey-20):
<img width="379" alt="image" src="https://user-images.githubusercontent.com/438537/29829134-79845648-8c93-11e7-860d-81412e88ef73.png">

confirmation/edit topsites modal (here white and gray-out grey-20 80%) :
<img width="436" alt="image" src="https://user-images.githubusercontent.com/438537/29829200-99b56d9e-8c93-11e7-8c4c-2c75cb7dcc1c.png">

prefs pane (here white) and subitem (here grey-20):
<img width="378" alt="image" src="https://user-images.githubusercontent.com/438537/29829219-a68dde66-8c93-11e7-9c9d-86971dfc97e0.png">

hovered top sites buttons (here grey-20):
<img width="70" alt="image" src="https://user-images.githubusercontent.com/438537/29829293-e00ccaee-8c93-11e7-817d-d9b4a35ce51f.png">

info option description (here white):
<img width="341" alt="image" src="https://user-images.githubusercontent.com/438537/29829478-677b7b10-8c94-11e7-8313-e40adc5ff936.png">

pocket article (here white):
<img width="249" alt="image" src="https://user-images.githubusercontent.com/438537/29829498-72b64190-8c94-11e7-9b21-825fff73865d.png">

**Comment by Mardak** [comment]
> rgba(9,6,13,0.10);

@aaronrbenson with the latest color update, we're already using the lightest gray with grey-10 at 12,12,13 (F9F9FA) 10%, so you want to make that even lighter? Should we be using a non-photon base color? Or should it be grey-10 at some lesser opacity, say 9% instead of 10%?

<img width="380" alt="image" src="https://user-images.githubusercontent.com/438537/29830091-106d09cc-8c96-11e7-8f6a-21e533431ca9.png">
left rgba(12,12,13,.09) (i.e., grey-10 9%), middle rgba(9,6,13,.1), right rgba(12,12,13,.1) (i.e., grey-10 10%)

**Comment by Mardak** [comment]
Updated Spec: https://mozilla.invisionapp.com/share/MHD92KAYR
