### ISSUE TITLE
buildmc fails in node 7

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3283]
Right now some changes that landed in https://github.com/mozilla/activity-stream/commit/828acca53137caaf1cb5cce840f441b0b5e8917c use syntax that is only available in node 8.

I think it's a bit early to require node 8 for the project just for this task? What do you think @dmose?

**Comment by pdehaan** [comment]
I'd say now is a fine time to dump Node 7.x. It isn't actively maintained, isn't an LTS branch:
https://github.com/nodejs/LTS

Node 8.x, on the other hand, is still "active", and should have LTS and maintenance support through Dec 2019.

Although, it _does_ look like Node 7 still gets backported security fixes: https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/
