### ISSUE TITLE
Use tippy-top-icons when available?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#3291]
Using the latest Nightly, I get a few screenshots for icons, which are very difficult to quickly see what the site in question is. It feels like we should use Tippy-Top-Icons whenever they are available, and fall back to screenshots when necessary.

But in the case of GitHub and Yahoo! Search, the screenshots make it very difficult to see what the site in question is at a quick glance, and makes the user experience a bit worse.

<img width="812" alt="new_tab" src="https://user-images.githubusercontent.com/557895/29846462-d7b11912-8ccb-11e7-94be-4481263a9b7b.png">

**Comment by Mardak** [comment]
dupe #3149
