### ISSUE TITLE
Unable to delete from history if a top site is pinned

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3294]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1395203
If I pin a top site and then try to delete from history via the context menu, it doesn't actually remove it from top sites

**Comment by sarracini** [comment]
Mirror of: https://bugzilla.mozilla.org/show_bug.cgi?id=1395203

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/e96f86e8071a
