### ISSUE TITLE
PERMA-FAIL | browser/base/content/test/about/browser_aboutHome.js | Test timed out 

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3302]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1396274
```1260330 - Intermittent browser_aboutHome.js | Test timed out, Found a tab after previous test timed out: about:home ```

https://treeherder.mozilla.org/#/jobs?repo=try&revision=4e323761c128b40621ffdff46c0e92dc6463df34&group_state=expanded&selectedJob=127119661

This test times out for a multitude of reasons, since it's testing stuff with snippets, search, all kinds of stuff

**Comment by tspurway** [comment]
Should this test be disabled @sarracini ?

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/3ce5a9419d5b

Split out getting tests partially running with activity stream in https://bugzilla.mozilla.org/show_bug.cgi?id=1399648
