### ISSUE TITLE
PERMA-FAIL | browser/components/migration/tests/browser/browser_undo_notification_multiple_dismissal.js | Test timed out

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3303]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1395305
```1371516 - Intermittent browser/components/migration/tests/browser/browser_undo_notification_multiple_dismissal.js | Test timed out ```

https://treeherder.mozilla.org/logviewer.html#?job_id=127119661&repo=try&lineNumber=3774

**Comment by sarracini** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1395305

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/c6f942bf16a8
