### ISSUE TITLE
 PERMA-FAIL | browser/components/migration/tests/browser/browser_undo_notification_wording.js | Test timed out 

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3304]
``` 1392432 - Intermittent browser/components/migration/tests/browser/browser_undo_notification_wording.js | leaked 8 window(s) until shutdown [url = about:home] ```

https://treeherder.mozilla.org/logviewer.html#?job_id=127119661&repo=try&lineNumber=3787

**Comment by sarracini** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1395305

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/c6f942bf16a8
