### ISSUE TITLE
PERMA-FAIL | browser/modules/test/browser/browser_UsageTelemetry_content_aboutHome.js | Test timed out 

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3305]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1394777

``` 1347693 - Intermittent browser/modules/test/browser/browser_UsageTelemetry_content_aboutHome.js | Test timed out, Found a tab after previous test timed out: about:home```

https://treeherder.mozilla.org/#/jobs?repo=try&revision=4e323761c128b40621ffdff46c0e92dc6463df34&group_state=expanded&selectedJob=127119592

**Comment by piatra** [comment]
Fixed by https://hg.mozilla.org/mozilla-central/rev/a1c4ec3f36f6.
