### ISSUE TITLE
TypeError raised in "PreferancesPane#handleClickOutside"

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#3308]
This happened on my local build on master.

Error was thrown at [here](
https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx#L39) with message:

```JavaScript error: resource://activity-stream/data/content/activity-stream.bundle.js, line 2254: TypeError: this.refs.wrapper is undefined```

**Comment by rlr** [comment]
I think I broke this with 7d6f8b354ff321c178287aab81dcb47e1cdf5628. I'll fix.
