### ISSUE TITLE
Remove unused strings to simplify translating

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3314]
Now that Test Pilot is done development and self destructed in #3143, we can remove unused strings that aren't used or won't be used by the system addon. This makes it easier for locales that haven't finished translating as per https://github.com/mozilla/activity-stream/pull/3274#issuecomment-325572223

> Yes please. There's one major pro: some locales might have not translated those strings, and will if they decide to start or finish translating AS.

**Comment by k88hudson** [comment]
Could we write a eslint rule / a test for this perhaps in the future?

**Comment by Mardak** [comment]
Possibly going forwards. We're just in an odd state right now because some things were only used by Test Pilot version but potentially should be reused by system-addon.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1433209
