### ISSUE TITLE
Re-think UI updating strategy for places intensive actions

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3319]
With the patch for #3296 landing, we optimistically update the UI once we get an action from the context menu for delete/block, but ultimately we also re-query places and send another update with new sites as well. It's possible that the query takes long and we don't get new data for a while so we're left in this sort of strange state where we don't have data but we've updated the UI. Perhaps we should think about some strategies to properly update the UI without depending too much on a potentially slow places query

**Comment by Mardak** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1389125 adds a way for activity stream to pass in a {numItems} to request some number of top sites. We can request more than what we can show so that if one item is removed, the reducer should have another to fill in right away.

**Comment by sarracini** [comment]
I think we're doing ok - let's close this for now until it becomes a real problem
