### ISSUE TITLE
Create an Activity Stream search source for about:home

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3320]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1396272
Similar to https://github.com/mozilla/activity-stream/issues/2729
We will (probably) end up with two `ContentSearchUIController` instances that will be used to initiate searches depending if you are on about:home or about:newtab.
Any thoughts for how it would be best to implement this?

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1396272
