### ISSUE TITLE
Change contentSearchUIController to better match existing tests

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3321]
Basically a lot the tests need a gContentSearchController to be exposed on window, and certain ids put in so that the tests can pick them up in browser_aboutHome.js
@k88hudson i know it's shitty to add it to window, but how would you feel about something like this: https://gist.github.com/sarracini/047ad959a1e896d11e308e5522a2ee3b

**Comment by Mardak** [comment]
There's #2729 if we need a special healthreport key

**Comment by sarracini** [comment]
@Mardak should i dupe this one and just prefer #3320 ?

**Comment by Mardak** [comment]
Nah. leave that issue #3320 for the m-c related changes to add a new healthreport key.
