### ISSUE TITLE
Periodically update preloaded pages to have new content

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3331]
Maria noted that Pocket stories were from a few hours ago but a second new tab page had fresh stories. This is probably because the preloaded page had loaded those stories (and top sites) whenever the previous new tab opened.

We could have the page refresh or send new content to the page if it hasn't been seen yet (to avoid updating a page that the user has open).

**Comment by k88hudson** [comment]
There are a couple of options we could consider here:

- periodically refreshing preloaded (and non-visible) content
- adding a `broadcastToNonVisible` action creator, for updating any background tabs including preloaded ones

I think both probably make sense for different things

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421437
