### ISSUE TITLE
Update search icon (including orientation) for in-content search field to match URL bar

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3333]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1396893
and https://bugzilla.mozilla.org/show_bug.cgi?id=1399642
- [ ] Change icon in the search field
- [ ] Make it so we detect platform and flip the icon the appropriate direction

https://mozilla.invisionapp.com/share/YNDB2H5SQ#/251492361_Search_Icon
Assets folder: https://drive.google.com/drive/folders/0B6F4iApRJzosVTdaZjN3UHY5NG8

**Comment by Mardak** [comment]
Maybe not actually fixed. Unless https://bugzilla.mozilla.org/show_bug.cgi?id=1399642 is going to make `find.svg` the correct orientation

**Comment by aaronrbenson** [comment]
I might actually consider this fixed. From our end we're doing the right thing and the icon will match once that bug is completed. Unless I'm missing something...

**Comment by Mardak** [comment]
We'll just keep this open until the Firefox bug is fixed.

**Comment by Mardak** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399642 got prioritized P1 and assigned to daleharvey.
