### ISSUE TITLE
Strange behavior with Pocket after upgrading to Nightly

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3334]
Upgraded to Nightly v. 57.0a1 (2017-09-01) 

What happened?
After upgrading/restarting Nightly, my new tab page had Pocket stories turned off in prefs. After toggling them back on I saw the "You've caught up" message. Refreshed my new tab a few times before stories loaded.

What should probably happen:
My preference to show Pocket stories should have remained.
If there's a problem showing Pocket stories, it would be more appropriate to show the skeleton cards instead of the message telling me I've read all the stories (because I haven't .. it's just broken).

**Comment by Mardak** [comment]
On a new profile, I noticed that browser.search.region is not being set as quickly as it used to resulting in no Pocket stories section

**Comment by Mardak** [comment]
Well now I can't seem to reproduce the missing `browser.search.region` issue. Maybe it was a server side issue not responding but now fixed?

**Comment by Mardak** [comment]
Sounds like worksforme for now
