### ISSUE TITLE
New Tab page is empty

### ISSUE THREAD

**Issue by jnv** [mozilla/activity-stream#3340]
Firefox 55.0.2 on Ubuntu 17.04, x64 (also happens to me on Windows 10, x64), extension version 1.14.3.

When I open the new tab, Activity Stream, the page is empty:

![Empty new tab](https://user-images.githubusercontent.com/616767/30018560-ab9a2d1e-915d-11e7-8fe6-af3428a2721b.png)

In the console, I see the following exceptions:

```
TypeError: n.i is not a function  vendor.bundle.js:20:85241
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:85241
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:84954
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:77392
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:29094
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:76377
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:76284
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:74405
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:59495
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:43682
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:42273
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:20825
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:20:130683
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:1:1360
	<anonymous> resource://activity-streams/data/content/vendor.bundle.js:1:2
TypeError: ReactDOM.render is not a function  bundle.js:10444:5
	renderRootWhenAddonIsReady resource://activity-streams/data/content/bundle.js:10444:5
	<anonymous> resource://activity-streams/data/content/bundle.js:10451:1
	t resource://activity-streams/data/content/vendor.bundle.js:1:96
	window.webpackJsonp resource://activity-streams/data/content/vendor.bundle.js:1:418
	<anonymous> resource://activity-streams/data/content/bundle.js:1:1
```

**Comment by jnv** [comment]
This seems to be fixed in the pre-release version, but I find it strange the issue has not been (probably) reported. Could it be some interaction with another extension? Though the Activity Stream was working fine until the next week, so this is something with the latest stable release.

**Comment by piatra** [comment]
Is it possible you had Test Pilot version of Activity Stream in Firefox release? We recently decommissioned the Test Pilot version in preparation of launching Test Pilot as part of Firefox 57. 
If you tried Activity Stream in the pre-release version with the same profile then `browser.newtabpage.activity-stream.enabled` is set to true. The version shipped with Firefox 55 was not ready for production.

**Comment by jnv** [comment]
Yes, I have used Activity Streams as part of the Test Pilot program. So I assume this will be integrated into Firefox 57?
I would like to keep using Activity Streams with the stable version of Firefox. The pre-release version of the extension seems to work fine with Firefox 55.

**Comment by piatra** [comment]
Firefox 56 (which includes a working version of Activity Stream) will become the stable version on Sept 26. Until then I think your only options are to use Beta or Nightly unfortunately.

**Comment by piatra** [comment]
I'm going to close this but feel free to re-open if you have any more questions.
