### ISSUE TITLE
[Bug 1396590] Scrolling the New Tab customization panel wrongly scrolls the page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3343]
https://bugzilla.mozilla.org/show_bug.cgi?id=1396590

[Affected versions]:
- Firefox 57.0a1 Build ID 20170903220032

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.
- (optional) browser.newtabpage.activity-stream.feeds.section.topstories is set to true in about:config in the same profile. 

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Resize the browser so that the scroll bar appears.
3. Click the "Customize your New Tab page" button.
4. Hover the sidebar and scroll up or down.
 
[Expected results]:
- Nothing happens.

[Actual results]:
- The New Tab page is scrolled.

[Notes]:
- Attached a screen recording of the issue:
![scrolling the new tab customization panel wrongly scrolls the page](https://user-images.githubusercontent.com/18304511/30029766-2f35174e-9193-11e7-9f01-c4101c878526.gif)

**Comment by Mardak** [comment]
Design says this is behaving as the web works.
