### ISSUE TITLE
[Bug 1396591] Clicking to the right of any customization option wrongly checks/unchecks the box

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3344]
https://bugzilla.mozilla.org/show_bug.cgi?id=1396591

[Affected versions]:
- Firefox 57.0a1 Build ID 20170903220032

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the "Customize your New Tab page" button.
3. Click to the right of one of the checkboxes.
4. Observe the behavior.
 
[Expected results]:
- Nothing happens.

[Actual results]:
- The checkbox is unchecked.

[Notes]:
- Attached a screen recording of the issue:
![customization wrongly checked](https://user-images.githubusercontent.com/18304511/30029793-4ab1cf8a-9193-11e7-8c51-d3ed04914728.gif)

**Comment by Mardak** [comment]
That was an intended change.
