### ISSUE TITLE
USA resident account is synced with a new profile created in a region that has "Recommended by Pocket" restricted 

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#3346]
[Affected versions]:
- Firefox Nightly 57.0a1
- Latest Activity Stream system add-on

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Firefox Nightly is updated to the latest version.
- User 1 is a USA resident, that has a Firefox account with sync enabled. All Preferences are available in the New Tab Preferences menu (Search, Top Sites, Recommended by Pocket)

[Steps to reproduce]:
1. User 1 travels to Europe or any other region in which "Recommended by Pocket" section is not available due to geo-restrictions.
2. Open Firefox Nightly and create a new profile.
3. Go to `about:preferences?entrypoint=menupanel#sync` and sync with the account from prerequisites.
4. Restart the browser.
5. Click on "Customize your New Tab page" button from the top-right side of the A-S page.
6. Observe the New Tab Preferences menu.

[Expected result]:
- Recommended by Pocket section is available.

[Actual result]:
- Recommended by Pocket section is missing from A-S and New Tab Preferences menu.

[Notes]:
- Force changing the pref `browser.newtabpage.activity-stream.feeds.section.topstories` from **false** to **true** does not show the "Recommended by Pocket" section in the New Tab Preferences menu.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1433255
