### ISSUE TITLE
Create render image to canvas function in PageThumbUtils.jsm

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3349]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1397390
This function should take a window, an imageURL and a width, and return a canvas. It should render the image to the canvas and resize it appropriately.

This is part of the preview image caching work

**Comment by sarracini** [comment]
Landed with: https://hg.mozilla.org/mozilla-central/rev/04e5cb3e68b4
