### ISSUE TITLE
Specific websites are still displayed in the "Top Sites" after they are dismissed from the context menu

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/activity-stream#3354]
https://bugzilla.mozilla.org/show_bug.cgi?id=1397207

**Notes**
- The issue is reproducible on the following websites:
		- https://9gag.com/
		- https://wordpress.com/
		- on https://www.facebook.com/ the issue is intermittent.
There may be more websites like this, but I have not found them yet.

**[Affected versions]:**
- Firefox: 57.0a1, Build ID: 20170905100117

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to https://9gag.com/ and open a new tab.
3. Close the previous tab and navigate again to https://9gag.com/
4. Repeat step 3 at least 2 more times.
5. Restart the browser.
6. Dismiss the "9Gag" Top Site.
7. Observe the "Top sites" area.

**[Expected result]:**
- Only the default top sites are displayed.

**[Actual result]:**
- The previously dismissed top site is still displayed.

**[Additional Notes]:**
- Attached a screen recording of the issue
![top sites](https://user-images.githubusercontent.com/31243259/30104851-7643e2c4-92ff-11e7-8913-aa3682fdb76f.gif)

**Comment by Mardak** [comment]
What's the url of the initial top site? And is the url different after dismissing the first time?

**Comment by Softvision-MariusComan** [comment]
The initial URL was https://9gag.com and after I dismissed the top site, URL changes to 9gag.com.

**Comment by Mardak** [comment]
A potential workaround is to block both a http and https version of the url. Although it's still quite likely that if the user has a say site/ and site/frecentUrl1 and site/frecentUrl2 near each other, blocking one will cause the other to appear because blocks are handled on a per-url basis not by domain.
