### ISSUE TITLE
A horizontal scroll bar is wrongly displayed for a fraction of a second when opening/closing the Customization menu

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3357]
https://bugzilla.mozilla.org/show_bug.cgi?id=1397252

[Affected versions]:
- Firefox 57.0a1 Build ID 20170905220108

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the "Customize your New Tab page" button and observe the bottom part of the menu.
 
[Expected results]:
- The open animation is smooth.

[Actual results]:
- A horizontal scroll bar is displayed for a fraction of a second.

[Notes]:
- On Mac and Windows, the same scroll bar appears when you close the menu.
- On Ubuntu, there is an empty space in stead of a scroll bar.
- Attached a screen recording of the issue:
![scroll bar is displayed for a second](https://user-images.githubusercontent.com/18304511/30110679-929f3798-9313-11e7-9c3e-75d1fad54a22.gif)

**Comment by tspurway** [comment]
I am reluctantly putting this at P2, but could be convinced otherwise

**Comment by Mardak** [comment]
@aaronrbenson says
> If we can't resolve this with the current layout I'd suggest we go back to a done button in the flow of the panel.
