### ISSUE TITLE
Show fewer top sites displays four items instead of six

### ISSUE THREAD

**Issue by ibrahimalhazwani** [mozilla/activity-stream#3358]
I have pinned 10 websites and deleted the last two. If I select show fewer only 4 are displayed instead of full row of 6 websites.

![screen shot 2017-09-06 at 19 20 33](https://user-images.githubusercontent.com/31704631/30125409-9d932eaa-9338-11e7-9db9-cd318b141983.png)
![screen shot 2017-09-06 at 19 20 52](https://user-images.githubusercontent.com/31704631/30125415-a20d1072-9338-11e7-9420-187c51628c27.png)

**Comment by Mardak** [comment]
This might be the same thing as #3141 except with the new default of 1 row

**Comment by tspurway** [comment]
@ibrahimalhazwani we are having trouble reproducing in the latest version.  Could you try again?

**Comment by Mardak** [comment]
I can reproduce this if I have a lot of pinned sites and shift them out of the first 12 positions. One fix is to only use the first `topSitesCount` pinned links (including holes), so this effectively throws away those pinned links. Or filter out the holes when only picking out the desired number of top sites -- although I'm not quite sure how that will affect the ordering of things…

**Comment by Mardak** [comment]
Duping to #3141
