### ISSUE TITLE
Prefs panel has some 'jank' to it when opening 

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3362]
Opening the prefs panel sidebar isn't as smooth as it used to be (before the fixed footer with the Done button). There appears to be a horizontal scrollbar showing up for a brief moment too.

If we can't resolve this with the current layout I'd suggest we go back to a done button in the flow of the panel.

https://cl.ly/3d1L1S363d2s

**Comment by asadotzler** [comment]
![ntp-prefs](https://user-images.githubusercontent.com/552390/30138364-c6c66bf0-931c-11e7-9c95-63172a7899de.gif)

**Comment by Mardak** [comment]
Dupe #3357
