### ISSUE TITLE
Support real strings in prerendered html

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3370]
Not sure if this will be covered by https://github.com/mozilla/activity-stream/issues/3367, but we would like to have real strings in our prerendered html

**Comment by flodolo** [comment]
CC @zbraniecki and @pike
The issue was reported as very visible on Debug builds, or slow hardware.

**Comment by Mardak** [comment]
In the mean time, we'll be removing the english string https://bugzilla.mozilla.org/show_bug.cgi?id=1406096
