### ISSUE TITLE
Add tests for activity-stream.jsx

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3373]
Currently, we don't have any unit tests for content-src/activity-stream.jsx. We should add some.

**Comment by georgegillams** [comment]
I notice this has the "Good first bug" tag and hasn't been dealt with for a while. I have some experience of testing with Jest. Mind if I jump on it?

**Comment by SeanPrashad** [comment]
Hi @georgegillams - I was wondering if you were still tackling this bug? If not, would you mind if I were to take the torch and see it through?

**Comment by georgegillams** [comment]
Yeah sure! Sorry - I've just been a bit buried in other work tbh

**Comment by SeanPrashad** [comment]
Hi @k88hudson - I've read the notes on [Unit Testing](https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/unit_testing_guide.md#unit-testing-in-activity-stream) in Activity Stream and I'm trying to figure out what tests I exactly need to carry out in the new test file (`test/unit/activity-stream.test.jsx`).

I was reviewing [activity-stream-prerender.test.jsx](https://github.com/mozilla/activity-stream/blob/8fe1055eb322385810376a2be8d137333e360767/system-addon/test/unit/activity-stream-prerender.test.jsx#L6) to get an idea of what's expected but I'm not sure exactly where to start.

I think to start off, we should test to see if we're in a pre-rendered state. If not, then try to request "state rehydration" according to [this](https://github.com/mozilla/activity-stream/blob/8fe1055eb322385810376a2be8d137333e360767/system-addon/content-src/activity-stream.jsx#L15) comment and `assert` if we actually did get the expected outcome.

What do you think? Would there be a better test suite that I should base my own off of?

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432315
