### ISSUE TITLE
Search suggestions box should not have a blue border around it

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3374]
![screen shot 2017-09-07 at 2 52 38 pm](https://user-images.githubusercontent.com/139451/30182469-70ee651e-93dc-11e7-945f-d0c618f77f69.png)

There should be a blue border around the input field and not the suggestions box beneath it.

**Comment by Mardak** [comment]
What should the border be for the suggestions? (If we don't have a border, it will be hard to position the suggestions correctly. Also, noticed there's a small white gap at the bottom right of the search button when suggestions are open.

**Comment by Mardak** [comment]
Actually, here it is without the border (it's actually box-shadow):
<img width="771" alt="image" src="https://user-images.githubusercontent.com/438537/30184835-347111d4-93d4-11e7-91c3-c62e52581bbe.png">

Notice that the suggestions start 2px right of the left blue edge. And end 2px left of the right blue edge.

**Comment by Mardak** [comment]
> can we round out the bottom left/right corner?

(of the input box)
