### ISSUE TITLE
Top Sites "Edit" button disappears after removing all Top Sites

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3384]
https://bugzilla.mozilla.org/show_bug.cgi?id=1398076

[Affected versions]:
- Firefox 57.0a1 Build ID 20170907220212

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a new tab.
2. Dismiss all the default Top Sites.
3. Observe the Top Sites section.
 
[Expected results]:
- Empty placeholders are displayed, but the "Edit" button remains.

[Actual results]:
- The "Edit" button disappears along with the last Top Site.

[Notes]:
- The issue is also reproducible if you dismiss Top Sites while you are in the Edit Top Sites menu.
- Attached a screen shot of the issue:
![top sites edit button missing](https://user-images.githubusercontent.com/18304511/30206151-d42457c6-9493-11e7-96b4-86ce17c4a739.png)

**Comment by Mardak** [comment]
Design says yeah fix because user can dismiss the initial 6. But yeah easy to fix itself by actually using Firefox by going to a website.
