### ISSUE TITLE
There is no background fading overlay when the "Customization" menu is open

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/activity-stream#3388]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1398192
**[Notes]:**
- The overlay was present in the old "about:newtab".

**[Affected versions]:**
- Nightly 57.0a1

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and open a new tab.
2. Click on the "Customize your New Tab page" button.
3. Observe the "New Tab" page.

**[Expected result]:**
- An overlay is obscuring the rest of the page.

**[Actual result]:**
- There is no overlay.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![overlay issue](https://user-images.githubusercontent.com/31243259/30218919-1f014590-94c3-11e7-86b3-b6b1f77bb459.gif)

**Comment by Mardak** [comment]
Design says it's by design because users should be able to see what they're doing as they interact with prefs.
