### ISSUE TITLE
Only show one highlight history per domain

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3390]
Design says to avoid cluttering highlights with history items all from the same site, e.g., shopping for multiple items.

![pasted image at 2017_09_08 08_21 am](https://user-images.githubusercontent.com/438537/30225020-c84d470e-9485-11e7-8ced-d2aa5ffabb33.png)

**Comment by Mardak** [comment]
@aaronrbenson @nchapman I would assume we should still show all the bookmarks even from the same domain. But how about if the user also has recent visits from those bookmarked domains? Do we show one history from the domain or treat it as the bookmark(s) has taken up the spot for that domain, and we should use the remaining space for other domains?

**Comment by aaronrbenson** [comment]
Lets de-dupe same-domain items including bookmarked / recently visited.

**Comment by Mardak** [comment]
@aaronrbenson sorry, do you mean even if the user has bookmarked multiple pages from the same domain, only pick out the most recently bookmarked from that domain? This would also prevent any recently visited from the same domain from showing up due to the recently bookmarked?

**Comment by Mardak** [comment]
Before (team):
![screen shot 2017-09-09 at 11 08 42 am](https://user-images.githubusercontent.com/438537/30242690-f0c884bc-954f-11e7-9b34-b99348d4df66.png)

After (only aaron):
![screen shot 2017-09-09 at 11 10 25 am](https://user-images.githubusercontent.com/438537/30242694-f7c22a16-954f-11e7-9868-65ef2529fed2.png)

**Comment by Mardak** [comment]
"keeping all recent bookmarks from a domain"
