### ISSUE TITLE
Switch Pocket "Now" card type to "Popular"

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3402]
#3391 was a fix to just treat everything as Trending because we need a new string for "Popular".

**Comment by csadilek** [comment]
Do we have an icon for "Popular"?

**Comment by Mardak** [comment]
@aaronrbenson suggested trending would be 🔥 and popular would be ⚡️ but still deciding

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432293
