### ISSUE TITLE
Show placeholder image for Highlight bookmarks without images

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3406]
https://bugzilla.mozilla.org/show_bug.cgi?id=1398715

[Notes]:
- The bookmarks have to have been created in a Nightly version that did not have Highlights.
- The issue is also reproducible if you import History from another browser in a new profile.

[Affected versions]:
- Firefox 57.0a1 Build ID 20170910220126

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile of Nightly 2017-09-07.
- Have enough history so that all 12 Top Sites are populated.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Navigate to three pages and bookmark them.
3. Update Nightly.
4. Open a New Tab and observe the first three cards from the Highlights section.

[Expected results]:
- The cards have an image, a title and a short description of the bookmarked page.

[Actual results]:
- The cards have titles, but lack descriptions and images.

[Additional Notes]:
- Attached a screen recording of the issue:
![bookmarks with no images after update](https://user-images.githubusercontent.com/18304511/30269404-5f4b822a-96f1-11e7-8dee-c945cb208f0e.gif)

**Comment by tspurway** [comment]
@bryanbell @aaronrbenson could you folks get us a comp with the 'grey rectangle' placeholder?

**Comment by AdamHillier** [comment]
Per Slack conversation with @bryanbell regarding #2322, we should fall back to a screenshot for any highlights that don't have an image, and while loading the image/screenshot should use a color gradient of grey 40 to grey 30 at 45 degrees.

![pasted image at 2017_09_11 04_34 pm](https://user-images.githubusercontent.com/7688302/30301539-50ea8ae0-9729-11e7-95aa-1bd2d7a40984.png)

**Comment by Mardak** [comment]
@bryanbell should the darker corner be in the top right for RTL?
