### ISSUE TITLE
If bookmark more than 9 websites, only they are displayed in Highlights section

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/activity-stream#3407]
https://bugzilla.mozilla.org/show_bug.cgi?id=1398752

[Affected versions]:
- Firefox 57.0a1 Build ID 20170910220126

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "browser.newtabpage.activity-stream.enabled" pref is set to true in about:config on a clean new profile.
- Have enough history so that all cards from Highlights are populated.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Navigate to 9 pages and bookmark them.
3. Visit multiple websites.
4. Restart the browser and observe the Highlights section.

[Expected results]:
- The visited websites are displayed in the Highlights section.

[Actual results]:
- The bookmarked websites are stuck in the Highlights section and no recently visited website are displayed.

[Notes]:
- Here is a screen recording with the issue:
![only bookmarked websites](https://user-images.githubusercontent.com/19226534/30274704-4336b620-9707-11e7-82d1-4bff7accbca3.gif)

**Comment by Mardak** [comment]
By design to just show the most recent 9 bookmarks
