### ISSUE TITLE
If a page is bookmarked multiple times it has to be removed just as many times in order to fully remove it

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3408]
https://bugzilla.mozilla.org/show_bug.cgi?id=1398753

[Affected versions]:
- Firefox 57.0a1 Build ID 20170910220126

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.
- Have enough history so that all 12 Top Sites are populated.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Navigate to a website and bookmark it in three locations.
3. Open a New Tab and hover the first Highlights card.
4. Remove it as a bookmark.
5. Refresh the page and observe the card's state.

[Expected results]:
- Card's status is "Visited".

[Actual results]:
- Card's status is "Bookmarked".

[Notes]:
- Attached a screen recording of the issue:
![not all bookmarks of the same page removed](https://user-images.githubusercontent.com/18304511/30275510-3d3ee2a8-970a-11e7-949e-11cb76dba7ff.gif)

**Comment by Mardak** [comment]
The location bar bookmark star shows "Remove # bookmarks" when there's multiple. Desired behavior is just to remove all bookmarks. (No string change to "Remove bookmark")

**Comment by PhillypHenning** [comment]
Hey this looks interesting, mind if I take it?

**Comment by PhillypHenning** [comment]
Also could I get a bit more context on what you would like done. 

Is it supposed to say visited instead of having the bookmark options, or when all bookmarks are removed would you like it to say 'visited' instead of 'bookmark'

**Comment by dmose** [comment]
@PhillypHenning consider it yours.  We can't assign bugs to people without direct push access, so I've assigned it to myself.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1398753

**Comment by dmose** [comment]
@PhillypHenning we're doing a process experiment by moving some of our issues to be tracked at bugzilla.mozilla.org.  We'd still love your help working on this bug; would be up for creating an account there?  [bug 1398753](https://bugzilla.mozilla.org/show_bug.cgi?id=1398753) is where the action is moving to...

**Comment by PhillypHenning** [comment]
Hey,
Unfortunately pressure from other projects has taken all the time up I have
currently, however if I become free again I will be sure to jump on board.
Sorry I couldn't help with this.

**Comment by dmose** [comment]
No worries; thanks for letting us know!
