### ISSUE TITLE
Fix sass linting

### ISSUE THREAD

**Issue by AdamHillier** [mozilla/activity-stream#3409]
Sass-linting was misconfigured to point to the old test-pilot code, so the system-addon wasn't being linted. Fixing that configuration in #3389 threw up lots of linting errors in the system-addon, so I disabled sass-linting for now. At some point those errors should be fixed and sass-linting re-enabled.

**Comment by SeanPrashad** [comment]
Hi @dmose! This will be my first time contributing to Mozilla's Activity Stream so I have some reading to do for [contributing](https://github.com/mozilla/activity-stream/blob/master/contributing.md#contributing-to-activity-stream) and [setting up my local env](https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/1.GETTING_STARTED.md#activity-stream-development-guide). I will ping you if I have any further questions!

**Comment by dmose** [comment]
Sounds good.  Note that it's possible that there are pieces of those docs that have bit-rotted, so if you hit a block, don't struggle with it too long and just ask in #activity-stream on irc.mozilla.org

**Comment by SeanPrashad** [comment]
Hi @tspurway, @dmose mentioned it was okay for me to tackle this bug - may I be assigned to it? Thank you!!

**Comment by Mardak** [comment]
The assignee is the mentor for the issue. Github doesn't seem to allow non-collaborators to be assigned to issues.

**Comment by SeanPrashad** [comment]
Ah ok thanks for clarifying that @Mardak!

**Comment by SeanPrashad** [comment]
Update: WIP as of Sunday October 22 - installed `sass-lint` locally and currently building via [CLI](https://github.com/sasstools/sass-lint) with ~3 errors and 73 warnings to go! 🙏🏽

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421444

**Comment by dmose** [comment]
@SeanPrashad, we're doing some experiments with process, and this bug and the PR based on your work are continuing to move [in Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1421444).  Would you be interested in creating an account there and continuing to follow along?  Let me know here, and I'll be happy to CC you on the bug if you're interested...

**Comment by SeanPrashad** [comment]
@dmose I would love to! I'll post over there on my account
