### ISSUE TITLE
If the Highlights section is re-enabled, no cards are displayed until the page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3410]
https://bugzilla.mozilla.org/show_bug.cgi?id=1398779

[Affected versions]:
- Firefox 57.0a1 Build ID 20170910220126

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- browser.newtabpage.activity-stream.enabled is set to true in about:config on a clean new profile.
- Have enough history so that Top Sites and Highlights are populated.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites.
2. Click the "Customize your New Tab page" button.
3. Disable the Highlights section.
4. Re-enable the Highlights section.

[Expected results]:
- All previously hidden Highlights are displayed.

[Actual results]:
- Three empty placeholders are displayed.

[Notes]:
- Attached a screen recording of the issue:
![highlights not displayed after re-enabling them](https://user-images.githubusercontent.com/18304511/30277775-73f53638-9711-11e7-9cab-7b4b07041c80.gif)

**Comment by AdamHillier** [comment]
This is a side-effect of https://github.com/mozilla/activity-stream/pull/3383 - no new tab load happens, so highlights aren't refreshed

**Comment by Mardak** [comment]
Sounds like HighlightsFeed needs to watch the pref change to broadcast?

**Comment by Mardak** [comment]
Alternatively somehow detect if it's late enough from startup during an `INIT` to avoid failing startup tests?

**Comment by AdamHillier** [comment]
In the store we have an init action that we hold onto and then pass to a re-initialised feed's onAction don't we? Could we add a bool to that action's data when it's reinit as opposed to init?
