### ISSUE TITLE
Black flash after clicking on site

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3413]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1398845

> After the click, the window briefly flashes black before it becomes white and
starts loading the page.
> I think this indicates that the compositor doesn't have any content for the
content area.

**Comment by k88hudson** [comment]
I'm seeing a black border, which I can't reproduce on Tiles

<img width="891" alt="image" src="https://user-images.githubusercontent.com/1455535/30289782-3ab57e2a-96fb-11e7-9158-5f0bc38611c6.png">
