### ISSUE TITLE
TopSites weirdness with pinning

### ISSUE THREAD

**Issue by AdamHillier** [mozilla/activity-stream#3415]
If you have not very many TopSites, then pin the last one (but probably if you pin any site) and dismiss some sites that come before the pinned site, you get the weirdness shown here.

![bug](https://user-images.githubusercontent.com/7688302/30293968-648513d8-9709-11e7-9d69-4545ef18e24f.gif)

**Comment by AdamHillier** [comment]
I think this arises when you pin a site at index eight, say, but have fewer than seven other top sites, causing the pinned site to be shifted leftwards because there aren't enough to "fill in" the spaces up to position seven. A possible solution is to temporarily have the pinned site be leftwards while there aren't enough top sites so it's restored to its original position later on when there are enough. Alternatively, permanently move the pinned site leftwards.

**Comment by rlr** [comment]
This got fixed with recent pinning and drag and drop changes and fixes
