### ISSUE TITLE
Dismissing a Pocket recommendation wrongly dismisses the Highlights card of the same page

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3423]
https://bugzilla.mozilla.org/show_bug.cgi?id=1399052

[Affected versions]:
- Firefox 57.0a1 Build ID 20170912013600

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "browser.newtabpage.activity-stream.enabled" and "browser.newtabpage.activity-stream.feeds.section.topstories" are set to true in about:config on a clean new profile.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Navigate to the three Top Stories from Pocket.
3. Open a new tab and dismiss one of the Top Stories.
4. Observe the Top Stories and Highlights sections. 

[Expected results]:
- The Top Story is dismissed from its section, another one takes it place and there is no change in the Highlights section.

[Actual results]:
- The Top Story is dismissed from its section, but the Highlight card of the same page is also dismissed.

[Notes]:
- Dismissing a Highlight will not dismiss a Top Story of the same page.
- Attached a screen recording of the issue:
![dismissing a top story will dismiss a highlight of the same page](https://user-images.githubusercontent.com/18304511/30319778-769139a2-97b9-11e7-901a-4fb03115910e.gif)

**Comment by Mardak** [comment]
Might be fixed by #3131 because the story card won't show up if in Highlights.

**Comment by Mardak** [comment]
Design says to fix by deduping stories agaginst highlights
