### ISSUE TITLE
Turning off Snippets doesn't hide snippets or onboarding

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3425]
Looks like turning it back on will maybe cause the snippets to refresh? @AdamHillier @k88hudson 

Snippets:
![screen shot 2017-09-12 at 6 36 47 am](https://user-images.githubusercontent.com/438537/30328736-1a26b14e-9785-11e7-81d6-3e0e3496e384.png)

Onboarding:
![screen shot 2017-09-12 at 6 35 50 am](https://user-images.githubusercontent.com/438537/30328755-2360bc28-9785-11e7-82e6-c8c0ac352011.png)

I suppose interesting to note that snippets appear behind the pref pane while onboarding appears on top.

**Comment by k88hudson** [comment]
@Mardak this is because some changes need to be landed in the snippet service, which is filed here: https://github.com/mozmeao/snippets-service/issues/281

Onboarding will be covered when https://bugzilla.mozilla.org/show_bug.cgi?id=1393489 lands

**Comment by k88hudson** [comment]
I added the `Metabug` label since this ticket is useful tracking but requires no further action on our end

**Comment by aaronrbenson** [comment]
Conversely, if I had snippets turned off and then I turn them back on, we should show a snippet. This helps to make it clear what a snippet is and where it lives.

**Comment by Mardak** [comment]
The converse might be tricky as there might not always be a snippet to show? Should we have some default snippet similar to the old about:home? Or I suppose that would basically just be onboarding's notifications?
