### ISSUE TITLE
Transparent background turns black when thumbnailed

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3433]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1399200
Noticed with #3427.

Before when fetching image directly:
![screen shot 2017-09-12 at 12 08 17 pm](https://user-images.githubusercontent.com/438537/30343756-7ed7a98a-97b3-11e7-8e8c-8ad83b56f000.png)

With #3427 using caching for #3349:
![screen shot 2017-09-12 at 12 12 15 pm](https://user-images.githubusercontent.com/438537/30343835-bcacf85a-97b3-11e7-9f0a-0c24f69f774a.png)

**Comment by k88hudson** [comment]
Ah, interesting – this probably requires some changes to the thumbnail code for rendering stuff with transparent backgrounds

cc @AdamHillier

**Comment by Mardak** [comment]
Of the choices of grey-30, grey-10, white:
> yeah grey-10 seem okay

For some context, grey-10 was previously suggested for rich favicons to prevent white images from disappearing.

grey-30
![pasted image at 2017_09_12 12_43 pm](https://user-images.githubusercontent.com/438537/30345445-eb9a4eb4-97b9-11e7-9022-33bfaeaecd9f.png)

grey-10
![pasted image at 2017_09_12 12_44 pm](https://user-images.githubusercontent.com/438537/30345454-f265491a-97b9-11e7-8fc1-c740c01b6c9d.png)

white
![pasted image at 2017_09_12 12_45 pm](https://user-images.githubusercontent.com/438537/30345460-f82f0eda-97b9-11e7-98d4-8cecf74ee5fb.png)

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/ce559fa15078
