### ISSUE TITLE
activity-stream.bundle.js isn't minified

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#3436]
Using today's Nightly build, if I navigate to resource://activity-stream/data/content/activity-stream.bundle.js, I notice that the output isn't minified.
Not sure if that's a big deal, but we may be able to shave a few KB.

**Comment by k88hudson** [comment]
We made this decision in order to allow for better debugging / readability in the codebase; I think it would be tough to commit minified code without including our source code in patches

**Comment by Mardak** [comment]
It gets compressed via jar for delivery but for parsing, potentially there's some benefit. P2 to profile to see if there's any benefit.

**Comment by Mardak** [comment]
This isn't done for other firefox js code
