### ISSUE TITLE
Punycode URL shows [?] as placeholder thumbnail in Top Sites

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#3440]
Possibly related to #3221

I manually created a topsite for the excellent http://🇨🇦🍕.ws web site, and it correctly shows my unicoded "🇨🇦🍕" as a title, but it seems like the placeholder image is a big **[?]** icon. I'm _guessing_ that may be because we're trying to extract the first letter in order to show an "A" (as is the case for my amazon.ca topsite) but it doesn't like my my punycode URL.

<img width="792" alt="nightly" src="https://user-images.githubusercontent.com/557895/30351953-8b31a93c-97d2-11e7-8fff-7ae935721075.png">

**Comment by Mardak** [comment]
Just confirming it's possible to show the "letter":
<img width="121" alt="image" src="https://user-images.githubusercontent.com/438537/30391734-5bd0ade4-986f-11e7-802c-6a1b088c52bb.png">

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432292
