### ISSUE TITLE
Delay showing latest Recommended stories if another new tab was opened recently?

### ISSUE THREAD

**Issue by cpeterso** [mozilla/activity-stream#3443]
Sometimes when opening two new tabs within a short period of time, the second tab's "Recommended by Pocket" stories are different from the first's. I understand that the first tab's stories are probably stale, but it is jarring to see the stories change.

Perhaps a new tab can check if another new tab has been opened less than (say) one minute ago and, if so, then show the same stories as it, even if more recent stories are available?

The current experience can be especially frustrating if I quickly open and close a new tab, but an interesting story caught my eye. So I reopen a new tab but the stories have either changed or shifted to the right. (I know the older stories are still available in "View More Stories", but some users might not see that small link and feel frustrated that the missed a story.)

**Comment by AdamHillier** [comment]
When we update Pocket stories we don't update them on existing open pages as we don't want a user to see them change on a tab they're currently looking at. Also, for performance reasons we pre-load new tab pages. When you open the first new tab you get the pre-loaded page that could have been created a while ago and have stale data as you say, then the second one gets the fresh data. A solution might be to do a targeted update of the pre-loaded page when we update a section.

**Comment by Mardak** [comment]
There's #3331 for making the pages refresh in the background, but that's more the opposite of this issue.

**Comment by Mardak** [comment]
The "View More Stories" link to the bottom right of the section actually shows all the previously shown cards in the same order.

This should still work until maybe the personalization happens...

There could be a lot of possible design outcomes but after 57

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432291
