### ISSUE TITLE
Add telemetry for types of images shown for top sites

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3449]
Could be useful to know how many users are seeing just screenshots (favicon too low quality) vs screenshot + icon in corner (#3150 vs high res icons (#3327).

I went through Dismiss/blocking top sites until I got all rich icons and my ~70th most frecent page got the 12th rich icon top site.

**Comment by piatra** [comment]
The approach will be similar to what we previously had in the TP version.
* payload example `{"topsite_tippytop/favicon": 3, "topsite_screenshot+icon": 5, "topsite_screenshot" : 1}`
  * keys have to be part of the top level session object. [The same way they were handled in TP](https://github.com/mozilla/activity-stream/blob/release-1.15.0/addon/TabTracker.js#L167-L171)
* in TopSites [notify on mount or update with the new data](https://github.com/mozilla/activity-stream/blob/5779a88eef785d058f0eff6267ad28691332dcef/content-src/components/NewTabPage/NewTabPage.js#L68-L73)
* attach the information to the session data and update throughout the session. 
  * Meaning we only send the information once when the session ends.
