### ISSUE TITLE
Early visibility_event lost when ActivityStream isn't ready

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3455]
`DetectUserSessionStart` has some custom `sendAsyncMessage` to send "visibility_event_rcvd_ts" and is run as the page is loading. Potentially we could be smarter to have a general queue for any early messages to be sent on `INIT` similar to what @k88hudson did for `NEW_TAB_STATE_REQUEST`:
https://github.com/mozilla/activity-stream/blob/c214278f4c07121c92a9dc52cb51d856cb2ba850/system-addon/content-src/lib/init-store.js#L64-L67

@dmose

**Comment by k88hudson** [comment]
If you want, you could wait on `NEW_TAB_INITIAL_STATE` since that is guaranteed to come from chrome. so something like this:

```js
if (!store._didRehydrate && actionIsTelemetry) {
   queue.push(action);
   // Don't call next
   return;
}
...
if (action.type === MERGE_STORE_ACTION && queue.length) {
  queue.forEach(a => store.dispatch(a));
}

```

**Comment by dmose** [comment]
I like Kate's generalization theory, assuming that doesn't have any unanticipated complexity.
