### ISSUE TITLE
Unable to debug new tab page using React DevTools

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#3459]
This is pretty meta, and not convinced it's worth solving, but...
I was trying to debug the page using React Developer Tools extension (https://addons.mozilla.org/en-US/firefox/addon/react-devtools/) and I'm getting "This page doesn't appear to be using React" error:

<img width="552" alt="nightly" src="https://user-images.githubusercontent.com/557895/30395902-9a6f2afa-987c-11e7-8db1-7d5cea0f0f72.png">

Could possibly be because we're not a _real_ page. I tried injecting the standalone version script https://github.com/facebook/react-devtools/tree/master/packages/react-devtools but that didn't seem to work for me locally.

Not sure if anybody else has gotten this working locally, or if it's something we should potentially investigate injecting into the dev version of the extension (if that still gets built regularly).

**Comment by k88hudson** [comment]
This is a known issue because about:home/about:newtab doesn't have a real origin :'(

**Comment by pdehaan** [comment]
The docs seem to imply it _could_ work w/ React Dev Tools standalone Electron app if you inject a `<script src="http://localhost:8097"></script>` before importing ReactDOM, but I'm not sure how stable that port number is, or if we have a way to detect whether we're running locally vs dev vs prod vs nightly, and if we could/should  inject that script. Or if we could optionally inject it using some about:newpage?debug flag.

<img width="800" alt="react_developer_tools" src="https://user-images.githubusercontent.com/557895/30397058-6dc0d34c-9880-11e7-8a8a-2c75c943d282.png">

**Comment by pdehaan** [comment]
Unreleated, but I was also trying to run the aXe a11y linter extension against Activity Steam the other day, but then hit https://github.com/dequelabs/axe-firefox-devtools/issues/53

Testing non-URL based stuff is tricky.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448364
