### ISSUE TITLE
Top site shows "http://" protocol and "H" letter fallback

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#3460]
In today's Nightly... I was trying to get React Developer Tools working locally and had http://localhost:8097 in my history, and noticed I had a top site for "http://localhost:...", which seemed odd:

<img width="782" alt="new_tab" src="https://user-images.githubusercontent.com/557895/30396220-c8f239ca-987d-11e7-93bf-baa67c19be54.png">

**Comment by Mardak** [comment]
This is probably because there's no `eTLD` for `localhost` and something is falling back to the url.

**Comment by pdehaan** [comment]
It looks like using an IP (http://192.168.0.17:8097/) instead of http://localhost:8097/ doesn't have the protocol in the title:

<img width="820" alt="new_tab" src="https://user-images.githubusercontent.com/557895/30397604-3d41ff5a-9882-11e7-993f-7d8ad55fb04d.png">
