### ISSUE TITLE
If Activity Stream is disabled from about:config, the old new tab page is wrongly displayed

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/activity-stream#3468]
**[Affected versions]:**
- Nightly 57.0a1 Build ID 20170914100122

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Steps to reproduce]:**
1. Open the latest Nightly and go to about:config page.
2. Change the value of "browser.newtabpage.activity-stream.enabled" pref to false.
3. Restart the browser and open a new tab.
4. Observe the new tab page.

**[Expected result]:**
- A blank page is displayed.

**[Actual result]:**
- Old New Tab page is displayed.

**[Notes]:**
- Attached a screen recording of the issue:
![new tab](https://user-images.githubusercontent.com/31243259/30439021-62a2e08a-997b-11e7-853d-078634322c46.gif)

**Comment by Mardak** [comment]
The desired behavior of disabling activity stream is to get tiles… for now. Later there won't be an option to disable activity stream
