### ISSUE TITLE
Activity Stream periodically pegs a content process

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3473]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1399965

Profile to view via https://perf-html.io (after extracting locally)
https://bugzilla.mozilla.org/attachment.cgi?id=8908260

**Comment by Mardak** [comment]
@k88hudson noticed that
> After some investigation it looks like the Sections component's render function is being called 9 times on every load (since it is receiving 9 SECTION_UPDATE_CARD events), that's something we might want to look more into

**Comment by k88hudson** [comment]
Here's some more data:

With highlights disabled: 
![image](https://user-images.githubusercontent.com/1455535/30454385-21de8222-996a-11e7-952f-6355a7b830f6.png)

With highlights enabled: 
![image](https://user-images.githubusercontent.com/1455535/30454402-296484b0-996a-11e7-866f-c87339dcf0f2.png)
