### ISSUE TITLE
Editing a top site does not change it

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#3478]
Firefox Version: 57.0a1 (2017-09-14) (64-bit)
OS: OSX Sierra 10.12.16

Steps to reproduce

1) Open a new tab
2) Hit 'edit'
3) Click the pen icon on a topsite
4) Type in some new site
5) Hit save

Expected results:

The top site changes to the entered site

Actual results:

It stays the same

Recording:
https://www.dropbox.com/s/kx7eaqkt0s71pe8/a-s%20topsites.mov?dl=0

**Comment by rlr** [comment]
I'm unable to reproduce on today's Nightly (2017-09-15)

**Comment by tspurway** [comment]
wfm, could you try to repro on latest nightly?

**Comment by jaredkerim** [comment]
Just tried to reproduce this on the latest nightly and couldn't, I'll close this for now and we can reopen it if it happens again.
