### ISSUE TITLE
Auto-format code using prettier?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#3479]
[**prettier**](https://github.com/prettier/prettier) is pretty awesome. Seems pretty trivial to add, but we may want to relax/remove some ESLint rules in order to make it work better w/ linting.

```sh
npm i prettier@latest -D
echo system-addon/vendor > .prettierignore
$(npm bin)/prettier '*.js' '{bin,loaders,system-addon/**}/*.{js,jsm,jsx,json,scss}' --no-bracket-spacing --write
```

We could also use prettier as an ESLint config and/or plugin, or use something like [**prettier-eslint**](https://github.com/prettier/prettier-eslint-cli) instead, which does a `prettier` then `eslint --fix`.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448365
