### ISSUE TITLE
Add telemetry for number of blocked urls

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3482]
Noted from #3477. But generally, the size of blocked affects a number of things such as over-querying from places to later filter out blocked. If this gets big on average (e.g., maybe users block a lot of stories to see more stories), we might run into performance issues. Or worse, the preference size caps out and things might just break in weird ways.

**Comment by piatra** [comment]
[This metric seems to already be collected](https://searchfox.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#1867-1868). Is there anything we would do differently? @emtwo @ncloudioj

**Comment by emtwo** [comment]
It's collected in UT which is hard to cross reference with our PingCentre data. If we want to be able to easily look at block counts side by side with our other telemetry, then this is about adding it in PingCentre. Probably as part of the session ping.

**Comment by piatra** [comment]
We can check the on [number of blocked URLs in UT](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2017-10-10&keys=__none__!__none__!__none__&max_channel_version=nightly%252F58&measure=NEWTAB_PAGE_BLOCKED_SITES_COUNT&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-09-21&table=0&trim=1&use_submission_date=0).

**Comment by ncloudioj** [comment]
I think we can start from using the existing UT metric before adding it to the AS ping. It should be good enough to evaluate the overall impact. We can revisit this later on if necessary.
