### ISSUE TITLE
Articles that begin with a video are wrongly displayed in the "Recommended by Pocket" section

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/activity-stream#3486]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1400211
[Affected versions]:
- Firefox 57.0a1 Build ID 20170913220121

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "browser.search.region" value is set to US. 
- Download the "InnerHTML" .txt document.
[InnerHTML.txt](https://github.com/mozilla/activity-stream/files/1306243/InnerHTML.txt)

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a new tab.
2. Right click one of the "Recommended by Pocket" cards and click the Inspect element option.
3. Press right click on the node containing the website link and and paste the Inner HTML from the downloaded .txt document.
4. Observe how the card is displayed.

[Expected results]:
- The modified card is correctly displayed.

[Actual results]:
- The modified card does not have an image.

[Notes]:
- This issue is reproducible naturally, because the specific article appeared in the "Recommended by pocket" section, as you can see here:
![as -screenshot](https://user-images.githubusercontent.com/31244235/30481195-00bd9dc8-9a26-11e7-89d3-2eac663577c7.png)

- If the specific article (https://www.si.com/tech-media/2017/09/10/media-circus-nfl-opening-weekend-32-thoughts) appears in Highlights, an image is correctly displayed.
- Attached a screen recording of the issue:
![as recommended by pocket](https://user-images.githubusercontent.com/31244235/30480972-1104ceb4-9a25-11e7-9609-62aab7494d06.gif)
- The Full page saved as ".htm" where the issue is reproducible.
[New Tab with broken pocket card.zip](https://github.com/mozilla/activity-stream/files/1306255/New.Tab.with.broken.pocket.card.zip)

**Comment by tspurway** [comment]
working as intended.  Pocket curation process (manual) will avoid this in the future
