### ISSUE TITLE
Localhost things should show in Recent History

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#349]
We seem to be blocking localhost cause we can't get icons from Embedly. That makes sense for now, but when we have our own content scraper we should remember to unblock those types of history items.

**Comment by jaredkerim** [comment]
Embedly is being deprecated in favour of local metadata processing.  A local metadata processor will have access to all the information about a site that the client does, including icons and content, for pages which are only locally accessible such as localhost, VPN content, session based pages, etc.  Therefore we should be able to compute and store such metadata in a way which embedly can not.
