### ISSUE TITLE
Add Edit to context menu for Top Sites

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3490]
Edit should be grouped with Pin (see https://github.com/mozilla/activity-stream/issues/2563). Clicking Edit should take you straight to the edit form for that top site and behave as it would if you entered Edit mode and clicked the edit icon. Clicking Save should take you straight back to New Tab.

**Comment by Mardak** [comment]
If for 57, we'll just reuse `edit_topsites_button_text=Edit` But if it's after 57, we should add a new string.

**Comment by aaronrbenson** [comment]
This would be great for 57 if we can reuse the string.
