### ISSUE TITLE
Pinned Top Sites includes a grey first letter of the title rather than a favicon

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#3493]
Firefox Version: 57.0a1 (2017-09-15) (64-bit)
OS: OSX 10.12.6

Steps to reproduce

1) Click edit on topsites
2) Edit a topsite
3) Type in a name and a url
4) Hit save

Expected results:

A screenshot of the url and its associated favicon appear

Actual results:

A screenshot of the url and a grey box with the first letter you typed in the 'name' box appears

Example:

![screenshot 2017-09-15 11 12 21](https://user-images.githubusercontent.com/119884/30490198-4532a0da-9a07-11e7-9d16-b0f94596631e.png)

**Comment by tspurway** [comment]
has same root as #3494

**Comment by Mardak** [comment]
Actually, probably a separate thing. I believe pinned sites don't know to get a favicon as we aren't fetching it from places.

**Comment by Mardak** [comment]
> We need to make a call to NewTabUtils.activityStreamProvider._addFavicons(pinnedLinks) in order to fetch the rich icons out of the db if they're pinned, but not frecent

With #3530, it'll be easy to cache the results of favicons to avoid querying each time. Although should we block the rest of TopSitesFeed to await the icons for pinned? I suppose we already do for frecent.
