### ISSUE TITLE
Need to implement collapsing or grouping of common URLs in Timeline

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#350]

**Comment by nchapman** [comment]
We need to do this at some point, but we'll need more data (dwell time) than we currently have to do this correctly.

**Comment by sarracini** [comment]
Closing this in favour of tracking in trello https://trello.com/c/6WRXiwEU/32-i-want-to-see-my-activities-clustered-by-site-so-that-i-can-more-easily-see-more-of-the-sites-i-ve-visited
Activity Stream tickets related to this: #609 #722
