### ISSUE TITLE
Favicon and context menu icon show through snippets

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3504]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1401254
![screen shot 2017-09-16 at 6 59 45 am](https://user-images.githubusercontent.com/438537/30512836-db254458-9aac-11e7-9696-8f42a646eb96.png)

It looks like z-index isn't necessary for either to show up correctly? @sarracini did you run into some situation that required it for favicons (bottom right)?

I suppose the context menu (top right) showing on top of snippets might be okay, but the context menu icon (top left) can end up just showing through by itself if it has (keyboard) focus or hover.

**Comment by sarracini** [comment]
I remember having to add a z-index when I was adding the icons in the top left and had them first as ```img``` tags before settling on just a div with a background image. It's totally possible that the z-index got left behind at that time. If it's no longer needed with the bottom right implementation then I can't think of a reason why we can't remove it

**Comment by k88hudson** [comment]
Adding `z-index: 1;` on `snippets-container would probably be enough to fix this

**Comment by Mardak** [comment]
Design says context menu icon and favicon should be below but context menu should be above.
