### ISSUE TITLE
Bad "null" description from British Airways

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3510]
Ha. This is on British Airways' page:
```html
<meta name="description" content="null" />
<meta name="keywords" content="null" />
```
<img width="252" alt="image" src="https://user-images.githubusercontent.com/438537/30516826-92f63f00-9afe-11e7-8b8d-5068aba6d4d2.png">

I suppose there's only so much we can do…

**Comment by sarracini** [comment]
This is definitely a case for #3368 hahaha

**Comment by Mardak** [comment]
I'll try to file some feedback on british airways website. wontfix.

**Comment by Mardak** [comment]
```
Firefox Quantum 57 now shows the description from the page as a Highlight. The logged in Executive Club landing page has a description of "null":

<meta name="description" content="null" />

https://www.britishairways.com/travel/viewaccount/execclub/_gf/en_gb
```

> Thanks for your feedback. At British Airways we pride ourselves on good customer service by reading and working with customer feedback to improve our products.
