### ISSUE TITLE
Flashing of placeholder search text for locales different than English

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3517]
If you load or refresh Activity Stream and the browser language is not english you will see in the search input "Search the web" before switching to the correct locale. On the reference hardware it's especially obvious, stays on screen for a good 1-2s.

**Comment by ItielMaN** [comment]
On RTL builds, the search bar on the activity stream looks like LTR, and a moment later it changes to RTL.
I think this one is a part of this bug.

**Comment by Mardak** [comment]
Fixed by #3740
