### ISSUE TITLE
Add a ping to check the health of initialization

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#3522]
We should add a ping that looks roughly like

let initializedProperly = false;
let errorMessage;

try {
    initailizeActivityStream();
    initalizedProperly = true;
} catch(err) {
   errorMessage = `${err}`;
}

pingCetnre.sendPing({initailizedProperly, errorMessage});

This will help us monitor the health of whether activity stream is initializing properly and debug issues surrounding activity stream clients breaking due to internal errors and then never receiving any telemetry from them, which is happening already in our Shield studies.

**Comment by ncloudioj** [comment]
I think sending a ping when the addon initializes successfully is perhaps undesired here, we can easily infer this from other telemetries, for instance, @emtwo is looking to do [this](https://github.com/mozilla/ping-centre/issues/100), also adding telemetry here sounds pretty risky in terms of performance.

@jaredkerim Did you have special need in this case? I am open to discuss though.

**Comment by ncloudioj** [comment]
Have talked about this with Jared, let's just send a ping to report the init failure for now. The success case could be inferred by other metrics.
