### ISSUE TITLE
Add option to include bookmarks toolbar in new tab page

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3527]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1400650

> It should still be displayed at the top of the new tab page similar to Google Chrome where the bookmarks are either always shown, or only as part of the new tab page. The space at the top of the new tab is empty anyway and could easily hold the bookmarks for easier access.

**Comment by aaronrbenson** [comment]
Tracking as a feature request in Trello: https://trello.com/c/VHh69ffo/159-include-bookmarks-toolbar-in-new-tab-page

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1400650
