### ISSUE TITLE
There is long delay before the about:home page is displayed if it is opened in a new tab

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3531]
https://bugzilla.mozilla.org/show_bug.cgi?id=1401155

[Affected versions]:
- Firefox 57.0a1 Build ID 20170918220054

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to any page.
2. Middle click the Home button.
3. Observe the behavior.

[Expected results]:
- The page content is displayed instantly or marginally the same time it takes to display a new tab.

[Actual results]:
- The page is blank for about a second and then the content appears.

[Notes]:
- The issue is also reproducible if you left click the Home button while on the New Tab page.
- The issue is intermittently reproducible when you open a new window. 
- The issue is not reproducible if you left click the home button while on a page.
- Attached a screen recording of the issue:
![display of homepage is delayed](https://user-images.githubusercontent.com/18304511/30589998-79678a3c-9d45-11e7-92f0-195abbc6bb0f.gif)

**Comment by Mardak** [comment]
The behavior of being able to replace the current tab with activity stream is desired

**Comment by piatra** [comment]
This issue is somewhat old and we've landed quite a few patches related to performance in the meantime. In today's Nightly when I click the home button I instantly get the prerendered version and I don't see the described:
> The page is blank for about a second and then the content appears.

I'm going to ask that this issue should be tested again.

**Comment by SoftVision-CiprianMuresan** [comment]
The behavior has improved, the delay is shorter now, but it's still noticeable.

Middle clicking the home button on Mac: https://goo.gl/SKtGxK
Middle clicking the home button on Windows: https://goo.gl/U9hq1v

I do have to say that I don't see any delay on my old Firefox profile, but I see it every time on a new profile (https://goo.gl/s82tFZ).

**Comment by piatra** [comment]
@k88hudson I've looked into the code that gets triggered when you click the button. It all starts here https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#2145
There's nothing that stands out. When opening AS though the home button does it still benefit from the same preload strategy as `about:newtab` ?

**Comment by Mardak** [comment]
Only about:newtab is preloaded

**Comment by SoftVision-CiprianMuresan** [comment]
I failed to mention in my comment above that the delay I see is on new profiles. If I use an older profile I instantly see the Top Sites and Highlights placeholders.

**Comment by tspurway** [comment]
see also #3367

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1401155
