### ISSUE TITLE
Highlights - Filter out tiles thats related

### ISSUE THREAD

**Issue by punamdahiya** [mozilla/activity-stream#3540]
Repetitive tiles are seen from same visited sites in new tab -> Highlights. The experience can be improved by building intelligence in code to filter out tiles that's related.

[Link to screenshot](https://imgur.com/a/UNT18) from nightly 57.0a1. In this case as a user, 3 tiles suffice.

**Comment by Mardak** [comment]
What build is this? If you go to `about:support`:

**Application Basics**
Build ID 	20170918100059
**Nightly Features**
Activity Stream	2017.09.16.0001-2fc82208	activity-stream@mozilla.org

This should have been fixed by #3398.

**Comment by Mardak** [comment]
Duped to #3390.
