### ISSUE TITLE
Appropriate label required on Edit Top Site dialog

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3553]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1401464

![image](https://user-images.githubusercontent.com/438537/30642384-88fe71a2-9dbf-11e7-80bd-16cd7b3c031b.png)

**Comment by aaronrbenson** [comment]
Updated Top Site modal spec: https://mozilla.invisionapp.com/share/7DEP1VMYX#/266461200_Top_Site_-_Edit_Image_

**Comment by Mardak** [comment]
Screenshot (might become outdated) from the spec:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/438537/33343178-47d1b0a8-d439-11e7-891e-e2e492f2a31f.png">

**Comment by aaronrbenson** [comment]
This will also be resolved as part of #3766

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1401464
