### ISSUE TITLE
Pinned top sites do not have a rich icon if they are not frecent

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3554]
If you pin a top site which *isn't* returned by your getTopSites query, you'll never get a rich favicon for it, even if the site has it. For example, https://www.koodomobile.com/ has loads of apple-touch icons, sure enough they get stored in the favcions db, however because I pinned koodomobile a long time ago and only visit it once in a while, it doesn't get returned as one of my top frecent sites therefore it never has an opportunity to get the rich icon.

We need to make a call  to ```NewTabUtils.activityStreamProvider._addFavicons(pinnedLinks)``` in order to fetch the rich icons out of the db if they're pinned, but not frecent

**Comment by Mardak** [comment]
Dupe #3493
