### ISSUE TITLE
implement remaining about:home load_trigger_type values

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3556]
The most important, "first_window_open", was implemented heuristically in #2658. The rest will probably need to be implemented in a style similar to that for about:newtab described in #3138, and should probably happen after that and #2165 are finished, as they can probably leverage a bunch of the code changes that will happen there.

**Comment by dmose** [comment]
Note that there are, as of this writing, extensive comments in TelemetryFeed.jsm describing some of the cases that will want to be handled.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1425494
