### ISSUE TITLE
Redirects aren't followed/cleanly displayed

### ISSUE THREAD

**Issue by stuartphilp** [mozilla/activity-stream#356]
I have "mail.google.com" bookmarked, when I go to that address it redirects to "https://mail.google.com/mail/". See [1]. This looks a bit confusing, and the bookmark isn't respected in the history view (only the original was starred).

Not sure what a better way to show this relationship would be, @tspurway suggested session grouping might solve this, I also thought a github style branch view [2] might be nice?

[1]
<img width="775" alt="screen shot 2016-03-23 at 3 16 06 pm" src="https://cloud.githubusercontent.com/assets/2964961/13997888/949dcb42-f10a-11e5-8a21-d3fdfb600866.png">

[2]
<img width="500" src="https://guides.github.com/activities/hello-world/branching.png">

**Comment by stuartphilp** [comment]
Probably related, a bookmark of "http://www.reddit.com" redirects to "https://www.reddit.com" and does not show the bookmark star, presumably because the URLs are not exact matches?

<img width="825" alt="screen shot 2016-03-23 at 3 21 59 pm" src="https://cloud.githubusercontent.com/assets/2964961/13998028/3d241460-f10b-11e5-9316-967171203433.png">

**Comment by pdehaan** [comment]
+1, I've seen this on a handful of sites too (reddit.com, etc.)
Not sure if there is a way we can test for "dwell time" so we know how long a user was on a page so we can exclude visits shorter than X seconds.

Here's a bit of fun experimentation:

1. Visit "http://reddit.com".
2. Click the New Tab button to open a new Activity Stream tab. Mouse over the "reddit.com" link and see where it redirects. My "Top Site" link goes to "reddit.com". (See **Figure 1**)
3. Click the Activity Stream timeline button in the toolbar. Mouse over the "reddit" link in the "Just now" section and see where it redirects. My "Just now" link goes to "https://www.reddit.com". (See **Figure 2**)

---

![menubar_and_new_tab_and_redirects_aren_t_followed_cleanly_displayed_ _issue__356_ _mozilla_activity-streams_and_string_prototype_includes___-_javascript___mdn_and_irccloud](https://cloud.githubusercontent.com/assets/557895/14093572/ac497884-f503-11e5-9a02-56f8c0c2ea49.png)
**Figure 1:** Goes to "http://reddit.com" (which is what I typed in address bar).

---

![menubar_and_activity_stream_and_redirects_aren_t_followed_cleanly_displayed_ _issue__356_ _mozilla_activity-streams_and_string_prototype_includes___-_javascript___mdn_and_irccloud](https://cloud.githubusercontent.com/assets/557895/14093595/cf3186fc-f503-11e5-9c12-a427c49f553d.png)
**Figure 2:** Goes to "https://www.reddit.com" (which is the final URL after the browser redirects).

---

**BONUS:** Here's the output from my call to `$ curl -v http://reddit.com` (which returns an HTTP/301 redirect to the HTTPS site):

```
 curl -v http://reddit.com
* Rebuilt URL to: http://reddit.com/
*   Trying 198.41.209.140...
* Connected to reddit.com (198.41.209.140) port 80 (#0)
> GET / HTTP/1.1
> Host: reddit.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Mon, 28 Mar 2016 23:33:42 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=dfa3b34aeafc90f316c8203620d56455c1459208022; expires=Tue, 28-Mar-17 23:33:42 GMT; path=/; domain=.reddit.com; HttpOnly
< Location: https://www.reddit.com/
< X-Content-Type-Options: nosniff
< Server: cloudflare-nginx
< CF-RAY: 28aee37d122d012a-SJC
<
* Connection #0 to host reddit.com left intact
```

**Comment by CosminMuntean** [comment]
After further investigations we encountered the following scenario:

[STR]:
1. Visit Facebook or Twitter websites.
2. Bookmark the visited website.
3. Open Activity Stream Timeline.
4. Click on the "X" button.
5. Click on the "Never show on this page".
6. Refresh Timeline.

[Expected]:
- The website is no longer displayed in Timeline.

[Actual]:
- The website is displayed in Timeline as a non bookmarked website.

[Notes]:
- When visiting Facebook or Twitter websites in History section two entries are displayed for each of them. (eg: http://twitter.com/ and https://twitter.com/) 
- The website that is displayed in Timeline as bookmarked is the one that has the URL with "https". After executing step #6 the "https" website that was blocked is replaced by the one with "http".
- In my opinion as an end user, when I select the "Never show on this page" option for a website from Timeline, the website should no longer be displayed after refresh. This behaviour should happened even if in History there are entries for the same website with "http" and "https".

[https and http URLs.zip](https://github.com/mozilla/activity-streams/files/252575/https.and.http.URLs.zip)

**Comment by jaredkerim** [comment]
Filter URLs from places by referring to 'transition type' to filter out interstitial URLs that result in redirects.

**Comment by oyiptong** [comment]
Here's the list of transition types in places:
http://searchfox.org/mozilla-central/source/__GENERATED__/dist/include/nsINavHistoryService.h#2376

**Comment by sarracini** [comment]
Closing this as recent activity + timeline is no longer around, and there's a new ticket filed to gracefully handle redirect #1388
