### ISSUE TITLE
Section title margin is too tall (again)

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3562]
This was perhaps regressed from some space changes to the Top Sites section. The margin between section headers and the content should be 12px and look like: 

![screen shot 2017-09-20 at 8 41 48 pm](https://user-images.githubusercontent.com/139451/30675131-614df74c-9e44-11e7-9654-09d0a6b31eef.png)

**Comment by aaronrbenson** [comment]
But it can be set to 12px, right?

**Comment by Mardak** [comment]
Nah. It's stuck at 13px! 13!!!! ;)

![screen shot 2017-09-20 at 7 26 49 pm](https://user-images.githubusercontent.com/438537/30676279-1e7041e6-9e3a-11e7-91c1-afcf132a1899.png)

**Comment by aaronrbenson** [comment]
Hahaha! Nice .. that's so much better, thank you Ed!

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/6fe64a79307f
