### ISSUE TITLE
Create a test checking that we don't store mask favicons and don't use rich favicons as the tab icon

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3566]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1401894

As a follow up to the rich icon, so maybe @ncloudioj ?

**Comment by ncloudioj** [comment]
Yes, I can add a test for this.

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/ae2fbd093aac
