### ISSUE TITLE
Use dark background for newtab page when the dark theme is enabled

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3576]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1402312

> As per spec: http://design.firefox.com/people/shorlander/photon/Mockups/macOS.html

> `<dao>` I don't really think this bug makes sense though
`<dao>` the dark theme doesn't affect web content
`<dao>` it's not clear why it should affect the new tab page

**Comment by Mardak** [comment]
> <shorlander> @nhnt11 Yeah, I like it! We should definitely make all our surface areas match the theme.

**Comment by StefanoCecere** [comment]
i think we should just tell the Themes authors to add (for the Dark theme, for example):

```
body.activity-stream {
  background-color: #333333;
}
body.activity-stream .top-sites .title {
  color: #737373;
}
```

it works perfectly.. what do you think?

**Comment by Mardak** [comment]
I'm not sure how the official dark theme works. And if it's different from #3600 ?

**Comment by StefanoCecere** [comment]
i'll talk to the theme team... but do you kno if it's possible to target body.activity-stream just for a local page (ActivityStream addon, in this case?)

**Comment by StefanoCecere** [comment]
i add this: the new Pocket Home page for Chrome (that quites really mimics our Activity Stram)
has the "dark theme" option inside its preferences.
maybe we should try this way?

![screen shot 2017-11-30 at 10 28 28](https://user-images.githubusercontent.com/640536/33423501-4f4b38a0-d5b9-11e7-8894-32b3565c7e54.png)

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1402312
