### ISSUE TITLE
Add an option for customizing rows in New Tab

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3577]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1400536

> Attached is a sample of how the design would be
<img width="362" alt="image" src="https://user-images.githubusercontent.com/438537/30753707-fa78d1d6-9f74-11e7-8fe5-093b2a994ab7.png">

**Comment by ryanbr** [comment]
More/Fewer Rows?, how many rows would the average user need? I thought keeping it simple (2 vs 3 rows) seems easy enough to understand, and anything more could be configurable via about:config
