### ISSUE TITLE
Certain Top Sites do not have the "Edit" and "Remove from History" options when they are pinned

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3593]
https://bugzilla.mozilla.org/show_bug.cgi?id=1402864

[Notes]:
- Only the visited default Top Sites have this behavior; if you manually add or if a different Top Site is populated naturally they will have those options when pinned.

[Affected versions]:
- Firefox 58.0a1 Build ID 20170924220116

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- All of the default Top Sites were visited multiple times so that they appear in the Top Sites section. 

[Steps to reproduce]:
1. Open the browser and navigate to about:newtab.
2. Pin one of the default Top Sites (eg. youtube).
3. Click the "..." button for the pinned Top Site.
4. Observe the context menu options. 

[Expected results]:
- "Unpin", "Edit", "Open in a New Window", "Open in a New Private Window", "Dismiss", "Remove from History" options are displayed.

[Actual results]:
- "Edit" and "Remove from History" options are not displayed. 

[Additional notes]:
- Attached a screen recording of the issue:
![different context menu for pinned visited default top sites](https://user-images.githubusercontent.com/18304511/30813424-161dcdc6-a216-11e7-8ff5-4a9a392ee89c.gif)

**Comment by Mardak** [comment]
#2823 refactored the link menu to have separate arrays of options for default vs not-default. #3490 added the edit context menu. Looks like a frecent item gains the default status when pinned. Probably a couple bugs:
1) default sites should be editable
2) a pinned site that happens to be default should probably keep its usual context menu?

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1402864
