### ISSUE TITLE
Unpinning an edited Top Site wrongly renames that Top Site

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3594]
https://bugzilla.mozilla.org/show_bug.cgi?id=1402863

[Affected versions]:
- Firefox 58.0a1 Build ID 20170924220116

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to about:newtab.
2. Edit the title of a Top Site (eg. youtube -> YouTube)
3. Unpin the Top Site and observe its name.

[Expected results]:
- The Top Site is unpinned.

[Actual results]:
- The Top Site is unpinned, but it is also renamed to what it was called before the edit was made.

[Regression Window]:
Last good revision: 50d08bf45f3df9a5eacfc4531aafd85fd32875fd
First bad revision: 40b3b10f78c2d5a72356d21532add0848fc928b2
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=50d08bf45f3df9a5eacfc4531aafd85fd32875fd&tochange=40b3b10f78c2d5a72356d21532add0848fc928b2

[Notes]:
- Attached a screen recording of the issue:
![unpinned top sites renamed](https://user-images.githubusercontent.com/18304511/30813463-2ea90900-a216-11e7-8ec5-c501118f57a8.gif)

**Comment by PhillypHenning** [comment]
Hey, I would like to take this bug and could we throw the hacktober label on this as well!

**Comment by k88hudson** [comment]
@PhillypHenning hey, what do you mean by hacktober label?

**Comment by Mardak** [comment]
Design says this is wontfix as unpinning makes it no longer custom top site, and having it revert to default naming makes it clearer it's a natural top site.
