### ISSUE TITLE
Code clean up and "Preferred Way of Coding" Declarations

### ISSUE THREAD

**Issue by mzhilyaev** [mozilla/activity-stream#360]
Burnt by blindly copy-pasting tests around and getting "nit" fixes from @oyiptong I am finally creating a bug to at least summarize code idioms that  Olivier consistently makes me to fix:
1.  Make Observer object into an Observer function

We have a lot of this, through out our test code

```
    let Observer = {
      observe: function(subject, topic, data) {
      }
    };
   Services.obs.addObserver(Observer, "some-event");
```

This could be replaced with:

```
function observeThatEvent(subject, topic, data) {...}
Services.obs.addObserver(observeThatEvent, "some-event");
```
1.   Serialization of data objects in notifications

We often do that

```
let foo = {x: 1, y:2 , z:3};
Services.obs.notifyObservers(null, "foo-happened", JSON.stringify(foo));
.....
function onFooEvent(subject, topic, data) {
   let foo = JSON.parse(data);
}
```

If we want objects passed with notification immutable, then perhaps we can use Object.freeze() to avoid serialization cost

**Comment by sarracini** [comment]
Closing this
