### ISSUE TITLE
Show top sites when they're all visually ready

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3607]
Ehsan suggests that because parts of top sites load later, e.g., screenshots, it feels like a webpage instead of part of the browser.

Design has said that showing placeholders and fading in new content is preferred.

**Comment by aaronrbenson** [comment]
Yeah, I still contend that progressive loading is the way to go because it has better perceived performance.

**Comment by Mardak** [comment]
Wontfix per previous comment.
