### ISSUE TITLE
Bookmark highlights are deduped against top sites

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3608]
Should bookmark highlights be removed if it's also a top site? This only really happens for people with small histories who happens to have a visited bookmarked article as a top site.

**Comment by Mardak** [comment]
Design says bookmarks should always show up.

**Comment by Mardak** [comment]
@piatra why was this `compare` logic added? The original function isn't really documented on what the expected behavior should be, and this test looks wrong:
https://github.com/mozilla/activity-stream/blob/444feabd2e98ed585d7ba97119e6005c34e00b70/system-addon/test/unit/common/Dedupe.test.js#L30-L36
The `compare` function in this test seems to say prefer a current item that has an amount that is greater than the previous one. So I would have expected the afterItems to be
```js
[
  [],
  [{id: 1, amount: 200}, {id: 2, {amount: 100}]
]
```

However, that would require removing an item from an earlier group, which would probably add a bit of complexity.

For this current issue, I would want to have a `compare` function that just says to keep a potentially deduped item if it's a "bookmark". However, the existing `group` code only calls `compare` if `globalKeys` doesn't already have a key. But then again, if we allow for duplicate keys, then it's unclear which `previous` item we should compare against.

Should I just remove the `compare` functionality and replace it with a `shouldKeep` as nothing is using `compare` outside of tests?

Alternatively, we should just not use `Dedupe` as it doesn't really do what we want for Highlights?

Or another alternative that seems a bit hacky: have `dedupeKey` return something unique / not-dedupable for "bookmark"s.

**Comment by piatra** [comment]
@Mardak most of that was just copied over from @k88hudson 's `fancy-dedupe` https://github.com/k88hudson/fancy-dedupe/blob/master/test/index.test.js
