### ISSUE TITLE
[Intermittent] A small number of new profiles wrongly turn off Activity Stream in Beta

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3613]
https://bugzilla.mozilla.org/show_bug.cgi?id=1403573

[Notes]:
- The issue is very intermittent, but I can manage to reproduce it at least on one profile out of ~15.
- Activity Stream appears to be turned off in about:config after you reproduce the issue.

[Affected versions]:
- Firefox 56.0b3 Build ID 20170925150345

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Create a new Firefox profile and open the browser.
2. Open a New Tab.
3. Click the Search arrow button.
4. Open a few more tabs (~6) and observe the behavior.
 
[Expected results]:
- Activity Stream is displayed on all opened new tabs.

[Actual results]:
- The last tab opened has the old New Tab page.

[Additional notes]:
- No errors appear in the Browser Console.
- I haven't managed to reproduce the issue on Nightly.
- Attached a screen recording of the issue:
![activity stream disabling itself](https://user-images.githubusercontent.com/18304511/30919123-336666d8-a3a9-11e7-9a78-0cbf0785e526.gif)

**Comment by jaredkerim** [comment]
Can you please change this pref:

extensions.shield-recipe-client.logging.level 

to this value:

0

And then recreate these steps, open up the browser console: cmd + shift + j

and copy paste all the output into a gist.

**Comment by jaredkerim** [comment]
Also when you reproduced this in 57b3 did you reuse the same profile from 56 or create a new one?

**Comment by SoftVision-CiprianMuresan** [comment]
> Also when you reproduced this in 57b3 did you reuse the same profile from 56 or create a new one?

No, all of the profiles I used were newly created profiles.
I'll try the same scenario with that pref set tomorrow though.

**Comment by jaredkerim** [comment]
Ah, found it.  There is an active Shield experiment which will disable Activity Stream for some users.  We are disabling it now and this behaviour should correct itself.

**Comment by Mardak** [comment]
@jaredkerim did that shield study get disabled? In some bug or somewhere to link to and track?
