### ISSUE TITLE
Provide an icon for the confirm dialog 

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#3615]
In the confirm dialog for deleting history we should add an icon to show what the action is intending to do.

**Comment by Mardak** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/438537/31735581-38c5fd7e-b3f7-11e7-8e79-938691adc5ed.png">

**Comment by aaronrbenson** [comment]
Specs for the new layout are here: https://mozilla.invisionapp.com/share/59E45AXDJ#/238928525_Photon_-_Confirm_Dialog

**Comment by Mardak** [comment]
Do we reuse the devtools clear / trash icon?

<img width="60" alt="image" src="https://user-images.githubusercontent.com/438537/31961696-5b2feb46-b8b0-11e7-9c1c-cb2ec5b1dff5.png">

chrome://devtools/skin/images/clear.svg
https://searchfox.org/mozilla-central/source/devtools/client/themes/images/clear.svg

**Comment by Mardak** [comment]
@bryanbell will provide a svg that should be able to accept css-specified colors/opacities, e.g., 
```css
{
  -moz-context-properties: fill, fill-opacity;
  fill-opacity: 0.2;
  fill: #0c0c0d;
}
```

**Comment by bryanbell** [comment]
The delete icon needed. 

[delete-32.svg.zip](https://github.com/mozilla/activity-stream/files/1416519/delete-32.svg.zip)

**Comment by Mardak** [comment]
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"><g fill="context-fill"><path d="M11.5 11a.5.5 0 0 0-.5.5v12a.5.5 0 0 0 1 0v-12a.5.5 0 0 0-.5-.5zm4 0a.5.5 0 0 0-.5.5v12a.5.5 0 0 0 1 0v-12a.5.5 0 0 0-.5-.5zm4 0a.5.5 0 0 0-.5.5v12a.5.5 0 0 0 1 0v-12a.5.5 0 0 0-.5-.5z"/><path d="M27 5h-6.6a5 5 0 0 0-9.8 0H4a1 1 0 0 0 0 2h1v20a4 4 0 0 0 4 4h13a4 4 0 0 0 4-4V7h1a1 1 0 0 0 0-2zM15.5 2a4 4 0 0 1 3.86 3h-7.72a4 4 0 0 1 3.86-3zM24 27a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2V7h17z"/><path d="M7.04 7h16.92a.04.04 0 0 1 .04.04V28a1 1 0 0 1-1 1H8a1 1 0 0 1-1-1V7.04A.04.04 0 0 1 7.04 7z" opacity=".2"/></g></svg>
```
