### ISSUE TITLE
should log as MIGRATION_ENTRYPOINT_HOME when migration wizard is triggered from about:home

### ISSUE THREAD

**Issue by gasolin** [mozilla/activity-stream#3619]
currently migrationWizard is triggered and log the entry point as `MIGRATION_ENTRYPOINT_NEWTAB`
 https://github.com/mozilla/activity-stream/blob/master/system-addon/lib/ManualMigration.jsm#L88

But now AS can also show on about:home, so to collect the accurate telemetry, we can add `MIGRATION_ENTRYPOINT_HOME` in 
http://searchfox.org/mozilla-central/source/browser/components/migration/MigrationUtils.jsm#1113 and log proper entrypoint according to the current tab.

This task is just for collect the accurate telemetry, not effect any user interactions.

**Comment by Mardak** [comment]
The two about: pages are treated the same
