### ISSUE TITLE
The context menu is not dismissed when a tile is dragged

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3624]
https://bugzilla.mozilla.org/show_bug.cgi?id=1403947

[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the browser and open a New Tab.
2. Click the context menu button for one of the tiles.
3. Drag a different tile and observe the context menu.
 
[Expected results]:
- The context menu is dismissed.

[Actual results]:
- The context menu stays in its place.

[Notes]:
- Attached a screen recording of the issue:
![context menu not dismissed](https://user-images.githubusercontent.com/18304511/30972789-43b48bca-a474-11e7-82e5-58c5a8ea88be.gif)

**Comment by tspurway** [comment]
related to #3137

**Comment by kunal12422** [comment]
Hi all, can I work on this issue?

**Comment by k88hudson** [comment]
Sure @kunal12422, let us know if you have any questions! @rlr might be a good person to help out since he is working on other drag-and-drop related bugs.

**Comment by SeanPrashad** [comment]
Hi @k88hudson - I was wondering if I could tackle this bug as part of my Open Source course with [David Humphrey](http://blog.humphd.org/)? I saw @kunal12422 wished to start on it and would love to help if it's possible! 😁

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1403947
