### ISSUE TITLE
Chore: Don't create a new state obj if there's nothing to change

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3627]
Followup to pull request https://github.com/mozilla/activity-stream/pull/3623 [Don't create a new state object](https://github.com/mozilla/activity-stream/pull/3623/files#diff-c74cab3ab6b305a830716d4e622105a6R250) if there is nothing to dedupe.

**Comment by jenn-chaulk** [comment]
Removing P2 label just so this get's triaged.

**Comment by piatra** [comment]
Decision is to keep this in mind as we modify different Reducers.
