### ISSUE TITLE
Bookmarked status for Highlights is only shown after you click the context menu a second time

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3629]
https://bugzilla.mozilla.org/show_bug.cgi?id=1404261

[Affected versions]:
- Firefox 58.0a1 Build ID 20170928220658

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have enough history so that Highlights are displayed.

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Click the "..." for one of the Highlights.
3. Click the "Bookmark" option and observe the bottom left corner of the card.

[Expected results]:
- The status of the card is changed to "Bookmarked"

[Actual results]:
- The status of the card remains unchanged.

[Regression window]:
Last good revision: d7ccda988869be632fb6b3345d3efba111db7f7d
First bad revision: 3b514f20525296a9b6a623ba680fb027bc9e6cae
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=d7ccda988869be632fb6b3345d3efba111db7f7d&tochange=3b514f20525296a9b6a623ba680fb027bc9e6cae

[Notes]:
- Dismissing a different Highlight will refresh the affected card and it will correctly show its status.
- The status is correctly displayed after the page is refreshed.
- Attached a screen recording of the issue:
![bookmark state for highlights not displayed instantly](https://user-images.githubusercontent.com/18304511/31009721-1ff087fa-a511-11e7-9158-28f6f08b4b54.gif)

**Comment by Mardak** [comment]
Should be fixed by #3623 I believe

**Comment by piatra** [comment]
I can confirm this bug is fixed.
