### ISSUE TITLE
Edit top sites "Done" button is displayed outside the parent window on narrow windows

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3630]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1404374

<img width="435" alt="image" src="https://user-images.githubusercontent.com/438537/31038482-0e0a65cc-a545-11e7-8468-ddfd6081b282.png">

**Comment by Mardak** [comment]
Move the Done button to a new line

**Comment by piatra** [comment]
Seems to be similar to the rest of the "min width bugs" submitted https://github.com/mozilla/activity-stream/issues/3749#issuecomment-339401334 which we chose not to fix.
