### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3632]
We should probably hold off on this until we're sure we're done uplifting to 57,  but it would be awesome to get this in for 58

**Comment by dmose** [comment]
I'm guessing we're not yet done with uplifting, but as I understand it, there are unlikely to be many more uplifts.

@k88hudson Why wait?  So that changes to master are easier to port to the branch?

That said, I can start the work locally.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421441
