### ISSUE TITLE
 The Tiles context menu button "(...)" slightly overlaps the Section info symbol "(?)" on Windows

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3634]
https://bugzilla.mozilla.org/show_bug.cgi?id=1405296

[Affected versions]:
- Firefox 58.0a1 Build ID 20171003100226

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Start the browser and open a New Tab.
2. Hover the last tile in the Top Sites section.
3. Observe the context menu button.
 
[Expected results]:
- The context menu button does not overlap any other button.

[Actual results]:
- The context menu button slightly overlaps the section info button.

[Notes]:
- The issue is also reproducible if you hover the 3rd Top Story or the 3rd Highlight tile.
- The issue is not reproducible on Mac or Linux. 
- Attached a screen shot of the issue:
![context menu overlaps the info button](https://user-images.githubusercontent.com/18304511/31129827-62d40254-a85e-11e7-996b-c6892999580f.png)

**Comment by Mardak** [comment]
Design says use 16px as the 12px from #3562 is too small and causes problems for the arrow for #3631.

![pasted image at 2017_10_03 11_16 am](https://user-images.githubusercontent.com/438537/31141582-a7b6b95c-a82c-11e7-94da-a799500e8ca0.png)

**Comment by IuliaCristescu4** [comment]
This issue is affecting the Firefox 57 build. I strongly recommend uplifting this fix in 57, too, before the merge. This will improve the feature's UX.

**Comment by Mardak** [comment]
The fix here was part of a more complex change, but we could possibly just increase the spacing to avoid the overlap for 57.
