### ISSUE TITLE
 Info hint message is not properly dismissed after moving the mouse away from it

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3635]
https://bugzilla.mozilla.org/show_bug.cgi?id=1405300

[Affected versions]:
- Firefox 58.0a1 Build ID 20171003100226

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the browser and open a New Tab.
2. Hover the (?) symbol from either section.
3. Move the mouse over the hint message.
4. Quickly move the mouse away from the message and then back to it.
5. Observe the behavior.
 
[Expected results]:
- The info message is not displayed.

[Actual results]:
- The info message reappears.

[Notes]:
- Attached a screen recording of the issue:
![info panel is not dismissed quickly enough](https://user-images.githubusercontent.com/18304511/31129867-80f26b90-a85e-11e7-8b90-98f21e51e779.gif)

**Comment by Mardak** [comment]
Probably can just fix this with `pointer-events: none` when it's `:not([aria-expanded="true"])` so that when it's fading away, it won't detect hover unless hover is on the icon.
