### ISSUE TITLE
 Grey placeholders are no longer displayed after importing History

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3636]
https://bugzilla.mozilla.org/show_bug.cgi?id=1405324

[Affected versions]:
- Firefox 58.0a1 Build ID 20171003100226

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Create a new profile and start the browser with it.
2. Import History from another browser.
3. Observe the Highlights section.
 
[Expected results]:
- Placeholder images are displayed on the imported Highlights.

[Actual results]:
- Placeholder images are no longer displayed.

[Regression Window]:
Last good revision: 8ce27eeef7662c04deed1328ff25937e530aaf79
First bad revision: e3221268f8fc67bd461c2e04ed486e264c070abf
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=8ce27eeef7662c04deed1328ff25937e530aaf79&tochange=e3221268f8fc67bd461c2e04ed486e264c070abf

[Notes]:
- Attached a screen recording of the issue:
![place holders no longer diplayed in nightly](https://user-images.githubusercontent.com/18304511/31129916-9d2e272c-a85e-11e7-9e0b-886576e5dadc.gif)

**Comment by Mardak** [comment]
This is by design now that highlights will use a screenshot if there's no preview image. There were perceived performance concerns of showing the dark placeholder then switching to an image.
