### ISSUE TITLE
There should not be double scrollbars when the Preferences Pane is open

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3639]
Currently, two scrollbars show up when the Preferences Pane is open. The correct behavior should be that the outer element should not be scrollable while the Preferences Pane is open, and it should be scrollable again when the pane closes.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1455535/31138956-213c70ee-a83e-11e7-8716-5225c0a6fe66.png">

**Comment by mmBabol** [comment]
Hello there! Could I take this bug?

**Comment by humphd** [comment]
@k88hudson ok if my student @mmBabol works on this?  Can you assign it to him?

**Comment by k88hudson** [comment]
Hey @mmBabol, absolutely! Let me know if you need help setting up the development environment or you have any questions 👍

**Comment by k88hudson** [comment]
@mmBabol this is the file you will need to be looking at for the preference pane:

https://github.com/mozilla/activity-stream/blob/master/system-addon/content-src/components/PreferencesPane/PreferencesPane.jsx

**Comment by k88hudson** [comment]
@mmBabol were you able to get set up ok?

**Comment by mmBabol** [comment]
Hi @k88hudson, just working on it now, sorry for the delay. Will let you know how it goes :)

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421440

**Comment by mmBabol** [comment]
Hi @Mardak , I fixed the problem. Do I create a new Pull Request and close the old one? I'm not sure what is the process right now.

**Comment by Mardak** [comment]
I've updated the assignee in bugzilla (we're in the middle of trying to track current issues in bugzilla). Did I assign to the right person? https://bugzilla.mozilla.org/show_bug.cgi?id=1421440

**Comment by Mardak** [comment]
The PR has your updated commit, so it's fine. You can run tests locally with "npm test" and see the failure. Looks like eslint doesn't like the indentation:
>  ✖  69:7  Expected indentation of 4 spaces but found 6  indent-legacy
>  ✖  71:7  Expected indentation of 4 spaces but found 6  indent-legacy

**Comment by mmBabol** [comment]
Okay fixed now, all checks passed. Thanks again for your help @Mardak
