### ISSUE TITLE
Be smarter about when to expire thumbnails (especially for Highlights)

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3646]
Right now thumbnails are expired based on other thumbnail user's logic:
https://searchfox.org/mozilla-central/search?q=filterForThumbnailExpiration

This means Highlights most likely are being thrown out of the cache pretty regularly whereas Top Sites might happen to work because they generally show the same thing as Tiles.

**Comment by piatra** [comment]
We could [register a new expiration filter for ActivityStreamLinks](https://searchfox.org/mozilla-central/rev/31606bbabc50b08895d843b9f5f3da938ccdfbbf/toolkit/modules/NewTabUtils.jsm#1923) but we would need to move the logic to dedupe by hostname from HighlightsFeed to ActivityStreamLinks.getHighlights.

**Comment by Mardak** [comment]
Why couldn't HighlightsFeed register?

**Comment by Mardak** [comment]
When testing #3695 I noticed some top sites queries happening on a delay:
```
getTopSites@resource://gre/modules/NewTabUtils.jsm:1348:37
async*getTopSiteURLs@chrome://browser/content/browser-thumbnails.js:217:19
async*get@resource://gre/modules/XPCOMUtils.jsm:199:21
_capture@chrome://browser/content/browser-thumbnails.js:149:11
async*idleCallback@chrome://browser/content/browser-thumbnails.js:169:7
requestIdleCallback handler*Thumbnails_delayedCapture/timeoutId<@chrome://browser/content/browser-thumbnails.js:175:28
setTimeout handler*Thumbnails_delayedCapture@chrome://browser/content/browser-thumbnails.js:174:21
Thumbnails_onStateChange@chrome://browser/content/browser-thumbnails.js:144:7
callListeners@chrome://browser/content/tabbrowser.xml:483:24
_callProgressListeners@chrome://browser/content/tabbrowser.xml:504:13
_callProgressListeners@chrome://browser/content/tabbrowser.xml:586:22
onStateChange@chrome://browser/content/tabbrowser.xml:838:15
_callProgressListeners@resource://gre/modules/RemoteWebProgress.jsm:179:11
receiveMessage@resource://gre/modules/RemoteWebProgress.jsm:244:7
```

I believe this query is purely for use by the thumbnail expiration logic:
https://searchfox.org/mozilla-central/source/browser/base/content/browser-thumbnails.js#132-135

Similar to having HighlightsFeed register expiration behavior, TopSitesFeed should probably register instead of having NewTabUtils.

**Comment by piatra** [comment]
Should we only remove the `activity-stream-enabled` case? https://searchfox.org/mozilla-central/source/browser/base/content/browser-thumbnails.js#217 as it looks like the expiration logic there also handles Tiles.
