### ISSUE TITLE
Update strings for info doorhanger

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3647]
https://mozilla.invisionapp.com/share/TUDPTAH8E#/screens
<img width="351" alt="image" src="https://user-images.githubusercontent.com/438537/31158594-93edb5f6-a877-11e7-9189-a5a041fc18b9.png">

There's strings in the design, but some seem to be outdated or similar but not quite.

In particular we replaced the old pocket string for 57:
```diff
 -pocket_feedback_body=Pocket, a part of the Mozilla family, will help connect you to high-quality content that you may not have found otherwise. 
 +pocket_description=Discover high-quality content you might otherwise miss, with help from Pocket, now part of Mozilla. 
```
https://github.com/mozilla/activity-stream/pull/3274/files#diff-906742e1af7418eb557312dc9217f2f1L141

It seems quite silly that we're having localizers translate it again.

**Comment by aaronrbenson** [comment]
Also see: https://trello.com/c/88gP8dJK/168-write-final-copy-for-section-explanation-cards

**Comment by aaronrbenson** [comment]
Will follow up with Michelle about these.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421439
