### ISSUE TITLE
Verify links get prefetched (on mousedown)

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3649]
This might already happen with `network.http.speculative-parallel-limit` so might just need to confirm that and close this issue.

**Comment by piatra** [comment]
I can confirm this using Wireshark: mousedown events trigger connections to that link.
Here is a comment confirming this behavior https://bugzilla.mozilla.org/show_bug.cgi?id=1363772#c1
Do we want to close this (it's mousedown not hover as the title says)?
