### ISSUE TITLE
Fix flash of untranslated content on Activity Stream search bar

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3655]
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1406096

**Comment by Mardak** [comment]
firefox-57 branch: https://github.com/mozilla/activity-stream/commit/5420afb0f0dc744430ab1dc4972271be7138419b

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/3fecc15c4d29
