### ISSUE TITLE
Set ping centre endpoint to different value in integration tests

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#3659]
I noticed a bunch of pings in the ping_centre_main table in Redash. However, the change to send data to production is not out yet. So Nan and I suspect that these are tests running in travis that startup the browser and thus trigger this ping being sent.

Any integration tests that startup the browser should set `browser.ping-centre.production.endpoint` pref to the staging endpoint or localhost

**Comment by ncloudioj** [comment]
@emtwo Let's move this issue to the ping-centre repo, since all ping-centre users could face the same issue.
