### ISSUE TITLE
No favicon being picked up for theguardian.com

### ISSUE THREAD

**Issue by AdamHillier** [mozilla/activity-stream#3664]
I've noticed for a few weeks that one of my top sites doesn't get the bottom-right favicon. On up-to-date nightly, I get this:
<img width="120" alt="screen shot 2017-10-06 at 8 48 41 pm" src="https://user-images.githubusercontent.com/7688302/31295788-c9690d4a-aad7-11e7-9dab-d32ecab24a33.png">

The site's `<head>` seems to be full of [icons](https://assets.guim.co.uk/images/favicons/451963ac2e23633472bf48e2856d3f04/152x152.png) (apple-touch and otherwise) and has a [web manifest](https://www.theguardian.com/2015-06-24-manifest.json) (though I don't know if we're doing anything with web manifests yet) so there should be something better there instead.

I can replicate on new profiles as well.

**Comment by AdamHillier** [comment]
Having said that, I now have ended up getting the favicon on some profiles (but not all). It remains the case that the screenshot + 32x32 favicon is being used instead of the 152x152 rich icon that's (also) included in the head.

**Comment by Mardak** [comment]
I think it's because it redirects? What's the url of the top site and what's the page you end up on?

**Comment by Mardak** [comment]
On a clean profile just typing in `theguardian` cmd-enter `favicons.sqlite`:
```
11|https://assets.guim.co.uk/images/favicons/451963ac2e23633472bf48e2856d3f04/152x152.png|92469486|144|0||1507930809570|?PNG
12|https://assets.guim.co.uk/images/favicons/79d7ab5a729562cebca9c6a13c324f0e/32x32.ico|4194250496|16|0||1507930809573|?PNG
13|https://assets.guim.co.uk/images/favicons/79d7ab5a729562cebca9c6a13c324f0e/32x32.ico|4194250496|32|0||1507930809573|?PNG
```

`places.sqlite`:
```
13|http://www.theguardian.com/||moc.naidraugeht.www.|1|0|1|2000|1507326008126064|m-X051nfJSaV|0|125507729784227||
14|https://www.theguardian.com/||moc.naidraugeht.www.|1|1|0|25|1507326008251285|OjGzQ-fupD3u|0|47359000463121||
15|https://www.theguardian.com/us|News, sport and opinion from the Guardian's US edition | The Guardian|moc.naidraugeht.www.|1|0|0|50|1507326008294301|G6qc44btgCNd|0|47358579219806|Latest US news, world news, sports, business, opinion, analysis and reviews from the Guardian, the world's leading liberal voice|https://assets.guim.co.uk/images/2170b16eb045a34f8c79761b203627b4/fallback-logo.png
```

The top site ends up being the first places entry: `http://www.theguardian.com/` with the 2000 frecency.

**Comment by AdamHillier** [comment]
You're right, the page it redirects to is https://www.theguardian.com/uk (for me) and the top site is the domain root

**Comment by AdamHillier** [comment]
<img width="128" alt="screen shot 2017-10-06 at 10 54 16 pm" src="https://user-images.githubusercontent.com/7688302/31300010-55b5e104-aae9-11e7-8039-b9ffc7110ef0.png">
And when I manually pin the `/uk` domain it has the much nicer, expected result

**Comment by Mardak** [comment]
Ha. It looks like the favicon service does save the default root `/favicon.ico` if you load a page that **doesn't** have any icon metadata. However, all normal theguardian pages have that metadata. However, if you go to some 404 page, e.g., https://www.theguardian.com/asdf it should cause Firefox to save that default icon, and it'll be used for the top site. ;)

**Comment by AdamHillier** [comment]
Also noticed it with `outlook.com`: 
<img width="129" alt="screen shot 2017-10-14 at 10 24 32 am" src="https://user-images.githubusercontent.com/7688302/31574563-2f71e196-b0ca-11e7-8ff8-a5b23f4107a9.png">
I would guess for the same reason - `outlook.com` redirects to `outlook.live.com/mail`

**Comment by Mardak** [comment]
Hrmmm outlook is an interesting situation as it's on different domains. A possible fix I was thinking of would be to look for favicons used elsewhere on the same domain, but for outlook, using the favicon of the redirect target for the source seems less okay. E.g., somehow you had a google search result that redirects to yahoo -> do we show the yahoo icon for a google url?

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421428
