### ISSUE TITLE
A few specific websites do not load a "Highlight" image

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/activity-stream#3668]
https://bugzilla.mozilla.org/show_bug.cgi?id=1406917

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a profile with enough history that all the "Top Sites" are populated.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Navigate to https://mibbit.com/?server=irc.mozilla.org&channel=%23nightly.
3. Add the website to the bookmarks.
4. Observe the "Highlight" card of the previously bookmarked page.

**[Expected result]:**
- After a short while, a screenshot is displayed in the card.

**[Actual result]:**
- No image is displayed.

**[Notes]:**
- The issue is also reproducible with PDFs and images from google drive (e.g. https://drive.google.com/file/d/0B4PpDEhzmb-7QTVrNy1HTkgyRkE/view ). However sometimes the screenshot related to a PDF is displayed in the "Highlight" card after a long while or after a restart.
- Attached a screenshot of the issue:
![ss of the issue](https://user-images.githubusercontent.com/31243259/31341043-d4236704-ad10-11e7-965f-4fe9c2a2f2c1.png)

**Comment by Mardak** [comment]
Probably similar to the causes of #3509

Specifically for `https://client01.chat.mibbit.com/?server=irc.mozilla.org&channel=%23nightly` I see
getScreenshot error: Error: page-thumbnail:error

But `https://mibbit.com/?server=irc.mozilla.org&channel=%23nightly` (a default bookmark in nightly) gets its screenshot okay.

**Comment by Mardak** [comment]
Design says to fall back to the no-image card state, but try not to have content shift around. (So potentially for a visible card, don't update it, but maybe a prerendered or switched-away tab could update, and definitely for new tabs would have the image-less version if we already know there's no thumbnail.)

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1406917
