### ISSUE TITLE
"Edit" and "?" should be hidden when sections are collapsed

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3671]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1406928

[Expected results]:
- Nothing is displayed.

[Actual results]:
- The "Edit" and "?" buttons are displayed.

![img_09102017_170327_0](https://user-images.githubusercontent.com/18304511/31374382-638de0be-ada6-11e7-9edb-1dbb40f7e303.png)

**Comment by rlr** [comment]
Easy fix is ready if we decide to do: https://github.com/mozilla/activity-stream/compare/master...rlr:gh3671/collapsed-no-hover

**Comment by Mardak** [comment]
Could do both styles as `:not(.collapsed)` to set `opacity: 1` and you get a nice fade when collapsing too. ;)

**Comment by aaronrbenson** [comment]
Sounds good to me.
