### ISSUE TITLE
Increase settle time to let pages to finish loading before screenshotting

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3672]
Split from #3509:

mint and schwab screenshot an all white section (maybe still loading?):
<img width="128" alt="image" src="https://user-images.githubusercontent.com/438537/30516675-58cef4b0-9afa-11e7-8c32-9c6d4d7d3804.png">
https://mint.intuit.com/overview.event
<img width="130" alt="image" src="https://user-images.githubusercontent.com/438537/30516764-45fb22a2-9afd-11e7-821b-df75cee307df.png">
https://www.schwab.com/

nve.ecofactor screenshots loading spinner:
<img width="129" alt="image" src="https://user-images.githubusercontent.com/438537/30516684-c3bd0258-9afa-11e7-97fe-e8526f82fca8.png">
https://nve.ecofactor.com/

**Comment by shikhar-scs** [comment]
@Mardak If this issue is still up, can I please work on it ? (If yes) could you also guide me on where to change this `settling time`

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432322
