### ISSUE TITLE
Capture loaded page instead of relying on background screenshot

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3673]
Split from #3509:

If we use the loaded logged-in browser of a tab to capture the screenshot, it would avoid the cookie-less screenshots from the background thumbnailer.

britishairways screenshots the language prompt overlay (probably can't do much here):
<img width="121" alt="image" src="https://user-images.githubusercontent.com/438537/30516687-f1fbc9e2-9afa-11e7-87ad-70ddb47c5a37.png">
https://www.britishairways.com/en-gb/executive-club/spending-avios/reward-flights

various google (mail, docs) have login (probably can't do much here):
<img width="126" alt="image" src="https://user-images.githubusercontent.com/438537/30516693-169970d8-9afb-11e7-97bb-95690f6fb10b.png">
https://mail.google.com/
https://docs.google.com/

**Comment by sarracini** [comment]
bug ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1413650
landed in autoland: https://hg.mozilla.org/integration/autoland/rev/0f9f5ef2c141

I'll just close it if it gets backed out we can re-open if we care to track it
