### ISSUE TITLE
Test Pilot users with activity stream set to start page get broken start page after self destruct

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3674]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1413207
Doh. Not sure what we can do about this or how widespread the issue. @emtwo ? Or how we should go about fixing it…

The Test Pilot version set the homepage pref to something like `resource://activity-streams/data/content/activity-streams.html#/`:
https://github.com/mozilla/activity-stream/blob/5779a88eef785d058f0eff6267ad28691332dcef/addon/ActivityStreams.js#L385-L394

Should have cleared that pref (and any other prefs) when self destructing. @ncloudioj 

We could try to uplift something to Firefox 57 to detect and clear that pref.

Alternatively, maybe a shield "study" that targets uses with that pref, and just resets that pref to `about:home` ? @jaredkerim

**Comment by nchapman** [comment]
> Alternatively, maybe a shield "study" that targets uses with that pref, and just resets that pref to about:home ? @jaredkerim

Yeah this seems like a pretty smart approach to clean this up. @jaredkerim how difficult would this be?
