### ISSUE TITLE
"Top Sites" disappear or moved to different position after they are unpinned

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/activity-stream#3676]
https://bugzilla.mozilla.org/show_bug.cgi?id=1407172

**[Notes]:**
- The issue is not reproducible if you import history from another browser.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- On a new profile sign in to sync with an account that has enough history and bookmarks to populate the "Top Sites" area.

**[Steps to reproduce]:**
1. Open the browser with the profiles from prerequisites.
2. Pin a Top Site and open it in multiple new tabs.
3. Restart the browser.
4. Unpin the Top Site pinned at step 2 and observe its behavior.

**[Expected result]:**
- The Top Site stays in the same place.

**[Actual result]:**
- The Top Site disappears or it is moved towards the back in the "Top Sites" area.

**[Additional Notes]:**
- Screen recording of the issue: https://goo.gl/AV7fsQ.

**Comment by piatra** [comment]
When we pin/unpin a Topsite we query for Topsites and they might have changed their frecency score (doesn't explain why in this example the topsite disappeared).

**Comment by aaronrbenson** [comment]
I honestly think this looks okay .. if I unpin a top site it's a pretty strong signal that I don't want it in my list anymore. Besides, there's an edit function to add it back if I want to.
