### ISSUE TITLE
The Search bar border around the search arrow is wrongly darker when the arrow is highlighted

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3679]
https://bugzilla.mozilla.org/show_bug.cgi?id=1407244

[Affected versions]:
- Firefox 58.0a1 Build ID 20171009220104

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the browser with the profile from prerequisites and open a New Tab.
2. Hover the Search bar arrow.
3. Observe the border around the arrow.

[Expected results]:
- The border has the same color as the rest of the Search bar border.

[Actual results]:
- The border around the Search arrow is slightly darker.

[Notes]:
- Attached a screen shot of the issue:
![search border is also highlighted](https://user-images.githubusercontent.com/18304511/31391389-0f2a18c4-addf-11e7-8dfe-3bc86075edfc.png)

**Comment by Mardak** [comment]
The address bar has a hover state that darkens the whole box:

no hover:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/438537/31415023-a87256ea-add5-11e7-9fef-03f350063311.png">

box hover:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/438537/31415031-b1949e72-add5-11e7-8ba8-ed1702eb6246.png">

button hover:
<img width="821" alt="image" src="https://user-images.githubusercontent.com/438537/31415044-c5d69d18-add5-11e7-9435-943ea66840aa.png">

**Comment by aaronrbenson** [comment]
It looks like the hover background extends into the border area making it look like the border is darker? Can we put some margin on the bg so it doesn't look that way @Mardak?

**Comment by Mardak** [comment]
Clarified on slack that the border near the arrow should not be darker than the rest. And that the whole box's border should get darker on hover like the address bar.

**Comment by sarracini** [comment]
Fixed with #3785
