### ISSUE TITLE
Card shadows disappear when collapsing or expanding a section

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3681]
@aaronrbenson says:
> I also noticed that the dropshadow seems to disappear during the transition

@rlr I believe you had to set some styling during a transition. Not sure if that's what's removing the shadows?

**Comment by rlr** [comment]
Yeah. the `overflow: hidden;` basically is clipping the shadows. Could be fixed by adding some padding. Or possibly just setting `overflow-y: hidden;`?

**Comment by Mardak** [comment]
I think that would work. We should also get rid of `margin-inline-end: -7px;` then. That was causing the "show more topics" link to be shifted right.

**Comment by rlr** [comment]
I'll give it a try. grabbing 👍

**Comment by rlr** [comment]
@Mardak so I tried `overflow-y: hidden`. Check out the scrollbar that appears on opening now 😖 . Oh and it seems this doesn't fix the shadow bug anyway.

<img src="https://d26dzxoao6i3hh.cloudfront.net/items/0x0D303y193Y371f0o0d/Screen%20Recording%202017-10-10%20at%2001.21%20PM.gif" />
