### ISSUE TITLE
Telemetry to record how long placeholders are shown for

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3687]
Similar to https://github.com/mozilla/activity-stream/issues/2672 but from a user perspective.
We want to know for how long users see placeholders. As opposed to the linked bug this situation might not happen at all times.

**Comment by piatra** [comment]
Blocked on meta bug https://github.com/mozilla/activity-stream/issues/3691 to ensure me measure this the right way.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432327
