### ISSUE TITLE
Reporting: placeholder and data_late_by, measurement objective

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3691]
This is a meta bug for https://github.com/mozilla/activity-stream/issues/3687 and https://github.com/mozilla/activity-stream/issues/2672.
Main objective is make sure we are measuring the right thing: specifically cases like rehydration.
Decide how we want to act on those measurements like track regressions.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1432327 with a needinfo from dmose
