### ISSUE TITLE
Vertical scrollbar shows up all the time, even when there is nothing to scroll

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/activity-stream#3696]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1407770

Testing on v58.0a1 (2017-10-11) on a 1920x1080 screen at 125% scaling. Should be reproducible regardless of the window size, resolution etc. though.

STR: Most easily noticeable if you have unchecked all items under 'New Tab Preferences' so that the page is blank, except for the Firefox logo and the cog icon.

AR: disabled scrollbar is visible:
![capture](https://user-images.githubusercontent.com/8336638/31488311-e5e4b046-af5a-11e7-864a-36d02b2d9436.PNG)

ER: it shouldn't be.

Probably because `body` has `overflow-y: scroll;`. Changing it to `overflow-y: auto;` fixes things.

**Comment by shikhar-scs** [comment]
@Mardak @tspurway If this issue is still up can I please work on it

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1407770

@shikhar-scs I've assigned you the bug in bugzilla

**Comment by shikhar-scs** [comment]
@Mardak Due to a lot of preoccupations, I wont be able to devote time to this issue. Any one else is free to take this over :+1:

**Comment by shaweglea** [comment]
@shikhar-scs 

I believe the solution has already been pointed out in https://bugzilla.mozilla.org/show_bug.cgi?id=1418515

this is a simple change to the CSS

**Comment by shikhar-scs** [comment]
@shaweglea Yeah that's true. Ok i'll do that ASAP :+1:

**Comment by shikhar-scs** [comment]
@shaweglea I've made the changes please review it at #3950
