### ISSUE TITLE
Unexpected behaviors when actions happen before INIT

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3697]
In investigating #3695 for the actual cause for #3377, turns out if Activity Stream is late to load and simulates a NEW_TAB_INIT/LOAD for existing pages, those might happen before INIT, which theoretically should be the very first action?

Here `createChannel` simulates "RemotePage:Init" and "RemotePage:Load" before "INIT". I guess `ActivityStreamMessageChannel` should only simulate after INIT?
https://github.com/mozilla/activity-stream/blob/9327fcc2c00a46662cf3b5426063a13481010487/system-addon/lib/Store.jsm#L135-L139

@k88hudson

**Comment by piatra** [comment]
Fixed by https://github.com/mozilla/activity-stream/pull/3695.
