### ISSUE TITLE
Need error testing if embedly or our proxy server goes down

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#370]

**Comment by tspurway** [comment]
Server side monitoring.  Let's ask ops

**Comment by pdehaan** [comment]
We should also make sure that the New Tab page behaves itself if the user is offline or is unable to reach our Embedly proxy for whatever reason.

**Comment by jaredkerim** [comment]
This is already in place.  If the proxy server fails to respond the user flow will not be interrupted, however metadata will not appear (icons, colours, etc).
