### ISSUE TITLE
Include new tab settings in the general browser options dialog

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3702]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1404890

This might turn into "move" instead of "include"

**Comment by aaronrbenson** [comment]
https://trello.com/c/kV4iQYE4/152-new-tab-should-have-more-robust-settings-inside-of-firefox-preferences

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1404890
