### ISSUE TITLE
Auto Scroll is wrongly enabled when the "Search arrow" is middle clicked

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/activity-stream#3704]
https://bugzilla.mozilla.org/show_bug.cgi?id=1408320

**[Notes]:**
- The problem is easily reproduced if all sections are populated.

**[Affected versions]:**
- Firefox 57 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile.
- Change the "browser.search.region" pref to "US".

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and open a new tab.
2. Middle click the "Search" button from the "Search bar" and observe the behavior.

**[Expected result]:**
- A new tab is opened.

**[Actual result]:**
- A new tab is opened and the auto scroll is activated.

**[Additional Notes]:**
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/438537/31555236-1ab41e0c-aff5-11e7-8ca8-965afd4872d0.gif)

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1408320
