### ISSUE TITLE
Highlights shifts down 1px when topics appears

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3712]
Regressed from #3670. Caused by the clearfix. @rlr 

left: no clearfix, right: with clearfix
<img width="275" alt="image" src="https://user-images.githubusercontent.com/438537/31568177-cfa37b3c-b027-11e7-8b0d-6dd1c292c74f.png">

**Comment by rlr** [comment]
Any easy way to repro this? I tried showing/hiding the topics list but no luck:

<img src="https://d26dzxoao6i3hh.cloudfront.net/items/2C0S43400u1Q1o2t3v1v/Screen%20Recording%202017-10-14%20at%2001.59%20PM.gif" />

**Comment by Mardak** [comment]
You can toggle `display: none` on `<a class="topic-read-more"`
