### ISSUE TITLE
Prepare for theme API

### ISSUE THREAD

**Issue by nt1m** [mozilla/activity-stream#3715]
It would be nice to layout some ground work for: https://bugzilla.mozilla.org/show_bug.cgi?id=1347204

Things that can be done:
- Figure out which chrome properties are relevant to Firefox
- Implement those theme properties as CSS variables for the NTP on the root, then the theming API code in m-c will simply need to set those variables.

```
 * COLOR_NTP_BACKGROUND,
 * COLOR_NTP_TEXT,
 * COLOR_NTP_LINK,
 * COLOR_NTP_LINK_UNDERLINE,
 * COLOR_NTP_HEADER,
 * COLOR_NTP_SECTION,
 * COLOR_NTP_SECTION_TEXT,
 * COLOR_NTP_SECTION_LINK,
 * COLOR_NTP_SECTION_LINK_UNDERLINE,
 * COLOR_NTP_SECTION_HEADER_TEXT,
 * COLOR_NTP_SECTION_HEADER_TEXT_HOVER,
 * COLOR_NTP_SECTION_HEADER_RULE,
 * COLOR_NTP_SECTION_HEADER_RULE_LIGHT,
 * COLOR_NTP_TEXT_LIGHT
```

**Comment by piatra** [comment]
We have to go through the list and figure out which of those variables applies to AS. We need to use undefined CSS variables that override our default styles if they are ever set (that's the gist of it).
The variable values "will be provided by the browser" (somehow, does not depend on us) and they will be used to style AS through addons.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1347204
