### ISSUE TITLE
Card hostname can overflow

### ISSUE THREAD

**Issue by AdamHillier** [mozilla/activity-stream#3716]
If [ShortURL.jsm](https://github.com/mozilla/activity-stream/blob/master/system-addon/lib/ShortURL.jsm) can't process the hostname of a url properly it falls back to using the page title. If the page title is too long then the hostname of the highlights card overflows as shown here.

<img width="237" alt="screen shot 2017-10-16 at 1 42 05 am" src="https://user-images.githubusercontent.com/7688302/31591069-5fc6f724-b213-11e7-9bd0-6eef87696248.png">

For reference, the url is [this](https://www.gov.uk/countersigning-passport-applications/accepted-occupations-for-countersignatories).

This issue is probably quite niche as it (presumably) has to be an unusual tld for the hostname to not be parsed properly (in this case `gov.uk`), and the page title has to be long enough.

One other issue the fallback causes is that highlights are no longer deduped by hostname, so all nine cards end up being from the same host, though that's less of a problem.

Probably a straightforward fix to limit the hostname to one line? Though I'm not sure what would happen if a domain itself happened to be really long.

**Comment by Mardak** [comment]
The url looks to be `https://www.gov.uk/countersigning-passport-applications`

**Comment by Mardak** [comment]
The url looks to be `https://www.gov.uk/countersigning-passport-applications`
```
Services.eTLD.getBaseDomain(Services.io.newURI("https://www.gov.uk/countersigning-passport-applications"))
"www.gov.uk"
```

**Comment by Mardak** [comment]
I think the bug is that the "hostname" for "www.gov.uk" is technically "www" but we strip out "www". But then again, showing "www" probably isn't the right fix either.

Probably we should just fall back to `hostname` before falling back to `title`.

**Comment by Mardak** [comment]
Or.. we should always have a `hostname` ? So probably don't need to fall back to `title` or `url`?

**Comment by piatra** [comment]
> Or.. we should always have a hostname ?

This will happen, I think the problem is just that the top level domain is not extracted properly and we end up with "".

**Comment by AdamHillier** [comment]
Yeah it's interesting because `.gov.uk` is a second level domain that can have subdomains registered "below" it but that happens to have an actual site hosted on `www.gov.uk`. Wikipedia yields several other similar examples: [`.parliament.nz`](http://parliament.nz), [`.govt.nz`](http://govt.nz), [`.gov.il`](http://gov.il), [`.idf.il`](http://idf.il).

In this case as a user it's clearest to have `gov` or `gov.uk` as the card hostname.
