### ISSUE TITLE
After clicking on the "New Tab Preferences" link in the (?) panel, the panel should go away

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3721]
STR: Hover over the (?) icon in a section and then click "New Tab Preferences" from that panel.

Actual Results: Sidebar opens and the (?) panel stays open
Expected Results: Sidebar opens and the (?) panel goes away

Note: The behavior described above does not happen at more narrow window widths because after the sidebar has opened, the mouse cursor is now over the sidebar and the (?) panel disappears. This is actually the preferred behavior.

**Comment by Mardak** [comment]
The fix here is probably to take set `pointer-events: none;` on the panel / icon when the pref pane is open similar to #3645.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1425500
