### ISSUE TITLE
Bookmarks created from Reader Mode don't show up in Highlights

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3722]
STR: Open a page in reader mode and bookmark it.

Actual Results: The bookmark never surfaces in Highlights on new tab or in the Library menu Highlights section.
Expected Results: Item should appear in both Highlights lists and, when visited, should open in Reader Mode.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1425499
