### ISSUE TITLE
Error: Can't resolve during initial build

### ISSUE THREAD

**Issue by PhillypHenning** [mozilla/activity-stream#3726]
Following the build instructions, an error occurred at the [building](https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/1.GETTING_STARTED.md#building) step.  

Running the command:
`npm run buildmc`

Expected:
Build js and css files and copy them into the browser/extensions/activity-stream directory inside mozilla-central

Result:
An error occurs during the build

![screenshot from 2017-10-17 20-25-02](https://user-images.githubusercontent.com/16713447/31695542-4a73ad56-b379-11e7-83a6-2d078ef2f54a.png)

Fix: 
`npm run buildmc:locales
npm run buildmc`

**Comment by Mardak** [comment]
Oh indeed. I had a fix as part of fixing #3370 but we can land a fix separately to build the locales file earlier:
```diff
diff --git a/yamscripts.yml b/yamscripts.yml
index e59000f5..150b7380 100644
--- a/yamscripts.yml
+++ b/yamscripts.yml
@@ -23,8 +23,8 @@ scripts:
   buildmc:
     pre: =>cleanmc
+    locales: pontoon-to-json --src locales --dest system-addon/data
     webpack: webpack --config webpack.system-addon.config.js
     css: node-sass system-addon/content-src/activity-stream.scss -o system-addon/data/content
     html: webpack --config webpack.prerender.config.js && node ./bin/render-activity-stream-html.js
-    locales: pontoon-to-json --src locales --dest system-addon/data
     # Copy over all of the system-addon directory
     copy: cpx "system-addon/**/{,.}*" ../mozilla-central/browser/extensions/activity-stream
```
