### ISSUE TITLE
[57] The Firefox firstrun page is set as a highlight when first opening the AS New Tab Page

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla/activity-stream#3728]
https://bugzilla.mozilla.org/show_bug.cgi?id=1409661

[Note]:
- Only the 57 beta builds are affected

[Affected versions]:
- 57.0b9 (20171016185129)

[Affected platforms]:
- Windows 10x64
- Ubuntu 16.04 x64
- macOS 10.12.1

[Steps to reproduce]:
1. Launch Firefox using a clean profile
2. Open a new tab and inspect the Highlights section

[Expected result]:
- The https://www.mozilla.org/en-US/firefox/57.0/firstrun/ is set as the first highlight (see the screencast https://goo.gl/Dr1y7N)

[Actual result]:
- The Highlight section is empty, as only the firstrun and privacy sites were opened (by default)

[Regression range]:
- It seems that this issue is reproducible starting with 57.0b1 (20170917031738) (the last 57.0a1 (2017-09-21) and the first 58.0a1 (2017-09-21) builds are not affected) 

[Additional notes]:
- Neither the privacy page or the default bookmarks are not automatically added in the Highlights section at the first AS New Tab Page opening, so the firstrun page should respect this behavior, too.

**Comment by aaronrbenson** [comment]
This does seem to undercut our zero state message for Highlights and the user never gets a chance to see it. I think it would make sense to omit that page from Highlights since they didn't really navigate to it on their own because Firefox loaded the page for them.

**Comment by piatra** [comment]
This issue is fixed, we now update every 15 minutes not if highlights are empty. This change landed in https://github.com/mozilla/activity-stream/commit/8850b8b59d4601d0ddf9e299d17792aaf1b274b7

**Comment by IuliaCristescu4** [comment]
I have to apologize because the Actual and Expected results are inverted by mistake in the description. So the right one is:

[Expected result]:
- The Highlight section is empty, as only the firstrun and privacy sites were opened (by default) 

[Actual result]:
- The https://www.mozilla.org/en-US/firefox/57.0/firstrun/ is set as the first highlight (see the screencast https://goo.gl/Dr1y7N)
