### ISSUE TITLE
New profiles trigger a bunch of places queries for highlights

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3730]
Noticed when testing #3695. Regressed by #3675:
https://github.com/mozilla/activity-stream/blob/d8f0b4ad8ab4b7699848ebd02f0ad59bad19e987/system-addon/lib/HighlightsFeed.jsm#L150-L154

New profiles create some bookmarks causing highlights to expire the cache. We end up requesting new highlights but also get none because they're too recently bookmarked (probably default bookmarks).

@piatra

**Comment by piatra** [comment]
I already created https://github.com/mozilla/activity-stream/issues/3724 to handle this.

**Comment by Mardak** [comment]
Ah doh. too many issues ;)
