### ISSUE TITLE
ReferenceError: reference to undefined property "doneReason" in BackgroundPageThumbs.jsm

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#3733]
https://bugzilla.mozilla.org/show_bug.cgi?id=1409691

ReferenceError: reference to undefined property "doneReason" in  BackgroundPageThumbs.jsm
http://searchfox.org/mozilla-central/rev/dca019c94bf3a840ed7ff50261483410cfece24f/toolkit/components/thumbnails/BackgroundPageThumbs.jsm#402

**Comment by Mardak** [comment]
https://hg.mozilla.org/mozilla-central/rev/adc548643541
