### ISSUE TITLE
async methods in content-src break prerender on older node

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3736]
#3611 added `async maybeLoadImage()` which is causing

```
activity-stream/bin/prerender.js:30469
  async maybeLoadImage() {
        ^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (activity-stream/bin/render-activity-stream-html.js:7:19)
```

Locally this fails on node v6.11.4 but is fine with node v8.7.0. @k88hudson

**Comment by dmose** [comment]
Our minimal node version has been semi-stapled to 7.* (see package.json, .nvmrc, and .travis.yml) for a little while.  It's not trivial to actually enforce this, and we could probably do a bit to make it clear what the problem is when stuff like this happens, but it hasn't (up until now) been a priority.  It's not obvious to me that we want to fix this.

**Comment by Mardak** [comment]
Ah, 7 should be fine for now… I didn't have a node 7 handy earlier (`brew` has node@6 and latest node 8 as "there is no upstream LTS for 7.x" https://github.com/Homebrew/homebrew-core/issues/14118#issuecomment-305371903 ) Not sure if that means we should update away from 7 to 8?

I got node 7 via nvm via brew, so just confirming that this `async` problem is gone with v7.10.1.

**Comment by dmose** [comment]
Kate specifically recommended 7 over 8 when I was doing the pinning work; I think was for stability reasons.  Undoubtedly we will want to switch to something with LTS, but I'm not sure when.  @k88hudson ?
