### ISSUE TITLE
Unexpected behaviors when stories redirect to different urls

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla/activity-stream#3738]
https://bugzilla.mozilla.org/show_bug.cgi?id=1410075

[Note]:
- There are some different issues generated by the https://mondaynote.com/teslas-new-car-smell-315c72c955d3 Pocket recommendation:
A. It can be displayed in all AS sections at once
B. There are created multiple hidden entries for it in the Highlights section, with different links
C. It is often displayed with different links in the Highlights section 

[Affected versions]:
- 58.0a1 (2017-10-18)
- 57.0b9 (20171016185129)

[Affected platforms]:
- Windows 10x64
- Ubuntu 16.04 x64
- macOS 10.12.1

[Steps to reproduce]:
1. Launch Firefox using a clean profile
2. Enable the Top Stories section (set the browser.search.region pref to "US") if it isn't already
3. Go to the AS New Tab page, look for the https://mondaynote.com/teslas-new-car-smell-315c72c955d3 Pocket recommendation and open it multiple times 
4. Reopen the AS New Tab page and inspect each section 
5. Dismiss a random top site and inspect each AS section 
6. Restart the browser and inspect each AS section 
7. Dismiss the above mentioned website from the Highlights section

[Expected result]:
- [step4] The above mentioned website is displayed in the Highlights section (with its original link) and it's replaced by other top story in the Pocket Recommendations section 
- [step5] The above mentioned website is displayed only in the Top Sites section (with its original link)
- [step6] The above mentioned website is displayed only in the Top Sites section (with its original link)
- [step7] The above mentioned website is dismissed from the Highlights section from the first try

[Actual result]:
- [step4] a) The above mentioned website is displayed in the Highlights section (with its original link) and it's replaced by other top story in the Pocket Recommendations section 
OR 
          b) The above mentioned website is displayed in both Highlights (with another link, e.g. https://mondaynote.com/teslas-new-car-smell-315c72c955d3?gi=6dc8ef42e073) and Pocket Recommendations (with its original link) sections 

- [step5] a) The above mentioned website is displayed in the Top Sites (with its original link) and Highlights (with another link, e.g. https://mondaynote.com/teslas-new-car-smell-315c72c955d3?gi=6dc8ef42e073) sections 
OR 
          b) The above mentioned website is displayed in Top Sites (with its original link), Pocket Recommendations (with its original link) and Highlights (with another link, e.g. https://mondaynote.com/teslas-new-car-smell-315c72c955d3?gi=6dc8ef42e073) sections 

- [step6] a) The above mentioned website is displayed in Top Sites (with its original link), Pocket Recommendations (with its original link) and Highlights (with another link, e.g. https://mondaynote.com/teslas-new-car-smell-315c72c955d3?gi=6dc8ef42e073) sections
          b) same as the a) case

- [step7] The above mentioned website can't be dismissed from the first try, there are created multiple hidden entries for it in the Highlights section, with different links (e.g. https://mondaynote.com/teslas-new-car-smell-315c72c955d3?gi=6dc8ef42e073 or https://mondaynote.com/teslas-new-car-smell-315c72c955d3?gi=a04ba95c6d1c) 

[Regression range]:
- This issue is reproducible all the way back to 57.0a1 (2017-09-08) build, when the Highlights section was introduced (bug 1396609) (in this build, every different entry that is created in the Highlight section is visible and displayed separately, not hidden) 

[Additional notes]:
- See the screencasts for a) case https://goo.gl/81LdCC and for b) case https://goo.gl/EpLji5.

**Comment by piatra** [comment]
The issue here is that the website adds a unique hash to each visit thus getting a "unique" url for each of those. Highlights uses URLs as dedupe key, so does the dismiss. Not much we can do for now but it also doesn't seem high priority.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1410075
