### ISSUE TITLE
Messages when running eslint: can't resolve reference #/definitions/basicConfig

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3743]
@Standard8 looks like this started with the eslint 4 update from #3705:
```
> esw --ext=.js,.jsm,.json,.jsx .

can't resolve reference #/definitions/basicConfig from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
✓ Clean (1:15:59 PM)
```

Before:
```
> esw --ext=.js,.jsm,.json,.jsx .

✓ Clean (1:15:16 PM)
```

**Comment by Mardak** [comment]
Looks like probably `eslint-plugin-react`:
```
eslint-plugin-react/lib/rules/jsx-curly-spacing.js:        basicConfigOrBoolean: {
eslint-plugin-react/lib/rules/jsx-curly-spacing.js:              $ref: '#/definitions/basicConfigOrBoolean'
eslint-plugin-react/lib/rules/jsx-curly-spacing.js:              $ref: '#/definitions/basicConfigOrBoolean'
```

**Comment by Mardak** [comment]
https://github.com/yannickcr/eslint-plugin-react/issues/1290

**Comment by Mardak** [comment]
@Standard8 any particular reason for `"eslint-plugin-react": "7.1.0",` vs 7.2.0 or later that should have this fixed?

**Comment by Mardak** [comment]
I'm guessing the 7.1.0 for activity stream was picked to match that in mozilla-central, but that change was from 4 months ago, so we might be okay just updating to something newer… ? https://bugzilla.mozilla.org/show_bug.cgi?id=1379092

**Comment by Standard8** [comment]
@Mardak I think picking up latest should be fine if it works for you. Generally having external repos on the same/a later version than central is a good thing IMO.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421832
