### ISSUE TITLE
Use a 1px border width for the search field on Windows only

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#3745]
We should match the native OS when styling the search field on New Tab. The focused state should look like the attached:

![screen shot 2017-10-19 at 3 42 16 pm](https://user-images.githubusercontent.com/139451/31793193-30f20e92-b4e4-11e7-9f04-159c4e82e188.png)

Related, I've filed a bug to change the placeholder text on Windows to non-italicized: https://bugzilla.mozilla.org/show_bug.cgi?id=1410233

**Comment by Mardak** [comment]
So it should be 2px on mac and 1px on windows?

**Comment by aaronrbenson** [comment]
Is it 2px on mac now? Seems a bit thicker but I could be wrong ..

**Comment by aaronrbenson** [comment]
I guess it doesn't matter .. the current state of macOS looks correct.

**Comment by Mardak** [comment]
Oh indeed. It's currently 1px border with 2px box-shadow, so a total 3px.

**Comment by aaronrbenson** [comment]
Hey @Mardak, was there anything else needed here for design feedback?

**Comment by Mardak** [comment]
Sounds like this should be good. Just to summarize: change total border width to 1px for windows and leave unchanged elsewhere.
