### ISSUE TITLE
First about:home gets rehydrated twice

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3747]
Noticed this when investigating #3741. Looks like main sends INIT while content mounts `Base` triggering NEW_TAB_STATE_REQUEST then content sees INIT come by to resend NEW_TAB_STATE_REQUEST. Turns out main already has strings and immediately responds with NEW_TAB_INITIAL_STATE to each REQUEST.

Should be mostly harmless unless messages can arrive out of order? (Pretty sure they stay in order.)

For potential fixes, it seems that we can't do much about the parallel main-to-content INIT and content-to-main REQUEST, and content has no idea (?) if the initial REQUEST was never received. So either main remembers that it already responded to a target and skips or the target content doesn't rehydrate twice? @k88hudson

**Comment by Mardak** [comment]
Here's a run with dumping action:
```diff
diff --git a/system-addon/content-src/lib/init-store.js b/system-addon/content-src/lib/init-store.js
--- a/system-addon/content-src/lib/init-store.js
+++ b/system-addon/content-src/lib/init-store.js
@@ -39,4 +39,5 @@ function mergeStateReducer(mainReducer) {
 const messageMiddleware = store => next => action => {
   if (au.isSendToMain(action)) {
+  dump(["cont",Date.now(),`${action.type} -> ${au.isSendToMain(action) ? "main" : "cont"}`]+"\n");
     sendAsyncMessage(OUTGOING_MESSAGE_NAME, action);
   }
@@ -45,4 +46,7 @@ const messageMiddleware = store => next => action => {
 
 const rehydrationMiddleware = store => next => action => {
+  if (!au.isSendToMain(action)) {
+    dump(["cont",Date.now(),`${action.type} -> ${au.isSendToMain(action) ? "main" : "cont"}`]+"\n");
+  }
   if (store._didRehydrate) {
     return next(action);
diff --git a/system-addon/lib/NewTabInit.jsm b/system-addon/lib/NewTabInit.jsm
index ceac7e72..a83d0ab7 100644
--- a/system-addon/lib/NewTabInit.jsm
+++ b/system-addon/lib/NewTabInit.jsm
@@ -6,5 +6,5 @@
 const {utils: Cu} = Components;
 
-const {actionCreators: ac, actionTypes: at} = Cu.import("resource://activity-stream/common/Actions.jsm", {});
+const {actionCreators: ac, actionTypes: at, actionUtils: au} = Cu.import("resource://activity-stream/common/Actions.jsm", {});
 
 /**
@@ -21,4 +21,5 @@ this.NewTabInit = class NewTabInit {
   }
   onAction(action) {
+    dump(["main",Date.now(),`${action.type} -> ${au.isSendToMain(action) ? "main" : "cont"}`]+"\n");
     switch (action.type) {
       case at.NEW_TAB_STATE_REQUEST:
```
```
main,1508506730260,INIT -> cont
main,1508506730262,PREFS_INITIAL_VALUES -> cont
main,1508506730266,SECTION_REGISTER -> cont
main,1508506730266,SECTION_REGISTER -> cont
main,1508506730268,SECTION_UPDATE -> cont
main,1508506730269,SECTION_UPDATE -> cont
main,1508506730273,NEW_TAB_INIT -> main
main,1508506730296,LOCALE_UPDATED -> cont
main,1508506730308,TOP_SITES_UPDATED -> cont
main,1508506730317,SECTION_UPDATE -> cont
main,1508506730344,SAVE_SESSION_PERF_DATA -> main
cont,1508506730371,NEW_TAB_STATE_REQUEST(1) -> main
cont,1508506730372,PAGE_PRERENDERED -> main
cont,1508506730383,INIT -> cont
cont,1508506730383,NEW_TAB_STATE_REQUEST(2) -> main (re-request on INIT)
main,1508506730383,NEW_TAB_STATE_REQUEST(1) -> main
main,1508506730383,NEW_TAB_INITIAL_STATE(1) -> cont
cont,1508506730384,PREFS_INITIAL_VALUES -> cont
cont,1508506730384,SECTION_REGISTER -> cont
main,1508506730384,PAGE_PRERENDERED -> main
cont,1508506730384,SECTION_REGISTER -> cont
cont,1508506730385,SECTION_UPDATE -> cont
cont,1508506730385,SECTION_UPDATE -> cont
cont,1508506730386,LOCALE_UPDATED -> cont
cont,1508506730386,TOP_SITES_UPDATED -> cont
cont,1508506730386,SECTION_UPDATE -> cont
main,1508506730388,NEW_TAB_LOAD -> main
cont,1508506730398,NEW_TAB_INITIAL_STATE(1) -> cont
cont,1508506730400,NEW_TAB_REHYDRATED -> main
cont,1508506730404,SAVE_SESSION_PERF_DATA -> main
main,1508506730427,NEW_TAB_STATE_REQUEST(2) -> main
main,1508506730427,NEW_TAB_INITIAL_STATE(2) -> cont
main,1508506730429,NEW_TAB_REHYDRATED -> main
main,1508506730429,SAVE_SESSION_PERF_DATA -> main
cont,1508506730445,SAVE_SESSION_PERF_DATA -> main
main,1508506730496,SAVE_SESSION_PERF_DATA -> main
main,1508506730498,SECTION_UPDATE -> cont
main,1508506730513,SECTION_UPDATE -> cont
main,1508506730520,SECTION_UPDATE -> cont
cont,1508506730528,NEW_TAB_INITIAL_STATE(2) -> cont
main,1508506730530,SNIPPETS_DATA -> cont
cont,1508506730560,SAVE_SESSION_PERF_DATA -> main
cont,1508506730565,SECTION_UPDATE -> cont
main,1508506730565,SAVE_SESSION_PERF_DATA -> main
cont,1508506730588,SECTION_UPDATE -> cont
cont,1508506730608,TELEMETRY_IMPRESSION_STATS -> main
main,1508506730611,TELEMETRY_IMPRESSION_STATS -> main
cont,1508506730612,SNIPPETS_DATA -> cont
```

If `Date.now()` can be compared between main and content, the first action (INIT) is received by content 123ms later. And the latest action (SNIPPETS_DATA) is 82ms later.

While sending from content to main seems faster: 12ms for first action (NEW_TAB_STATE_REQUEST(1)) and 3ms for the last action (TELEMETRY_IMPRESSION_STATS).

**Comment by Mardak** [comment]
@dmose @ncloudioj see previous comment about timing delays of messages. Is any of our telemetry a mix of chrome and content times that depend on when a message is received? Depending on how we measure, we could be under counting some things (e.g., measured time in chrome but content doesn't actually get it until ~100ms later) or over counting other things (e.g., something finished in content ~10ms ago but chrome measured time on receiving the message).

**Comment by ncloudioj** [comment]
@Mardak So I just did a quick audit particularly on those perf metrics, looks like they are all being calculated on the content side, then get passed (SAVE_SESSION_PERF_DATA) to chrome. So I think we should be fine here.

**Comment by Mardak** [comment]
Marked from main when INIT is sent (1.532s) to mark on receiving INIT (1.623s).
https://perfht.ml/2yBpwCK

mconley says:
> yeah, so in this case, it looks like the content process is busy doing other things before it can respond to the IPC message
that's where the delay is - not that the IPC message is taking a long time to send.
the content process is busy running JS to render activity stream.
Earlier on, there's a long paint occurring.
26ms spend rasterizing
so painting the initial about:home takes about 26ms, and then a bunch of JS executes almost immediately, and that takes a while
something like ~66ms
and then finally the IPC messages are all serviced at the end
so they were all received and queued up
they were just at the back of the queue

**Comment by Mardak** [comment]
For possible fixes in getting the message sooner: break up execution in a way that puts the latter chunks after the processing the message. Although in the profile, 51ms is spent on loading the bundle and React running stuff.

**Comment by dmose** [comment]
Here's another more general profile with all of the messages marked.  Note, however, that they're all marked on the main thread side, next step might be to mark send & receive of all of them.

https://perf-html.io/from-addon/marker-table/?hiddenThreads=&markerSearch=UserTiming&thread=0&threadOrder=0-2-3-4-5-6-1&v=2

**Comment by dmose** [comment]
(Note that this is for the general question of "what all is going on here", as Ed has already suggested a specific tactic for the particular problem this bug describes).

**Comment by Mardak** [comment]
I don't think the perf-html link you provided is the shareable version.

**Comment by dmose** [comment]
Indeed not; that's a rather surprising UX choice.   And, excitingly, when I generate the shareable version, it doesn't have all the data.  I'll get a new link in the morning.

**Comment by dmose** [comment]
My mistake; it just leads to the wrong view on the correct data.  https://perf-html.io/public/5f913e6e18f7b56c1ee8ca2f149bd51aa4704c5b/marker-table/?hiddenThreads=&markerSearch=UserTiming&thread=0&threadOrder=0-2-3-4-5-6-1&v=2

**Comment by dmose** [comment]
I put together some profiling markers to help debug this, and Ed and I spent a bunch of time sorting through this yesterday.  I haven't yet been able to reproduce the problem on my machine, so Ed's gonna grab this bug while I start poking at verifying timestamp correctness stuff.

https://github.com/dmose/activity-stream/tree/profile-messages 

is the branch with my profiling markers
