### ISSUE TITLE
Useless horizontal scrollbar shown at minimum window width

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla/activity-stream#3748]
https://bugzilla.mozilla.org/show_bug.cgi?id=1410442

[Note]:
- This issue is reproducible only on Windows platforms

[Affected versions]:
- 58.0a1 (2017-10-20)
- 57.0b10 build1 (20171019140425)

[Affected platforms]:
- Windows 10 x64

[Steps to reproduce]:
1. Launch Firefox using a clean profile
2. Access the AS New Tab page and make sure you have every section populated
3. Resize the browser windows to minimum width. 

[Expected result]:
- The entire AS New Tab page can be properly scrolled and all its elements are visible
- No visual artifacts or useless elements are displayed

[Actual result]:
- Useless horizontal scrollbar is displayed at the bottom of the browser window

[Additional notes]:
- The AS New Tab page can be properly scrolled, all its elements are visible and no elements are uncovered using the horizontal scrollbar

**Comment by piatra** [comment]
After discussing this issue we decided that the minimum width isn't a likely usage scenario.
