### ISSUE TITLE
The New Tab Preferences menu's width doesn't adapt to the window's width

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla/activity-stream#3749]
https://bugzilla.mozilla.org/show_bug.cgi?id=1410450

[Note]:
- The New Tab Preferences menu is not entirely visible at minimum window width 

[Affected versions]:
- 58.0a1 (2017-10-20)
- 57.0b10 build1 (20171019140425)

[Affected platforms]:
- Windows 10 x64
- Ubuntu 16.04 x64
- Mac OS X 10.11.6

[Steps to reproduce]:
1. Launch Firefox using a clean profile
2. Access the AS New Tab page and open the New Tab Preferences menu
3. Resize the browser window to minimum width 

[Expected result]:
- The New Tab Preferences menu adapt to the window's width so that all its elements are visible 

[Actual result]:
- The New Tab Preferences menu is not entirely visible

**Comment by bryanbell** [comment]
Surely this can be better, but we should recognize that the browser itself isn't useful at that size. Arguably the browser min-width should be adjusted wider. 

![narrow-browser](https://user-images.githubusercontent.com/228979/32012277-2cc76164-b96c-11e7-9d85-29d825721b2c.gif)

Besides this whole menu is slated to be removed and relocated into the application preferences. Its inclusion on this page was always a temporary move. 

let's not fix, and instead work on its replacement.
