### ISSUE TITLE
ReferenceError: reference to undefined property site.images (and site.favicon_colors)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#375]
Found in **activity-streams-experiment@1.0.4** (via Test Pilot).

---

### Steps to reproduce:
1. Browse the following set of random URLs:
  1. http://testpilot.dev.mozaws.net/__version__ (see [embedly-proxy](https://embedly-proxy.dev.mozaws.net/extract?urls=http://testpilot.dev.mozaws.net/__version__))
  2. https://www.gravatar.com/avatar/6143f61ca9cb48d4f5e590389597e644 (see [embedly-proxy](https://embedly-proxy.dev.mozaws.net/extract?urls=https://www.gravatar.com/avatar/6143f61ca9cb48d4f5e590389597e644))
  3. https://www.gravatar.com/avatar/6143f61ca9cb48d4f5e590389597e644?s=64 (see [embedly-proxy](https://embedly-proxy.dev.mozaws.net/extract?urls=https://www.gravatar.com/avatar/6143f61ca9cb48d4f5e590389597e644?s=64))
  4. https://d1fnkpeapwua2i.cloudfront.net/index.html?cachebust=1459206036063 (see [embedly-proxy](https://embedly-proxy.dev.mozaws.net/extract?urls=https://d1fnkpeapwua2i.cloudfront.net/index.html?cachebust=1459206036063))

2. Click the Activity Streams button in the toolbar.
3. Open up the DevTools console.

### Actual results:
![browser_console_and_activity_stream](https://cloud.githubusercontent.com/assets/557895/14094099/11394a40-f508-11e5-8b37-4dc11dbde25a.png)

> ReferenceError: reference to undefined property `site.favicon_colors` ([bundle.js:367:6](https://github.com/mozilla/activity-streams/blob/2fdac97691cacef5359ba5af32c7cc76b13c3d94/content-src/selectors/selectors.js#L63))
> ReferenceError: reference to undefined property `site.images` ([bundle.js:333:12](https://github.com/mozilla/activity-streams/blob/12322a854709686a4e6a20f917c3ed572c39198b/content-src/selectors/selectors.js#L19))

I'm mildly confused since results 1&4 above have `null` for their `images[]` and `favicon_colors[]`, and results 2&3 above have values for those.
Still trying to dig in and see exactly which items are causing the ReferenceErrors.

**Comment by pdehaan** [comment]
Me thinks it is https://d1fnkpeapwua2i.cloudfront.net/index.html?cachebust=1459206036063 which is causing the Reference Errors.

```json
{
    "https://d1fnkpeapwua2i.cloudfront.net/index.html?cachebust=1459206036063": {
        "app_links": [],
        "authors": [],
        "cache_age": 86400,
        "content": null,
        "description": null,
        "embeds": [],
        "entities": [],
        "favicon_colors": null,
        "favicon_url": null,
        "images": [],
        "keywords": [],
        "language": null,
        "lead": null,
        "media": {},
        "offset": null,
        "original_url": "https://d1fnkpeapwua2i.cloudfront.net/index.html?cachebust=1459206036063",
        "provider_display": "d1fnkpeapwua2i.cloudfront.net",
        "provider_name": "D1fnkpeapwua2i",
        "provider_url": "https://d1fnkpeapwua2i.cloudfront.net",
        "published": null,
        "related": [],
        "safe": true,
        "title": "Universal Search",
        "type": "html",
        "url": "https://d1fnkpeapwua2i.cloudfront.net/index.html?cachebust=1459206036063"
    }
}
```
&mdash; via https://embedly-proxy.dev.mozaws.net/extract?urls=https://d1fnkpeapwua2i.cloudfront.net/index.html?cachebust=1459206036063

![activity_stream](https://cloud.githubusercontent.com/assets/557895/14094352/4323f0d0-f50a-11e5-9a65-26447af51c91.png)

**Comment by sarracini** [comment]
@pdehaan I can't reproduce this anymore, can you?

**Comment by pdehaan** [comment]
Nope. Closing.
Thanks for the 👀
