### ISSUE TITLE
Imported bookmarks don't show up in Highlights

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3753]
I couldn't find an issue for this but imported bookmarks won't show up because they have 0 visits. In https://github.com/mozilla/activity-stream/pull/3734 we went with adding a visit to them. Probably should do something similar.

**Comment by tspurway** [comment]
Let's broaden this to investigate bookmark importing

**Comment by piatra** [comment]
The behavior differs depending on the browser we import from but overall it seems we are not affected.
 * for Chrome we don't import date created [only url and title](http://searchfox.org/mozilla-central/rev/ed212c79cfe86357e9a5740082b9364e7f6e526f/browser/components/migration/ChromeProfileMigrator.js#101)
   * we use current time & import history so higlights will show up.
 * for Edge we [try to import date created](http://searchfox.org/mozilla-central/rev/ed212c79cfe86357e9a5740082b9364e7f6e526f/browser/components/migration/EdgeProfileMigrator.js#311) and also import browsing history so everything should work fine
 * for Safari we only import bookmarks no history so no highlights will show up

This is true for Windows as well (where it probably matters most).
So we might get more bookmark highlights then we actually want from Chrome because using current date + importing visits means all bookmarks are potential candidates.
Not sure if it's something we necessarily want to fix/change. Leaving this open for comments.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421432
