### ISSUE TITLE
The snippets cover the New Tab Preferences Done button

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla/activity-stream#3760]
https://bugzilla.mozilla.org/show_bug.cgi?id=1411569

[Affected versions]:
- 58.0a1 (2017-10-24)
- 57.0b11 build1 (20171023180840)

[Affected platforms]:
- Windows 10 x64 
- macOS 10.13	
- Ubuntu 16.04 x64

[Steps to reproduce]:
1. Launch Firefox 
2. Open the AS New Tab Page 
3. Wait for the snippets to be shown (make sure you have the snippets displaying enabled)
4. Open the New Tab Preferences menu and inspect the Done button

[Expected result]:
- The Done button is visible and fully functional

[Actual result]:
- The New Tab Preferences menu bottom side is covered by the snippets (including the Done button) (see the screenshot https://goo.gl/rU7GtJ) 
- The Done button is still functional

[Additional notes]:
- On reduced width windows, the snippets are not displayed anymore and so, the Done button gets visible

**Comment by k88hudson** [comment]
The screenshot appears to indicate an issue with onboarding notifications, not snippets; although we should take a look at whether this is also an issue with snippets

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1411569
