### ISSUE TITLE
Unbookmarking a Pocket recommendation wrongly changes its status from Bookmarked to Visited instead of Trending

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3761]
https://bugzilla.mozilla.org/show_bug.cgi?id=1411577

[Affected versions]:
- Firefox 58.0a1 Build ID 20171024220325

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "browser.search.region" is set to "US" in about:config

[Steps to reproduce]:
1. Open the browser and open a new tab.
2. Bookmark a Pocket recommendation from the context menu.
3. Observe the card's status.

[Expected results]:
- Card's status is "Trending".

[Actual results]:
- Card's status is "Bookmarked".

[Additional notes]:
- If you remove the bookmark from the context menu, the card's status changes to "Visited". Restarting the browser resets the card's status back to Trending.
Regressed by: https://bugzilla.mozilla.org/show_bug.cgi?id=1407657.
- Attached a screen recording of the issue:
![pocket recommendation status incorrectly changed from trending](https://user-images.githubusercontent.com/18304511/32000225-a9f79e6a-b99e-11e7-8d18-8fdbdb40e6c1.gif)

**Comment by piatra** [comment]
This is expected behavior. When https://github.com/mozilla/activity-stream/pull/3734 lands, bookmarked Top Stories will also show up in the Highlights section.

**Comment by SoftVision-CiprianMuresan** [comment]
@piatra, I'm not sure I understand, is something in [Bug 1407657](https://bugzilla.mozilla.org/show_bug.cgi?id=1407657.) that's a part of the work in #3734? 
Up until this point Pocket recommendations always had the "Trending" status weather they were bookmarked or not. 

Is it expected for the status to change from Trending to Bookmarked and from Bookmarked to Visited? If yes, shouldn't these statuses persist after a page refresh or a restart?

**Comment by Mardak** [comment]
This was an intentional change as part of fixing #3629 to show the user that the story was bookmarked.

**Comment by SoftVision-CiprianMuresan** [comment]
@Mardak, could you please explain how these transitions will work from now on?

Because now we have the following:
If you bookmark a Pocket recommendation it changes from Trending to Bookmarked. 
If you remove the bookmark it changes from Bookmarked to Visited. (at this point I haven't visited the page so saying it was Visited doesn't seem right)
If you restart the browser the recommendation changes from Visited to Trending. (if the above is expected, then wouldn't it be expected for the status to not change after a restart?)

Is this the way they are supposed to be?

**Comment by piatra** [comment]
A pocket story is only around for at most 90 minutes. Fixes for these kind of edge cases where the user takes and action and then reverts it are not of high priority, especially since we are not losing any of the data.
To summarize the only problem is that the card should go from "Bookmarked" -> "Trending" and instead goes to "Visited". But everything works as expected.

**Comment by aaronrbenson** [comment]
@piatra's latest comment sounds right to me. What's the design feedback needed here?

**Comment by Mardak** [comment]
What's the expected label for bookmarking a story then immediately removing the bookmark? Right now removing a bookmark updates the card to Visited just like for Highlights.

**Comment by aaronrbenson** [comment]
It should go back to whatever the label was previously. So in the case of a Pocket item, the label should go back to read "Trending" but if it was in Highlights as a visited item, it should go back to read as "Visited".

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1411577
