### ISSUE TITLE
Fix test failures with activity stream disabled on 57

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3764]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1411797

https://treeherder.mozilla.org/#/jobs?repo=try&revision=ebaa7dc9af12fce83b4372466423cdd6760755c4

- [ ]  FAIL | [browser/components/search/test/browser_eBay.js | eBay engine is null](https://treeherder.mozilla.org/logviewer.html#?job_id=139269898&repo=try&lineNumber=4422)
- [ ] FAIL | [browser/components/search/test/browser_searchEngine_behaviors.js | Uncaught exception undefined - timed out after 50 tries.](https://treeherder.mozilla.org/logviewer.html#?job_id=139269898&repo=try&lineNumber=4668)
- [x] FAIL | [browser/modules/test/browser/browser_UsageTelemetry_content_aboutHome.js | Uncaught exception TypeError: searchInput is null](https://treeherder.mozilla.org/logviewer.html#?job_id=139269800&repo=try&lineNumber=10309)
- [ ] FAIL | [browser/extensions/screenshots/test/browser/browser_screenshots_ui_check.js | leaked 1 window(s) until shutdown [url = moz-extension://5cdb1de6-e7c0-4127-b61a-b903af9ff9bf/_generated_background_page.html]](https://treeherder.mozilla.org/logviewer.html#?job_id=139570186&repo=try&lineNumber=22912)
- [ ] FAIL | [browser/base/content/test/about/browser_aboutHome_imitate.js | leaked 2 window(s) until shutdown [url = https://example.com/browser/browser/base/content/test/about/test_bug959531.html]](https://treeherder.mozilla.org/logviewer.html#?job_id=139271987&repo=try&lineNumber=4218)
- [x] FAIL | [browser/components/newtab/tests/xpcshell/test_AboutNewTabService.js | test_as_and_prerender_initialized](https://treeherder.mozilla.org/logviewer.html#?job_id=139269805&repo=try&lineNumber=2406)

**Comment by piatra** [comment]
First bug (browser_eBay.js) is confusing. eBay doesn't seem to be a search engine anymore. It's not been removed on my profile (see grayed out restore button). Are we sure this one was green?

<img width="701" alt="image" src="https://user-images.githubusercontent.com/810040/32016456-081f4efa-b992-11e7-8625-f868bf7af2c2.png">

**Comment by Mardak** [comment]
Sounds like first 2 might be related to artifact builds. https://bugzilla.mozilla.org/show_bug.cgi?id=1406164

I'm pushing to try with --no-artifact: https://treeherder.mozilla.org/#/jobs?repo=try&revision=95c6970fb91ef521fc41af86926e38ec4d825ebe

**Comment by piatra** [comment]
#3 on the list assumes AS is turned on. Forcing the pref on fixes it.
```
diff --git a/browser/modules/test/browser/browser_UsageTelemetry_content_aboutHome.js b/browser/modules/test/browser/browser_UsageTelemetry_content_aboutHome.js
index 7f2239ab15ab..89982065c4a8 100644
--- a/browser/modules/test/browser/browser_UsageTelemetry_content_aboutHome.js
+++ b/browser/modules/test/browser/browser_UsageTelemetry_content_aboutHome.js
@@ -40,6 +40,7 @@ add_task(async function setup() {
     Services.search.removeEngine(engineOneOff);
     await PlacesTestUtils.clearHistory();
     Services.telemetry.setEventRecordingEnabled("navigation", false);
+    Services.prefs.clearUserPref("browser.newtabpage.activity-stream.enabled");
     Services.prefs.clearUserPref("browser.newtabpage.activity-stream.aboutHome.enabled");
   });
 });
@@ -98,6 +99,7 @@ add_task(async function test_abouthome_simpleQuery() {

 add_task(async function test_abouthome_activitystream_simpleQuery() {
   // Make sure Activity Stream about:home is enabled.
+  Services.prefs.setBoolPref("browser.newtabpage.activity-stream.enabled", true);
   Services.prefs.setBoolPref("browser.newtabpage.activity-stream.aboutHome.enabled", true);

   // Let's reset the counts.
```

**Comment by piatra** [comment]
the 5th browser_aboutHome_imitate.js doesn't seem to be failing in your other try run
https://treeherder.mozilla.org/#/jobs?repo=try&revision=48b7e30020a723bdf6f150efaf81bb634b0a0e58&selectedJob=139630353

The --no-artifact run also seems to clear the browser_eBay.js failures.
 * there are browser_UsageTelemetry_content_aboutHome.js failures but that's just because the run didn't include the pref change

**Comment by piatra** [comment]
Regarding browser_aboutHome_imitate.js, it looks like it was added when AS was already on by default. The test doesn't flip any prefs. Was it ever tested with the old about:newtab?

**Comment by Mardak** [comment]
Here's a run with your patch and not artifact:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=fef51103f9baa6966b0a9760e99b66ac33cc592d

This is the only one that seems to be consistently failing:
FAIL | [browser/components/search/test/browser_searchEngine_behaviors.js | Uncaught exception undefined - timed out after 50 tries.](https://treeherder.mozilla.org/logviewer.html#?job_id=139689492&repo=try&lineNumber=3253)

For browser_aboutHome_imitate.js, I'll probably skip it for win32 debug !e10s. It was added after activity stream, but it was just split from existing other aboutHome tests.

**Comment by piatra** [comment]
@Mardak ok that's should be hard to fix. The problem is here https://searchfox.org/mozilla-central/source/browser/components/search/test/browser_searchEngine_behaviors.js#108 gContentSearchController is only set for about:home not :newtab. Just trying to figure out what it should be replaced with.

**Comment by Mardak** [comment]
Should be able to get it from `gSearch` on Tiles: https://searchfox.org/mozilla-central/source/browser/base/content/newtab/search.js#12-13

i.e., gSearch._contentSearchController

**Comment by piatra** [comment]
```
diff --git a/browser/components/search/test/browser_searchEngine_behaviors.js b/browser/components/search/test/browser_searchEngine_behaviors.js
index d3bdee5b65cb..b534cde50758 100644
--- a/browser/components/search/test/browser_searchEngine_behaviors.js
+++ b/browser/components/search/test/browser_searchEngine_behaviors.js
@@ -105,8 +105,8 @@ function promiseStateChangeURI() {

 function promiseContentSearchReady(browser) {
   return ContentTask.spawn(browser, {}, async function(args) {
-    await ContentTaskUtils.waitForCondition(() => content.wrappedJSObject.gContentSearchController &&
-      content.wrappedJSObject.gContentSearchController.defaultEngine
+    await ContentTaskUtils.waitForCondition(() => content.wrappedJSObject.gSearch._contentSearchController &&
+      content.wrappedJSObject.gSearch._contentSearchController.defaultEngine
     );
   });
 }
```

**Comment by piatra** [comment]
My local build is artifact so it's failing for the same reason browser_eBay was failing. But that diff should fix browser_searchEngine_behaviors.js

**Comment by Mardak** [comment]
I pushed the patches to try with out artifact builds with activity stream enabled and disabled:
https://treeherder.mozilla.org/#/jobs?repo=try&author=edilee@gmail.com&fromchange=6e6e7343ead7034c9ef154692768bf10e03f6629&tochange=ae5bb9d81d88258f0a101cb47ce68cea179dd2c4

Ended up doing to support enabled and in case gSearch doesn't exist.
```diff
+    await ContentTaskUtils.waitForCondition(() => (content.wrappedJSObject.gContentSearchController ||
+      (content.wrappedJSObject.gSearch || {})._contentSearchController || {}).defaultEngine
```

**Comment by piatra** [comment]
From your runs it looks like we have another failure on Windows 10 x64 debug

- [ ] [dom/indexedDB/test/browser_permissionsPromptWorker.js | leaked 2 window(s) until shutdown [url = http://mochi.test:8888/browser/dom/indexedDB/test/browser_permissionsWorker.html](https://treeherder.mozilla.org/logviewer.html#?job_id=139938774&repo=try&lineNumber=20212)

**Comment by Mardak** [comment]
Disabled the leaking tests (browser_aboutHome_imitate, browser_screenshots_ui_check, browser_permissionsPromptWorker):

https://treeherder.mozilla.org/#/jobs?repo=try&author=edilee@gmail.com&fromchange=a835467c518361e027fe9498a6a4a80d42fc1b23&tochange=23d3488ab58ec272e068d546be01fba3df6bbf7a

**Comment by Mardak** [comment]
The bug is wontfix.
