### ISSUE TITLE
Add a URL field the Top Site editor so users can pick their own imagery 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#3766]
After we get a better handle on auto finding the Alexa top 1000 website iconography, we should give users a simple and direct way to customize what they see representing their top websites, by adding a URL field to the top site editor. 

With this tool, users will be able to override whatever we automatically find to show as an icon with something of their own choosing. 

Example: a user doesn't like their bank logo, or icon, well google something more interesting to represent something so mundane, copy the URL and paste it in the editing field. 

Boom! 

![image](https://user-images.githubusercontent.com/228979/32027891-8369fc50-b9a0-11e7-96e5-a80c570b95f3.png)

Could be better...

![image](https://user-images.githubusercontent.com/228979/32027930-b59d68f6-b9a0-11e7-9fd8-a6a18994ddcd.png)

Perfect! 

![screen recording 2017-10-25 at 04 14 pm](https://user-images.githubusercontent.com/228979/32027940-bcad6c40-b9a0-11e7-8e10-39a80b0bc626.gif)

**Comment by piatra** [comment]
@bryanbell what should happen in the case the user provides a URL but fetching it fails? (maybe the image size is too big). This will most likely happen asynchronously so it could look like "nothing happened".

**Comment by Mardak** [comment]
And does the url have to be an image? Could it just be a page and we capture a screenshot of it?

**Comment by tspurway** [comment]
need mock @bryanbell

**Comment by jenn-chaulk** [comment]
Aaron to attach measurements, but enough provided to get started.
Note - this will also address #3553

**Comment by aaronrbenson** [comment]
Updated spec for Top Site editor with details for the URL field: https://mozilla.invisionapp.com/share/7DEP1VMYX#/266461200_Top_Site_-_Edit_Image_

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421430
