### ISSUE TITLE
[Intermittent] Top Stories bookmarked status cannot be removed

### ISSUE THREAD

**Issue by IuliaCristescu4** [mozilla/activity-stream#3767]
https://bugzilla.mozilla.org/show_bug.cgi?id=1411970

[Affected versions]:
- 57.0b11 build1 (20171023180840)

[Affected platforms]:
- Windows 10 x64
- Ubuntu 16.04 x64
- macOS 10.13

[Steps to reproduce]:
1. Launch Firefox
2. Enable the Top Stories section (if it isn't already) 
3. Choose a random Pocket recommendation and bookmark it using its context menu
4. Reopen its context menu and click the "Remove Bookmark" option
5. Repeat step 4. 

[Expected result]:
- [step3] The chosen top story is properly bookmarked
- [step4] The chosen top story is successfully removed from bookmarks 
- [step5] The "Remove Bookmark" option is replaced by the "Bookmark" option

[Actual result]:
- [step3] The chosen top story is properly bookmarked
- [step4] The chosen top story is successfully removed from bookmarks 
- [step5] The "Remove Bookmark" option is still displayed (see the screencast https://goo.gl/pNKxDf)

[Additional notes]:
- The following error is displayed in the Browser Console https://goo.gl/XQT9kB, due to the fact that the bookmark was successfully removed from the first try
- I haven't been able to reproduce this issue using 58.0a1 (2017-10-25)
- The issue is intermittent and it's reproducible with different top stories

**Comment by Mardak** [comment]
Fixed by #3675
