### ISSUE TITLE
Add implementation to Activity Stream mochitests/head.js

### ISSUE THREAD

**Issue by paulsilaghi** [mozilla/activity-stream#3768]
We want to create mochitests to automate the following Activity Stream scenarios: https://bugzilla.mozilla.org/show_bug.cgi?id=1410333
To do that, we need most of the old NewTabPage methods from https://dxr.mozilla.org/mozilla-central/source/browser/base/content/test/newtab/head.js to be refactored to the new Activity Stream head.js: https://dxr.mozilla.org/mozilla-central/source/browser/extensions/activity-stream/test/functional/mochitest/head.js, considering the new functionalities.

Tests dep tree https://bugzilla.mozilla.org/showdependencytree.cgi?id=1410333&hide_resolved=1

**Comment by Mardak** [comment]
#3791 has been reverted by #3841. Reopening

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421844
