### ISSUE TITLE
Collect a more precise timestamp for each event

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#3777]
This is so we can compute time to first interaction.

Each event should have a precise timestamp like we have for our other performance metrics so that we can subtract it from load_trigger_ts to compute this.

Right now we only have a "receive_at" field populated by the server, rounded to the nearest minute, which is not useful for this computation.

**Comment by dmose** [comment]
@emtwo What do you by "event" here?  Can you give examples?

**Comment by emtwo** [comment]
Any user event that we send and is stored in the assa_events_daily table (e.g clicks, searches, etc)

**Comment by tspurway** [comment]
Let's dig into this and figure out exactly what the requirements are

**Comment by dmose** [comment]
We agreed in the experiment services meeting to collect this on all user events for greater server computation flexibility.  We still have to figure out whether we want to send an exact timestamp or a duration.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421904
