### ISSUE TITLE
getScreenshot error: Unix error 2 during operation open on file

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3779]
Also see: https://bugzilla.mozilla.org/show_bug.cgi?id=1413078

**Comment by piatra** [comment]
It sounds like this is caused by "browser.pagethumbnails.capturing_disabled" being set to `true`.
This is causing `BackgroundPageThumbs.captureIfMissing` to return early and not do a capture and `PageThumbs.getThumbnailPath` to use an old image no longer present in the cache.

As sson as I get a confirmation on bugzilla that resetting the pref fixes the issue I will close this. (not a real issue, pref should not be used)

**Comment by piatra** [comment]
Issue was caused by pref as described above.

**Comment by Mardak** [comment]
@piatra did you notice this error when working on #3791? It's spewing activity stream stack all over the console when running mochitests now. We definitely should make sure there aren't all these errors otherwise it makes it hard to track down test failures, and makes others suspicious of activity stream code when running tests.

**Comment by piatra** [comment]
The screenshots mochitests just turn off capturing. We could do the same. Tried a quick test and seems to fix it.

**Comment by piatra** [comment]
@Mardak previous comment isn't correct. Capturing is disabled in mochitest by default (probably for network request reasons). [Screenshots.jsm expects a screenshot to exist](https://github.com/mozilla/activity-stream/blob/master/system-addon/lib/Screenshots.jsm#L50). Should we check the `capturing_disabled` pref and return early from `getScreenshotFromURL`?

Sidenote: tiles used [getThumbnailURL](https://searchfox.org/mozilla-central/source/browser/base/content/newtab/sites.js#188) and worked around using the `File.open` API, do you know why we do it like this?

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1413078
