### ISSUE TITLE
validate that the timestamps used in activity-stream telemetry are comparable

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3780]
Based on some discussion between @Mardak and @mikeconley, there's some concern that our performance telemetry timestamps may not be directly comparable across chrome and content. 

I don't yet see how that could be true, but I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1413352 and needinfo-ed some folks who can help us understand better.

In addition to that, we need to investigate if there's a way to manually validate that the timestamps are comparable.  In an ideal world, this would be in the form of an integration test, to ensure that no platform assumptions change out from under us, but the first step is just to figure out how to do it at all. 

First off, though, to just test it manually, the idea is write some code to just send a bunch of messages with timestamps in both directions and see if the sent & received "absolute timestamps" are very close in time and in the right order.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1413352
