### ISSUE TITLE
Failed to associate icons to topsites that redirect

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#3788]
This is reproducible for sites like "python.org", but not for "www.python.org". 

Attached some records from my `places.sqlite` and `favicons.sqlite` below. Looks like Firefox favicon service didn't associate any icons with the original URL "python.org" (i.e. page id 17, 18), instead, it did that for the FQDN "https://www.python.org/" (i.e. page id 19), which links to 4 icons (19, 20, 21, 22), and icon 19 is the rich one.

I believe `NewTabUtils.getTopsites` has combined page 17, 18, and 19, and returned `python.org` as it has the highest frecency score, but this URL doesn't have any icon attached in `favicons.sqlite`.

An easy fix could be try another fetch with the FQDN URL, if the original one failed. 

* moz_places
```
id | url | title | rev_host | visit_count | hidden | typed | frecency |
17|http://python.org/||gro.nohtyp.|2|0|1|125|
18|https://python.org/||gro.nohtyp.|2|1|0|50|
19|https://www.python.org/|Welcome to Python.org|gro.nohtyp.www.|2|0|0|100|

```

* moz_icons
```
id | icon_url | width |
19|https://www.python.org/static/apple-touch-icon-144x144-precomposed.png|144|
20|https://www.python.org/static/favicon.ico|16|
21|https://www.python.org/static/favicon.ico|32|
22|https://www.python.org/static/favicon.ico|48|
```

* moz_pages_w_icons 
```
id | page_url | page_url_hash
14|https://www.python.org/|47358693054934
```
* moz_icons_to_pages
```
page_id | icon_id
14|19
14|20
14|21
14|22
```

**Comment by ncloudioj** [comment]
We could add a flag in [NewTabUtils.getTopFrecentSites](http://searchfox.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#1147) when we combine those `www` and `not-www` sites. Then use the url with `www` to fetch the favicon, only fall back to the `not-www` one if that fetch fails.

@Mardak Thoughts?

**Comment by Mardak** [comment]
There is some existing fallback icon behavior for switching between http/https:
http://searchfox.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#961-964

I suppose maybe without exposing too much detail that it was replaced by a better link, instead of a flag to try with-www, it would have an alternate url for checking for icon. This way, it would be closer to supporting the case of handling any redirected urls.

To be clear, the same bug can happen the other way, e.g., you type in www. and end up at no-www. and the icon is at no-www.

**Comment by ncloudioj** [comment]
Another finding from the investigation for "www.nike.com".

In this case, the top site URL was `www.nike.com/ca/en_gb/`, it failed to fetch the rich icon with the default protocol `http://` as `http://www.nike.com/ca/en_gb/`. However, it succeeded with the protocal `https://`.

I assume we could add a size check at http://searchfox.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#962, so that it'll try the other protocol if the fetched icon isn't the rich one.

**Comment by rlr** [comment]
There is also a `http://` vs `https://` issue. For example:

1) Visit http://airbnb.com
2) Call:

```
PlacesUtils.favicons.setAndFetchFaviconForPage(
  Services.io.newURI("http://airbnb.com"),
  Services.io.newURI("https://a0.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png"),
  false,
  PlacesUtils.favicons.FAVICON_LOAD_NON_PRIVATE
);
```

3) Open favicons.sqlite and you'll see:

```
sqlite> select * from moz_icons;
...
11|https://a0.muscache.com/airbnb/static/icons/android-icon-192x192-c0465f9f0380893768972a31a614b670.png|2123766952|192|0||1510166470440|�PNG
...

sqlite> select * from moz_pages_w_icons;
...
10|https://www.airbnb.com/|47357413054760
...

sqlite> select * from moz_icons_to_pages;
...
10|11
...
```

So, even though I set the icon for `http://...`, it's in the database as `https://...` and `NewTabUtils.activityStreamProvider._addFavicons()` doesn't seem to find it when I request it again for the `http://...` url.

**Comment by Mardak** [comment]
The airbnb should be the same originally filed issue of top site being without www and favicon associated to with-www. The http/https difference is already handled.

**Comment by rlr** [comment]
> The airbnb should be the same originally filed issue of top site being without www and favicon associated to with-www. The http/https difference is already handled.

Ah, yeah. It is being saved with the www.

Interestingly, if you look at the bookmarks library:

<img width="735" alt="screen shot 2017-11-08 at 1 52 26 pm" src="https://user-images.githubusercontent.com/36629/32568453-46aba448-c48c-11e7-9459-d716293a4114.png">

Why do we choose the redirect for Top Sites instead of the destination?

**Comment by Mardak** [comment]
Top Sites picks the thing that has higher frecency, where the url you type in gets a big frecency bonus. This fixed an issue #3102 where www.news.ycombinator.com doesn't exist and had a low frecency score compared to the actual page.

**Comment by Mardak** [comment]
The fix that @rlr is looking at of adding tippy top favicon data to moz_favicons is somewhat interesting for fixing this bug in that it does indeed fix it in the case where we do have tippy top, but we could also make it detect that a similar (http/https) or redirected (www/no-www) page has a favicon and insert the data to the top site page. !

Basically, we can remove the special http <-> https fallback logic that happens on every top site request and just directly insert a favicon to the specific top site page. We run this "cleanup" / "find better favicon" logic when we notice there's no favicon. Although I suppose we should be careful to not introduce an issue similar to #3763 where we fail to find a favicon and should avoid unnecessarily retrying to fail repeatedly.

**Comment by ncloudioj** [comment]
As @Mardak metioned above, this is partly fixed via 80baa634a3ab40d04dd4acbc4d848adee4af2e26, where the `FaviconFeed` associates the tippy top icon to the page on action `RICH_ICON_MISSING`. Given that we have a large collection of tippy top icons, it should be able to cover quite a lot of ground, and the to-be-added telemetry will lead us to the actual coverage.

For those sites that are not in the tippytop, we'd have to add the "cleanup" / "find better favicon" logic for both 1), "http" vs "https" and 2), "www" vs "no-www". To avoid the unnecessary retry, we need to store the status either in the `FaviconFeed` or in the satellite cache.

**Comment by ncloudioj** [comment]
Turns out the page redirection also affects the non-rich icons.

<img width="251" alt="screen shot 2017-11-15 at 2 30 00 pm" src="https://user-images.githubusercontent.com/1455254/32856038-9f84cba0-ca11-11e7-8ff7-2420f0e0060b.png">

In this case, the top sites are "www.taobao.com" and "http://americanexpress.ca/", which get redirected to "https://world.taobao.com/" and "https://www.americanexpress.com/canada/", respectively. In the favicon database, the icons are actually linked to the redirected URLs instead of the original ones.

This is more complex to fix than the previous cases. Maybe it's a won't fix?

**Comment by Mardak** [comment]
Right, I noted in https://github.com/mozilla/activity-stream/issues/3788#issuecomment-341740214 that we can more generally handle redirected pages with the "favicon missing, so find a better icon" behavior (as opposed to specifically targeting www vs no-www)

**Comment by ncloudioj** [comment]
It's tricky to handle those arbitrary redirects though, so I took a look at the implementation of [getFaviconDataForPage](https://searchfox.org/mozilla-central/source/toolkit/components/places/mozIAsyncFavicons.idl#183), if it can't find any icon for the target URL, it uses the root icon (i.e. {URL}/favicon.ico) as the fallback if any.

Unless we could figure out the "better" page URL before using it to fetch the icon, it'll be hard to cover all the redirects mentioned above.

**Comment by Mardak** [comment]
Well, in the missing icon case, we're async figuring out what tippy top or other icon to set as the icon for the page. So for a page with missing icon, we can look at moz_historyvisits to see where it redirects to and figure out what icon to use.

**Comment by ncloudioj** [comment]
Oh right, I totally forgot moz_historyvisits, which has all the detail about that visit. I was looking at columns like `hidden` and `typed` in moz_places.

**Comment by ncloudioj** [comment]
Per :mak, there is no existing "visit path" API available to find out the terminal redirection for a given URL, see [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=320831#c33). He also suggested that:

* Try sqlite's CTE expressions "WITH RECURSIVE", but this should be used with extra care for the performance's concern
* We can make `favicon.getIconForPage` redirect-aware, and the Places team is open to add that support if needed. This need further brainstorming

The second solution sounds like a better plan to me. But until it gets implemented, we can still try the first one at the same time.

**Comment by Mardak** [comment]
Given the fallback and async nature of this fixup logic, it's probably not too bad for FaviconFeed to do queries against moz_historyvisits to find the final redirection. Or if we want to handle most of the cases, just follow one redirection to look for favicons.

**Comment by ncloudioj** [comment]
@Mardak Sounds good.

Filed a feature request bug here https://bugzilla.mozilla.org/show_bug.cgi?id=1418080 for more brainstorming.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421428

**Comment by ncloudioj** [comment]
This is now fixed. All the missing icons are shown in the topsites.

<img width="517" alt="screen shot 2018-02-01 at 11 20 52 am" src="https://user-images.githubusercontent.com/1455254/35689705-1b4a391a-0742-11e8-8520-709e2352d79e.png">
