### ISSUE TITLE
Use appropriate platform-specific panelarrow image and sizing

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3792]
With #3784, we now have per-platform css, so the double-background-image from #3644 to get an available icon isn't necessary as we can just directly reference the icon for that platform.

This also means we can get rid of the `parsable_css` whitelist entry:
https://searchfox.org/mozilla-central/source/browser/base/content/test/static/browser_parsable_css.js#91-99

Also, turns out the size of the image is slightly different depending on the platform.

**Comment by piatra** [comment]
Follow up bugzilla bug to remove the whitelist entry
> https://bugzilla.mozilla.org/show_bug.cgi?id=1415892
