### ISSUE TITLE
IndexedDB errors in nightly

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#3794]
I am getting IndexedDB errors in Nightly 58.0a1 (2017-11-03) on every new tab. Unfortunately, the error information is not particularly helpful: 

```js
{
 DOMException
code: 0
columnNumber: 0
data: null
filename: ""
lineNumber: 0
message: "The operation failed for reasons unrelated to the database itself and not covered by any other error code."
name: "UnknownError"
result: 2154168321
stack: ""
}
```

Being thrown on the open request here:

https://github.com/mozilla/activity-stream/blob/caaa2fd0d8c878eec9e6a4be62b3be8e366704e7/system-addon/content-src/lib/snippets.js#L120

**Comment by k88hudson** [comment]
Hm, I am seeing this in beta as well....

**Comment by piatra** [comment]
Is this AS related? I'm seeing the same failure on other websites trying to use IndexedDB.

**Comment by dmose** [comment]
Note that indexedDB is enabled on about:home but not about:newtab.  Could that be related ?

https://dxr.mozilla.org/mozilla-central/source/browser/components/about/AboutRedirector.cpp#81

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421427
