### ISSUE TITLE
Pocket disclaimer link is not clickable

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3796]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/810040/32438856-6b71df28-c2ec-11e7-936a-6a5a6e9eda77.png">
Pocket disclaimer link does not have an href.

**Comment by csadilek** [comment]
The reasons for this not being clickable for some users is that we launched a Shield study last week targeting the topstories.options pref just before we got this link. So, for users in this study the href won't be configured. I will prepare a PR with a client-side fallback in case the config is missing.
