### ISSUE TITLE
Pinned cache link does not expire on pref change

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3800]
The pinned cache link is expired on blocking a website and pinning/unpinning. If you clear the pref your pinned sites do not change. I came across this when writing tests, might be useful for some users as well (clear all pinned sites without having to repeatedly click).

https://github.com/mozilla/activity-stream/blob/1da4378c310323360c39c37b7938d141ae810748/system-addon/lib/TopSitesFeed.jsm#L39

**Comment by Mardak** [comment]
FYI, expiring the cache won't make things update as NewTabUtils.pinnedLinks doesn't look for pref changes either.
