### ISSUE TITLE
Pocket notice text and button overlap on Windows

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3801]
I assume this is true for all locales with long strings.

<img width="950" alt="image" src="https://user-images.githubusercontent.com/810040/32561877-9f824dbc-c4ad-11e7-92b0-2efbe45c110f.png">

This is on the reference laptop, Windows @ 1920x1080

**Comment by csadilek** [comment]
Hm this works fine on Mac but wasn't tested on other platforms:

![screen shot 2017-11-08 at 12 01 14 pm](https://user-images.githubusercontent.com/472523/32562443-af0dd73c-c47c-11e7-9646-d2117696500b.png)

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/2796c4cd23e3
