### ISSUE TITLE
Very long domain names overflow from the Highlight borders

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3805]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1415665

![image](https://user-images.githubusercontent.com/810040/32576989-d94dc780-c4d8-11e7-84fd-99faacfbceed.png)

**Comment by ItielMaN** [comment]
This could potentially apply also to the top sites. Not sure.

**Comment by piatra** [comment]
This only affects highlights 

<img width="160" alt="image" src="https://user-images.githubusercontent.com/810040/32604005-2f67b61c-c54c-11e7-9d25-5a120355bcad.png">

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/acde061a6109
