### ISSUE TITLE
Perma-fail: debug browser_highlights_section.js | there should be 1 of [data-mochitest='highlights-card-placeholder'] found 3

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3820]
@piatra this seems to be failing on linux and windows:

 FAIL | browser/extensions/activity-stream/test/functional/mochitest/browser_highlights_section.js | there should be 1 of [data-mochitest='highlights-card-placeholder'] found 3
Stack trace: chrome://mochitests/content/browser/browser/extensions/activity-stream/test/functional/mochitest/head.js:check_highlights_elements:125
https://treeherder.mozilla.org/logviewer.html#?job_id=143511024&repo=pine&lineNumber=14901

As well as a bunch of
 FAIL | browser/extensions/activity-stream/test/functional/mochitest/browser_topsites_section.js | A promise chain failed to handle a rejection: cache is undefined - stack: null Rejection date: Fri Nov 10 2017 01:04:34 GMT+0000 (UTC) - false == true
JS frame :: resource://testing-common/PromiseTestUtils.jsm :: assertNoUncaughtRejections :: line 253 
https://treeherder.mozilla.org/logviewer.html#?job_id=143511024&repo=pine&lineNumber=15536

That latter one is failing on all platforms:
mac: https://treeherder.mozilla.org/logviewer.html#?job_id=143510757&repo=pine&lineNumber=27770
win32-noe10s: https://treeherder.mozilla.org/logviewer.html#?job_id=143516756&repo=pine&lineNumber=28571
win32-e10s: https://treeherder.mozilla.org/logviewer.html#?job_id=143516761&repo=pine&lineNumber=40261
win64: https://treeherder.mozilla.org/logviewer.html#?job_id=143518254&repo=pine&lineNumber=38405

**Comment by piatra** [comment]
What does `cache` refer to? There is no variable with that name in our mochitests.
