### ISSUE TITLE
Network requests made in mochitests

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3821]
> FATAL ERROR: Non-local network connections are disabled and a connection attempt to s3.amazonaws.com (54.231.40.106) was made

https://treeherder.mozilla.org/logviewer.html#?job_id=143668484&repo=try&lineNumber=14636

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/6ff9a23d3212
