### ISSUE TITLE
Not all Top Sites and Highlights show their correct image preview when dragged

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3822]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415907

[Affected versions]:
- Firefox 58.0a1 Build ID 20171108110838

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a clean new profile.
- Have a sync account with enough History and Bookmarks to populate the sections.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and sync your history.
2. Restart the browser and open a new tab.
3. Wait for Top Sites to load images.
4. Drag all the Top Sites and observe their previews.

[Expected results]:
- The Top Site images are shown as a drag previews.

[Actual results]:
- Some Top Sites show a white preview.

[Notes]:
- The issue is also reproducible when dragging Highlights.
- If you drag the tiles a second time they will show their correct image preview.
- Attached a screen recording of the issue:
![missing preview when dragging a top site or highlight](https://user-images.githubusercontent.com/18304511/32664175-1d2595da-c639-11e7-92b8-444966b969a9.gif)

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1415907
