### ISSUE TITLE
Search bar box shadow does not look correct on different zoom levels

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3823]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415493

[Affected versions]:
- Firefox 58.0a1 Build ID 20171106100122

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Open the browser and open a new tab.
2. Set the page zoom level to 150%.
3. Observe the Search bar highlight.

[Expected results]:
- The highlight is uniform.

[Actual results]:
- Some parts of the highlight are more prominent.

[Notes]:
- The issue can be observed at different zoom levels.
- Attached a screen shot of the issue:
![different zoom levels](https://user-images.githubusercontent.com/18304511/32664165-1565f40c-c639-11e7-8bd4-6a53810d275f.png)

**Comment by tspurway** [comment]
@SoftVision-CiprianMuresan to retest in older builds to figure out if it's a graphics bug

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1415493
