### ISSUE TITLE
Activity Stream is only disabled/enabled after the second new tab is opened

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3824]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415492

[Affected versions]:
- Firefox 57 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the browser and navigate to about:config.
2. Click "I accept the risk!" and search for browser.newtabpage.activity-stream.enabled.
3. Set the pref to "false".
4. Open a new window and observe the behavior.
5. Open another new window and observe the behavior.

[Expected results]:
- Step 4 & 5: The old about:newtab is displayed.

[Actual results]:
- Step 4: Activity Stream is displayed.
- Step 5: The old about:newtab is displayed.

[Notes]:
- The issue is also reproducible when you enable Activity Stream.
- Attached a screen recording of the issue:
![disabled or enabled only at second new tab](https://user-images.githubusercontent.com/18304511/32664758-e6884be2-c63a-11e7-9d26-86b32e8eb770.gif)

**Comment by tspurway** [comment]
wontfix this, as Tiles is going away
