### ISSUE TITLE
New content is displayed only on the second new tab

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3825]
https://bugzilla.mozilla.org/show_bug.cgi?id=1415491

[Affected versions]:
- Firefox 58.0a1 Build ID 20171106100122

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Create a new profile and start the browser.
2. Visit 50 different pages. (from www.reddit.com/r/news)
3. Open a new tab and observe the page.
4. Open another new tab and observe the page.

[Expected results]:
- Step 4 & 5: New content is displayed on the page.

[Actual results]:
- Step 4: Default content is displayed.
- Step 5: New content is displayed.

[Notes]:
- Attached a screen recording of the issue:
![new content appears only after a second new tab is opened](https://user-images.githubusercontent.com/18304511/32664771-ecc0e848-c63a-11e7-918e-bf1ce2498f23.gif)

**Comment by tspurway** [comment]
see also #3331 (duplicate)
