### ISSUE TITLE
The import button is not aligned properly

### ISSUE THREAD

**Issue by piatra** [mozilla/activity-stream#3831]
Windows 10, Nightly 59

![import_banner](https://user-images.githubusercontent.com/810040/32734713-178a5e92-c893-11e7-8b18-13b026d0cd62.png)

Caused by https://github.com/mozilla/activity-stream/commit/73ea6dc43a149fb9a31a0b23cd03d6a5b97d13e5

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/18524c7a40b3
