### ISSUE TITLE
Better handling of failure cases for remote tippy top fetch

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3834]
Right now, the `FaviconFeed` can get into a state where it tries to fetch on every `SYSTEM_TICK` event. This will happen if there is no cache or the cached data is old and the remote endpoint returns a status code that isn't 200 (ok) or 304 (not modified).

We should probably add some sort of backoff algorithm.

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/6ff9a23d3212
