### ISSUE TITLE
Upgrade React Intl to latest version

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3836]
We need to do this in order to upgrade to React 16.  As part of it, we should either file an issue to make React Intl warnings break our tests, or we should just fix that error.

**Comment by dmose** [comment]
[Bug 1418130](https://bugzilla.mozilla.org/show_bug.cgi?id=1418130) will be the github export that will contain these changes.  I've attached a `license.html` update patch to that bug, and requested a review from gerv.

**Comment by dmose** [comment]
For these following along at home, until this merges, we've been using react-intl 2.2.3.  This upgrades us to 2.4.0.  The changes are listed on the react-intl [github releases page](https://github.com/yahoo/react-intl/releases).

https://github.com/facebook/prop-types#prop-types has information about how prop-types has (slightly) changed as it's been split out from React.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421426
