### ISSUE TITLE
Telemetry for remote tippy top

### ISSUE THREAD

**Issue by rlr** [mozilla/activity-stream#3837]
We are putting icons fetched from the remote tippy top manifest into the rich icons database (moz_icons), so currently they will appear as rich icons in telemetry. We are already adding a `ref` to the favicon URLs (`#tippytop`).  We need to update `NewTabUtils` to check the URL's `ref` and add a `isTippyTop` property based on it.

From IRC convo with @Mardak:

> Mardak> r1cky: we could make https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/NewTabUtils.jsm#935-936
> resolve(iconURI ? {isTippyTop: iconURI.ref === "tippytop", …
> what a hack ;)

**Comment by Mardak** [comment]
Depending on how #3788 gets fixed, there might be other `ref`s being used. Not sure if we should just return the the `ref` to avoid needing to change `NewTabUtils` on each additional type.

**Comment by Mardak** [comment]
https://hg.mozilla.org/releases/mozilla-beta/rev/6ff9a23d3212
