### ISSUE TITLE
Make sure go.twitch.tv gets a tippy top icon

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3842]
Either we need to include "go.twitch.tv" as a domain, or be less strict on domain matching similar to how we allow "www.domain" and "domain" to use the same icon. Maybe it should try for an exact match first then fall back to a higher domain match? @rlr 

This would reduce the likelihood of https://bugzilla.mozilla.org/show_bug.cgi?id=1412505

**Comment by Mardak** [comment]
The original approach in #3843 is reverted with an alternate approach of making sure the manifest includes "go.twitch.tv"

**Comment by Mardak** [comment]
At least according to https://bugzilla.mozilla.org/show_bug.cgi?id=1412505#c40
> go.twitch.tv is no longer being used as a subdomain for twitch.tv since yesterday.

And quick testing seems to show that's the case. So maybe this is wontfix? Although those who have pinned a go.twitch.tv top site would still try to get screenshots…

**Comment by rlr** [comment]
See https://activity-stream-icons.services.mozilla.com/v1/icons.json.br :

```
    {
        "domains": [
            "twitch.tv", 
            "go.twitch.tv"
        ], 
        "image_url": "https://m.twitch.tv/apple-touch-icon.png"
    }, 
```

**Comment by rlr** [comment]
<img width="781" alt="screen shot 2017-11-17 at 8 41 31 pm" src="https://user-images.githubusercontent.com/36629/32975674-b8181858-cbd7-11e7-834a-246658fa6622.png">
