### ISSUE TITLE
Bookmarking a Pocket recommendation makes it appear in History even if it wasn't visited

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/activity-stream#3849]
https://bugzilla.mozilla.org/show_bug.cgi?id=1417363

[Affected versions]:
- Latest Nightly
- beta 58.0b3

[Affected platforms]:
- Windows 10 x64
- Ubuntu 16.04 x64
- macOS 10.13

[Prerequisites]:
- "browser.search.region" is set to "US" in about:config

[Steps to reproduce]:
1. Open the browser and open a new tab.
2. Bookmark a Pocket recommendation from the context menu, without actually visiting the site.
3. Observe the card's status.
4. Access hamburger menu - Library - History

[Expected result]:
- The Pocket recommendation is not listed in History.

[Actual result]:
- The Pocket recommendation is listed in the History. 

[Regression range]:
- last good build id: 20171103100331
- first bad build id: 20171104100412
Mozregression concluded that [bug 1413550](https://bugzilla.mozilla.org/show_bug.cgi?id=1413550) might be the cause of the problem. 

[Additional notes]:
- If you restart the browser, the article disappears from the Pocket recommendation section. I guess this is expected considering the fact that the browser perceives it as being visited.

**Comment by piatra** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1417363#c1
