### ISSUE TITLE
Search box gets focus after entering input in location bar for about:home

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#3859]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1417943

This is because about:home has focused the search box, but the browser chrome has focus until navigating away, which then focuses the content.

**Comment by SoftVision-CiprianMuresan** [comment]
Last good revision: 8ce27eeef7662c04deed1328ff25937e530aaf79
First bad revision: e3221268f8fc67bd461c2e04ed486e264c070abf
Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=8ce27eeef7662c04deed1328ff25937e530aaf79&tochange=e3221268f8fc67bd461c2e04ed486e264c070abf

This behavior seems to have been regressed by [bug 1403215](https://bugzilla.mozilla.org/show_bug.cgi?id=1403215).

And it's also reproducible when you click the Search arrow without having a keyword in the search bar.

**Comment by Mardak** [comment]
Sounds like we're removing the auto focus behavior, so this will also fix #3506 and fix #3505

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1417943
