### ISSUE TITLE
Redux.jsm does not appear to be a production build

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3860]
Unless process.env.NODE_ENV is magically set somewhere in the environment in a way that I haven't yet found.  There are a bunch of checks of this var in the code itself.

CC @k88hudson

**Comment by tspurway** [comment]
kate to verify

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1425491
