### ISSUE TITLE
Add Recently Pocketed Items to Highlights

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#3868]
This is related/blocked on weighted highlights, though alternatively we could just treat pocketed items as regular bookmarks, and just insert them into the highlights section.

Note that this will not create a new section.

If you are not logged into Pocket, you just won't see any pocket items.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1425496
