### ISSUE TITLE
Collect "region" and "profile_creation_date" for AS

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#3876]
This is just a clone of the Pingcentre bugs [#111](https://github.com/mozilla/ping-centre/issues/111) and [#117](https://github.com/mozilla/ping-centre/issues/117). The code change has already been merged. We just need to update the document of AS, and finish the data review here.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421422
