### ISSUE TITLE
Users having difficulty knowing how to hide sections in New Tab

### ISSUE THREAD

**Issue by AmyYLee** [mozilla/activity-stream#3889]
There's been feedback that users are having difficulty finding the New Tab Preferences panel to hide sections of New Tab. 

Proposing to add a "hide" button on each section to make it more visible. See spec for details.

[New Tab – Hide Section Spec](https://mozilla.invisionapp.com/share/QFEPZRATX)

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1422079
