### ISSUE TITLE
Let's have 2 rows of topsites by default

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#3896]
We've seen in several studies and data sources that people want more Top Sites. Let's consider having 2 rows by default. Here are some sources:

1. ~36% of survey results from 57 Release about Top Sites want more rows - https://docs.google.com/spreadsheets/d/1hVyKOsgshBxZurYM3V7d5fy1ceFBi3dibO8XokdcRxw/edit#gid=1826461623

2. ~54% of all weekly interactions are clicks on Top Sites: https://sql.telemetry.mozilla.org/queries/48887?p_channel=release&p_granularity=week#131759

3. ~22% weekly click through rate on Top Sites. That's almost 2x the search rate, 31x the Pocket click rate, 12x the highlight click rate. https://sql.telemetry.mozilla.org/queries/48831?p_granularity=week&p_channel=release#131668

4. ~2% absolute increase in click rates on new tab observed in test pilot study. https://sql.telemetry.mozilla.org/dashboard/activity-stream-a-b-testing-two-rows-topsites

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1425489
