### ISSUE TITLE
Rework context clues in Spotlight (needs documentation)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#391]
I can't remember if this was regarding deleting Featured Highlighted sites instead of hiding them (ref: #382), of if was about confusion around how seemingly stale bookmarks were featured because you bookmarked it 2 years ago but visit it frequently.
Or maybe related to the conversation about adding icons for Bookmark icons versus just a "visited" icon.

**Comment by nchapman** [comment]
I think my advice on this one is that we add an icon for the type (bookmark or history) and then use the date of your most recent interaction (rather than when the bookmark was created).
