### ISSUE TITLE
Verify fill in behavior after deleting spotlight items (as a last resort include mozilla tiles)

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#393]
Ref: #389

Not sure how this differs from #389

**Comment by nchapman** [comment]
> Not sure how this differs from #389

This has to do with filling in more items as you delete them rather than just making sure they're filled in to begin with.

**Comment by nchapman** [comment]
We should continue to fill in Top Sites and Highlights as you delete them rather than showing empty boxes.
