### ISSUE TITLE
Make timeline/bookmarks pages larger than 25

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#402]
"Make timeline/bookmarks pages larger than 25 (50?)"

Currently when you click the "See more activity" button at the bottom of your Activity Stream/Bookmarks pages, it loads ~25 items from Embedly proxy. We should maybe bump that up to 50 items (2 different requests to embedly proxy?) until we do/decide on infinite scrolling.

![activity_stream](https://cloud.githubusercontent.com/assets/557895/14129012/de60d966-f5da-11e5-879e-8e081174d3af.png)

**Comment by oyiptong** [comment]
Needs to be prioritized

**Comment by k88hudson** [comment]
Closing this since we now have infinite scroll!
