### ISSUE TITLE
Revisit top sites vs top pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#405]
Currently the "Top Sites" links don't necessarily take you to "sites" but sometimes "random" pages within a site (such as a YouTube video about lip syncing Muppets you were watching last week).
It can be confusing if you were expecting to go to a site (because we only show the site name, and we call the section Top Sites).

This logic breaks down if you're expecting to go to a specific sub-Reddit page instead of top level www.reddit.com.

**Comment by pdehaan** [comment]
We should revisit this, there are a few oddly sharp edges here.

<img width="960" alt="new_tab" src="https://cloud.githubusercontent.com/assets/557895/15950860/a050b496-2e67-11e6-9d00-d8d7b228b84f.png">

(A) I have two generic links to "reddit.com" (but I don't know where they go or URLs until I hover over them and look at the address in the lower-left corner).
- https://www.reddit.com/r/videos
- http://reddit.com/r/worldnews

(B) Plus, I'm trying to find the YouTube video I was _just_ looking at, but it doesn't show up in my **Recent Activity** with a preview because it's buried away in **Top Sites**.

--- 

I almost feel like **Top Sites** should just SQL through all my history (or last 1000 history items) and extract the domains and sort by the 6 most common domains and then just display top-level domains and not dedupe against anything. That way my Top Sites will literally be my most popular sites that I visit.

**Comment by oyiptong** [comment]
there is a potential duplication issue with http vs https versions of the same url. can someone please verify?

**Comment by sarracini** [comment]
Our deduping has gotten much better in the last year 😂 I'll close this since a lot of work has been done with our top sites
