### ISSUE TITLE
Consider adding url/domain to spotlight

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#407]
Currently I have no idea what URL my Spotlight/Highlight result will go to, unless I can infer it from the title.

We should consider adding the pretty-URL to the result somewhere.
@bryanbell to clarify if we want it above or below the "Visited a day ago" label, since I don't see any design in http://people.mozilla.org/~shorlander/activity-stream/activity-stream-latest/start-page.html# for that.

![new_tab](https://cloud.githubusercontent.com/assets/557895/14129139/2e9b52e8-f5dc-11e5-970a-3998cc932c11.png)

**Comment by k88hudson** [comment]
Note that url is currently used as a fallback for description
