### ISSUE TITLE
Sticky search box with instrumentation

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#408]
@bryanbell is passionate about having a sticky search bar when scrolling the New Tab/Activity Stream page. I mean, like, _REALLY_ passionate.

Reference UX: http://people.mozilla.org/~shorlander/activity-stream/activity-stream-latest/start-page.html

**Comment by bryanbell** [comment]
#509" is unrelated to my desire to have the search bar or the new tab page remain at the top of the screen when scrolling. 

The timeline surface is a web-app, and therefore its controls need to remain visible at all times.

**Comment by edangor** [comment]
But then the search bar should be more by the center so that it becomes a focus point, beacuase at the moment you just see something that got stuck at the top of the page while you searched through your history.

**Comment by edmoz** [comment]
UX/PM Triage: P3 closing for now
