### ISSUE TITLE
Activity collapsing

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#409]
I have no idea what this is about, but I'm assuming it's related to the following screenshot:

![firefox_start](https://cloud.githubusercontent.com/assets/557895/14129222/122ae64a-f5dd-11e5-80eb-397cd8ad16a7.png)
**Figure 1:** via http://people.mozilla.org/~shorlander/activity-stream/activity-stream-latest/start-page.html

**Comment by nchapman** [comment]
Closing in favor of [tracking this in Trello](https://trello.com/c/6WRXiwEU/32-i-want-to-see-my-activities-clustered-by-site-so-that-i-can-more-easily-see-more-of-the-sites-i-ve-visited).
