### ISSUE TITLE
Highlighted search results

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#410]
We should highlight search results, so we can do better activity collapsing (Ref: #409) and group search results.

![firefox_start](https://cloud.githubusercontent.com/assets/557895/14129245/5d265760-f5dd-11e5-9372-a6153869e34d.png)

**Comment by nchapman** [comment]
Closing in favor of [tracking this in Trello](https://trello.com/c/6WRXiwEU/32-i-want-to-see-my-activities-clustered-by-site-so-that-i-can-more-easily-see-more-of-the-sites-i-ve-visited).
