### ISSUE TITLE
Show synced tabs label in Highlights

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#411]
I think this is related to the "Last Opened on Luke's iPhone 6" and "Last Opened on Lukes iPad 6" footers on the Highlights section.

![firefox_start](https://cloud.githubusercontent.com/assets/557895/14129283/a274b2e4-f5dd-11e5-8f21-325cc578e070.png)

**Comment by sarracini** [comment]
trello spec:  https://trello.com/c/NBKOCvmn

**Comment by oyiptong** [comment]
We should clarify what "synced tabs" means. Does it mean currently open tabs?
If so, we can implement this feature.

We won't be able to for history items, as the device origination is not stored anywhere

**Comment by bryanbell** [comment]
https://trello.com/c/NBKOCvmn

**Comment by bryanbell** [comment]
![pasted_image_7_7_16__5_19_pm](https://cloud.githubusercontent.com/assets/228979/16673892/27d5fe3e-4467-11e6-9b7d-81103a2ef9e4.png)
Seems there's some mechanism that appends "firefox on..." in front of device name. This should be eliminated, and or filtered out.

**Comment by bryanbell** [comment]
let's drop the "from" from the context clue given the size constraints.

<img width="755" alt="image" src="https://cloud.githubusercontent.com/assets/228979/16673998/63fc8490-4468-11e6-84f2-0be091b80882.png">

**Comment by bryanbell** [comment]
The icon you need @rlr 


[glyph-sync-16.svg.zip](https://github.com/mozilla/activity-stream/files/353326/glyph-sync-16.svg.zip)

**Comment by rlr** [comment]
@bryanbell awesomesauce, thank you!

@nchapman do we know what the initial rules will be to show a synced tab or not in the highlights? I know you mentioned only fresh tabs but not sure if that's hours or days. Thanks!

**Comment by edmoz** [comment]
From product meeting, this is blocked on scoring system heuristics.  We should probably move this to backlog.

**Comment by nchapman** [comment]
We've decided that this should work like bookmarks: history items that are currently an open synced tab should get a boost in scoring (similar to bookmarks but not as strong) and contain the new context labeling [mentioned above](https://github.com/mozilla/activity-stream/issues/411#issuecomment-231245919).
