### ISSUE TITLE
Implement context menu share

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#414]
This ticket should implement a share action in the existing context menu on New Tab/Timeline items. This will require add-on apis as well as new UI in the `LinkMenu` component. It should use the same strategy/options that are currently in the share plane (this will be iterated on later).

[Edit by @k88hudson]

> Currently you can only delete Top Sites and Highlighted sites.
But for Top/Recent Activity and Bookmarks, you can share and do "...".
Ideally we should be able to share Highlighted results since they're presumably "important" content.

> ![firefox_start_and_firefox_start_and_new_tab](https://cloud.githubusercontent.com/assets/557895/14129409/d3f6b398-f5de-11e5-8b8b-4e1ece842308.png)

> ![firefox_start_and_firefox_start_and_new_tab](https://cloud.githubusercontent.com/assets/557895/14129413/df311d66-f5de-11e5-818e-aa4a67ad1007.png)

> UX Ref: http://people.mozilla.org/~shorlander/activity-stream/activity-stream-latest/start-page.html

**Comment by edmoz** [comment]
spec: https://trello.com/c/uRoUOISr

**Comment by k88hudson** [comment]
Before this can go to engineering, spec still needs:
- [ ] comps for expanded "share" menu: what do the choices look like? Does it simply open the share plane menu up top? etc.
- [ ] how are the options determined? What relationship does this has to the share plane data?

cc @aaronrbenson @bryanbell

**Comment by bryanbell** [comment]
![context menu - share 2x](https://cloud.githubusercontent.com/assets/228979/16469300/1640b6c2-3e05-11e6-8a44-90dd56556548.png)

**Comment by edmoz** [comment]
I believe we're unblocked on design here and rlr wanted to pick this up (please change it if not)
