### ISSUE TITLE
Add embeds (images, videos, etc) to timeline

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#415]

**Comment by edmoz** [comment]
@tspurway should we add this to A or B milestones, can we prototype this and get UX to review?  embedly provides: 
media:html
`<iframe class="embedly-embed" src="//cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FtntOCGkgt98%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DtntOCGkgt98&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FtntOCGkgt98%2Fhqdefault.jpg&key=internal&type=text%2Fhtml&schema=youtube" width="500" height="281" scrolling="no" frameborder="0" allowfullscreen></iframe>`

**Comment by edmoz** [comment]
we'd probably wnat to src= from our own video player harness rather than embedlys

**Comment by edmoz** [comment]
in chatting with tim and rittme, let's prototype this for youtube then review it with UX/Product

**Comment by bryanbell** [comment]
https://invis.io/T27FS4AMH#/161823311_Activity

Here's a mockup

**Comment by bryanbell** [comment]
![playbutton-hover 2x](https://cloud.githubusercontent.com/assets/228979/15592120/fae78924-2355-11e6-9566-3484e2d33494.png)
![playbutton 2x](https://cloud.githubusercontent.com/assets/228979/15592121/fb091ba2-2355-11e6-9fda-d06bb59f9af2.png)
parts needed

**Comment by bryanbell** [comment]
[playButton.zip](https://github.com/mozilla/activity-stream/files/285491/playButton.zip)

parts needed

**Comment by bryanbell** [comment]
[playButton.zip](https://github.com/mozilla/activity-stream/files/285498/playButton.zip)
 compressed PNGs
