### ISSUE TITLE
Add filter to Timeline for filtering/searching history and bookmarks

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#416]
This ticket should add a filter/search box that allows searching the Timeline.

This will require:
- [ ] add-on APIs for searching history/bookmarks, as well as new data structures in the store
- [ ] new search input UI
- [ ] new search results display UI

Might be worth splitting this up into different tickets.

Trello spec here: https://trello.com/c/UMGCuxJy

*[edit by @k88hudson for clarity]*

**Comment by edmoz** [comment]
@tspurway can we move this into either A or B milestones?

**Comment by pdehaan** [comment]
Yeah, lets move this to Banff (and bump if we don't get to it) or move it right into Columbia milestone so this doesn't get lost in the shuffle.

**Comment by edmoz** [comment]
spec: https://trello.com/c/UMGCuxJy

**Comment by k88hudson** [comment]
Designs are still needed for:

- [ ] What search results look like when someone triggers a search
- [ ] Is there any kind of auto-complete etc. while someone is typing?

cc @aaronrbenson @bryanbell

**Comment by nchapman** [comment]
We're filling in the design for this [in Trello](https://trello.com/c/UMGCuxJy/11-i-want-to-search-all-the-activities-i-ve-done-in-the-browser-so-that-i-can-find-things-i-ve-found-before). This should be a very basic wildcard search on title and url to begin with (`title LIKE '%?%' OR url LIKE '%?%'`).

**Comment by edmoz** [comment]
from the triage meeting - the goals was bare bones design so auto-complete isn't needed for the first PR to land but may be requested in future iterations

**Comment by aaronrbenson** [comment]
Filtering items inside of Activity Stream: https://invis.io/HP7X9Y9VD

**Comment by sarracini** [comment]
@Mardak are you taking this? should i assign you?
