### ISSUE TITLE
Check for missing results from Embedly Proxy

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#428]
Soon, the embedly proxy may exclude a result from its response due to data validation or other errors.  So for instance if you send urls [url1, url2, url3] you may only get back [url1, url3].  The client may want to check that it got back what it asked for and potentially re-request failed attempts or log them in some way.

**Comment by pdehaan** [comment]
Does it make sense for the proxy to drop results, or should it always return all requested URLs and just add some keys to the failing results?
OK, that was garbage explanation, but basically when we get an Embed.ly error now, it should automatically return stuff like this:
- `"type": "error"`
- `"error_code": 404`
- `"error_message": "HTTP 550: Unknown"`

https://embedly-proxy.dev.mozaws.net/extract?urls=https://www.pinterest.com
http://embed.ly/docs/explore/extract?url=https%3A%2F%2Fwww.pinterest.com

**Comment by jaredkerim** [comment]
@pdehaan Those are valid response bodies from embedly which the proxy will consider a valid response and return to the calling client.  I'm talking about the case where 

1) embedly returns a completely invalid response for a URL (a string where we expect an integer, etc) which fails validation or 

2) a metadata body which fails some custom validation step we define (do not proxy images, do not mutate URLs, etc) which forces us to drop the data before it's returned to the calling client.

**Comment by pdehaan** [comment]
Yeah, I was thinking instead of removing those results from the response, you just override `type` to "error", set the `error_code` to [418](https://tools.ietf.org/html/rfc2324#section-2.3.2), and set the `error_message` to "Failed schema validation".

**Comment by jaredkerim** [comment]
@pdehaan we could do, whatever's easier for the client to consume.  I think the most significant part is how the client responds to erroneous calls.  Retry? Drop? etc

**Comment by jaredkerim** [comment]
The proxy will currently drop erroneous results however in the future we can pass erroneous results back with data which contains validation errors when the client is able to process them correctly.

**Comment by sarracini** [comment]
If the client receives something which it didn't request, it will just return based on https://github.com/mozilla/activity-stream/blob/master/lib/PreviewProvider.js#L291-295. Jared and I talked about how the proxy will log the error, but that the client doesn't need to be aware of the kind of error that the proxy threw. The client should however have an extra layer of response sanitization, which jared filed as #678. I'll write a test to ensure that the client is throwing out any responses from the proxy that it didn't ask for and we can close this issue from there
