### ISSUE TITLE
Use the same strategy to configure content/add-on

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#438]
Right now we kind of have 2 configuration strategies – the add-on uses prefs, and content uses a yaml-based config. 

We should consider unifying these strategies somewhat since certain values are shared between add-on and content code, and it's way nicer to edit them in one place. This will probably consist of two things:
- passing prefs to content
- configuration that happens at build time that can't be modified by users

**Comment by sarracini** [comment]
Closing this as a won't fix
