### ISSUE TITLE
favicon and spotlight images are broken if tracking protection is enabled

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#449]
Ref: #334 

We should come up for a good fallback for displaying broken images (for things that aren't in tippy-top-sites).

**Comment by pdehaan** [comment]
Not sure if we want to do something similar to this (which requires some jQuery spice): https://css-tricks.com/snippets/jquery/better-broken-image-handling/

**Comment by tspurway** [comment]
tippy-top makes this much better

**Comment by pdehaan** [comment]
In the case of Twitter and GitHub, etc, I believe this has been resolved with our clever use of tippy-top-sites.  I'm now seeing images being served by the add-on if they're in tippy-top-shape:

```html
<img class="site-icon-favicon" src="resource://activity-streams/data/content/favicons/images/twitter-com.png" data-reactid="..." />
```

Probably still want to keep this open and come up with a better story for tracking protection and sites that are NOT in the tippy-top-database.

**Comment by cpeterso** [comment]
I see this favicon problem with tracking protection enabled on https://developers.google.com/.

**Comment by dmose** [comment]
I'm not seeing this problem on the current default branch with tracking protection on at https://developers.google.com/.  It defaults to a D icon for developers.  Is there still a bug here?

**Comment by k88hudson** [comment]
I'm not seeing this either. Let's close this and re-open if it's still around after #488 lands (I wonder if it was a false alarm?)
