### ISSUE TITLE
Bug 1259373 - Multiple items can be removed at once from "New Tab" or "Timeline" pages by spam clicking the close button on first hovered item

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#452]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1259373

---

Created attachment 8734299 [details]
Remove all.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.3
- Activity Stream 1.0.4

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.4) was previously installed on a profile.  

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Navigate to a couple of pages in order to have some history stored.
3. Open a new tab, and wait for it to be populated with the visited pages.
4. Hover over first item from "Top Sites" or "Spotlight" area until the close button appears "(x)".
5. Move the pointer to the center of the remove button and spam click it.
6. Observe the browser behavior.

#### [Expected results]:
Only the hovered item is removed when clicking the close button. The next item can be removed only if the close button is displayed again after tile is hovered.

#### [Actual results]:
All items are removed from the selected area without hovering them and without the close button to appear (see attached screen capture).

**Comment by SoftVision-PaulOiegas** [comment]
Fixed by remove functionality workflow update. Items are no longer removable with single click. A context menu is now displayed with options.
