### ISSUE TITLE
Bug 1259383 - Feed-icon-image is no longer displayed after the website is accessed from Timeline

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#453]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1259383

---

Created attachment 8734307 [details]
Feed-icon-image is removed

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.4

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.4) was previously installed on a profile.
- Have more websites that have favicon+feed icon in "Just now" area from Activity Stream Timeline.

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on a link from a website that has favicon+feed icon in Timeline.
4. Click on "Back" button after the page was loaded.
5. Click on "Refresh" button.

#### [Expected results]:
The visited website is displayed first in Just now area from Timeline and the favicon+feed icon are displayed.

#### [Actual results]:
Feed icon image is no longer displayed. The favicon is displayed inside the site-icon-wrapper.

#### [Notes]:
This issue is reproducible also in New Tab page.

**Comment by pdehaan** [comment]
Notes:
- This seems to be because of our "random" behavior for showing preview images.
- @nchapman suggests maybe showing the images for all Embedly "article" types.

**Comment by pdehaan** [comment]
Actually, I wonder if we know what the response `type` is from Embedly...

It returns a response type of "html" for this random URL: http://embed.ly/docs/explore/extract?url=http://bleacherreport.com/articles/2633065-johnny-manziel-accused-of-trashing-west-hollywood-mansion-he-rented-during-party when I hit the API directly:

```js
{
  "original_url": "http://bleacherreport.com/articles/2633065-johnny-manziel-accused-of-trashing-west-hollywood-mansion-he-rented-during-party",
  "favicon_colors": [...],
  "favicon_url": "http://static2.bleacherreport.net/favicon.ico",
  "images": [...],
  "language": "English",
  "lead": null,
  "provider_display": "bleacherreport.com",
  "provider_name": "Bleacher Report",
  "provider_url": "http://bleacherreport.com",
  "published": null,
  "safe": true,
  "title": "Johnny Manziel Accused of Trashing West Hollywood Mansion He Rented During Party",
  "type": "html",
  "url": "http://bleacherreport.com/articles/2633065-johnny-manziel-accused-of-trashing-west-hollywood-mansion-he-rented-during-party",
}
```

Yet, if I look at my merged debug response in Activity Stream, it looks like everything has a "type" of "history":

```js
{
  "original_url": "http://bleacherreport.com/articles/2633065-johnny-manziel-accused-of-trashing-west-hollywood-mansion-he-rented-during-party",
  "content": "<div>\n<p>Former Cleveland Browns quarterback <a href=\"http://bleacherreport.com/johnny-manziel\">Johnny Manziel</a> is accused of trashing a mansion in West Hollywood, California.</p>\n<p>According to <a href=\"http://pagesix.com/2016/04/14/johnny-manziel-accused-of-trashing-pad-with-booze-and-drug-filled-ragers/\">Emily Smith</a> of Page Six, real estate broker Nicholas Goodwin said Manziel partied for two days straight at the Los Angeles property last week, leaving evidence of alcohol and drug use and causing $32,000 in damage.</p>\n</div>",
  "favicon_url": "http://static2.bleacherreport.net/favicon.ico",
  "provider_display": "bleacherreport.com",
  "provider_name": "Bleacher Report",
  "provider_url": "http://bleacherreport.com",
  "type": "history",
  ...
}
```

Not entirely sure why, but I'm looking suspiciously at this line in [./lib/PlacesProvider.js:236](https://github.com/mozilla/activity-streams/blob/6644bcfa0829f20d9b46d2826abc780d1005ccee/lib/PlacesProvider.js#L236):
I'm guessing there is some Object merge and name collision stuff happening here.

**Comment by sarracini** [comment]
Closing this since we've removed timeline and recent activity
