### ISSUE TITLE
Bug 1259396 - "See more activity" button is displayed when one website is available in history

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#454]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1259396

---

Created attachment 8734318 [details]
see more activity button

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.4

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.4) was previously installed on a profile.
- There is no history for the profile used.

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Visit a website (e.g. 9gag.com)
3. After the page is loaded click on "Activity Stream" button from browser toolbar.

#### [Expected results]:
One website is displayed in the Timeline.
There is no "See more activity" button.

#### [Actual results]:
"See more activity" button is displayed even if there are no other websites that can be loaded in Timeline.

**Comment by pdehaan** [comment]
I was able to reproduce this today. I only have 2 items in my history

![activity_stream](https://cloud.githubusercontent.com/assets/557895/14393067/b64a187e-fd79-11e5-9f33-6705a996bcdd.png)

**Comment by softvision-VladBacia** [comment]
This issue was verified on Activity Stream v1.0.14-dev and it is reproducible.

**Comment by k88hudson** [comment]
This is resovled with 005ba6f
