### ISSUE TITLE
Bug 1259443 - A website that was visited multiple times is redisplayed in "Top Sites" even if manually removed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#455]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1259443

---

Created attachment 8734354 [details]
Website redisplayed.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.3
- Activity Stream 1.0.4

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.4) was previously installed on a clean profile.  

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Navigate to multiple articles / pages from a specific website (eg: a few videos from YouTube).
3. Open a new tab, and wait for the "Top Sites" area to be populated with the visited website (additionally, open the "History" tab with "Ctrl+h" keys combination)
4. Hover over the website from "Top Sites" area and chose to remove it.
5. Refresh the page and observe the "Top Sites" area.

#### [Expected results]:
The visited website is removed from "Top Sites" area and it's no longer displayed after refreshing the page.

#### [Actual results]:
The visited website reappears on the "Top Sites" area (see attached screen recording).

#### [Notes]:
- The website continues to reappear in "Top Sites" area after each removal until all the history related to that specific website is deleted.

**Comment by pdehaan** [comment]
Notes:
- **Top Sites** points to pages, and not actual sites.
- Deleting a link only deletes that one page/link, not all links for that site.

**Comment by jaredkerim** [comment]
This is working as intended for now, it can be revisited if we decide to change how top sites works in the future.
