### ISSUE TITLE
Bug 1260409 - Spotlight placeholders are repopulated at page refresh, after all items were previously removed

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#456]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1260409

---

Created attachment 8735818 [details]
remove Spotlight items

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.3
- Activity Stream 1.0.4

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.4) was previously installed on a clean profile.  

#### [Steps to reproduce]:

1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Navigate to multiple articles / pages so that they will be displayed in "Spotlight" area. (about 10-15 Spotlight items)
3. Go to Activity Stream Timeline.
4. Hover over the website from "Spotlight" area and chose to remove it.
5. Removed all visible and queued (if any) Spotlight items.
6. Refresh the Activity Stream Timeline.

#### [Expected results]:
Spotlight placeholders are displayed.
There are no items displayed in "Spotlight" area after refresh.

#### [Actual results]:
Some of the Spotlight items are displayed (see attached screen recording).

#### [Notes]:
- This issue is reproducible also in the New Tab page.

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160701030235) using latest Activity Stream v1.1.0-custom build and could not reproduce it. Fixed along the way.
Thus, marking this issue as Verified-Fixed.
