### ISSUE TITLE
Long titles and descriptions are just cut instead of displaying suspension points as truncation method in "Highlights" area

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#459]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1261889

---

Created attachment 8737864 [details]
truncated.png
#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.5
#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux
#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.5) was previously installed on a clean profile.  
#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Navigate to a website that has multiple articles with the same structure (eg: http://cnn.com).
3. Open multiple articles / pages from the website that have long titles and descriptions.
4. Open a "New Tab" page and observe how the long titles and descriptions of the opened pages are displayed in "Highlight" area.
#### [Expected results]:

Long titles and descriptions that exceed the implemented space are displayed as truncated with suspension points.
#### [Actual results]:

The titles / descriptions that exceed the implemented space are just cut without knowing that there's more text that could not be displayed.
#### [Notes]:
- Attached screenshot with the issue.

**Comment by sarracini** [comment]
Mutli-line ellipses are hard 😢. Let's close this since it doesn't look like this is in the design specs for now. Thanks Peter!
