### ISSUE TITLE
Invalid width/height on img tag in ReturnToAMO component

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#4598]
Per PR #4578 and the https://html5.validator.nu/ HTML 5 validator, the `width` and `height` attributes appear to be invalid on the `<img>` tag (unless it's a React thing). The values should just be numeric in HTML (no "px" suffix, since that's a CSS only thing):

https://github.com/mozilla/activity-stream/blob/f40d201cfe4d67fec4ba7adc10d46c4c97924af6/content-src/asrouter/templates/ReturnToAMO/ReturnToAMO.jsx#L27

```
Error: Bad value 20px for attribute width on element img: Expected a digit but saw p instead.

From line 8, column 7; to line 8, column 54

t">↩      <img src="foo.png" width="20px" height="20px" />↩    <

Error: Bad value 20px for attribute height on element img: Expected a digit but saw p instead.

From line 8, column 7; to line 8, column 54

t">↩      <img src="foo.png" width="20px" height="20px" />↩    <

Error: An img element must have an alt attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.

From line 8, column 7; to line 8, column 54

t">↩      <img src="foo.png" width="20px" height="20px" />↩    <
```

**NOTE:** I tested w/ the following simplified snippet, which is why it says "foo.png" above:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>An example page</title>
  </head>
  <body>
    <main class="content">
      <img src="foo.png" width="20px" height="20px" />
    </main>
  </body>
</html>
```

**Comment by piatra** [comment]
Moved this to bugzilla so it gets triaged https://bugzilla.mozilla.org/show_bug.cgi?id=1517750
