### ISSUE TITLE
Bug 1262138 - Bookmarked pages from "Highlights" and "Recent Activity" remain blocked in "Highlights" area even if multiple new pages are visited

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#469]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262138

---

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a clean profile.  

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Navigate to multiple websites / articles, each in new tab, in order to have pages displayed in "Highlights" and "Recent activity" areas.
3. Open a new tab page.
4. Bookmark one of the pages displayed in "Recent activity" and two pages from "Highlights" area (or vice versa).
5. Observe the pages behavior in a "New Tab" page.
6. Visit a couple more pages and observe the "Highlights" area.

#### Expected results:
5\. Bookmarked pages appear with bookmarked status in "Highlights" area and with "Star" icon in "Recent Activity" area. The pages are not moved from their previously spot since they were visited a single time.
6\. New visited pages replaced the previously displayed pages from "Highlights" area.
 
#### Actual results:
5\. Bookmarked page(s) from "Recent Activity" area are forcedly moved to "Highlights" area.
6\. New visited pages are displayed directly into "Recent Activity" area instead of "Highlights" area. This is caused by the 3 previously bookmarked pages that remain stuck in "Highlights" area.

#### [Notes]:
- The "Highlights" area can be populated again with new articles only if the current pages are removed from bookmarks.
- This issue also occurs in Timeline page for "Highlights" and "Just Now" areas.
- Attached a screen recording with the issue.
- Reproducible 5/5 tries.

Screen recording with the issue https://goo.gl/Nnz1fs .

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160706030233) using latest Activity Stream v1.1.0-custom build and could not reproduce it. This issue was fixed along the way..
Thus, marking this issue as Verified-Fixed.
