### ISSUE TITLE
Bug 1262824 - Horizontal scrollbar does not appear in Activity Stream Timeline, when you resize the browser window

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#504]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262824

---

Created attachment 8739012 [details]
Screencast of the issue.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.
- Have at least two website in "Highlights" area from Activity Stream Timeline.

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Make sure that the browser window is not maximized.
4. Resize the window from right to left until only one tile from "Highlights" area is displayed in viewport.
5. Scroll to right in order to view the other tiles that are not displayed in viewport. 

#### [Expected results]:
- Horizontal scrollbar is visible and functional.

#### [Actual results]:
- There is no horizontal scrollbar.

#### [Notes]:
- If a google spreadsheet is displayed in a tile form "Highlights" area, when resizing the browser window the tile will not resize. This issue is randomly reproducible with random google spreadsheets.
- The issue is visible in attached video.

**Comment by sarracini** [comment]
Closing this since we've removed timeline
