### ISSUE TITLE
Bug 1263141 - Timestamp is not updated when revisiting a website after changing the system time to a future one and back to current

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#505]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1263141

---

Created attachment 8739408 [details]
Screencast of the issue.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.8

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.8) was previously installed on a profile.
- Multiple pages were previously visited in order to have items displayed in "Recent activity" from "New Tab" and "Timeline" pages. 

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Change the system time to be in future.
3. Open a New Tab.
4. Click on a website from "Recent Activity" area.
5. Open a New Tab.
6. Observe the time for the visited website (Timestamp has been updated with the new time settings).
7. Change the system time to the current time.
8. Click again the previously visited website from "Recent Activity" area.
9. Open a New Tab.
10. Observe the time for the visited website.

#### [Expected results]:
The timestamp is correctly updated.

#### [Actual results]:
The timestamp is not updated. The time from the future is still displayed.

#### [Notes]:
This issue is reproducible also in "Timeline".

---

I found a similar issue that is reproducible only on Linux. 
When switching the Timezone from a higher value to a lower one (eg: switching from +10 to +3).

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Change the Timezone to a higher value.
3. Open a New Tab.
4. Click on a website from "Recent Activity" area.
5. Open a New Tab.
6. Observe the time for the visited website (Timestamp has been updated with the new time settings).
7. Change the Timezone back to the previous one.
8. Click again the previously visited website from "Recent Activity" area.
9. Open a New Tab.
10. Observe the time for the visited website.

#### [Expected results]:
The timestamp is correctly updated.

#### [Actual results]:
The timestamp is not updated. The time from the future is still displayed.

**Comment by oyiptong** [comment]
while we'll support timezone changes, detecting a change in system clock is something that might not be worthwhile for us to do

**Comment by sarracini** [comment]
closing this since we've removed recent activity
