### ISSUE TITLE
Stop upscaling fav icons in Top Sites. 

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#523]
<img width="264" alt="pasted_image_4_14_16__10_28_am" src="https://cloud.githubusercontent.com/assets/228979/14537368/98000f84-022b-11e6-976f-3fc8f72be55c.png">

Can we detect if a fav icon is not large enough and replace it the letter+color fallback.

**Comment by pdehaan** [comment]
Define "large enough".

Do we want to keep the icons at 32px or increase them to 64px (to match the icons from tippy-top-sites)?

![new_tab](https://cloud.githubusercontent.com/assets/557895/14570799/e96a74ca-02fa-11e6-8075-c75fb0d314b6.png)
**Figure 1:** Icons at 32 x 32px.

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/14570843/1c6c6130-02fb-11e6-8c9a-c31431c2230b.png)
**Figure 2:** Upscaled icons at 64 x 64px.

**Comment by bryanbell** [comment]
If an icon is not at least 32px we should not use it at all in Top Sites or Highlights. Instead we should just use the letter and icon color for the BG. 

Like this... 
![pasted_image_4_20_16__5_27_pm](https://cloud.githubusercontent.com/assets/228979/14694435/3acbc14a-071d-11e6-87bb-8795fd0b6a58.png)

**Comment by jaredkerim** [comment]
#770 This will covered by the new metadata processing and storage which will allow the storage and display of rich (high res) icons.  Closing this as it is covered by the new metadata initiative.
