### ISSUE TITLE
jpm should never send pings to prod

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#525]
Right now, running a simple `jpm test` will send telemetry pings to our prod server. So we must always use `npm run test:jpm` which runs `jpm test --prefs ./test-prefs.json` where `test-prefs.json` points to a staging server instead.

In order to avoid accidentally sending test pings to prod, we can instead make the default value for the `telemetry` pref set to `false`. Then we can create a `prod-prefs.json` config that turns the telemetry pref on.

**Comment by k88hudson** [comment]
Note that the issue where `npm run travis` was not picking up the test prefs was fixed in this PR https://github.com/mozilla/activity-streams/pull/551

**Comment by sarracini** [comment]
This is done
