### ISSUE TITLE
Pin a custom search engine to a tile on the new tab page.

### ISSUE THREAD

**Issue by xmha97** [mozilla/activity-stream#5398]
Hello,
How I can pin a custom search engine to a tile on the new tab page?
I can't see the custom search engine on the "Add Search Engine" dialog! (see below picture)
![Firefox](https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/images/2020-02-26-21-56-03-c3faed.png)
Please help me.
Thanks.

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @xmha97, sadly this repo is no longer used for issue tracking, can you please file a bug in https://bugzilla.mozilla.org/ in the New Tab Page component?

**Comment by piatra** [comment]
To answer your request this is already possible from the urlbar
<img width="492" alt="image" src="https://user-images.githubusercontent.com/810040/75557202-83d99f80-5a37-11ea-9ee4-f81e9c64cd41.png">
You can type something in and search with your default search engine or choose a different one by clicking on the icons show below like twitter or wikipedia.
To add more search engines go to `about:preferences#search`
