### ISSUE TITLE
Consider better strategy for updating stuff in <head>

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#553]
@pdehaan suggested we might want to consider Helmet or something similar for setting title/favicon:
> Semi-related, but I found this to be pretty cool: https://github.com/nfl/react-helmet
You may be able to simplify it down to something similar to this in NewTabPage and TimelinePage:
> ```
<Helmet link={[{
    "rel": "icon",
    "type": "image/svg+xml",
    "href": "${options.baseUrl}img/glyph-activityStream-16.svg"
  }]} />
```
> (At the obvious expense of yet another dependency)

Might also be worth rolling this into the base route and use route definitions to define icons/titles etc.

**Comment by oyiptong** [comment]
closing as per @k88hudson
