### ISSUE TITLE
Bug 1266467 - Similar websites are populating "New Tab" page sections in different way

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#556]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1266467

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.10

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.10) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Navigate to "http://adevarul.ro/" website.
3. Open multiple articles from the website and after each one observe how the "Highlights" and "recent Activity" areas are populated.
4. Clear the browser history (optional for better visibility) and navigate to "http://edition.cnn.com/" website.
5. Repeat step #3 for CNN website.

Expected results:
Both websites home pages are displayed first in "Top Sites" area, where they will always remain. After, each new article visited is cycled trough "Highlights" area. When the 4th article is visited, the last one from "Highlights" area drops in "Recent Activity" area.

Actual results:
The first CNN website article visited is updating the "Top Sites" CNN position (home page) instead of appearing in "Highlights" area. Only after visiting the next article the one from "Top Sites" area drops in "Highlights" area, including the Home Page.

[Notes]:
- Link for screen recording with the issue (https://goo.gl/hSMeAA).
- Reproducible 5/5.

**Comment by SoftVision-PaulOiegas** [comment]
Verified this again using the latest dev build (1467233670) and with the lasted custom build from today and it still behaves the same way. 
The "adevarul.ro" website home page is displayed in top sites no matter how many articles are visited, while the "cnn.com" website last visited article is displayed in top site and the homepage in "Recent Activity" area.

**Comment by sarracini** [comment]
@SoftVision-PaulOiegas is this still reproducible?

**Comment by sarracini** [comment]
I believe this is fixed now, closing this

**Comment by Softvision-VladBacia** [comment]
This issue is no longer reproducible in Activity Stream Dev 1.3.0-dev-1484695187.
