### ISSUE TITLE
Highlights always showing default tiles

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#570]
Found in 1.0.12

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/14800945/599814bc-0afa-11e6-9d40-9e19cc7e77bc.png)

---

### Steps to reproduce:
1. Git clone and `npm run once`.
2. Go to www.reddit.com/r/worldnews and open about 10-12 links.
3. Observe the "Highlights" section on New Tab or Timeline.

### Actual results:
![new_tab](https://cloud.githubusercontent.com/assets/557895/14800975/93c6cec6-0afa-11e6-858b-8dd4f90e5494.png)
**Figure 1:** New Tab page. I see 6 "Top Sites", and then the 3 default "Highlights", and then all my browsing history down in "Recent Activity". So apparently in my 11 page views across 11 sites we weren't able to find a single Highlight site. Seems fishy. 🐟 

---

![activity_stream](https://cloud.githubusercontent.com/assets/557895/14801012/e6ab6c1e-0afa-11e6-943e-b529e228ad48.png)
**Figure 2:** Timeline page. Same 3 default Highlights, and then my 11 page views down there in the "Just meow" section.

### Expected results:
At least 3 of those page visits should have been promoted up to Highlights.

**Comment by SoftVision-PaulOiegas** [comment]
We also found it and logged it too in Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1267556

**Comment by tspurway** [comment]
@nchapman to verify and close

**Comment by oyiptong** [comment]
closing. working as expected
