### ISSUE TITLE
Bug 1267558 - Unable to remove default sites from "Highlights" and "Top Sites" sections

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#571]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1267558
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.12

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.12) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and open a new tab.
2. Hover a tile from "Top Sites" section.
3. Observe the upper right corner of the tile.

[Expected result]:
An remove "(X)" button appears in the upper right corner of the tile.

[Actual result]:
The remove "(X)" button does not appear on the default pages.

[Notes]:
- The issue is reproducible for Highlights tiles from New Tab and Timeline pages.
- Attached a screen recording of the issue https://goo.gl/5qQqhH .

**Comment by SoftVision-PaulOiegas** [comment]
If this is intended behavior so the "Top sites" and "Highlights" areas to be always populated, we should ignore this and mark it as invalid.

**Comment by k88hudson** [comment]
This is an intended behaviour, we've decided to leave it the way it is
