### ISSUE TITLE
Switching tabs should not cause a session end

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#597]
Right now switching from one tab to another will end a session (reason: `unfocus`)

@nchapman and I discussed this and we decided that we should not cause a session to end on this event.

However, we will need to significantly refactor the `tabTracker` so that it is able to handle more than one simultaneous session.

**Comment by emtwo** [comment]
What was the reason we don't want to consider this a session end? I recall initially our session end was about the user no longer being "engaged" with activity stream.

I suppose if a user returns to the tab soon and continues engaging we can consider it part of the same session.

**Comment by emtwo** [comment]
@nchapman, could we please get your input on this?

@k88hudson and I had a chat and we think we should first find out what questions we want to answer with the data. If we can answer those questions with the way we currently log a session, then maybe we can skip the work of refactoring.

For example, if we want a single tab to always represent 1 session when doing data analysis, then we can simply look at sessions with the same tab id (sure glad we've got that!) and consecutive timestamps.

**Comment by ncloudioj** [comment]
As a side note, the current design of session will terminate a session once the user switches to another tab, and its "unload_reason" will be set as "unfocus". If the user gets back to this tab again, and continues to interact with it, a new session will be created with "load_reason" as "focus".
