### ISSUE TITLE
Tracking protection blocks items on "activity stream" page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#601]
From IRC:

> - **\<rhelmer\>** hi! testing out test pilot, I noticed tracking protection is active and found items to block on the "activity stream" page (the one that loads in a tab when I press the toolbar button)

> - **\<rhelmer\>** resource://activity-streams/data/content/activity-streams.html#/timeline that is

> - **\<rhelmer\>** I don't know if the bug is that activity stream should be using a chrome:// or about: URL, or that TP shouldn't be blocking resource:// ...

**Comment by sarracini** [comment]
Closing this since we've removed timeline
