### ISSUE TITLE
Use high-resolution apple-touch-icons instead of 16x16 favicons in Top Sites list

### ISSUE THREAD

**Issue by cpeterso** [mozilla/activity-stream#603]
The Top Sites list could use the high-resolution apple-touch-icons, when available, instead of low-resolution 16x16 favicons. For example, sfgate.com is in my Top Sites list, but uses the low-resolution 16x16 favicon, . View-source of sfgate.com shows that the site advertises multiple higher-resolution apple-touch-icons that would look nicer scaled down than the 16x16 favicon does scaled up.

```
<link rel="SHORTCUT ICON" href="/favicon.ico"/>
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon.png" />
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />
<link rel="apple-touch-icon-precomposed" sizes="128x128" href="/apple-touch-icon-128x128.png" />
```

**Comment by pdehaan** [comment]
A couple interesting things of note:

1. Embed.ly seems to return only the /favicon.ico for the `favicon_url`. Looking at the raw JSON response, I don't see any mention of the apple-touch-icons.
2. Not sure if we're using Embed.ly for favicons anyways, or if that comes from our internal 8-bit favicon storage.
3. We _could_ address this with higher res favicons via https://github.com/nchapman/tippy-top-sites/blob/moar-sites/top_sites.json, but we'd probably have to add nearly all local newspaper sites and everybody else with 16px favicons.

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/14904803/edeefb82-0d5f-11e6-8ff6-20e2400949e2.png)

**Comment by k88hudson** [comment]
This is definitely a good idea for our post-embedly implementation 👍

cc @jaredkerim

**Comment by cpeterso** [comment]
For future reference, here are some example apple-touch-icons.

16x16 favicon: 
![favicon](https://cloud.githubusercontent.com/assets/629193/14922708/f7a7c18e-0ded-11e6-8829-2f355af9da5f.png)

60x60 apple-touch-icon: 
![apple-touch-icon-60x60](https://cloud.githubusercontent.com/assets/629193/14922741/28f24a3e-0dee-11e6-9894-c7d7d0d261c0.png)

152x152 apple-touch-icon:
![apple-touch-icon-152x152](https://cloud.githubusercontent.com/assets/629193/14922672/c9866a62-0ded-11e6-9a53-526348922636.png)

**Comment by pdehaan** [comment]
From IRC:

> **\<sebastian\>** Did you consider using the (apple) touch icons for the top sites in the activity streams? It seems like you have the same problems like fennec (with very ugly low res favicons). We are trying to use the touch icons in [bug 1265710](https://bugzilla.mozilla.org/show_bug.cgi?id=1265710) and so far this looks much much better in the app.

**Comment by jaredkerim** [comment]
The fathom based metadata extractor will allow for the usage of rich high res icons by design.
