### ISSUE TITLE
Consistent background colors for sites (per domain)?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#605]
Found in 1.0.13:

<img width="773" alt="nightly" src="https://cloud.githubusercontent.com/assets/557895/14926087/49ac5db2-0dff-11e6-98a3-0788a6606680.png">

---

### Steps to reproduce:
1. Install Activity Stream via Test Pilot.
2. Browse a bunch of pages for a specific site.

### Actual results:
I'm seeing ~3 different favicon background colors for testpilot.stage.mozaws.net (although one result is a JSON file, which wouldn't have any associated favicon info).

<img width="1440" alt="screenshot_4_29_16__11_41_am" src="https://cloud.githubusercontent.com/assets/557895/14926117/6f7ee366-0dff-11e6-89fb-00419cbaf77f.png">

### Expected results:
Not sure if there is a way to procedurally generate a favicon background color based on the "pretty" domain. Possibly [probably?] not worth the effort.

**Comment by oyiptong** [comment]
peter to re-verify as recent changes may have fixed this

**Comment by sarracini** [comment]
Closing this since we don't have timeline anymore and recent activity is going away too
