### ISSUE TITLE
It would be nice if circles in Recent Activity were treated like hanging punctuation.

### ISSUE THREAD

**Issue by helenvholmes** [mozilla/activity-stream#611]
The circles on the left side of Recent Activity probably aren't _true_ [hanging punctuation](https://en.wikipedia.org/wiki/Hanging_punctuation), but I think it would be a nice UI update if they were treated that way. 

For comparison, current on the left, hanging on the right:

![hanging-punctuation](https://cloud.githubusercontent.com/assets/1720093/14960314/1386bace-1062-11e6-8edc-eb706865d06e.png)

**Comment by k88hudson** [comment]
😭 😄   @helenvholmes you are the best

**Comment by bryanbell** [comment]
I totally see the issue, and often feel that this might be better, but it doesn't really work when shown with a sidebar, and beside we might consider a totally new layout soon.
