### ISSUE TITLE
Bug 1270107 - Different numbers of bookmarks displayed depending on OS in Timeline "Bookmarks" tab

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#631]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1270107
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.14-dev

[Affected Platforms]:
- Windows 7, Windows 8.1, Windows XP

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.14-dev) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open Activity Stream from the browser toolbar and click the on the Bookmarks tab.
3. Open the Bookmarks sidebar (Ctrl+B).
4. Click on "Bookmarks Menu" and then double click on the "Mozilla Firefox" folder.
5. Compare the bookmarks lists from "Mozilla" and "Bookmarks Toolbar" folders with the one from Timeline Bookmarks.

[Expected result]:
The same bookmarks are displayed in both lists.

[Actual result]:
Not all the default bookmarks are displayed on the Timeline->Bookmarks page

[Notes]:
- Attached a screenshot of the issue (from Windows 8.1).
- Windows 7 shows 3 bookmarks, Windows 8.1 shows 2 and Windows XP shows only 1.
- Not reproducible on Mac OS X and Linux.
![different bookmarks number](https://cloud.githubusercontent.com/assets/17258026/15018936/7e8e53cc-1224-11e6-80bc-84fd04aa9ed5.png)

**Comment by rlr** [comment]
I suspect this may be fixed now. @oyiptong I'll grab and take a look.

**Comment by rlr** [comment]
This is fixed in 1.0.17 already.

<img width="1191" alt="screen shot 2016-05-24 at 2 34 15 pm" src="https://cloud.githubusercontent.com/assets/36629/15515550/b18402ca-21bc-11e6-9497-919eacbc1c6a.png">
