### ISSUE TITLE
Bug 1269777 - Google search string from context menu wrongly searches also after the host name initial

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#632]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1269777
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.14-dev-1462225209

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.14-dev-1462225209) was previously installed on a clean profile.
- Have at least one website in "Highlights" or "Recent Activity" area from Activity Stream Timeline.  

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Right click on any website from "Highlights" or "Recent Activity".
4. Click on "Search Google for "..."" from the context menu.

[Expected results]:
Only visible strings are displayed in Google search bar. 

[Actual results]:
Hidden strings are also displayed in Google search bar.

[Notes]:
- The hidden string is the first letter of the URL.
- In my opinion, the best user experience would be to search only after the page title not also the page link and time-stamp.   
- The issue is reproducible on the New Tab page as well.
- Attached a screenshot of the issue.
![hidden string](https://cloud.githubusercontent.com/assets/17258026/15019089/2808c0b8-1225-11e6-9bdf-85b7399d369a.png)

**Comment by softvision-VladBacia** [comment]
In addition to this we observed that when a link is bookmarked from context menu (Timeline and New Tab pages), the Name of the bookmark contains hidden strings. When the same link is bookmarked from the original location, the name of the bookmark contains only the name and the domain. (eg. youtube videos)
![bookmark](https://cloud.githubusercontent.com/assets/9248513/15252114/157dc7d8-1935-11e6-9234-8df733232e34.png)

**Comment by sarracini** [comment]
The context menu is appending the fallback text to the search string 
<img width="1440" alt="context-menu" src="https://cloud.githubusercontent.com/assets/7219526/15299069/b1dd1556-1b70-11e6-88ec-ebf967b9218c.png">

**Comment by SoftVision-VladBacia** [comment]
@sarracini , this issue was verified on Windows 8.1 x64 with latest Nightly (50.0a1, Build ID: 20160607030217) using Activity Stream v1.0.19-dev build and we've noticed that the timestamp is still displayed at the end of the search string. 

![timestamp added](https://cloud.githubusercontent.com/assets/9248513/15886772/793ed56e-2d67-11e6-88d2-6925eeb9af34.jpg)

Can the timestamp be removed from the end of the search string or is this a limitation?

**Comment by sarracini** [comment]
I fix I fix

**Comment by SoftVision-VladBacia** [comment]
@sarracini , we have found a few other scenarios while testing.

1.Right-click on a tile from Highlights that has a visited website and click on "Search Google for ...." from the context menu. At the end of the searched string we can observe the status that was displayed in the Highlights tile.

![search from highlights](https://cloud.githubusercontent.com/assets/9248513/16085165/db5a1454-3323-11e6-95d5-ee69600ba681.jpg)
<hr>
2.Right click on a `site-icon-title` from Top Sites and perform a Search from the context menu displayed. At the end of the searched string we can observe that the `Open context menu` text has been added.

![top sites search](https://cloud.githubusercontent.com/assets/9248513/16085403/9d3ba060-3324-11e6-8cc7-07ea9dbf121e.jpg)

Can you remove the `Highlights status` and `Open context menu` text from the end of the search string?
