### ISSUE TITLE
first run of activity stream shows default tiles that aren't personalized at all, feels like a big regression

### ISSUE THREAD

**Issue by msujaws** [mozilla/activity-stream#647]
i enabled activity stream, and i lost all of my personalizations when i opened a new tab. it felt like the feature was a big step backwards because i was used to seeing my top sites, but now i was seeing generic amazon, ebay, etc sites.

i pretty quickly thought about disabling the feature since it seemed quite useless to me.

after a few minutes i opened a new tab again and it was now personalized. we need to let users know that the database is being built when it first gets enabled or users are going to have the same feeling i had.

**Comment by k88hudson** [comment]
I agree, this is really good feedback. I'm going to file a ticket to show some UI while we're analyzing your DB 👍

**Comment by k88hudson** [comment]
The first run of the add-on now shows your real data instead of defaults, although without enhanced metadata (follow-up issue filed here https://github.com/mozilla/activity-stream/issues/669)

Thanks for reporting!
