### ISSUE TITLE
hover buttons on the bookmarks view are out of order

### ISSUE THREAD

**Issue by msujaws** [mozilla/activity-stream#648]
See http://screencast.com/t/lF1igzDdqa

It looks like the popup menu should have come from the three-dots button, not the X button (which i thought would delete).

also, we should have tooltips for these buttons. what does the middle one do? upload the bookmark somewhere?

**Comment by k88hudson** [comment]
This is correct according to the design, but I will mark this as design feedback 👍

**Comment by msujaws** [comment]
okay thanks

**Comment by sarracini** [comment]
We removed this UI altogether, and are using a single context menu now. Thanks @msujaws for the feedback at the time! Closing this :)
