### ISSUE TITLE
switching between All and Bookmarks in activity stream flashes a resource:// URL in the location bar

### ISSUE THREAD

**Issue by msujaws** [mozilla/activity-stream#649]
Switching between All and Bookmarks in activity stream flashes a resource:// URL in the location bar.

See http://screencast.com/t/My3i0HnT6e

**Comment by oyiptong** [comment]
That would be one for @rlr :-)

**Comment by rittme** [comment]
I looked a bit more into this problem. It seems there is nothing we can do about it with the current implementation and I can't see any other approach to this problem. 

I would suggest we close this for now, since it's only a polish.

**Comment by oyiptong** [comment]
closing, we'll tackle it when in gecko
