### ISSUE TITLE
Enable manually editing top sites

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#652]
via https://github.com/mozilla/testpilot/issues/725

---

> @mystor: "Currently, in the new new-tab page, there doesn't seem to be a way for me to remove a website from my top sites, or pin one, unlike the tiles on the old new tab page. I would like to be able to do that, because having a stable list of top sites helps me navigate from the new tab page to websites I want to visit faster."

**Comment by bryanbell** [comment]
![edit](https://cloud.githubusercontent.com/assets/228979/15694655/810be764-2754-11e6-8944-5984a9df1040.png)

**Comment by bryanbell** [comment]
Mockup here: https://invis.io/YR76EYDBZ#/163224753_TopSite

**Comment by bryanbell** [comment]
![topsite-menu 2x](https://cloud.githubusercontent.com/assets/228979/15698829/0c6c799a-277d-11e6-8116-dc30a67cedeb.png)

![topsite-editmenu 2x](https://cloud.githubusercontent.com/assets/228979/15698831/0f548c06-277d-11e6-88db-ce0423788996.png)

![topsite-pin-editmenu 2x](https://cloud.githubusercontent.com/assets/228979/15698835/13f90f66-277d-11e6-9736-8235463fac42.png)

**Comment by bryanbell** [comment]
![pasted_image_5_31_16__10_16_pm](https://cloud.githubusercontent.com/assets/228979/15698875/696879e6-277d-11e6-992b-0524b7cce825.png)

![pasted_image_5_31_16__10_17_pm](https://cloud.githubusercontent.com/assets/228979/15698884/7934bec0-277d-11e6-835f-5740d369532a.png)

![pasted_image_5_31_16__10_17_pm](https://cloud.githubusercontent.com/assets/228979/15698888/8cab8632-277d-11e6-8ee1-3245d079d332.png)

**Comment by sarracini** [comment]
Feature requests should be added to the trello board
