### ISSUE TITLE
Bug 1270838 - The Top Sites remove context menu can be opened while a Highlight or Recent Activity one is already opened

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#657]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1270838
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.15-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.15-dev) was previously installed on a clean profile.  
- Have at least one item in Highlights, Top Sites, Recent Activity different than the default ones.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and open a new tab.
2. Hover over an item from Highlights/Recent Activity areas and click the "X" button to bring up the context menu.
3. Hover over a site from the Top Sites area and click the "X" button.

[Expected result]:
The previous menu is dismissed while the one from Top Sites appears.

[Actual result]:
The Top Sites remove context menu can be opened while one from Highlights/Recent Activity is already opened.

[Notes]:
- It can only be reproduced if the Top Sites context menu is the second one to be opened.
- Both context menus are clickable and are responsive.
- Attached a screen recording of the issue https://bug1270838.bmoattachments.org/attachment.cgi?id=8749646

**Comment by SoftVision-VladBacia** [comment]
The "remove context menu" has been replaced by the new "..." context menu but this issue is still reproducible in the latest Activity Stream builds.

This issue has been verified on Win 10 x64, Mac OS X 10.11 and Ubuntu 16.10 x64 with latest Nightly 50.0a1 (Build ID: 20160623030210) using latest Activity Stream v1.1.0-custom build and could produce it.
Thus, marking this issue as Reopened.

**Comment by k88hudson** [comment]
This is due to `event.stopPropagation()` being called in TopSites

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160721030216) using latest Activity Stream v1.1.0-dev-1469146673 and Activity Stream v1.1.0-custom and could not reproduce it.

Thus, changing the status of the issue to Verified-Fixed.
