### ISSUE TITLE
Bug 1270840 - The "Enter" key opens the webpage when the "Top Sites" remove context menu is opened

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#658]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1270840
<hr>
[Notes]:
- If the same steps are performed on "Highlights" or "Recent Activity" items nothing happens.
- Attached a screen recording of the issue while using the On-Screen Keyboard, but this is also reproducible with the physical keyboard (https://goo.gl/EeMNwJ).

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.15-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.15-dev) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Visit a webpage and open a new tab.
3. Hover over the webpage you have previously visited which is now in the Top Sites section.
4. Click the "X" button in the upper-right corner.
5. Hover over one of the options from the dropdown menu.
6. Press "Enter" key on your keyboard.

[Expected result]:
Nothing happens.

[Actual result]:
The site you have highlighted is opened in the current page.

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160629030209) using latest Activity Stream v1.1.0-custom build and could not reproduce it. The issue has been fixed along the way.
Thus, marking this issue as Verified-Worksforme.
