### ISSUE TITLE
Bug 1270842 - Add "remove bookmark" UI

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#659]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1270842
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.15-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.15-dev) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open Activity Stream from the browser toolbar and click the on the Bookmarks tab.
3. Hover one of the saved bookmarks and click the "X" button.

[Expected result]:
The option to remove a bookmark from Bookmarks should be available in the context menu.

[Actual result]:
Instead of having an option to remove a bookmark from Bookmarks, we only have the option to remove from History.

[Notes]:
- If you remove a bookmark from History, it is removed from the page, but after a refresh it reappears.
- From the User's perspective the option to remove from History doesn't make much sense in the Bookmarks tab since this can be achieved from Timeline->All History page. 
- Attached a screen recording of the issue https://goo.gl/m9MBDq.

**Comment by k88hudson** [comment]
This will be resolved by:

* [ ] https://github.com/mozilla/activity-streams/issues/666

**Comment by k88hudson** [comment]
To resolve this bug we need to update the [Delete Menu](https://github.com/mozilla/activity-stream/blob/master/content-src/components/DeleteMenu/DeleteMenu.js) component to take an prop that allows it to show a `"Remove this bookmark"` option, as well as hide the `"Remove from History`.

You'll need to make sure that the `DeleteMenu` on the [ActivtyFeed](https://github.com/mozilla/activity-stream/blob/master/content-src/components/ActivityFeed/ActivityFeed.js#L85) shows the bookmark delete option when it appears on the Timeline/Bookmarks page.

It should look this this:
![image](https://cloud.githubusercontent.com/assets/1455535/15231631/54868da0-186a-11e6-81cf-f312855b9c55.png)

**Comment by k88hudson** [comment]
Tests are here: https://github.com/mozilla/activity-stream/blob/master/content-test/components/DeleteMenu.test.js
