### ISSUE TITLE
Bug 1271273 - The "Search" button doesn't receives focus border when selecting the search field 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#665]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1271273
<hr>
[Affected versions]:
- Firefox 49.0a1
- Activity Stream 1.0.15

[Affected Platforms]:
- All Windows

Prerequisites]:
- Latest Activity Stream add-on version (1.0.15) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a new tab and click on the Search bar.
3. Type something in the Search bar.
4. Observe the Search bar while it has focus.

[Expected result]:
- A blue border surrounds both the search bar and "Search" button when text box is focused.

[Actual result]:
- The blue border only covers the search bar when textbox is focused, leaving the "Search" button smaller in size(see attachment).

[Notes]:
- Considering that the browser address bar has almost the same behavior (on default theme), I think that the "New Tab" search bar should perform the same.
![as search field](https://cloud.githubusercontent.com/assets/17258026/15118550/56c5d1f4-1615-11e6-85f0-225111df621d.png)

**Comment by sarracini** [comment]
fixed with #738
