### ISSUE TITLE
Bug 1271668 - slow embedly proxy response results in grey backgrounds in highlights

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#669]
1. install activity stream for the first time or update your version
2. open new tab fairly quickly after install

actual:
<img width="772" alt="screen shot 2016-05-10 at 9 26 28 am" src="https://cloud.githubusercontent.com/assets/3698618/15154430/5c9b46f4-1692-11e6-9e3a-1a63053f879a.png">

**Comment by pdehaan** [comment]
How are you installing Activity Stream? If it's via Test Pilot, we have a UI tour which may slow down the user slightly which makes the quick succession of steps a bit less likely.

I though the general idea currently was:

1. A [very new] user visits Test Pilot and installs the add-on
2. User installs Activity Stream add-on
3. We _immediately_ start processing their history cache (as soon as the activity stream add-on is installed -- not on first visit to the activity stream page)
4. User opens a new tab and sees Activity Stream for the first time (or presses the Activity Stream button in toolbar and sees timeline).

By the time step 4 happens above, I was expecting we'd already have a large portion of their cache populated (unless they are very quick clickers).

**Comment by SoftVision-PaulOiegas** [comment]
We encountered this also and filed a Bugzilla issue for it yesterday, but I didn't had time to clone it in Github.We'll consider this one as reference.
https://bugzilla.mozilla.org/show_bug.cgi?id=1271668

**Comment by softvision-VladBacia** [comment]
This issue is happening in both cases, when Activity Stream is installed through Test Pilot and when it's installed from the links provided by you.

**Comment by softvision-VladBacia** [comment]
After further investigation, I've observed that in the web console the following error is displayed:

```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full Message: TypeError: this._addon is null
Full Stack: BrowserAddonActor.prototype.id@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/actors/addon.js:50:5
DSC_setAddonOptions/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/server/main.js:1556:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:11
waitForSyncCallback@resource://services-common/async.js:102:7
makeSpinningCallback/callback.wait@resource://services-common/async.js:156:27
_handlerListener@resource://gre/modules/services-sync/addonsreconciler.js:633:9
onInstalled@resource://gre/modules/services-sync/addonsreconciler.js:658:5
AddonManagerInternal.callAddonListeners@resource://gre/modules/AddonManager.jsm:1801:11
this.AddonManagerPrivate.callAddonListeners@resource://gre/modules/AddonManager.jsm:2842:5
AddonInstall.prototype.startInstall/<@resource://gre/modules/addons/XPIProvider.jsm:6056:9
TaskImpl_run@resource://gre/modules/Task.jsm:315:40
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:933:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:812:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:746:11
```

**Comment by SoftVision-CosminMuntean** [comment]
It seems that in the current version of Activity Stream (v1.0.18) when the visited websites are displayed in the "Highlight" area, the tiles are populated but the images and description are missing. Instead of images, a background with the specific colour of the visited websites is displayed.

![highlights tiles](https://cloud.githubusercontent.com/assets/19226534/15652568/b7874e02-268f-11e6-89f1-2e7cdaf941ae.png)

**Comment by pdehaan** [comment]
@jaredkerim Did you say that the gray boxes was an embedly-proxy issue which was getting resolved with a new deploy this week?

**Comment by k88hudson** [comment]
Part of the problem here is that there is too much load on the proxy and it was timing out frequently. So far, we've taken  the following steps to improve this situation:
- [x] Improvements to de-duping/caching strategy in Embedly proxy (by @jaredkerim) (Status: landed)
- [x] #787: Refactor updating strategy on the addon to reduce load on proxy (Status: landed) 
- [ ] #794: Add local color metadata parsing for favicons (Status: has PR)

**Comment by edmoz** [comment]
#794 doesn't seem to block closing the user issue here.  closing
