### ISSUE TITLE
Reduce duplicate queries to embedly-proxy

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#671]
Presently when we initialize the addon, we make multiple concurrent requests to the embedly proxy for the same URLs.

https://github.com/mozilla/activity-stream/blob/master/lib/ActivityStreams.js#L112-L129

Each of these statements will apply a query to the places db and receive a list of URLs, however the same URLs may appear in many of these results.  They each fire off a separate request to the proxy.  These should be brokered by a single point which can prevent multiple calls to the proxy for the same data.

**Comment by sarracini** [comment]
fixed with #686
