### ISSUE TITLE
Better access to data in activity stream search/filter

### ISSUE THREAD

**Issue by thewhitetulip** [mozilla/activity-stream#676]
We'd love to have filtering on activity streams, search or domain wise. Taking it forward, we can filter out a domain name or particular website, or based on date

**Comment by k88hudson** [comment]
Thanks for the feedback!

**Comment by thewhitetulip** [comment]
Why is this put in v1? and the tag is design feedback needed, do I need to give some feedback? or something else?

**Comment by Noitidart** [comment]
Will the search be able to search content of the websites offline?

**Comment by pdehaan** [comment]
@thewhitetulip The **Post v1** milestone and **Design feedback needed** label are just for our internal tracking.

**Comment by thewhitetulip** [comment]
@Noitidart Yep, that's the plan, I mean we want to be able to search *within* activity stream only for websites and not for contents.

Also we want to filter out domains like facebook.com and other ones like gmail.com because they are of no use 😄 

@pdehaan Okay, thank you :-). If you implement this I'd love to contribute.

**Comment by Noitidart** [comment]
Hahaha @thewhitetulip sounds so cool! Really looking forward to this future! :)

**Comment by sarracini** [comment]
Feature requests should be added to the trello board
