### ISSUE TITLE
Sanitize Embedly Proxy results

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#678]
When the addon receives data from the embedly proxy, it should run a few sanitization checks for 

- checking that there isn't JS inside any fields that are sent to the user
- check that URLs aren't manipulated

@k88hudson @oyiptong @pdehaan feedback?

**Comment by sarracini** [comment]
GOOD NEWS React will check for any malicious content being injected: 
* https://facebook.github.io/react/docs/tutorial.html#whats-going-on
* https://facebook.github.io/react/tips/dangerously-set-inner-html.html

So we'll just check that the URLs aren't manipulated when they come back out

**Comment by sarracini** [comment]
So this is definitely already done when #428 landed
