### ISSUE TITLE
Activity Stream does not load content on re-install (from testpilot repo)

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/activity-stream#682]
_filing on behalf of @edgibara_

>Activity Stream work fine but after a re-install the program dont work everytime and need me to re-open the New Tab to work. (That is Normal?)

_originally at https://github.com/mozilla/testpilot/issues/797_

**Comment by SoftVision-PaulOiegas** [comment]
It could be related to #674, when remember windows and tabs from last time option is set.

**Comment by tspurway** [comment]
@oyiptong  to verify

**Comment by oyiptong** [comment]
The description seems to be about restore behavior rather than being about performance.
This is probably due to the addon not re-attaching workers.

**Comment by oyiptong** [comment]
might be related to #674

**Comment by oyiptong** [comment]
Closing as duplicate #674
