### ISSUE TITLE
Add white icon for toolbar icon

### ISSUE THREAD

**Issue by charlesmilette** [mozilla/activity-stream#685]
![capture](https://cloud.githubusercontent.com/assets/6440374/15219577/4ee829f4-1832-11e6-9809-4bdd33b539f3.PNG)

**Comment by k88hudson** [comment]
Thanks for the feedback!

**Comment by SoftVision-PaulOiegas** [comment]
Related to #545

**Comment by bryanbell** [comment]
On it.

**Comment by bryanbell** [comment]
needs something like this:  -inverted 

https://dxr.mozilla.org/mozilla-central/source/browser/themes/shared/search/search-arrow-go.svg

**Comment by charlesmilette** [comment]
[Might help you](https://github.com/charlesmilette/GoogleKeepPanel/blob/master/index.js). I only found two things not working correctly with my implementation:
- Private browsing (personnas won't apply)
- Personas preview (they don't trigger a refresh of the icon)

**Comment by bryanbell** [comment]
[Share Icons.zip](https://github.com/mozilla/activity-stream/files/567881/Share.Icons.zip)
Share icons needed.

**Comment by SoftVision-CiprianMuresan** [comment]
The share button is also barely visible on some themes.

**Comment by sarracini** [comment]
Closing this as we won't be having an icon in the system-addon version, and the test pilot version will soon be unsupported
