### ISSUE TITLE
Bug 1272346 - Incorrect favicon displayed for random YouTube links 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#687]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1272346
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.16

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.16) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to "www.youtube.com".
3. Open a few videos and for each of them, hover over the users names that posted comments.
4. Click the Activity Stream button from the browser toolbar and refresh the Timeline page.
5. Observe the favicon for visited youtube links.

[Expected result]:
- Youtube links from "Just now" area are displayed with their specific favicon.

[Actual result]:
- Youtube links from "Just now" area are randomly displayed with the google favicon.

[Notes]:
- The issue is reproducible on the New Tab page as well.
- Attached a screen recording of the issue https://goo.gl/p4z4ZL.

**Comment by k88hudson** [comment]
This should be resolved with https://github.com/k88hudson/activity-stream/commit/dd70e49fdb9e7dca6409897b01b80813be1d9adc

**Comment by SoftVision-VladBacia** [comment]
This issue was verified with latest Nightly 50.0a1 (Build ID: 20160607030217) using Activity Stream v1.0.19-dev and it cannot be reproduced.
