### ISSUE TITLE
Limited number of entries per page is frustrating

### ISSUE THREAD

**Issue by fvsch** [mozilla/activity-stream#693]
Scenario:

1. Open a new tab. Look at the "Just now" entries trying to find something you visited recently.
2. It’s not there (in the 10 entries). Click on the "See all activity" button.
3. You get a page with the same 10 entries, and 7 more. That’s not much to get you going.
4. Click "See more activity". You get 17 new entries (if I counted correctly).
5. Still not there? Click "See more activity" a few times while visually browsing the list.

Clicking 4, 5 or 8 times on "See all activity" / "See more activity" gets old rather quickly.

So I would suggest a slightly more generous pagination count. Maybe 30 or 40? Perhaps loading 30 at first (on the "All" page's initial state, I’m not suggesting changing the New Tab item count), then adding 50 items at a time?

Infinite (lazy-)loading might be a solution too.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/activity-stream/issues/417

**Comment by k88hudson** [comment]
This will be fixed by #417, which is now in progress!

**Comment by k88hudson** [comment]
Ok, infinite scroll has been merged. It should be in the next release 👍
