### ISSUE TITLE
Remove all timeouts from PreviewProvider.js

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#696]
There are multiple timeouts in PreviewProvider designed to 

1) delete expired data from the cache

2) refresh cached data from a remote source

However, there are logical errors in these timeouts which are producing a flood of invalid traffic to the proxy, which places an unnecessary amount of strain on the servers, and is difficult to debug.  We should remove all of these timeouts on the grounds that

1) We can expire keys at lookup time which is much simpler and 

2) Doing so will encompass the use case of refreshing stale data automatically 

This closes the following bugs.

Steps to reproduce:  Reduce periodic timeouts to some small interval (ie 10s) and observe erroneous network calls.

Related: 

https://github.com/mozilla/embedly-proxy/issues/70

https://github.com/mozilla/activity-stream/issues/518

**Comment by oyiptong** [comment]
Expiring at lookup can be done, but will increase latency.

Can we Identify the bugs are and fix them instead? That might be cheaper

**Comment by rlr** [comment]
Yeah, this makes sense. `_startPeriodicBuildPreviewCache()` (which is what does the timeouts) calls `_asyncBuildPreviewCache()` which has a bug in it. See https://github.com/mozilla/activity-stream/issues/518#issuecomment-218909183. That should fix it

**Comment by sarracini** [comment]
^ building on @rlr 's idea,  #697 fixes the null issue so we don't need to remove the timeouts anymore
