### ISSUE TITLE
Seeing a lot of "load_reason: none" in the pings 

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/activity-stream#698]
There are a large number of pings with "load_reason: none" [see here](https://sql.telemetry.mozilla.org/queries/363#607). Looks like if the page didn't load at all, the addon just populated it as "none". Given that this happens quite often, perhaps it's worth investigating it a bit. Attached is a sample ping fetched from the raw logs.

Also, I'd recommend using a more specific value for this, such as "not loaded yet", instead of "none". Cause there is a "other" value for the unknown "load_reason" already.

@emtwo @k88hudson @tspurway 

```json
{"addon_version":"1.0.16",
 "total_history_size":88186,
 "date":"2016-05-12",
 "timestamp":1463097577207,
 "locale":"en-US",
 "ua":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko\/20100101 Firefox\/46.0","url":"resource:\/\/activity-streams\/data\/content\/activity-streams.html#\/",
 "session_duration":0,
 "unload_reason":"close",
 "action":"activity_stream_session",
 "tab_id":"-3-17",
 "load_reason":"none",
 "page":"NEW_TAB",
 "total_bookmarks":351}
```

**Comment by pdehaan** [comment]
```js
"load_reason": "¯\_(ツ)_/¯"
```

**Comment by emtwo** [comment]
It would probably be nice to avoid both the `none` and `other` labels and use more descriptive names.

**Comment by oyiptong** [comment]
+1

**Comment by ncloudioj** [comment]
The "other" should already be fixed, the most recent date it showed up was "2016-04-04".

Will change "none" to "not_loaded".

**Comment by emtwo** [comment]
Additional issue @ncloudioj discovered:

If you open two new tabs in a row quickly, two pings are sent. The first has a load reason of "none" and an unload reason of "unfocus". This means the user opened a new tab and quickly switched away from it before it finished loading. This makes sense and sounds good.

However, once that tab is done loading, it sends ANOTHER ping with load reason "newtab" and unload reason "refresh". This ping doesn't make sense and we probably don't want to send it. If a page already ended its session and it's not active, we don't care about what happens to it after.

**Comment by ncloudioj** [comment]
Found another related issue with @emtwo and @k88hudson :

When closing the whole Firefox window, those inactive tabs also sent pings with `"unload_reason: close"`. This was not intended as those inactive tabs already sent pings with `"unload_reason: unfocus"` before. The addon should only send a "close" ping for the active tab in this case.
