### ISSUE TITLE
Neither Activity Stream nor Universal Search will enable

### ISSUE THREAD

**Issue by AustinGuy** [mozilla/activity-stream#699]
From https://testpilot.firefox.com/experiments/activity-stream and https://testpilot.firefox.com/experiments/universal-search, I clicked the "Enable Activity Stream" and "Enable Universal Search" buttons. The text changed to "Enabling..." with a barber-pole animation behind it. Nothing ever happened. I let the Activity Stream activation sit overnight last night and nothing happened. Today I tried again, both Activity Stream and Universal Search, half a dozen times each, letting the "Enable..." animation run for various periods, 30 seconds to 30 minutes. Nothing.

I'm running FF 46.0.1 on WIn 7 Pro SP1. I use Adblock Plus but disabled it on testpilot.firefox.com. I was able to activate Tab Center immediately.

**Comment by softvision-VladBacia** [comment]
@AustinGuy , thank you for reporting this. We investigated this issue on Windows 7 x64 and Windows 8.1 x64 (Firefox 46.0.1, Build ID: 20160502172042) and it is somehow reproducible. We could reproduce this issue through the following steps:

[PREREQUISITES]:
1. Have a Firefox account that is logged into Test Pilot.
2. Test Pilot is installed on the profile used.

[STR]:
1. Open https://testpilot.firefox.com/experiments/activity-stream in tab 1.
2. Open https://testpilot.firefox.com/experiments/activity-stream in tab 2.
3. From Tab 1 click on "Enable Activity Stream" button.

[EXPECTED]:
- After Activity Stream add-on is installed, the state of "Enable Activity Stream" button will switch from "Enabling..." into "Disable Activity Stream".

[ACTUAL]:
- "Enable Activity Stream" button remains in "Enabling..." state, even if the Activity Stream add-on was successfully installed.

[NOTES]:
- Even if the "Enable Activity Stream" button remains in "Enabling..." state,  Activity Stream add-on is successfully installed.
- I have successfully install Activity Stream add-on on a Firefox profile that has Adblock Plus or uBlock Origin enabled/disabled, I didn't encountered any problems.
- I have successfully installed the Activity Stream add-on using a bandwidth limiter (limit was set to 15 KB/s).

Please try to install Activity Stream add-on on a new profile using the same Firefox account and please report back the results obtained. Go to `about:addons`->`Extensions` screen and verify if Activity Stream add-on has been installed.

**Comment by pdehaan** [comment]
@AustinGuy Thanks for the report. A couple other users have reported this as well and we're investigating.

For more information, you can follow this **Test Pilot** issue: https://github.com/mozilla/testpilot/issues/843

Closing in favor of upstream Test Pilot bug.
