### ISSUE TITLE
Reading List

### ISSUE THREAD

**Issue by bradmont** [mozilla/activity-stream#700]
I would find it very helpful to have a "read later" list on the activity stream, where I can add pages I come across but don't have the time to read right away --  like the the reading list in Firefox mobile.

**Comment by k88hudson** [comment]
This is a great idea 👍 we are definitely considering this

**Comment by pdehaan** [comment]
Ref: #414
Not sure if this would integrate w/ the Sharing and Send to Device stuff in #414.
I don't think we have a reading list in Firefox desktop and just use Pocket.

**Comment by bradmont** [comment]
Perhaps a relatively simple way to handle this (without needing to mess with pocket or reading list infrastructure) could be simply to have a "read later" bookmarks folder that populates a view on the activity stream.

**Comment by sarracini** [comment]
Out of scope for this repo - trello is where we should put feature requests
