### ISSUE TITLE
Favicon missing for some tumblr pages' tiles on Activity Stream 

### ISSUE THREAD

**Issue by dholbert** [mozilla/activity-stream#702]
STR:
1. Ideally starting with a fresh profile, install Activity Stream.
2. Visit http://fionalanham.tumblr.com/image/144076668817 or http://richdifeo.tumblr.com/image/140564663352 or probably any number of other tumblr pages.
3. Open a new tab, and look for your tumblr site in the "Top Sites" section.
4. (sometimes necessary): reload your new tab.

ACTUAL RESULTS:
* The tumblr tiles are shown with a broken-image icon.
* If I right-click the broken broken-image and choose "View Image", it takes me to e.g. http://fionalanham.tumblr.com/favicon.ico (for the first option above).
* That URL has very strange properties. If I view it in Firefox directly, I get a 404 (though it renders as a blank page -- I can tell it's 404 from checking the Browser Console).  Same goes for wget -- 404.  But if I download it with "curl", e.g.
   `curl http://fionalanham.tumblr.com/favicon.ico > icon.ico`
...it gives me a tumblr "t" favicon image. So it seems Tumblr may or may not actually serve it to us, depending on how we request it, I guess?

EXPECTED RESULTS:
- Meaningful icon on the tile for the tile.
- Ideally we should request the favicon "in the same way that we do when actually displaying the site", whatever that means, so that it successfully downloads.  But as a fallback, we should also detect 404 / broken icons and display some fallback content (e.g. initials) instead. We should never show a broken-image icon on these tiles.

**Comment by dholbert** [comment]
Screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/426803/15280242/1050f73a-1ae3-11e6-8fda-a554455a5876.png)

**Comment by pdehaan** [comment]
Neat trick. Seems like Embed.ly is giving us that favicon address:
http://embed.ly/docs/explore/extract?url=http%3A%2F%2Ffionalanham.tumblr.com%2Fimage%2F144076668817

**`favicon_url`:** http://fionalanham.tumblr.com/favicon.ico 
Which indeed is a broken URL: ![](http://fionalanham.tumblr.com/favicon.ico)

But yeah, something very odd at play here. This is the only "favicon.ico" i see in source:

```
<link rel="shortcut icon" href="http://assets.tumblr.com/images/favicons/favicon.ico?_v=a891a6916b745ae20be499f98db2f875" type="image/png"/>
```
![](http://assets.tumblr.com/images/favicons/favicon.ico?_v=a891a6916b745ae20be499f98db2f875)

But that isn't the same favicon that appears in my Firefox tab:
![menubar_and_http___fionalanham_tumblr_com_image_144076668817_and_mozilla_-_calendar_-_week_of_may_16__2016](https://cloud.githubusercontent.com/assets/557895/15296687/51556af0-1b4b-11e6-8c32-8c1461a65c3d.png)

**Comment by dholbert** [comment]
> favicon_url: http://fionalanham.tumblr.com/favicon.ico
> Which indeed is a broken URL
...except it's a perfectly-fine URL if I download it with `curl`, for some reason. *shrug*

**Comment by pdehaan** [comment]
Ref: #449
I don't think this issue is tracking protection related, but would be solved by a similar approach of better fallbacks for broken favicon images. And this _exact_ use case would be solved by our proxy for tippy-top-sites which will have a Tumblr icon.

Ultimately, this looks like an odd Tumblr issue (where the icon is 404, but works via curl), mixed with an embed.ly issue.

Closing this in favor of the related #449 which should also handle this issue.
