### ISSUE TITLE
Use new ContentSearch.jsm module

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#704]
With a refactoring landed in nightly of ContentSearch.jsm, our current search stuff is a little broken. We'll need to change SearchProvider.js in Activity Stream to reflect the changes.

**Comment by oyiptong** [comment]
Make sure to keep the changes backward compatible, I.e AS should work for both pre content search refactor and post refactroe

**Comment by SoftVision-PaulOiegas** [comment]
We found this too and logged it in Bugzilla and cloned it in Github as (#706). Sorry for the dupe here, haven't seen the email from github in time.
https://bugzilla.mozilla.org/show_bug.cgi?id=1273164

**Comment by sarracini** [comment]
closing this as a dupe of #706, will add a couple comments in that bug
