### ISSUE TITLE
Incorrectly logging session "unload_reason"

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#707]
In the activity stream distributions dashboard, we can see ~15,000 search events and ~44,000 click events. However, there are only 29 pings with "click" as unload reason and 22 with search as unload reason.

I confirmed that clicks are triggering a "navigation" unload reason but I think "navigation" should only be for navigating away from activity stream without any engagement. We should look into what's happening with search as well

**Comment by oyiptong** [comment]
+1

**Comment by sarracini** [comment]
@ncloudioj confirm and close?

**Comment by ncloudioj** [comment]
Yes. It's fixed now.
