### ISSUE TITLE
Bug 1273524 - Visited local websites are displayed in browser history but not on Activity Stream pages 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#713]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1273524
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.16

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.16) was previously installed on a clean profile.  
- Save/download the website from 'Attachments'. 

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open the saved website.
3. Click on "Activity Stream" button from browser toolbar.

[Expected result]:
- The local website that was visited is displayed in "Timeline".

[Actual result]:
- The local website that was visited is displayed in History but is missing from "Timeline".

[Notes]:
- If the local website is bookmarked, it will not be displayed in "Bookmark" screen from Timeline.
- The issue is reproducible on the New Tab page as well.
- Attached a test page to the issue https://goo.gl/BJefBo .

**Comment by oyiptong** [comment]
works as designed

**Comment by jaredkerim** [comment]
Until we are able to process metadata locally, we can not display localhost/filesystem/vpn pages in activity stream.  When we move metadata processing to take place in the browser, we can revisit this.  Closing for now.
