### ISSUE TITLE
Bug 1273535 - A website will no longer appear in "Highlights" area if it is added and removed from Bookmarks several times 

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#714]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1273535
<hr>
[Affected versions]:
- Nightly 49.0a1
- Activity Stream 1.0.16

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.16) was previously installed on a clean profile.
- Open the browser with the created profile and have at least two tabs opened.  

[Steps to reproduce]:
1. Visit a website and bookmark it.
2. Click on "Activity Stream" button from browser toolbar and close the tab from step #1.
3. Click on the visited website from "Just now" area and remove it from bookmark.
4. Click on "Activity Stream" button from browser toolbar and close the tab from step #3.
5. Click on the visited website from "Just now" area and bookmark it.
6. Repeat the steps from #2 to #4.
7. Click on "Activity Stream" button from browser toolbar.

[Expected result]:
- The bookmarked website is displayed in "Highlights".

[Actual result]:
- The bookmarked website will no longer be displayed in "Highlights", even if 30 minutes have passed since last visit.

[Notes]:
- If we go a step further and remove the website from bookmarks, the website won't be displayed in "Highlights" even if hours have passed since last visit.
- The issue is reproducible on the New Tab page as well.
- Attached a screen recording of the issue https://goo.gl/dHEUYo .

**Comment by tspurway** [comment]
intended behaviour.  @oyiptong to verify

**Comment by oyiptong** [comment]
verified
