### ISSUE TITLE
Cluster similar tab visits in categories

### ISSUE THREAD

**Issue by marco-c** [mozilla/activity-stream#722]
It would be awesome if we could cluster the activity in categories.
It might be difficult to do it in detail (e.g. `plan trip to XXX`, `research about pizza`, etc.), but we could at least cluster by website (e.g. if I have seven subsequent visits to different bugzilla bugs, just show one entry that I can expand to see the individual visits).

**Comment by softvision-VladBacia** [comment]
@marco-c thanks for the feedback. From my point of view this issue is similar to #609 .

**Comment by aaronrbenson** [comment]
https://trello.com/c/6WRXiwEU

**Comment by sarracini** [comment]
Closing this as it's feature tracking will be done on trello (the link above). We can re-file more specific tickets for the engineering work when we decide to start implementing this
