### ISSUE TITLE
Bug 1273923 - The "Please fill out this field." tooltip is not horizontally aligned with the Top Sites and Highlights tiles

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#723]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1273923
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.17

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.17) was previously installed on a clean profile.  

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and open a new tab.
2. Without writing anything in the search bar, click the "Search" button (right arrow).
3. Observe the "Please fill out this field." tooltip position.

[Expected result]:
The "Please fill out this field" tooltip should keep the aesthetic of the page and be aligned with the Top Sites and Highlights tiles.

[Actual result]:
The "Please fill out this field" is not aligned with the Top Sites and Highlights tiles.

[Notes]:
- Attached a screenshot of the issue
![tooltip alignment](https://cloud.githubusercontent.com/assets/17258026/15365057/80dd3d88-1d27-11e6-8a41-db76e941d30b.png)
.

**Comment by tspurway** [comment]
The text "Please fill out this field" is also worrysome.

**Comment by bryanbell** [comment]
Kill it with FIRE!

**Comment by sarracini** [comment]
to be consistent with the current implementation of about:newtab, when you click the submit button with an empty search string, it should take you to the default page of the search provider. will fold that into this
