### ISSUE TITLE
replace about:home with activity stream

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#724]
As a windows user who views each site in a new window, I want to see activity stream so that I can get value out of my recent items.  

A number of users who open a single window for every site often see about:home or the custom home page that they've set.  New Tab is for multi-tab users.  To maximize the impact of the activity stream experiment, let's take over about:home.  If users want to fall back to the old about:home experience, we should verify they can set that as their default home page in preferences.

**Comment by edmoz** [comment]
@nchapman could you let us know the priority of this if this should be in Amethyst? Can someone on engineering pick this up in the sprint?

**Comment by tspurway** [comment]
I think it is important to track which page (about:home, about:newtab) the user sees the page on.  Let's make sure to track this in the session ping.

**Comment by rlr** [comment]
AFAIK, about:home doesn't have the same hooks to override that about:newtab has (thanks to the RNT work. @oyiptong correct me if I am wrong. Given that, this might be tricky. @oyiptong ideas?

**Comment by rlr** [comment]
Something that would work would be to change their Home Page preference like:
<img width="838" alt="screen shot 2016-05-19 at 12 04 57 pm" src="https://cloud.githubusercontent.com/assets/36629/15400591/0d75217e-1dba-11e6-836b-9d473de70ee1.png">

But we probably only want to change it if they haven't changed the default. Then they can go reset to default if they don't like... But hmm, how would we detect that the next time we startup or install a new version so that we don't keep changing it on them?

**Comment by edmoz** [comment]
That works for me and it's something a user could see and change back easily.

**Comment by pdehaan** [comment]
bonus points if we could use a URI like `about:newtab` instead of a cryptic `resource://activitity-streams/...` URI.

**Comment by edmoz** [comment]
about:newtab goes to tiles currently

**Comment by oyiptong** [comment]
For `about:home`, We can just change the pref `startup.homepage_override_url` to the url @rlr mentioned.

Should we go that route, on initial install, we should capture their current start page, and restore it if someone uninstalls the addon. If the person manually overrides that pref, we should remember that and do nothing upon uninstalling.

Keep in mind that impacts snippets.

We do not want to change document URI to `about:newtab` for a number of reasons:
* about:newtab is a privileged resource URI, we are loading an unprivileged resource
* about:newtab loads or redirects to the default newtab page for Firefox, which activity stream, sadly, isn't yet

**Comment by edmoz** [comment]
@nchapman can you comment on the design
