### ISSUE TITLE
Bookmarks - Timing

### ISSUE THREAD

**Issue by AdamDenoon** [mozilla/activity-stream#728]
In the Bookmarks tab under "See all activity", the top-most bookmark has its date marked as "Just Now", despite being bookmarked weeks ago.

OS X 10.11.4
Firefox 46.0.1

**Comment by softvision-VladBacia** [comment]
@AdamDenoon thank you for reporting this. We already tracked this issue in #604 and it was fixed in #710. The fix will be available in the next release.
