### ISSUE TITLE
Bug 1274241 - Highlights item brought from queue after a delete, is wrongly replaced at refresh by a related page of the deleted item

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#730]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1274241
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.17

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.17) was previously installed on a profile.
- Have more more history so that the "Highlights" area is populated with visited websites.
- Visit multiple articles from the same hostmane(eg. multiple articles from www.bbc.com) and wait between 30 minutes and 1 hour, so that at least one of the visited articles to be added to "Highlights" area.

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Hover the mouse cursor over the article from prerequisites that it is displayed in "Highlights" area.
3. Click on "X" button and remove it from History.
4. Observe the Highlights area.
5. Refresh the Timeline.
6. Observe again the Highlights area.

[Expected results]:
4. Next item from Highlights queue is displayed.
6. Same 3 articles are displayed in Highlights after refresh. 

[Actual results]:
4. Next item from Highlights queue is displayed.
6. The item that has been brought from queue is replaced by an item that belongs to the same hostname as the deleted one.

[Notes]:
- Added screen recording with the issue https://goo.gl/FDwUBA .

**Comment by tspurway** [comment]
working as intended for now
