### ISSUE TITLE
Show better favicons by setting optimizeToDimension preference

### ISSUE THREAD

**Issue by rittme** [mozilla/activity-stream#731]
Even though the browser places need more work to store bigger favicons in a better way, most of the fetching and rendering work is already implemented. Setting the pref for the favicon size hard cap can be a temporary solution to be able to store better favicons.

`places.favicons.optimizeToDimension: 64`

If we set this pref to 64 (32px favicons with 2x for retina displays) we allow the browser to store bigger images that we can use with no change to our code.

**Comment by pdehaan** [comment]
I lack any real context on how favicons in Firefoxen work, but a quick ~~Google~~ Yahoo! search gave me this bugzilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=523646 

Some good information and quotes, such as:

> _"This won't make all favicons bigger.  Most favicons on the web are 16x16, and they already fall under our 1KB limit.  Increasing this just means that we get a better images when a site might actually provide a larger icon, or when we want to for defaults."_

So increasing the pref may not have an effect on a bunch of sites (depending on the favicon that they're serving us). But building our own embedly which checks for apple-touch-icons (see #603) combined with [tippy-top-sites](https://github.com/nchapman/tippy-top-sites) would give us a really good win -- at the cost of we have to build a thing.

**Comment by rittme** [comment]
Our own embedly could also check for favicons with bigger ICOs, PNGs and even SVGs. There are some telemetry on favicons, by file type, that the desktop browser download at the PLACES_FAVICON_***_SIZES buckets.

There is some more information here: 
http://www.rittme.com/mozilla-2014/assets/player/KeynoteDHTMLPlayer.html#19

This discussion may have more information about what is going on at the browser too:
https://bugzilla.mozilla.org/show_bug.cgi?id=798223
