### ISSUE TITLE
Dev Addon should use Production Embedly Proxy

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#737]
The dev prefs points to the staging embedly proxy for local development use, see here:

https://github.com/mozilla/activity-stream/blob/master/dev-prefs.json#L5

However, this should point to the production embedly proxy endpoint here:

https://embedly-proxy.services.mozilla.com/v2/extract

The reason for this is that the stage embedly proxy is meant to test embedly proxy code deploys which may break, and if the stage instance breaks (which is an expected result) then that will block use of any addons built using the dev prefs which can block addon development.

**Comment by jaredkerim** [comment]
@k88hudson @oyiptong

**Comment by pdehaan** [comment]
@jaredkerim: pull-requests welcome. \*cough\*
