### ISSUE TITLE
Refactor PreviewProvider to hide link processing

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#741]
Presently, we preprocess links to be looked up in the cache or remotely requested outside of previewProvider.js, see here:

https://github.com/mozilla/activity-stream/blob/fad6c5553332c1f2874b9b1d9c083068608bf1b0/lib/ActivityStreams.js#L153-L157

and here:

https://github.com/mozilla/activity-stream/blob/fad6c5553332c1f2874b9b1d9c083068608bf1b0/lib/ActivityStreams.js#L345-L349

However this is an implementation detail of previewProvider and should not be the responsibility of the external caller.  Please consolidate this so that previewProvider has external interfaces for retrieving cached data or remotely fetching and storing data by only receiving an array of URL strings.  Processed links should only live within previewProvider.js.

**Comment by sarracini** [comment]
Fixed with #872
