### ISSUE TITLE
Restoring of last usage

### ISSUE THREAD

**Issue by gangit** [mozilla/activity-stream#746]
While testing I have noticed the following:
1. A user can closing the browser by mistake, there is no message asking whether you want to close the all tab or the browser.
2. If I am not mistaken, restoring previous search activities on the browser is not available.

**Comment by sarracini** [comment]
Thanks for the feedback!
Unfortunately this is not an Activity Stream related bug, it sounds more like a Firefox ticket, so we will be closing it.
