### ISSUE TITLE
Add Sentry tooling to front-end 

### ISSUE THREAD

**Issue by tspurway** [mozilla/activity-stream#747]
https://docs.getsentry.com/hosted/clients/javascript/

By default, Sentry will ping all uncaught JS exceptions from the browser, which will give us a rough, but good indication of how AS is performing in the wild.  I believe we already have a Mozilla account for Sentry - @relud and @jaredkerim know more.

**Comment by tspurway** [comment]
Just escalating this. 

@jasonthomas, how do we hook up to sentry/raven-js from our addon?

**Comment by tspurway** [comment]
Is this blocking progress on #1145?  
^ @jaredkerim @oyiptong

**Comment by jaredkerim** [comment]
@tspurway No, #1145 should be diagnosable without any help from Sentry.

**Comment by tspurway** [comment]
Note that this is just for the content side - the chrome process is covered in #1231

**Comment by jaredkerim** [comment]
You should be able to follow the react integration docs here:

https://sentry.io/for/react/

**Comment by dmose** [comment]
@jbuck / @jasonthomas : is either of you guys the right person to help us get something set up on the server side here?

**Comment by jasonthomas** [comment]
It looks like a sentry project was already created for activity stream. I've sent you a invite to access sentry and you should be able to manage the project directly.

**Comment by dmose** [comment]
Here's the [Sentry docs discussion about sensitive data](https://docs.sentry.io/learn/sensitive-data/).  The short version is they do all of their sanitization on the server side.  

At the very least, the server-side does record user-agent style info and IP address of the client (much like any webserver, really).

With some work, I can scrub most (or maybe all) of the error messages for other things (eg URLs) on the client-side before they're sent.  If their stack crawler gets better about parsing arguments on the stack (or can actually succeed at it now), those might want to be scrubbed as well.

Some guidance here would be helpful.

@nchapman ?

@jaredkerim can you paste a pointer to the scrubbing you're doing on the Python server side?

**Comment by dmose** [comment]
I've just poked the folks who maintain the Raven JS toolkit to improvement their scrubbing capabilities over at https://github.com/getsentry/raven-js/issues/296 and we'll see what response that gets.

**Comment by dmose** [comment]
It does look like we can tell the server not to collect/record the IP addresses.

**Comment by dmose** [comment]
It is worth noting that a variety of server-side projects at mozilla already collect all of this kind of data as web applications running on a server, so there may be some precedent there.

**Comment by dmose** [comment]
As part of this, I discovered that the stacks that Sentry sends are/were almost useless when resource: URIs are involved.  I fixed the code in getsentry/ravenjs itself, https://github.com/getsentry/raven-js/pull/837/files, and it should be contained in the next ravenjs release after 3.9.2.

**Comment by benvinegar** [comment]
Just chiming in: the fix for `resource:` URLs was published in Raven.js 3.10.0.

**Comment by k88hudson** [comment]
This might be useful when React 16 is released:

https://facebook.github.io/react/blog/2017/07/26/error-handling-in-react-16.html

**Comment by tspurway** [comment]
We need to know if the system addon is crashing.  Let's do something here even if we can't get stack traces.

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1421438
