### ISSUE TITLE
"Remove from History" button is not available in Activity Stream Timeline for bookmarked items

### ISSUE THREAD

**Issue by SoftVision-VladBacia** [mozilla/activity-stream#750]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1275946
<hr>
[Notes]:
- If in Activity Stream Timeline is a bookmarked item, in order to remove it from history we first need to remove it from bookmarks, then refresh the page because the website disappears and then click again on the "X" button and remove it from Timeline. Video [here](https://drive.google.com/open?id=0B6QogV2AJFKicWtucmduOTF3aUE).
- When removing a bookmarked website from Bookmarks History screen, the website is also removed from Timeline History. That website will be redisplayed only after a refresh. Video [here](https://drive.google.com/open?id=0B6QogV2AJFKiaC1yRXd2UHE2QTQ).
- This issue is also reproducible on Activity Stream New Tab page.

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.18

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.18) was previously installed on a clean profile.
- Have more history so that the "Highlights" area is populated with visited websites.
- Bookmarked websites are also present in Timeline History.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Activity Stream button from the browser toolbar.
3. Move the mouse cursor over a bookmarked website.
4. Click on "X" button.
5. Click on "Remove from History" button.

[Expected result]:
- The bookmarked website can be removed from Timeline 

[Actual result]:
- The "Remove from Bookmarks" button is displayed instead of "Remove from History".
![remove from history a bookmarked item](https://cloud.githubusercontent.com/assets/9248513/15581641/db76f212-2375-11e6-83bc-650d6fb43e87.jpg)

**Comment by SoftVision-VladBacia** [comment]
Followup for #715

**Comment by bryanbell** [comment]
![remove_bookmarks_and_delete](https://cloud.githubusercontent.com/assets/228979/15694609/1bc4db22-2754-11e6-947f-d296e10d503b.png)

Users should be able to remove a bookmarks and or delete an item from history. 

Deleting from history should not remove the bookmark however. It should only remove the item from history.

**Comment by pdehaan** [comment]
@bryanbell Re: "Remove Bookmark", was it also the plan that I can toggle that big, blue bookmark star on the far left to add/remove bookmarks as well?
Tooltip menus are useful, but it feels like toggling the actual star/circle would possibly be more intuitive.

**Comment by bryanbell** [comment]
I started the thought in the context of a highlights. 

![pasted_image_5_31_16__5_31_pm](https://cloud.githubusercontent.com/assets/228979/15694775/84d5eb8c-2755-11e6-81d0-9b62822a2da2.png)

What worries me about making the dot/star the sole bookmark/remove-bookmark control is that we'll be using that spot to show other context clues, like pocket, or if it's an open tab. So let's for sure give people a quick bookmark tool by hovering over the dot, but let's also include that control in the ••• menu.

**Comment by bryanbell** [comment]
example of an open tab. 
![pasted_image_5_31_16__5_45_pm](https://cloud.githubusercontent.com/assets/228979/15694981/862002b4-2757-11e6-9367-d69d8a47e997.png)

**Comment by tspurway** [comment]
probably related to #701

**Comment by k88hudson** [comment]
This is resovled by #701

**Comment by SoftVision-VladBacia** [comment]
This issue is similar with #887. 

This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160630030207) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
