### ISSUE TITLE
As a user, I want an inline preview of a URL so I can see what I've seen without having to click a bunch of links

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#752]
As a Slack user, I really like inline previews.

Not sure how we display these to the user (possibly lazy load them and make the users click a triangle icon to see previews). But this does a good job of displaying a summary and a primary image and easy UI to toggle a bookmark, etc. But in most cases, this would probably give me enough context of the page to see if it was something I truly cared about vs just loaded and quickly closed because it wasn't the recipe or page that I wanted. In most cases we probably have most of this data via Embedly anyways (title, favicons, provider name, summary, possibly an image).

<img width="675" alt="slack_and_issues_ _mozilla_activity-stream" src="https://cloud.githubusercontent.com/assets/557895/15588995/a2e529a8-2345-11e6-97d3-c1581e8da98e.png">

Ref: http://embed.ly/docs/explore/extract?url=https://food52.com/recipes/36062-carrot-lentil-and-feta-salad

**Comment by pdehaan** [comment]
Actually, possibly a dupe of #415 (although this isn't specific to images or videos).

**Comment by pdehaan** [comment]
FWIW, Apple just [WWDC 2016] announced "rich text links" in Messages (in upcoming iOS 10+mac OS "Sierra").

> _"Messages makes conversations more interesting, now allowing you to preview web links and watch video clips within the app, ..."_
> &mdash; via http://www.apple.com/newsroom/2016/06/apple-previews-major-update-with-macos-sierra.html

**Comment by sarracini** [comment]
Trello spec: https://trello.com/c/vkzeme0X/35-as-a-user-i-want-an-inline-preview-of-a-url-so-i-can-see-what-i-ve-seen-without-having-to-click-a-bunch-of-links 

Closing this in favour of tracking in trello
