### ISSUE TITLE
Bug 1276679 - If a specific link is bookmarked multiple times it has to removed just as many times in order to fully remove it

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#768]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1276679
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.18-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.18-dev) was previously installed on a clean profile.
- Have the same link bookmarked multiple times, in the same folder or in separate folders.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open Activity Stream Timeline from the browser toolbar and click the on the Bookmarks tab.
3. Hover the saved bookmark from prerequisites and click the "X" button.
4. Click the "Remove from Bookmarks" button.

[Expected result]:
The Bookmark is removed from all of the saved locations.

[Actual result]:
In order to fully remove the Bookmark you have to remove it as many times as you have saved it.

[Notes]:
- The default browser behavior is to remove all the link entries when choosing to remove one of them.
- Attached a screen recording of the issue (https://goo.gl/yVQtCv).

**Comment by bryanbell** [comment]
If a site has its bookmark removed. It should be all recorded entries.

**Comment by sarracini** [comment]
closing this since we've removed timeline
