### ISSUE TITLE
Bug 1276680 - Unable to remove webpages from the second batch of loaded History items in Timeline->History

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#769]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1276680
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.18-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.18-dev) was previously installed on a clean profile.
- Have enough History and Bookmarks in the profile so when scrolling is performed, a new batch of History items is fetched.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open Activity Stream Timeline from the browser toolbar.
3. Scroll down the list until the next batch is automatically loaded.
4. Hover one of the newly loaded links and click the "X" button.
5. Click the "Remove from History" button.
6. Refresh the page and look for the removed item.

[Expected result]:
The link is removed from History and is no longer shown in the list, after the refresh.

[Actual result]:
The link is removed from History, but after a refresh, the link can still be found in the second History items batch of Timeline->History.

[Notes]:
- The issue is also reproducible if you choose the "Never show on this page" option.
- The issue is also reproducible when removing bookmarks from the Bookmarks tab.
- Attached a screen recording of the issue (https://goo.gl/R1bxHE).

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 10 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160620030215) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
