### ISSUE TITLE
Remove SearchProvider's dependency on ContentSearch

### ISSUE THREAD

**Issue by sarracini** [mozilla/activity-stream#775]
Advantages to writing our own slimmed down version of ContentSearch for ActivityStream:
 * No more backwards compatibility issues
 * No more having to load in ContentSearch and all the useless stuff that comes along with it
 * No more calling into private functions like ```_onMessageGetSuggestions``` which is not what we want anyways
 * We can make it do what we want, how we want

Disadvantages:
 * Code overlap/duplication with existing ContentSearch
 * Having to maintain it, instead of just using the built ContentSearch functionality 
 * It can go away when the refactored version of ContentSearch lands in FFx

what do you think @oyiptong?

**Comment by oyiptong** [comment]
We'll want to customize search results anyway. I think it's a good idea

**Comment by sarracini** [comment]
Fixed with #799
