### ISSUE TITLE
(Tracking) Write experiment definition framework

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#779]
In https://github.com/mozilla/activity-stream/issues/732 @ncloudioj and I worked on getting an A/B experiment set up (hurray!) Now that we have the wires in place, we'd like to refactor this a bit  be able to define experiments a little more easily/centrally.

We'd like to have a single file (js or json) that contains info for each active experiment, something like this:

```js
{
  name: "reverseDeleteMenu",
  description: "A test to determine how delete menu order affects engagement",
  size: 0.1
}
```

We can also might want to store control, variant, and dates active if necessary (this also helps with analysis):

```js

{
  name: "imageSize",
  description: "A test to determine how image size affects engagement",
  beginDate: "2016-06-01",
  endDate: "2016-07-01`"
  variants: {
    control: {
      description: "This is the standard size (320x480)",
      data: {
        width: 320,
        height: 480
      }
    },
    large: {
      size: 0.1,
      description: "This is a larger size",
      data: {
        width: 480,
        height: 649
      }
    },
    small: {
      size: 0.1,
      description: "This is a smaller size",
      data: {
        width: 100,
        height: 150
      }
    }
  }
}
```

The goal of this is to:
- preserve information about each experiment in one place
- make it easier to add new experiments and related data for devs/product
- provide a source file for metrics dashboards to show the right data 
- could eventually be generated by a splice-like interface

**Comment by k88hudson** [comment]
cc @ncloudioj

**Comment by pdehaan** [comment]
FWIW: A few FxA people wrote an A/B service for FxA/B testing: https://github.com/dannycoates/able
Not sure if that would be useful, or if we have a lot simpler needs.

**Comment by chuckharmston** [comment]
Related issue in Test Pilot: https://github.com/mozilla/testpilot/issues/477

**Comment by k88hudson** [comment]
This has landed!
