### ISSUE TITLE
Bug 1277273 - Re-bookmarking links from the Timeline->Bookmarks tab causes the page to hide older entries

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#784]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1277273
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.18-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.18-dev) was previously installed on a clean profile.
- Have at least 25 bookmarks saved.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open Activity Stream Timeline from the browser toolbar and click the on the Bookmarks tab.
3. Hover a saved bookmark from prerequisites and drag it to the Bookmarks Toolbar, either in a folder or just in the bar.
4. Refresh the page and drag the same link to the Bookmarks Toolbar.
5. Repeat step 4 until the issue can be observed. 

[Expected result]:
- The newly saved bookmark is moved to the first position on the list and it's timestamp is updated.

[Actual result]:
- The newly saved bookmark is moved to the first position on the list and it's timestamp is updated. As we continue to save the bookmark again and again, the Bookmarks list is shrinking and older entries are hidden.

[Notes]:
- If you re-bookmark the same link in a 10 minutes time interval, then the new bookmark will replace the old one and it will be moved to the top of the list with the updated timestamp. See Bug 1276679.
- If you re-bookmark the same link after the 10 minutes time interval, then the new bookmark will be displayed in the first position from Bookmarks History screen and it will be a duplicate of the old bookmark.
- Maybe this issue is somehow related with the link that is made between items that are visited in a 10 minutes interval and with those that are visited after the 10 minutes time interval.
- Attached a screen recording of the issue https://goo.gl/6bHelJ.

**Comment by SoftVision-PaulOiegas** [comment]
Saving the same bookmark after 10 minutes recording https://goo.gl/b2Oqo8

**Comment by edmoz** [comment]
Triage: we believe this is an edge case, reopen if more users hit this.

**Comment by sarracini** [comment]
Timeline has gone away - closing this
