### ISSUE TITLE
Bug 1277527 - Keywords written in the Search bar from Activity Stream New Tab are lost after a page refresh

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#788]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1277527

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.18-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.18-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a new tab and write something in the Search bar.
3. Refresh the page.

[Expected result]:
- The written text is still displayed in the Search bar.

[Actual result]:
- After refreshing the page, the text from the Search bar is no longer displayed.

[Notes]:
- If you follow the STR using the search bar from about:newtab and about:home, the text is still displayed in the Search bar after a refresh. In my opinion we should keep the behavior of the aforementioned pages for consistency.
- Attached a screen recording of the issue https://goo.gl/sE9reo.

**Comment by sarracini** [comment]
Closing this, as in the system addon version we will be re-using the search box that comes in the default about:newtab and about:home
