### ISSUE TITLE
Bug 1278527 - Delete from history doesn't work (regression)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#796]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1278527
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Visit a website and click the Activity Stream button from the Browser Toolbar.
3. Hover the recently visited item, click the "X" button and click "Remove from History".
4. Refresh the page.

[Expected result]:
The Timeline page is refreshed and the removed website is no longer displayed in the page.

[Actual result]:
After the page is refreshed, the previously removed website reappears.

[Notes]:
- The issue is also reproducible on the New Tab page.
- After restarting the Browser, the removed item is no longer displayed in Timeline History/New Tab pages.
- If a website is removed from Bookmarks after step 3, then the website from step 3 will no longer be displayed if a refresh was previously made.
- This issue is not reproducible with Activity Stream v1.0.19 from Test Pilot.
- Attached a screen recording of the issue https://goo.gl/YQpnpp.

**Comment by pdehaan** [comment]
I believe this was fixed via #807

**Comment by SoftVision-VladBacia** [comment]
This issue has been tested on latest Firefox release v47.0 and latest Nightly 50.0a1 (Build ID: 20160616163918 ) using Activity Stream v1.1.0 and it is no longer reproducible.
