### ISSUE TITLE
Problem in enabling activity stream

### ISSUE THREAD

**Issue by symphonystory** [mozilla/activity-stream#803]
I am not able to enable it in test pilot. it keeps showing that its enabling but actually it doesn't.

**Comment by ncloudioj** [comment]
What's your Firefox version? It requires 45 and beyond.

**Comment by symphonystory** [comment]
It's the most updated one.

-----Original Message-----

**Comment by ncloudioj** [comment]
Hmm, that sounds like an issue in Test Pilot.

Could you try installing Activity Stream from [here](https://moz-activity-streams.s3.amazonaws.com/dist/latest.html)?

**Comment by symphonystory** [comment]
That worked. Thanks. But I've same problem with universal search too.. Can you give me a link for that too??

-----Original Message-----

**Comment by ncloudioj** [comment]
There seems to be issue in the TestPilot, a bug has been filed to track this https://github.com/mozilla/testpilot/issues/963.

Unfortunately, we don't have the link for Universal Search, and please install it via TestPilot once my colleagues fix this issue.

Thank you very much for reporting this issue to us.
