### ISSUE TITLE
inline embedded video should be closer to the size of youtube's default

### ISSUE THREAD

**Issue by edwinwongsf** [mozilla/activity-stream#810]
when i watch a video in activity stream, it feels to small and makes me click on the youtube link to view it larger.  We want the convenience of watching past videos without having to navigate away. Can we do an A/B test of a larger size vs current.  Here's the difference:

<img width="1249" alt="screen shot 2016-06-08 at 11 15 58 pm" src="https://cloud.githubusercontent.com/assets/3698618/15920497/25731356-2dcf-11e6-97e8-a8eb91785bf2.png">

**Comment by pdehaan** [comment]
Another compelling reason to increase the player size is that the YouTubes context menu on our embedded videos scrolls vertically:

<img width="760" alt="new_tab" src="https://cloud.githubusercontent.com/assets/557895/15950644/813eacd6-2e65-11e6-8bc3-dc06f703f4bb.png">

**Comment by pdehaan** [comment]
On my screen, it looks like the default YouTube video dimensions are 640x360 (and our are roughly 367x206).

**Comment by nchapman** [comment]
@aaronrbenson is going to work up a few options for this.

**Comment by edmoz** [comment]
I believe are goal is to give users value.  I would find a bit of magic and value if i could just finish my video in newtab, rather than loading a big page again.  So what if we bumped it up a bit: 20%, it just feels too small to be useful.

**Comment by edmoz** [comment]
here's a comparison of twitter's sizing:

<img width="1318" alt="screen shot 2016-06-23 at 2 02 45 pm" src="https://cloud.githubusercontent.com/assets/3698618/16320153/3ff6297a-394b-11e6-9c38-09e02348ea1a.png">

**Comment by sarracini** [comment]
Feature requests should go on the trello board
