### ISSUE TITLE
Activity Stream Enabling

### ISSUE THREAD

**Issue by anilatluri** [mozilla/activity-stream#811]
Appears that Activity Stream Enabling seems to go on for ever.  The browser has been active for more than a few hours.  What am I looking forward to?  How long does it take for this two feature to become active?

**Comment by ncloudioj** [comment]
Thank you for reporting this issue.

There seems to be an issue in the TestPilot, a bug has been filed to track this https://github.com/mozilla/testpilot/issues/963
