### ISSUE TITLE
Bug 1279198 - Inconsistency between "Dismiss" button name and block action

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#813]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279198
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19) was previously installed on a profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a New Tab so the Activity Stream New Tab page is displayed.
3. Move the mouse cursor over a visited item.
4. Click on "..." button.
5. Observe the "Dismiss" option.
6. Click on "Dismiss" button.
7. Click on "Setting" button from Activity Stream New Tab page.
8. Observe "Reset Block List" option.

[Expected result]:
- Instead of "Dismiss" button there should be an option related to "Block", so the user knows exactly what that option does.

[Actual result]:
- In the new context menu the blocking option is called "Dismiss". This naming is not intuitive nor consistent with the "Reset Block List" option from Settings menu in the Activity Stream New Tab Page.

[Notes]:
- The naming for the block option should reflect exactly what the option will do. Examples of naming: "Add to Block List", "Block this page", "Block from Activity Stream".
- At first sight, I've associated the "Dismiss" option with the close context menu action. From my point of view, a user that will use Activity Stream for the first time will have difficulties in associating the "Dismiss" button with the block action and Reset Block List.
![dismiss vs block](https://cloud.githubusercontent.com/assets/17258026/15934677/1deed162-2e6d-11e6-854a-bb1a0ca884a6.jpg)

**Comment by nchapman** [comment]
I think we'll remove the reset option for now. @bryanbell will follow up.

**Comment by bryanbell** [comment]
Since the nature of the Block option has shifted to a simple Dismiss (from only New Tab only) button, there doesn't seem to be a rationale for a reset button. 

We should simply hide the settings.

<img width="239" alt="pasted_image_6_23_16__1_15_pm" src="https://cloud.githubusercontent.com/assets/228979/16318592/ae9786c8-3944-11e6-8028-6391fd2b27fc.png">

**Comment by nchapman** [comment]
We decided in triage to remove the setting from new tab and move it onto the debug page. We're also going to rename the menu item to "Reset Dismiss List".

**Comment by k88hudson** [comment]
This will be closed by @sarracini  in https://github.com/mozilla/activity-stream/issues/870, so I'm closing this
