### ISSUE TITLE
Bug 1279229 - Timestamp is displayed under the URL for visited websites, that have a long Web address

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#815]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279229
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19) was previously installed on a profile.
- Have several visited websites, that are displayed in Activity Stream Timeline History page and have a long URL.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Activity Stream button from the browser toolbar.
3. Observe the timestamp.

[Expected result]:
- Timestamp is displayed on the right side of the visited webpage and it is inline with the title.

[Actual result]:
- For websites that have a long URL, the timestamp is displayed under the URL.

[Notes]:
- This issue is also reproducible in Timeline Bookmarks and New Tab pages.
![wrong position for timestamp](https://cloud.githubusercontent.com/assets/17258026/15934882/d8ee70d0-2e6d-11e6-9799-f5bc2150e7dd.png)

**Comment by sarracini** [comment]
Strange....I don't get this behaviour 

![timestamp](https://cloud.githubusercontent.com/assets/7219526/15940023/3dc140bc-2e48-11e6-909b-c92f70cb5d2c.png)

**Comment by sarracini** [comment]
this regressed when https://github.com/mozilla/activity-stream/blob/master/content-src/components/ActivityFeed/ActivityFeed.scss#L176 was added

**Comment by rittme** [comment]
It seems I broke this in #755. Should be an easy fix.

**Comment by SoftVision-VladBacia** [comment]
This issue has been tested on latest Firefox release v47.0 and latest Nightly 50.0a1 (Build ID: 20160616163918 ) using Activity Stream v1.1.0 and it is no longer reproducible.
