### ISSUE TITLE
Bug 1279257 - Timeline /New Tab page content is lost at refresh if the page tab is dragged and opened in a new window when e10s is enabled

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#816]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279257

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Firefox has e10s enabled. 
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Open a "Timeline" page from browser toolbar or "New Tab" page.
3. Click and hold the opened page tab and drag it on the screen to open it in a new window.
4. Refresh the page on the new window and observe its behavior.

[Expected results]:
The page content is correctly displayed after refresh.

[Actual results]:
The page content disappears after the refresh and it's never displayed back.

[Notes]:
- This issue only reproduces with e10s enabled.
- The content is displayed back only when a new page of its kind is opened.
- The "New Tab" page displays the "Hang on tight! We are analyzing your history to personalize your experience" message for indefinite time.
- Attached a screen recording of the issue https://goo.gl/dL5Fu4 .

**Comment by sarracini** [comment]
This looks related to #674, similar behaviour is happening

**Comment by SoftVision-PaulOiegas** [comment]
No luck with this one. Still reproducible after #891 was merged. So there must be something else here since #674 now correctly works.

**Comment by sarracini** [comment]
Closing this as this is no longer reproducible
