### ISSUE TITLE
The Bookmarks tab on Timeline is not automatically updated with actions performed in Timeline/History and New Tab pages (Bug 1279252)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#817]
In order for this to happen, we would need to update the `Bookmarks` reducer to add/remove items when a`"RECEIVE_BOOKMARKS_CHANGES"` action is received.

*Edited for clarity by @k88hudson*
<hr>
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279252
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click the Activity Stream button from the browser toolbar.
3. Hover a website from History and Bookmark it.
4. Navigate to the Bookmarks tab.

[Expected result]:
The previously bookmarked website it is displayed in Bookmarks History page.

[Actual result]:
The previously bookmarked website is not displayed in Bookmarks History page until a manual refresh is made.

[Notes]:
- If you bookmark an item from the New Tab page, the bookmark status is updated correctly and automatically in the Timeline History page. In Bookmarks History page the bookmarked item is displayed only after a manual refresh.
- Attached a screen recording of the issue https://goo.gl/6lPTxT .

**Comment by sarracini** [comment]
Timeline has gone away - closing this
