### ISSUE TITLE
Bug 1279256 - Removing a Bookmark from Highlights using the context menu doesn't change the status until a refresh is made

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#819]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279256
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.
- Have at least one Bookmarked item in the Highlights section.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click the Activity Stream button from the browser toolbar.
3. Hover the bookmarked item from the Highlights section.
4. Expand the Highlight context menu and click "Remove Bookmark".

[Expected result]:
The status changes from "Bookmarked X second/minutes/hours ago" to "Visited X second/minutes/hours ago".

[Actual result]:
The status doesn't change, but the website is removed from bookmarks.

[Notes]:
- Attached a screen recording of the issue https://goo.gl/w4gDcd .

**Comment by k88hudson** [comment]
This appears to be fixed on current master.
