### ISSUE TITLE
Bug 1279261 - The page URL is displayed when playing an embedded video in fullscreen from Timeline and New Tab

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#820]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279261
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.
- Have a video embedded in the Timeline or New Tab page

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click the Activity Stream button from the browser toolbar.
3. Play the video from prerequisites in fullscreen and move the mouse to the right side of the screen.

[Expected result]:
The video is played in fullscreen.

[Actual result]:
The video is played in fullscreen, but the page URL is still displayed in the bottom left corner of the video.

[Notes]:
- Attached a screen recording of the issue https://goo.gl/1jZgYT .

**Comment by sarracini** [comment]
closing this since we've removed timeline
