### ISSUE TITLE
Update tippy-top-sites to the tippy-top-version

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#828]
Currently in [package.json](https://github.com/mozilla/activity-stream/blob/be02057fb6a415c5395bcabfd26e3df1ea2acdb5/package.json#L69), we specify **tippy-top-sites@0.1.0** (because that's the only version we've ever released on npm -- see https://github.com/nchapman/tippy-top-sites/issues/38).

We should publish a new version of **tippy-top-sites** then bump our package.json version so we get the  latest top sites (179 vs 97) and use the optimized images (756KB vs 1.6MB).

**Comment by sarracini** [comment]
Fixed with #923
