### ISSUE TITLE
Add support for video playback from more sites

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#830]
Currently we support https://youtube.com and https://vimeo.com (see #755), but we should probably make a checklist of other sites we want to support in the future.

There is a pretty good list over in the https://github.com/meandavejustice/min-vid/issues/6 repo, but we'll probably want to settle on our own shortlist. I believe they currently only support youtube.com and are currently working on [Vine integration](https://github.com/meandavejustice/min-vid/issues/47).

The min-vid gang are also working on custom player skin and some other stuff. Not sure if it's worth collaborating so we can steal all their hard work (or somehow use some embedded min-vid player).

**Comment by sarracini** [comment]
Closing this since we're no longer doing in-line videos
