### ISSUE TITLE
Bug 1279471 - Unable to remove items from History if the "Prevent this page from creating additional dialogs" checkbox was checked

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#832]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279471

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click the Activity Stream button from the browser toolbar.
3. Hover an item from the Highlights section.
4. Expand the Highlight context menu and click "Delete from History".
5. When the dialog appears click "Cancel" and repeat step 4.
6. When the dialog appears check the "Prevent this page from creating additional dialogs" checkbox and click "Cancel".
7. Repeat steps 3 and 4.

[Expected result]:
The "Prevent this page from creating additional dialogs" checkbox should not be displayed.

[Actual result]:
After the checkbox is checked you are no longer able to remove items from History because no dialogs are created.

[Notes]:
- The issue is also reproducible in the New Tab page.
- After a page refresh you are again able to remove items from History, because the checkbox resets itself.
- Attached a screen recording of the issue https://goo.gl/6T85rL.

**Comment by tspurway** [comment]
working on an alternative design
