### ISSUE TITLE
Bug 1279434 - "Delete from History" and "Dismiss" buttons from context menu are wrongly positioned

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#833]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279434
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19) was previously installed on a profile.
- Have two profiles: profile A has a Firefox account, profile B doesn't have a Firefox account.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile A from prerequisites.
2. Open a New Tab so the Activity Stream New Tab page is displayed.
3. Move the mouse cursor over a visited item.
4. Click on "..." button.
5. Observe the context menu.
6. Open the browser with the profile B from prerequisites.
7. Open a New Tab so the Activity Stream New Tab page is displayed.
8. Move the mouse cursor over a visited item.
9. Click on "..." button.
10. Observe the context menu.

[Expected result]:
- "Delete from History" and "Dismiss" buttons are displayed under the second separator line.

[Actual result]:
- For the profile with the Firefox account, "Delete from History" and "Dismiss" buttons are displayed above the second separator line.
![different context menus](https://cloud.githubusercontent.com/assets/17258026/15963860/cfcebb62-2f1d-11e6-98df-a962a0417f37.jpg)

**Comment by SoftVision-VladBacia** [comment]
This issue has been tested on latest Firefox release v47.0 and latest Nightly 50.0a1 (Build ID: 20160616163918 ) using Activity Stream v1.1.0 and it is no longer reproducible.

**Comment by anilatluri** [comment]
**no longer reproducible.**...so what does it mean to the end user like me?  Please remember I am not a techie!

**Comment by SoftVision-VladBacia** [comment]
@anilatluri , [my comment](https://github.com/mozilla/activity-stream/issues/833#issuecomment-226792983) means that the fix made for this issue has been tested and confirmed on the test environment with the latest Activity Stream version. This issue could not be reproduced after the fix was applied.

Please do not hesitate to contact me if I can be of further assistance.
