### ISSUE TITLE
ContextMenu should open relative to its position in the window (Bug 1279486)

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#835]
Right now the `ContextMenu` component is positioned via CSS and always opens to the bottom right. Ideally, when the menu is opened, we should be reading its position relative to the window and determine if it should appear above/below/right/left depending on where it is.

Here is an example where the menu should be opening to the bottom _left_, but it opens to the bottom right instead:

![contextmenu in wrong position](https://k88hudson-screenshots.s3.amazonaws.com/screen-shots/Screen_Shot_2016-07-19_at_6.47.03_PM.png)

_edited by @k88hudson for clarity_
_--------_
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279486

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.
- Scroll bar is available in Timeline History page.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click the Activity Stream button from the browser toolbar.
3. Hover the last website displayed in portview from Timeline History page.
4. Expand the item's context menu.

[Expected result]:
- The page is scrolled down automatically in order to see all the options of the context menu.

[Actual result]:
- After the context menu expands, only a few options are visible making the user to scroll down in order to see all the options available.
- In my opinion, the scroll action should be handled automatically.

[Notes]:
- The issue is also reproducible in the Bookmarks History page.
- After the context menu appears and the user has scrolled down to see the rest of the options, if the menu is dismissed, the page is automatically scrolled upwards.
- Attached a screen recording of the issue https://goo.gl/M0K4X1.

**Comment by k88hudson** [comment]
Right now the context menu does not have window position detection, it would be nice to add it.

**Comment by rlr** [comment]
Additionally, the new share submenu should open out to the side where there is more space. It currently always opens out to the left.

**Comment by turquoisemelon** [comment]
Hi there, 
I would like to work on this bug. I checked out the activity stream in the production stage and seems like the bug is still there. I forked and cloned activity stream on my own machine. I ran 'npm install' and 'npm run package' commands. The next step would probably be run the activity stream on the production mode, wouldn't it? 
Could anyone guide me on how can I continue from this step? 
Thank you.

**Comment by k88hudson** [comment]
Hey @turquoisemelon! After npm installing, Try opening two terminal windows, and in one terminal run `npm start` (which will continuously build assets), and in the other, `npm run firefox` (which will start a copy of Firefox). You'll need a copy of Firefox nightly installed by the way – you can get that here: https://www.mozilla.org/en-US/firefox/channel/desktop/

If that works, you should be able to make changes to the front end and see them updated on a refresh. Let me know if that works!

**Comment by turquoisemelon** [comment]
Hey @k88hudson ! It worked! I'm able to make changes to the front end and see them updated on a refresh. As for the next step, I'm trying to find the right file in the source code so that I can locate where I should be working on. As a first glance, ContextMenu.js seemed to me a good place to start. Please let me know what you think!
Thanks!

**Comment by jaredkerim** [comment]
This is a non critical bug for the test pilot addon that we will not be able to fix before we decomission it.  We can address this more effectively in the system addon, closing this as a won't fix for the test pilot version for now.
