### ISSUE TITLE
Bug 1279554 - The default "about:newtab" page can be opened instead of Activity Stream "New Tab" page at browser startup

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#837]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279554
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.19-dev

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.0.19-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. As soon as the browser window appears, open a "New Tab" page as fast as possible (spam click on new tab button could help too).
3. Observe the "New Tab" page content.

[Expected results]:
Opened "New Tab" page has the Activity Stream content displayed. 

[Actual results]:
Opened "New Tab" page has the default browser content displayed (old tiles).

[Notes]:
- This is a very edge case, the reproducibility rate depends on catching the right moment to open the new tab. Probably it occurs before AS add-on is initiated.
- Attached screen recording with the issue https://goo.gl/VORw10.

**Comment by rlr** [comment]
Yeah, this is because you beat the addon loading. I don't think there is much we can do here until we implement it for realz using the remote newtab infrastructure (or however we end up implementing it).

**Comment by oyiptong** [comment]
won't be able to fix it until we get into gecko
