### ISSUE TITLE
Add footer to new tab and timeline pages?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#840]
Here's what our footers look like currently:

![new_tab](https://cloud.githubusercontent.com/assets/557895/15979415/b3e0dc8c-2f18-11e6-8dd8-d11d13f4ba97.png)

---

![activity_stream](https://cloud.githubusercontent.com/assets/557895/15979421/bfd2f368-2f18-11e6-93fd-9ac05a2eace2.png)

---

Currently the page just "ends" and feels a little abrupt.

I think [Test Pilot](https://testpilot.firefox.com/) does a pretty solid job of giving outbound links to useful stuff:

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/15979476/0881d96c-2f19-11e6-94f1-b5135b66d841.png)

| Label | Link |
|:----|:----|
| Mozilla | https://www.mozilla.org/
| Legal | https://www.mozilla.org/about/legal/
| Privacy | https://testpilot.firefox.com/privacy
| Terms | https://testpilot.firefox.com/terms
| Cookies | https://www.mozilla.org/privacy/websites/#cookies
| Contribute | https://www.mozilla.org/contribute/signup/

Not sure if we want to add some footer-like stuff to our templates. Not sure what to put for Privacy or Terms since I'm not sure if we have specific legal docs for this repo. I don't see them in the root directory, or linked from https://testpilot.firefox.com/experiments/activity-stream. And maybe it's weird if we linked directly to the Test Pilot Privacy Notice and Test Pilot Terms of Use docs. But it may be nice to have a Contribute link which points to our GitHub repo so people can file issues or submit PRs or whatever.

**Comment by pdehaan** [comment]
Not sure if this still is valid since we're using infinite scrolling (which doesn't always play nice with footer navigation).

**Comment by sarracini** [comment]
Feature requests should be added to the trello board
