### ISSUE TITLE
Bug 1279918 - Writing a 110+ string in the New Tab Search bar, breaks the Search Suggestion dropdown UI

### ISSUE THREAD

**Issue by SoftVision-VladBacia** [mozilla/activity-stream#844]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279918
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a New Tab and write a 110+ string in the Search bar.
3. Observe the Search Suggestion UI.

[Expected result]:
- The long string is correctly truncated to fit the Search Suggestion dropdown.

[Actual result]:
- The long string does not respect the Search Suggestion dropdown boundaries.

[Notes]:
- [Here](https://bugzilla.mozilla.org/attachment.cgi?id=8762540), is a screen recording of the issue.

**Comment by sarracini** [comment]
Fixed with #850

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 10 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160620030215) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
