### ISSUE TITLE
Bug 1279927 - Normal Select cursor changes to Text Select cursor for Search Suggestion strings

### ISSUE THREAD

**Issue by SoftVision-VladBacia** [mozilla/activity-stream#846]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1279927
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a New Tab and write a keyword in the Search bar.
3. Hover a few of the suggested keywords.

[Expected result]:
- Normal Select cursor is kept while hovering suggested keywords.

[Actual result]:
- The mouse pointer switches from "Normal Select" to "Text Select".

[Notes]:
- [Here](https://bugzilla.mozilla.org/attachment.cgi?id=8762555), is a screen recording of the issue.

**Comment by sarracini** [comment]
Fixed with #865

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 10 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160620030215) using latest Activity Stream v1.1.0-custom build and it is partially reproducible. 
If the "Google Search" and "Search for...with" elements from the Search Suggestion dropdown are hovered, the mouse cursor changes to Text Select cursor. This behavior can be observed [here](https://bugzilla.mozilla.org/attachment.cgi?id=8763902). 

Also, while testing, we observed that the written string from the New Tab Search Box is displayed with a gray color instead of black in the "Search for...with" element.
![search string color](https://cloud.githubusercontent.com/assets/9248513/16232110/f7a0e612-37d1-11e6-83c9-3aade046afa4.jpg)


Thus, marking this issue as Reopened.

**Comment by sarracini** [comment]
Fixed with #869 
can you confirm @SoftVision-VladBacia?

**Comment by SoftVision-VladBacia** [comment]
@sarracini , the search string displayed in "Search for...with" element should have a black color and without bold formatting. The Search Suggestion UI from New Tab should be consistent with the one implemented in the browser.

**Comment by sarracini** [comment]
Its consistent with the implementation found in the search drop down in about:newtab

**Comment by SoftVision-VladBacia** [comment]
Yes, you are right. From our point of view this issue can be closed.

This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 15.10 x64 with latest Nightly 50.0a1 (Build ID: 20160621030208) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
