### ISSUE TITLE
Refactor PreviewProvider to request specific metadata fields

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#853]
In its current form, requesting getEnhancedLinks for a list of URLs will return all metadata that it can from embedly, however in the future we will want to specify exactly which metadata fields we need for a particular use case, ie colour, icons, titles, desriptions, highlight images, etc so that we can 1) make it clearer which specific fields the caller expects and 2) prevent doing preprocessing work or making database queries for fields which are not required.  This will become increasingly important as we move more and more processing into the addon, so we should provide this interface early so that we don't need to change the interface in the future.

**Comment by pdehaan** [comment]
Is this related to #176?

**Comment by sarracini** [comment]
Kind of, it's also related to #187. Embedly does return a lot of stuff that we don't necessarily need, but the idea behind this ticket is to provide a good foundation for when the Embedly gets replaced by the addon processing.

**Comment by sarracini** [comment]
There are actually a bunch of embedly related tickets open that we should triage, since the metadata extractor for the addon will be underway very soon

**Comment by jaredkerim** [comment]
@sarracini 👍

**Comment by jaredkerim** [comment]
Inside preview provider, there should be a mapping of individual metadata fields to how that data is accessed so that if someone requests ['favicon_url', 'favicon_color'] and this triggers local metadata processing that additional work that is not necessary to satisfy just those two fields is not performed.

    {
        favicon_color: link => this.getFaviconColor(link),
        favicon_url: link => this.getFaviconURL(link),
        ....
    }

**Comment by jaredkerim** [comment]
This was done.
