### ISSUE TITLE
Bug 1280019 - The dots from "..." context menu button are not centred

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#854]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1280019
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a New Tab and hover any website displayed.
3. Observe the dots from "..." button.

[Expected result]:
- The dots from "..." button are positioned in the centre of the button.

[Actual result]:
- The dots from "..." button are positioned slightly to the left side of the button.

[Notes]:
- The issue is reproducible on "Highlights" and "Top Sites" tiles and also on items from Recent Activity.
- The issue is also reproducible on the Timeline History page.
- Attached two screenshots of the issue.
![more button not centered](https://cloud.githubusercontent.com/assets/17258026/16047585/8d1bdb5a-3248-11e6-9d11-b398e2d866c1.png)

**Comment by sarracini** [comment]
should be fixed with #869 
can you confirm @SoftVision-PaulOiegas ?

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 10 x64, Mac OS X 10.11 and Ubuntu 15.10 x64 with latest Nightly 50.0a1 (Build ID: 20160622030210) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
