### ISSUE TITLE
Bug 1280020 - Search Suggestions dropdown displays all the searched keywords for a second when searching for a new keyword

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#855]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1280020

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.
- Search for at least 25 keywords using the Search from New Tab page.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open a New Tab and type a letter in the Search bar.
3. Delete the previous letter, write a new one and observe the Search Suggestion dropdown.

[Expected result]:
- The Search Suggestions dropdown is displayed and keywords related to the typed letter appear.

[Actual result]:
- The Search Suggestion dropdown is displayed, but for a second the dropdown displays all the searched keywords.

[Notes]:
- Attached a screen recording of the issue https://goo.gl/1TjQI6 .

**Comment by Mardak** [comment]
I would think this is fixed by https://github.com/mozilla/activity-stream/pull/2611 in the version available in Nightly (tonight/tomorrow). And if it's still happening in Test Pilot version, development there has been wrapped up.
