### ISSUE TITLE
Bug 1280430 - Websites that are accessed from a pinned New Tab, are opened in another tab

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#857]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1280430

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Open Activity Stream New Tab and pin it.
3. Click on a website from Top Sites/Highlights/Recent Activity.

[Expected result]:
- The website is opened in the current(pinned) tab.

[Actual result]:
- The website is opened in another tab.

[Notes]:
- On Firefox builds, without the Activity Stream add-on installed, websites visited from a pinned `about:newtab` page are opened in the same tab.
- The issue is also reproducible on the Timeline History page, if you pin the tab.
- If a page URL is written in the address bar and accessed, the website is opened in the pinned(current) tab.
- Attached a screen recording of the issue https://goo.gl/9IMXxE.

**Comment by tspurway** [comment]
intended
