### ISSUE TITLE
Opening a new tab opens the "Nightly Start Page", opening a new window opens the activity stream's "New Tab" page

### ISSUE THREAD

**Issue by marco-c** [mozilla/activity-stream#860]
Since today, the behavior is exactly the opposite of what it should be.

**Comment by rlr** [comment]
We are also "hijacking" the home page in the case that the user doesn't have a custom home page set, so that behavior is correct. However, new tab should never open the "Nightly Start Page". I'll try to repro.

**Comment by marco-c** [comment]
I can't reproduce anymore. I don't know if it's an intermittent issue or if it was fixed.

**Comment by rlr** [comment]
Yeah, I can't repro. Closing. Please reopen if you ever see it happen again. Thanks!
