### ISSUE TITLE
some keystrokes end up missing when I type in the search box

### ISSUE THREAD

**Issue by wlusink** [mozilla/activity-stream#862]
So when I type slowly in the search box, all is well.
However, when I type faster, some keystrokes are missing. I'm pretty sure this has to do with the search suggestions. Apparently the search suggestions change the text I'm typing, as I'm typing.

This only happens to me in the 'New Tab screen' that is presented to me by the Activity Stream 1.1.0 add-on.
I have no other add-ons active in FireFox.

I run windows 8.1 and firefox 47.0

If other info is needed, please ask.

**Comment by ncloudioj** [comment]
Thanks for reporting this!
dup #848

**Comment by wlusink** [comment]
ayyy sorry!

I did do a search but didn't find anything.

ahum.. must have been because my search box didn't work correctly hehehe 
;-)

thanks!

Nan Jiang schreef op 2016-06-20 09:24:
