### ISSUE TITLE
Implement recommendation highlight

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#870]
This ticket should replace one of the tiles in the Highlights section with a "recommended" tile, if possible.

We should be able to use the new pocket recommendation engine to do this.

*[Edit by @k88hudson for clarity]*

spec:
https://trello.com/c/TQcZZhMe

**Comment by k88hudson** [comment]
We still need to work out:
- [ ] What should be the source of the recommendation? Should it be related to an existing tile that is also shown? Should it *replace* the tile it is related to? Should it be a general "trending" recommendation?
- [ ] What if a recommendation is not available from the designated source? Should we replace it with a general recommendation? Should we just not show it?
- [ ] How frequently should recommendations be shown? All the time when we have one? Only sometimes?

Also note: we should try running this as an experiment.

cc @bryanbell @aaronrbenson

**Comment by k88hudson** [comment]
If you want, I can try something like replacing one of the tiles with its recommendation, and we can see how that goes.

**Comment by k88hudson** [comment]
Note: this is also blocked on implementing pocket endpoints in the proxy

**Comment by aaronrbenson** [comment]
![new tab - recommended content spec](https://cloud.githubusercontent.com/assets/139451/16470763/b7f6fcfc-3e1d-11e6-839e-57353089eddb.png)

**Comment by k88hudson** [comment]
@tspurway I wasnt able to make the meeting on Thursday, did you end up asking about the short URLs?

**Comment by k88hudson** [comment]
Also thanks for the clarification @aaronrbenson! Looks great

**Comment by sarracini** [comment]
Fixed with #906
