### ISSUE TITLE
Activity Stream Executive Summary

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#874]
As per discussion with @nchapman, @tspurway, @edmoz we would like a re:dash dashboard with the following graphs:

* Weekly cohorts
* MAU/WAU/DAU
* Daily active users
* Engagement ratio (DAU/MAU)
* Session durations
* Awesomebar users vs. activity stream users cohort retention

**Comment by emtwo** [comment]
Work in progress for this dashboard can be found here:
https://sql.telemetry.mozilla.org/dashboard/activity-stream-executive-summary

**Comment by edmoz** [comment]
I'd like to see an value that tells us that users find activity stream useful or has value for them.  From discussion, something like a avg/mean interactions per user (min 1 interaction) over time.

**Comment by emtwo** [comment]
@edmoz @nchapman @tspurway the executive dashboard now has all the charts we previously discussed.

Please feel free to comment and let me know what changes/additions/tweaks you'd like to see.

For now I just have a couple of comments to make:

1) The session durations chart is just a distribution of durations. Was there anything different you wanted to see?

2) The new retention charts basically separate the retention of "very active" and "inactive" users. The results in the graphs are quite dramatic I'd say! I did try some retention charts with users who usually navigated away via awesomebar instead of interacting vs. those who usually interact (they're saved on re:dash now but not in the exec dashboard). I found that the results here were not as dramatic, likely because navigating away often does not necessarily correlate with a general lack of inactivity.

**Comment by nchapman** [comment]
@emtwo this looks great! I would love to see 2 more charts:

1. Average weekly interactions (per user) as a cohort analysis chart to answer the question: Do a cohort of users interact more (or less) with activity stream over time?

2. Distribution of usage on new tab that includes search, top sites, highlights, and recent activity as a stacked bar chart by week. I'm imagining every bar would add up to 100%. Let me know if you can think of a better way to visualize this.

**Comment by emtwo** [comment]
Remaining items for this:

1. Finish doing annotations for all the charts
2. Add a chart with week-by-week navigation vs. other interactions

**Comment by emtwo** [comment]
All remaining items have been taken care of. Going to close this issue. Please file a new one if you would like changes/additions to the Exec Dash.
