### ISSUE TITLE
Videos in the timeline that are not connected to previous history should not have a timeline strand

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#880]
![screen shot 2016-06-23 at 5 37 05 pm](https://cloud.githubusercontent.com/assets/139451/16322472/d3f16a14-3968-11e6-8294-d4c18701c022.png)

Pretty descriptive title. The image should make it crystal clear.

**Comment by SoftVision-VladBacia** [comment]
@aaronrbenson , this issue is related to #834.

**Comment by oyiptong** [comment]
closing as duplicate of #834
