### ISSUE TITLE
Context menu dots are not center aligned with their container

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#881]
![context_menu](https://cloud.githubusercontent.com/assets/139451/16323500/dedd7b7c-3970-11e6-9e0b-144d7aea97aa.png)

Cannot be unseen.

**Comment by nchapman** [comment]
![tumblr_inline_nn1gu3ahi61t09k6m_540](https://cloud.githubusercontent.com/assets/3095/16323592/c7740c54-3960-11e6-82cd-7ae4fdbd5def.gif)

**Comment by SoftVision-VladBacia** [comment]
@aaronrbenson , thank you very much for reporting this issue to us.

This issue is similar with #854 . A fix has been made and it will be available in the next release.
