### ISSUE TITLE
Bug 1282053 - Activity Stream resource is not removed from "about:preferences->Home Page" field after uninstalling the add-on

### ISSUE THREAD

**Issue by SoftVision-VladBacia** [mozilla/activity-stream#882]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1282053
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Go to `about:preferences` and observe the Home Page resource.
3. Open `about:addons` in a new tab and click on "Remove" button.
4. Go back to `about:preferences` and observe the Home Page resource.

[Expected result]:
- Default `Mozilla Firefox Start Page` is set as Home Page.

[Actual result]:
- `resource://activity-streams/data/content/activity-streams.html#/` is set as Home Page.

[Notes]:
- When Activity Stream add-on is disabled, the resource from Home Page is removed and Default Mozilla Firefox Start Page is set as Home Page.
- Related to #724 .
- [Here](https://bug1282053.bmoattachments.org/attachment.cgi?id=8764888) is a screen recording of the issue.

**Comment by rlr** [comment]
ugh. I thought disable was called before uninstalling. I might have to revert that commit if there is no way to tell when user is uninstalling.

**Comment by oyiptong** [comment]
interesting. I thought so too. We should find out what is the unload reason when the user is uninstalling.

**Comment by SoftVision-VladBacia** [comment]
This issue has been verified on Win 8.1 x64, Mac OS X 10.11 and Ubuntu 14.04 x64 with latest Nightly 50.0a1 (Build ID: 20160626030213) using latest Activity Stream v1.1.0-custom build and could not reproduce it.
Thus, marking this issue as Verified-Fixed.
