### ISSUE TITLE
Bug 1282780 - Embedded video player is missing for movies/trailers played from www.vimeo.com/ondemand/

### ISSUE THREAD

**Issue by Softvision-VladBacia** [mozilla/activity-stream#888]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1282780
<hr>
Affected versions]:
- Firefox 45.0 and up
- Activity Stream v1.1.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on (v1.1.0-dev) was previously installed on a profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Go to https://vimeo.com/ondemand.
3. Click on one of the movie posters displayed on the page (do not click on "Watch Trailer" button).
4. After the detailed view of the selected movie is displayed click on "Watch Trailer" button.
5. Click the Activity Stream button from the browser toolbar.
6. refresh Timeline History page.

[Expected result]:
- The embedded video player is displayed in Activity Stream Timeline History page and the trailer can be played inside Activity Stream.

[Actual result]:
- The embedded video player is not displayed in Activity Stream Timeline History page, only the URL and movie title are displayed in AS.

[Notes]:
- [Here](https://bugzilla.mozilla.org/attachment.cgi?id=8765916) is a screen recording of the issue.

**Comment by sarracini** [comment]
Closing this since we're timeline is gone and we are no longer developing for recent activity
