### ISSUE TITLE
Implement Share Toolbar button

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#892]
feature card: https://trello.com/c/uRoUOISr

**Comment by pdehaan** [comment]
This feels weird to me.
Why is this an Activity-Stream thing and not a separate Test Pilot experiment add-on that we validate separately? If I opt out of Activity Stream, I can no longer share anything?

And as a user, installing the Activity Stream add-on and now having TWO new toolbar icons appearing would be pretty confusing.

**Comment by rlr** [comment]
Quick update: the toolbar is implemented (minus "send to device") in https://github.com/mixedpuppy/sharemenu. Now working on porting the code over to Activity Stream. Then there is some polish and some messing with preferences so our users have a default set of social sites enabled to share to out of the box.

**Comment by rlr** [comment]
@edmoz @nchapman,

I'm going to enable this default set of providers for users that haven't ever enabled any before. Are these good? Should any others be added? The full list of providers is here: https://activations.cdn.mozilla.net/en-US/

<img width="249" alt="screen shot 2016-08-10 at 12 30 51 pm" src="https://cloud.githubusercontent.com/assets/36629/17561962/7da2fe4e-5ef6-11e6-8454-21296dd0f9fc.png">

**Comment by edmoz** [comment]
Not sure why yahoo mail would be in the list.  The others are social feeds, but mail seems the same as 'email link'. Otherwise it looks like a good list to me, it matches what i see on my Android Fx Share button.

**Comment by edmoz** [comment]
The mocks have yahoo mail - so we should include it.  Rlr also mentioned the order of display is based on frencency (though i'm on a new profile).  

'Email Link...' launched the default mail and if it's gmail in chrome, it focuses the browser but doesn't launch a new window with gmail in it.

**Comment by nchapman** [comment]
> Are these good? Should any others be added?

I'd like to see the list be the following:

- Facebook
- Twitter
- Tumblr
- LinkedIn
- Yahoo Mail
- Gmail

This is based somewhat on the numbers that Shane shared previously:

> For activations of share providers [in order], facebook 50%, yahoo email 20%, G+ 9%, GMail 5%, odnoklassniki + vkontakte come up to 8%, twitter 3%.  all others <1%

But I've also grouped them by type. Can we make sure that we instrument which ones are being clicked on?

**Comment by bryanbell** [comment]
Icons needed 

[_final Activity Stream icons.zip](https://github.com/mozilla/activity-stream/files/412329/_final.Activity.Stream.icons.zip)
