### ISSUE TITLE
Bug 1283398 - Two items will be highlighted in the search suggestion dropdown when navigating with the arrow keys if another item is hovered with the mouse cursor

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#894]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1283398

<hr>

[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0

[Affected Platforms]:
- All Windows
- All Linux
- All Mac OS

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0) was previously installed on a profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Open a New Tab so the Activity Stream New Tab page is displayed.
3. Enter a keyword in the Search text box.
4. Hover a suggestion keyword with the mouse cursor.
5. Navigate through the search suggestion dropdown with "down arrow" or "up arrow" from keyboard.

[Expected result]:
- Only one item from the suggestion dropdown is highlighted.

[Actual result]:
- Two items from suggestion dropdown are highlighted (one will be highlighted from keyboard and one from mouse cursor).

[Notes]:
- In 'about:newtab' page when "down arrow" or "up arrow" buttons are pressed, only the last selected item is highlighted.
- A screenshot describing the issue was attached.
  ![two items highlighted](https://cloud.githubusercontent.com/assets/17258026/16482293/cc0ce61c-3eb7-11e6-9687-7ad46612cc06.png)

**Comment by sarracini** [comment]
Closing this as we are using the same search bar as about:newtab and about:home, and will adopt the same behaviour as them
