### ISSUE TITLE
I used the Forget Button and Activity Stream was removed

### ISSUE THREAD

**Issue by fabiorios** [mozilla/activity-stream#897]
I'm on Windows 10, Firefox 47.0.1

After using the forget button, activity stream was removed, but my universal search remained.

**Comment by tspurway** [comment]
Thanks for reporting this, @fabiorios !  This sounds like a test pilot issue - @edmoz  can you file this where it belongs?

**Comment by jaredkerim** [comment]
I'm going to close this for now.  If it recurs we can reopen or refile.
