### ISSUE TITLE
Missing event pings

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#898]
I found this while creating cohort charts. Some users have session pings with unload reason as `click` but there is no associated `click` event ping in the `activity_stream_events_daily`.

For example, we can see this with user `6bfc0841-a937-2b42-a099-f0d568f25b89` using the following two queries:

```
SELECT tab_id, unload_reason, receive_at, date, session_id
FROM activity_stream_stats_daily
WHERE client_id = '6bfc0841-a937-2b42-a099-f0d568f25b89'
AND unload_reason = 'click'
ORDER BY date
```

```
SELECT tab_id, event, receive_at, date, session_id
FROM activity_stream_events_daily
WHERE client_id = '6bfc0841-a937-2b42-a099-f0d568f25b89'
ORDER BY date
```

In the first query there is a session ping with tab ID `-3-19` dated 29/06/16. However in the second query there is no associated click event ping.

**Comment by jaredkerim** [comment]
Closing this for now and if we see it again we will reopen it.
