### ISSUE TITLE
Discuss letting users explore highlights

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/activity-stream#900]
Worth considering? 

So that I can engage more deeply with my own browsing history, as an new tab page user, I want to be able to view more highlights.

YouTube UI example:
![scroll](https://cloud.githubusercontent.com/assets/68213/16689451/07b74cd6-44f1-11e6-9902-d4bafe2b3b3d.gif)

**Comment by aaronrbenson** [comment]
@ryanfeeley yes, great suggestion. We'll move this into the backlog on Trello as a feature request. Follow along here: https://trello.com/c/9ygAg0AB/60-i-want-to-see-more-highlight-content-on-new-tab-so-that-i-can-discover-more-interesting-places-on-the-web
