### ISSUE TITLE
highlight delete from history or dismiss doesn't delete

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#910]
I'm on dev build of addon
1. on new tab, hover over highlight item
2. select delete from history or dismiss
3. open a new tab

actual: deleted/dismissed item displays in highlight
expected: it shouldn't

**Comment by edmoz** [comment]
@pdehaan can you repro this?

**Comment by pdehaan** [comment]
I can reproduce w/ "Activity Stream Dev 1.1.0-dev-1468450495".
I have a "PageShot" URL in my highlights which I delete, as well as a few FxA login links.
If I delete PageShot and dismiss the FxA links, then open a new tab (or hit refresh), then the results come back on the next page load.

Actually, I'm a bit confused about the results not deleting. It's a bit unclear as to if they're not deleting, or I just have 20 results which are all just generic API pings to PageShot which are being returned and I'm just deleting them one at a time.

**Comment by k88hudson** [comment]
Weird. I'm unable to reproduce this.

**Comment by k88hudson** [comment]
Ok, I was able to nail this down. No further STR needed!

**Comment by k88hudson** [comment]
This should now be fixed as of the latest commit

**Comment by k88hudson** [comment]
Waiting on confirmation from #858

**Comment by k88hudson** [comment]
This is done
