### ISSUE TITLE
Developer shim mode is broken

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#926]
Last week @dmose reported that running stuff in shim mode (i.e. `SHIM=true`) is currently broken for some reason

**Comment by dmose** [comment]
I have a fix for this in the React Story PR.

**Comment by dmose** [comment]
(which is only on my fork at this moment, but will show up in the mozilla fork soon).

**Comment by k88hudson** [comment]
Ok, thanks!
