### ISSUE TITLE
Bug 1288061 - The status of a bookmarked item from Highlights is not change after it was removed from bookmarks

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#927]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1288061
<hr>
[Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.1.0-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on version (1.1.0-dev) was previously installed on a clean profile.
- Have enough history so that the "Top Sites", "Highlights", "History" areas are populated with visited websites.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click the Activity Stream button from the browser toolbar.
3. Click on "..." context menu button from an item that is displayed in Timeline History area. 
4. Click on "Bookmark" button for the selected item.
5. Refresh the page. (the bookmarked item should be displayed in Highlights area)
6. From Highlights area, click on "..." context menu button for the recently bookmarked item.
7. Click on "Remove Bookmark" button for the selected item.

[Expected result]:
The status changes from "Bookmarked X second/minutes/hours ago" to "Visited X second/minutes/hours ago".

[Actual result]:
The status doesn't change, but the website is removed from bookmarks.

[Notes]:
- Attached a screen recording of the issue https://goo.gl/8snkNx.

**Comment by k88hudson** [comment]
This was fixed by https://github.com/mozilla/activity-stream/pull/1285/commits/4dd365246ebea67779baddad695ed513d164da3e. Thanks @devmasao!
