### ISSUE TITLE
Some favicons appear as blank-ish 1x1 pixels

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#944]
Found in **Activity Stream Dev** (1.1.0-dev-1460133119)

---

### Steps to reproduce:
1. Install latest activity-stream add-on.
2. Browse to http://nurturedbynature.org/group-n.html
3. Swim with otters.
4. Go go New Tab or Timeline feed.

### Actual results:
With some luck, you may have "Swim with an Otter by Nurtured by Nature" in your Highlights feed, and it'll look something like this:

![activity_stream](https://cloud.githubusercontent.com/assets/557895/17039413/44d39fda-4f4f-11e6-8eee-b9cbfac3665a.png)

### Expected results:
Not sure if we can detect unusually small dimensions on a favicon and just fall back to a random color and first letter of hostname or whatever. Having a blank looking icon here looks decidedly broken or like I'm still waiting on assets to load.

**Comment by jaredkerim** [comment]
Investigation required to determine whether this is happening locally or caused by the data.

**Comment by jaredkerim** [comment]
The favicon for that page exists and is a 1x1 pixel white icon, so I guess in this case we could add a code exception as you suggest @pdehaan.

**Comment by Mardak** [comment]
Before: 
![screen shot 2016-07-28 at 1 52 16 am](https://cloud.githubusercontent.com/assets/438537/17206795/539303c8-5466-11e6-83e1-826cd5072b07.png)

After: 
![screen shot 2016-07-28 at 1 54 10 am](https://cloud.githubusercontent.com/assets/438537/17206800/57c45190-5466-11e6-810a-76f5061754b7.png)
