### ISSUE TITLE
Sort cache key query parameters to improve the chance of cache hits

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-stream#945]
After normalizing a URL, we might also want to canonicalize, then make a cache key.

We can obtain a canonical URL from the page. If we don't have that (which we won't right now), we should still take steps to ensure URLS are the same, and that means:
1. potentially dropping URL fragments (or not, depending on how many dynamic pages there are)
2. sorting query parameters

**Comment by sarracini** [comment]
Closing this since there's no more cache
