### ISSUE TITLE
Search Box A/B Test

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#946]
It would be nice to test if we can increase interaction rates with Activity Stream if we default the cursor to the search box when users open a new tab.

**Comment by jaredkerim** [comment]
Closing this for now pending any further feedback from design.

**Comment by edmoz** [comment]
changing the browsers primary workflow is a bit scary. We could try it but may anger that cohort.

**Comment by emtwo** [comment]
It's an A/B test which is really where we get to be brave, try out these things, and see what happens.

**Comment by edmoz** [comment]
Agreed - we should re-open when we get curious about what things we can do that would lead users to bounce or uninstall activity stream.
