### ISSUE TITLE
youtube icon isn't displaying in top sites

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#951]
1. i'm doing a npm run once with fx47 as my fxBeta.
2. open new tab 

actual:
<img width="775" alt="screen shot 2016-07-22 at 11 31 45 am" src="https://cloud.githubusercontent.com/assets/3698618/17067428/85e5aade-5000-11e6-827d-2125b971065d.png">

expected: icon!

**Comment by ncloudioj** [comment]
Same here.

**Comment by sarracini** [comment]
problem with tippytop maybe?

**Comment by pdehaan** [comment]
Yeah, is weird, because it was definitely missing for me before, but then sometimes appears:
![new_tab](https://cloud.githubusercontent.com/assets/557895/17069909/0e5c59fa-500e-11e6-9c20-a732bb14b585.png)

**Comment by rlr** [comment]
But I may have just uncovered a bug there. Note that it shows youtube because I visited it, but it shows it again as part of the canned default sites.

**Comment by edmoz** [comment]
note mine is a fresh install... you might try npm run once

**Comment by pdehaan** [comment]
:+1:  I can repro on a fresh profile as well.

In fact, here's what it looks like in my Dev Tools:

![fullscreen_8_22_16__1_54_pm](https://cloud.githubusercontent.com/assets/557895/17871365/0c97d7e6-6870-11e6-9060-0c1a53c43bc6.png)

And here's the Tippy-Top youtube-com.png icon, courtesy of Preview.app:

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/17871449/73929896-6870-11e6-97a8-c953cffd9cbe.png)

Actually... Digging deeper, this looks interesting (disclaimer: not really):

```json
  {
    "title": "YouTube",
    "url": "https://www.youtube.com/",
    "image_url": "youtube-com.png",
    "background_color": "#db4338",
    "domain": "youtube.com"
  },
```
&mdash; via [**nchapman/tippy-top-sites** ./top_sites.json:1199-1205](https://github.com/nchapman/tippy-top-sites/blob/799bacd41ca62cc10ad783c56e85e48d25879a75/top_sites.json#L1199-L1205)

Note that the `background_color` should be `#db4338` for youtube.com, yet if you look at the tiny screenshot above, it is `rgb(255, 255, 255)` (aka: "white"). Not sure why, but I point my QA-finger-of-blame squarely at this:

```json
    {
      "title": "YouTube",
      "url": "https://www.youtube.com/",
      "favicon_url": "youtube-com.png",
      "background_color": "#fff"
    },
```
&mdash; via [./content-src/lib/first-run-data.js:14-19](https://github.com/mozilla/activity-stream/blob/49b724bb5b47481abea96dc1a44948fd3301f3ad/content-src/lib/first-run-data.js#L14-L19)

**Comment by pdehaan** [comment]
... I just realized that a PR would have taken me about 700 fewer keystrokes. Stand by.

**Comment by pdehaan** [comment]
I also verified all the other top-sites' colors matched those specified in tippy-top, and the rest did.
Not sure if duplicating the data in tippy-top sites and content-src/lib/first-run-data.js is the best approach since we could easily break things in the future, but probably a bit cleaner than specifying first-run-data.js' `TopSites: []` as:

```js
TopSites: ["Facebook", "YouTube", "Amazon", "Yahoo", "eBay", "Twitter"]
```

... then trying to do an `Array#reduce()` against the **tippy-top-sites** module's `/top_sites.json` file to get the pre-calculated `background_colors`, `title`,`url`, and `favicon_url`. 

---

Not pretty, but it works... Basically we'd only set `TopSites` to an array of domains that we want to use, then the actual data is extracted from the **tippy-top-sites** module:

```js
const tippyTop = require('tippy-top-sites');

const FAVICON_PATH = "favicons/images/";
const FIRST_RUN_TYPE = "first-run";

let TopSites = ["Facebook", "YouTube", "Amazon", "Yahoo", "eBay", "Twitter"];

const sites = tippyTop.reduce((prev, curr) => {
  if (TopSites.indexOf(curr.title) !== -1) {
    prev.set(curr.title, curr);
  }
  return prev;
}, new Map());

TopSites = TopSites
  .map(site => sites.get(site))
  .map(item => {
    item.type = FIRST_RUN_TYPE;
    item.favicon_url = FAVICON_PATH + item.image_url;
    return item;
  });

console.log(TopSites);

/*
[ { title: 'Facebook',
    url: 'https://www.facebook.com/',
    image_url: 'facebook-com.png',
    background_color: '#edf0f5',
    domain: 'facebook.com',
    background_color_rgb: [ 237, 240, 245 ],
    type: 'first-run',
    favicon_url: 'favicons/images/facebook-com.png' },
  { title: 'YouTube',
    url: 'https://www.youtube.com/',
    image_url: 'youtube-com.png',
    background_color: '#db4338',
    domain: 'youtube.com',
    background_color_rgb: [ 219, 67, 56 ],
    type: 'first-run',
    favicon_url: 'favicons/images/youtube-com.png' },
  { title: 'Amazon',
    url: 'http://www.amazon.com/',
    image_url: 'amazon-com.png',
    background_color: '#FFF',
    domain: 'amazon.com',
    background_color_rgb: [ 255, 255, 255 ],
    type: 'first-run',
    favicon_url: 'favicons/images/amazon-com.png' },
  { title: 'Yahoo',
    url: 'https://www.yahoo.com/',
    image_url: 'yahoo-com.png',
    background_color: '#5009a7',
    domain: 'yahoo.com',
    background_color_rgb: [ 80, 9, 167 ],
    type: 'first-run',
    favicon_url: 'favicons/images/yahoo-com.png' },
  { title: 'eBay',
    url: 'http://www.ebay.com',
    image_url: 'ebay-com.png',
    background_color: '#ededed',
    domain: 'ebay.com',
    background_color_rgb: [ 237, 237, 237 ],
    type: 'first-run',
    favicon_url: 'favicons/images/ebay-com.png' },
  { title: 'Twitter',
    url: 'https://twitter.com/',
    image_url: 'twitter-com.png',
    background_color: '#049ff5',
    domain: 'twitter.com',
    background_color_rgb: [ 4, 159, 245 ],
    type: 'first-run',
    favicon_url: 'favicons/images/twitter-com.png' } ]
 */
```

**Comment by pdehaan** [comment]
Current status:

![new_tab](https://cloud.githubusercontent.com/assets/557895/17876086/3846889e-688c-11e6-925f-abf621184da6.png)
