### ISSUE TITLE
A few browser console errors when running locally

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#952]
Current SHA a263977e6742baf18cb3d095b591943445440720

![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/17067472/b26193b6-5000-11e6-9d7a-26fed36dc2b3.png)

---

After running `$ npm run package` and generating an XPI (and then adding it to my Firefox Nightly), I'm stuck at this spinner.

![new_tab](https://cloud.githubusercontent.com/assets/557895/17067367/45b1edec-5000-11e6-8126-1a2b050e81ed.png)

Looking at my Browser Console, I'm seeing the following errors:

![browser_console](https://cloud.githubusercontent.com/assets/557895/17067314/10f48f88-5000-11e6-8778-712a298fc05a.png)

> 1. "TypeError: this._tabTracker is undefined"
> 2. "TypeError: this._experimentProvider is undefined: _respondToExperimentsRequest@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:284:5"
> 3. "TypeError: this._tabTracker is undefined: _onRouteChange@resource://gre/modules/commonjs/toolkit/loader.js -> resource://activity-streams/lib/ActivityStreams.js:332:7"

---

And my experiments.json looks like:

``` json
{
  "sample": {
    "name": "Sample Experiment",
    "active": false,
    "description": "This is just a sample experiment. It will not be included since active is false",
    "control": {
      "value": "#000",
      "description": "This is black"
    },
    "variant": {
      "id": "do-not-delete-this-is-a-sample",
      "value": "#FFF",
      "threshold": 0.5,
      "description": "This is white"
    }
  },
  "reverseMenuOptions": {
    "name": "Delete order",
    "description": "Tests whether or not the order of block and delete impact how often people use them",
    "control": {
      "value": false,
      "description": "Delete is first, block is second"
    },
    "variant": {
      "id": "exp-001-delete-menu",
      "value": true,
      "threshold": 0.5,
      "description": "Block is first, delete is second"
    }
  },
  "recommendedHighlight": {
    "name": "Recommended Highlights",
    "description": "Show a recommendation from Pocket to the user",
    "control": {
      "value": false,
      "description": "Do not show a recommendation"
    },
    "variant": {
      "id": "exp-002-recommended-highlights",
      "value": true,
      "threshold": 0.9,
      "description": "Show a recommendation in the third highlights spot"
    }
  }
}
```

**Comment by jaredkerim** [comment]
Can we verify this is reproducible?

**Comment by sarracini** [comment]
This is no longer an issue, closing this
