### ISSUE TITLE
 trending recommendation from 8 days ago doesn't feel fresh

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-stream#953]
1. enable recommendation experiment
2. look at recommended highlight

actual: it says: 'trending  8 days ago', this doesn't feel like it's trending.

expected: it should say 'trending' only unless it's 'treading 8 hours ago' or just hide date all the time.

**Comment by pdehaan** [comment]
I vote to hide the timestamp for trending things.

**Comment by edmoz** [comment]
dupe of #957
