### ISSUE TITLE
Trending results appear on different sides on NewTab vs Timeline

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#955]
![menubar_and_activity_stream](https://cloud.githubusercontent.com/assets/557895/17068824/0c146530-5008-11e6-8134-5214a64b98b8.png)
**Figure 1:** Timeline Trending on Left.

---

![menubar_and_new_tab](https://cloud.githubusercontent.com/assets/557895/17068841/1c8d1722-5008-11e6-9d29-4859ebd2f771.png)
**Figure 2:** New Tab Trending on Right.

**Comment by sarracini** [comment]
Closing this since we're removing timeline
