### ISSUE TITLE
Sometimes I get no Trending results if you clicked on a previous trending article

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#956]
### Steps to reproduce:
1. Launch Activity Stream in New Tab (and cross fingers you're in the Experiment Bucket).
1. Click on a trending article and open in a new tab.
1. Refresh the New Tab page.

### Actual results:
Note that the trending article now appears in your "Top Sites" section, but now you have no trending topics displayed if you refresh the New Tab page (I'm assuming because of deduping).
Note that my trending article was http://www.bakadesuyo.com/2016/07/workout-motivation/ which now appears in Top Sites.

![menubar_and_new_tab](https://cloud.githubusercontent.com/assets/557895/17068955/c2fb176c-5008-11e6-82c0-974e5a277421.png)

### Expected results:
We should possibly pick a new Trending article and display that to the end user in the highlights section.

**Comment by sarracini** [comment]
oh wow.... i'll see what's going on here. good catch!

**Comment by sarracini** [comment]
so, opening with in a new tab doesn't register as a "click" event - so there's no indicator to activity stream that they clicked on it and now need a new recommendation...will look into a nice way to fix this
