### ISSUE TITLE
Tooltip for recommended content behaves strangely

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#958]
The tooltip for recommended/trending content shows up in the wrong spot (should appear below the trending label, seen here: https://trello.com/c/TQcZZhMe/19-i-want-to-have-popular-content-recommended-to-me-so-that-i-can-learn-about-new-things-happening-on-the-web) and the mouseover behavior appears off. See attached:

https://cl.ly/2N3k1i233y3L

**Comment by sarracini** [comment]
this happens when the metadata for that highlight hasn't come back yet and you opened a new tab too quickly. if you gave it another half a second it would load and the tooltip would be in the right spot. i don't know that there's anything we can do here so i'm inclined to mark this as a won't fix

**Comment by aaronrbenson** [comment]
Yeah, agreed. I was also seeing some errant behavior with what appeared to be a bad add-on build. Closing.
