### ISSUE TITLE
Trending Highlights use the wrong icon

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-stream#962]
Per https://trello.com/c/TQcZZhMe/19-i-want-to-have-popular-content-recommended-to-me-so-that-i-can-learn-about-new-things-happening-on-the-web, we should use the Pocket icon (or something):

![i_want_to_have_popular_content_recommended_to_me_so_that_i_can_learn_about_new_things_happening_on_the_web_on_activity_stream___trello](https://cloud.githubusercontent.com/assets/557895/17073433/aebb7522-5025-11e6-8fe8-4f16e657d753.png)

Here's what the icon looks like currently:

![new_tab](https://cloud.githubusercontent.com/assets/557895/17073448/d3388fca-5025-11e6-97e9-c4458865fc3a.png)

**Comment by sarracini** [comment]
The spec was changed - these were the icons UX gave me. Thanks Peter, I'm closing this
