### ISSUE TITLE
Add experiments interface for about:config to force enable experiments

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#964]
We need to add a graphical UI for interacting with experiment settings.  It should read experiments.json and expose checkboxes for each one which, when checked, force enable that experiment, so that it's easier to interact with experiments through the UI rather than having to build the addon from scratch.

**Comment by oyiptong** [comment]
We don't need to create a new GUI. We can create a pref that we can flip. Testers only need to go to `about:config`, search for the pref name and flip it.

**Comment by edmoz** [comment]
from discussion: the experiment framework should look for a pref in about:config prior to client side enablement.
