### ISSUE TITLE
Update highlights with new context information

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-stream#965]
We'd like to update the context information for Highlights, including:

- new icons
- new labels
- new timestamp format

Some of the types are not yet implemented (e.g. synced)

See for details:
https://trello.com/c/0TZHVlQQ/38-i-want-to-understand-where-my-highlighted-content-is-coming-from

**Comment by k88hudson** [comment]
@bryanbell can you add the icons in here?

**Comment by bryanbell** [comment]
https://mozilla.invisionapp.com/static-signed/live-embed/22240415/170871141/13/latest/olEuW2AoOkLoJ59jcGA1rjToE0o4ObG8hyaGfrnCY01hb1iIEqRCb9MDs9ULVCm2WkEL81uNlEkJuZGGSagg52CAlE/Highlight-Card-Design-Refactor-2x.png

**Comment by bryanbell** [comment]
Mockup here: https://invis.io/EN82I6OGS

**Comment by bryanbell** [comment]
Icon you need
[Archive.zip](https://github.com/mozilla/activity-stream/files/382656/Archive.zip)

**Comment by sarracini** [comment]
Fixed with #975 🎉 💃
