### ISSUE TITLE
Allow export of activities in Activity Streams 2.0 format

### ISSUE THREAD

**Issue by BigBlueHat** [mozilla/activity-stream#969]
[Activity Streams 2.0](https://www.w3.org/TR/activitystreams-core/) is soon to be entering the "Candidate Recommendation" phase at the W3C. It would be fabulous to have this extension provide a basic export function into that format.

Having that could enable export, sharing, and cross community organizing and importing of activities.

Cheers!
:tophat:

**Comment by oyiptong** [comment]
Needs trello ticket?

**Comment by BigBlueHat** [comment]
@oyiptong happy to make one if you point me to the place. :smile:

**Comment by sarracini** [comment]
Closing this, will re-open if this becomes an issue later
