### ISSUE TITLE
Bug 1289782 - "Bookmark" option is available for a previously bookmarked "Trending" Highlight

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#976]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1289782
<br>
[Affected versions]:
- Firefox 45 and up
- Activity Stream 1.1.1-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on (v1.1.1-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click on "+" to open a new tab.
3. Hover on a Trending item from Highlights, and then click on the "..." button.
4. Choose the "Bookmark" option.
5. Observe the "..." button options, from the same "Trending" Highilight item.

[Expected result]:
- The "Remove Bookmark" option is available for the bookmarked item.

[Actual result]:
- The "Bookmark" option is still displayed instead of "Remove Bookmark" in the context menu. 

[Notes]:
- A screen recording describing the issue was attached https://goo.gl/2ZRYKm.

**Comment by sarracini** [comment]
Closing this since we've disabled recommended cards
