### ISSUE TITLE
Bug 1289806 - Dismissed "Trending" Highlights items reappear after the browser is restarted

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#979]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1289806
<br>
[Affected versions]:
- Firefox 45 and up
- Activity Stream 1.1.1-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on (v1.1.1-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Click on "+" to open a new tab.
3. Dismiss a few Trending articles from Highlights.
4. Close and restart the browser.

[Expected result]:
- The dismissed "Trending" articles are no longer displayed after the restart.

[Actual result]:
- The dismissed "Trending" articles are redisplayed in Highlights after the restart.

[Notes]:
- If all "Trending" articles are dismissed, the next number of fetched articles is not constant. Sometimes I got just 1 new article, sometimes I got more, but always the number was lower than the ones firstly displayed. 
- Also, when second batch is displayed, some of the articles are repeated even if they were previously dismissed.
- This issue is reproducible 5/5.
- A screen recording describing the issue was attached https://goo.gl/k8nrac.

**Comment by sarracini** [comment]
we don't persist the blocked list of recommendations - when activity stream unloads we reset the block list to be empty

**Comment by oyiptong** [comment]
Sounds like a feature request. Needs a trello card?

**Comment by sarracini** [comment]
Closing this since we have disabled the recommended cards altogether
