### ISSUE TITLE
Drop TLD from domains (4 dot ellipsis seems extravagant)

### ISSUE THREAD

**Issue by bryanbell** [mozilla/activity-stream#980]
<img width="253" alt="image" src="https://cloud.githubusercontent.com/assets/228979/17184903/7da343e0-53e3-11e6-97f8-89bbe44f07eb.png">

just need to cut this down to the standard 3 dots ;)

**Comment by pdehaan** [comment]
I don't think this is a bug, I think you're just hitting the edge case of those two domains having a ".com" but the "com" isn't fitting and is truncating with a "...", giving you 4 dots.

Here's mine:

![new_tab](https://cloud.githubusercontent.com/assets/557895/17186257/56516ca8-53e9-11e6-9888-f8c12d95a6b6.png)

- `testpilot.firefo...` (3 dots)
- `ww1.forefox.co...` (3 dots)
- `jsbin.com` (full url)
- `reddit.com` (full url)
- `moz-activity-` (no dots -- links to https://moz-activity-streams-dev.s3.amazonaws.com/dist/latest.html)
- `search.yahoo....` (4 dots)

**Comment by Mardak** [comment]
The 4th dot is coming from the period of `.com` and the `…` is from `text-overflow: ellipsis`

**Comment by bryanbell** [comment]
details details ;) 

OK, maybe we should think about not showing the the ends of the domain. 

For example "reddit.com" would be "reddit", "search.yahoo...." would be "search.yahoo"

**Comment by pdehaan** [comment]
> For example "reddit.com" would be "reddit", "search.yahoo...." would be "search.yahoo"

Would that get confusing if I happen to browse reddit.com and reddit.ca and reddit.co.uk and then all 3 are shrunk to the generic "reddit" in my Top Sites?

**Comment by aaronrbenson** [comment]
We'll also want to remove the .com from the provider name on Highlights 
![screen shot 2016-12-29 at 1 11 43 pm](https://cloud.githubusercontent.com/assets/139451/21552614/6218bdf8-cdc8-11e6-9f41-c540cf08e52f.png)

**Comment by Mardak** [comment]
Fixed by #1377

**Comment by Mardak** [comment]
So, this should have been fixed in #1377 but it seems to have regressed?
