### ISSUE TITLE
awesome bar auto complete is slower when activity stream is installed

### ISSUE THREAD

**Issue by edwinwongsf** [mozilla/activity-stream#984]
Logging for Asa on high power Win Nightly with e10s off:
1.  when I type in say "f enter" to load facebook 

actual: it doesn't finish the autocomplete in time so it does a search on "f"

expected: should autocomplete quickly like when AS isn't installed.

**Comment by sarracini** [comment]
Closing this in favour of tracking awesomebar issues in #1458
