### ISSUE TITLE
Recommended items should link to the Pocket short url for that item

### ISSUE THREAD

**Issue by aaronrbenson** [mozilla/activity-stream#986]
Pocket's API returns a short link so that they are able to track click-through rates. It appears as though we're linking directly to the webpages.

**Comment by oyiptong** [comment]
We do not link to pocket's url shortener on purpose. This is to protect the privacy of our users

**Comment by oyiptong** [comment]
And we track click-through rates on our own telemetry system

**Comment by oyiptong** [comment]
After a conversation with @aaronrbenson and @nchapman I understand this is part of our agreement with pocket. It makes sense to give back on the interaction.

If a user found it valuable enough to click on a link, it seems to make sense for pocket to know about it so they can improve their system.

Note: they don't know about the impression, just the click

**Comment by jaredkerim** [comment]
The updates to the embedly proxy to send an additional 'pocket_url' field are being deployed, and then the client changes can take place.

**Comment by pdehaan** [comment]
Does the shortened Pocket URL still get routed through HTTP instead of HTTPS?
https://embedly-proxy.services.mozilla.com/v2/recommendations seems to have all HTTP URLs, which makes me v sad.

**Comment by pdehaan** [comment]
Do we have a Privacy Notice or Terms of Service for Activity Stream? It seems like we should be disclosing that Pocket will get a portion of your browsing data.

**Comment by jaredkerim** [comment]
@pdehaan Pocket will be adding HTTPS to their redirect URLs before we launch this update.

**Comment by edmoz** [comment]
We need to discuss PN and TOS updates.  Please hold on merging this fix.

**Comment by edmoz** [comment]
@aaronrbenson another UX note - I believe the status bar will show a "getpocket.co" URL vs article URL. Any thoughts on this?

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/activity-stream/issues/407

Maybe we should revisit adding a site to Highlights, although we'd still need to be careful to make sure users know that we're sending them to the site via Pocket servers.

Possibly the Twitter model where we show the site domain (ie: cnn.com), and hovering over the highlight/domain shows the unshortened URL as a tooltip/title, and we leave the status bar/href to show the shortened Pocket URL. Basically, we're sending you through a proxy, but the target site is cnn.com (so you can decide if you want to click or not).

**Comment by sarracini** [comment]
Closing this since we aren't showing recommendations anymore and the PR for this has been closed
