### ISSUE TITLE
Cohorts for Interaction Rate

### ISSUE THREAD

**Issue by emtwo** [mozilla/activity-stream#991]

**Comment by edmoz** [comment]
Big question to answer: are we increasing engagement? How many clicks (maybe: average per user, median) on activity stream UI, over time viewed by week.

**Comment by edmoz** [comment]
Can we put this at the top of the priority list.  This is our _leading metric._

**Comment by emtwo** [comment]
Cohort Interaction Rates:
https://plot.ly/~emtwo/83/

Cohort Interaction Counts:
https://plot.ly/~emtwo/85/

**Comment by jaredkerim** [comment]
Moving this to Horton to discuss the results.

**Comment by edmoz** [comment]
mtg scheduled to discuss this

**Comment by emtwo** [comment]
The notebook with the work can be found here:
https://gist.github.com/emtwo/3807e216bee055f2cbbdc64e38f160d2

The main conclusions from the meeting were:
1. The overall interaction rate regardless of cohort is quite stable, roughly 17%
2. While the raw number of interaction decreases over time per cohort, so do the number of sessions, keeping the rate stable (as stated in 1.) - This aligns with behaviour we see in our engagement ratio graphs

Will close this issue out now with these conclusions
