### ISSUE TITLE
Always asyncClose the metadatabase regardless of unload reason

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/activity-stream#992]
We need to make sure we disconnect and unload the database regardless of the unload reason otherwise this happens:

Warning: Sqlite connection 'metadata.sqlite#1' was not properly closed. Auto-close triggered by garbage collection.
Sqlite.jsm:79
Error: Warning: Sqlite connection 'metadata.sqlite#1' was not properly closed. Auto-close triggered by garbage collection.
Sqlite.jsm:88:20

Look here to fix this:

https://github.com/mozilla/activity-stream/blob/master/lib/main.js#L37

**Comment by ncloudioj** [comment]
How can I reproduce this issue?

"asyncTearDown" will close the database connection automatically if there is any. I wonder if the `app` is null in this case, so it won't enter this if branch here https://github.com/mozilla/activity-stream/blob/master/lib/main.js#L32
