### ISSUE TITLE
Bug 1290436 - Embedded video player is no longer displayed in Activity Stream

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/activity-stream#998]
via https://bugzilla.mozilla.org/show_bug.cgi?id=1290436
<br>
[Affected versions]:
- Firefox 45 and up
- Activity Stream 1.1.1-dev

[Affected Platforms]:
- All Windows
- All Mac OS X
- All Linux

[Prerequisites]:
- Latest Activity Stream add-on (v1.1.1-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Play a video from YouTube or Vimeo.
3. Click the Activity Stream button from the browser toolbar.
4. Refresh Timeline History page.

[Expected result]:
- The embedded video player is displayed in Timeline and the visited video can be played inside Activity Stream.

[Actual result]:
- The embedded video player is no longer displayed in Activity Stream 

[Notes]:
- The issue is also reproducible on New Tab.
- A screen recording describing the issue was attached https://goo.gl/kL4q5k.

**Comment by sarracini** [comment]
Closing this since we've removed timeline and recent activity
